### ISSUE TITLE
Dual-stack localhost binding

### ISSUE THREAD

**Issue by Yamakaky** [nicolargo/glances#1001]
Currently, `glances --bind localhost` only listen on ipv4. It should also listen on ipv6.

**Comment by nicolargo** [comment]
Nope, you can make it bind to IPv6:

    # glances -s --disable-autodiscover -B '::'
    Glances server is running on :::61209

Check:

    # netstat -an | grep 61209
    tcp6       0      0 :::61209                :::*                    LISTEN

**Comment by Yamakaky** [comment]
Yes, but will it also listen on ipv4? Also, the output should be `Glances server is running on [::]:61209`.

**Comment by nicolargo** [comment]
Nope, only IPv6...
With multi platform software, dual stack is a mess:

* http://code.activestate.com/recipes/578504-server-supporting-ipv4-and-ipv6/
* http://stackoverflow.com/questions/16762939/use-of-in6addr-setv4mapped-and-dual-stack-sockets

I will have a look on it for the next release.

Nicolas

**Comment by TheQue42** [comment]
Is this issue dead and forgotten? Do I need to run dual instances to bind glances to BOTH ipv4 and ipv6? Configuring access to a running glances server I will normally want to use a DNS name, that has both A and AAAA records.

But supplying -B :: only binds for IPv6, and -B 0.0.0.0 only binds for v4. And supplying both will just use the last parameter on the command line it seems?
