### ISSUE TITLE
interrupts and usb_fiq

### ISSUE THREAD

**Issue by DJJo14** [nicolargo/glances#1007]
Glances v2.8 with psutil v5.0.1
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
i get 
> Traceback (most recent call last):
>   File "/usr/local/bin/glances", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 232, in main
>     start_server(config=config, args=args)
>   File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 168, in start_server
>     args=args)
>   File "/usr/local/lib/python2.7/dist-packages/glances/server.py", line 210, in __init__
>     self.server.register_instance(GlancesInstance(cached_time, config, args))
>   File "/usr/local/lib/python2.7/dist-packages/glances/server.py", line 127, in __init__
>     self.stats.update()
>   File "/usr/local/lib/python2.7/dist-packages/glances/stats_server.py", line 46, in update
>     super(GlancesStatsServer, self).update()
>   File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 164, in update
>     self._plugins[p].update()
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 805, in wrapper
>     ret = fct(self, *args, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 814, in wrapper
>     ret = fct(*args, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 70, in update
>     self.stats = self.irq.get()
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 141, in get
>     return self.__update()
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 202, in __update
>     current_irqs = self.__sum(line)
>   File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 181, in __sum
>     return sum(map(int, splitted_line[1:(self.cpu_number + 1)]))

ValueError: invalid literal for int() with base 10: 'usb_fiq'

because " cat /proc/interrupts" looks like

>            CPU0       CPU1       CPU2       CPU3
>  16:          0          0          0          0  bcm2836-timer   0 Edge      arch_timer
>  17:  291561558  457022183  272779568  356729741  bcm2836-timer   1 Edge      arch_timer
>  23:    1034511          0          0          0  ARMCTRL-level   1 Edge      3f00b880.mailbox
>  24:          2          0          0          0  ARMCTRL-level   2 Edge      VCHIQ doorbell
>  39:          1          0          0          0  ARMCTRL-level  41 Edge
>  46:          0          0          0          0  ARMCTRL-level  48 Edge      bcm2708_fb dma
>  48:   30738158          0          0          0  ARMCTRL-level  50 Edge      DMA IRQ
>  50:          0          0          0          0  ARMCTRL-level  52 Edge      DMA IRQ
>  59:       4629          0          0          0  ARMCTRL-level  61 Edge      serial
>  62: 1719580858          0          0          0  ARMCTRL-level  64 Edge      dwc_otg, dwc_otg_pcd, dwc_otg_hcd:usb1
>  79:          0          0          0          0  ARMCTRL-level  81 Edge      3f200000.gpio:bank0
>  80:          0          0          0          0  ARMCTRL-level  82 Edge      3f200000.gpio:bank1
>  86:   11102171          0          0          0  ARMCTRL-level  88 Edge      mmc0
>  87:       4871          0          0          0  ARMCTRL-level  89 Edge
>  92:       3830          0          0          0  ARMCTRL-level  94 Edge      mmc1
> FIQ:              usb_fiq
> IPI0:          0          0          0          0  CPU wakeup interrupts
> IPI1:          0          0          0          0  Timer broadcast interrupts
> IPI2:   54830555   59228210   61527945   56371382  Rescheduling interrupts
> IPI3:         40         39         51         45  Function call interrupts
> IPI4:          7          8          2          1  Single function call interrupts
> IPI5:          0          0          0          0  CPU stop interrupts
> IPI6:          0          0          0          0  IRQ work interrupts
> IPI7:          0          0          0          0  completion interrupts

possible solution, add tease lines of code in File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_irq.py", line 181

>         if len(splitted_line) < self.cpu_number + 1:
>             return 0

**Comment by escproxy** [comment]
Experienced the same problem. Used supplied fix and it worked. +1

**Comment by nicolargo** [comment]
Corrected in the develop branch.

Thanks for the patch @DJJo14
