### ISSUE TITLE
Enable docker plugin on Windows

### ISSUE THREAD

**Issue by fraoustin** [nicolargo/glances#1009]
Add docker information on glance run on windows

#### Versions

Glances v2.8 with psutil v5.0.1
Distributor ID: Windows 10
Description:  Microsoft Windows 10 Professional 64bits
Release: 10

Docker 1.13

#### Logs
On windows, we have not information on docker container
It's possible that get information on windows. On Docker for Windows, clients can connect to the Docker Engine through a named pipe: npipe:////./pipe/docker_engine, or TCP socket at this URL: http://localhost:2375. (https://docs.docker.com/docker-for-windows/faqs/)

I propose to amend  glances/glances/plugins/glances_docker.py , in function _connect_old

`if WINDOWS:
                url = 'npipe:////./pipe/docker_engine'
            else:
                url = 'unix://var/run/docker.sock'
            if version is None:
                ret = init_docker(base_url=url)
            else:
                ret = init_docker(base_url=url,
                                  version=version)`

I generate soon a pull request

**Comment by fraoustin** [comment]
add pull request https://github.com/nicolargo/glances/pull/1011

**Comment by nicolargo** [comment]
Thanks @fraoustin 

Merged in the DEVELOP branch.

Did you test it ?
Can we have a screenshot of the Web UI ?

**Comment by fraoustin** [comment]
Yes I did a test on 
Versions

Glances v2.8 with psutil v5.0.1
Distributor ID: Windows 10
Description: Microsoft Windows 10 Professional 64bits
Release: 10
Docker 1.12.13

The result is same that other platform (linux debian jessie)
