### ISSUE TITLE
Glances in Docker - Docker Stats Missing

### ISSUE THREAD

**Issue by ryanborstelmann** [nicolargo/glances#1014]
Running latest Docker image using the following `docker run` command:
`docker run -d --name=glances -p 61208:61208 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances`

The Docker stats that usually appear above system processes appears to be missing. I've tried pulling a new image, but that hasn't solved it. This has been running smoothly for a very long time, the docker stats just disappeared recently.

Version info:
> REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
nicolargo/glances    latest              82fc5ad6f90b        48 minutes ago      693.2 MB

**Comment by nicolargo** [comment]
Not reproduce on my system.

![selection_291](https://cloud.githubusercontent.com/assets/776747/22406548/66efd244-e655-11e6-8f3a-4a1797a77281.png)

with:

```
docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
nicolargo/glances     latest              82fc5ad6f90b        About an hour ago   693 MB
```

**Comment by ryanborstelmann** [comment]
Okay anything I can check to get this working? Running on the latest unRAID install. Let me know if I can provide you with any info you may need.

**Comment by nicolargo** [comment]
@ryanborstelmann Yes, try to add the debug option -d in the GLANCES_OPT="-w -d" and paste/bin us the contents of the log file (/tmp/glances*.log - inside the container)

**Comment by ryanborstelmann** [comment]
http://pastebin.com/SUPeLaXV

This jumps out at me near the bottom:

> 2017-01-30 13:05:57,448 -- DEBUG -- Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
> 2017-01-30 13:05:57,448 -- DEBUG -- No config file found
> 2017-01-30 13:05:57,452 -- DEBUG -- Docker API error (400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/version ("client is newer than server (client API version: 1.24, server API version: 1.22)"))
> 2017-01-30 13:05:57,453 -- DEBUG -- Try connection with Docker API version 1.22
> 2017-01-30 13:05:57,453 -- DEBUG -- Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
> 2017-01-30 13:05:57,453 -- DEBUG -- No config file found
> 2017-01-30 13:05:57,457 -- ERROR -- Docker API error (400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/version ("client is newer than server (client API version: 1.24, server API version: 1.22)"))
> 2017-01-30 13:05:57,457 -- DEBUG -- Docker plugin is disable because an error has been detected

**Comment by ryanborstelmann** [comment]
Solved :)

unRAID just needed to update their Docker version. All is well now. Thanks for the help @nicolargo, and keep up the great work!
