### ISSUE TITLE
Docker image does not work in web server mode!

### ISSUE THREAD

**Issue by victornoel** [nicolargo/glances#1017]
Hi,

I ran the following on my system:
```
docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances:stable
```

(notice I used the image tagged stable)

and now I see this in the container's log:
```
root@docker0:/home/linagora# docker logs pedantic_mayer
Bottle module not found. Glances cannot start in web server mode.
```

**Comment by nicolargo** [comment]
How do you install your Glances container ?
It seams that the Bootle lib client is not install inside your container.

**Comment by victornoel** [comment]
@nicolargo exactly my point :)

I just run the command line you provide in the README which uses your image:
```
docker.io/nicolargo/glances:stable
```

**Comment by nicolargo** [comment]
Just found an issue on the stable:

    Glances 2.8 does not provide the extra 'WEB'

Try the build latest build instead of the stable one. 

    docker.io/nicolargo/glances:**latest**

**Comment by victornoel** [comment]
@nicolargo ok, thanks!

**Comment by nicolargo** [comment]
Dockerfile change.
