### ISSUE TITLE
Can't export data to a CSV file in Client/Server mode

### ISSUE THREAD

**Issue by F4b1an** [nicolargo/glances#1023]
#### Description

I start the glances server successfully with the line:

`glances -s`

And when I try to connect to it and generate a CSV file on the client PC with the information of the server, the system crash. I'm using the following command:

`glances -c IP_SERVER --export-csv /path/to/file/name.csv`

Is it possible to do what I want to do? Am I doing something wrong?

Thanks in advance!

#### Versions

* Glances (glances -V): 2.8
* PSutil (glances -V): 5.1.1
* Operating System (lsb_release -a): Ubuntu 14.04 LTS

**Comment by nicolargo** [comment]
Corrected in the DEVELOP branch. Can you test it on your side ?

**Comment by nicolargo** [comment]
Tested.

**Comment by F4b1an** [comment]
I upgraded Glances and tried again, but I didn't succeed.

Versions:
Glances (glances -V): 2.8
PSutil (glances -V): 5.1.2

**Comment by nicolargo** [comment]
It's in the develop branch, please read the Wiki to test and install it

**Comment by F4b1an** [comment]
Many thanks. It works!

**Comment by F4b1an** [comment]
Many thanks. It worked!

**Comment by nicolargo** [comment]
Perfect. Thanks for your support.

**Comment by nicolargo** [comment]
Ok Glances 2.8.1 is available !

**Comment by F4b1an** [comment]
Great! I've just tried to upgraded it and I had a problem with python's version. So, I installed python 3.5 and tried again, but I couldn't. When you install Python 3.5 the command's name that appear is "python3.5" instead of "python", I believe the problem is there. Thanks!
