### ISSUE TITLE
Pip install not working for latest version of Glances (>= 2.8.1) on Ubuntu for Python v2.7.6

### ISSUE THREAD

**Issue by jakesherman** [nicolargo/glances#1028]
Apologies if this issue is known, I searched recent open/closed issues for this and didn't find anything. 

I often install `glances` on Ubuntu 14.04.2 LTS EC2 instances running Python 2.7.6. I have never run into this issue before, even though I last installed `glances` successfully only a few days ago. See the error below:

```bash
sudo pip install glances

Downloading/unpacking glances
  Downloading Glances-2.8.2.tar.gz (5.5MB): 5.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/glances/setup.py) egg_info for package glances
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/glances
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

I have confirmed that this is an issue with the latest version of `glances` by successfully installing an earlier version via

```bash
sudo pip install glances==2.8
```

2.8.2 and 2.8.1 are not working, earlier versions are working.

Thank you so much! I love `glances`.

**Comment by nicolargo** [comment]
Upgrading pip solves the issue:

    pip install --upgrade pip

**Comment by jakesherman** [comment]
Thank you!
