### ISSUE TITLE
Detect if the current instance is an AWS EC2 instance.

### ISSUE THREAD

**Issue by angelopoerio** [nicolargo/glances#1029]
Hi guys,
I would like to propose a new feature I was thinking about. I use glances on several Linux systems (bare metal and cloud ones), it would be very nice if the software could detect if the server I am monitoring is an EC2 instance or not.
It could be implemented in few lines of code: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html.
This would add a very great value to glances, because AWS is the most used IaaS.
The displayed informations could be: AMI-id, the amazon region where the server is etc ...

Regards,
Angelo

**Comment by nicolargo** [comment]
Interesting...

Can you be more precise concerning the information (and the corresponding Restful URL) useful for your need ?

Nicolas

**Comment by angelopoerio** [comment]
Yes,

I mean these informations. This is very useful if you work with multiple servers spanning in different AWS regions and availability zones.
They could be showed in a box in the main screen of glances

**Comment by angelopoerio** [comment]
Do you agree ?

**Comment by nicolargo** [comment]
Yes. I propose to display it in a line just bellow the system information:

Before:
```
dhcppc5 (CentOS Linux 7.3.1611 64bit / Linux 3.10.0-327.36.1.el7.x86_64) - IP 192.168.176.133/24 Pub 80.15.130.7                                                                                                     Uptime: 29 days, 23:51:49

Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz - 3.40/3.30GHz                                   CPU       9.9%  nice:     0.1%  ctx_sw: 12006               MEM     60.7%  active:    3.64G               SWAP      3.7%               LOAD    4-core
```

After:
```
dhcppc5 (CentOS Linux 7.3.1611 64bit / Linux 3.10.0-327.36.1.el7.x86_64) - IP 192.168.176.133/24 Pub 80.15.130.7                                                                                                     Uptime: 29 days, 23:51:49
AWS EC2 instance ami-a29943cb (us-east-1b)

Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz - 3.40/3.30GHz                                   CPU       9.9%  nice:     0.1%  ctx_sw: 12006               MEM     60.7%  active:    3.64G               SWAP      3.7%               LOAD    4-core
```

**Comment by angelopoerio** [comment]
So cool!
Be ready to receice a pool request :)

**Comment by nicolargo** [comment]
@angelopoerio Just implement a first version of the new "cloud" plugin in the latest commit of the DEVELOP branch:

- [x] collect the stats (threaded)
- [x] display the stats in the Curses interface
- [ ] display the stats in the web UI

@notFloran : Can you implement the Web UI ?

![selection_293](https://cloud.githubusercontent.com/assets/776747/22864859/457c0952-f159-11e6-8b76-16281b644c77.png)

Here is a sample of the the stat:

    {'ami-id': 'titi', 'region': 'toto'}

and the view:

```
[{'msg': 'AWS EC2', 'decoration': 'TITLE', 'optional': False, 'additional': False, 'splittable': False}, {'msg': ' instance titi (toto)', 'decoration': 'DEFAULT', 'optional': False, 'additional': False, 'splittable': False}]
```

**Comment by notFloran** [comment]
@nicolargo I'm on it

**Comment by angelopoerio** [comment]
@nicolargo cool! I will try it on some EC2 instances

**Comment by angelopoerio** [comment]
I run it on a test EC2, it looks great!
Just some suggestions:
* I would show instance-id rather than ami-id (instance-id is the id of the server, ami-id is the image used to boot up the machine)
* I would show instance-type too

@nicolargo what do you think?

**Comment by nicolargo** [comment]
@angelopoerio Ok, i will have a look on it.

**Comment by angelopoerio** [comment]
Other useful informations: the provisioning script used to boot up a new instance in AWS (but it can be applied to other provider too) is cloudinit (https://cloudinit.readthedocs.io/en/latest/).
If you check /var/log/cloud-init.log on any EC2 instance you can find a lot of useful informations

**Comment by nicolargo** [comment]
@angelopoerio Done for the instance-id and instance-type, can you test it ?

For the additional information hosted in the cloud-init.log file it is better to display it through the AMP plugin. For example, just add the following section inside your Glances configuration file:

    [amp_cloudinit]
    enable=true
    regex=.*init.*
    refresh=60
    one_line=false
    command=cat /var/log/cloud-init.log | head -4
    countmin=1

Replace command by the command that filter useful information...

**Comment by nicolargo** [comment]
Hi @notFloran can you add this new plugin to the Web UI ?

**Comment by angelopoerio** [comment]
Hi @nicolargo ,
it works well:
![glances_r](https://cloud.githubusercontent.com/assets/350096/23468061/12954194-fea0-11e6-91b5-ac68385ea214.png).
Just add "requests==2.13.0" in requirements.txt.

Note: I tested it with python3.3

**Comment by nicolargo** [comment]
b'foo' to foo corrected in the HEAD of the DEVELOP branch.

Add the requests as an optional pre-requirement:

    pip install glances[cloud]

@angelopoerio  a last test ?

**Comment by angelopoerio** [comment]
it works now @nicolargo

**Comment by nicolargo** [comment]
Nice ! Thanks @angelopoerio 

@notFloran Can you implement the web UI ? I want to release Glances 2.8.3 as soon as possible. Thanks !

**Comment by notFloran** [comment]
@nicolargo I'm on it

**Comment by notFloran** [comment]
@nicolargo Can you give me a json of the stats/views ?

**Comment by nicolargo** [comment]
@notFloran  Here it is:

$ curl http://0.0.0.0:61208/api/2/cloud
{"region": "R", "instance-type": "IT", "ami-id": "AMI", "instance-id": "IID"}

$ curl http://0.0.0.0:61208/api/2/cloud/views
{"region": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "instance-type": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "ami-id": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "instance-id": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}}

**Comment by asergi** [comment]
Due to this new plugin, Glances (or better the thread) hangs forever on exit, so I have to kill -9 the process.

**Comment by nicolargo** [comment]
@asergi Can not reproduce on my laptop (cloud plugin not used...). Can you investigate on your side ? Perhaps more information in debug mode ?

**Comment by asergi** [comment]
After a little debugging I found the culprit where it hangs forever:
```
 r = requests.get(r_url)
```
The following works for me:
```
try:
    r = requests.get(r_url, timeout=5)
except requests.exceptions.ConnectTimeout:
    logger.debug('Connection to {} timed out'.format(r_url))
    break
except Exception:
    ...
```

**Comment by nicolargo** [comment]
Thanks @asergi !

I will correct it and have a look on others threaded plugins.

**Comment by nicolargo** [comment]
Ok done in the latest commit in the DEVELOP branch.
