### ISSUE TITLE
Drives showing up weird - Screenshot attached

### ISSUE THREAD

**Issue by madvtak** [nicolargo/glances#1031]
Hi,

Something odd has happened, my drives show up...well odd. Take a look below. I tried to stop and start glances again but it still shows up weird. Any idea how to fix this? 

![filesys](https://cloud.githubusercontent.com/assets/18261123/22851996/6f838db0-efe7-11e6-80e4-e0eb0431cb11.png)

I've attached a screenshot to my other server that is working correctly. 

![workingfilsys](https://cloud.githubusercontent.com/assets/18261123/22852005/d923dd1a-efe7-11e6-88ab-ca4390836b43.png)

**Comment by nicolargo** [comment]
Please [follow the template](https://github.com/nicolargo/glances/blob/master/.github/ISSUE_TEMPLATE.md) when you add an issue... We need more information about your configuration.

**Comment by madvtak** [comment]
Sorry

`Glances v2.8.2 with psutil v5.1.3`

OS: macOS 10.12.3

**Comment by notFloran** [comment]
I think I reproduced the bug : when I plug my iPhone, I have the same bug in the webUI.

<img width="793" alt="capture d ecran 2017-02-12 a 20 04 25" src="https://cloud.githubusercontent.com/assets/523981/22865187/2787541e-f15f-11e6-9aaf-4b7b117c2e8b.png">

 In the curse interface the mount point name is cut when is too long, we forgot that in the web UI.
