### ISSUE TITLE
Can't install with python 3.4

### ISSUE THREAD

**Issue by fraoustin** [nicolargo/glances#1032]
installation of glances by pip with python 3.4 is not possible

#### Description

I run pip3 install glances and the result is

```
Collecting glances
  Using cached Glances-2.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
```

#### Versions

* Glances (glances -V): 2.8.2
* PSutil (glances -V): 5.0.1
* Operating System (lsb_release -a): 

- Distributor ID:	Debian
- Description:	Debian GNU/Linux 8.6 (jessie)
- Release:	8.6
- Codename:	jessie

**Comment by fraoustin** [comment]
the problem is in setup.py

` 'folders:python_version<"3.5"': ['scandir'],`

If I comment the line, the install is ok and glances work

**Comment by nicolargo** [comment]
Nope the problem is not the setup.py file, the problem is your Pip version.

Please upgrade it:

    sudo pip install --upgrade pip

Then:

    sudo pip install glances

**Comment by C-Duv** [comment]
Had the same issue (got _Invalid environment marker: python_version<"3.5"_ when running `pip install glances`) on Debian v8.7 with Python v2.7.9 and v3.4.2 and `pip` v1.5.6.
I ran `pip install --upgrade pip setuptools` (only upgrading `pip` did not suffice) as advised in #1034 and then `pip install glances` worked (installed Glances v2.8.8 with psutil v2.1.1).
