### ISSUE TITLE
Can't install on 3.5.x or 2.7.12

### ISSUE THREAD

**Issue by hawkeyej** [nicolargo/glances#1034]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

Can't install glances due to this failure:

```
Collecting glances
  Using cached Glances-2.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in Glances setup command: Invalid environment marker: python_version<"3.5"
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0_YCQE/glances

```
Same results with pip versions 6.1.1 and 9.01

glances 2.8 installs fine. The problem starts with 2.8.1

**Comment by asergi** [comment]
`pip install -U pip setuptools`
