### ISSUE TITLE
Sort process list by network I/O

### ISSUE THREAD

**Issue by rmenessec** [nicolargo/glances#1037]
#### Description

Please add the ability to sort by network I/O. This is an important requirement for me. Having the ability to apply at least simple pcap filters (ex: 'tcp && ! port 22') would also be appreciated.

#### Versions

N/A; feature request

#### Logs

N/A; feature request

**Comment by giampaolo** [comment]
I'm not aware of any OS which provides this info. You can get IO counters but that includes both network and disk I/O, which is not what you want.

**Comment by rmenessec** [comment]
First: Windows—or [Process Hacker](http://processhacker.sourceforge.net/), at least—**can** do this, at least as of Win7SP1 (what I'm using). However this works, it doesn't seem to even use much CPU time on heavily-loaded systems.

Second, if Linux doesn't provide a way to get network statistics for a process directly, then that just means handling two steps: iftop can certainly provide per-session statistics. lsof or netstat can tell me what owns the session... so long as it isn't closed by the time I get the process / session information manually. This could probably be accomplished with netfilter accounting as well, although it would be more complicated. There's probably another method or two that's just not occurring to me right now.

All I'm asking is for Glances to automate pairing session / socket statistics with the owning processes.

NOTE: Even being able to show packets per second per process or similar would be helpful. Or Ethernet frames per second per process; I'm not picky. Precision would be good, but what I really need is fast, relative, reasonably accurate measures.

**Comment by giampaolo** [comment]
By "not possible" I meant not possible natively. AFAIK tools like nethogs on Linux (UNIX?) use libpcap which has 2 limitations: 1) requires root access 2) it's an extra dependency requiring additional headers (`apt-get install libpcap-dev`).
With py-libpcap (or whatever it's called) + psutil it would technically be possible though.
I expect libpcap to listen on the network interface, call a callback function for every TCP or UDP packet transmitted (with payload length) then map packet's ip:port to `psutil.net_connections()` which provides both both `(ip, port) and pid information.

**Comment by giampaolo** [comment]
> First: Windows—or Process Hacker, at least—can do this, at least as of Win7SP1 (what I'm using). 

I can't find it. Where is this information shown?

**Comment by rmenessec** [comment]
> I can't find it. Where is this information shown?

@giampaolo I don't know where it's documented, if that's what you're asking. Here's a screenshot of Process Hacker from a Windows VM. Some of these columns, including the network, bitness, and DEP / CF Guard / ASLR columns are not shown by default; they must be selected from a list of available columns.

![virtualbox microsoft puppy puncher](https://cloud.githubusercontent.com/assets/425616/23049250/d775fc32-f488-11e6-8fef-fb3f1aa0104a.png)

Again, I don't know the mechanism. I'm just pointing out that it can be done. I've seen this done with other Windows Task Manager replacements in the past as well.

Frankly, Process Hacker is one of the few things I miss about Windows. I've never seen a comparable utility in UNIX.

**Comment by nicolargo** [comment]
Related to issues:

* Adding TCPTrack like funtionality #870
* Add process network connection information #529

All tests i have done conclude with the same result: "too much CPU consumption for the value added by the feature."

**Comment by nicolargo** [comment]
Hi @rmenessec / @giampaolo 

i just write a peace of Python code:

https://github.com/nicolargo/pythonarena/blob/master/psnettop/psnettop.py

which:

1. listen from all Ethernet packets
2. filter TCP and UDP packets (do not take ARP or ICMP packets into account)
3. check if it is a incoming or outgoing packet (thanks to the psutil.net_connections())
4. add the size (with header) to a dict (the key is the pid)

It works (but had to manage the fact that a PID can be reused by another process).

But... the CPU consumption is high...

![workspace 2_294](https://cloud.githubusercontent.com/assets/776747/23333274/2976dea0-fb89-11e6-87be-06186b24c244.png)

The CPU is consumed in the psutil.net_connections() function (called every time a packet is received). Perhaps an optimization can be done... Any idea is welcome.

**Comment by nicolargo** [comment]
An optimized version of the script is available here:

https://github.com/nicolargo/pythonarena/blob/master/psnettop/psnettop2.py

What's new ?

1) the sniffer is threaded
2) the psutil.net_connections() is only called every refresh (3 seconds)
3) yes we steel need to run it as root...

but the CPU consumption is "acceptable" (on my Laptop: ~ 3% if there is no flow and 5% with some internet flows).

**Comment by Simplenuity** [comment]
I only came here to check whether that feature has already been suggested/requested for this outstanding piece of software.

On Linux systems this would be a killer feature to have within such a comprehensive monitoring tool.

Currently I only know of nethogs (mentioned above) to monitor network i/o by processes in real time. Anything else (mentioned above) is a tedious, more step process and not real time.

As root permission and extra dependencies are required, it would surely help to have this feature optional, meaning, if the dependencies are not installed and/or glances is not run as root, glances doesn't even try to display that info.

Thanks for your consideration and work on this feature!

**Comment by nicolargo** [comment]
This feature will not be implemented in Glances because it need root rights. Too much risk to run Glances in root mode because of action feature.

Perhaps a new command line should could be created for this feature.

**Comment by Simplenuity** [comment]
Thanks for taking the time to consider and respond.

**Comment by fzyzcjy** [comment]
hi is there any updates? thanks!

**Comment by nicolargo** [comment]
@fzyzcjy In Glances 4.4.1 just click on SHIFT + LEFT to move the process list sort to network IO:

https://github.com/user-attachments/assets/fce5e2d4-4da7-4bd2-b95a-5c26d6090b3d
