### ISSUE TITLE
glances --export-influxdb starts webserver?

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#1038]
#### Description

Trying to export to influxdb, however, it starts the webserver instead?

CMD output:

C:\WINDOWS\system32>python3.6 -m glances --export-influxdb
Glances web server started on http://0.0.0.0:61209/

#### Versions

Glances v2.8.2
psutil v5.1.3
Python 3.6
Windows 10P

**Comment by nicolargo** [comment]
Bug confirmed. On Windows OS, the Web mode is used by default. Actually the Web mode is not compatible with the --export-<foo> options.

Proposal, on Windows OS, when a --export-<foo> function is detected, Glances will be ran in "quiet" mode.

**Comment by seanvree** [comment]
@nicolargo  - Right, that's what I thought. 

Any other way to run the --export-influxdb then?

**Comment by nicolargo** [comment]
Corrected in the HEAD of the DEVELOP branch.

Will be release in Glances 2.8.3.

**Comment by asergi** [comment]
9cee73212a4db1b902bae63b32d44e53b24571cf breaks tests on Windows: https://ci.appveyor.com/project/nicolargo/glances/build/1.0.319/job/7l9s6lxfjt9haa4x.
The config part is already fixed in 257a5a3d7b3f61b8d3a84697cde2f7bf8d85bc34.
