### ISSUE TITLE
Docker Web Password

### ISSUE THREAD

**Issue by kikaida** [nicolargo/glances#1040]
Does --password work with the docker version? I've tried running:

`docker run -d --name=dookie --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w --password" -v /home/dookie/glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances`

But I'm just getting these errors:

`EOFError /usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal. passwd = fallback_getpass(prompt, stream) Warning: Password input may be echoed. Define the Glances server password (glances username): Traceback (most recent call last):`

I've modified the glances.conf for my passwords.

**Comment by nicolargo** [comment]
Hi @kikaida 

the first time Glances server is ran with the --password option, it asks for the password (twice) and if the password should be stored (hash) in a file (~/.config/glances/glances.pwd by default).

If you want to add a password to your Docker Glances server, i propose to try the following procedure:

1) outside the container, run Glances with the following options:

```
$ glances -s --password
Define the Glances server password (glances username): <enteryourpassword>
Password (confirm): <enteryourpassword>
Do you want to save the password? [Yes/No]: Yes
Announce the Glances server on the LAN (using 192.168.0.12 IP address)
Glances server is running on 0.0.0.0:61209
```
2) CTRL-C to exit from the Glances server

3) Run the container using the local glances.pwd file:

```
docker run -d --name=dookie --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w --password" -v /home/dookie/.config/glances/glances.pwd:/root/.config/glances/glances.pwd -v /home/dookie/glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
```

Not tested but should works...

**Comment by kikaida** [comment]
@nicolargo 

Your solution worked. Thanks!

**Comment by nicolargo** [comment]
I will add a reference to the procedure in the documentation.

**Comment by altsalt** [comment]
Hi, it appears that this documentation never made it in. I've just opened a [PR](https://github.com/nicolargo/glances/pull/1777) to fix that.
