### ISSUE TITLE
Glances into Docker and network stats

### ISSUE THREAD

**Issue by Nesousx** [nicolargo/glances#1041]
Hi,

Not sure if this is the right place to ask, but I'll go.

#### Description

I am running Glances into Docker. I export all the data to influxdb and visualize it vi Grafana. All of them inside docker.

At first, I faced a small issue, where I couldn't get information about all my host filesystems from the Glances container.

Then I found a small trick to fix it. In order to get the missing filesystems data to show inside the container, I created fake directory (eg. /home/nesousx/fake) on the desired host filesystem, which I mount inside the Glances container. This way, I can access the disk usage of that filesystem inside the Glances container.

However, i can't find a way to get stats from the host network interface. The only network interfaceI can see from within the Glances container is the interface from the Docker container... which is not really relevant.

If anyone has any idea, in order to achieve this, I am all ears.
Thanks in advance :)

#### Version
Doesn't seem to be related to any version / OS But more likely Docker specific.

#### Additional info

Will add my docker-compose file later.

**Comment by nicolargo** [comment]
Hi @Nesousx ,

Glances 2.5 or higher already display the network stat( Rx/s and Tx/s): http://glances.readthedocs.io/en/stable/aoa/docker.html

Do you need additional information ?

**Comment by Nesousx** [comment]
Salut Nicolas, 

Sauf erreur de ma part, impossible de voir l'interface de l'hôte dans le container. Je vois uniquement celle de docker propre au container. Du coup, c'est pas très utile...

**Comment by nicolargo** [comment]
I understand... but i am not realy sure that this information is available inside the container...

**Comment by Nesousx** [comment]
For the filesystems, it was more or less the same issue. I couldn't see them inside the container unless I mounted a folder a folder from that said filesystem inside the container. 

Now, I am wondering if something similar can be done with the interface. I'll keep looking and let you know if I find anything. Maybe in the meantime we can leave this "issue" open and see if someone has a fix.

Thanks for your time, anyway :)

**Comment by nicolargo** [comment]
Ok if another "Glances inside Docker" user have the information please let us known...

**Comment by craSH** [comment]
Hi @nicolargo -

> Glances 2.5 or higher already display the network stat( Rx/s and Tx/s): http://glances.readthedocs.io/en/stable/aoa/docker.html

I'm trying to determine if I have a new issue or if it is related to this one. I never see anything other than 0 for network stats (RX/S and TX/S) when running glances within Docker (in the same setup I referenced in #1791) - is there something special that must be done to make per-container network stats work? `docker stats` does properly show network statistics per-container, on the same host.

**Comment by RazCrimson** [comment]
@Nesousx Running the container with `host` network_mode should do that?

An example compose config is present here: https://github.com/nicolargo/glances/issues/1350#issuecomment-628889568

**Comment by joshtbernstein** [comment]
@RazCrimson Is `privileged: true` still needed? What does that affect here?

**Comment by RazCrimson** [comment]
Solution:

For docker: Use the option `--network host`

For docker-compose: Specify `network_mode: host` for the glances container.
