### ISSUE TITLE
Odd behavior running Glances behind Nginx reverse proxy with nginx listening on non standard port

### ISSUE THREAD

**Issue by lgromb** [nicolargo/glances#1042]
Hi, 

Glances is running quite well on the box I want to monitor, but nginx seems to have some kind of problem rewriting the URLs for Chrome to understand it correctly.

My setup is as follows : Nginx is locally listening on port 2443, and sslh is redirecting 443 requests to nginx when it's called from a web browser, and to port 22 when it's from an ssh connection.

Sometimes, when I tinker too much on my nginx conf file, URLs got rewritten with https://my.domain.com:2443/... which should not occur if the redirections are correctly done.

That's what's happening with Glances, the base URL is correct but every ressources (css for example) Chrome tries to retrieve, it tries on port 2443.

I'm pretty sure it's a nginx conf issue, but if someone can shed light on this for me that would help me understand quite some things related to regex in nginx conf files :)

Here's the bloc for glances (taken from the wiki)

```
location /glances/ {
        rewrite /glances/(.*) /$1 break;
        proxy_pass http://192.168.1.98:61208;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; #doesn't do anything?
}
```

and on my / location 

```
location = / {
        if ($http_referer ~ "^https?://[^/]+/glances"){
                rewrite ^/(.*) https://$http_host/glances/$1 redirect;
        }
```

I guess some nginx expert will sort this in a blink of an eye but I'm lost 🗡

**Comment by lgromb** [comment]
Okay a little mort search from myself has been helpful.

To avoid this kind of behavior you should add

`port_in_redirect off;`

to the server block, and that's enough ! FYI.

**Comment by nicolargo** [comment]
@lgromb Wiki updated: https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

Thanks !

**Comment by return42** [comment]
@lgromb : what glance version did you use?

**Comment by evitor** [comment]
I'm having the same problem with OpenLiteSpeed, I use cyberpanel and to make the reverse proxy work I should add the rewrite code bellow(but it freezes on the logo inicial page that says "an eye on your system":

```
### Rewrite Rules Added by CyberPanel Rewrite Rule Generator

RewriteEngine On
RewriteCond %{HTTPS}  !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
REWRITERULE ^(.*)$ HTTP://glances/$1 [P]

### End CyberPanel Generated Rules.
```

and add this to the file: /usr/local/lsws/conf/httpd_config.conf

```
extprocessor glances {
  type                    proxy
  address                 127.0.0.1:61208
  maxConns                100
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}
```

The wiki page dont have the custom conf to OpenLiteSpeed, anyone can help-me? Thanks!
