### ISSUE TITLE
Glances crash on RPi 1 running ArchLinuxARM

### ISSUE THREAD

**Issue by kevlar1818** [nicolargo/glances#1046]
This bug yields the same exact crash as #1007, but is not yet fixed for the original Raspberry Pi (B), running ArchLinuxARM. I think this is because the RPi 1 has only one CPU, so the following bugfix did not cover the one-CPU case:

Line 181 in glances_irq.py:
``` py
if len(splitted_line) < self.cpu_number + 1:
    return 0
```

**Comment by nicolargo** [comment]
Could you please paste the result of:

cat /proc/interrupts

Thanks

**Comment by nicolargo** [comment]
Should be corrected in the last commit of the DEVELOP branch.

Can you test it ?

**Comment by kevlar1818** [comment]
Sorry for the late response, and thanks for the quick fix! I will test it in a few hours and report back.

**Comment by kevlar1818** [comment]
It is fixed on my Raspberry Pi 1 running ArchLinuxARM (not Raspbian, as the code comment implies). I image the distro does not affect the bugfix, however.

**Comment by nicolargo** [comment]
Thanks for the test !
