### ISSUE TITLE
Cloud plugin error: Name 'requests' is not defined

### ISSUE THREAD

**Issue by adrianovieira** [nicolargo/glances#1047]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

- run `glances` and you will see this error
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/glances/plugins/glances_cloud.py", line 156, in run
    r = requests.get(r_url, timeout=3)
NameError: name 'requests' is not defined
```

#### Versions

* Glances (glances -V): 2.8.4
* PSutil (glances -V): 5.2.0
* Operating System (lsb_release -a):
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:	7.3
Codename:	Maipo
```

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

```
2017-03-10 15:06:02,562 -- INFO -- Start Glances 2.8.4
2017-03-10 15:06:02,562 -- INFO -- CPython 3.4.5 and PSutil 5.2.0 detected
2017-03-10 15:06:02,566 -- INFO -- Start standalone mode
2017-03-10 15:06:03,819 -- INFO -- Stop Glances
```

**Comment by nicolargo** [comment]
Forget to catch this exception if requests is not install on your system.

Workaround, install requests:

    # pip install requests

**Comment by nicolargo** [comment]
Release in Glances 2.8.5.
