### ISSUE TITLE
Including battery and AC adapter health in Glances

### ISSUE THREAD

**Issue by rmenessec** [nicolargo/glances#1049]
#### Description

Please add critical extended battery (ACPI / laptop) information to Glances in order to monitor battery health. This information should include—where available—voltage _versus_ design voltage and battery capacity _versus_ design capacity. This should be available as both raw data and as calculated percentages. ACPI battery information provided can vary based on manufacturer, kernel revision, and so forth. Where possible, the battery manufacture date and/or calculated age should be displayed if the data are available to Glances. Similarly, temperature (if available) and voltage / voltage _versus_ design voltage should be provided.

It may be desirable to evaluate the temperature based on well-known lithium-ion safe operating temperature ranges. Providing informational messages about charging at suboptimal temperatures would be welcome. Based on multiple sources, the lithium-cobalt chemistry used in most common laptop batteries should not be charged at temperatures near the end of the range 0-45°C to avoid reducing the battery lifespan. Similarly, discharge temperatures near or above 60°C appear to be best avoided. Lithium-cobalt chemistry becomes dangerous at about 130°C, and charge management ICs in batteries should normally disable the battery well before this point; however, advance warnings to the user would be beneficial, perhaps around 90°C.

Finally, please provide the AC adapter state.

#### Versions

n/a

#### Logs

All of the necessary information appears to be available from sysfs on all of the portable Linux systems I've tested. Here's some example output, and then nearly the same information as formatted by the upower(1) tool:
```
$ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Unknown
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=12221000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=7800000
POWER_SUPPLY_CHARGE_FULL=7597000
POWER_SUPPLY_CHARGE_NOW=7301000
POWER_SUPPLY_CAPACITY=96
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=DELL PT43485
POWER_SUPPLY_MANUFACTURER=Samsung SDI
POWER_SUPPLY_SERIAL_NUMBER=[REMOVED]
```
```
$ upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               Samsung SDI
  model:                DELL PT43485
  serial:               [REMOVED]
  power supply:         yes
  updated:              Fri 10 Mar 2017 04:29:14 PM EST (71 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              81.0411 Wh
    energy-empty:        0 Wh
    energy-full:         84.3267 Wh
    energy-full-design:  86.58 Wh
    energy-rate:         0.0111 W
    voltage:             12.221 V
    percentage:          96%
    capacity:            97.3974%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'
```
AC adapter information is available from several sources, again including sysfs:
```
$ cat /sys/class/power_supply/AC/online
1
```
```
$ acpitool -a
  AC adapter     : online
```

**Comment by nicolargo** [comment]
@rmenessec thanks for the proposal. I am not sure that Glances is the best place to display those very specifics information. Glances aims at providing the maximum information in a minimal of space...

Nevertheless, i write a specific Python lib to programmaticaly retreive all the BAT RAW data: https://github.com/nicolargo/batinfo

I let the issue open. If others users need this kind of stats, i will re-study it...

**Comment by kenguest** [comment]
is there any movement on this? :-)

**Comment by nicolargo** [comment]
It should be simple to add this feature because all the stats are available thanks to the Batinfo library. Nevertheless, i need to have your feed back concerning information displayed in the user interface.

The simple solution. just add the status as an additional information in the sensor plugin:

Before:

    BAT BAT0                         91%

After with a ↓ symbol for discharging:

    BAT BAT0 ↓                      91%
or
    BAT BAT0                         91%↓


or more advanced solution (need to check it is possible versus the space available in the plugin):

    Dell Li-ion BAT0               91%↓

**Annexe for dev**:

```
$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import batinfo
>>> b = batinfo.Batteries()
>>> b.stat
[{"path": "/sys/class/power_supply/BAT0", "name": "BAT0", "uevent": "POWER_SUPPLY_NAME=BAT0\nPOWER_SUPPLY_STATUS=Discharging\nPOWER_SUPPLY_PRESENT=1\nPOWER_SUPPLY_TECHNOLOGY=Li-ion\nPOWER_SUPPLY_CYCLE_COUNT=0\nPOWER_SUPPLY_VOLTAGE_MIN_DESIGN=7400000\nPOWER_SUPPLY_VOLTAGE_NOW=7674000\nPOWER_SUPPLY_CURRENT_NOW=1293000\nPOWER_SUPPLY_CHARGE_FULL_DESIGN=7440000\nPOWER_SUPPLY_CHARGE_FULL=5904000\nPOWER_SUPPLY_CHARGE_NOW=5689000\nPOWER_SUPPLY_CAPACITY=96\nPOWER_SUPPLY_CAPACITY_LEVEL=Normal\nPOWER_SUPPLY_MODEL_NAME=Dell\nPOWER_SUPPLY_MANUFACTURER=SIMPLO\nPOWER_SUPPLY_SERIAL_NUMBER=324", "charge_full_design": 7440000, "serial_number": 324, "technology": "Li-ion", "current_now": 1293000, "charge_now": 5689000, "present": 1, "manufacturer": "SIMPLO", "type": "Battery", "charge_full": 5904000, "capacity": 96, "cycle_count": 0, "voltage_now": 7674000, "status": "Discharging", "alarm": 0, "model_name": "Dell", "voltage_min_design": 7400000, "capacity_level": "Normal"}]
>>> b.stat[0].status
'Discharging'
```

What do you think @kenguest @mushi-nova @rmenessec ?

**Comment by kenguest** [comment]
I think the presence of a down-arrow to indicate a discharging battery, implies an up-arrow for one that's charging. 
It would be more obvious than leaving it out.

tbh I'm using glances for monitoring these system details via Home Assistant - as long as the battery/ac status is provided via API I'm happy.

**Comment by nicolargo** [comment]
Done in the develop branch.



For sure the entry point is available from the REST API:

![Selection_065](https://user-images.githubusercontent.com/776747/150672906-1ac670b5-3110-4eb3-ad4a-b3641000dbf3.jpg)
