### ISSUE TITLE
[WebUI] Improve WebUI for Windows 10

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1052]
#### Description

Glances WebUI for Windows 10 displays some non useful informations:

![windows 10 running - oracle vm virtualbox_298](https://cloud.githubusercontent.com/assets/776747/23835145/84931a26-0762-11e7-904b-cd2e8c8795e2.png)

1) CPU nice is not available and should not be displayed
2) MEM active and inactive are not available and should not be displayed
3) Process user name display the DOMAIN, if the user name contains a '\\' char, display only the string after the '\\' 

#### Versions

* Glances (glances -V): 2.8.8
* PSutil (glances -V): 5.2.0
* Operating System (lsb_release -a): Windows 10

@notFloran Can you take this one ?

**Comment by nicolargo** [comment]
@notFloran can you have a look ?

**Comment by nclsHart** [comment]
@nicolargo I'll take this one.

**Comment by nicolargo** [comment]
@nclsHart Any news ?

**Comment by nicolargo** [comment]
Merged thanks to @nclsHart !
