### ISSUE TITLE
Glances v2.8.7 issues with Curses UI on Android

### ISSUE THREAD

**Issue by ybudimirov** [nicolargo/glances#1053]
#### Description

Glances works but have issues with text: [Screenshot](https://cloud.githubusercontent.com/assets/12114831/23835256/cd7a7360-076c-11e7-84e2-142749fb2e57.png)

I have installed Glances via pip:
apt update
apt upgrade
apt install clang python python-dev
pip install glances

#### Versions

* Glances (glances -V): **Glances v2.8.7 with psutil v5.2.0**
* Operating System (there is no lsb_release): 
$ uname -a
Linux localhost 3.10.49-perf-g4714f7e #1 SMP PREEMPT Wed Oct 19 18:05:06 CST 2016 aarch64 Android

#### Logs

[glances-u0_a117.zip](https://github.com/nicolargo/glances/files/838055/glances-u0_a117.zip)

**Comment by nicolargo** [comment]
Strange... What is your operating system ?

**Comment by slamp** [comment]
3.10.49-perf-g4714f7e is a kernel used by Android

**Comment by ybudimirov** [comment]
> Strange...  What is your operating system ?

Android 5.1.1.

> 3.10.49-perf-g4714f7e is a kernel used by Android

Yes you are right.

**Comment by slamp** [comment]
By curiosity how did you install it ? Is it in an emulator ?

**Comment by ybudimirov** [comment]
No, it's real phone. 
Got root access on Android. Installed Termux app, Termux provides Shell and Apt package manager, after that:
apt update
apt upgrade
apt install clang python python-dev
pip install glances

That's all :)

**Comment by nicolargo** [comment]
Reproduced on my One Plus One:

![screenshot_20170315-215532](https://cloud.githubusercontent.com/assets/776747/23970655/da84230c-09ca-11e7-93c7-2fd26ad25ccd.png)

I think that the issue came from the Curse lib, i will double check if i limit the number of digit in the Curses interface...

**Comment by nicolargo** [comment]
Should be corrected in c41f74f

To be tested...

**Comment by ybudimirov** [comment]
Thank you!  You are rock! Will wait for new release.

**Comment by nicolargo** [comment]
@ybudimirov Glances 2.9 is out. Can you test it on your device ? A screenshot will be welcome ;)

**Comment by ybudimirov** [comment]
@nicolargo  **Thank you! :)**
Main window works without issues:
![screenshot_2017-03-28-12-25-59](https://cloud.githubusercontent.com/assets/12114831/24398809/81b9ab1e-13b3-11e7-933f-b2c7d8e1bd17.png)


Sorry for bothering, but if you open per CPU statistics(press 1), same(or similar) issue exist:
![screenshot_2017-03-28-12-26-08](https://cloud.githubusercontent.com/assets/12114831/24398823/8618ca50-13b3-11e7-8c76-28d23a754369.png)

**Comment by nicolargo** [comment]
@ybudimirov you do no bother me, you help me to improve Glances :)

I just open a news issue to track this problem: issue #1071
