### ISSUE TITLE
Sensor values don't refresh since psutil backend

### ISSUE THREAD

**Issue by DeltaDistribution** [nicolargo/glances#1061]
#### Description

For some reason the sensor values don't refresh since the psutil backend and remain at the values when starting glances.
Manually calling `psutil.sensors_temperatures()` does show the current (and updated) temperature state.
Same with `psutil.sensors_fans().`

#### Versions

* Glances (glances -V): 2.8.8
* PSutil (glances -V): 5.2.0
* Operating System (lsb_release -a): Arch Linux

#### Logs

Debug-log while stress testing the cpu in order to increase fan speed and temperature.
[http://pastebin.com/qV3qp3jN](http://pastebin.com/qV3qp3jN)

**Comment by crackleware** [comment]
quick fix: https://github.com/crackleware/glances/commit/62e952ae7cd3ce60880914121a416e505ce93e82

**Comment by nicolargo** [comment]
Corrected in commit dedc0258643a4a9c867387498eec38ebae5913cc in the DEVELOP branch.

Will be available in the next version.

Please note that on my Ubuntu system, i have a high CPU consumption if i enable the fans grab through PsUtil.
