### ISSUE TITLE
OSX: can't python setup.py install due to python 3.5 constraint

### ISSUE THREAD

**Issue by giampaolo** [nicolargo/glances#1064]
I've just bumped into this weird error while trying to install glances from sources:

```
osx:glances root# python setup.py install
error in Glances setup command: Invalid environment marker: python_version<"3.5"
```

I can work around it by modifying setup.py like this:

```
diff --git a/setup.py b/setup.py
index 28fe927..a671496 100755
--- a/setup.py
+++ b/setup.py
@@ -86,7 +86,6 @@ setup(
         'docker': ['docker>=2.0.0'],
         'export': ['bernhard', 'cassandra-driver', 'couchdb', 'elasticsearch',
                    'influxdb>=1.0.0', 'pika', 'potsdb', 'pyzmq', 'statsd'],
-        'folders:python_version<"3.5"': ['scandir'],
         'gpu:python_version=="2.7"': ['nvidia-ml-py'],
         'ip': ['netifaces'],
         'raid': ['pymdstat'],
```

Python: 2.7.6
uname -a: Darwin osx 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by staticfloat** [comment]
I ran into this as well, upgrade your `setuptools`, via `pip install --upgrade setuptools`; otherwise python doesn't know how to interpret these dependencies.

**Comment by nicolargo** [comment]
"Corrected" by @asergi in the commit https://github.com/nicolargo/glances/commit/0adf1392568b10cbbf69ea56771db988e9767b2b
