### ISSUE TITLE
On Windows --export-statsd  terminates immediately and does not export.

### ISSUE THREAD

**Issue by IanTAtWork** [nicolargo/glances#1067]
#### Description
- When executing --export-statsd on Windows; glances terminates immediately and does not export stats
- Based on the below; assuming this is an issue with the --export in general, as standalone mode cannot be started on Windows
- It appears this is a regression from 2.8.6 related to the fix of "Global name standalone not defined (#1030)" which reverted the fix from #1038 in __init__ to 
   if core.is_standalone()and not WINDOWS: from    if core.is_standalone():
- Commenting out "and not WINDOWS" causes the export to function as expected.

#### Versions

* Glances (glances -V): v2.8.8
* PSutil (glances -V): v5.2.0
* Operating System (lsb_release -a): Windows 7

#### Logs
This is the whole of the log:
2017-03-27 09:53:24,388 -- INFO -- Start Glances 2.8.8
2017-03-27 09:53:24,388 -- INFO -- CPython 2.7.8 and PSutil 5.2.0 detected
2017-03-27 09:53:24,403 -- INFO -- On Windows OS, export disable the Web interface

**Comment by nicolargo** [comment]
Corrected in the latest commit of the DEVELOP branch.

To be release in Glances 2.9.
