### ISSUE TITLE
Some FS and LAN metrics fail to export correctly to StatsD

### ISSUE THREAD

**Issue by IanTAtWork** [nicolargo/glances#1068]
#### Description
When running with --export-statsd; some metrics are not translating over correctly and throw exceptions in StatsD.

- FS metrics are sent with special characters in the stats name (On windows, so filesystem = C:\\, which then fails in StatsD) 
-- 27 Mar 11:01:29 - DEBUG: Bad line: **\\.free** in msg "glances.fs.**C:\\**.free:3366996787
- LAN Metrics send boolean True/False instead of numeric, and get a similar error.
--27 Mar 11:01:29 - DEBUG: Bad line: **False**,g in msg "glances.network.Local Area Connection* 11.is_up:False|g"
--27 Mar 11:01:29 - DEBUG: Bad line: **False**,g in msg "glances.network.isatap.mtg.home.ads.is_up:False|g"
--27 Mar 11:01:29 - DEBUG: Bad line: **True**,g in msg "glances.network.Local Area Connection.is_up:True|g"
--27 Mar 11:01:29 - DEBUG: Bad line: **True**,g in msg "glances.network.Loopback Pseudo-Interface 1.is_up:True|g"

A naive solution might be to filter out non-alphanum in the stat_name:
`stat_name = filter(lambda x: str.isalnum(x) or x == '.',stat_name)`
I don't know if that would play nice across all platforms though, maybe it would make more sense to swap \ and / to _.  
Then convert the stat_value to int when sending the gauge, so it's within the try/catch just in case this fails.  The bools translate nicely over to 0/1.  I don't think you'd ever want a non-int metric value here
`try:`
`    self.client.gauge(stat_name, int(stat_value))`
`except Exception as e:`
`    logger.error("Can not export stats to Statsd (%s)" % e)`

#### Versions

* Glances (glances -V): v2.8.8
* PSutil (glances -V): v5.2.1
* Operating System (lsb_release -a): Windows 7 

#### Logs
Below is the StatsD Logfile, does not appear in Glances log (which makes sense - metrics are delivered)

> 27 Mar 11:27:34 - DEBUG: Bad line: False,g in msg "glances.network.isatap.mtg.home.ads.is_up:False|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: True,g in msg "glances.network.Local Area Connection.is_up:True|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: True,g in msg "glances.network.Loopback Pseudo-Interface 1.is_up:True|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: \.free in msg "glances.fs.C:\.free:33671733248|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: \.size in msg "glances.fs.C:\.size:106848841728|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: \.percent in msg "glances.fs.C:\.percent:68.5|g"
> 27 Mar 11:27:34 - DEBUG: Bad line: \.used in msg "glances.fs.C:\.used:73177108480|g"

**Comment by nicolargo** [comment]
The problem came from the metric name convention. 

Somme resources:

* http://stackoverflow.com/questions/29674488/whitespace-in-statsd-metric-name
* https://github.com/etsy/statsd/issues/110

Proposal:

* replace ':' by ''
* replace ' ' (space) by '_'
* let StatsD manage non numerical value

What do you think ?

**Comment by IanTAtWork** [comment]
You're right! I had assumed the \ was the culprit; but filtering out the ':' worked beautifully.  Glances passes it as C\ to StatsD and then the graphite sanitizer works as expected to convert to just "C". 

Regarding the value - I would still think it makes sense to coerce the bool to a numeric.  The [StatsD spec docs](https://github.com/b/statsd_spec)  (which are unofficial and 4 years out of date...) state:
> For compatibility all values should be integers in the range (-2^53^, 2^53^).

Looking through my current output, this appears to be true for all metrics published by glances except for the bools (which are mostly of the is_up? variety).

**Comment by nicolargo** [comment]
Corrected in the latest commit on the DEVELOP branch.

**Comment by aleosd** [comment]
Installed glances today from `develop` branch. From `statsd.log`:

```
28 Apr 09:34:36 - DEBUG: Bad line: True,g in msg "stats.glances.network.veth3ac6b8c.is_up:True|g"
28 Apr 09:34:36 - DEBUG: Bad line: True,g in msg "stats.glances.network.ens160.is_up:True|g"
28 Apr 09:34:36 - DEBUG: Bad line: True,g in msg "stats.glances.network.docker0.is_up:True|g"
28 Apr 09:34:36 - DEBUG: Bad line: True,g in msg "stats.glances.network.lo.is_up:True|g"
28 Apr 09:34:36 - DEBUG: Bad line: True,g in msg "stats.glances.docker.src_stasd_1.mountsrw:True|g"
```

```
$ glances -V
Glances v2.9.2_DEVELOP with psutil v5.2.2
```
