### ISSUE TITLE
Glances PerCPU issues with Curses UI on Android

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1071]
#### Description

Child of https://github.com/nicolargo/glances/issues/1053

If you open per CPU statistics(press 1), same(or similar) issue exist:
![screenshot_2017-03-28-12-26-08](https://cloud.githubusercontent.com/assets/12114831/24398823/8618ca50-13b3-11e7-8c76-28d23a754369.png)

#### Versions

* Glances (glances -V): 2.9.0
* Operating System (lsb_release -a): Android

**Comment by nicolargo** [comment]
Corrected in the latest commit (1b8f955) in the DEVELOP branch.

**Comment by ybudimirov** [comment]
@nicolargo Thank you!
Now all works fine:
![1](https://cloud.githubusercontent.com/assets/12114831/24458075/92c8eee0-14a0-11e7-96f0-9cf8cd39d49d.png)
