### ISSUE TITLE
StatsD export prefix option is ignored

### ISSUE THREAD

**Issue by aleosd** [nicolargo/glances#1074]
While initiating statsd client `prefix` option is ignored and `glances` is always used. As i can see from source, prefix from config is not passed to stats cliet, and it uses default value.

```
$ glances -V
Glances v2.9.1 with psutil v5.2.1
```

**Comment by nicolargo** [comment]
Corrected in commit https://github.com/nicolargo/glances/commit/cc06451cc06e0d1ea42f0d429303caf74a430bdd (DEVELOP branch).

Thanks for the issue report !
