### ISSUE TITLE
No Offline status for timeouted ports?

### ISSUE THREAD

**Issue by alexylem** [nicolargo/glances#1084]
#### Description

Not sure if this is a bug.
I have defined some ports to watch in the config file.
But when a port is not responding, it keeps displaying a blue "Scanning" (forever).
I was expecting something more like a red "Offline".

![image](https://cloud.githubusercontent.com/assets/11017174/25568567/fbf9c046-2e05-11e7-98a9-71ffd690211f.png)
```shell
[ports]
refresh=30
timeout=3
port_3_host=192.168.1.31
port_3_description=OSMC
port_3_rtt_warning=1000 # I understand this is not related to timeout but more a latency warning
```

#### Versions

* Glances v2.9.1 with psutil v5.2.2
* Raspbian Jessie 8

#### Bonus Question

What about an `_action` for timeouted ports?

Thanks a lot, this tool is fantastic!

**Comment by nicolargo** [comment]
It should but it does not work as expected for ICMP request... 
I will have a look on it.

For the bonus question, it is a good idea. Can you submit another issue for this enhancement request ?

**Comment by nicolargo** [comment]
@alexylem should be corrected by the latest commit on the DEVELOP branch. Can you test it on your system ?

**Comment by alexylem** [comment]
👍 

![image](https://cloud.githubusercontent.com/assets/11017174/25593895/d9f2e0d6-2ebe-11e7-893d-527f06d1710f.png)
```
Glances v2.9.2_DEVELOP with psutil v5.2.2
```
