### ISSUE TITLE
GlancesAutoInstall script is not compliant with your system.

### ISSUE THREAD

**Issue by ikzjfr0** [nicolargo/glances#1085]
#### Description

Trying to install and got this error: 
"Sorry, GlancesAutoInstall script is not compliant with your system."

#### Versions
macOs 10.12.4

**Comment by nicolargo** [comment]
The GlancesAutoInstall script is only available for GNU/Linux OS. Please open an issue on the official Github repository (https://github.com/nicolargo/glancesautoinstall) and ask for an enhancement.
