### ISSUE TITLE
Using glances.conf for export data

### ISSUE THREAD

**Issue by arudat** [nicolargo/glances#1086]
Hi,

it would be nice to configure export data by the main configuration, so that I don't have to set every export target by parameter or that I have one parameter which says "don't start with exports, now". Alternative, if an export  configuration is set in glances.conf, use it on start or ignore by argument

**Comment by nicolargo** [comment]
Hi @arudat , i do not understand your needs... What the goal of this enhancement request ?

Why don't you create an alias to run glances as you want ?

    alias myglances='glances --export-influxdb'

**Comment by arudat** [comment]
Hi Nicolargo,

yes I can do that, but I thought it would be nice to set that if you need many export types, but  perhaps, yes it is too much ;)
