### ISSUE TITLE
When exporting, uptime values loop after 1 day

### ISSUE THREAD

**Issue by IanTAtWork** [nicolargo/glances#1092]
#### Description

When exporting to StatsD/Graphite, the Uptime values being returned by Glances do not reflect the ones in the UI.  Instead they reset to 0 every 24 hours.

I believe this is caused by the use of the seconds property on the timedelta.  In glances_uptime.py, in the  "get_export" function self.uptime.seconds is returned. For timedelta this the seconds part of the difference, but I believe the totalseconds() method should be used to return the whole difference in seconds. 

From the timedelta help():
 **|  total_seconds(...)
 |      Total seconds in the duration.**
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  days
 |      Number of days.
 |  
 |  microseconds
 |      Number of microseconds (>= 0 and less than 1 second).
 |  
 **|  seconds
 |      Number of seconds (>= 0 and less than 1 day).**

#### Versions

* Glances (glances -V): 2.9.1
* PSutil (glances -V): 5.2.1
* Operating System (lsb_release -a):

#### Logs
Since the data is being exported without exceptions, instead of the glances log, here is an example of one of the stats rolling over.  You can see it hit 85785 seconds (23 hours 49 minutes), and then the next interval is 285

stats.gauges.glances.uptime.seconds.HOST14,1495056600,1495143000,900|18287.0,19188.0,20088.0,20988.0,21888.0,22788.0,23685.0,24586.0,25487.0,26387.0,27287.0,28187.0,29088.0,29986.0,30886.0,31786.0,32686.0,33586.0,34486.0,35387.0,36287.0,37187.0,38087.0,38986.0,39887.0,40788.0,41685.0,42585.0,43485.0,44386.0,45286.0,46187.0,47087.0,47987.0,48884.0,49785.0,50686.0,51586.0,52487.0,53388.0,54288.0,55188.0,56088.0,56988.0,57888.0,58788.0,59688.0,60585.0,61486.0,62386.0,63287.0,64185.0,65086.0,65986.0,66886.0,67786.0,68686.0,69587.0,70487.0,71386.0,72286.0,73186.0,74086.0,74987.0,75884.0,76784.0,77685.0,78585.0,79485.0,80385.0,81286.0,82187.0,83087.0,83987.0,84888.0,**85785**.0,**285**.0,1186.0,2086.0,2987.0,3887.0,4784.0,5684.0,6585.0,7486.0,8387.0,9287.0,10185.0,11085.0,11985.0,12885.0,13786.0,14685.0,15586.0,16486.0,16516.0

**Comment by nicolargo** [comment]
Corrected in the latest commit in the DEVELOP branch.

Thanks for the issue report and solution :)
