### ISSUE TITLE
Windows standalone mode

### ISSUE THREAD

**Issue by CorrectHorseBatteryStapple** [nicolargo/glances#1093]
#### Description
Is it possible to run glances in standalone (console) mode on Windows machines?
It seems glances command always defaults to web server mode.

#### Versions

* Glances (glances -V): v2.9.1
* PSutil (glances -V): v5.2.2
* Operating System (lsb_release -a): Windows 7

**Comment by nicolargo** [comment]
The respond is no...

... as soon as Microsoft will not deliver a fully Curse's compliant console/terminal with it operating system (like GNU/Linux, BSD, Mac OS and all others OS of the galaxy...), Glances standalone mode will not be available on Windows.

**Comment by CorrectHorseBatteryStapple** [comment]
Would it be possible to run it from cmder then? (https://github.com/cmderdev/cmder)
