### ISSUE TITLE
Unable to parse ... invalid field format

### ISSUE THREAD

**Issue by contactmat85** [nicolargo/glances#1096]
Hi everybody!
I have a problem with influxDB and curl. I want new entries stored in a file. I am using something like: `std::string uri = "write?db=" + _database + "&consistancy=all&u=" + _username + "&p=" + _password;

	std::ifstream ifs(file_path);
	std::string concat_data((std::istreambuf_iterator<char>(ifs)),
		(std::istreambuf_iterator<char>()));

	HTTPResponse http_res;
	RemoteEndpoint::send_http_post(uri, concat_data, http_res);
	std::cout<<"http response: "<<http_res.content<<std::endl;
	//std::cout << "uri: " << uri << std::endl;

	if (http_res.code == InfluxHTTPCode::INFLUX_WRITE_SUCCESS)
	{
		return true;
	}
	else if (http_res.code == InfluxHTTPCode::INFLUX_WRITE_OVERLOADED)
	{
		//Endpoint server is overloaded
		//TODO : client behaviour when server is overloaded

		return false;
	}
	else
	{
		return false;
	}`

The function is working on windows but in linux I have:

`http response: {"error":"unable to parse 'count_people,age=unknown,campaign=persee,gender=unknown,location=barcelona 1 count=1 1495722361370000000': invalid field format\nunable to parse 'count_face,age=unknown,campaign=persee,gender=unknown,location=barcelona 1 count=1 1495722361370000000': invalid field format\nunable to parse 'dwell_time_content,age=unknown,campaign=persee,content=unknown,gender=unknown,location=barcelona 1 interaction_time=2.778000 1495722361370000000': invalid field format\nunable to parse 'count_people,age=unknown,campaign=persee,gender=unknown,location=barcelona 1 count=1 1495722381373000000': invalid field format\nunable to parse 'count_face,age=unknown,campaign=persee,gender=unknown,location=barcelona 1 count=0 1495722381373000000': invalid field format"}
`

any idea?

Thanks to everybody

**Comment by nicolargo** [comment]
It's Glances issue tracker, not InfluxDB...
