### ISSUE TITLE
Error while initializing the gpu plugin: missing parentheses in pynvml.py

### ISSUE THREAD

**Issue by mholt** [nicolargo/glances#1097]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

We want to use glances in our lab as a system monitor. Our machines have multiple GPUs and we'd really like to see that usage alongside everything else, and I was pleased to see #170 where it is apparently available as a plugin now. However, I'm having a problem:

I installed glances on Ubuntu 16.04 (python-dev already installed):

```
$ sudo pip install glances
$ glances   # works great (but no GPU info)
$ sudo pip install nvidia-ml-py
$ glances   # big crash
```

It's totally possible that I'm doing something wrong, however the error (see log entry below) looks like something wrong in the code?

#### Versions

* Glances v2.9.1 with psutil v.5.2.2
* Operating System (lsb_release -a): Ubuntu 16.0.4.2 LTS

#### Logs

```
-- CRITICAL -- Error while initializing the gpu plugin (Missing parentheses in call to 'print' (pynvml.py, line 1831))
```

Thanks for any guidance/suggestions. Let me know if you need more information!

**Comment by mholt** [comment]
Reading more closely, I just saw the same error in the middle of that (long) issue I linked to.

Seems that it's just not updated on pip... :confused: https://github.com/jonsafari/nvidia-ml-py/issues/1 

Sorry for the noise.

**Comment by kyle-mccarthy** [comment]
I get the same error when installing with `wget -O- https://bit.ly/glances | /bin/bash`

**Comment by vinnu5064** [comment]
simply add the Missing parentheses in pynvml.py, it works for me.
