### ISSUE TITLE
Submit data to a webhook

### ISSUE THREAD

**Issue by aftabnaveed** [nicolargo/glances#1109]
Sorry, this is not a bug, but a question about a feature which I am not sure if it exists or not. I want to use glances as an agent like Newrelic which sends data to a webhook periodically. Is it something it can be used for? I reckon it is something which can be achieved through Actions. 

A command collects all the stats in real time, and then post that to a webhook. I found this here http://glances.readthedocs.io/en/stable/aoa/actions.html not sure if that would be the right way of doing it?

**Comment by jamesacoughlin** [comment]
You can use those action lines to call curl, and use that to send the data to a webhook. I do this to get alerts sent to slack channels. 

However, this will only send data if the pre-defined events mapped to those actions are triggered (i.e. if memory utilization crosses the critical threshold, then the [mem] critical_action line will be run). If you're hoping to send data periodically a la an export module (influxdb, csv, etc ) this won't help you.

**Comment by aftabnaveed** [comment]
CSV sounds like an option. I may use a cron to collect data from CSV and post it to the webhook. How huge the file gets?  Is it even a better idea to do it like every 2 to 5 minutes?

**Comment by nicolargo** [comment]
@aftabnaveed i do not understand your need. You said that ou want to export Glances stats to a "webhook". What is it ? What format is accepted by this "webhook" ? What protocol ?

**Comment by aftabnaveed** [comment]
@nicolargo I figured out, let me try to explain what I wanted to achieve and how I did it. 

We have about 20 EC2 instances running at a time on AWS, with auto scale enabled. Every time when a new instance is rolled out running glances in Server/Client mode would require us to register that. 

Instead, I want when the new server is provisioned from a template it already has glances configured and started automatically (Like newrelic agent) As soon as the server is booted glances registers the instance by sending a unique identifier such as hostname or IP address to a remote server outside of AWS. 

Now Glances has a few options to achieve above, you either configure an export which can talk to a remote server and export the stats or access each server independently through its URL, but since the server is remote I do not want to be dependent on that and neither I wanted to access each server independently. 

Now here is what I did, since glances can be used as a module. I am able to get the server stats through

```python
 # Create the Glances main instance
    core = GlancesMain()
    config = core.get_config()
    args = core.get_args()

    # Catch the CTRL-C signal
    signal.signal(signal.SIGINT, __signal_handler)

    # Glances can be ran in standalone, client or server mode
    from stats import GlancesStats
    import json
    full_stats = GlancesStats(config, args)
    full_stats.update()
    #Post the generated json to a webhook periodically.
   print json.dumps(full_stats.getAllAsDict())
```
That way on my remote server I am able to store the information whichever database backend I want such as MongoDB or elastic and also not exposing any of these to glances.  

I am not sure if this is the best way of using glances, but it is now serving my purpose and I am able to get all the stats without making glances dependent on external servers.

**Comment by aftabnaveed** [comment]
@nicolargo does that description help or you think I should add some more description and be clear about my requirements?

**Comment by nicolargo** [comment]
@aftabnaveed  Let me summarize. You want a kind of proxy between your Glances servers (hosted on AWS) and backend such as NoSQL database.

For the moment, Glances browser mode only accept new client coming from Zeroconf (local network only) and static configuration file. To do what you want, Glances browser mode as to be modify to accept incoming requests from external Glances server (pushed by Glances server).

It's a big enhancement request, are they another Glances' users interesting by this function ?

**Comment by aftabnaveed** [comment]
Sorry for not been very clear about my requirements. I think I now know what I am looking for. Let me explain...

I understand Glances have a few modes (web server, and standalone etc), but I want it to work like a monitoring agent such as Newrelic. I also see there are quite many glances export plugins such as Elasticsearch, InfluxDB, and CSV etc.

Therefore, I would like to replace Newrelic agent with glances. Every few seconds or minute I want glances to post export or post data to an endpoint instead of exporting it to a database or CSV. 

This is what I am currently doing at the moment, but not sure if an export would be a better option
```python
 full_stats = GlancesStats(config, args)
 full_stats.update()
 #Post the generated json to a webhook periodically.
 data = json.dumps(full_stats.getAllAsDict())
 requests.post(url, data=data, allow_redirects=True)
```

**Comment by nicolargo** [comment]
Implementation of a standard and configurable restful exporter will be done in issue https://github.com/nicolargo/glances/issues/1129
