### ISSUE TITLE
Cant move up or down in glances --browser

### ISSUE THREAD

**Issue by mrmcox** [nicolargo/glances#1113]
Hi All,

I am running the latest release of Glances on Ubuntu 16 and all is working great expect that in browser mode I cannot move the cursor down the list of servers meaning I can only expand the details of the first one in the list.

Setup overview
WIndows Server 2012R2 --->Hyper V UbuntuVM---->Glances install.

My access is via the Hyper V remote console window.

Any help would be great.

**Comment by nicolargo** [comment]
Hi @mrmcox ,

first of all thanks for the issue report.

Please can you run glances in debug mode (glances -d --browser) and [paste/bin](https://pastebin.com/) us the /tmp/glances-<user>.log file ?

**Comment by mrmcox** [comment]
[glances-ubuntuadmin.txt](https://github.com/nicolargo/glances/files/1105426/glances-ubuntuadmin.txt)
Please find requested log attached as .txt file.

Thanks all.

**Comment by nicolargo** [comment]
Two additional questions: 

- what is the version of your Glances running on servers 10.14.2.4 and 10.14.2.7 ?
- Is the Glances TCP/61209 port open between your client and yours servers ?

**Comment by mrmcox** [comment]
Hi,

Below is the version output of both the servers. All ports are open internally between the boxes.
10.14.2.7
Package: glances
Status: install ok installed
Priority: extra
Section: utils
Installed-Size: 800
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 2.6.2-2
Depends: adduser, libjs-angularjs, libjs-lodash, lsb-base, python3-pkg-resources, python3-psutil (>= 2.0.0), python3:any (>= 3.3.2-2~)
Recommends: hddtemp, lm-sensors, python3-bottle, python3-docker, python3-influxdb, python3-matplotlib, python3-netifaces, python3-pysnmp4, python3-pystache
Conffiles:
 /etc/default/glances b163a9cd5f309dd04fa1a2abe96c26c6
 /etc/glances/glances.conf 14a554dea5226627a95f6f796ca03f99
 /etc/init.d/glances c50025840783b04b55af27b58dab729b
Description: Curses-based monitoring tool
 Glances is a curses-based monitoring tool for GNU/Linux or BSD OS.
 Glances uses the PsUtil library to get information from your system.

10.14.2.4

Package: glances
Status: install ok installed
Priority: extra
Section: utils
Installed-Size: 800
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 2.6.2-2
Depends: adduser, libjs-angularjs, libjs-lodash, lsb-base, python3-pkg-resources, python3-psutil (>= 2.0.0), python3:any (>= 3.3.2-2~)
Recommends: hddtemp, lm-sensors, python3-bottle, python3-docker, python3-influxdb, python3-matplotlib, python3-netifaces, python3-pysnmp4, python3-pystache
Conffiles:
 /etc/default/glances b163a9cd5f309dd04fa1a2abe96c26c6
 /etc/glances/glances.conf 14a554dea5226627a95f6f796ca03f99
 /etc/init.d/glances c50025840783b04b55af27b58dab729b
Description: Curses-based monitoring tool
 Glances is a curses-based monitoring tool for GNU/Linux or BSD OS.
 Glances uses the PsUtil library to get information from your system.
 .
 It monitors CPU, load, memory, network bandwidth, disk I/O, disk use, process.
Original-Maintainer: Daniel Echeverry <epsilon77@gmail.com>
Homepage: https://nicolargo.github.com/glances/

**Comment by mrmcox** [comment]
Hi @nicolargo any further thoughts on this one?

Thanks for the help so far!

**Comment by rollenwiese** [comment]
I have this issue as well. Arch Linux, Glances v 2.10. Client/Server communication works fine, no other issues. The cursor keys don't function in browser mode. I tried in both rxvt-unicode and termite. It seems to register the cursor keystroke, but no action is taken. Only Enter and 'q' seem to do anything.

    2017-07-09 12:09:10,404 -- DEBUG -- Keypressed (code: [259, -1])
    2017-07-09 12:09:10,404 -- DEBUG -- Key pressed. Code=259
    2017-07-09 12:09:10,708 -- DEBUG -- Keypressed (code: [259, -1])
    2017-07-09 12:09:10,708 -- DEBUG -- Key pressed. Code=259
    2017-07-09 12:09:11,717 -- DEBUG -- Keypressed (code: [258, -1])
    2017-07-09 12:09:11,717 -- DEBUG -- Key pressed. Code=258
    2017-07-09 12:09:11,818 -- DEBUG -- Keypressed (code: [258, -1])
    2017-07-09 12:09:11,818 -- DEBUG -- Key pressed. Code=258
    2017-07-09 12:09:12,119 -- DEBUG -- Keypressed (code: [259, -1])
    2017-07-09 12:09:12,119 -- DEBUG -- Key pressed. Code=259
    2017-07-09 12:09:12,319 -- DEBUG -- Keypressed (code: [259, -1])
    2017-07-09 12:09:12,320 -- DEBUG -- Key pressed. Code=259
    2017-07-09 12:09:13,021 -- DEBUG -- Keypressed (code: [113, -1])
    2017-07-09 12:09:13,021 -- DEBUG -- Key pressed. Code=113
    2017-07-09 12:09:13,021 -- INFO -- Stop Glances client browser

**Comment by nicolargo** [comment]
Bug reproduced.

Try to work on it as soon as possible.

@ all : thanks for the report !

**Comment by rollenwiese** [comment]
You can still use browser mode, but the keys it's listening for are 'A' (65) and 'B' (66) instead of the cursor keys. In glances_curses_browser.py:

    elif self.pressedkey == 65:
    # 'UP' > Up in the server list
    self.cursor_up(servers_list)
    elif self.pressedkey == 66:
    # 'DOWN' > Down in the server list
    self.cursor_down(servers_list)

**Comment by nicolargo** [comment]
@rollenwiese Thanks for the workarround !

**Comment by nicolargo** [comment]
Ok corrected by the latest commit on the DEVELOP branch.

Will be available in Glances 2.11.

Thanks again.

**Comment by rollenwiese** [comment]
@nicolargo no problem, thank you!
