### ISSUE TITLE
Enable/disable per plugin alert from the command line

### ISSUE THREAD

**Issue by ghost** [nicolargo/glances#1116]
#### Description
Load on Linux and BSD are different things, high load on BSD does not means high CPU load.
I found an article describes the load in detail.
http://undeadly.org/cgi?action=article&sid=20090715034920

The picture below is glances running on my vps, the load looks high, but it does not run anything heavy.
There is a system overloaded warning at the bottom, maybe it's good to disable that warning on BSD systems, currently I use `--disable-load` to disable that warning but it disables load completely.
![untitled-1](https://user-images.githubusercontent.com/28924404/27525220-732c7e12-5a6e-11e7-99ba-e0539fa2c2c6.png)

#### Versions

* Glances (glances -V):
`Glances v2.10`
* PSutil (glances -V):
`psutil v5.2.2`
* Operating System (lsb_release -a):
`OpenBSD vultr.guest 6.1 GENERIC.MP#20 amd64`
#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Hi @outoftheloopxa , first of all thanks for this information about how load is computed on BSD systems. If i understand your need, i see two solutions:

1) the first one without any patch on the Glances code by configuring load's thresholds to "very" high values in the Glances configuration file:

```
[load]
careful=100
warning=100
critical=100
log=False 
```

2) Wait for the development of a new Glances function to disable alert for a specific plugin (--disable-alert load)

What do you think ?

**Comment by outoftheloopxa** [comment]
1. Thank you for the tip, I didn't notice there is a configuration file, this is useful.

2. This one is also convenient for those who don't want to change the configuration file.

**Comment by nicolargo** [comment]
The second solution will be implemented in Glances 3.0.

I just rename the issue.
