### ISSUE TITLE
not installing to macOS via pip

### ISSUE THREAD

**Issue by rozenshtein** [nicolargo/glances#1117]
#### Description

Pip installation fails on macOS 
#### Versions

* Operating System (lsb_release -a): OS X 10.12 and up

**Comment by nicolargo** [comment]
Not easy to investigate with this kind of issue report...

Please copy/paste the error message.

**Comment by rozenshtein** [comment]
Its likely to be  caused by system integrity protection. Same with or without sudo 

     creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-dN4Es6/glances/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nw914l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-dN4Es6/glances/

**Comment by rozenshtein** [comment]
#1117 is the same issue, but with better info
