### ISSUE TITLE
New Feature - Web Based browser function

### ISSUE THREAD

**Issue by mrmcox** [nicolargo/glances#1121]
To be able to view the glances --browser window via a web page like when using glances -w. This would allow for a central point, web based, to monitor all  glances servers from a single point eg I can see all my servers from my windows desktop in a remote office via a web browser page. 

Thanks

**Comment by nicolargo** [comment]
For developers, two actions to implement this new feature:

- Glances core: add a new --browser for the -w mode (add to wait the refactor of the code ==> Glances 3.x)
- Glances core (API): add a new entry point in the Web API to be able to retrieve server list
- Glances Web GUI: add a new page to display server list + link

**Comment by mrmcox** [comment]
Thanks @nicolargo

Not a developer myself unfortunately but hopefully one of the more skilled than me can get this going. I reckon it will be a popular feature for sure!

**Comment by nicolargo** [comment]
@mrmcox You are not the first one asking this feature.

I will try to implement it in the next release (aka Glances 2.11) without waiting for the code refactoring. Is @nclsHart or @notFloran available to implement the Web GUI parts ?

**Comment by nicolargo** [comment]
@notFloran / @nclsHart : I just push a new branch (https://github.com/nicolargo/glances/tree/issue1121) with the Glances core update. The API now give the servers list:

$ glances -w --browser

$  curl http://0.0.0.0:61208/api/2/serverslist
[{"username": "glances", "status": "ONLINE", "mem_percent": 50.6, "name": "localhost", "cpu_percent": "3.9", "ip": "127.0.0.1", "load_min5": "0.17", "alias": "My local PC", "key": "localhost:61209", "password": "", "type": "STATIC", "port": "61209", "hr_name": "Ubuntu 16.04 64bit"}, {"username": "glances", "status": "OFFLINE", "name": "localhost", "ip": "127.0.0.1", "alias": null, "key": "localhost:61235", "password": "", "type": "STATIC", "port": "61235"}, {"username": "glances", "status": "OFFLINE", "name": "192.168.0.17", "ip": "192.168.0.17", "alias": "Another PC on my network", "key": "192.168.0.17:61209", "password": "", "type": "STATIC", "port": "61209"}, {"username": "glances", "status": "ONLINE", "mem_percent": 50.6, "ip": "192.168.0.48", "load_min5": "0.17", "key": "XPS13-9333:61209._glances._tcp.local.", "password": "", "port": 61209, "name": "XPS13-9333", "cpu_percent": "3.9", "type": "DYNAMIC", "hr_name": "Ubuntu 16.04 64bit"}]

You need to create a new page (for example index_browser.html) and display the previous list in a fancy way. When a user click on a server on the list it should be redirected to the Glances web server page (on another tab ?).

**Comment by nicolargo** [comment]
@notFloran Do you have some availability to work on this new feature ?

**Comment by notFloran** [comment]
@nicolargo I will try to do it at the beginning of next week

**Comment by notFloran** [comment]
@nicolargo I made a first draft of the feature if you want to test: https://github.com/notFloran/glances/tree/issue1121-webui

**Comment by mrmcox** [comment]
@notFloran HI, I have updated my glances code with your first draft, how do I now set glances and then access the browser page?

**Comment by notFloran** [comment]
I use the following command: `LANGUAGE=en_US.utf8 ~/glances-venv/bin/python -m glances -w --browser -C ~/glances.conf`

You must change the args to match your needs.

And the browser page is available at the following URL: http://0.0.0.0:61208/browser

**Comment by mrmcox** [comment]
Thanks. 
Whats the -m switch doing?

When I run the following command "glances -w --browser" and go to the url you quoted from a browser on the local glances box I get unable to connect message. Any tips?

**Comment by notFloran** [comment]
No idea, I get the command from the wiki: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#run-the-glances-develop-version

**Comment by nicolargo** [comment]
Hi all,

@notFloran your implementation should work:

![selection_334](https://user-images.githubusercontent.com/776747/28352599-b9b2bcac-6c57-11e7-832c-70e62a1d2e77.png)

but i made a mistake on my side...

The result returned by the API give the list of XML-RPC server, not the list of WEB Server, so when i click on the connected server (green one), i have this message:

![selection_335](https://user-images.githubusercontent.com/776747/28352660-00548dfc-6c58-11e7-91e5-68571a1e68fe.png)

So i need to refactor my code to only provide the WEB server list and its relative stats:
[ ] Add zeroconf to the Webserver part
[ ] Modify the API to give the Web server list (and not the XML-RPC list). Check if servers (static or dynamix respond to the Restful API)

@notFloran Can you pull request your code to this remote branch: https://github.com/nicolargo/glances/tree/issue1121

I will try to implement my part as soon as possible (probably this week-end) and came back to you to finalise the WebUI side.

**Comment by nicolargo** [comment]
Another issue... The current version of Glances generate the server list with both static and dynamic RPC server but not dynamic Web server. So i have to change the way the list is build and add a dynamic message (different from the RPC one) when the Web server is started. Last but not list i have to change the way that stats are updated in the web server list (replace XML RPC request by Restful API)...

I know now why i postpone this enhancement, the current Glances version is not designed to implement easily this feature. Sorry but i have to postpone it in Glances 3.0.

Has a workaround you can write a external peace of code to display a Glances server list and ask stats via the Restful API...

@notFloran Sorry for your time but keep the code in a branch, we will reuse it in Glances 3.0.

**Comment by mrmcox** [comment]
Ah, very sad times. I was looking forward to seeing this sooner rather than later. IT would be great for our current environment. 

Hopefully glaces 3.0 wont be too far off?

Thanks to @nicolargo and @notFloran for all the work so far, great job guys.

**Comment by nicolargo** [comment]
Note a sad new, just an hope for the version 3.0 (not scheduled but perhaps in beginning of 2018).

**Comment by nicolargo** [comment]
Sorry but no time to work on this issue...

Looking for a contributor to take the control of the Glances browser function.

**Comment by tpcforever** [comment]
A little up for this feature ? 
Still possible in Glances 3.X ?
Thanks a lot in advance, it's very good idea

**Comment by nicolargo** [comment]
Found a bug.

How to reproduce:
- start a Web server (-w)
- start a Central Glances Browser (--browser)
- stop the Web server
- restart it
-  bug...

```
Exception in thread zeroconf-ServiceBrowser-_glances._tcp-2689041:
                                                                         8      1.2       1.5                                                                  Traceback (most recent call last):
     File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
                                                                                self.run()
                                                                                            File "src/zeroconf/_services/browser.py", line 811, in zeroconf._services.browser.ServiceBrowser.run
    File "src/zeroconf/_services/browser.py", line 730, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
                                                                                                                                             File "src/zeroconf/_services/browser.py", line 740, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
                                                                                        File "src/zeroconf/_services/__init__.py", line 56, in zeroconf._services.Signal.fire
                                                                                                                                                                               File "src/zeroconf/_services/browser.py", line 305, in zeroconf._services.browser._on_change_dispatcher
                                                                                       5AttributeError: 'GlancesAutoDiscoverListener' object has no attribute 'update_service'. Did you mean: 'remove_service'?

```

**Comment by nicolargo** [comment]
Patch done for the previous error on the develop branch.

**Comment by stanthewizzard** [comment]
sorry but how does it work for end user ?
thanks
