### ISSUE TITLE
CPU Usage, what should I expect?

### ISSUE THREAD

**Issue by mrmcox** [nicolargo/glances#1122]
Hi All,

Just a quick one. When I am running glances in server mode ( --glances -s -B 111.111.111.111) what sort of CPU usage should I see from the local box? Currently I am running at between 10-20% but tend to hover around 13-16%.

Any tips to get this reduced but maintain getting useful perf data out? No point turning everything of and saying, great, less CPU but no data!

Thanks.

**Comment by nicolargo** [comment]
You have two configuration key.

One for the client side where you can set the refresh time to 10 seconds (for example, default is 3 seconds) using the '-t 10' option.

Another one on the server side to set the cache delay (the stats will not be refreshed during this delay). The default value is 1 second. To set it to 10 seconds, use the '--cached-time 10' option.
