### ISSUE TITLE
What to mount in docker to see FILE SYS from host, not from container?

### ISSUE THREAD

**Issue by muhahacz** [nicolargo/glances#1131]
What to mount in docker to see FILE SYS from host, not from container?
Thanks

**Comment by nicolargo** [comment]
Read this: https://docs.docker.com/engine/tutorials/dockervolumes/#locate-a-volume

**Comment by nicolargo** [comment]
REJECTED: not a Glances issue

**Comment by muhahacz** [comment]
@nicolargo  I know how docker mounting works. I need to know what directory from host system mount in docker container to FILE SYS group? For example /proc:ro for processes... I dont know from what are you reading stats about partitions and theirs size in os.
Thanks

**Comment by emreyak** [comment]
Old issue but, for anyone who comes across this, try mounting the root directory of the host to the container, preferably with readonly restrictions, like so: `-v /:/host/root:ro`, to allow glances to display stats for the host filesystem.
