### ISSUE TITLE
How to stop the glances service in windows OS via openssh command?

### ISSUE THREAD

**Issue by kaihongdu** [nicolargo/glances#1134]
#### Description
I installed Python and Glances service in windows 2016 along with Openssh. Now I'm sending glances command to windows via ssh from another linux host, but I am unable to stop the service via ssh command unless end the glances task in windows task manager.  any suggestion on it?

#### Versions
* Glances (glances -V):   v2.10
* PSutil (glances -V):   v5.2.2
* Operating System (lsb_release -a):  windows 2016 standard

#### Logs

ssh -i id_rsa Administrator@remote ip "glances -t 5 --export-csv ./tmp/glances.csv"
then glances is running all the time, unable to stop it.

**Comment by nicolargo** [comment]
Not realy a Glances issue... Nevertheless, you can use the Taskkill
command.

https://technet.microsoft.com/fr-fr/library/cc725602(v=ws.11).aspx

**Comment by kaihongdu** [comment]
ok, thanks!
