### ISSUE TITLE
help wanted with reverse proxy base url

### ISSUE THREAD

**Issue by stevens-r** [nicolargo/glances#1136]
code is from /etc/apache2/sites-available/default-ssl.conf
`<Location /glances>`
`ProxyPass http://localhost:61208/`
 `ProxyPassReverse http://localhost:61208/`
`</Location>`

 does anyone know how to get this working if i set it up like that ^ it doesnt work cause there no base url setting in glances 
`<Location />`
`ProxyPass http://localhost:61208/`
 `ProxyPassReverse http://localhost:61208/`
 `</Location>`
set up like that ^ it just makes www.domain.ca go to glances and it works but i would like www.domian.ca/glances 

just set up ombi that way and it works good but ombi has a base url option in settings so i know the reverse proxy is working i just need to config glances somehow

 any help would be greatly appreciated 

#### Versions

* Glances (glances -V): latest 
* PSutil (glances -V):idk
* Operating System (lsb_release -a): ubuntu 16.04

**Comment by nicolargo** [comment]
Hi, did you try this https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI ?

**Comment by stevens-r** [comment]
yes i tried that and it worked for a couple days now it redirects to http://host/glances

**Comment by stevens-r** [comment]
found the answer in #1141
