### ISSUE TITLE
error when starting glances with gpu plugin

### ISSUE THREAD

**Issue by AnderssonPeter** [nicolargo/glances#1137]
#### Versions
Glances v2.10 with psutil v5.2.2
Docker container based on arm32v7/python:3.6

#### Logs
```bash
Error while initializing the gpu plugin (Missing parentheses in call to 'print' 
(pynvml.py, line 1831))
```

**Comment by nicolargo** [comment]
As said in the documentation:

nvidia-ml-py (for the GPU plugin) [Python 2-only]

As a work arround, you can use my own implementation of NVidia-ml for Python 3 available here:

https://pypi.python.org/pypi/nvidia-ml-py3

**Comment by AnderssonPeter** [comment]
thanks for the fast reply i guess i missed the information in the documentation, sorry for wasting your time.
