### ISSUE TITLE
Client and Quiet mode don't work together

### ISSUE THREAD

**Issue by Stringers** [nicolargo/glances#1139]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Running glances in client mode prevents you from disabling the curses interface using the quiet option. 

 `glances -q -c @hostname` - in this cases, the curses interface will still appear. I including the -q switch on the server as well, to no avail. 

#### Versions

* Glances (glances -V): 2.11
* PSutil (glances -V): 2.2.1
* Operating System (lsb_release -a): CentOS Linux release 7.3.1611 (Core)

**Comment by nicolargo** [comment]
Corrected in the latest commit.
Will be release in Glances 2.11.1 and higher.

Thanks for the report.
