### ISSUE TITLE
Can you add qnap support?

### ISSUE THREAD

**Issue by altek86** [nicolargo/glances#1140]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a):

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
What do you expect ? A compatibility with the Qnap SNMP ? Or a way to run Glances on the Qnap support ?

Please fill the issue correctly.

**Comment by altek86** [comment]
Im sorry I was looking for a way to run glances on qnap.

**Comment by nicolargo** [comment]
@altek86 Did you try to install Python and Pip and install Glances with:

    pip install glances

???

See: http://rdkevinchien.blogspot.fr/2013/08/how-to-setup-my-python-developing.html

**Comment by altek86** [comment]
[~] # pip install glances
-sh: pip: command not found
[~] #

**Comment by nicolargo** [comment]
Follow all the procedure (http://rdkevinchien.blogspot.fr/2013/08/how-to-setup-my-python-developing.html). It explains how to install pip...

**Comment by nicolargo** [comment]
@altek86 Any news about this issue ?

**Comment by altek86** [comment]
Nope it doesnt work I give up.
