### ISSUE TITLE
Server bug with Ubuntu 16.04.3?

### ISSUE THREAD

**Issue by wayofthefuture** [nicolargo/glances#1141]
I have a recently fresh install of Ubuntu 16.04.3 and when I run the wget script located on the home page i the following error. I've used localhost, 0.0.0.0, and 192.168.1.X and none of them work.

See pic.

Thank you.
![screenshot from 2017-09-04 14-15-00](https://user-images.githubusercontent.com/5134107/30036770-bfd42988-917b-11e7-908e-978734bba4ae.png)

**Comment by ngandhy** [comment]
Just installed on 16.04 myself with no issues. 

Are you doing a reverse proxy or hitting the port directly? If you're using a reverse proxy try adding a "/" to the end of the URL to get things working.

**Comment by stevens-r** [comment]
my reverse proxy started redirecting to https://host/glances the other day adding / to end fixed it up

**Comment by wayofthefuture** [comment]
I was using the wrong switch... server instead of webserver... Thanks.
