### ISSUE TITLE
[WebUI] Sensors not showing on Web

### ISSUE THREAD

**Issue by ngandhy** [nicolargo/glances#1142]
#### Description

Sensors shows up when I run glances via console but **not** when I use the WebUI (glances -w). I referred to #687 to make sure I sent information useful to you

**WebUI:** https://www.dropbox.com/s/epejf5tko4zp4w2/Screenshot%202017-09-05%2013.47.36.png?dl=0

**Console** https://www.dropbox.com/s/sfasmyhafrpi09n/Screenshot%202017-09-05%2013.48.22.png?dl=0

#### Versions

* Glances: Glances v2.11 with psutil v5.3.0
* Operating System: Ubuntu 16.04.3 LTS

#### Logs

Referring to what you asked for in past reports:

**Request:** /api/2/sensors
**Response:**
[{"key": "label", "type": "temperature_core", "unit": "C", "value": 38, "label": "Core 0"}, {"key": "label", "type": "temperature_core", "unit": "C", "value": 32, "label": "Core 1"}, {"key": "label", "type": "battery", "unit": "%", "value": [], "label": "Battery"}]

**Request:** /api/2/all
**Response:**
...
"sensors": [{"key": "label", "type": "temperature_core", "unit": "C", "value": 38, "label": "Core 0"}, {"key": "label", "type": "temperature_core", "unit": "C", "value": 32, "label": "Core 1"},"hddtemp": [], 
...

**Request:** /api/2/cpu
**Response:**
{"softirq": 0.0, "iowait": 0.0, "interrupts": 1163, "system": 2.2, "guest": 0.0, "soft_interrupts": 1134, "time_since_update": 3.6782970428466797, "idle": 96.0, "user": 1.8, "guest_nice": 0.0, "irq": 0.0, "cpucore": 2, "syscalls": 0, "total": 10.1, "steal": 0.0, "ctx_switches": 2155, "nice": 0.0}

#### Other Notes

I've tried reinstalling the whole thing using the bit.ly scripts and still have the same issue. As a side note (and I'm not sure if related) I can't get hddtemp to show up at all (in webui or command line). But if I run "sudo hddtemp /dev/sda" I get "/dev/sda: Hitachi HDE721010SLA330: 43°C" . If you can think of anything to fix hddtemp as well please let me know. 

Thanks for the great tool!

**Comment by nicolargo** [comment]
Also reproduced on my Ubuntu 16.04 configuration.

@nclsHart / @notFloran Can you have a look on it ?
