### ISSUE TITLE
Whats the "S" column in browser?

### ISSUE THREAD

**Issue by mrmcox** [nicolargo/glances#1143]
Hi All,

Quick question - In the browser view when looking at the details of a machine what is the "S" column to the left of "Time" and what do the letters in that column mean?

Thanks all.

**Comment by nicolargo** [comment]
As said in the documentation (http://glances.readthedocs.io/en/stable/aoa/ps.html#columns-display), it's the process status.

**Comment by nicolargo** [comment]
Rejected cause: #RTFM
