### ISSUE TITLE
Question: Aggregate process group by memory is possible?

### ISSUE THREAD

**Issue by Webysther** [nicolargo/glances#1145]
#### Description

I would like to know if there is a way to aggregate the amount of memory used by a parent process and its children, for example, chrome, nginx, php-fpm, and so on.

#### Versions

Glances v2.3 with psutil v3.4.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

#### Logs

N/A

**Comment by nicolargo** [comment]
I see two solutions:

1) Use AMP: http://glances.readthedocs.io/en/stable/aoa/amps.html
2) Use the filter function (filtered view): http://glances.readthedocs.io/en/stable/aoa/ps.html

**Comment by ChillarAnand** [comment]
AMP & filter functions work for user defined process. 

In general, when looking at a system overall resource usage, won't it make sense to have an aggregation feature?

For example, in `atop`, we can aggregate process with 

```
Accumulated figures:
        'u'  - total resource consumption per user
        'p'  - total resource consumption per program (i.e. same process name)
        'j'  - total resource consumption per container
```

This will quickly help to identify the actual process hogging a resource.
