### ISSUE TITLE
Memory usage reported via WEB GUI doesn't match top value in container

### ISSUE THREAD

**Issue by Constantin07** [nicolargo/glances#1148]
#### Description

The RAM used reported via WEB GUI and in the glances container do not match. 
Glances WEB - 487 MB
Inside container - 132 MB
The difference is almost 3x times which is very suspicious.

#### Versions

* Glances (glances -V): Glances v2.11.1 with psutil v5.3.0
* Operating System (lsb_release -a): Ubuntu 16.04.3 LTS (Xenial Xerus)
* Used the stable version of [glances](https://hub.docker.com/r/nicolargo/glances/tags/) container 

#### Logs

<img width="1588" alt="screen shot 2017-09-14 at 10 29 26" src="https://user-images.githubusercontent.com/11664677/30422576-45240efa-9938-11e7-9f5d-46c88711ec0a.png">
<img width="1212" alt="screen shot 2017-09-14 at 10 29 52" src="https://user-images.githubusercontent.com/11664677/30422584-4ca059f4-9938-11e7-883b-35c8edbafcc6.png">

**Comment by nicolargo** [comment]
Hi,

can you run a docker stats <container ID> command ?
Glances uses the standard API to retrieve the stats.

Thk

**Comment by Constantin07** [comment]
@nicolargo here is the output:

```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
16eb87c04502        0.12%               24.55MiB / 1.952GiB   1.23%               607kB / 749kB       0B / 9.65MB         34
0546f2d30c3f        4.11%               29.79MiB / 1.952GiB   1.49%               60.4kB / 440kB      17.8MB / 0B         3

```

**Comment by nicolargo** [comment]
Glances computes the free memory based on PsUtil stats and the Htop algorithm (free=available+buffer+cached and used=total-free). Top uses a different method.

Also read: 
* https://stackoverflow.com/questions/41224738/how-to-calculate-system-memory-usage-from-proc-meminfo-like-htop
* http://hisham.hm/htop/index.php?page=faq

**Comment by Constantin07** [comment]
@nicolargo  I've run the docker with the `-v /proc/meminfo:/proc/meminfo:ro` and the values now are correct (match `free -m`).
