### ISSUE TITLE
A way to have only REST API available and disable WEB GUI access

### ISSUE THREAD

**Issue by Constantin07** [nicolargo/glances#1149]
#### Description

Just wondering is there is a way to turn off the WEB GUI and leave only REST API access.
I need a very lightweight and as much as possible minimal footprint of the process so that I can consume only the API. I know that they both are listening on 61208.

At the same time disabling WEB can reduce possible security/vulnerability radius.

PS: I'm planning to centrally poll the API for different metrics and actually don't need the WEB.

Regards,
Constantin

**Comment by nicolargo** [comment]
Hi @Constantin07 ,

first of all, thanks for the enhancement request. Split between API and WebUI is scheduled in Glances version 3 (with a big refactor). Nevertheless i think that it could also be implemented in the version 2 branch. I will have a look.

When i read your "PS:" i understand that you need a Glances server with only the Restful API implemented. In // of Glances 3 i want to develop a  thin server with a low memory print and a limited external lib to limit the vulnerability radius.

**Comment by Constantin07** [comment]
@nicolargo Thanks for getting back so quickly.

I'm planning to use as a central server Nagios or other tool (haven't decided which one yet) which allows easily to write custom plugins and integrate them.

My scope is to have a simple dashboard with possibility to check the docker containers states on remote hosts.

**Comment by nicolargo** [comment]
Implementation done in the latest commit.

Current mode:

    # glances -w
    Glances Web User Interface started on http://0.0.0.0:61208/

New mode

    # glances -w --disable-webui
    Glances Restful API Server started on http://0.0.0.0:61208/api/2/

Available in the DEVELOP branch and will be release in Glances 3.0.

Thanks for your proposal !

**Comment by Constantin07** [comment]
Much appreciated @nicolargo
