### ISSUE TITLE
System uptime reported from container and not from host

### ISSUE THREAD

**Issue by Constantin07** [nicolargo/glances#1150]
#### Description

At the moment glances runs as a Docker container and returns the uptime from container itself.
I need to monitor the uptime of the host system on which container runs.

Is there any way to pull out the host system uptime ?

#### Versions

* Glances (glances -V): Glances v2.11.1 with psutil v5.3.0
* Operating System (lsb_release -a): Ubuntu 16.04.3 LTS (Xenial Xerus)
* Used the stable version of [glances](https://hub.docker.com/r/nicolargo/glances/tags/) container 

#### Logs

Screenshot attached.
<img width="1230" alt="screen shot 2017-09-19 at 10 20 27" src="https://user-images.githubusercontent.com/11664677/30585338-683b72f8-9d24-11e7-8d88-6f7edb2c93f0.png">

**Comment by nicolargo** [comment]
Hi @Constantin07,

try to add thefollowing option to your docker run command line:

    -v /proc/uptime:/proc/uptime:ro  

Not tested and not sure it is working...

**Comment by Constantin07** [comment]
Thanks @nicolargo  Your suggestion worked fine.
