### ISSUE TITLE
Docker module doesn't export details about stopped containers

### ISSUE THREAD

**Issue by Constantin07** [nicolargo/glances#1152]
#### Description

The docker module at the moment doesn't show details about `stopped` containers.
It would be good to have this information included as well to monitor them when they go down.

#### Versions

* Glances (glances -V): Glances v2.11.1 with psutil v5.3.0
* Operating System (lsb_release -a): Ubuntu 16.04.3 LTS (Xenial Xerus)
* Used the stable version of [glances](https://hub.docker.com/r/nicolargo/glances/tags/) container

**Comment by nicolargo** [comment]
Hi @Constantin07 ,

i have made a test on a specific branch and i am not sure that it is a good idea to add stopped (exited) containers because the list is too long:

![selection_338](https://user-images.githubusercontent.com/776747/31146590-8bb2643a-a887-11e7-8f35-221477a97c12.png)

For your point of view, what is the information needed ?

**Comment by Constantin07** [comment]
Hi @nicolargo,
 I think the container `name` and `Status` should be enough.

What I suggest is to have an option in config file for docker so that reporting of stopped containers can be turned on/off depending on needs.

Does it make sense ?

**Comment by nicolargo** [comment]
Done  in the latest commit.

A new configuration key has been added (default value is False). Set it to True to display all the containers

```
[docker]
# By default, Glances only display running containers
# Set the following key to True to display all containers
all=True
```

Result:

![selection_339](https://user-images.githubusercontent.com/776747/31486860-1c60ba06-af39-11e7-9246-6bad47946bba.png)

Available in the DEVELOP branch and will be release in Glances 3.0.

**Comment by Constantin07** [comment]
Many Thanks @nicolargo I will give it a go in my environment.
