### ISSUE TITLE
Disk usage not accurate

### ISSUE THREAD

**Issue by wernight** [nicolargo/glances#1155]
#### Description

Glances reports and marks in color depending on used space but not actual disk used space. For example here it **should be marked as a critical** issue but it only marks it in red currently:

    $ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    foo              85G   81G     0 100% /foo

    FILE SYS    Used  Total
    _l/foo     80.2G  84.5G

#### Versions

* Glances (glances -V): Glances v2.11.1 with psutil v5.3.1
* Operating System (lsb_release -a): Ubuntu 14.04.5 LTS

**Comment by nicolargo** [comment]
Hi @wernight ,

do not understand the issue...

The used space is drawn in RED because the used disk space is > CRITICAL threshold (default value 90%) as define in the Glances configuration file.

```
[fs]
# Define the list of hidden file system (comma-separated regexp)
#hide=/boot.*
# Define filesystem space thresholds in %
# Default values if not defined: 50/70/90
# It is also possible to define per mount point value
# Example: /_careful=40
careful=50
warning=70
critical=90
# Allow additional file system types (comma-separated FS type)
#allow=zfs
```

**Comment by wernight** [comment]
Ah sorry I mixed up violet and red. I wonder if reporting disk usage would be better, as there it was really 100% which isn't the same at all compared to 4G free.

**Comment by wernight** [comment]
Color was correct but usage was wrong. My disk usage was 100% and glances reported 80.2G out of 84.5G. It's not wrong in term of size but wrong in term of disk usage meaning that I actually couldn't add 4 GB.

**Comment by garygreen** [comment]
I'm also getting this too. Glances calculation of disk space does seem inaccurate - for our server it reports 65G used but when doing a `df` command usage is actually 69GB

**Comment by RazCrimson** [comment]
@garygreen 
Can you just try a plain `df` without any rounding flags like `-h` and compare the result that you get with what you see in glances?

Also could you let me know the file system being used in your server in case you observe any discrepancy?
