### ISSUE TITLE
Glances won't start on Windows Server 2012R2

### ISSUE THREAD

**Issue by ohadbenita** [nicolargo/glances#1157]
I run Glances using glances -c server_ip 

> Traceback (most recent call last):
  File "C:\Python27\Scripts\glances-script.py", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "c:\python27\lib\site-packages\glances\__init__.py", line 134, in main
    start(config=config, args=args)
  File "c:\python27\lib\site-packages\glances\__init__.py", line 103, in start
    mode.serve_forever()
  File "c:\python27\lib\site-packages\glances\client.py", line 238, in serve_forever
    if not self.login():
  File "c:\python27\lib\site-packages\glances\client.py", line 180, in login
    self.screen = GlancesCursesClient(config=self.config, args=self.args)
  File "c:\python27\lib\site-packages\glances\outputs\glances_curses.py", line 104, in __init__
    self.screen = curses.initscr()
NameError: global name 'curses' is not defined

Glances v2.11.1 with psutil v5.3.1

Any help is appreciated

**Comment by nicolargo** [comment]
The Curses interface is not available in Windows OS (shame on Microsoft).

Two workarounds:
1) use a Glances client in a GNU/Linux terminal
2) Use the Web server instead of the RCP Server and monitor your Windows OS from a remote Web browser.

**Comment by ohadbenita** [comment]
Thanks for that,

Can you elaborate (in a newbie) level how can this be done ?
1. Are you referring to using Glances client on a Linux VM running on this Windows machine ?
2. Would I still be able to connect from home assistant based Glances server to the client's glances instance ?

Thanks for the info

**Comment by nicolargo** [comment]
If you are a newbie, the second solution is the simple.

So start the Glances server on the machine you want to monitor:

    glances -w

On the client machine, start your Web browser and enter the following URL: http://<@ipserver>:61208/

**Comment by jack10bells** [comment]
Hi, I´ve got an issue but don´t know if it is about W2012 or something else. I need actions to be executed as the server starts up without a web client connect to it.
How can I do that?
