### ISSUE TITLE
Underscores in File sys and Network section

### ISSUE THREAD

**Issue by muhahacz** [nicolargo/glances#1161]
#### Description

I have some weird underscores in File Sys section. It is also in Network section, ( First one should be br-b3b112008c9c

Maybe another bug:
There is also suspicious cpu value in docker section. 
Docker stats output on host:
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
c8cc4349cf8f        0.10%               25.53MiB / 1.87GiB   1.33%               0B / 0B             0B / 0B             3
```
Image:
https://imgur.com/a/AAAZw

P.S. I have same problem with your docker image.

#### Versions

* Glances (glances -V): 2.11.1
* PSutil (glances -V): 5.3.1
* Operating System (lsb_release -a): Alpine 3.6 - Docker image / Ubuntu 17.04 - Host

#### Dockerfile

```
FROM alpine:latest

ENV GLANCES_VERSION 2.11.1

RUN apk add --no-cache python3  && \
    apk update && apk upgrade && apk add --no-cache --virtual build-dependencies gcc musl-dev python3-dev linux-headers && \
    pip3 install glances==${GLANCES_VERSION} \
                psutil \
                netifaces \
                bottle \
                hddtemp \ 
                docker \
                py-cpuinfo  && \
    apk del build-dependencies


EXPOSE 61209
EXPOSE 61208


ENTRYPOINT python3 -m glances -C /opt/glances/glances.conf -w
```

**Comment by nicolargo** [comment]
It is not a bug, it is a feature...

When the length of the File system name or network interface is too long to be displayed in the user interface, Glances truncates it and add a '_' caracter to the begin of the line.

**Comment by nicolargo** [comment]
REJECTED: not a bug

**Comment by muhahacz** [comment]
@nicolargo 

Thanks

ad1: I guess its not possible to override this behaviour, right? I dont even know, what _olv.conf, hostanem, tc/hosts mean....  (/etc/resolv.conf, /etc/hostname, /etc/hosts ?) Why is it there?

ad2: There should be a consistency between docker stats command (output above, docker api, =  0.10% ) and glances output (541%). It was measured in the same time.
