### ISSUE TITLE
Feature request: Mount proc and sys from host, run glances with prefix to look for stats

### ISSUE THREAD

**Issue by muhahacz** [nicolargo/glances#1163]
Netdata does something like this: --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro 
Then you can start netdata with  -s /host  parameter
Same ability to mount volumes from hosts for glances would be much more consistent in glances behaviour.
Thanks

**Comment by nicolargo** [comment]
Do not understand... Can you (re)explain ?

**Comment by nicolargo** [comment]
Rejected cause: do not understand the issue...
