### ISSUE TITLE
Wrong total disk size on large size disk on macOS using APFS format

### ISSUE THREAD

**Issue by chuanconggao** [nicolargo/glances#1164]
#### Description

Glances report wrong total disk size on my large 20TB disk on macOS 10.13 using APFS format. The total usage size is correct and disk size is in green color. 
```
_ore Data  33.7G  2.19T
```
When switching to showing available size, the disk size is also in green color.
```
_ore Data  2.16T  2.19T
```
There is no error on computing the usage size and usage percentage. It seems it is just a bug for formatting the total disk size.

`df -h` reports the right one.
```
/dev/disk5s1     19T   34G   19T   1% /Volumes/Core Data
```

#### Versions

* Glances (glances -V): v2.11.1
* PSutil (glances -V): v5.4.0
* Operating System (lsb_release -a): macOS 10.13

**Comment by nicolargo** [comment]
Strange...

Can you enter the following commands in a terminal and show us the result:

    # python
    >>> psutil.disk_usage('/dev/disk5s1')

**Comment by chuanconggao** [comment]
The output from psutil is even more weird. All my four disks have the same output on both Python 2 (with psutil 5.3.1) and Python 3 (with psutil: 5.4.0). 

```
>>> import psutil
>>> psutil.disk_usage('/dev/disk1')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk1s1')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk5')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk5s1')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk2')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk2s3')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk3')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
>>> psutil.disk_usage('/dev/disk3s1')
sdiskusage(total=209408, used=209408, free=0, percent=100.0)
```

**Comment by nicolargo** [comment]
@giampaolo Any idea ?

**Comment by giampaolo** [comment]
`disk_usage` relies on `os.statvfs`, that's where those numbers come from. Same goes for stdlib `shutil.disk_usage` so this problem is not related to psutil per se. I wonder what `df` cmdline utility uses on Mac.

**Comment by chuanconggao** [comment]
After I pour some data on my disk, the output looks like this now.

The usage size is negative now, and in blue color.
```
_ore Data-15169957355520   2.19T
```
The available size is correct now, also in blue color.
```
_ore Data  16.0T  2.19T
```

My current `df -h` output is:
```
/dev/disk5s1     19T  2.3T   16T  13% /Volumes/Core Data
```

**Comment by nicolargo** [comment]
@chuanconggao what is the output of:

python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.statvfs('/dev/disk5s1')
>>> import psutil
>>> psutil.disk_usage('/dev/disk5s1')

If it is a os.statvfs() issue, need to track it on the official Python repository ==> https://github.com/python/cpython

**Comment by giampaolo** [comment]
Right, but I doubt it's a Python issue. Most likely it's gonna be a OSX kernel issue. It wouldn't be the first time (e.g. I remember all sorts of bad things with poll() sysctl on OSX).

**Comment by chuanconggao** [comment]
@nicolargo The output is:
```
In [1]: import os                                                    
In [2]: os.statvfs('/dev/disk5s1')
Out[2]: os.statvfs_result(f_bsize=512, f_frsize=512, f_blocks=419, f_bfree=0, f_bavail=0, f_files=726, f_ffree=0, f_favail=0, f_flag=0, f_namemax=255)

In [3]: import psutil
In [4]: psutil.disk_usage('/dev/disk5s1')
Out[4]: sdiskusage(total=214528, used=214528, free=0, percent=100.0)
```

**Comment by nicolargo** [comment]
REJECTED: not a Glances issue.
