### ISSUE TITLE
Hard requirement on bottle for Windows?

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#1167]
Sorry for the rather basic question. Why is `bottle` needed for Windows?

https://github.com/nicolargo/glances/blob/0adf1392568b10cbbf69ea56771db988e9767b2b/setup.py#L40-L45

**Comment by nicolargo** [comment]
Because there is no more Curses interface. Web UI is the default one for Windows OS.

Please only use Github to fill issue or enhancement request, there is a forum for this kind of question https://groups.google.com/forum/?hl=en#!forum/glances-users

**Comment by jakirkham** [comment]
I see. Thanks. Should `requests` be a hard requirement for Windows too since it seems to be needed for the web interface as well?
