### ISSUE TITLE
Add a new output mode to stdout

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1168]
#### Description

Request from the forum: https://groups.google.com/forum/?hl=en#!topic/glances-users/eFFwLDhhHOU

Hi,

in 'top' I can do this to pipe one iteration into a text file:

top -n 1 -b > top-output.txt

Is this possible with glances too?

If it it would be very nice if this feature could be added.

Regards,

Christian

**Comment by nicolargo** [comment]
Proposed implementation:

```
glances --stdout cpu.user,mem.used,load
cpu.user: 25.0
mem.used: 3853836288
load: {'cpucore': 4, 'min1': 2.13, 'min5': 1.11, 'min15': 0.73}
cpu.user: 3.8
mem.used: 3846971392
load: {'cpucore': 4, 'min1': 2.04, 'min5': 1.11, 'min15': 0.74}
cpu.user: 2.5
mem.used: 3846090752
load: {'cpucore': 4, 'min1': 1.88, 'min5': 1.09, 'min15': 0.73}
...
```

**Comment by nicolargo** [comment]
Ok merged in the DEVELOP branch.

Please test !

**Comment by notFloran** [comment]
Looks good to me ! No problem with mac
