### ISSUE TITLE
Docker plugin - Implement Rancher Python Lib

### ISSUE THREAD

**Issue by joe307bad** [nicolargo/glances#1169]
#### Description

After running the following command from the docker image documentation: 

`docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances`

The docker container spins up and is the web UI accessible within my local network via port number 61208

The issue is that I have other containers running on this server that I would like to see, but no containers are viewable via the glances web UI.

Whenever running glances without a docker container, I can view the host's containers, presumably because glances is not running within a container.

#### Versions

* Glances (glances -V): not sure how to ascertain this information. Whenever I go into the docker container via `docker exec -it glances bash` and run the `glances -v` command I get the error `gla`nces command not found
* PSutil (glances -V):
* Operating System (lsb_release -a): Again, not sure how this is utilized. I am using RancherOS

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

Where is the logs file located for the docker container?

**Comment by joe307bad** [comment]
After doing more research, this may have to do with RancherOS not exposing the docker remote API. Does the glances docker container rely on the docker remote api of the host server being exposed?

**Comment by nicolargo** [comment]
Yes, Glances uses the standard Python Docker lib to retrieve containers stats through the API. To do this, Glances uses the /var/run/docker.sock host file (thanks to the -v /var/run/docker.sock:/var/run/docker.sock:ro option). 

If you found how to correct this issue, please feel free to add a new comment !

**Comment by nicolargo** [comment]
One clean solution will be to use the official Rancher Python Lib to get stats from Rancher API.

==> https://github.com/hivesolutions/rancher_api

Need contributors to implement this feature...

**Comment by joe307bad** [comment]
It seems as if this has been resolved. I can now run Glances in a docker container and see all the containers in the web UI using Rancher 1.5.2 and Glances 3.1.2.
