### ISSUE TITLE
OS specific arguments should be documented and reported

### ISSUE THREAD

**Issue by mapio** [nicolargo/glances#1180]
I agree that is perfectly fine to disable some features according to the OS, but instead of adding options conditionally as in 

https://github.com/nicolargo/glances/blob/7fc0f887e450e71772e3f64c913c6e3a132ef8e3/glances/main.py#L246-L251

it should be probably better to emit a specific warning, or at least to note it in the documentation.

**Comment by nicolargo** [comment]
Added to the documentation in the last commit (DEVELOP branch).
