### ISSUE TITLE
Speedometer (network histogram) sidebar ((and in-terminal graphic capabilities))

### ISSUE THREAD

**Issue by thorsummoner** [nicolargo/glances#1187]
#### Description

[speedometer <sup>pypi [↗]</sup>](https://pypi.python.org/pypi/Speedometer) integration (for active network interfaces)

Speedometer does an excellent job of drawing time-series bargraphs via utf-8 character in a terminal, screenshot:
![speedometer-256.png](https://excess.org/media/speedometer-256.png)

I noticed I tend to tmux speedometer together with glances, and also speedometer is annoying to launch given it expects the network interfaces to be launched ahead of time. This is the kind of information glances already collects.

I didn't check what toolkit glances is using for rendering, it may not nicely integrate with the [urwid <sup>pypi [↗]</sup>](https://pypi.python.org/pypi/urwid/) toolkit that powered speedometer, however if it does, it might open up a door for graphing more system stats in real time, which would be pretty amazing.

I also get that this feature request is a long shot, I dont mind taking a crack at it myself, if you want to 'permit' the feature as a possible in-scope thing. (Or maybe you can point me at an extension interface so I can recycle a lot of glances into my own tool/wrapper)

edit: this might also be a bit of an integration nightmare for package maintainers, as speedometer isn't exactly formated like its meant to be used as a library, that might be worth lobbying for on the speedometer project, a stable widget interface for binding to.

**Comment by nicolargo** [comment]
An alternative to this (the Glances interface is already full and i do not see where i can integrate Speedometer), will be to add a new line to the Quicklook plugin in order to follow the network bitrate thanks to --sparkline option:

![image](https://github.com/nicolargo/glances/assets/776747/8eb63486-e20f-4b81-a556-b19ac44bce9c)

I close this issue and open another one.
