### ISSUE TITLE
Update problem - Fedora 27

### ISSUE THREAD

**Issue by Matteofalafel** [nicolargo/glances#1190]
Good evening,

I tried to update glances from 2.7.1 version to 2.11.1 but didn't' work, this is the problem that occurred.
As I said before I am using Fedora 27 as the operating system.

![screenshot from 2017-11-19 16-39-45](https://user-images.githubusercontent.com/33809495/32996642-480c7494-cd7d-11e7-9f53-5d06f6982145.png)

Thanks in advance

**Comment by nicolargo** [comment]
The pip command needs root account. Use sudo:

    sudo pip install --upgrade glances

All is explain in the manual... 
So RTFM...
