### ISSUE TITLE
display info for second battery

### ISSUE THREAD

**Issue by senorsmile** [nicolargo/glances#1193]
#### Description

enhancement: On T & X series thinkpads (and some P), there are two batteries.  On my p51s, only BAT0 is displayed.  

#### Versions

- Glances v2.11.1 with psutil v5.4.1
- Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by nicolargo** [comment]
Need additional information:

1. Is Batinfo installed on your system ? 

    pip list | grep batinfo

2. if yes, please show us the result of:

    # python
    import batinfo
    print(batinfo.batteries())

3. if not:

    # python
    import psutil
    psutil.sensors_battery()

Thanks !

**Comment by senorsmile** [comment]
Greetings!

```
$ pip list | grep batinfo
batinfo (0.4.2)
```

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import batinfo
>>> print(batinfo.batteries())
<batinfo.battery.Batteries object at 0x7fce220e8b10>
```

I also did the psutil version... why not?
```
>>> import psutil
>>> psutil.sensors_battery()
sbattery(percent=100.0, secsleft=-2, power_plugged=True)
```

**Comment by senorsmile** [comment]
I take it back.. after comparing the output in glances with ```acpi```
I realize that it's simply combining the two batteries and presenting a single total.  This wasn't clear at first but makes sense.
