### ISSUE TITLE
windows 10 stuck on landing page

### ISSUE THREAD

**Issue by phairplay** [nicolargo/glances#1196]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances v2.11.1 
* psutil v4.3.1
* Windows 10

#### Logs

no glances folder created

hi ive jist installed glances and im stuck on the landing page im currently running python 2.7 and currently not able to upgrade due to certain scripts which need it.

how can i get your program to work as i would love to link it to home assistant

here is w debbug log

192.168.0.21 - - [01/Dec/2017 21:19:19] "GET / HTTP/1.1" 200 917
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /css/normalize.min.css HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /css/bootstrap.min.css HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /css/style.min.css HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /js/vendor.min.js HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /js/main.min.js HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /js/templates.min.js HTTP/1.1" 304 0
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /api/2/all/limits HTTP/1.1" 200 2952
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /api/2/config HTTP/1.1" 200 1587
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /api/2/args HTTP/1.1" 200 1974
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /api/2/all HTTP/1.1" 404 812
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /api/2/all/views HTTP/1.1" 200 236338
192.168.0.21 - - [01/Dec/2017 21:19:19] "GET /images/glances.png HTTP/1.1" 304 0

**Comment by notFloran** [comment]
Can you go to `http://localhost:61208/`, open the web console (for [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) , for [Chrome](https://developer.chrome.com/devtools/docs/console)) and paste me back the result.

**Comment by phairplay** [comment]
After rebooting a few times while installing a few other programs it’s now working. Many thanks for the quick response.
