### ISSUE TITLE
Web browser is not working with Glances 2.11.1 in Debian stretch

### ISSUE THREAD

**Issue by raushanjha146** [nicolargo/glances#1198]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

I am using glances 2.7.1.1-2  on our debian-stretch system. 
when running glances -w or glances -s, got the error "ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)"

step:
install glances 2.7
run- glances
    After few seconds you will shee the error of open ssl, and then format will be changed.

run- glances -w
   you will get the openssl exception

#### Versions

* Glances (glances -V): 2.7.1 (Glances v2.7.1 with psutil v5.0.1)
* PSutil (glances -V): 5.0.1
* Operating System (lsb_release -a): debian stretch

#### Logs

complete error is given below:
-----------------------------------
asdf@systen123:~$ glances -w
Glances web server started on http://0.0.0.0:61208/
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 417, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1426, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1174, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 323, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 424, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/glances/amps/glances_amp.py", line 201, in update_wrapper
    return self.update(process_list)
  File "/usr/lib/python3/dist-packages/glances/amps/glances_nginx.py", line 80, in update
    res = requests.get(self.get('status_url'))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

---------------------------------------

**Comment by nicolargo** [comment]
No idea... Perhaps have a look on https://github.com/requests/requests/issues/4247#issuecomment-323440886

**Comment by nicolargo** [comment]
Try with the latest stable version (Glances 2.11.1).

**Comment by raushanjha146** [comment]
I download the Glances 2.11.1(from debian sid repo). OpenSSL problem was not found in that version.
glances version: Glances v2.11.1 with psutil v5.0.1

run : glances -w

console:
raushan@raushan:~$ glances -w
Glances web server started on http://0.0.0.0:61208/

hitting the IP:port from browser:
http://<IP>:61208/

in this case glances UI doesn't show any details. 

**Glances Logs are given below:**
2017-12-10 16:10:34,781 -- INFO -- Start Glances 2.11.1
2017-12-10 16:10:34,781 -- INFO -- CPython 3.5.3 and PSutil 5.0.1 detected
2017-12-10 16:10:34,784 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2017-12-10 16:10:34,792 -- INFO -- Start GlancesWebServer mode
2017-12-10 16:10:35,420 -- ERROR -- Could not import pynvml.  NVIDIA stats will not be collected.
2017-12-10 16:10:35,426 -- WARNING -- PsUtil 5.1.0 or higher is needed to grab temperatures sensors
2017-12-10 16:10:35,426 -- WARNING -- PsUtil 5.2.0 or higher is needed to grab fans sensors
2017-12-10 16:10:35,570 -- INFO -- Glances web server started on http://0.0.0.0:61208/
2017-12-10 16:46:05,872 -- INFO -- Start Glances 2.11.1
2017-12-10 16:46:05,872 -- INFO -- CPython 3.5.3 and PSutil 5.0.1 detected

**browser logs:**

Uncaught Error: [$injector:modulerr] Failed to instantiate module glancesApp due to:
Error: [$injector:modulerr] Failed to instantiate module cfp.hotkeys due to:
Error: [$injector:nomod] Module 'cfp.hotkeys' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.10/$injector/nomod?p0=cfp.hotkeys
    at http://10.98.0.176:61208/js/vendor.min.js:69:12
    at http://10.98.0.176:61208/js/vendor.min.js:2130:17
    at ensure (http://10.98.0.176:61208/js/vendor.min.js:2054:38)
    at module (http://10.98.0.176:61208/js/vendor.min.js:2128:14)
    at http://10.98.0.176:61208/js/vendor.min.js:4667:22
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at http://10.98.0.176:61208/js/vendor.min.js:4668:40
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=cfp.hotkeys&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'cfp.hotkeys'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dcfp.hotkeys%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2130%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2054%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2128%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4667%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)
    at http://10.98.0.176:61208/js/vendor.min.js:69:12
    at http://10.98.0.176:61208/js/vendor.min.js:4690:15
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at http://10.98.0.176:61208/js/vendor.min.js:4668:40
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at createInjector (http://10.98.0.176:61208/js/vendor.min.js:4573:19)
    at doBootstrap (http://10.98.0.176:61208/js/vendor.min.js:1806:20)
    at bootstrap (http://10.98.0.176:61208/js/vendor.min.js:1827:12)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=glancesApp&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20cfp.hotkeys%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'cfp.hotkeys'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dcfp.hotkeys%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2130%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2054%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2128%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4667%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fmodulerr%3Fp0%3Dcfp.hotkeys%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'cfp.hotkeys'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.10%252F%2524injector%252Fnomod%253Fp0%253Dcfp.hotkeys%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A69%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2130%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2054%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2128%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4667%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4651%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4668%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4651%253A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4690%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4573%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A1806%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A1827%3A12)
    at http://10.98.0.176:61208/js/vendor.min.js:69:12
    at http://10.98.0.176:61208/js/vendor.min.js:2130:17
    at ensure (http://10.98.0.176:61208/js/vendor.min.js:2054:38)
    at module (http://10.98.0.176:61208/js/vendor.min.js:2128:14)
    at http://10.98.0.176:61208/js/vendor.min.js:4667:22
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at http://10.98.0.176:61208/js/vendor.min.js:4668:40
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=cfp.hotkeys&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'cfp.hotkeys'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dcfp.hotkeys%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2130%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2054%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2128%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4667%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)
    at http://10.98.0.176:61208/js/vendor.min.js:69:12
    at http://10.98.0.176:61208/js/vendor.min.js:4690:15
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at http://10.98.0.176:61208/js/vendor.min.js:4668:40
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at createInjector (http://10.98.0.176:61208/js/vendor.min.js:4573:19)
    at doBootstrap (http://10.98.0.176:61208/js/vendor.min.js:1806:20)
    at bootstrap (http://10.98.0.176:61208/js/vendor.min.js:1827:12)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=glancesApp&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20cfp.hotkeys%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'cfp.hotkeys'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3Dcfp.hotkeys%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2130%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2054%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A2128%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4667%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fmodulerr%3Fp0%3Dcfp.hotkeys%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'cfp.hotkeys'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.10%252F%2524injector%252Fnomod%253Fp0%253Dcfp.hotkeys%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A69%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2130%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2054%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A2128%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4667%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4651%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4668%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.98.0.176%253A61208%252Fjs%252Fvendor.min.js%253A4651%253A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A69%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4690%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4668%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4651%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A4573%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A1806%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2F10.98.0.176%3A61208%2Fjs%2Fvendor.min.js%3A1827%3A12)
    at http://10.98.0.176:61208/js/vendor.min.js:69:12
    at http://10.98.0.176:61208/js/vendor.min.js:4690:15
    at forEach (http://10.98.0.176:61208/js/vendor.min.js:326:20)
    at loadModules (http://10.98.0.176:61208/js/vendor.min.js:4651:5)
    at createInjector (http://10.98.0.176:61208/js/vendor.min.js:4573:19)
    at doBootstrap (http://10.98.0.176:61208/js/vendor.min.js:1806:20)
    at bootstrap (http://10.98.0.176:61208/js/vendor.min.js:1827:12)
    at angularInit (http://10.98.0.176:61208/js/vendor.min.js:1712:5)
    at http://10.98.0.176:61208/js/vendor.min.js:32538:5
    at HTMLDocument.trigger (http://10.98.0.176:61208/js/vendor.min.js:3254:7)

**Comment by nicolargo** [comment]
@notFloran Any idea ?

**Comment by notFloran** [comment]
@raushanjha146 Can you try to clear the cache ? or open glances in a incognito window

**Comment by raushanjha146** [comment]
@notFloran I tried and check the browser console log. the same log is showing.

**Comment by notFloran** [comment]
@raushanjha146 Can you open http://0.0.0.0:61208/js/vendor.min.js and try to search `angular.module('cfp.hotkeys'` ?

**Comment by raushanjha146** [comment]
[vendor.min.js.zip](https://github.com/nicolargo/glances/files/1546794/vendor.min.js.zip)
@notFloran angular.module('cfp.hotkeys' is not found in vendor.main.js file.
file is attached.

**Comment by notFloran** [comment]
I think it's a cache error : the v2.11 version use AngularJS v1.6.6 (see [vendor.min.js](https://raw.githubusercontent.com/nicolargo/glances/v2.11.1/glances/outputs/static/public/js/vendor.min.js)) but the file uploaded by @raushanjha146 indicate AngularJS 1.5.10.

Can you try the WebUi in a different browser to be sure that's a cache issue ? 

Or download the "http://0.0.0.0:61208/js/vendor.min.js " file with curl/wget and check the angularjs version at the beginning of the file.

**Comment by raushanjha146** [comment]
I checked the  vendor.min.js file, it is showing v1.5.10.
I checked the file in "/usr/share/javascript/angular.js/angular.js" and "/usr/lib/python3/dist-packages/glances/outputs/static/public/js/vendor.min.js", the version is the same( v1.5.10).

Again i tried to identify the issue. the complete workaround is given below:

- I removed and purge the glances package.
- check the AngularJS version in "/usr/share/javascript/angular.js/angular.js" file. it is 1.5.10. "/usr/lib/python3/dist-packages/glances/outputs/static/public/js/vendor.min.js" file/symlink not exist.
- Install again the glances v-2.11.1
- check the AngularJS version in "/usr/share/javascript/angular.js/angular.js" file. it is still 1.5.10. In "/usr/lib/python3/dist-packages/glances/outputs/static/public/js/vendor.min.js", the AngularJS version is the same(1.5.10).
- I checked the glances source. in Debian/glances.link file it is creating a link of existing AngularJS file.
**_usr/share/javascript/angular.js/angular.js usr/lib/python3/dist-packages/glances/outputs/static/public/js/vendor.min.js**_

So, "http://0.0.0.0:61208/js/vendor.min.js " file showing the version v1.5.10 not v1.6.6.

@notFloran Please suggest !!

**Comment by notFloran** [comment]
@raushanjha146 Thanks for this detailed report !

With your report I understand the issue: the debian package replace `vendor.min.js` with the angularjs version provided by Debian but the `vendor.min.js` contains angulars + others dependencies (like  `cfp.hotkeys`).

So the debian package breaks two things : 

* the version of angular : 1.6 -> 1.5 (
* the dependancies included in vendor.min.js

Any ideas @nicolargo @nclsHart ?

**Comment by nicolargo** [comment]
Nope. I will send an email to the Glances'Debian packet manager.

**Comment by sbadia** [comment]
Hi, indeed, it's a issue packaging side, I take a look

**Comment by sbadia** [comment]
It should be ok, with 2.11.1-2 ( https://tracker.debian.org/news/893294 ).
Thanks for your help!

**Comment by nicolargo** [comment]
@Thanks you @sbadia !

**Comment by raushanjha146** [comment]
Thanks @nicolargo @notFloran @sbadia 
but when open the web browser in Tablets/mobile(smalss screen), the data is overlapped. 
Can any one suggest anything.
