### ISSUE TITLE
[WebUI] --fahrenheit option do not take into account

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1200]
#### Description

Start Glances with the --fahrenheit option (to switch sensor temperature in fahrenheit).

On the Curses UI (OK):

![selection_348](https://user-images.githubusercontent.com/776747/33959008-781564a8-e046-11e7-9a25-78f1b3468449.png)

On the Web UI (Not OK):

![selection_347](https://user-images.githubusercontent.com/776747/33959013-7a3a662a-e046-11e7-862f-712b7f4cc0f8.png)

#### Versions

* Glances (glances -V): 2.11.1
* PSutil (glances -V): 5.4
* Operating System (lsb_release -a): Ubuntu 16.04.3 LTS 

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
@notFloran Can you have a look?

**Comment by notFloran** [comment]
@nicolargo Do you want the fix for master or develop?

**Comment by nicolargo** [comment]
Develop, it is not a critical bug.
