### ISSUE TITLE
Context switches bottleneck identification

### ISSUE THREAD

**Issue by realies** [nicolargo/glances#1212]
Running kernel 4.14.9 on Ryzen 1700 and Glances in a container. `ctx_sw` is constantly displayed in red despite values in the `10000-20000` range. Noticed there's a [bottleneck value](https://github.com/nicolargo/glances/blob/4dd873ac0e269b6597d2de26cd2fe104e4f11437/glances/config.py#L170) defined with an index of `56000`. Why would that value be critical to a system?

**Comment by nicolargo** [comment]
Hi @realies ,

by default the Context Switch bottleneck value is set to 56000/<number of CPU core> (read this article http://old.koetzingit.de/index.php?option=com_content&task=view&id=196&Itemid=260).

Nevertheless, you can set the threshold to others values using the glances.conf file:

```
[cpu]
# Context switch limit (core / second)
# Leave commented to just use the default config (critical is 56000/# (of CPU core))
ctx_switches_careful=10000
ctx_switches_warning=12000
ctx_switches_critical=14000
```

**Comment by realies** [comment]
Thanks for the reply. This article is from 2006, CPUs have gone a long way since then. It states that a value of `56000` would be alerting for a quad CPU system. This alone does not translate correctly in the `ctx_switches_bottleneck` value calculation.

Since multi-core CPUs were introduced around 2005, it seems fair to assume the values taken from Citrix Resource Manager by the time the article is written could have been related to single core CPUs. If this is true, `ctx_switches_bottleneck` should be equal to `14000 * multiprocessing.cpu_count()` instead.

The bigger question is, how is critical context switching frequency estimated and how does it relate to different CPU architectures.

**Comment by nicolargo** [comment]
@realies Agree with you. The current threshold formula is not correct. I read others posts on context switch monitoring and i found this interesting article: https://www.percona.com/blog/2017/11/09/mysql-linux-context-switches/

On my 4-Core system, if i generate a lot of threads:

    sysbench --num-threads=1024 --test=threads run

the context switch go up to 2M (so 500K per logical CPU). I propose to set the threshold limit to 10% (50K per logical CPU as said in the article).

What do you think ?

**Comment by realies** [comment]
Looks great. Looking to run a `sysbench` on a few architectures and report on results.

**Comment by realies** [comment]
Interestingly, running `sysbench --num-threads=1024 --test=threads --time=7200  run ` on an ` i7-4980HQ` on `Darwin 10.13.2 64bit` makes `ctx_sw` go up to only 8K and it does go into negative values while the benchmark is running. Quitting a browser with multiple tabs open makes `ctx_sw` spike to about 128K. Is context switching detected incorrectly under macOS or is `sysbench` not acting as expected on this platform?

**Comment by realies** [comment]
Apologies for the delay.

`sysbench --num-threads=1024 --test=threads --time=60 run` produced values between `-6000` and `300`.

`sysbench  --num-threads=2048 --test=threads --time=60 run` produces values between `-1500` and `7K`

Unable to allocate enough memory for a `4096` threads test. Are negative values possible at all?

```
$ uname -a    
Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```
