### ISSUE TITLE
glances -w  -C glances.conf   command error

### ISSUE THREAD

**Issue by 2892931976** [nicolargo/glances#1213]
glances -w -p 63999 --password="123456"   command error

**Comment by 2892931976** [comment]
“glances -w -C glances.conf”   How glances.conf documents set up passwords and users, there are examples

**Comment by notFloran** [comment]
Hi @2892931976 

To set up a password you must execute `glances -w -p 63999 --password` then glances will ask you for the password and save it to a `glances.pwd` file.

<img width="412" alt="capture d ecran 2018-01-05 a 22 48 48" src="https://user-images.githubusercontent.com/523981/34630028-ad459a36-f26a-11e7-8dc9-bccaa31c2d13.png">

**Comment by 2892931976** [comment]
Thank you! Solve the problem
