### ISSUE TITLE
Default alerts for io wait on CPU plugin seem wrong

### ISSUE THREAD

**Issue by rocketraman** [nicolargo/glances#1214]
#### Description

IO Wait on Linux is a form of idle time. Its an indication that the processor is idle while one or more process is doing I/O. It doesn't necessarily indicate a problem, unless that I/O is itself taking a long time. This is a good description of it:

https://blog.pregos.info/wp-content/uploads/2010/09/iowait.txt

Given this information, I'm not sure that the following default configuration of the CPU plugin makes sense:

```
iowait_careful=50
iowait_warning=70
iowait_critical=90
```

On a very fast mostly idle system, writing to rotational disks often causes Glances to produce critical CPU_IOWAIT alerts, simply because writing to rotational disks is slow and the CPU is doing nothing else at the time. These alerts don't actually mean anything is wrong though.

#### Versions

```
# glances -V
Glances v2.7.1 with psutil v5.0.1
```

* Operating System (lsb_release -a):

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix
```

**Comment by nicolargo** [comment]
The default value are not 50/70/90 but a percent based on the formula "1/Number of Core * 100" (see this post: http://blog.scoutapp.com/articles/2011/02/10/understanding-disk-i-o-when-should-you-be-worried).

**Comment by rocketraman** [comment]
@nicolargo  I have a ThreadRipper 32 core system, so if I'm reading the code correctly that results in the values:

2.5%
2.8125%
3.125%

If I'm understanding correctly, that's even worse than I thought initially. An I/O wait of 3.125% on a mostly idle system that is writing to rotational disk would be quite normal, which explains why I often get the critical CPU_IOWAIT alert from glances. Is this the right default?

**Comment by nicolargo** [comment]
Yes, but you can overwrite this setting in the glances.conf file.

**Comment by rocketraman** [comment]
> Yes, but you can overwrite this setting in the glances.conf file.

Thank you, I have done this.

**Comment by Memphizzz** [comment]
@rocketraman I think I have the same issue. Can you tell me how you calculated the OK values for your system so I can adjust my glances.conf as well? I get critical IOWAIT warnings every time the system has to do almost any work.

**Comment by rocketraman** [comment]
@Memphizzz Yeah, the default values in Glances really only work for a core count less than 4 or so... the source article referenced by @nicolargo doesn't really present a good understanding of IO wait, which is really a form of idle time, not (necessarily) of slow or overloaded I/O. The blog I referenced in the OP (https://blog.pregos.info/wp-content/uploads/2010/09/iowait.txt) has a very good explanation of this.

I used these values on my 32-core system, but could probably even go to 10/20/30:

```
[cpu]
user_careful=50
user_warning=70
user_critical=90
# Defaults: https://github.com/nicolargo/glances/issues/1214
iowait_careful=20
iowait_warning=30
iowait_critical=40
system_careful=50
system_warning=70
system_critical=90
steal_careful=50
steal_warning=70
steal_critical=90
```

**Comment by Memphizzz** [comment]
I have a host machine with a total of 24 cores. It has some virtual machines running which I gave 8 cores each. With 8 cores per machine, can you suggest values to try and keep adjusting? None of them do excessive HDD work. Mostly servers like teamspeak etc which work in RAM. Only one of them runs an apt-mirror which shows up in glances as a warning as soon as it starts updating. Thanks for the article and your quick reply!

**Comment by rocketraman** [comment]
> With 8 cores per machine, can you suggest values to try and keep adjusting

Try different workloads and print io/wait periodically with vmstat to understand your workload (and identify issues, if any), then set your glances thresholds accordingly.

**Comment by Memphizzz** [comment]
I see, thats a good Idea. Thank you very much!

**Comment by maravento** [comment]
> Sí, pero puede sobrescribir esta configuración en el archivo lookings.conf.

What is the path of that file?

**Comment by maravento** [comment]
This thread needs to be opened. The explanations provided do not clarify the problem.
- What about servers? (for example, HPE servers with Xeon processors last gen)
- What would be the correct values for servers?
- Where are these values modified?
- If this alert means nothing, then why does it exist or where is it deactivated?

too many questions without clarification
