### ISSUE TITLE
Nice Process Priority Configuration

### ISSUE THREAD

**Issue by patrodyne** [nicolargo/glances#1218]
#### Description

Enhancement: Implement configuration for 'nice' values. Define color levels using a comma separated list of 'nice' values for `nice_careful`, `nice_warning` and/or `nice_critical`. The list may contain negative, positive or zero values.

```
[processlist]
# Nice priorities range from -20 to 19. 
# Configure nice levels using a comma separated list.
#
# Nice: Example 1, non-zero is warning
# nice_warning=-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
#
# Nice: Example 2, low priority processes escalate from careful to critical
# nice_careful=1,2,3,4,5,6,7,8,9
# nice_warning=10,11,12,13,14
# nice_critical=15,16,17,18,19
```
#### Versions

* Glances (glances -V): v2.3 
* PSutil (glances -V): v3.4.2
* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

#### Logs

N/A

**Comment by nicolargo** [comment]
Ok done and merged in the DEVELOP branch (will be available in Glances 3.0).

@patrodyne Can you test it on the develop branch ?
