### ISSUE TITLE
InfluxDB error during stat conversion

### ISSUE THREAD

**Issue by goofballtech** [nicolargo/glances#1222]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description
I'm having an export to influxDB issue. I have installed all dependencies as per the website just to make sure something else wasn't holding it up. I have been searching and have not yet found anything close enough to be relevant. 

I started out with a basic glances.exe --export-influxdb

I have gone through the process so i am now running 

glances.exe --disable-hddtemp --disable-wifi --disable-docker --export-influxdb -d

I am getting so many "InfluxDB error during stat conversion" with what looks like fair data in the ines before. Not sure where to go from here to have that data import properly.

I am still getting the occasion errors that i believe should be negated by disabling docker and hddtemp as well. 

#### Versions

* Glances (glances -V):2.11.1
* PSutil (glances -V):5.4.3
* Operating System (lsb_release -a):Windows Server 2012

#### Logs
Debug Log
https://pastebin.com/65X7nGk5

**Comment by nicolargo** [comment]
There is only two errors on your log file:

```
2018-01-18 12:27:17,528 -- ERROR -- Cannot export localhost.sensors stats to InfluxDB (400: {"error":"unable to parse 'localhost.sensors ': invalid field format"}
)
2018-01-18 12:27:17,529 -- ERROR -- Cannot export localhost.docker stats to InfluxDB (400: {"error":"unable to parse 'localhost.docker ': invalid field format"}
)
```

The others are DEBUG messages because InfluxDB only accept numerical stats.

Example:

```
2018-01-18 12:28:48,301 -- DEBUG -- InfluxDB error during stat convertion 0.key=cpu_number (could not convert string to float: cpu_number)
```

InfluxDB can not store "cpu_number".

For me everything is ok...

Have you check if there is anything in the InfluxDB database ?

**Comment by goofballtech** [comment]
Yes. InfluxDB is receiving data and some is getting graphed properly. 

My expectation was that cpu_number is a variable that should be the actual CPU number and that would be stored as a number within the database that way. This is where the error was in my mind. Is this not the case? There are quite a few graphs in the prepared JSON file that get no data, i understand some would be hardware/OD dependent but was expecting things like CPU cores to come us as i can see that information clearly in the debug statements.

Also, if i have docker disabled then why would i still get the docker error?

Thanks for your assistance. I'm just trying to get it working as well as can be expected. 

![data](https://user-images.githubusercontent.com/8220165/35120776-d80d14c6-fc5e-11e7-942a-6b3c95c4684b.JPG)
