### ISSUE TITLE
Failed to run glances in web server mode in Ubuntu(16.04)

### ISSUE THREAD

**Issue by aaronkilik** [nicolargo/glances#1225]
Hello, 

Am using Linux Mint 18 Sarah and Glances v2.3 with psutil v5.0.  ### Versions. I installed python-bottle to run glances in web server mode but i get the following error:

**`CRITICAL: Bottle module not found. Glances cannot start in web server mode.`**

Can any one please help me. Thanks in advance.

**Comment by nicolargo** [comment]
Please can you enter the following command line and copy/paste the result:

```
$ python
> import bottle
> bottle.__version__
```

**Comment by aaronkilik** [comment]
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bottle
>>> bottle.__version__
'0.12.13'
>>>

**Comment by nicolargo** [comment]
No idea, perhaps Glances is ran with Python 3 instead of Python 2 ?

Please run:

```
glances -V
```

**Comment by aaronkilik** [comment]
Am running Python 2, may be i should install Python 3 and see how it works. Thanks.

**Comment by mrichman** [comment]
Same issue on macOS after installing via homebrew: `Glances v2.11 with psutil v5.4.3`

**Comment by Beasta** [comment]
I just had to run 
`pip install bottle`
and things began working

**Comment by Vadim-Stupakov** [comment]
This is not the isssue
Read the [doc](https://glances.readthedocs.io/en/stable/install.html)

**Comment by richardk80** [comment]
I just ran sudo apt install python-bottle and sudo apt install python3-bottle for good measure and everything started working after that. I can even run glances -w when my server first starts up.

**Comment by mario-g0** [comment]
I installed everything, even ran pip install bottle, but still the web server version won't work on macOS because it says bottle is missing

**Comment by tim77** [comment]
Web server mode not working on Fedora 29. Already installed `python2-bottle` and `python3-bottle`.

**Comment by roumano** [comment]
See issue on my Gentoo : 
```
~ $ glances -w
Bottle module not found. Glances cannot start in web server mode.
```
workarround :  
```
sudo emerge -av dev-python/bottle
```

So this issue is a dependency issue and the file [requirements.txt](https://github.com/nicolargo/glances/blob/develop/requirements.txt) need to be updated.

**Comment by KaKi87** [comment]
Hello,
When will this fix be released ?
Thanks
