### ISSUE TITLE
Centos7/RHEL7 API error messages of Docker Plugin

### ISSUE THREAD

**Issue by markusdd** [nicolargo/glances#1226]
#### Description
Hi. First of all thanks for this amazing tool.
I'm having an issue in CentOS7 and the system-provided docker. We're running 2 Kubernetes nodes with heavy workload-containers and would like to monitor these. We use the RHEL-provided docker.

Error message is:
docker plugin - Docker API error (400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.24)"))

installed as root via (using the system python 2.7.5):
pip install glances[web,docker] --user

run as:
/root/.local/bin/glances -w

I've seen this error in closed issues, but never found the solution for our platform. I thinks it's pretty essential, as RHEL7/CentOS 7 is a LTS operating system powering a lot of critical infrastructure.

If you need any more input just let me know, your efforts are much appreciated!

#### Versions

prompt> docker --version
Docker version 1.12.6, build 3e8e77d/1.12.6

prompt> .local/bin/glances -V
Glances v2.11.1 with psutil v5.4.3

* Operating System:
prompt> uname -a
Linux  3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

prompt> cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by nicolargo** [comment]
The error message is clear: "client is newer than server (client API version: 1.35, server API version: 1.24)".

Two solutions...

1) Downgrade your Python Docker lib used by Glances to grab the containers stats to 1.24.

    pip uninstall docker
    pip install docker==1.24

2) Upgrade your Docker server to 1.35

Easy choice: ===> 1)
