### ISSUE TITLE
macOS 10.13.3  does not report buffered and cached memory.

### ISSUE THREAD

**Issue by dfkbg** [nicolargo/glances#1227]
#### Description

On macOS 10.13.3 glances does not report buffered and cached memory.

#### Versions

Glances v2.11.1 with psutil v5.4.3
macOS 10.13.3 (17D47)

**Comment by nicolargo** [comment]
Glances used PsUtil to grab system stats. Concerning the memory buffers and cached memory are only available on Linux and BSD system (as said in the documentation: http://psutil.readthedocs.io/en/latest/#psutil.virtual_memory):

* buffers (Linux, BSD): cache for things like file system metadata.
* cached (Linux, BSD): cache for various things.

Actually, from what I understand, there's no way to inspect the buffer cache. It seems OSX is just using regular memory for caching files. 

If PsUtil implements a way to retrieve buffers/cached memory on Mac, it will be displayed automatically in Glances.
