### ISSUE TITLE
Ryzen CPU reporting current frequency as current and maximum frequency

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [nicolargo/glances#1233]
Running glances stand-alone, current frequency always reports for both current and max:
>AMD Ryzen 5 1600X Six-Core Processor - 3.58/3.58GHz

Installed via pip.
Glances v2.11.1 with psutil v5.4.3
openSUSE Tumbleweed 20180209 64bit / Linux 4.15.1-1-default

**Comment by nicolargo** [comment]
Glances use the Py-Cpuinfo lib to grab CPU stats.

Please open an issue on the Py-Cpuinfo official Github (). And copy paste the result o fthe following command line:

```
$ python
>>> import cpuinfo
>>> cpuinfo.cpuinfo.get_cpu_info()
```

**Comment by nicolargo** [comment]
Rejected cause: not a Glances issue. Should be reported to dep lib ==> https://github.com/workhorsy/py-cpuinfo
