### ISSUE TITLE
Web UI - Migrate to webpack

### ISSUE THREAD

**Issue by spike008t** [nicolargo/glances#1234]
#### Description

As we know bower is deprecated, so it could be good to switching from npm + bower + gulp to webpack (and optionally yarn) and use the latest lts node version to be 'up to date', without upgrading vendor libs if possible.

#### Versions

* Glances (glances -V): 3.0
* PSutil (glances -V):
* Operating System (lsb_release -a):

**Comment by nicolargo** [comment]
@notFloran What do you think about this enhancement request ?

**Comment by spike008t** [comment]
I've prefix WIP the PR. I'll update until the `PR Quality Review` pass

**Comment by spike008t** [comment]
now it's looking good :)

**Comment by spike008t** [comment]
So on this new PR, public folder is under git control.
