### ISSUE TITLE
[WEB UI] Flood if refresh_time is negative

### ISSUE THREAD

**Issue by spike008t** [nicolargo/glances#1241]
#### Description

On the web ui, the route `/<refresh_time:int>` can define the `refresh_time` on the webap.
But if we set a negative value (ie: `http://localhost:61208/-1`). We flood the server to refresh

<img width="1133" alt="screen shot 2018-02-20 at 23 10 44" src="https://user-images.githubusercontent.com/262459/36452192-d335e76c-1693-11e8-8719-3ea3afd311be.png">
<img width="559" alt="screen shot 2018-02-20 at 23 16 58" src="https://user-images.githubusercontent.com/262459/36452281-2e755824-1694-11e8-8a3a-33ca50a13d21.png">

The webapp should check the refresh delay and if that is < 1s, set to 1s or 5s.

#### Versions

* Glances (glances -V): latest develop version
* PSutil (glances -V):
* Operating System (lsb_release -a): 

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by notFloran** [comment]
@spike008t thanks for the report, I have made a PR #1242

**Comment by nicolargo** [comment]
@spike008t Can we close this issue ?
