### ISSUE TITLE
Stats updated during export (thread issue)

### ISSUE THREAD

**Issue by usd-yamazaki** [nicolargo/glances#1250]
Related issue #971

environment
Glances v2.11.1 with psutil v3.4.2
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

This happens when the PC load is high.
For example, the data obtained from plugins/glances_system.py is as follows.

Normal
```
{'os_name': 'Linux', 'os_version': '4.4.0-62-generic', 'linux_distro': 'Ubuntu 16.04', 'hostname': 'localhost.localdomain', 'platform': '64bit', 'hr_name': 'Ubuntu 16.04 64bit'}
```

High load
```
{'os_name': 'Linux', 'hostname': 'localhost.localdomain'}
```

This is solved by commenting out the "self.reset()" function of the update function.
https://github.com/nicolargo/glances/blob/c2863629dda28d98a1df126c65c5da3540fbf4a2/glances/plugins/glances_system.py#L108

Perhaps, after clearing the data with "self.reset()", I think that I output it to CSV before getting it again.
In addition, this problem is not limited to the system plug-in, it may occur in all plug-ins.

**Comment by nicolargo** [comment]
Hi @usd-yamazaki 

Thanks for this report.

I completely refactor the export code in Glances 3.0 (currently in RC2). Can you test it ?

**Comment by usd-yamazaki** [comment]
Thank you for your response.
When I tried to operate for about 30 minutes under high load condition, it worked normally.
