### ISSUE TITLE
Webserver Mode: failed because of iptables

### ISSUE THREAD

**Issue by ViennaCivicEP2** [nicolargo/glances#1252]
Hi,
tried to run the docker container in webserver mode resulting in:

`docker: Error response from daemon: driver failed programming external connectivity on endpoint sleepy_panini (458ea254322b019d3bbd3ea241321a799fe67483fc8bf56547d9fe20257f412b):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 61209 -j DNAT --to-destination 172.17.0.2:61209 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).`

i started the container using the command given:
`docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances`

172.17.0.2 is none of my hosts - is there a problem with an iptables rule?

I apprechiate your help, as i am relatively new to docker and glances.

Edit: 
OS: Debian Jessie

**Comment by RazCrimson** [comment]
Closing as a stale issue and its not reproduced.
