### ISSUE TITLE
On Fedora 28 x64 btrfs with the command  "pip " Glances not install

### ISSUE THREAD

**Issue by xzj8b3** [nicolargo/glances#1257]
On Fedora 28 x64 btrfs with the command  "pip " Glances not install

Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KL6moR/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5aWXjI/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-KL6moR/psutil/

**Comment by nicolargo** [comment]
Please fill the issue as asked in the template.

===

Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a):

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

===

**Comment by xzj8b3** [comment]
On Fedora 28 with  "Pip" You just can not install it.... Installed the
version in the distribution glances. Noarch 2.11.1-2. Fc28 but always
reports the following error:

/usr/lib64/python3.6/site-packages/psutil/_pslinux.py: 1150:
RuntimeWarning: Ignoring OSError (22, ' invalid argument ')


Glances v2.11.1 with psutil v5.4.3




Seguimi su Facebook <https://www.facebook.com/IvanDeFelice>  Seguimi su
Twitter <https://twitter.com/xzj8b3>  Seguimi su Istagram
<https://www.instagram.com/defelice.ivan/> Seguimi su Pinterest
<https://it.pinterest.com/xzj8b3/>

                            Seguimi su Google +
<https://plus.google.com/+IvanDeFelice>     Seguimi su Flipboard
<https://flipboard.com/profile>


Il giorno dom 6 mag 2018 alle ore 22:39 Nicolas Hennion <
notifications@github.com> ha scritto:

**Comment by xzj8b3** [comment]
Could not find a version that satisfies the requirement psutils (from
versions: )
No matching distribution found for psutils

Seguimi su Facebook <https://www.facebook.com/IvanDeFelice>  Seguimi su
Twitter <https://twitter.com/xzj8b3>  Seguimi su Istagram
<https://www.instagram.com/defelice.ivan/> Seguimi su Pinterest
<https://it.pinterest.com/xzj8b3/>

                            Seguimi su Google +
<https://plus.google.com/+IvanDeFelice>     Seguimi su Flipboard
<https://flipboard.com/profile>


Il giorno mar 8 mag 2018 alle ore 11:21 Nicolas Hennion <
notifications@github.com> ha scritto:

**Comment by nicolargo** [comment]
And this:

    pip install python-psutil

**Comment by RazCrimson** [comment]
Closing as a stale issue
