### ISSUE TITLE
AMP for kernel process is not working

### ISSUE THREAD

**Issue by SailorMax** [nicolargo/glances#1261]
#### Description

Currently we can't setup AMP for processes without command line!
Can you add to amps_list.py:116
https://github.com/nicolargo/glances/blob/c2863629dda28d98a1df126c65c5da3540fbf4a2/glances/amps_list.py#L115
```python
                if len(amps_list) == 0:
                    amps_list = [p for p in processlist if re.search(v.regex(), p['name']) is not None]
```

#### Versions

* Glances (glances -V): Glances v2.11.1
* PSutil (glances -V): with psutil v5.4.5
* Operating System (lsb_release -a): Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy

**Comment by nicolargo** [comment]
Yes you can setup an AMP without command line.

Example:

```
[amp_python]
# Use the default AMP (no dedicated AMP Python script)
# Monitor all the Python scripts
# Alert if more than 20 Python scripts are running
enable=true
regex=.*python.*
refresh=3
countmax=20
```

Result:

![image](https://user-images.githubusercontent.com/776747/39970735-0be8170e-56f1-11e8-9a3d-742f2843d62b.png)

**Comment by SailorMax** [comment]
@nicolargo I meant processes without command line! For example kernel modules. "regex" did not see them...

**Comment by nicolargo** [comment]
What is the use case ? Any example ?

**Comment by SailorMax** [comment]
process "aacraid" for Adaptec Hardware Raid.
"aacraid" is kernel module driver and glances regex did not see it, but we can see it in process list.

**Comment by nicolargo** [comment]
I understand your need but if you do not use the --hide-kernel-thread option (default behavior), the kernel process should be displayed (and AMP should work).

**Comment by nicolargo** [comment]
Forget my last message.

Bug reproduced on my side:

![image](https://user-images.githubusercontent.com/776747/40269427-ac1312c4-5b7e-11e8-879b-5e41d6341a39.png)

Kernel processes are displayed but not viewed by the AMP plugin.

I will have a look on it.

**Comment by nicolargo** [comment]
Correction done in the latest commit on the DEVELOP branch.

Can you test it ?

Note: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by SailorMax** [comment]
@nicolargo I think your solution can return double result... wrong count of founded processes.
Better check accessibility of cmdline in first search line, or add before second my `if`.
