### ISSUE TITLE
Overlap in Web UI when monitoring a machine with 16 cpu threads

### ISSUE THREAD

**Issue by imbuedHope** [nicolargo/glances#1265]
#### Description

When running `glances` on a machine that has a large number of cpu threads and enabling the per cpu load view, the cpu info overlaps with the memory info making it somewhat unreadable.

![screenshot from 2018-05-14 11-15-13](https://user-images.githubusercontent.com/5403817/40249936-a6a21704-5aa2-11e8-90e1-3425ffc596e7.png)

This fixes itself on really high-resolution displays but a 16 CPU thread machine shows overlap when in a full-screen view on a 1080p display which is a bit vexing (image above).

It would be really nice if the memory info got pushed below when it filled up instead of being locked to the left.

#### Versions
Glances v2.11.1 with psutil v5.4.5

**Comment by nicolargo** [comment]
Agree...

I propose to switch columns and lines when the number of CPU is > 4

**Comment by nicolargo** [comment]
Change my mind during the development.

The percpu plugin will be always displayed per line (one CPU = one line). If the quicklook plugin is enable, it is not necessary to display the sum.

With Quicklook:

![image](https://user-images.githubusercontent.com/776747/40266747-f493b900-5b50-11e8-8451-01bb865f1c20.png)

Without:

![image](https://user-images.githubusercontent.com/776747/40266750-f9a35f36-5b50-11e8-9f31-23e8fa34d194.png)

Merged in the DEVELOP branch. Can you test and cpoy/paste a screen shot ?

Note: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version
