### ISSUE TITLE
fatal error: 'crypt.h' file not found when installing glances

### ISSUE THREAD

**Issue by giupardeb** [nicolargo/glances#1268]
#### Description
I follow the tutorial to install glances on my android phone (Xiaomi redmi note4x Android version 7.0), when I launch the following command: `pip install glances`, I got this error:

> /data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found
>     #include <crypt.h>
>              ^~~~~~~~~
>     1 error generated.
>     error: command 'aarch64-linux-android-clang' failed with exit status 1
> 
>     ----------------------------------------
> Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-nb12tm2r/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-dx8ctld7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-nb12tm2r/psutil/
> 

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a): Android

**Comment by nicolargo** [comment]
The problem came from the PsUtil installation.

Please have a look here: https://github.com/giampaolo/psutil/issues/1261#issuecomment-378980760
