### ISSUE TITLE
Glances windows 8.1 API GET

### ISSUE THREAD

**Issue by DjDOESIT** [nicolargo/glances#1270]
#### Description
Bonjour,

Je viens d'installer la version  windows de Glances sur un windows 8.1.

Lors ce que je lance le mode serveur il indique:
`Glances server is running on 0.0.0.0:61209`

Mais si j'utilise une commande GET ... il me retourne continuellement:
`Error response
Error code 501.
Message: Unsupported method ('GET').
Error code explanation: 501 = Server does not support this operation.`

Je souhaites pourvoir obtenir les infos des process sur un pc via l'api de glances afin de les afficher dans un autre gestionnaire depuis une Raspbian.

Commande utilisée:
curl -H "Content-Type: application/json" -v http://IP:61209/api/2/all

#### Versions

* Glances : Glances-1.7.2-win32
* Operating System: Windwows 8.1

#### Logs

Je ne trouve pas de log sous %TMP% n'y %APPDATA% et dans le dossier de glances non plus.

D'avance merci.

**Comment by nicolargo** [comment]
L'API est uniquement disponible à partir de la version 2.0+.
