### ISSUE TITLE
Glances error after docker installation

### ISSUE THREAD

**Issue by Raptor039** [nicolargo/glances#1271]
#### Description

Just after install docker on my system, glances not working anymore except if I launch it with --disable-fs argument.

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.6
* Operating System (lsb_release -a): 

Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
 
Below a screen showing the issue :

![glances](https://user-images.githubusercontent.com/16542820/41400466-88880488-6fbd-11e8-9b68-46c70c555e46.PNG)

Thanks in advance for your help.

**Comment by clyra** [comment]
Mine is broken too and I'm also on debian stretch. --disable-plugin fs didn't help and the web ui seems to be frozen and not updating.

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/1094
