### ISSUE TITLE
setup.py should refrence nvidia-ml-py3 to avoid breaking on python3

### ISSUE THREAD

**Issue by gdahlm** [nicolargo/glances#1273]
#### Description

Related to #1137 and the [documentation](http://glances.readthedocs.io/en/stable/aoa/gpu.html) related to the GPU option.  If you install `nvidia-ml-py3` on python3 it will be overwritten by ` nvidia-ml-py`.  This breaks the nvidia gpu function.

As `nvidia-ml-py3` is listed in: :https://github.com/nicolargo/glances/blob/b016d508f014721823d836486a419482c47e3fd4/optional-requirements.txt#L10

And setuptools is installing `nvidia-ml-py`:
https://github.com/nicolargo/glances/blob/b016d508f014721823d836486a419482c47e3fd4/setup.py#L91

I assume that this is just an issue that is not captured in the unit tests.  I have tested on a few hosts with python2.7 and various versions of python 3 and this simple change solves the issue.  Unfortunately it setuptools does not seem to support python version constraints in this use case.

The issue can be recreated by running:

```sh
$ mkvirtualenv -p python3 foo
...
(foo)$ pip install glances[gpu]
...
(foo)$ glances
```

#### Versions

Python 2:
* Glances v3.0.rc5 with psutil v5.4.6 
* Glances v2.11.1 with psutil v5.4.6

Python 3.6:
* Glances v3.0.rc5 with psutil v5.4.3
* Glances v2.11.1 with psutil v5.4.6

lsb_release:

>Distributor ID:	Ubuntu
>Description:	Ubuntu 18.04 LTS
>Release:	18.04
>Codename:	bionic

#### Logs

[glances-gdahlm.log](https://github.com/nicolargo/glances/files/2104826/glances-gdahlm.log)

[glances-pip3.txt](https://github.com/nicolargo/glances/files/2104827/glances-pip3.txt)

```
$ python -c "import pynvml"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gdahlman/build/python/venvs/glancestest/lib/python3.6/site-packages/pynvml.py", line 1831
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int c_count.value)?
```

**Comment by nicolargo** [comment]
Thanks for the issue and the PR :)
