### ISSUE TITLE
Terminal window stuck at the last accessed *protected* server

### ISSUE THREAD

**Issue by SecKarma** [nicolargo/glances#1275]
#### Description

The terminal window where you get to choose from the static servers you set in the configurations file, it just stops responding and cant move (the arrow) between the servers list, if you connect to a server and press "q" to go back to the servers list, in here the arrow wont move up and down, and also it would freeze, but you can still only access the same server by hitting enter or you can press q again to quit.

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.6
* Operating System (lsb_release -a): Ubuntu 16.04.4 LTS

#### Logs

https://pastebin.com/7Gs3V1hG

P.S: ofcourse for security reasons the servers are deleted and the IP addresses with the hashed passwords no longer exist. but it can replicated at anytime

**Comment by nicolargo** [comment]
Please, can you provide an extract of the servers list configured in the glances.conf file ?

**Comment by SecKarma** [comment]
i can give you an exact example of what i had in my configuration: (these are just random domains which i don't own if exist)

```
[serverlist]
# Define the static servers list
server_1_name=app.somethingcool.com
server_1_alias=My_APP
server_1_port=61209
server_2_name=admin.somethingcool.com
server_2_port=61209
```
after the configuration up and after i launch glances in the background as a server on the servers listed up i do run glances locally using this command:
`glances --browser --disable-autodiscover`

it pops up a list of the servers configured up (ofcourse they're protected with the same password each) and the have *protected* mark next to them

so when i choose one server and type in the password it takes me to that server's info, and when i press `q` to go back to the main menu where the list of servers is available it just gets stuck and i can't move the arrow up or down, but i can only press Enter or press q to quit.. if i press Enter it would go to the same server i previously accessed and if i press q it just hangs for 3-5 seconds then quits

**Comment by SecKarma** [comment]
Any Updates so far on this issue?

**Comment by nicolargo** [comment]
Vgv bave et rédtr

**Comment by nicolargo** [comment]
Also reproduced with Glances 3.0 RC...

With a simple dynamic configuration and two Glances server:

![selection_374](https://user-images.githubusercontent.com/776747/43287930-c1bf2b98-9126-11e8-9aeb-a34cc4751379.png)

Same issue with:
- password protected server
- no password protected server

**Comment by nicolargo** [comment]
Corrected in the DEBELOP branch. can you test it @SecKarma ?

**Comment by SecKarma** [comment]
ofcourse, I will test it and will reply in couple of days later.

thank you so much.

**Comment by SecKarma** [comment]
Update: Works perfectly thanks! :heart:
