### ISSUE TITLE
Sort docker stats

### ISSUE THREAD

**Issue by oppianmatt** [nicolargo/glances#1276]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

We can sort the processes by a few different properties, but yet the docker stats we can't sort by anything. Would be nice if the same/similar sort options existed, like sorting docker containers by cpu for example.

For example here it's sorted by cpu, but due to number of docker containers the sorting doesn't do anything:

![image](https://user-images.githubusercontent.com/48596/41606643-10efdf0e-73dc-11e8-968e-a779c4f54c04.png)

**Comment by nicolargo** [comment]
Proposal: Containers sort key will be the same than the processes.

What do you think ?

**Comment by nicolargo** [comment]
@notFloran Can you implement the same sort algorithm to the Web UI ?

**Comment by notFloran** [comment]
@nicolargo I started to look at it but I cannot display my containers with develop, no problems with master. Any idea ?

**Comment by nicolargo** [comment]
Nope... Working fine for both master and dev branch.

Ubuntu 18.04 and Docker 17.05.0-ce

**Comment by notFloran** [comment]
@nicolargo I resolve my issue with https://github.com/docker/docker-py/issues/1796
