### ISSUE TITLE
How to send email when warnings or critical values come up?

### ISSUE THREAD

**Issue by jack10bells** [nicolargo/glances#1277]
Hi, I would like to know if this feature is already available or the best way to develop it using the already Glances implemented code.
I've just taken contact with this amazing tool.
Thanks in advance
Gustavo

**Comment by shawngiese** [comment]
I think you want this... http://glances.readthedocs.io/en/stable/aoa/actions.html

**Comment by nicolargo** [comment]
@jack10bells Is it ok for you ?

**Comment by jack10bells** [comment]
Hi, sorry for not answering before. Yes, that's was what I was looking for. 
It worked for a Python program execution (i.e. critical_action=python /path/to/foo.py) but didn't work when using mustache syntax (ie careful_action=echo {{percent}} > C:\tmp\memory.alert). It prints "{{percent}}" instead of the percentage itself.
I'm running on Windows platform.
Any idea?

**Comment by samcro1967** [comment]
Ah, didn't realize there was a  generic amp for commands.

Append works in that scenario, but `echo date $1 $2 >> /glances/alerts/iowait.alert` results in `date {{iowait}} {{percent}}` in the file.  I did `pip install pystache` in the container and restarted it.  Seems like variables are not expanded before being pushed to the script or are not expanded in the script as date did not work either.

If I am understanding, this will run every 15 mins, not just on critical error correct?
