### ISSUE TITLE
Webserver over https

### ISSUE THREAD

**Issue by TheBestPessimist** [nicolargo/glances#1280]
#### Description

Is it possible that the webserver option `glances -w` works over https?

**Comment by TheBestPessimist** [comment]
Or should we use this?

https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

**Comment by nicolargo** [comment]
If you want to use SSL to access to your Glances server, you should use a reverse proxy (Nginx or other).
