### ISSUE TITLE
Add new status value to browser

### ISSUE THREAD

**Issue by shawngiese** [nicolargo/glances#1281]
Glances is fun! Thanks.

Would be great if we could have a new status in glances_curses_browser.py like 'DEGRADED': self.ifWARNING_color2. Then we could add some if logic to the browser to highlight high resource usage. I mean, I did it for my browser but I think others might find it useful.

Maybe even another for ERROR in case an essential service failed.

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/977
