### ISSUE TITLE
Glances docker export influxdb problem with curse

### ISSUE THREAD

**Issue by fraoustin** [nicolargo/glances#1284]
When run glances by docker, i have a error

#### Description

> docker run -v /home/fraoustin/Downloads/test/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -e GLANCES_OPT="--export influxdb" docker.io/nicolargo/glances

 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/glances/glances/__main__.py", line 29, in <module>
>     glances.main()
>   File "glances/__init__.py", line 140, in main
>     start(config=config, args=args)
>   File "glances/__init__.py", line 106, in start
>     mode = GlancesMode(config=config, args=args)
>   File "glances/standalone.py", line 87, in __init__
>     self.screen = GlancesCursesStandalone(config=config, args=args)
>   File "glances/outputs/glances_curses.py", line 118, in __init__
>     self.screen = curses.initscr()
>   File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
>     fd=_sys.__stdout__.fileno())
> _curses.error: setupterm: could not find terminal

#### Versions

* Glances & psutil (glances -V): Glances v3.0.rc5 with psutil v5.4.3
* Operating System (lsb_release -a): docker ce

Can you help me please

**Comment by nicolargo** [comment]
Try this:

    ... GLANCES_OPT="--quiet --export influxdb" ...

**Comment by fraoustin** [comment]
it's working , thank you
For a next feature: add export in server mode it's a good idea ... I wish have the ihm web and the export influxdb in same instance
thank you
