### ISSUE TITLE
Configuration file issues

### ISSUE THREAD

**Issue by gseluja** [nicolargo/glances#1286]
Configuration file worked for a Python program execution (i.e. in **[mem]** section, **critical_action=python /path/to/foo.py** was ok) but it didn't work when using mustache syntax (ie **careful_action=echo {{percent}} > C:\Users\jack1\AppData\Roaming\glances\memory.alert**). It prints "{{percent}}" instead of the percentage itself.
Or even if I want to echo from **careful_action_repeat** and run python script from **warning_action_repeat**, only the second one works.
I'm running Glances on a Windows 10 platform. 
glances.txt (my configuration file attached)
Any help, please?

[glances.txt](https://github.com/nicolargo/glances/files/2182486/glances.txt)

**Comment by nicolargo** [comment]
Hi @jack10bells , some additional question regarding your configuration:
- what is your Glances version ? (glances -V)
- did the Python mustache lib installed on your system ? (pip list)

**Comment by jack10bells** [comment]
Hi @nicolargo , the first issue is solved (mustache lib was missing). 
Glances version is v2.11.1 with psutil v5.4.6.
Regards

**Comment by scottcopus** [comment]
@gseluja @nicolargo FYI, the documentation for the Windows configuration file path location is wrong.  It's listed as `%APPDATA%\glancesglances.conf`.  However, it should be`%APPDATA%\glances\glances.conf`.  I doubt this is the source of the problem for this issue, but something I wanted to pass this along for those users having issues on the Windows side of the house.

cheers,
Scott

**Comment by RazCrimson** [comment]
Closing as stale issue
