### ISSUE TITLE
Swap isn't reported correctly in FreeBSD

### ISSUE THREAD

**Issue by mcarlton00** [nicolargo/glances#1290]
#### Description

On a FreeBSD machine, swap is reported at the correct percentage, but the wrong values.

Glances view:
```
SWAP     44.7%
total:    512K
used:     229K
free:     283K
```
Swapinfo view:
```
zeus% sudo swapinfo -h
Device          512-blocks     Used    Avail Capacity
/dev/ada0p3        4194304     915M     1.1G    45%
```

#### Versions

* Glances & psutil (glances -V): `Glances v2.11.1 with psutil v5.4.3`
* Operating System (lsb_release -a): `FreeBSD 11.1-RELEASE-p9`

#### Logging
This seems to be the relevant line.  I can provide more if needed:
```
2018-07-16 10:39:37,331 -- DEBUG -- Plugin memswap update return {'used': 234327, 'percent': 44.7, 'free': 289945, 'sout': 4137890, 'total': 524272, 'sin': 93000}
```

**Comment by nicolargo** [comment]
Hi,

the stats are provided by the PsUtil lib (https://psutil.readthedocs.io/en/latest/#psutil.swap_memory).

Please can you enter the following command lines in a terminal and copy/paste the result:

```
$ python -c 'import psutil; print(psutil.swap_memory())'
sswap(total=8082419712, used=225681408, free=7856738304, percent=2.8, sin=2838528, sout=228032512)
$  free -m
              total        used        free      shared  buff/cache   available
Mem:           7507        2685         235         332        4586        4136
Swap:          7707         215        7492
```

Thanks.

**Comment by mcarlton00** [comment]
Different server than the first example, but still has the same problem:
```
zeus% python -c 'import psutil; print(psutil.swap_memory())'
sswap(total=524272, used=220768, free=303504, percent=42.1, sin=95343, sout=6661956)
```
`free` is a linux command and isn't available on freebsd.  
```
zeus% swapinfo
Device          1K-blocks     Used    Avail Capacity
/dev/ada0p3       2097152   883072  1214080    42%
```
If I'm reading this right, it looks like this may be a problem with psutil instead of glances, right?

**Comment by mcarlton00** [comment]
One of these days I'll learn to run OS updates before opening bug reports.  I was still on psutil 5.4.3.  All fixed, thanks for the help.
