### ISSUE TITLE
Invalid metric name: glances_processcount_?

### ISSUE THREAD

**Issue by LabSen** [nicolargo/glances#1291]
#### Description

I've Glances with Prometheus and Grafana. It's work, but Something in the logs is not correct

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.6
* Operating System (lsb_release -a): Ubuntu 18.04.1 LTS

#### Logs

Jul 27 14:50:30 srv glances[1469]: Exception in thread Thread-10864:
Jul 27 14:50:30 srv glances[1469]: Traceback (most recent call last):
Jul 27 14:50:30 srv glances[1469]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Jul 27 14:50:30 srv glances[1469]:     self.run()
Jul 27 14:50:30 srv glances[1469]:   File "/usr/lib/python3.6/threading.py", line 864, in run
Jul 27 14:50:30 srv glances[1469]:     self._target(*self._args, **self._kwargs)
Jul 27 14:50:30 srv glances[1469]:   File "/usr/local/lib/python3.6/dist-packages/glances/exports/glances_export.py", line 169, in update
Jul 27 14:50:30 srv glances[1469]:     self.export(plugin, export_names, export_values)
Jul 27 14:50:30 srv glances[1469]:   File "/usr/local/lib/python3.6/dist-packages/glances/exports/glances_prometheus.py", line 87, in export
Jul 27 14:50:30 srv glances[1469]:     self._metric_dict[metric_name] = Gauge(metric_name, k)
Jul 27 14:50:30 srv glances[1469]:   File "/usr/local/lib/python3.6/dist-packages/prometheus_client/core.py", line 609, in init
Jul 27 14:50:30 srv glances[1469]:     raise ValueError('Invalid metric name: ' + full_name)
Jul 27 14:50:30 srv glances[1469]: ValueError: Invalid metric name: glances_processcount_?

**Comment by nicolargo** [comment]
Hi Labsen,

can you try with the Glances DEVELOP branch (future Glances 3.0) and also paste/bin us the Glances log file.

Thanks

**Comment by nicolargo** [comment]
Did you try with Glances 3 ?
