### ISSUE TITLE
Capture Glances alerts?

### ISSUE THREAD

**Issue by jack10bells** [nicolargo/glances#1296]
Is it possible to capture Glances alerts and possible writing it on a file? 

Warning or critical alerts (lasts 2 entries)
2018-07-31 19:28:03 (ongoing) - MEM (40.174265803272725)
2018-07-31 19:24:38 (00:01:51) - WARNING on MEM (44.04490948848545)

I want to capture both lines

**Comment by nicolargo** [comment]
What you looking for can be done with action.

Read this: http://glances.readthedocs.io/en/stable/aoa/actions.html

**Comment by jack10bells** [comment]
Hi @nicolargo, I will use actions to do that, but my question is how can I capture the alerts? In which way? Which object should I call?
Regards
