### ISSUE TITLE
Disk throughput unit is missing in display, help, manpage and online ReadTheDocs

### ISSUE THREAD

**Issue by beat** [nicolargo/glances#1298]
#### Description

Disk throughput measurement unit is missing in display, help, manpage and online ReadTheDocs:

Is disk throughput I/O requests per seconds ? Is it Bytes per seconds ?

Both would be useful, and being able to toggle display like for networks would be nice too (possibly also adding disk latency as third toggle choice (#1070) and SMART state (#1288) as fourth (with any abnormal SMART state making the reading of any throughput indication red).

The per second part is clearly shown, but with R/s and W/s it's not clear.

3 Suggested solutions for main display:
- if it is Bytes, display it as `R B/s` and `W B/s`, or
- add a 'B' after the number: '3MB (like for network 'b', which could also add a 'B' when switched to Bytes/s)
- or if it can be switched to I/O/s, title could be 'IOR/s' and 'IOW/s, but I see that there would be an inconsistency with process IO/s in this case, which also seems to be Bytes/s....

But in help page it would be easy to add units to the 'd' disk line at end: `d  Show/hide disk I/O stats B/s`.

Then of course, man page and online doc is easy to add unit too.

**Comment by nicolargo** [comment]
Hi @beat ,

the documentation can be found here: http://glances.readthedocs.io/en/stable/aoa/disk.html

Agree with you concerning the unit, it is in Bytes per seconds but it is not clear in the documentation.

Concerning the request per second, it can be done using the --diskio-iops option or *B* hot key.

Also agree with you that thoses options are not in the ReadTheDocs.
