### ISSUE TITLE
Glances shows mdadm RAID0 as degraded when chunksize=128k and the array isn't degraded.

### ISSUE THREAD

**Issue by piotrp88** [nicolargo/glances#1299]
`Glances v2.11.1 with psutil v5.4.3`

I'm observing a very strange behaviour after creating a new and clean RAID0 array using mdadm and six SSDs. Glances shows the following output when the chunk size of the array is 128k:

```
RAID disks   Used Avail
RAID0 md125  128k     2
└─ Degraded mode
   └─ chunks
```

I tried with other values, like 64k, 256k and 512k and none of them displayed as degraded. For example:

```
RAID disks   Used Avail
RAID0 md125   64k     2
```

I'm sure that the array isn't degraded for two reasons: first, it's a clean and empty array. Second, the output of `cat /proc/mdstat` is:

```
Personalities : [raid0] [raid1] [linear] [multipath] [raid6] [raid5] [raid4] [raid10] 
md125 : active raid0 sdh[5] sdg[4] sdf[3] sde[2] sdc[1] sdb[0]
      2306837760 blocks super 1.2 128k chunks
```
and the output of `mdadm --detail /dev/md125` is:

```
/dev/md125:
        Version : 1.2
  Creation Time : Fri Aug  3 17:48:23 2018
     Raid Level : raid0
     Array Size : 2306837760 (2199.97 GiB 2362.20 GB)
   Raid Devices : 6
  Total Devices : 6
    Persistence : Superblock is persistent

    Update Time : Fri Aug  3 17:48:23 2018
          State : clean 
 Active Devices : 6
Working Devices : 6
 Failed Devices : 0
  Spare Devices : 0

     Chunk Size : 128K

           Name : calculon:125  (local to host calculon)
           UUID : 8a7e941e:6c616c29:52711695:d75f5aa5
         Events : 0

    Number   Major   Minor   RaidDevice State
       0       8       16        0      active sync   /dev/sdb
       1       8       32        1      active sync   /dev/sdc
       2       8       64        2      active sync   /dev/sde
       3       8       80        3      active sync   /dev/sdf
       4       8       96        4      active sync   /dev/sdg
       5       8      112        5      active sync   /dev/sdh
```

**Comment by piotrp88** [comment]
Probably I found the issue. [In the code](https://github.com/nicolargo/glances/blob/4675fff26d6e03daf75b1e9b5e15d95544601950/glances/plugins/glances_raid.py#L135), you check the number of used disks (`x`) against the number of available disks (`y`). If `x` < `y` then the array is degraded, but in this case `x` equals the chunk size (`"128k"`) and not the number of used disks. Also, for some reasons `y` equals `2` and not `6`. 
To resume, in my case `x` equals the chunk size and `y` equals `2`. You should check how `Plugin.stats[array]['used']` and `Plugin.stats[array]['available']` are obtained.

**Comment by nung0707** [comment]
/ etc / mdstat

**Comment by piotrp88** [comment]
I have different RAID arrays on my server. The output from `pymdstat` seems the same as the output of `cat /proc/mdstat`.

```
# cat /proc/mdstat
Personalities : [raid0] [raid1] [linear] [multipath] [raid6] [raid5] [raid4] [raid10] 
md129 : active raid1 sda3[0] sdd3[1]
      15825920 blocks super 1.2 [2/2] [UU]
      
md128 : active raid1 sda2[0] sdd2[1]
      126887936 blocks super 1.2 [2/2] [UU]
      bitmap: 1/1 pages [4KB], 65536KB chunk

md125 : active raid0 sdg[4] sdc[1] sdf[3] sdh[5] sde[2] sdb[0]
      2306837760 blocks super 1.2 128k chunks
      
md126 : active raid0 nvme0n1[0] nvme1n1[1]
      999948288 blocks super 1.2 3072k chunks
      
unused devices: <none>
```

```
# python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymdstat
>>> raid = pymdstat.MdStat()
>>> raid
Personalities : [raid0] [raid1] [linear] [multipath] [raid6] [raid5] [raid4] [raid10] 
md129 : active raid1 sda3[0] sdd3[1]
      15825920 blocks super 1.2 [2/2] [UU]
      
md128 : active raid1 sda2[0] sdd2[1]
      126887936 blocks super 1.2 [2/2] [UU]
      bitmap: 1/1 pages [4KB], 65536KB chunk

md125 : active raid0 sdg[4] sdc[1] sdf[3] sdh[5] sde[2] sdb[0]
      2306837760 blocks super 1.2 128k chunks
      
md126 : active raid0 nvme0n1[0] nvme1n1[1]
      999948288 blocks super 1.2 3072k chunks
      
unused devices: <none>

>>> 
```

**Comment by nicolargo** [comment]
Corrected in the Glances DEVELOP branch.

![image](https://user-images.githubusercontent.com/776747/43706296-3ac5bbd8-9965-11e8-807a-1da72c5352b3.png)

Thanks for the report !

**Comment by piotrp88** [comment]
But what does "Avail" and "Used" mean? In my case I must interpret it reports 2 disks available for all my arrays, but there are a total of 6 used disks and 0 available disks for md125 and 2 used disks and 0 available disks for md126. I think the reported info is wrong, or probably I don't quite understand it.

**Comment by nicolargo** [comment]
Ok copy that. I just push another patch on the DEVELOP branch:

![image](https://user-images.githubusercontent.com/776747/43723801-d366f4be-9998-11e8-94b5-e7c405587e80.png)

For a RAID0, it display the number of used disks. Available disk has no sense in the RAID0 case because if one disk is down, all the RAID0 will be in failure.

Can you simulate a failure on one disk and show me the result of the Glances UI in this case ?

Nicolas

**Comment by piotrp88** [comment]
I can't because this is a production server, I'm sorry.

**Comment by piotrp88** [comment]
I can confirm that version 3.0.1 solves the bug.
