### ISSUE TITLE
Allowing Glances through firewall

### ISSUE THREAD

**Issue by Sethox** [nicolargo/glances#1300]
#### Description

So I have a very hard firewall (iptables and ip6tables) filter and it would seem that it blocks the standalone runtime by having an unlimited timeout of not running. I tested by flushing my rules and volá glances runs perfectly without any delays.

I would like to know what port or interface/s (for further specified filter) needs to go through my filter, I looked in the wiki and start page of the project (readme), nothing of the matter unless I missed it.
#### Versions

* Glances & psutil (glances -V):
Glances v2.11.1 with psutil v5.4.3

* Operating System (lsb_release -a):
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	3.9999
Codename:	shannon

**Comment by nicolargo** [comment]
Hi @Sethox ,

as said in the documentation ([here](http://glances.readthedocs.io/en/stable/quickstart.html#client-server-mode) or [here](http://glances.readthedocs.io/en/stable/cmds.html#cmdoption-p)) the default TCP port is 61209.
