### ISSUE TITLE
View by CPU with more than 10 CPU cores

### ISSUE THREAD

**Issue by sylvainmouquet** [nicolargo/glances#1304]
Hello,

We have a server with 56 cpu-cores.
The view by CPU does not display all cores :

![image](https://user-images.githubusercontent.com/184874/43964732-c3882b08-9cbd-11e8-8a64-2818c8d88bf6.png)

Glances version 2.11.1
PSUtil 5.4.2
Linux

**Comment by nicolargo** [comment]
Ooops... Never tested Glances with such hardware configuration.
Will have a look on this issue. 

Any idea to display it ?
Like htop ?

**Comment by vielmetti** [comment]
For reference, we have systems with 224 hardware threads (Cavium ThunderX2, arm64). The htop style just works here if you have a big screen and a teeny tiny font. It is definitely needed though; the arm64 server systems generally have lots of cores (up to 32 on Ampere, 48 on Qualcomm, 96 on ThunderX and 256 on ThunderX2).

**Comment by asymmetric** [comment]
On a machine with 48 cores, the CPU list fits, but the right side is basically all empty. That side of the UI  should be used to display sensor data, which instead is (I imagine) still at the bottom, but invisible.
