### ISSUE TITLE
doesn't work with docker in swarm mode ?

### ISSUE THREAD

**Issue by marcwaz** [nicolargo/glances#1311]
The option --pid host seems to be mandatory in order to use glances with docker. However docker in swarm mode is not supporting this option. 

Is it possible to use glances without --pid host option ? 

If not, it means that glances is currently not supporting docker in swarm mode, right !?

**Comment by nicolargo** [comment]
Never tested...
What is the error message /log ?

**Comment by nicolargo** [comment]
Confirmed here: https://github.com/docker/docker.github.io/issues/5624

Docker in swarm mode is not compatible with --pid option...
