### ISSUE TITLE
Processes list doesn't expand when top menu is disabled

### ISSUE THREAD

**Issue by LChris314** [nicolargo/glances#1313]
#### Description

Steps to reproduce:

1. Run `glances`.
2. Press `5` to disable the top menu.

Expected behaviour:

* The processes list expands to take up available vertical space.

Actual behaviour:

* The list may or may not expand at the moment of pressing `5`, but always become unexpanded after the next refresh.

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.7
* Operating System: Arch Linux

**Comment by nicolargo** [comment]
Already corrected in Glances 3.0_RC5.
