### ISSUE TITLE
From a Docker container, can't see additional drives in filesystem

### ISSUE THREAD

**Issue by juan11perez** [nicolargo/glances#1316]
Glances v2.11.1 with psutil v5.4.3
docker image, ubuntu 18.04

Good day, I cant see the drive that's mounted onto /home. I can only see the system drive.
I tried adding #allow=zfs,misc,afpfs,autofs per another thread, but no change. 
Below a pastebin of container errorlog and my docker compose.

https://hastebin.com/qezezurede.rb

![screen shot 2018-09-08 at 10 12 26](https://user-images.githubusercontent.com/30061229/45250997-c1cc9a80-b34f-11e8-965f-c51b6d9cc088.png)

Thank you

**Comment by nicolargo** [comment]
Reproduced...

I will have a look.

**Comment by nicolargo** [comment]
It is not a Glances or PsUtil issue:

```
$ docker run --rm -it nicolargo/glances /bin/bash
root@34008e20deba:/glances# df -kh
Filesystem                          Size  Used Avail Use% Mounted on
none                                227G  166G   50G  77% /
tmpfs                               3.7G     0  3.7G   0% /dev
tmpfs                               3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/mapper/ubuntu--gnome--vg-root  227G  166G   50G  77% /etc/hosts
shm                                  64M     0   64M   0% /dev/shm
tmpfs                               3.7G     0  3.7G   0% /sys/firmware
```

As a workaround, add the following lines to your Glances configuration file:

```
[fs]
# Define the list of hidden file system (comma-separated regexp)
hide=/etc/hosts,/sys/firmware
```

**Comment by nicolargo** [comment]
hide=/dev/loop*

**Comment by dvision1979** [comment]
@juan11perez
late to the party, but in order to be able to see the disks in docker, one needs to also add the following to the volumes under the docker-compose.yml:
`- /run/udev:/run/udev:ro`
I hope this will help others looking for a solution for this issue.
