### ISSUE TITLE
[ENHANCEMENT] Disable automatic sorting between cpu_percent, io_counters and memory_percent

### ISSUE THREAD

**Issue by Hypocritus** [nicolargo/glances#1317]
A user can choose to sort the process list by cpu percentage, memory usage, i/o ... etc, or to have glances automatically sort the process list.

However even though the user can select their desired manner of sorting, the list reverts to being automatically sorted according to alert thresholds pre-set in the glances.conf file. This feature has been troublesome for me. (I have just now figured out how to prevent automatic sorting from removing the view I have set by editing the alert thresholds in the glances.conf file).

Desired behavior: Allow the disabling of automatic sorting irrespective of alert status

Behavior is the same between the following two builds:
1) Ubuntu Xenial (16.04 LTS) default repository, as well as 
2) source-built Glances v2.11.1 with psutil v5.4.6

**Comment by nicolargo** [comment]
Hi @Hypocritus ,

if i understand your need, you want an option to disable the automatic processes sort when sort configuration is not set to "automatic" and an alert is reached.

Are we agree ?

Nicolas

**Comment by Hypocritus** [comment]
Hi @nicolargo,

Yes, that is correct.

**Comment by nicolargo** [comment]
Implementation done as a default behavior (without any command line option) in the DEVELOP branch.
Will be release in Glances 3.1.

Please can you test it on your system ?

**Comment by Hypocritus** [comment]
@nicolargo just wanted to drop a line and say _very_ nice work with this project, and thanks for the continued support!
