### ISSUE TITLE
Add action script on alert

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#132]
Upon trigger (for exemple critical alert on free diskspace) a mail will be sent to a administrator.

**Comment by nicolargo** [comment]
As a bonus, you can also use stats values as {{mustache}} tag in the command line:

```
 [fs]
# Default limits for free filesytem space in %
# Default values if not defined: 50/70/90
careful=20
careful_action=echo {{mnt_point}} {{used}}/{{size}} > /tmp/fs.alert
warning=70
critical=90
```

**Comment by nicolargo** [comment]
Feature available on the develop branch (commit: 283af00).

Should be beta-tested with a maximum of case.

===

Glances can trigger actions on events. 

By action, we mean all shell command line. For example, if you want to execute the foo.py script if the last 5 minutes load are critical then add the action line to the Glances configuration file:

```
[load]
critical=5.0
critical_action=python /path/to/foo.py
```

All the stats are usable in the command line by the use of the {{mustache}} syntax. Another example to create a log file containing used vs total disk space if a warning space trigger is reached:

```
[fs]
warning=70
warning_action=echo {{mnt_point}} {{used}}/{{size}} > /tmp/fs.alert
```

Note: You can use all the stats for the current plugin (see https://github.com/nicolargo/glances/wiki/The-Glances-2.x-API-How-to for the stats list)

===

**Comment by APalau82** [comment]
Hi 
I would like to cumulate action script with cron to be alerted when fs size is in warning status.
But while running glances with cron (* * * * * /usr/bin/glances) the {{mustaches}} values are not replaced by the real values. 'fs.alert' file litterally prints : "{{mnt_point}} {{used}}/{{size}}".
While running manually glances, the output is correct : / 1571274752/3102470144

By the way if glances starts automatically with cron does it mean that it never stops ?
Thanks

**Comment by iseriousnoob** [comment]
Is it available in master already?
