### ISSUE TITLE
Docker image for ARM architecture

### ISSUE THREAD

**Issue by nemchik** [nicolargo/glances#1320]
#### Description

For an enhancement or new feature: it would be cool if there were a docker image for ARM, or if your existing image were multi-arch like portainer.

**Comment by nicolargo** [comment]
Two new Dockerfiles added to the DEVELOP branch:

* [One based on Alpine](https://github.com/nicolargo/glances/blob/develop/docker-files/devel-alpine/Dockerfile) 
* [One based on Alpine ARM](https://github.com/nicolargo/glances/tree/develop/docker-files/devel-arm)

The first one build ok on my computer but not on Docker Hub.
No idea for the second one. Do not have any ARM device to test it.

**Comment by SirTerrific** [comment]
I saw on the hub that the image ARM was on error. I build one with alpine:3.8 and it seems to work well

#
# Glances Dockerfile for ARM (based on Alpine ARM)
#
# https://github.com/nicolargo/glances
#

# Pull base image.
FROM alpine:3.8

# Install Glances (develop branch)
RUN apk add python py2-psutil py2-bottle
RUN apk add git
RUN git clone -b develop https://github.com/nicolargo/glances.git

# Define working directory.
WORKDIR /glances

# EXPOSE PORT (For XMLRPC)
EXPOSE 61209

# EXPOSE PORT (For Web UI)
EXPOSE 61208

# Define default command.
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
~                                                                                                                                                                                                                  
~                                                                                                                                                                                                                  
~

**Comment by cricket007** [comment]
Added PR for this @nicolargo . I decided to build from `python:2.7-alpine` rather than `apk add python` manually.
