### ISSUE TITLE
Sorting by process time works not as expected

### ISSUE THREAD

**Issue by IchSchreiGleich** [nicolargo/glances#1321]
#### Description

Sorting by process time not sorting in expected order

![2018-09-18_112021](https://user-images.githubusercontent.com/5748547/45677607-dde0f080-bb34-11e8-9532-a87de494a144.png)

#### Versions

* Glances v3.1.0_beta with psutil v5.4.7
* FreeBSD 11.2-RELEASE-p2

#### Logs

Debug log offers no forther informations

**Comment by nicolargo** [comment]
It looks like a PsUtil issue:

```
$ ipython
In [1]: import psutil 

In [67]: p1 = psutil.Process(1575)
In [68]: p2 = psutil.Process(2937)

In [71]: p1.cpu_times()
Out[71]: pcputimes(user=1327.5, system=132.68, children_user=0.0, children_system=0.0)
In [72]: p2.cpu_times()
Out[72]: pcputimes(user=1263.44, system=654.21, children_user=0.03, children_system=0.0)

In [74]: p1.cpu_times() > p2.cpu_times()
Out[74]: True
```

It should be False. Only the user CPU time is take into account, not the system...

**Comment by nicolargo** [comment]
Corrected in the latest commit.

@IchSchreiGleich Please can you check on the DEVELOP branch ?
