### ISSUE TITLE
Glances shows memory and used space in kilobytes while running in web server mode (in Safari)

### ISSUE THREAD

**Issue by Burekas** [nicolargo/glances#1322]
#### Description

Glances shows memory and used space in kilobytes while running in web server mode

#### Versions

* Glances & psutil (glances -V): Glances v3.0.1 with psutil v5.4.7
* Operating System (lsb_release -a): Ubuntu 18.04.1 LTS

<img width="372" alt="screen shot 2018-09-21 at 12 00 00 pm" src="https://user-images.githubusercontent.com/2567471/45871618-98bbf900-bd96-11e8-8ceb-a00f47643110.png">
<img width="164" alt="screen shot 2018-09-21 at 12 00 09 pm" src="https://user-images.githubusercontent.com/2567471/45871619-98bbf900-bd96-11e8-9357-d2f9fb317867.png">

**Comment by joker999** [comment]
Yes I got that too.

**Comment by nicolargo** [comment]
@notFloran Can you have a look ?

**Comment by notFloran** [comment]
@joker999 @Burekas can you copy/paste the result of http://0.0.0.0:61208/api/3/mem or http://0.0.0.0:61208/api/3/fs ?

**Comment by Burekas** [comment]
MEM:

> {"available": 7395844096, "used": 807686144, "cached": 4714872832, "percent": 9.8, "free": 7395844096, "inactive": 3487711232, "active": 2045448192, "shared": 3948544, "total": 8203530240, "buffers": 659632128}

FS:

> [{"mnt_point": "/", "fs_type": "ext4", "free": 15918989312, "key": "mnt_point", "size": 19550347264, "percent": 14.1, "used": 2614661120, "device_name": "/dev/mapper/vg-root"}, {"mnt_point": "/boot", "fs_type": "ext4", "free": 305809408, "key": "mnt_point", "size": 486105088, "percent": 33.0, "used": 150568960, "device_name": "/dev/sda1"}, {"mnt_point": "/mnt/timemachine_ex", "fs_type": "ext4", "free": 28238708736, "key": "mnt_point", "size": 491180957696, "percent": 93.9, "used": 437920186368, "device_name": "/dev/sde1"}, {"mnt_point": "/home", "fs_type": "ext4", "free": 18422927360, "key": "mnt_point", "size": 19550347264, "percent": 0.6, "used": 110723072, "device_name": "/dev/mapper/vg-home"}, {"mnt_point": "/var", "fs_type": "ext4", "free": 25551822848, "key": "mnt_point", "size": 56180178944, "percent": 52.4, "used": 28077248512, "device_name": "/dev/mapper/vg-var"}, {"mnt_point": "/mnt/parity/parity1", "fs_type": "ext4", "free": 72251211776, "key": "mnt_point", "size": 3999180890112, "percent": 98.2, "used": 3926912901120, "device_name": "/dev/sdb1"}, {"mnt_point": "/mnt/data/disk1", "fs_type": "xfs", "free": 151403991040, "key": "mnt_point", "size": 3998831599616, "percent": 96.2, "used": 3847427608576, "device_name": "/dev/sdd1"}, {"mnt_point": "/tmp", "fs_type": "ext4", "free": 896598016, "key": "mnt_point", "size": 965763072, "percent": 0.3, "used": 2478080, "device_name": "/dev/mapper/vg-tmp"}, {"mnt_point": "/mnt/irinas_usb", "fs_type": "fuseblk", "free": 514098200576, "key": "mnt_point", "size": 1000204795904, "percent": 48.6, "used": 486106595328, "device_name": "/dev/sdf1"}, {"mnt_point": "/var/watch", "fs_type": "ext4", "free": 43693056, "key": "mnt_point", "size": 48602112, "percent": 2.4, "used": 1093632, "device_name": "/dev/mapper/vg-watch"}, {"mnt_point": "/mnt/data/disk2", "fs_type": "xfs", "free": 312375320576, "key": "mnt_point", "size": 3998831599616, "percent": 92.2, "used": 3686456279040, "device_name": "/dev/sdc1"}]

**Comment by joker999** [comment]
MEM:
 
> {"available": 498999296, "used": 473231360, "cached": 272977920, "percent": 48.7, "free": 498999296, "inactive": 465342464, "active": 390086656, "shared": 6782976, "total": 972230656, "buffers": 257818624}

FS:

> [{"mnt_point": "/", "fs_type": "ext4", "free": 20849172480, "key": "mnt_point", "size": 28715270144, "percent": 23.4, "used": 6383833088, "device_name": "/dev/root"}, {"mnt_point": "/boot", "fs_type": "vfat", "free": 48186368, "key": "mnt_point", "size": 71222272, "percent": 32.3, "used": 23035904, "device_name": "/dev/mmcblk0p6"}, {"mnt_point": "/media/pi/SETTINGS", "fs_type": "ext4", "free": 28631040, "key": "mnt_point", "size": 31437824, "percent": 1.6, "used": 458752, "device_name": "/dev/mmcblk0p5"}, {"mnt_point": "/mnt", "fs_type": "fuseblk", "free": 495500107776, "key": "mnt_point", "size": 750121869312, "percent": 33.9, "used": 254621761536, "device_name": "/dev/sda1"}]

**Comment by notFloran** [comment]
@joker999 @Burekas which browser did you use?

**Comment by joker999** [comment]
first, on my ios12 iPhone 7 Plus (safari), I paste these code from my
chrome browsers Version 70.0.3538.22 (Official Build) beta (64-bit)  seem
fine on it. Just iPhone problem I guess.

**Comment by notFloran** [comment]
Thanks, I can now reproduce the problem with safari (mac and ios)

**Comment by nicolargo** [comment]
@Burekas @joker999 Can you please test the DEVELOP branch and tell us if the problem is solved ?

Thnaks !

**Comment by Burekas** [comment]
@nicolargo , it's fixed in develop. Thank you.
