### ISSUE TITLE
RuntimeWarning: ignoring OSError(22, 'Invalid argument')   warnings.warn("ignoring %r" % err, RuntimeWarning)

### ISSUE THREAD

**Issue by ATLief** [nicolargo/glances#1330]
Every time I open glances, the following message is printed before the main interface appears:
`/usr/lib/python3/dist-packages/psutil/_pslinux.py:1191: RuntimeWarning: ignoring OSError(22, 'Invalid argument') warnings.warn("ignoring %r" % err, RuntimeWarning)`

Everything else works, it's just annoying.

#### Versions

* Glances & psutil: Glances v2.11.1 with psutil v5.4.2
* Operating System: Ubuntu 18.04.1 LTS

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/1203

A patch is already available here: https://github.com/nicolargo/glances/commit/49fafb6db4d267d5484e32cfbeb65ec6d74c6d1a

It will be release in the next release.
