### ISSUE TITLE
Window 10 doesn't report cpu_temp

### ISSUE THREAD

**Issue by ccollinscj** [nicolargo/glances#1332]
Window 10 doesn't report cpu_temp,  run the latest version of Python and Glances.

**Comment by nicolargo** [comment]
Glances 3.0 and higher uses the PsUtil lib to grab system temperatures values.

Unfortunately, and for the moment, the PsUtil sensor methods are only available on Linux and Mac OS (read this: https://github.com/giampaolo/psutil/issues/371).
