### ISSUE TITLE
gpu plugin not exported to influxdb

### ISSUE THREAD

**Issue by p5a0u9l** [nicolargo/glances#1333]
#### Description

found problem, duplicate entry of `uptime` - not fixed on develop, so will fix and push a PR.

**Comment by p5a0u9l** [comment]
ok, well. unable to push my branch. So, may be easier for you to fix, or you can advise on pushing a new branch?

Here is output from `git diff`
```
@ glances_export.py:74 @ class GlancesExport(object):
                'uptime',
                'sensors',
                'docker',
                'uptime',
                'gpu']

    def load_conf(self, section, mandatories=['host', 'port'], options=None):
```

**Comment by p5a0u9l** [comment]
I tested by restarting glances and verifying that the gpu plugin was now seen inside influx.

**Comment by nicolargo** [comment]
@p5a0u9l Thanks ! Just commit it on the develop branch.
