### ISSUE TITLE
Timezone listed doesn’t match system timezone, outputs wrong time

### ISSUE THREAD

**Issue by johndrinkwater** [nicolargo/glances#1337]
#### Description

In the bottom left of a default glances install, it will output the current date, time, and timezone

Which appears as `2018-10-19 11:02:56 GMT`

However the current time is **11:02:56 BST**, which is _10:02:56 GMT_

```
❯ date --iso-8601=seconds
2018-10-19T11:03:11+0100
````

#### Versions

* Glances & psutil (glances -V): Glances v3.0.2 with psutil v5.4.7
* Operating System (lsb_release -a): Ubuntu 15.10

Having quickly glanced over the source, the change in https://github.com/nicolargo/glances/commit/e3e1aaf303872ec1f4447900a56d1e54c744260d #1249 is incorrect and treats `tzname[0]` as the active timezone, when that isn’t always true.

```
john@joran ~ ❯ python
>>> from time import tzname
>>> tzname
('GMT', 'BST')
```

**Comment by nicolargo** [comment]
Corrected in latest commit.

Thanks for the report !

**Comment by johndrinkwater** [comment]
Hey, sorry for the feedback, but I don’t think this is robust enough as tzname will always be 2 items for my country whether in daylight time or not.

Had a quick poke in python interactive, and there are two easier solutions with strftime producing the output,

Either using `tzlocal` module to fetch local TZ & inject into the naive datetime variable:
```
from tzlocal import get_localzone

self.stats = datetime.now( get_localzone() ).strftime('%Y-%m-%d %H:%M:%S %Z')    
return self.stats
```

or using just `time` to resolve this, as it seems to be better aware of its position in spacetime:
```
self.stats = time.strftime('%Y-%m-%d %H:%M:%S %Z')
return self.stats
```

**Comment by fcalvet** [comment]
Hey,

First thanks for this tool, but I don't think this is fixed, as in my situation I think tzname[0] should be used instead of tzname[1].
```
> date --iso-8601=seconds
2019-10-29T12:13:28+01:00
```
The output of glances is 

> 2019-10-29 12:13:53 CEST

Which should be CET and not CEST (as it the one corresponding to +02:00 and not +01:00).

```
>>> print(tzname)
('CET', 'CEST')
```
Versions

    Glances & psutil (glances -V): Glances v3.1.3 with psutil v5.6.3
    Operating System: Ubuntu 19.10
