### ISSUE TITLE
error type host : AWS EC2 on VM public OVH ;( 

### ISSUE THREAD

**Issue by batchris** [nicolargo/glances#1340]
Hi,

when use Glances over VM (public cloud ovh)
the type of host is AWS EC2 ... WHOUA !   
OVH reseal AWS EC2 ?!? joke ;)

the host type after is good.

"AWS EC2 hg-30-ssd-flex instance i-00b18f3e (nova)"
see screen 

![glances_bug_vm_ovh_screenshot from 2018-10-23 11-24-46_bis](https://user-images.githubusercontent.com/926352/47350980-58160f00-d6b7-11e8-8a41-079401720624.png)

alors que 
```
ubuntu@xxxxxxxx:~$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-00022c1f
ubuntu@xxxxxxxx:~$ curl http://169.254.169.254/latest/meta-data/instance-type
hg-30-ssd-flex
ubuntu@xxxxxxxx:~$
```

#### Versions

* Glances & psutil (glances -V):
* Operating System (lsb_release -a):

```
ubuntu@xxxxxxx:~$ glances -V
Glances v2.11.1 with psutil v5.4.2
ubuntu@xxxxxxx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
ubuntu@xxxxxx:~$ 
```

#### Logs

```
.../...
2018-10-23 09:34:40,080 -- INFO -- [{'msg': 'AWS EC2', 'decoration': 'TITLE', 'optional': False, 'additional': False, 'splittable': False}, {'msg': ' hg-30-ssd-flex instance i-00b18f3e (nova)', 'decoration': 'DEFAULT', 'optional': False, 'additional': False, 'splittable': False}]
.../...
```
@

Very thank's
for your grazy work
Chris.

**Comment by batchris** [comment]
idem pour la version 3.x de glances

```
ubuntu@xxxxxx:~$ sudo glances -V
Glances v3.0.2 with psutil v5.4.7
ubuntu@xxxxxx:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
ubuntu@xxxxxx:~$ 
```

**Comment by nicolargo** [comment]
C'est étrange... Cela veut dire qu'OVH a implémenté la même API de meta-donnée que AWS ? Pourtant je ne trouve pas trace de la requête /latest/meta-data dans la doc de l'API OVH: https://eu.api.ovh.com/console/#/

**Comment by batchris** [comment]
> Es-tu sûr que c'est celle de ta machine ?
Je ne suis sûr de rien ...

ce que je suis sur, c'est que OVH pour son public cloud utilise openStack pour le "compute"
qui implémente le meme genre de service metadata

https://docs.openstack.org/nova/latest/user/metadata-service.html

A suivre ...

**Comment by nicolargo** [comment]
Haha... les couccinous d'Amazon qui font passer leur API comme maison alors que c'est juste celle d'OpenStack... 

Tu peux me donner le résultat de la commande suivante sur ta machine ?

```
curl http://169.254.169.254/latest/meta-data
```

**Comment by batchris** [comment]
```
ubuntu@ubuntu@xxxxxx:~$ curl http://169.254.169.254/latest/meta-data
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
hostname
instance-action
instance-id
instance-type
local-hostname
local-ipv4
placement/
public-hostname
public-ipv4
public-keys/
reservation-id
security-groups
ubuntu@xxxxxx:~$ 
```

ps/ veux tu une vm en pret/test ? envoi moi clef ssh public si tu veux

**Comment by nicolargo** [comment]
Here it is:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCs0ZMcSvcJwW+Fk1+eJjylUwiftKncFhf1oVMXU2oii+pTPpQa5HcfW4go4jUdbtocOr3Yya0wxlOMdo/1ifwDQb4XwV6tzGtlR2lI8CxQBckGV8a4nbNSvExRM/ft28fDGvk73X+DzMalne++/63ETf+KKTrfNzpGiETdEcwaBVg6YzO8yXkC92paIkwjy+IK4Uf9ANBDr0aY5WP3N/bV+tC0PvxA6qmkho0lF/QVgw5gGoF6HI++m3JV+qZ/6+lMKd1J7K+YQa3WAI/gt5XN+wbYpv7vxcn+mTL9VghSJnAWMpsjTVDitpU24BbeB/w01BekNsDxF8cRcL4nvg7V4wbDFYSLw2Oj/3hr89WtCuZAbBKjrryaX3rbce8yMfb7nYWxPLFUU1K2UCgGNDZVfOAq/+eam70Hn5I72rTi1Y1YXKllYIpZ5lrnnWV2k0nRUP4fFZEVnvQ+VXjebCMis+hQuZzUUlerxcPsGoLApXq35GYHxfOPrBQg2bU1dI2swDkaNc0tI/2cgAaabsuFT4jBvCgTjTRmkRFkqCgkcJyEgZnwzJMf9cat+DP+zqpBNkoRRKtXxYDSHXW9ipvPPm6UGjpSwl7tVTo45rBJKykoSxjWiuE3Baw3Iy627P5DR/RYLavA3xXkmAqc883F+CoyoN/KhPZsYSnADyTj8Q== nicolas@nicolargo.com
```

**Comment by batchris** [comment]
le mail vient de partir ;)

**Comment by nicolargo** [comment]
J'obtiens ca:

```
$ for u in `curl http://169.254.169.254/latest/meta-data`; do echo $u; curl http://169.254.169.254/latest/meta-data/$u; echo; echo "==="; done
===
ami-id
ami-00030e20
===
ami-launch-index
0
===
ami-manifest-path
FIXME
===
block-device-mapping/
ami
root
===
hostname
for-glances
===
instance-action
none
===
instance-id
i-00b95769
===
instance-type
vps-ssd-1
===
local-hostname
for-glances
===
local-ipv4
213.32.73.50
===
placement/
availability-zone
===
public-hostname
for-glances
===
public-ipv4

===
public-keys/
0=arbo_chris_jes
===
reservation-id
r-dupxn5v7
===
security-groups
default
===
```

**Comment by batchris** [comment]
> instance-type
> vps-ssd-1

a l'air pas mal ;)

**Comment by batchris** [comment]
le post initiale

j'avais obtenu sur un autre type de machine

```
ubuntu@xxxxxxxx:~$ curl http://169.254.169.254/latest/meta-data/instance-type
hg-30-ssd-flex
```

**Comment by nicolargo** [comment]
![selection_007](https://user-images.githubusercontent.com/776747/47955709-29901200-df9c-11e8-928c-517463b5190f.jpg)

**Comment by nicolargo** [comment]
J'ai fait la modification sur la branche DEVELOP.

**Comment by batchris** [comment]
Magnifique !

**Comment by batchris** [comment]
merci ton outil est tellement bien ! bravo !

**Comment by nicolargo** [comment]
C'est surtout grâce aux utilisateurs qui me pousse à encore le faire évoluer !

N'hésite pas si tu as d'autres remarques.

Encore merci pour la VM. Tu peux enlever ma clé SSH ;)
