### ISSUE TITLE
Static binary

### ISSUE THREAD

**Issue by sachk** [nicolargo/glances#1342]
Hello, I'm just wondering if there's a way to compile a fully static binary for glances. It'd be useful in some edge cases.

**Comment by nicolargo** [comment]
You can have a look on https://github.com/nicolargo/glancesautopkg
There is a target for a full self contain sh.
Never tested it...

**Comment by nicolargo** [comment]
If you find a way to do it, please feel free to contribute through a [Wiki page](https://github.com/nicolargo/glances/wiki).

**Comment by sachk** [comment]
Isn't that just an installer that still requires root access and is split among multiple dependencies when installed?

**Comment by nicolargo** [comment]
You can try to use https://pyinstaller.readthedocs.io/en/stable/usage.html

Never tested, keep us inform if you find a way to do it.

**Comment by ejfine** [comment]
are you still open to having someone create a Pull Request to enable pyinstaller compilation of a windows binary?  (or did someone try at some point since 2018 and run into major challenges?)

**Comment by nicolargo** [comment]
Still open but the major issue with Glances packaging is plugins' dynamic import. It generates some troubles with binary packaging (same issue with Nuitka).

Related issue:

- https://github.com/nicolargo/glances/discussions/3153#discussioncomment-12904435
- https://github.com/nicolargo/glances/issues/3156

**Comment by ejfine** [comment]
Good to know.  I'll poke around.  I've done some work before with `hidden_imports` in pyinstaller---not sure yet if that's the same thing going on with the "plugin dynamic imports"
