### ISSUE TITLE
Problem installation OVH Vps

### ISSUE THREAD

**Issue by Hotfirenet** [nicolargo/glances#1346]
I can't install glances , have you got an idea ?

```
pip install glances
Collecting glances
  Using cached https://files.pythonhosted.org/packages/59/32/3bc36a9198998a4d73d5b19b02e0a59cde96fa1d8dccce05015a9b1929b7/Glances-3.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-of9Gk_/glances/
```

Thanks

**Comment by nicolargo** [comment]
What is your Python version ?

```
python -V
```

Glances 3.0 and higher is only compatible with Python 2.7...

If you want to use Glances with Python 2.6, try Glances 2.6.2 (latest Glances version with Python 2.6 support).

**Comment by Hotfirenet** [comment]
Bonjour Nicolargo,
merci de prendre le temps de me répondre.
```
python -V
Python 2.7.13
```
en faite j'ai utilisé basiquement initialement la commande 
`
curl -L https://bit.ly/glances | /bin/bash
`

**Comment by Hotfirenet** [comment]
Une idée ?

**Comment by nicolargo** [comment]
pip install setuptools

**Comment by Hotfirenet** [comment]
yep impec, merci @nicolargo
