### ISSUE TITLE
Is there a way  to filter block devices by pattern

### ISSUE THREAD

**Issue by neith00** [nicolargo/glances#1349]
On glances version v3.0.2 , Is there a way  to filter block devices by pattern?
I have dozen of block devices on the host and I want to be able to exclude some of them on display.
For example I would like to hide all loop devices such as /dev/loop* ou /dev/loop[0-9].
Any clue?

**Comment by nicolargo** [comment]
Yes, it is poissible using the Glances configuration file.

Read this: https://glances.readthedocs.io/en/stable/aoa/disk.html

**Comment by clemisch** [comment]
Link is broken, but it's pretty easy to use the relevant bits from the [config template](https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf) (if anybody else is reading this).
