### ISSUE TITLE
ERROR -- Can not grab extended stats (invalid attr name 'num_fds')

### ISSUE THREAD

**Issue by jack10bells** [nicolargo/glances#1351]
I've just installed Glances on Windows 2012R2 64bits server and found out this messaje in the log file.
Before that I tested on a Windows 10 Home laptop and works fine.

I point out that in the Windows server Glances was started in Web Server mode (glances -w) because in client/server mode didn't worked as stated in https://github.com/nicolargo/glances/issues/1157. In Windows 10 it was run in Standalone mode.

What is more, it delays 15 minutes between each log writing, what I find odd (is there any parameter to config this?)

**Comment by nicolargo** [comment]
Please fill the issue with the following information:

* Glances & psutil (glances -V): ?
* Operating System (lsb_release -a): ?

**Comment by jack10bells** [comment]
Glances v3.0.2 with psutil v5.4.8
OS: Windows Server 2012 R2 Standard 64 bits

**Comment by jack10bells** [comment]
Hi Nicole, I will test it in a while and let you know about the results. On the other hand, I know that is out of this thread but I couldn't find the way to make actions work without client connection (as Standalone or Web Server modes). I need the server to be monitored without a client connection. Is that possible?
Thanks in advance

**Comment by jack10bells** [comment]
Nico, in Develop branch works just fine!!
Thanks a lot
