### ISSUE TITLE
Trigger actions without a client connection on Windows

### ISSUE THREAD

**Issue by jack10bells** [nicolargo/glances#1355]
Is it possible to monitor system without a client connection, no matter Standalone, Client/Server or WebServer mode? 
I need to monitor servers without a client to connect to them and make them trigger actions according certain threshold, but don't need an operator to be connected to the servers.
Is it there any parameter or something to do that? I've tried --quite and nothing happens.
OS: Windows 10 HOME and Windows 2012R2, both 64 bit
SW versions: Glances v3.0.2 with psutil v5.4.6

**Comment by nicolargo** [comment]
Never tested it on Windows. Did you try to run Glances in server mode (-s) ?

The Glances' actions did not need any operator. Just ran Glances and all the trigger configured in the Glances configuration file will be done: https://glances.readthedocs.io/en/stable/aoa/actions.html

**Comment by jack10bells** [comment]
Not working on Windows 2012R2 nor server mode
On the other hand, same config file on Windows 10 as Standalone or Webserver mode refreshes Glances every 8 seconds but on Windows 2012R2 Server it works every 15 minutes!!! No parameters for time refreshing used in the command line nor the URL. Where other place do I have to look for?

**Comment by jack10bells** [comment]
I can't trigger actions on folders. Is there a differente way to do that?
In my conf file:

folder_1_path=c:\my_folder
folder_1_careful=2
folder_1_warning=3
folder_1_warning_action = python %%APPDATA%%\glances\nbk_monitor_stats.py "folders" {{size}} "warning" 
folder_1_critical=4

nbk_monitor_stats.py is my Python script that receives 3 parameters
I running this on a Windows Server 2012R2

**Comment by nicolargo** [comment]
Perhaps related to https://github.com/nicolargo/glances/issues/1358

**Comment by nicolargo** [comment]
Concerning the refresh time, can you paste/bin us the Glances log file (https://glances.readthedocs.io/en/stable/config.html) ?

**Comment by jack10bells** [comment]
Already uploaded. Also check if folders section is all right.
[glances.conf.txt](https://github.com/nicolargo/glances/files/2640913/glances.conf.txt)

**Comment by jack10bells** [comment]
The following configuration shows the different thresholds in the curse screen but does not run any Python script (Windows 10 Home or Windows 2012R2 Server):

folder_1_path=C:\Users\jack1\AppData\Roaming\glances
folder_1_careful=20
folder_1_careful_action_repeat = python %%APPDATA%%\glances\nbk_monitor_stats.py "folder_1" {{size}} "careful"
folder_1_warning=30
folder_1_warning_action_repeat = python %%APPDATA%%\glances\nbk_monitor_stats.py "folder_1" {{size}} "warning"
folder_1_critical=40
folder_1_critical_action_repeat = python %%APPDATA%%\glances\nbk_monitor_stats.py "folder_1" {{size}} "critical"

**Comment by nicolargo** [comment]
Corrected on the latest commit.

Please test the DEVELOP branch.

Examples for folder:

```
[folders]
# Define a folder list to monitor
# The list is composed of items (list_#nb <= 10)
# An item is defined by:
# * path: absolute path
# * careful: optional careful threshold (in MB)
# * warning: optional warning threshold (in MB)
# * critical: optional critical threshold (in MB)
folder_1_path=/tmp
folder_1_careful=2500
folder_1_warning=3000
folder_1_critical=3500
folder_2_path=/home/nicolargo/Videos
folder_2_warning=1000
folder_2_critical=2000
folder_2_critical_action=echo "TOTO" > /tmp/test_folder.txt
```

and for ports:

```
[ports]
# Ports scanner plugin configuration
# Interval in second between two scans
refresh=30
# Set the default timeout (in second) for a scan (can be overwritten in the scan list)
timeout=3
# If port_default_gateway is True, add the default gateway on top of the scan list
port_default_gateway=True
#
# Define the scan list (1 < x < 255)
# port_x_host (name or IP) is mandatory
# port_x_port (TCP port number) is optional (if not set, use ICMP)
# port_x_description is optional (if not set, define to host:port)
# port_x_timeout is optional and overwrite the default timeout value
# port_x_rtt_warning is optional and defines the warning threshold in ms
#
port_1_host=www.google.com
port_1_port=80
port_1_description=Google site
port_1_timeout=1
port_1_rtt_warning=40
port_1_rtt_warning_action=echo titi > /tmp/test.txt
```

**Comment by jack10bells** [comment]
Hi Nico, still is not working. Updated from DEVELOP branch glances dir and subdirs, not docker-files, not docs, etc, but glances dir and subdirs only

**Comment by nicolargo** [comment]
Can you start Glances with the debug mode option (-d) and paste/bin us the Glances log file (https://glances.readthedocs.io/en/stable/config.html#logging) ?

**Comment by jack10bells** [comment]
[glances-jack10bells.log](https://github.com/nicolargo/glances/files/2659740/glances-jack10bells.log)
Log file uploaded

**Comment by nicolargo** [comment]
Strange... Perhaps the action script is not found. Can you make a simple test with the following configuration and check if the file c:\test.txt is created.

```
folder_1_path=c:\my_folder
folder_1_careful=200
folder_1_warning=500
folder_1_warning_action=echo 'TEST' > c:\test.txt
folder_1_critical=900
```

**Comment by jack10bells** [comment]
No, the file is not created

**Comment by nicolargo** [comment]
Are you sure that the folder size is higher than 500 MB ?

**Comment by nicolargo** [comment]
In your log file i see:

```
2018-12-08 11:13:47,790 -- DEBUG -- Plugin folders update return [{'indice': '1', 'path': 'C:\\Users\\jack1\\AppData\\Roaming\\glances', 'careful': '2', 'careful_action': 'python %APPDATA%\\glances\\nbk_monitor_stats.py "folder_1" {{size}} "careful"', 'warning': '3', 'warning_action': 'python %APPDATA%\\glances\\nbk_monitor_stats.py "folder_1" {{size}} "warning"', 'critical': '4', 'critical_action': 'python %APPDATA%\\glances\\nbk_monitor_stats.py "folder_1" {{size}} "critical"', 'size': 2314760}]
```
The size of the folder is 2314760 Bytes ==> 2.3 MBytes.
Your warning threshold is 3 MB...

**Comment by jack10bells** [comment]
No, folder size is 2.3 MBytes, just for testing actions in folders. I stated thresholds as follows:

folder_1_path=C:\Users\jack1\AppData\Roaming\glances
folder_1_careful=2
folder_1_careful_action = echo 'TEST' > c:\test.txt
folder_1_warning=3
folder_1_critical=4

In the curse inteface it works with these sizes as I can see folders stats change of colour (green, blue, violet, red) as it changes folder size. Screens attteched
 
![glances_folders_careful](https://user-images.githubusercontent.com/9864785/49698780-4628f680-fba7-11e8-818e-91c9aaf8bfaf.png)
![glances_folders_critical](https://user-images.githubusercontent.com/9864785/49698781-4628f680-fba7-11e8-9bb3-aaf18b54a89d.png)
![glances_folders_normal](https://user-images.githubusercontent.com/9864785/49698782-4628f680-fba7-11e8-9716-8ffd38529218.png)
![glances_folders_warning](https://user-images.githubusercontent.com/9864785/49698783-4628f680-fba7-11e8-94f1-ca12d291720e.png)

**Comment by nicolargo** [comment]
It works on my Ubuntu system with the following configuration:

```
[folders]
folder_1_path=/tmp
folder_1_careful=2500
folder_1_warning=3000
folder_1_critical=3500
folder_2_path=/home/nicolargo/tmp
folder_2_warning=1
folder_2_critical=2
folder_2_critical_action=echo "TEST" > /tmp/test_folders.txt
```

Action is triggered when i put a file in the folder:

![selection_010](https://user-images.githubusercontent.com/776747/49702237-51574300-fbf6-11e8-95b3-96b07b0b4650.jpg)

And the file is created in the /tmp folder:

![selection_011](https://user-images.githubusercontent.com/776747/49702247-5b794180-fbf6-11e8-91e6-42afc7405588.jpg)

Do not know why it did not work on Windows...

If you have an idea, let me known.

**Comment by jack10bells** [comment]
I will try to investigate inside the code. Should I have to dive into the glances_folders.py only or is any other piece of code to check?

**Comment by nicolargo** [comment]
Any news ?

**Comment by jack10bells** [comment]
Hi, I couldn't check any further. Is not working in Windows 10 nor Windows 2008 R2
