### ISSUE TITLE
unable to see diskio

### ISSUE THREAD

**Issue by scurrvy2020** [nicolargo/glances#1356]
I'm not able to view the diskio section of glances.  I have tried the latest version (3.0.2) and an older version (2.11) and I still have the issue.  I have the same issue with multiple computers. 
I've pressed 'd' after loading and it still does not show me diskio. 

I've checked journalctl for errors and there are no errors present. 

I'd be grateful for any help.

**Comment by nicolargo** [comment]
Any log message in the Glances log file  (/tmp/glances-*.log) ?

Do you have a screenshot ?

**Comment by recteurlp** [comment]
I got the same issue

Thanks for the log file path 😋 

I thought my RAID was preventing the plugin from loading:

```
2018-11-27 02:45:30,039 -- INFO -- Start Glances 3.0.2
2018-11-27 02:45:30,039 -- INFO -- CPython 3.7.1 and psutil 5.4.3 detected
2018-11-27 02:45:30,050 -- INFO -- Search glances.conf file in /root/.config/glances/glances.conf
2018-11-27 02:45:30,051 -- INFO -- Search glances.conf file in /etc/glances/glances.conf
2018-11-27 02:45:30,076 -- INFO -- Start GlancesStandalone mode
2018-11-27 02:45:30,085 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2018-11-27 02:45:30,111 -- WARNING -- Missing Python Lib (No module named 'pynvml'), Nvidia GPU plugin is disabled
2018-11-27 02:45:30,461 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2018-11-27 02:45:30,580 -- WARNING -- Missing Python Lib (No module named 'cpuinfo'), Quicklook plugin will not display CPU info
2018-11-27 02:45:30,607 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2018-11-27 02:46:21,002 -- INFO -- Glances stopped (keypressed: CTRL-C)
```

So after ```pip install pymdstat nvidia-ml-py3 py-cpuinfo wifi netifaces``` i got a new "RAID disks" section but still no Disk I/O with no error in log.

I'am on Fedora 29 with Python 3, i've tried the docker image as well with no luck.

**Comment by scurrvy2020** [comment]
My logs also do not have any errors.

**Comment by scurrvy2020** [comment]
screen clip:
![image](https://user-images.githubusercontent.com/20618759/49057870-7d5ce680-f23c-11e8-9bed-069405ec2ca8.png)

**Comment by nicolargo** [comment]
Please can you run Glances in debug mode (-d) and paste/bin us the log file ?

**Comment by recteurlp** [comment]
No relevant error in debug mode the plugin return [] (empty list)


```bash
cd /usr/lib/python3.7/site-packages/glances/plugins
```

Maybe something like :

```python
❯ python3                                                                                                                                                                                                                                               13:43
Python 3.7.1 (default, Nov 23 2018, 10:01:49)
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import glances_diskio
>>> test = glances_diskio.Plugin()
>>> test.update()
[]
>>> import psutil
>>> psutil.disk_io_counters(perdisk=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/site-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/usr/lib64/python3.7/site-packages/psutil/_pslinux.py", line 1076, in disk_io_counters
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 4832711 727751429 5872878716 2716439908 19052 64878 621556 852405 0 26993828 2717175220 0 0 0 0\n'
```

with glances_diskio.py line 73
```python
try:
    diskiocounters = psutil.disk_io_counters(perdisk=True)
except Exception:
    return stats
```

A psutil bug ? (5.4.8)

**Comment by nicolargo** [comment]
Perhaps related https://github.com/giampaolo/psutil/issues/1354

**Comment by recteurlp** [comment]
Thanks applying the patch manually did the trick.
Definitely need a new psutil version or a beta for 4.18+ kernel.
Thank you for your time and this great tool :+1: 

@scurrvy2020 What kernel version do you use ?

**Comment by stephdl** [comment]
thank so much, I fixed it on fedora30 but the issue was existing since some time

`sudo pip install --upgrade psutil`

after that the disk IO is well displayed

**Comment by Twofyw** [comment]
This problem appears again on `Linux 5.5.1-arch1-1`. I'm using `Glances v3.1.3 with psutil v5.7.0`. I've opened a issue at psutil (https://github.com/giampaolo/psutil/issues/1680)

> No relevant error in debug mode the plugin return [] (empty list)
> 
> ```shell
> cd /usr/lib/python3.7/site-packages/glances/plugins
> ```
> 
> Maybe something like :
> 
> ```python
> ❯ python3                                                                                                                                                                                                                                               13:43
> Python 3.7.1 (default, Nov 23 2018, 10:01:49)
> [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import glances_diskio
> >>> test = glances_diskio.Plugin()
> >>> test.update()
> []
> >>> import psutil
> >>> psutil.disk_io_counters(perdisk=True)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib64/python3.7/site-packages/psutil/__init__.py", line 2014, in disk_io_counters
>     rawdict = _psplatform.disk_io_counters()
>   File "/usr/lib64/python3.7/site-packages/psutil/_pslinux.py", line 1076, in disk_io_counters
>     raise ValueError("not sure how to interpret line %r" % line)
> ValueError: not sure how to interpret line '   8       0 sda 4832711 727751429 5872878716 2716439908 19052 64878 621556 852405 0 26993828 2717175220 0 0 0 0\n'
> ```
> 
> with glances_diskio.py line 73
> 
> ```python
> try:
>     diskiocounters = psutil.disk_io_counters(perdisk=True)
> except Exception:
>     return stats
> ```
> 
> A psutil bug ? (5.4.8)

**Comment by stephdl** [comment]
I am back, disk IO doesn't work anymore on fedora31

```
Requirement already up-to-date: glances in /usr/local/lib/python3.7/site-packages (3.1.4.1)
Requirement already satisfied, skipping upgrade: psutil>=5.3.0 in /usr/local/lib64/python3.7/site-packages (from glances) (5.7.0)
Requirement already satisfied, skipping upgrade: future in /usr/local/lib/python3.7/site-packages (from glances) (0.18.2)
```
some ideas ?

**Comment by CMSplumbear** [comment]
Hello,
Kernel 5.5 requires psutil 5.7.0, see #1665 https://github.com/giampaolo/psutil/pull/1665

https://github.com/giampaolo/psutil/commit/2e0952e939d6ab517449314876d8d3488ba5b98b#diff-befef210ffc1d19a84ee5969886021a3

**Comment by stephdl** [comment]
I think it is satisfied : on Fedora 31

```
╰─➤  rpm -qa kernel       
kernel-5.6.11-200.fc31.x86_64
kernel-5.6.7-200.fc31.x86_64
kernel-5.6.8-200.fc31.x86_64
╰─➤  sudo pip install --upgrade psutil
Requirement already up-to-date: psutil in /usr/local/lib64/python3.7/site-packages (5.7.0)
```
