### ISSUE TITLE
Action on port/web and folders plugins is not working

### ISSUE THREAD

**Issue by stenwt** [nicolargo/glances#1358]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Documentation for port + web checks do not list the syntax for running an action when a check fails. I've tried several permutations (web_N_status_critical_action, web_N_critical_action, web_N_timeout_critical_action....), nothing seems to match up. I see [the alerts are being sent](https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_ports.py#L113) just don't understand how to add an action to them. 

#### Versions

Glances v3.1.0_beta with psutil v5.4.3
Fedora 29

**Comment by nicolargo** [comment]
Hi @stenwt ,

for the moment, it is not possible to run action with the port/web plugins. There is an issue on the plugin. I will have a look as soon as possible.

Thanks for the issue report.

Nicolas

**Comment by nicolargo** [comment]
Corrected on the latest commit.

Please test the DEVELOP branch.

Examples for folder:

```
[folders]
# Define a folder list to monitor
# The list is composed of items (list_#nb <= 10)
# An item is defined by:
# * path: absolute path
# * careful: optional careful threshold (in MB)
# * warning: optional warning threshold (in MB)
# * critical: optional critical threshold (in MB)
folder_1_path=/tmp
folder_1_careful=2500
folder_1_warning=3000
folder_1_critical=3500
folder_2_path=/home/nicolargo/Videos
folder_2_warning=1000
folder_2_critical=2000
folder_2_critical_action=echo "TOTO" > /tmp/test_folder.txt
```

and for ports:

```
[ports]
# Ports scanner plugin configuration
# Interval in second between two scans
refresh=30
# Set the default timeout (in second) for a scan (can be overwritten in the scan list)
timeout=3
# If port_default_gateway is True, add the default gateway on top of the scan list
port_default_gateway=True
#
# Define the scan list (1 < x < 255)
# port_x_host (name or IP) is mandatory
# port_x_port (TCP port number) is optional (if not set, use ICMP)
# port_x_description is optional (if not set, define to host:port)
# port_x_timeout is optional and overwrite the default timeout value
# port_x_rtt_warning is optional and defines the warning threshold in ms
#
port_1_host=www.google.com
port_1_port=80
port_1_description=Google site
port_1_timeout=1
port_1_rtt_warning=40
port_1_rtt_warning_action=echo tit
```
