### ISSUE TITLE
when does it come to iOS? do you want a dev to make an iOS app?

### ISSUE THREAD

**Issue by tcpaul** [nicolargo/glances#1359]
Hi I see there is an android version of this, im wondering if there is an iOS version, if not I could start working on that kthx

**Comment by nicolargo** [comment]
Yes, it will be nice but i think that PsUtil (the main lib used to grab system stats) is not available on IOS smarthphone...

**Comment by RazCrimson** [comment]
PsUtil support for IOS: https://github.com/giampaolo/psutil/issues/1520
