### ISSUE TITLE
Support for monochrome (serial) terminals e.g. vt220

### ISSUE THREAD

**Issue by Chaz6** [nicolargo/glances#1362]
When trying to run glances on a terminal via serial (e.g. vt220) it gives the following error:-
```
_curses.error: use_default_colors() returned ERR
```
It would be nice to fallback to monochrome. Example situations: using a terminal multiplexer, or on a vps provider that provides a virtual terminal connection.

**Comment by nicolargo** [comment]
Hi @Chaz6 

i just publish a patch on the DEVELOP branch.

I tested it with a Jagacy VT 220 terminal emulator but i am not sure that it is monochrome.

![jagacy vt - swingvt_009](https://user-images.githubusercontent.com/776747/49684426-2bd21880-fad4-11e8-80d4-677656807b81.jpg)

Can you please test this patch on your VT220 monochrome configuration ?

**Comment by Chaz6** [comment]
Thank you for this, I am sorry I did not get back sooner, I had an overflow of github notifications and I am learning to manage them better.
