### ISSUE TITLE
Feature request: support path prefix so we can watch glances via url like http://ip/urlprefix/

### ISSUE THREAD

**Issue by cailiang9** [nicolargo/glances#1365]
Feature request: support path prefix so we can watch glances via url like http://ip/urlprefix/ . it's useful for very restricted environment(some companies only allow one port on server).
I implemented by adding an outer bottle server, though it's not very elegant:
```
    def start(self, stats):
        """Start the bottle."""
        ...
        mainapp = Bottle()                # add an outer bottle class
        mainapp.mount('/glances/', self._app)
        mainapp.run(host=self.args.bind_address,
                      port=self.args.port,
                      quiet=not self.args.debug)
```

**Comment by chuong98** [comment]
This feature is very important. @nicolargo  has it been supported yet?? Thank you.

**Comment by nicolargo** [comment]
Implementation done on the develop branch.

Extract of the updated documentation:

**API URL**

The default root API URL is http://localhost:61208/api/3.

The bind address and port could be changed using the --bind and --port command line options.

It is also possible to define an URL prefix using the url_prefix option from the [outputs] section of the Glances configuration file. The url_prefix should always end with a slash (/).

For example:

will change the root API URL to http://localhost:61208/glances/api/3 and the Web UI URL to http://localhost:61208/glances/

**Comment by nicolargo** [comment]
To be tested on your side from the develop branch.

**Comment by chuong98** [comment]
Thabks you.  It works great
