### ISSUE TITLE
MacOS Mojave ModuleNotFoundError:

### ISSUE THREAD

**Issue by RyuuzakiJulio** [nicolargo/glances#1367]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Installed Python, pip, home-brew, etc, psutil.
Installed glances with brew

No matter what I do I get a Module Not Found Error "pkg_resources"

#### Versions

* Glances & psutil (glances -V):
glances -V will throw the same error, missing pkg_resources module.

* Operating System (lsb_release -a):
This command don't work on MacOS terminal.
I'm on MacOS Mojave 10.14.02
Using the system Terminal 2.9.1 (421.1)

#### Logs

$glances
Traceback (most recent call last):
  File "/usr/local/Cellar/glances/3.0.2/libexec/bin/glances", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by nicolargo** [comment]
pkg_resources is provided by the setuptools Python lib...

Try this: 

```
pip3 install --upgrade pip setuptools
```

or (pip2 if you uses Python 2).

**Comment by RyuuzakiJulio** [comment]
That did the trick! Damn there is so much to learn. I love glances. Looks so sexy. Thank you!!

**Comment by RazCrimson** [comment]
Closing stale issue.
