### ISSUE TITLE
Prohibit some plug-in data from being exported to influxdb

### ISSUE THREAD

**Issue by leavesbnw** [nicolargo/glances#1368]
When I run command:   glances --queit --disable-plugin docker  --export influxdb
I hope docker data won't be stored in influxdb。
I saw the source, and found a solution:  vim  glances/exports/glances_export.py
modify method below:
```
def  plugin_to_export(self):
     """Return the list of plugins to export."""
    plugins = ['cpu','percpu','load','mem','memswap','network','diskio','fs','processcount','ip','system','uptime','sensors','docker','gpu']
    for plg in plugins:
        if getattr(self.args, 'disable_' + plg):
            plugins.remove(plg)
    return plugins
```

Please give some suggestions.

**Comment by nicolargo** [comment]
Hi @leavesbnw, thnaks for the report !

Corrected in patch c76a5f05 (on the DEVELOP branch). Will be release in Glances 3.1.
