### ISSUE TITLE
Missing kernel task names when the webui is switched to long process names.

### ISSUE THREAD

**Issue by grheard** [nicolargo/glances#1371]
#### Description

When the webui is switched to show the long process names, the names of the kernel processes disappear.

In general the process list doesn't look the same between the cli interface and the webui.

#### Versions

* Glances & psutil (glances -V):

Glances v3.0.2 with psutil v5.4.8

* Operating System (lsb_release -a):

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch

**Comment by grheard** [comment]
Here is an example.

Long process names.
![screenshot from 2018-12-17 14-45-50](https://user-images.githubusercontent.com/11306237/50111374-a56fb200-020a-11e9-9904-bd144ed8f125.png)

Short process names.
![screenshot from 2018-12-17 14-45-35](https://user-images.githubusercontent.com/11306237/50111375-a56fb200-020a-11e9-97bf-f60052490ad1.png)

**Comment by nicolargo** [comment]
@notFloran Can you have a look on this issue ?

Thanks !

**Comment by nicolargo** [comment]
@notFloran Any news ?

**Comment by grheard** [comment]
Updated to 3.1.0 this morning and this does not appear to be fixed.

Here's a little gif showing the version of glances and switching into/out of the long process names.

![peek 2019-01-21 11-27](https://user-images.githubusercontent.com/11306237/51486942-004b7a80-1d70-11e9-9db0-27c07bec298a.gif)

**Comment by nicolargo** [comment]
@grheard Did you clear your browser cache ? (CTRL-F5)

**Comment by grheard** [comment]
I've tried the CTRL-F5, I've tried clearing the entire browser cache, and I've tried a different browser (firefox as opposed to chrome).
