### ISSUE TITLE
Standard output misbehaviour (need to flush)

### ISSUE THREAD

**Issue by roomcays** [nicolargo/glances#1376]
#### Description

I'm trying to marry glances with [lemonbar](https://github.com/LemonBoy/bar) using `--stdout` argument. While *echoing* some strings from bash scripts works well, glances keep silent. This is really weird as `glances --stdout` work well when redirecting output to file. I do not know where is the problem, it seems that either glances or lemonbar treat standard output differently (some encoding? line endings?).

However, I've done some simple testing using named pipies:

```
mkfifo /tmp/tmp_fifo
echo "foo" > /tmp/tmp_fifo; sleep 1; echo "bar" > /tmp/tmp_fifo; sleep 1; echo "baz" > /tmp/tmp_fifo
```
makes `foo` appear in the `/tmp/tmp_fifo` file first, then one second passes, then `bar` appears, then `baz`:

```
foo
(1 second)
bar
(1 second)
baz
```

Then while using glances:

```
mkfifo /tmp/tmp_fifo
glances --stdout cpu.user > /tmp/tmp_fifo
```

does not display anything in the `/tmp/tmp_fifo` file until glances quit (`CTRL+C`). Aftert quitting glances all generated lines of it's output are instantly passed to the `/tmp/tmp_fifo`:

```
(nothing...)
(still nothing...)
[CTRL+C] pressed
cpu.user: 18.4
cpu.user: 1.8
cpu.user: 1.6
cpu.user: 1.4
```

Is it possible, that glances are not terminating the output for every loop/iteration?

#### Versions

* Glances v3.0.2 with psutil v5.4.0
* Gentoo Base System release 2.6

**Comment by nicolargo** [comment]
You are right, Glances do not flush stdout.

I just publish a patch on the DEVELOP branch to correct this behavior on stdout and stdout-csv.

Can you test it ?
