### ISSUE TITLE
Disable plugin from Glances configuration file

### ISSUE THREAD

**Issue by geeseven** [nicolargo/glances#1378]
#### Description

I have used glances for some time, but I have just started getting into customizing it.  It would appear that there is not away to disable a plugin via the glances.config file. In my case, I am looking to disable the alert plugin.  It is possible with cli flags, ```glances --disable-plugin=alert``` or for older versions ```glances --disable-alert```.  Is there a way to disable it in glances.config?

#### Versions

I do not think versioning information is needed.  Here is what I have tested on so far.

Arch:
```
$ glances -V
Glances v3.0.2 with psutil v5.4.8
```

Freebsd 12.0 with py36-glances:
```
$ glances -V
Glances v2.11.1 with psutil v5.4.7
```
#### Logs

n/a

Also, it appears that there are some options that can only be set in glances.config and other can only be done via cli options.  It would be nice for (most) all options to be set either way.

**Comment by nicolargo** [comment]
Done in the latest commit on the DEVELOP branch.

Will be release in Glances 3.1.

Thanks for the enhancement request @geeseven !

**Comment by geeseven** [comment]
@nicolargo, thanks for the timely update.  :+1:
