### ISSUE TITLE
Error in install.sh on CentOS 7

### ISSUE THREAD

**Issue by StuxForce** [nicolargo/glances#1379]
#### Description
When I run https://raw.githubusercontent.com/nicolargo/glancesautoinstall/master/install.sh I'm getting output:

> Detected system: centos
> /bin/bash: line 59: conditional binary operator expected
> /bin/bash: line 59: syntax error near `$distrib_name'
> /bin/bash: line 59: `elif [[ $distrib_name == "redhat" || $distrib_name == "centos" || [[ $distrib_name == "fedora" ]] || $distrib_name == "Scientific" ]]; then'

After deleting "[[" and "]]" near || [[ $distrib_name == "fedora" ]] || installation is continue

Also there is no packages in default CentOS repo:

> Detected system: centos
> Loaded plugins: fastestmirror
> Determining fastest mirrors
>  * base: centos-mirror.rbc.ru
>  * extras: mirror.reconn.ru
>  * updates: centos-mirror.rbc.ru
> base                                                                                                                                  | 3.6 kB  00:00:00
> extras                                                                                                                                | 3.4 kB  00:00:00
> updates                                                                                                                               | 3.4 kB  00:00:00
> (1/4): base/7/x86_64/group_gz                                                                                                         | 166 kB  00:00:00
> (2/4): extras/7/x86_64/primary_db                                                                                                     | 156 kB  00:00:01
> (3/4): updates/7/x86_64/primary_db                                                                                                    | 1.3 MB  00:00:02
> (4/4): base/7/x86_64/primary_db                                                                                                       | 6.0 MB  00:00:03
> No package python-pip available.
> No package wireless-tools available.
> Resolving Dependencies
>...

#### Versions
* Operating System (CentOS Linux release 7.5.1804 (Core)):

**Comment by nicolargo** [comment]
Solved 1 minute ago... ;)
