### ISSUE TITLE
Documentation is unclear how to get Docker information

### ISSUE THREAD

**Issue by nedbat** [nicolargo/glances#1386]
The [docs section on Docker](https://glances.readthedocs.io/en/latest/aoa/docker.html) says:

> If you use Docker, Glances can help you to monitor your containers. Glances uses the Docker API through the docker-py library.

There are two problems here: First, it doesn't make clear that the docker-py library is not installed by defaut, and to get Docker information you have to install it yourself.  Second, "pip install docker-py" will install a library, but not the right library (as I found out from a [glances issue](https://github.com/docker/docker-py/issues/1796#issuecomment-342569508)).

Could the docs be more explicit about how to get Docker support?  I suggest:
```
If you would like Docker information displayed, you must install an optional Python dependency::

    $ pip install docker
```

BTW: [a comment in glances_docker.py](https://github.com/nicolargo/glances/blob/6d1c0ccce0e45a43d919747e02c79acf466af52f/glances/plugins/glances_docker.py#L32) seems to suggest that it will only work on Linux, but it works fine on Mac.

**Comment by nedbat** [comment]
FWIW, even nicer would be to define a setup.py "extras" so that we could install like this: 
```
$ pip install glances[docker]
```
to get the Docker support installed when we install glances.  I can make a pull request for this if you like.

**Comment by nicolargo** [comment]
The extras docker dep in the setup.py file is already done.

I will improve  the Docker plugin doc.

Thanks !

**Comment by milonite** [comment]
I've installed glances[docker] but still I dont see the conteiners in the UI. Do you have any idea?

**Comment by TheRealMaN** [comment]
> I've installed glances[docker] but still I dont see the conteiners in the UI. Do you have any idea?

Did you do:
`pip install docker`
