### ISSUE TITLE
MQTT: '<=' not supported between instances of 'str' and 'int' 

### ISSUE THREAD

**Issue by frenck** [nicolargo/glances#1392]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

As soon as I enable MQTT on a Docker based system, the following happens:

`'<=' not supported between instances of 'str' and 'int' `

Seems similar to #1315 

Reproduction: Simply set up MQTT on a Docker-based system.

#### Versions

* Glances & psutil (glances -V): `Glances v3.0.2 with psutil v5.4.6`
* Operating System (lsb_release -a): Alpine 3.8

#### Logs

```txt
Connection to MQTT server failed : '<=' not supported between instances of 'str' and 'int' 
```

**Comment by frenck** [comment]
How do I do that? This is the only thing it reports at this moment...

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/51084570-7f1b3480-172c-11e9-9552-69023f3d828a.png)


![image](https://user-images.githubusercontent.com/195327/51084575-8cd0ba00-172c-11e9-8b1d-2b3d70e71d1c.png)

**Comment by frenck** [comment]
Could be, since 3.1.0 is now released, I will go ahead and try that one out. 
Will update this issue with the results.

**Comment by molobrakos** [comment]
Maybe we just miss a cast to int here: https://github.com/nicolargo/glances/blob/develop/glances/exports/glances_mqtt.py#L56

**Comment by arturol76** [comment]
Hi,
I solved changing "glances_mqtt.py" as follows:
self.port = int(self.port) or 8883

...and by disabling this:
#client.tls_set(certs.where())
