### ISSUE TITLE
Fan speed and voltages section?

### ISSUE THREAD

**Issue by UmbralSamurai** [nicolargo/glances#1398]
#### Description

For an enhancement or new feature: Describe your needs:

First time poster, LONG LONG time user... (back under python2... God, it's been that long!)

I've scoured the docs, and pretty much every resource that I can find, but I can't find a way to actually display the fan speeds that are being reported under sensors. Sensors displays them completely, however, I can't find a way (and there might not be one?) to actually see them. Not sure if it would have to be added.  I do know that, at least for me, seeing voltages would be useful as well, at least to me.  It's not something that I've seen addressed or asked for before.  

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.0 with psutil v5.4.8

* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch

**Comment by nicolargo** [comment]
Hi @UmbralSamurai 

The fan stats has been disable long time ago because of an issue on Ubuntu system https://github.com/giampaolo/psutil/issues/1199

It is now solved in latest Ubuntu version.

I will include the fan speed stat in the next release.

Nicolas

**Comment by UmbralSamurai** [comment]
I remember the issue in Ubuntu, but I didn't think that it affected
Debian.  And I appreciate it being included again.

**Comment by wordlessly** [comment]
psutil.sensors_fans() does not increase CPU usage for me. Still, there is also no output for the fan speed. I have a Intel NUC8i5BEH. Maybe there is no sensor for the fan speed?

**Comment by Strykar** [comment]
`Glances v3.1.0 with psutil v5.6.3`
Enabling the fans does not increase CPU load for me.
How do we enable voltage monitoring?

**Comment by kamilmirza** [comment]
`Glances v3.1.0 with psutil v5.4.2`
Enabling the fans does not increase CPU load for me either

**Comment by nicolargo** [comment]
Ok, thanks for the head up. 
Fan is (re)enable in Glances 3.1.1 RC2.

Please test the develop branch on your system.
