### ISSUE TITLE
Permission denied: '/etc/glances/glances.conf'

### ISSUE THREAD

**Issue by tdeckers** [nicolargo/glances#1403]
#### Description

Steps:
1. Create /etc/glances/glances.conf, add any configuration.
2. Start glances from the command line without any options.

```
$ glances
Warning: Unable to set locale. Expect encoding problems.
Traceback (most recent call last):
  File "/snap/glances/5/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 126, in main
    core = GlancesMain()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/main.py", line 84, in __init__
    self.args = self.parse_args()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/main.py", line 274, in parse_args
    self.config = Config(args.conf_file)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/config.py", line 107, in __init__
    self.read()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/config.py", line 140, in read
    with open(config_file, encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/etc/glances/glances.conf'
```
Running with an explicit option for config file (`-C`) has the same effect.  Running with `sudo` doesn't help either.

I assume the file needs to be added as interface for the snap somehow?

#### Versions

* Glances & psutil (glances -V):
```
$ glances -V
Warning: Unable to set locale. Expect encoding problems.
Glances v2.11.1 with psutil v5.4.2
```
* Operating System (lsb_release -a):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

#### Logs

Additional logs, in /var/log/syslog:
```
Jan 23 10:18:44 lies kernel: [1030617.699217] audit: type=1400 audit(1548235124.182:1093): apparmor="DENIED" operation="open" profile="snap.glances.glances" name="/etc/glances/glances.conf" pid=21316 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by nicolargo** [comment]
Unfortunatly, it breaks the Snap buil: https://build.snapcraft.io/user/nicolargo/glances/440272

**Comment by Lin-Buo-Ren** [comment]
You may want to consider making the config file's path configurable via an environment variable, and set it to `$SNAP_USER_COMMON/glances.conf` in the Snapcraft recipe.

The `*-files` interface probably not yet supported by both Snapcraft & snapd.

**Comment by Lin-Buo-Ren** [comment]
> https://build.snapcraft.io/user/nicolargo/glances/440272

Note that this link is not public to non-snap publisher and collaborators

**Comment by Lin-Buo-Ren** [comment]
Quote from [The system-files interface - doc - snapcraft.io](https://forum.snapcraft.io/t/the-system-files-interface/9358):

> Requires snap version 2.37+. Consumers of this interface require a [snap declaration](https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455/) for distribution via the Snap Store.

You'll have to request an auto-connection to the `system-files` interface that binds with the `/etc/glances/glances.conf` path, and after it is granted, wait for the snapd distribution shipped in the `core` snap has the 2.37 release (`snap info core`), and finally start the transition of using the `system-files` interface.

**Comment by nicolargo** [comment]
@Lin-Buo-Ren i am not very familiar with Snap. I just add you as a collaborator on Snapcraft. Can you have a look for me ? Thanks !

**Comment by Lin-Buo-Ren** [comment]
>  ReRevert Permission denied: '/etc/glances/glances.conf' #1403 

Please keep the commit reverted as the feature is not in the stable release of snapd so it won't work even if it's gets pass the Snap Store automatic review process(a force-push might be preferable to keep the history clean).

I need your verbal authorization to request the usage of `system-files` interface in the Snapcraft Forum (a comment on this page will do).  Is this application has any user-wide config locations?  If so we might want to request using `personal-files` interface as well.

**Comment by Lin-Buo-Ren** [comment]
Also, you might want to make the application avoid from crashing when the system-wide config file isn't accessible.

**Comment by Lin-Buo-Ren** [comment]
As per the reviewer's inquiry, I would like to ask if the application would modify either the user and global config files?

**Comment by Lin-Buo-Ren** [comment]
> I need your verbal authorization to request the usage of the `personal-files` and the `system-files` interface in the Snapcraft Forum (a comment on this page will do). 

Re-ping.

Also as per the reviewer's request, please answer the following question:

> How does glances handle different versions of config files (going forward and backward)?
