### ISSUE TITLE
"sorted by ?" is displayed when setting the sort criterion to "USER"

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [nicolargo/glances#1407]
#### Description
1. Launch Glances 
2. Use left/right keys to change the sort criterion to "USER"

The "TASKS N (N thr), N run, N slp, N oth sorted by ?" line is printed instead of something like "sorted by username" etc.

#### Versions

* Glances & psutil (glances -V): I use the locally built snap from the development snapshot 62debf2, I currently have no idea the version of psutil
* Operating System (lsb_release -a): Ubuntu 18.04.1 LTS

#### Logs
http://paste.ubuntu.com/p/CQGDqWDj2K/

**Comment by nicolargo** [comment]
Ok corrected by the latest commit on the DEVELOP branch.

Thanks for the issue report @Lin-Buo-Ren !
