### ISSUE TITLE
Why I can't open  http://0.0.0.0:61208/ web page in web broswer?

### ISSUE THREAD

**Issue by colemanlee** [nicolargo/glances#1413]
#### Description
* For a issue: Why I can't open  http://0.0.0.0:61208/ web page in web broswer?

#### Versions
* Glances & psutil (glances -V):Glances v3.1.0 with psutil v5.5.0
* Operating System (lsb_release -a):Microsoft Windows 10 version 1803

#### Logs
C:\Users\Jeff> glances
Glances Web User Interface started on http://0.0.0.0:61209/
Then i copy *http://0.0.0.0:61209/* to web broswer and press Enter key, but the page can't be opened.

**Comment by notFloran** [comment]
@colemanlee Can you show us a screenshot of your browser web console (Ctrl-Maj-K with Firefox) ?

**Comment by colemanlee** [comment]
> @colemanlee Can you show us a screenshot of your browser web console (Ctrl-Maj-K with Firefox) ?

My OS Version: Microsoft Windows® 10 version1803
I saw your code READ.ME page said "windows failing", maybe i should not run it in windows.
Here is the web console page of Chrome, I have no Firefox installed.
![pic_0205234305](https://user-images.githubusercontent.com/10258421/52284659-cd27fe80-299f-11e9-82f3-07d54481ac4e.jpg)

![pic_0205234239](https://user-images.githubusercontent.com/10258421/52284660-cdc09500-299f-11e9-9421-3f466bedcb8f.jpg)

**Comment by notFloran** [comment]
Given the Chrome console message (ERR_ADDRESS_INVALID), the web browser can not reach the server.

Do you use a proxy or something similar?

**Comment by colemanlee** [comment]
> Given the Chrome console message (ERR_ADDRESS_INVALID), the web browser can not reach the server.
> 
> Do you use a proxy or something similar?

No, I don't use any proxy or something similar, but i run ```glances -w``` in windows in this issue, glances can't run in windows, so i should not run glances in windows.
I will close this issue, thank you.

**Comment by rjgrandy** [comment]
Was there ever resolution to this?  I performed the same actions and have the same results:

C:\> glances
Glances Web User Interface started on http://0.0.0.0:61209/
Then i copy http://0.0.0.0:61209/ to web broswer and press Enter key, but the page can't be opened.

Just want to know what I am doing wrong. I even tried to -B to the local IP address but still not luck

**Comment by philiporlando** [comment]
I was able to get this working on a Windows machine by changing the `http://0.0.0.0:61209` to `http://localhost:61209`. Let me know if that's working for you!

**Comment by jasonisgod** [comment]
> I was able to get this working on a Windows machine by changing the `http://0.0.0.0:61209` to `http://localhost:61209`. Let me know if that's working for you!

thanks its working
