### ISSUE TITLE
[DOCKER]Cannot get FILE SYS info for non-boot drive

### ISSUE THREAD

**Issue by bfiset** [nicolargo/glances#1414]
#### Description

Running Glances' official Docker container.

I have 5 volumes mounted on my host system.

- /dev/sda1
- /dev/sdb1
- /dev/sdc1
- /dev/sdd1
- /dev/sde1 (is boot drive)

I can only get FILE SYS info for /dev/sde1

#### Versions

* Glances & psutil (glances -V):
Using latest container: Glances v3.1.1b0 with psutil v5.4.8
* Operating System (lsb_release -a):
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

#### Note

Running Glances directly on Host does work as intended. It leads me to believe the issue lies in exposing all the volumes to the docker container.

**Comment by nicolargo** [comment]
Hi !

What is the command line used to run the Docker container ?

Try to add the following option: --device=/dev/sda

Nicolas

**Comment by bfiset** [comment]
It does expose the devices inside the container so it's a step in the right direction!

Sadly, it will not mount them so my guess is psutil will not list unmounted file systems.

I am running latest-alpine image as it is more lightweight than the regular image.
