### ISSUE TITLE
IP plugin displays incorrect subnet mask

### ISSUE THREAD

**Issue by jpsutton** [nicolargo/glances#1417]
#### Description
When I start glances, the IP plugin displays my local IP and my public IP at the top of the display.  Unforunately, on the local IP the network mask seems to be showing a /24 rather than my configured /23 network mask.  I verified my NetworkManager config is set to /23 and ifconfig confirms it is set to /23 correctly.

#### Versions
* Glances & psutil (glances -V):
** Glances v3.1.0 with psutil v5.5.0

* Operating System (lsb_release -a): 
** LSB Version:    1.4
** Distributor ID: Arch
** Description:    Arch Linux
** Release:        rolling
** Codename:       n/a

**Comment by foot-gloves** [comment]
I see the same behavior. I have a /22 network and glances on my machine shows /24.

**Comment by foot-gloves** [comment]
it looks like netifaces library is being used to grab the info. I dug around in the library and did some tests and netifaces is returning the correct information for netmask on my affected systems. Maybe the section in glances_ip.py plugin which converts it to cidr is not working or grabbing the wrong ip to convert. However I don't have any /24 networks connected to my machines.

line 150
`return sum([int(x) << 8 for x in ip.split('.')]) // 8128`

I added netaddr and IPAddress library to the plugin and also modified the conversion to use IPAddress

added at line 33:
`from netaddr import IPAddress`

at line 150:
`return IPAddress(ip).netmask_bits()`

so far it looks good but im gonna test it on my other machines before

**Comment by nicolargo** [comment]
Can you open an issue o the Netifaces Github... 

If it is not corrected in the next Glances version, i will hide it. Do not want to show a wrong information...

**Comment by Atticfire** [comment]
If you don't want to import IPAddress then make the following change to glances_ip.py

line 150
return sum([int(x) << 8 for x in ip.split('.')]) // 8128

Change to 
return sum(bin(int(x)).count('1') for x in ip.split('.'))

That will give a correct CIDR on my Linux system

>>> range = ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.128',  '255.255.255.192', '255.255.255.224', '255.255.255.240',  '255.255.255.248',  '255.255.255.252',  '255.255.255.255']
>>> for ip in range:
...  sum(bin(int(x)).count('1') for x in ip.split('.'))
8
16
24
25
26
27
28
29
30
32

**Comment by nicolargo** [comment]
Done !

Thanks @Atticfire
