### ISSUE TITLE
Readable API JSON

### ISSUE THREAD

**Issue by gotjoshua** [nicolargo/glances#1418]
I would love if the [API Docs JSON examples](https://github.com/nicolargo/glances/wiki/The-Glances-XML-RPC-API-How-to/212c9b96f440250bdbe80c5b380d9caecb460fcc) were a bit more readable.
I thought about cloning and making a PR, but maybe it isn't worth the trouble, if you agree you could just run the json through something like:
https://jsonformatter.curiousconcept.com/
and drop it into a code block formatted.

I'm happy to clone and make a PR if you agree and prefer...

**Comment by douglasg14b** [comment]
It would be helpful to link to different docs that have the ugly JSON...

**Comment by gotjoshua** [comment]
good call @douglasg14b ... i edited the original, so we can actually delete these comments to keep the thread clean...

**Comment by douglasg14b** [comment]
No need to delete comments, it's all relevant. Also that is some pretty ugly json (not valid either as a copy/paste).

My recommendation is to prettify it, syntax highlight it, and then hide it under an accordion:

<details>
 <summary>Some JSON</summary>

```json
[
  {
    "tx": 750,
    "cumulative_rx": 164699607,
    "rx": 750,
    "cumulative_cx": 329399214,
    "time_since_update": 1,
    "cx": 1500,
    "cumulative_tx": 164699607,
    "interface_name": "lo"
  },
  {
    "tx": 0,
    "cumulative_rx": 5180644,
    "rx": 0,
    "cumulative_cx": 231328829,
    "time_since_update": 1,
    "cx": 0,
    "cumulative_tx": 226148185,
    "interface_name": "docker0"
  },
  {
    "tx": 398,
    "cumulative_rx": 6813463626,
    "rx": 245,
    "cumulative_cx": 10184194830,
    "time_since_update": 1,
    "cx": 643,
    "cumulative_tx": 3370731204,
    "interface_name": "wlan0"
  }
]
```
</details>

**Comment by nicolargo** [comment]
@gotjoshua It will be nice if you can do it through a PR.

**Comment by gotjoshua** [comment]
Sorry for the huge delay... Finally  made time to prepare the PR.

This is how far I got: https://github.com/gotjoshua/glances/wiki/The-Glances-XML-RPC-API-How-to

But I don't know what to do with the weird syntax (what's with the `u'` ? ?):
`{u'load': {u'cpucore':...`
should i reformat that to:
`{"load": {"cpucore":...`
?

**Comment by nicolargo** [comment]
Nice work!

The u is for Unicode. A specific Python notation. You can remove it from
the doc.

**Comment by gotjoshua** [comment]
So the [GitHub wiki doesn't seem to support pull requests](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github), but you can consider this comment a formal and official "copy-paste Pull Request" for the wiki page:
https://github.com/gotjoshua/glances/wiki/The-Glances-XML-RPC-API-How-to

Thanks for the guidance about the python notation and thanks for the amazingly useful Glances!

**Comment by gotjoshua** [comment]
wrapping them into accordion/collapse elements is a good idea @douglasg14b ... so thats also done in the latest [revision](https://github.com/gotjoshua/glances/wiki/The-Glances-XML-RPC-API-How-to/_history)

**Comment by RazCrimson** [comment]
Closing issue as this is resolved
