### ISSUE TITLE
Misleading image tag latest-arm

### ISSUE THREAD

**Issue by grewhit25** [nicolargo/glances#1419]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

The tag 'latest-arm' implies a 32bits architecture. I download this image to my Raspberry Pi 3B running Raspbian OS, it did not work for the reasons pointed here; that it's actually an arm64 or arm64v8 image.

Please can we have a multi arch image posted to Docker Hub that will work on different architectures including armhf, arm32v7, arm32v6 family.

Please also update your tag to reflect the architecture, for example latest-arm64.

In the meantime here is the Dockerfile I use to build the latest Glances release for my Raspberry Pi. It's an Alpine Linux variant (which itself is multi arch) and should build on any supported platform.

``` yml
# Glances Dockerfile based on Alpine OS
# https://github.com/nicolargo/glances

# Pull base image.
FROM alpine
# Install Glances
RUN apk add -U --no-cache --virtual \
    build-dependencies \
    build-base bash curl && \
    curl -L https://bit.ly/glances | /bin/bash && \
    apk del build-dependencies
# Define working directory.
WORKDIR /glances
# EXPOSE PORT (For XMLRPC)
EXPOSE 61209
# EXPOSE PORT (For Web UI)
EXPOSE 61208
# Define default command.
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
```

#### Versions

* Glances & psutil (glances -V):

After successful built image.

Glances v3.1.0 with psutil v5.5.0

* Operating System (lsb_release -a):

uname -a

Linux 1bd88fd02cd2 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l Linux

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

Glances Web User Interface started on http://0.0.0.0:61208/

**Comment by kolewu** [comment]
The image tagged `arm-latest` is **not** *arm* (neither `arm32` nor `arm64`), it's `x86_64`because it's build on docker hub and only x86_64 images can be built there. You can test it with this command on a x86_64 linux computer:

```bash
docker run --rm nicolargo/glances:latest-arm /bin/uname -m
```

It is possible to cross compile on docker hub for arm, but I have currently not enough experience to do this.

**Comment by medelay** [comment]
How would i get this to work in a docker container ?

**Comment by Overbryd** [comment]
This is the `Dockerfile` I use on my Raspberry Pi 4 on `arm64`:

```Dockerfile
FROM python:3.8-slim-buster

RUN apt-get update \
  && apt-get install -y \
    gcc \
    python3-dev 

ARG GLANCES_VERSION=3.1.5

RUN pip install \
      glances[web,ip,folders,docker,cpuinfo,action]==${GLANCES_VERSION}

WORKDIR /glances

# EXPOSE PORT (For XMLRPC)
EXPOSE 61209
# EXPOSE PORT (For Web UI)
EXPOSE 61208

# Define default command.
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
```

**Comment by BlackDark** [comment]
Maybe we could resolves multiple issues if we could go with multiarch builds.

Docker provides an experimental solution: https://docs.docker.com/buildx/working-with-buildx/

Currently trying it out with github actions (https://github.com/BlackDark/glances/blob/develop/.github/workflows/main.yml).
I will open a PR if i have an working solution.

Relates #1479, #1662
