### ISSUE TITLE
[WEB-UI] Glances-3.1.0: no Linux distribution name in the web GUI

### ISSUE THREAD

**Issue by spezialist1** [nicolargo/glances#1420]
#### Description

It looks like a bug: after the standard installation (from https://nicolargo.github.io/glances/) of the stable release Glances 3.1.0 with psutil 5.5.0 under CentOS-7.6, the Linux distribution name is not displayed in the web-GUI. Below is my screenshot where the top is the web-GUI, and the bottom is the usual ssh-console. It is clearly seen, that the Linux distribution name is present in the ssh-console:
![no_distro_name](https://user-images.githubusercontent.com/10425179/52559553-31165100-2dfe-11e9-9ea4-bcaabefddc10.png)

#### Versions

* Glances & psutil (glances -V): Glances v3.1.0 with psutil v5.5.0
* Operating System (lsb_release -a): CentOS Linux release 7.6.1810 (Core)

Very thanks for the support.

**Comment by nicolargo** [comment]
@notFloran Can you have a look ? i think that the distrib name is available in the API.
