### ISSUE TITLE
Tried glances in docker, glances container is running at 696% CPU....

### ISSUE THREAD

**Issue by GiganteX** [nicolargo/glances#1423]
I'm a total newbie at glances so I might be misinterpreting things, but this sure looks weird...
I just now started up glances in a container on my CoreOS VM running on XenServer,
and glances seem to be a total resource hog, overclocking my CPU to the extreme... :D

See attached picture.
![image](https://user-images.githubusercontent.com/15637533/52900956-4aa00a00-31fd-11e9-9ca8-07ea3d3f2e3a.png)

**Comment by nicolargo** [comment]
Strange...

Your global CPU is 26.9%. How many CPU core do you have on your Xen instance ?
Are you sure that the elastic_benz containers is the one hosting Glances ?

**Comment by GiganteX** [comment]
"Virtual CPUs: 4"
"Topology: 2 sockets with 2 cores per socket"

Yes, elastic_bens is the glances container, I double-checked it right now.

**Comment by zoredache** [comment]
I am seeing similar behavior.

[Imgur](https://i.imgur.com/F0henBg.png)

VM Host

    Windows Server 2016 Datacenter

Docker VM details (4 vCPU's assigned and 8GB RAM)

    # lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 9.8 (stretch)
    Release:	9.8
    Codename:	stretch

    # docker --version
    Docker version 18.09.4, build d14af54

    # docker image ls nicolargo/glances
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    nicolargo/glances   latest              e11d9ef79840        2 months ago        618MB

    # # Container start 
    # docker run --rm --name glances -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances

**Comment by gk7279** [comment]
Me too. When I am running glances with docker along with other containers, I see it at 8-10% when I am viewing via the web. But on certain machines where docker+glances is the only container, I see it at 300% CPU whereas the global CPU stats shows under 2%. What is this strange behavior? Please advice.
