### ISSUE TITLE
How to configure showing command name without path in process list

### ISSUE THREAD

**Issue by Mellbourn** [nicolargo/glances#1424]
I would like to configure glances to always show the short process name (without the path) in the processes list.

On a Mac the folder path is often so long that the actual command name is not visible. Even when the path is shorter than that, it is hard to quickly see the process name.

I know about the `/` command, and it does what I want, but I don't want to have to issue it every time I start glances. 

Is there a way to configure this that I have missed? If not, then this is a feature request.

#### Versions

* Glances & psutil (glances -V): Glances v3.0.2 with psutil v5.4.8
* Operating System (lsb_release -a): Mac OS X 10.14.3

**Comment by nicolargo** [comment]
Have you try: --process-short-name ?

==> https://glances.readthedocs.io/en/stable/cmds.html#cmdoption-process-short-name

**Comment by Mellbourn** [comment]
Yeah, I guess I can create an alias so I always get this flag. Would still be nice if it could be configured in the config file.
