### ISSUE TITLE
Using glances programatically

### ISSUE THREAD

**Issue by Mustafa-C** [nicolargo/glances#1426]
Is there any way to use glances as a module (such as import glances)? 
This is in order to get usage information per process. I see glances is using the psutil library, however when using that directly long blockages are present due to having to set interval=1 or higher to get reasonable numbers (otherwise you just get 0.0 for everything) but this means every process takes 1 second which can take minutes to go through every running process but glances does this very quickly.

**Comment by nicolargo** [comment]
Yes you can but there is no documentation about this because Glances is not a Python module...

You can have a look in https://github.com/nicolargo/glances/blob/develop/unitest.py
