### ISSUE TITLE
DIsk I/O - hide partition or disk of single partition drive

### ISSUE THREAD

**Issue by ArielRosenfeld** [nicolargo/glances#1429]
#### Description
DIsk I/O - hide partition or disk of single partition drive
if you have drives with a single partition you get to see the same i/o twice for example as sdd and sdd1
its just the same information twice showing just one of them is enough and if you have multiple drives it also pushes the FILE SYS plugin information down and some of it wont be visible

#### Versions
Glances v3.1.0 with psutil v5.5.0
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

**Comment by nicolargo** [comment]
You can use the hide option of the configuration file. For example, if you only want to display sdaX and not sda, use:

```
[diskio]
# Define the list of hidden disks (comma-separated regexp)
hide=loop.*,^sda$
```

Before:

![image](https://user-images.githubusercontent.com/776747/53832784-59214c00-3f87-11e9-8489-6ce9e6aefa1d.png)

After:

![image](https://user-images.githubusercontent.com/776747/53832742-3f800480-3f87-11e9-92d3-06052b5b2fca.png)

**Comment by ArielRosenfeld** [comment]
i actually prefer the inverse of only disks and not the partitions.

but more examples in the documentation would be welcome anyway

**Comment by fcalvet** [comment]
> i actually prefer the inverse of only disks and not the partitions.

For anyone looking for this, `^sd..$` did the trick for me
