### ISSUE TITLE
cannot read pygal import datetimeline

### ISSUE THREAD

**Issue by danny916** [nicolargo/glances#1433]
I have the following issue when running command 
'glances --export graph' 

I get the following error: 

file /usr/lib/python2.7/site-packages/Glances-3.1.1b0-py.2.7.egg/glances/exports/glances_graphy.py 
line 22 in <module>
from pygal import DateTimeLine
ImportError: cannot import name DateTimeLine

glances 3.1.1b0
psutil v5.4.3
RHEL 7.6 server

Thanks

**Comment by nicolargo** [comment]
Hi @danny916 

you need Pygal 2.0 or higher.

What is your Pygal version ?

I will add a minimal version number in the requirements file.

**Comment by danny916** [comment]
Thanks that helped.
