### ISSUE TITLE
docker glances container shows container's own network traffic

### ISSUE THREAD

**Issue by crusaderky** [nicolargo/glances#1435]
I'm using glances docker image, as documented in README.md:
```
docker pull nicolargo/glances
docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
```
The "NETWORK" section shows the network traffic (and interface names) of the docker container (eth0 lo), instead of the ones of the host running docker (docker0 enps20 lo).

**Comment by nicolargo** [comment]
You need to add the "insecure" following option to the command line:

```
--net=host --privileged
```

I will add a note on the documentation.
