### ISSUE TITLE
docker glances container doesn't map UIDs to user names

### ISSUE THREAD

**Issue by crusaderky** [nicolargo/glances#1436]
I'm using glances docker image, as documented in README.md:
```
docker pull nicolargo/glances
docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
```
The TASKS view correctly shows the processes running on the host running docker; however any user that is not root appears as a numeric UID instead of its user name.

**Comment by nicolargo** [comment]
Perhaps a solution here: https://docs.docker.com/engine/security/userns-remap/

**Comment by Ellpeck** [comment]
It seems like this hasn't been added to the Glances documentation even after 3.1.1. I'm having trouble making sense of the docker docs article you shared, so if you have any additional info, please let me know.
