### ISSUE TITLE
FR: Add docker dependency to docker images

### ISSUE THREAD

**Issue by tfonfara** [nicolargo/glances#1442]
It would be great if docker images would already contain docker dependency (`pip install docker`), as it's obvious that people are using docker in that case 😊

Thanks!

**Comment by tenitz** [comment]
I second that! I think all available dependencies should be baked into the Docker Images, as installing them manually and make them persistent is not a very elegant solution.

**Comment by RazCrimson** [comment]
Closing as we have different variants of docker images for this case now,
