### ISSUE TITLE
Limiting data exported for economic storage

### ISSUE THREAD

**Issue by LrrrAc** [nicolargo/glances#1443]
I am wondering if it would be possible to limit the data exported by glances in an effort to save storage space. I currently export to influxdb and it stores everything that glances sees and I dont use all of that data. I would like to prevent data sets that I dont use from being sent to influxdb.

**Comment by hcoohb** [comment]
I would also be interested in having a config option to select which plugins get exported.
Using MQTT export here..

**Comment by nicolargo** [comment]
You can disable a plugin using the --disable-plugin option from the command line (and from the Glances config file in the future 3.1.4 version):

Example to disable the cpu plugin:

```
python -m glances --export influxdb --disable-plugin cpu
```

**Comment by nicolargo** [comment]
As a future enhancement, it will be nice to have two options:

- --disable-plugin to completely disable the plugin
- --disable-plugin-export to only disable the plugin export task

**Comment by jorisvankessel** [comment]
@nicolargo wat a great tool have you made! 
Like @LrrrAc mentioned, I'm also very interested in an --export where you can define which tags you would like to publish.

It would be a nice feature when using `--export mqtt` for example which I use at this moment. 

Like this: 
`glances --export mqtt cpu.user,mem.used,load` 
(The functionality like --stdout)

**Comment by nicolargo** [comment]
Use --disable-plugin and --enable-plugin.

Example to only enable cpu and mem plugins for a CSV export:

    glances --export csv --export-csv-file /tmp/export.csv --disable-plugins all --enable-plugin cpu,mem --quiet
