### ISSUE TITLE
Kill a process from the Curses interface

### ISSUE THREAD

**Issue by daniel-vera-g** [nicolargo/glances#1444]
#### Description

I could not find the possibility to kill a process without exiting glances.

It would be nice to have a way to kill a process/processes within glances with the name or PID.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.0 with psutil v5.6.0
* Operating System (lsb_release -a): Ubuntu 16.04.6 LTS

**Comment by Dibbyo456** [comment]
**+1**

I have mostly used `htop` to view process and kill it.

**Comment by jdrch** [comment]
+1000 on this. I often have to `Esc` from `glances`, `# killall RogueProcess`, and then `# glances` again. Rather inconvenient.

**Comment by nicolargo** [comment]
First version implemented in the DEVELOP branch. 

Feature only available for standalone mode (not in the web UI and not in client/server mode).
