### ISSUE TITLE
Should warn about homebrew installation

### ISSUE THREAD

**Issue by KenanSulayman** [nicolargo/glances#1448]
The “Glances Auto Install script” as listed on the website should _not_ install Homebrew without explicit warning and the website should explicitly mention that the automated installation will try install Homebrew on the host system.

I deeply abhor Homebrew and would have loved to be given a choice, and even better, had glances use my existing MacPorts installation.

Thanks

**Comment by nicolargo** [comment]
Cloned here: https://github.com/nicolargo/glancesautoinstall/issues/31
