### ISSUE TITLE
Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string

### ISSUE THREAD

**Issue by arturol76** [nicolargo/glances#1450]
#### Description
I get the error "Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string" when trying to enable MQTT.
I'm using the docker image "docker.io/nicolargo/glances".

Here are the steps:

glances.conf:
[mqtt]
host=192.168.2.96
port=1883
user=xxx
password=xxxx
topic=glances

then i run the docker with the following option:
-e GLANCES_OPT="--export mqtt"

#### Versions

Glances:
docker.io/nicolargo/glances 

Operating System:
Linux 4.19.25-coreos 64bit

#### Logs
Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "glances/standalone.py", line 93, in __init__
    self.screen = GlancesCursesStandalone(config=config, args=args)
  File "glances/outputs/glances_curses.py", line 119, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal

**Comment by arturol76** [comment]
Hi,
I solved that as follows:

**1st step**: I upgraded from python 2.7 to python 3
**result**: the error changed from:

_"Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string"_ 

to:

  _"'<=' not supported between instances of 'str' and 'int'"_


**2nd step:** I edited "glances_mqtt.py" to covert "port" to int as follows:
self.port = int(self.port) or 8883

**3rd step**: i disabled TLS (which I do not use) as follows:
#client.tls_set(certs.where())

It works!!!

**Comment by nicolargo** [comment]
Thanks for the report.

Corrected by the latest commit on the DEVELOP branch (see commit 96bfd95e).

I also add a new tls key (tls=true by default) to disable TLS from the configuration file (tls=false).

**Comment by juan11perez** [comment]
please update docker image. Thank you

**Comment by jaburges** [comment]
@nicolargo are you able to update the docker image?

**Comment by juan11perez** [comment]
@nicolargo 
@jaburges 

I created an image based on the repo dockerfile. Used the alpine base added requests and paho. I have now been using it for a month without bugs. See below 

```
#
# Glances Dockerfile for ARM (based on Alpine ARM)
#
# https://github.com/nicolargo/glances
#

# Pull base image.
FROM python:3.4-alpine

# Install Glances (develop branch)
RUN apk add --no-cache --virtual .build_deps \
	gcc \
	musl-dev \
	linux-headers \
	&& pip install 'psutil>=5.4.7,<5.5.0' bottle==0.12.13 \
	&& apk del .build_deps
RUN pip3.4 install requests
RUN pip3.4 install paho-mqtt
RUN apk add --no-cache git && git clone -b develop https://github.com/nicolargo/glances.git

# Define working directory.
WORKDIR /glances

# EXPOSE PORT (For Web UI & XMLRPC)
EXPOSE 61208 61209

# Define default command.
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
```

**Comment by Anian-igor** [comment]
Could you share your config please?
I tried with your docker file and docker-compose file and get error
version: "2"
services:
  glances:
    build:
      context: ./data
      dockerfile: dockerfile.dev
    volumes:
      - ./data/glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      #- GLANCES_OPT=-w
      - GLANCES_OPT=--export mqtt
    ports:
      - 61208-61209:61208-61209
    pid: host
    restart: always

glances_1  | Traceback (most recent call last):
glances_1  |   File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
glances_1  |     "__main__", mod_spec)
glances_1  |   File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
glances_1  |     exec(code, run_globals)
glances_1  |   File "/glances/glances/__main__.py", line 29, in <module>
glances_1  |     glances.main()
glances_1  |   File "/glances/glances/__init__.py", line 143, in main
glances_1  |     start(config=config, args=args)
glances_1  |   File "/glances/glances/__init__.py", line 108, in start
glances_1  |     mode = GlancesMode(config=config, args=args)
glances_1  |   File "/glances/glances/standalone.py", line 98, in __init__
glances_1  |     self.screen = GlancesCursesStandalone(config=config, args=args)
glances_1  |   File "/glances/glances/outputs/glances_curses.py", line 121, in __init__
glances_1  |     self.screen = curses.initscr()
glances_1  |   File "/usr/local/lib/python3.4/curses/__init__.py", line 30, in initscr
glances_1  |     fd=_sys.__stdout__.fileno())
glances_1  | _curses.error: setupterm: could not find terminal

**Comment by juan11perez** [comment]
sure, this is my docker compose

```
  glances-mqtt:
    container_name: glances-mqtt
    image: glances-mqtt
    restart: unless-stopped
    network_mode: host    
    hostname: UNRAID    
    volumes:
    - /mnt/cache/appdata/glances/conf/glances.conf:/glances/conf/glances.conf
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - GLANCES_OPT= --export mqtt
    - PGID=100
    - PUID=99
    pid: "host"
    stdin_open: true
    tty: true
    mem_limit: 512m
    mem_reservation: 256m 
```

no ports on mine. My understanding is Glances can only do onething at time ;-)

**Comment by petter-b** [comment]
This issues is still there in 3.1.1b0.

```
[core@homeassistant ~]$ sudo docker run --name=glances --restart=always -p 61208:61208 -e GLANCES_OPT="--disable-process --quiet --export mqtt" -v /var/run/docker.sock:/var/run/docker.sock:ro -v /srv/automation/glances:/glances/conf:z -v /etc/localtime:/etc/localtime:ro --pid host nicolargo/glances
Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string 
```
```
[core@homeassistant ~]$ sudo docker run -e GLANCES_OPT="-V" nicolargo/glances
Glances v3.1.1b0 with psutil v5.4.8
```
My glances.conf for mqtt export:

> [mqtt]
> host=localhost
> port=1883
> user=xxxx
> password=yyyy
> topic=homeassistant
> tls=false

I am running Fedora Core OS with SELinux, hence the "z" option on the volume. WebGUI and rest API works just fine if I alter the GLANCES_OPT slightly.
