### ISSUE TITLE
Cannot export graph or CSV files.

### ISSUE THREAD

**Issue by Tom-Development** [nicolargo/glances#1451]
#### Description

 I run the following command and my glances gets a long error.

glances --export-graph

Then, once on the glances screen I press the "G" key and the following occurs:
https://pastebin.com/r88fBgiF

#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.4.2

* Operating System (lsb_release -a): 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

2019-03-30 18:44:23,160 -- INFO -- Start Glances 2.11.1
2019-03-30 18:44:23,160 -- INFO -- CPython 3.6.7 and PSutil 5.4.2 detected

**Comment by nicolargo** [comment]
Can you try with the latest Glances version ? (aka 3.1.0)
