### ISSUE TITLE
Glances Sensor Alias not getting updated

### ISSUE THREAD

**Issue by pymenow** [nicolargo/glances#1456]
Using Glances-3.1.0, bottle-0.12.16,psutil5.6.1

>>> import psutil
>>> psutil.sensors_temperatures()
{'pma8084_tz': [shwtemp(label='', current=38.411, high=145.0, critical=145.0)], 'tsens_tz_sensor0': [shwtemp(label='', current=0.042, high=None, critical=None)], 'tsens_tz_sensor5': [shwtemp(label='', current=0.043, high=None, critical=None)], 'tsens_tz_sensor10': [shwtemp(label='', current=0.041, high=None, critical=None)], 'tsens_tz_sensor2': [shwtemp(label='', current=0.041, high=None, critical=None)], 'tsens_tz_sensor9': [shwtemp(label='', current=0.041, high=None, critical=None)], 'tsens_tz_sensor3': [shwtemp(label='', current=0.041, high=None, critical=None)], 'quiet_therm': [shwtemp(label='', current=0.034, high=None, critical=None)], 'tsens_tz_sensor4': [shwtemp(label='', current=0.041, high=None, critical=None)], 'apq_therm': [shwtemp(label='', current=0.034, high=None, critical=None)], 'tsens_tz_sensor1': [shwtemp(label='', current=0.04, high=None, critical=None)], 'tsens_tz_sensor7': [shwtemp(label='', current=0.042, high=None, critical=None)], 'tsens_tz_sensor6': [shwtemp(label='', current=0.041, high=None, critical=None)], 'tsens_tz_sensor8': [shwtemp(label='', current=0.04, high=None, critical=None)]}

pma8084_tz is the only one that shows , which is fine as all others are around 0.

In the conf file I alias this as below
# Sensors alias
pma8084_tz_alias=MAIN SOC 0

But in the webui it continues to show 
SENSORS
pma8084_tz 1	C	39

Also there are a bunch of temp sensors on the ARM SOC I am using under the below sys path 
But how do i get those to show as well ?

/sys/class/thermal$ ls
thermal_zone0   thermal_zone11  thermal_zone2  thermal_zone5  thermal_zone8
thermal_zone1   thermal_zone12  thermal_zone3  thermal_zone6  thermal_zone9
thermal_zone10  thermal_zone13  thermal_zone4  thermal_zone7

**Comment by nicolargo** [comment]
Is the alias displayed correctly in the Curses (terminal) interface ?

**Comment by pymenow** [comment]
in Curses , I see all the sensors as listed by psutil.sensors_temperatures() in my first post instead of just pma8084_tz 1 that shows up in the web mode.
Also in Curses the alias is displayed correctly.

**Comment by sentriz** [comment]
I have the same problem

**Comment by sentriz** [comment]
I just created https://github.com/nicolargo/glances/pull/1466
which fixes the problem for me
