### ISSUE TITLE
Quicklook is broken

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#1474]
#### Description

With the last develop, when I start Glances the quicklook plugin is not here and I have the following error : 

> Error while initializing the quicklook plugin ('str' object has no attribute 'decode')

#### Versions

* Glances & psutil (glances -V): Glances v3.0.2 with psutil v5.4.8
* Operating System (lsb_release -a): mac os

**Comment by notFloran** [comment]
After some checks is related to `'\xe2\x96\x81'.decode('utf-8')` in `glances_sparklines.py`

**Comment by nicolargo** [comment]
Last commit should solve the issue...
