### ISSUE TITLE
Docker image fails on ARM: `exec user process caused "exec format error"`

### ISSUE THREAD

**Issue by rlue** [nicolargo/glances#1479]
#### Description

The example `docker run` command given in the README fails on a Raspberry Pi 3B+:

```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances
standard_init_linux.go:207: exec user process caused "exec format error"
```

Tried again with the `latest-arm` tag, just for good measure—but got the same result:

```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances:latest-arm
standard_init_linux.go:207: exec user process caused "exec format error"
```

#### Versions

* Glances & psutil (glances -V): N/A
* Operating System (lsb_release -a): latest stable Raspbian

      Distributor ID: Raspbian
      Description:    Raspbian GNU/Linux 9.4 (stretch)
      Release:        9.4
      Codename:       stretch

Tried with both `latest` (e11d9ef79840) and `latest-arm` (61b5cda20dee) tags.

#### Logs

N/A

**Comment by hajo62** [comment]
I see the same with **Raspbian GNU/Linux 9.9 (stretch)**.
Any ideas how to fix this?

**Comment by pierow2k** [comment]
I am also seeing this on Raspbian 9.9 with `nicolargo/glances:latest-arm`:

	Distributor ID:	Raspbian
	Description:	Raspbian GNU/Linux 9.9 (stretch)
	Release:	9.9
	Codename:	stretch

**Comment by XuZhen86** [comment]
Also observed same problem on Nvidia Jetson Nano
```
 Server Version: 19.03.2
 Kernel Version: 4.9.140-tegra
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: aarch64
```

**Comment by medelay** [comment]
aparently are the tags with arm not 32 bits but they are 64 bits thats why it isn't working. Has anyone got this working in docker on a raspberry pi ?

**Comment by XuZhen86** [comment]
Looks like a lot of images have the same issue. I get around by compiling locally and creating my own image. Make a Dockerfile from Ubuntu and run apt install packages also works except the image size is larger. Docker hub is kinda vague about exactly which arm architecture is supported by an image

**Comment by rlue** [comment]
I finally got around to building my own image today. In case anyone is not familiar with Docker, here's how you can build the docker image locally:

```sh
# perform these steps on your ARM machine
$ git clone https://github.com/nicolargo/glances
$ docker build -t nicolargo/glances:arm glances/docker-files/devel-arm/
```

This will create a **local** Docker image for glances on your ARM system, named `nicolargo/glances` and tagged `arm`. (tbh I really don't know the convention around specifying `armhf` vs `armv6` etc., but since you presumably won't be publishing this image, you don't even really need the tag at all.)

Then, start a container using the [Docker directions in the README](https://github.com/nicolargo/glances#docker-the-funny-way), replacing `docker.io/nicolargo/glances` with `nicolargo/glances:arm`.

---

Honestly I don't know the first thing about Docker image publishing and ARM compatibility. I've [pushed an image built on my RPi 3B+ to `rlue/glances:armv6`](https://hub.docker.com/r/rlue/glances). If you try it, **please report back to this thread** with some information about your device and whether the image works on it; if it works for everyone, maybe @nicolargo would be willing to audit and replace his official ARM image with it?

**Comment by brondum** [comment]
Any updates on this one? seems like the problem persists ?

**Comment by davidtrattnig** [comment]
I have the same issue within OpenMediaVault on a OdroidXU4.

**Comment by brondum** [comment]
Ended up creating my own docker image like @rlue 
But instead of using develop i used a specific version:

```
# Pull base image.
FROM python:2.7-alpine

# Install Glances
RUN apk add --no-cache --virtual .build_deps \
	gcc \
	musl-dev \
	linux-headers \
	&& pip install 'psutil>=5.4.7,<5.5.0' bottle==0.12.13 \
	&& apk del .build_deps

COPY ./glances /glances

# Define working directory.
WORKDIR /glances

# EXPOSE PORT (For Web UI & XMLRPC)
EXPOSE 61208 61209

# Define default command.
CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
```

**Comment by mcaden** [comment]
@rlue Worked like a charm on my rpi 4b 4GB

**Comment by Overbryd** [comment]
This is the `Dockerfile` I use on my Raspberry Pi 4 on `arm64`:

https://github.com/nicolargo/glances/issues/1419#issuecomment-677644194

**Comment by talondnb** [comment]
Any updates on this?

**Comment by TenPetr** [comment]
I have same issue.

**Comment by Verguldebarman** [comment]
Same here. I am on:

```
NAME=		LibreELEC
VERSION=	8.2.5
BUILD_ID=	0beeae963db04e94b1d4457a8fcaa3c25bf2161a
OPENELEC_ARCH=	WeTek_Hub.aarch64
LIBREELEC_ARCH=	WeTek_Hub.aarch64
```

and docker

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   1.13.1
 Built:        Sat Jul 15 18:44:38 UTC 2017
 OS/Arch:      linux/arm64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   1.13.1
 Built:        Sat Jul 15 18:44:38 UTC 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Comment by BlackDark** [comment]
Try `dev` tag:
![image](https://user-images.githubusercontent.com/9947112/103458516-44d84280-4d09-11eb-99e9-88c6241db782.png)

Next version release should automatically create all necessary builds for multiple archs.

**Comment by Verguldebarman** [comment]
Works!!!

![image](https://user-images.githubusercontent.com/67055019/103460176-87ebe300-4d14-11eb-9ccd-8d9b9e08fd06.png)

**Comment by RazCrimson** [comment]
Closing as we have multi-arch images now with proper support for arm.
