### ISSUE TITLE
Highly Recommend to add pynvml in requirements.txt

### ISSUE THREAD

**Issue by monchin** [nicolargo/glances#1480]
I installed glances but couldn't see the gpu information, and just now I found the reason: I didn't install pynvml. After I installed that, everything goes right. 
So I highly recommend that pynvml should be added in requirements.txt

**Comment by nicolargo** [comment]
It is already done:

- https://github.com/nicolargo/glances/blob/develop/setup.py#L64
- https://github.com/nicolargo/glances/blob/develop/optional-requirements.txt#L10
