### ISSUE TITLE
Random Starting CPU Usage

### ISSUE THREAD

**Issue by LrrrAc** [nicolargo/glances#1481]
When the container I run glances in is started, it can run at either around 100% of a core, or 50% of a core. I can restart it enough times to get either option, but dont understand why it will potentially double its cpu usage for apparently no reason. 

![image](https://user-images.githubusercontent.com/27321984/57474701-b58f3900-7260-11e9-82cd-f02c7d4e2e8d.png)

Here is a graph of me restarting the container every 2 minutes for an hour. Its 100% 17 times and 50% 14 times out of 30.

**Comment by nicolargo** [comment]
Please fill the issue with all relative information provided in the issue template...

**Comment by RazCrimson** [comment]
Closing stale issue.
