### ISSUE TITLE
No able to get ip address or no "address" key in SELECT "address" in "localhost.ip" 

### ISSUE THREAD

**Issue by chetankabra** [nicolargo/glances#1482]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: No able to get ip address or no "address" key in SELECT "address" in "localhost.ip" 
I am exporting the contents from glances to influxdb and quering through grafana to access the metrics
#### Versions

* Glances & psutil (glances -V): Glances v2.11.1 with psutil v5.2.2
* Operating System (lsb_release -a): Ubuntu 18.04.1 LTS"

**Comment by nicolargo** [comment]
Export of string (IP plugin) are only available in Glances 3.0 or higher.
Please upgrade...
