### ISSUE TITLE
Glances is not connecting to Elasticsearch

### ISSUE THREAD

**Issue by BhavanaGudi** [nicolargo/glances#1487]
I have installed glances in of of the AWS servers. I am trying to connect to Elasticsearch That is on a different server. My elasticsearch is behind Nginx and can reach elasticsearch only through reverse proxy.
In glances.conf, It is mandatory to give port number. But why elasticsearch works with http://<my_url>.com/elasticsearch. When I try to establish the connection, It says connection TimeOut error. ( I have also increased the time out to 60 )

**Comment by nicolargo** [comment]
Can you copy paste your glances configuration file and give us the information concerning Glances version and operating system environment.

**Comment by BhavanaGudi** [comment]
Glances version: Glances v3.1.0 with psutil v5.6.1
OS version:
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian


glances.conf:

[elasticsearch]
# Configuration for the --export elasticsearch option
# Data are available via the ES RESTful API. ex: URL/<index>/cpu/system
# https://www.elastic.co
host=http://<dns_server_name>/elasticsearch
port=NONE
index=glances


I am trying to contact elasticsearch  which is behind nginx. The connection is not being established.

**Comment by BhavanaGudi** [comment]
And also I want to export data we get from processlist. Each individual process and how much CPU, Mem its consuming. How will I be able to send these data to elasticsearch?

**Comment by nicolargo** [comment]
For the moment, only direct access to ELK is allowed (not through Proxy)....

**Comment by BhavanaGudi** [comment]
What about process list. 
I want details of how much CPU and memory each individual process is consuming

**Comment by nicolargo** [comment]
Not yeat, track this issue: https://github.com/nicolargo/glances/issues/794
