### ISSUE TITLE
Add net.ipv4.netfilter.ip_conntrack_count in the Connections plugin

### ISSUE THREAD

**Issue by SailorMax** [nicolargo/glances#1488]
Can you add check `net.ipv4.netfilter.ip_conntrack_count` and `net.ipv4.netfilter.ip_conntrack_max` to warn about dropped packets?

thank you.

**Comment by nicolargo** [comment]
For the moment, you can also use a simple AMP to do this.

Read the https://glances.readthedocs.io/en/stable/aoa/amps.html

**Comment by nicolargo** [comment]
@SailorMax For a future enhancement, what kind of information do you want Glances to return ? Only the current number of tracked connection and if this value is lower than the ip_connentrack_max ? Where do you want this stat to be displayed ?

**Comment by SailorMax** [comment]
I just faced the situation with aborted client connections. To find the reason took some time.
As a result, I thought it would be nice to see the warnings in Glances in these cases (Too many connections).

This is network theme => you can output these values in Network group.
Highlight with yellow when `ip_conntrack_count` near `ip_conntrack_max`.
Highlight with red when them almost or equal.

thank you.

**Comment by nicolargo** [comment]
Perhaps to be included in the future Connections plugins ==> See https://github.com/nicolargo/glances/issues/1526

**Comment by nicolargo** [comment]
Done in Glances 3.1.3 or higher.

Glances conf file:

```
[connections]
# Display additional information about TCP connections
# This plugin is disabled by default because it consumes lots of CPU
disable=False
# nf_conntrack thresholds in %
nf_conntrack_percent_careful=70
nf_conntrack_percent_warning=80
nf_conntrack_percent_critical=90
```

Result:

![image](https://github.com/nicolargo/glances/assets/776747/4421bd4c-b466-414d-8366-1be74e9de649)
