### ISSUE TITLE
I want to track the CPU percent for the specified process with influxdb , Is there any solution

### ISSUE THREAD

**Issue by zphiliam** [nicolargo/glances#1493]
I use the command to export the data
`glances --export influxdb -q`
but there is no specific process CPU or Memory percent .
I want to track the CPU percent for the specified process with influxdb, then display in Grafana.

Is there any solution ?

**Comment by nicolargo** [comment]
Sorry but not for the moment...

Follow ==> https://github.com/nicolargo/glances/issues/794
