### ISSUE TITLE
Per CPU in Web UI have some display issues.

### ISSUE THREAD

**Issue by gustaf71** [nicolargo/glances#1494]
#### Description

For a bug: 'glances -w1' display user, system and idle wrong in Web UI... 
but are correct in console view.
 
#### Versions

* Glances & psutil (glances -V): Glances v3.1.0 with psutil v5.6.1
* Operating System (lsb_release -a): Mac OS X 10.14.3

#### Logs

<img width="827" alt="Screenshot 2019-06-16 at 20 12 44" src="https://user-images.githubusercontent.com/36249438/59567841-513b7280-9073-11e9-80ba-1400a96a5302.png">

**Comment by nicolargo** [comment]
@notFloran can you have a look ?

**Comment by gustaf71** [comment]
not sure i understad you questions, what do you mean?.

**Comment by gustaf71** [comment]
I do like to point out that I do use 15" MacBookPro with Safari and the WEB UI on the above picture.
It looks to me that WEB UI maybe have difficult to display correct on smaller screen like 15" but
console (command-line) do not.

**Comment by nicolargo** [comment]
@gustaf71 Can you test the DEVELOP branch ?

**Comment by gustaf71** [comment]
The 'Per CPU' -option w1 in WEB UI looks to be correct now.  (Thanks) pic above.

More I look at it I find the user interface display duplicates and thinking it could be better I believe.

So I have made a example how it could look when -option w1 is used to display all CPU Core.

1. Brand 'This line could be long so it will not cut any information about the CPU'
2. CPU Core (name)	|	CPU (bar)	| 	Usage (%)	|	User (%)		|	System (%)		|	 Idle (%)
3. ...
N to end of all CPU Core.
Swap	|	Swap (bar)	| 	Swap (%) 		

Regards.
Fredrik
