### ISSUE TITLE
Can't connect to influxdb with https enabled

### ISSUE THREAD

**Issue by inmusic-bshephard** [nicolargo/glances#1497]
I'm not really sure if this is a bug or a feature request but I don't see any way to export to influxdb over HTTPS. Having looked at the code for the influxdb export module I don't see any way to enable this. I need to monitor multiple instances across different environments all around the world and I need to secure communication between glances and influxdb so as not to expose my influxdb credentials.

**Comment by inmusic-bshephard** [comment]
Some more digging later and this should be easy to add as the influxdb client library already supports this but it's disabled by default. changing the following lines to True works but it would be nice to be able to set these options in glances.conf and have them passed through to the client.
Lines 73 and 74 of influxdb/client.py
                 ssl=False,
                 verify_ssl=False,

**Comment by nicolargo** [comment]
Feature implemented by the latest commit.

Download the DEVELOP branch and add the **protocol=https** to your configuration file (default is http).

Can you test it ?

Will be available in Glancs 3.1.1 (coming soon).

**Comment by inmusic-bshephard** [comment]
Seems to do the trick however doesn't seem to verify the cert.
