### ISSUE TITLE
Thresholds not displayed in the WebUI for the DiskIO plugin

### ISSUE THREAD

**Issue by ChillarAnand** [nicolargo/glances#1498]
This is a new feature request. 

Currently, CPU/RAM has color codes which makes it easy to identify the resource usage. Can same color codes be added to disk io usage?
https://glances.readthedocs.io/en/latest/aoa/disk.html

**Comment by nicolargo** [comment]
Hi @ChillarAnand 

thanks for the feature request.

I already think about this feature but what threshold cans be implement by default for this kind of metrics... 

Do you have any advises ?

**Comment by ChillarAnand** [comment]
In general, IO > 70% is considered as critical. For example, [atop uses the same metric](https://linux.die.net/man/1/atop) for color codes.

I am not sure about the remaining thresholds. Do these thresholds be good enough?

<35 - Ok
>35 - Careful
>50 - Warning
>70 - Critical

**Comment by msalaz03** [comment]
@nicolargo, where in the glances outputs and or plugins does the program define the whether the display a different colour for the health level. Within the glances.conf file I can see the threshold values but not where the program is checking for these threshold values.

**Comment by msalaz03** [comment]
Hi I am currently in 4.2 and added these lines

# Set thresholds (in bytes per second) for a given disk name (rx = read / tx = write)
dm-0_rx_careful=4000000000
dm-0_rx_warning=5000000000
dm-0_rx_critical=6000000000
dm-0_rx_log=True
dm-0_tx_careful=700000000
dm-0_tx_warning=900000000
dm-0_tx_critical=1000000000
dm-0_tx_log=True

however this did not do anything.

It is important note that I changed the values for careful warning to 10 1000 10000 to double check. However this did not change the color of the text.

![image](https://github.com/user-attachments/assets/e615035f-6b84-4dd7-be23-3f314fea2a5e)
