### ISSUE TITLE
[Feature Request] Add ability to hide snaps / loopback devices

### ISSUE THREAD

**Issue by Justinzobel** [nicolargo/glances#1510]
#### Description

Add a switch in-app or from terminal to hide/show loopback devices (DISK I/O) and snaps (FILE SYS)

#### Versions

glances 3.1.1
OS Solus

**Comment by nicolargo** [comment]
It is already possible from the Glances configuration file. 

Please read the doc: https://glances.readthedocs.io/en/stable/aoa/disk.html

**Comment by jolly-llama** [comment]
The above link is broken, anyone looking for the new doc page can find it here: [](https://glances.readthedocs.io/en/stable/aoa/fs.html)
