### ISSUE TITLE
glances is not displaying in cmd. just run webserver mode without -w option

### ISSUE THREAD

**Issue by metya** [nicolargo/glances#1513]
#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

It's not a bug I think, but not a right behavior
When I type `glances` in cmd on Windows 10 it's not displaying in cmd, but start webserver like if I type `glances -w`

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.1 with psutil v5.6.3
* Operating System (lsb_release -a):
Windows 10

**Comment by nicolargo** [comment]
It's not a big. It's a feature...
As long as Microsoft will not ship a curse fully compatible terminal (compatible with the curse python lib), Glances will switch automatically to Web server mode on Windows OS.
