### ISSUE TITLE
Possible typo in glances_influxdb.py

### ISSUE THREAD

**Issue by DPellone** [nicolargo/glances#1514]
Hello,
it seems to me that at [line 44 of file glances_influxdb.py](https://github.com/nicolargo/glances/blob/3286e83ee07fdbfb27fc80e754deccacb7bf6882/glances/exports/glances_influxdb.py#L44) the variable `self.protocol` is misspelled as `self.protocole`.
This prevent glances to connect to InfluxDB; please check it.

**Comment by nicolargo** [comment]
Fix merged
