### ISSUE TITLE
Increase web refresh rate

### ISSUE THREAD

**Issue by Paytah232** [nicolargo/glances#1521]
From what I can see the web interface refreshes every 5 seconds.
Is there an environment variable I can set that will reduce that refresh rate to 1s or less?

**Comment by a2902793** [comment]
`glances -t 1`

**Comment by Paytah232** [comment]
I tried this and it seems to have increaseds the interval from 5secs to 6sec. Any other solution that could work? @nicolargo @a2902793

**Comment by CanisW** [comment]
e.g. using http://0.0.0.0:61208/30 can set the refresh rate to every 30 seconds.
ref:
1. "Web Server Mode" section on https://glances.readthedocs.io/en/stable/quickstart.html
2. https://github.com/nicolargo/glances/issues/784

**Comment by notFloran** [comment]
It seems that `glances -w -t 30` does not work anymore. I will look at it.

**Comment by notFloran** [comment]
@Paytah232 can you try the 3.1.3 version ? is now possible to do this : `glances -w -t 1`

**Comment by Paytah232** [comment]
How do I update on the synolgy nas? Is it auto or do I need to build it again from image?
________________________________
