### ISSUE TITLE
Can't install  glances using pip on Solus

### ISSUE THREAD

**Issue by bkdwt** [nicolargo/glances#1522]
When I try to install glances using pip, this error appears on compile:

`Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-CjLick/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8z0f9g/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-CjLick/psutil/`

*Operating** System*
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	4.0
Codename:	fortitude

*Logs*
https://gist.github.com/bkdwt/e42342bf4da3c28d5095a739d6c6d7db

**Comment by nicolargo** [comment]
unable to execute 'x86_64-solus-linux-gcc': No such file or directory

You should install the Dev tools (Gcc, make...) to be able to compile PsUtil.
