### ISSUE TITLE
Allow processlist columns to be selected in config file

### ISSUE THREAD

**Issue by ghost** [nicolargo/glances#1524]
I do not need all columns of the processlist. I would like to select the columns to be shown in the config file.

**Comment by nicolargo** [comment]
Related (for the WebUI) https://github.com/nicolargo/glances/issues/1515

**Comment by nicolargo** [comment]
CPU%, MEM% and command should alway be displayed.

Other column could be disabled by configuration. If a column is disable:
- stats related to the column should not be grabbed
- sort is not possible for this column
- filter are not possible for this column 

Warning: should be compliant to both thread and program mode

Example in the Glances configuration file:

```
[processlist]
disable_stat=io_counters,cpu_times,status,num_threads,pid,nice,username
```

**Comment by webysther** [comment]
@nicolargo How to hide some columns in containers? I tried this but no luck:

```sh
[containers]
disable_stat=Command
```

**Comment by nicolargo** [comment]
First version on the issue1524 branch.

First version ok for TUI StandAlone mode.

Should be done for:

[ ] - TUI standalone
[ ] - TUI client / server
[ ] - TUI browser
[ ] - WebUI 
[ ] - WebUI  browser
[ ] - Exports

**Comment by nicolargo** [comment]
Merged into develop.

Will be release in Glances 4.3.

@webysther I will open another issue to track this request.
