### ISSUE TITLE
Make CSV export append instead of replace

### ISSUE THREAD

**Issue by mitar** [nicolargo/glances#1525]
#### Description

I would like to save all recorded measurements to a CSV file. But currently if there is a CSV already present glances overrides it. I think it would be awesome if instead glances would just append additional rows.

It could check that existing header matches and abort if it does not.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.1 with psutil v5.6.3
* Operating System (lsb_release -a): Ubuntu 18.04.2 LTS

**Comment by nicolargo** [comment]
Nice enhancement request !

What i propose to implement in the future release:

- CSV file export will be append by default
- if the header did not match with the existing CSV file an error message is displayed and Glances is stopped
- a new --export-csv-overwrite tag is added in order to allow Glances to delete the existing CSV file on startup

Do you have additionnal requirements ?

**Comment by mitar** [comment]
Sounds good.

**Comment by nicolargo** [comment]
New documentation:

It's possible to export stats to a CSV file.

.. code-block:: console

    $ glances --export csv --export-csv-file /tmp/glances.csv

CSV file description:

- first line: Stats description (header)
- others lines: Stats (data)

By default, data will be append any existing CSV file.

If the header did not match with a previous one, an error is logged.

The --export-csv-overwrite tag should be used if you want to delete the existing CSV file when Glances starts.

It is possible to remove some exported data using the --disable-plugin tag:

  $ glances --export csv --export-csv-file /tmp/glances.csv --disable-plugin load,swap

**Comment by nicolargo** [comment]
Ok, it is available in the DEVELOP branch.

@mitar please can you test it ?

**Comment by nicolargo** [comment]
@mitar Any head up ?

**Comment by wellskb** [comment]
Is there any way to export CSV for a single process stats? At the moment exports all the stats and process. Is that possible to use the filter (regex) to export it? only one process.
