### ISSUE TITLE
Add a new TCP connections status plugin

### ISSUE THREAD

**Issue by mitar** [nicolargo/glances#1526]
#### Description

To monitor network load it would be also useful to record the number of TCP connections currently established. A very rude way to get this is: `netstat -an | grep -c ESTABLISHED`

Similarly, also connections in other states could be counted.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.1 with psutil v5.6.3
* Operating System (lsb_release -a): Ubuntu 18.04.2 LTS

**Comment by nicolargo** [comment]
I will have a look to add this feature but for the moment you can use a simple AMP:

Edit the Glances configuration file and add this section:

```
[amp_tcpconnections]
enable=true
regex=.*init.*
refresh=3
one_line=true
command=netstat -an | grep -c ESTABLISHED
countmin=1 

```

**Comment by nicolargo** [comment]
@minar

I propose the following implementation in the left menu of Glances:

![image](https://user-images.githubusercontent.com/776747/65818572-06ed9400-e213-11e9-8534-016d33f0113e.png)

With the following description:
- Listen: all ports created by server and waiting for a client to connect
- Initialized: All states when a connection is initialized (sum of SYN_SENT and SYN_RECEIVED)
- Established: All established connections between a client and a server
- Terminated: All states whena connection is terminated (FIN_WAIT1, CLOSE_WAIT, LAST_ACK, FIN_WAIT2, TIME_WAIT and CLOSE)

Are you ok ?

Any other idea to implement ?

**Comment by nicolargo** [comment]
Add:
/proc/sys/net/netfilter/nf_conntrack_count
/proc/sys/net/netfilter/nf_conntrack_max

**Comment by mitar** [comment]
This looks cool (have to yet to test it), and I agree that conntrack values would be useful as well.

**Comment by nicolargo** [comment]
Ok done.

Merged  in the DEVELOP branch.
