### ISSUE TITLE
Make processes.sort_key configurable

### ISSUE THREAD

**Issue by chtombre** [nicolargo/glances#1536]
#### Description

It would be nice if the default sort_key for processes (and also for docker plugin which uses same key as processes) could be overwritten by config file. 

This issue is possibly related to #1515

**Comment by nicolargo** [comment]
Also related to https://github.com/nicolargo/glances/issues/1432

**Comment by nicolargo** [comment]
Done in the develop branch.

Just add the sort_key line in the glances.conf file:

```
[processlist]
# Sort key: if not defined, the sort is automatically done by Glances (recommended)
# Should be one of the following:
# cpu_percent, memory_percent, io_counters, name, cpu_times, username
sort_key=memory_percent
```
