### ISSUE TITLE
Quicklook plugin not working on Systemd

### ISSUE THREAD

**Issue by poonab** [nicolargo/glances#1537]
#### Description

When starting glances through Systemd the quicklook plugin doesn't work, plugin works fine when executing from command line.

**glances.service:**

[Unit]
Description=Glances
After=network.target

[Service]
ExecStart=/usr/local/bin/glances -w
Restart=on-abort

[Install]
WantedBy=multi-user.target

#### Versions

Glances v3.1.2 with psutil v5.6.3

OS:
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

#### Logs

● glances.service - Glances
   Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset:
   Active: active (running) since Wed 2019-09-04 19:11:35 BST; 1s ago
 Main PID: 7038 (glances)
    Tasks: 4 (limit: 2200)
   Memory: 13.8M
   CGroup: /system.slice/glances.service
           └─7038 /usr/bin/python /usr/local/bin/glances -w

Sep 04 19:11:35 pidocker-1 systemd[1]: Started Glances.
Sep 04 19:11:36 pidocker-1 glances[7038]: Error while initializing the quicklook plugin (encode() argument 1 must be string, not None)

**Comment by nicolargo** [comment]
Hi,

can you try to add the percentage_char option in the quicklook section of the Glances configuration file ?

```
[quicklook]
disable=false
percentage_char=|
cpu_careful=50
cpu_warning=70
cpu_critical=90
mem_careful=50
mem_warning=70
mem_critical=90
swap_careful=50
swap_warning=70
swap_critical=90
```

**Comment by SNoof85** [comment]
Hi,

Google sent me there and i have exact same problem : 
```
2019-09-11 22:20:42,828 -- WARNING -- Sparklines module not found (No module named sparklines)
2019-09-11 22:20:42,829 -- CRITICAL -- Error while initializing the quicklook plugin (encode() argument 1 must be string, not None)
2019-09-11 22:20:42,830 -- ERROR -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 118, in _load_plugin
    plugin = __import__(plugin_script[:-3])
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_quicklook.py", line 25, in <module>
    from glances.outputs.glances_sparklines import Sparkline
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_sparklines.py", line 38, in <module>
    '┌┬┐╔╦╗╒╤╕╓╥╖│║─═├┼┤╠╬╣╞╪╡╟╫╢└┴┘╚╩╝╘╧╛╙╨╜'.encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None
```

Tried to add the `percentage_char=|` in the configuration file but still same error.

**Comment by poonab** [comment]
> Hi,
> 
> can you try to add the percentage_char option in the quicklook section of the Glances configuration file ?
> 
> ```
> [quicklook]
> disable=false
> percentage_char=|
> cpu_careful=50
> cpu_warning=70
> cpu_critical=90
> mem_careful=50
> mem_warning=70
> mem_critical=90
> swap_careful=50
> swap_warning=70
> swap_critical=90
> ```
> 
> Note for developer: already managed https://github.com/nicolargo/glances/blob/v3.1.2/glances/plugins/glances_quicklook.py#L134-L135

Added that to conf file and there was no change.

Can confirm conf is working as was able to use the disable flag to enable/disable plugin

**Comment by nicolargo** [comment]
The 66c9fff7 commit should solve the issue.

**Comment by nicolargo** [comment]
@poonab Can you test the DEVELOP branch ?

**Comment by poonab** [comment]
@nicolargo initial testing of Glances v3.1.4_BETA with psutil v5.6.3 shows issue to have been fixed

**Comment by nicolargo** [comment]
Thanks for the report @poonab !
