### ISSUE TITLE
xmlrpc service is unprotected and enabled by default!

### ISSUE THREAD

**Issue by jm33-m0** [nicolargo/glances#1541]
as i recently found, glances by default enable a systemd service which starts a xmlrpc server bound to 0.0.0.0.
everyone is able to call all APIs without a password, which is extremely dangerous!
please fix it

**Comment by jm33-m0** [comment]
i suggest disable all API services by default, when being enabled, ask the user to set a password

**Comment by nicolargo** [comment]
The fact that Glances is ran as a service is on the responsability of the package manager of you operating system. Please open an issue in the package manager issues tracker.

**Comment by jm33-m0** [comment]
Yeah I am aware of that, but glances really needs to set a password for its
API server in case it's being used.

**Comment by nicolargo** [comment]
You can by using --username and --password. See https://glances.readthedocs.io/en/latest/quickstart.html#client-server-mode

The packager should create (or ask) for a default password when Glances is installed on the OS.

**Comment by jm33-m0** [comment]
okay, im closing this
