### ISSUE TITLE
Running glances starts Sysinfo 0.7 again and again

### ISSUE THREAD

**Issue by johann-petrak** [nicolargo/glances#1542]
#### Description

Whenever I run glances, the Sysinfo 0.7 programm (sourceforge.net/projects/gsysinfo) gets started before the glances output even appears. When I close that program it immediately gets restarted, again and again and again.

#### Versions

* Glances & psutil (glances -V):  v3.1.2, v5.6.3
* Operating System (lsb_release -a): Ubuntu 18.04.3 
* Python: Anaconda (conda version 4.7.12)
* Installed with pip install

**Comment by nicolargo** [comment]
??? 

Do you have any special configuration keys in the AMPs section of your Glances configuration file ?

**Comment by johann-petrak** [comment]
I did not change anything in the config file at all. On the system where I have originally observed this I  have since completely re-installed Anaconda and glances within Anaconda and this is not happening any more. 

I tried this on another computer:
* conda version 4.7.5
* glances version v3.1.0 with psutil v5.6.3
* Ubuntu 18.04.3
* initially the "sysinfo" command was not found on that system
* Glances worked as expected
* I installed sysinfo using "apt install sysinfo"
* called sysinfo and it showed the gui, terminated sysinfo
* I started glances and the sysinfo GUI was shown, no output of glances on the console
* Clicking on the close window button of sysinfo closes the window and immediately re-opens the sysinfo window again. Still no output of glances
* repeatedly closeing the sysinfo gui, eventually makes the glances output appear on the console, but not updating, so the sysinfo process is locking glances progress
* I removed sysinfo using "sudo apt remove sysinfo"
* After this glances is back to normal
* I re-installed sysinfo and glances is broken and brings up the sysinfo window again

So on that system it seems to be repeatable that as soon as the sysinfo package is installed it will be called from within glances somehow and stop glances from working properly

**Comment by nicolargo** [comment]
I just have a look on the Glances sources and there no reference to sysinfo.

Perhap it is called by the PsUtil lib (used by Glances to grab system information).

Can you please test the following:

Open a python command line:

    python

Import PsUtil

    >>> import psutil

Get the stats:

    >>> psutil.virtual_memory()

Is the sysutil windows appears ?

**Comment by johann-petrak** [comment]
I think I have tracked down why this happens:
https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_quicklook.py#L92

This calls the method `get_cpu_info()` from the cpuinfo package (https://pypi.org/project/py-cpuinfo/) 

This package apparently tries to run `sysinfo -cpu` in order to get information from stdout, and this will invoke the GUI from  /usr/bin/sysinfo when the Ubuntu sysinfo package is installed. 
If the sysinfo  package is not installed (if the /usr/bin/sysinfo binary is not present) the same call to `get_cpu_info()` succeeds and returns useful information, so there seems to be some kind of fallback algorithm at work. 

I have submitted issue https://github.com/workhorsy/py-cpuinfo/issues/136 there

**Comment by nicolargo** [comment]
Ok thanks for the report.

I close this issue.

**Comment by johann-petrak** [comment]
Until py-cpuinfo is getting fixed and until glances depends on the new py-cpuinfo version, this is broken in glances though and will show that weird behavior on any system where that package is installed.

**Comment by nicolargo** [comment]
Temporary workaround the upstream py-cpuinfo is corrected:

```
glances --disable-plugin quicklook
```
