### ISSUE TITLE
IP plugin still exporting data when disabled

### ISSUE THREAD

**Issue by Nicholi** [nicolargo/glances#1544]
#### Description
When disabling the IP plugin an empty string is still exported (using influxdb). The IP portion of curses interface is disabled however.

Disabling the plugin through conf file with
```
[ip]
disable=true
```

Running with
`glances -d --export influxdb`

Observed measurement data in influxdb
```
> SELECT * FROM ip ORDER BY time DESC LIMIT 5
name: ip
time       history_size host                    ip_disable
----       ------------ ----                    ----------
1570164122 28800        vm15-dev-v2 true
1570164119 28800        vm15-dev-v2 true
1570164116 28800        vm15-dev-v2 true
1570164090 28800        vm15-dev-v2 true
1570164087 28800        vm15-dev-v2 true
```

If enabling ip plugin again (as well as re-appearing in upper right of curses interface):
```
> SELECT * FROM ip ORDER BY time DESC LIMIt 5
name: ip
time       address         gateway       history_size host                    ip_disable mask          mask_cidr public_address
----       -------         -------       ------------ ----                    ---------- ----          --------- --------------
1570164455 157.230.132.137 157.230.128.1 28800        vm15-dev-v2 false      255.255.240.0 20        2604:a880:2:d0::52b7:1
1570164452 157.230.132.137 157.230.128.1 28800        vm15-dev-v2 false      255.255.240.0 20        2604:a880:2:d0::52b7:1
1570164449 157.230.132.137 157.230.128.1 28800        vm15-dev-v2 false      255.255.240.0 20        2604:a880:2:d0::52b7:1
1570164446 157.230.132.137 157.230.128.1 28800        vm15-dev-v2 false      255.255.240.0 20        2604:a880:2:d0::52b7:1
1570164443 157.230.132.137 157.230.128.1 28800        vm15-dev-v2 false      255.255.240.0 20        2604:a880:2:d0::52b7:1
```

#### Versions
Glances v3.1.2 with psutil v5.6.3
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

#### Logs
You can see the ip plugin being listed as disabled in log. But still exporting data to influxdb regardless.
https://pastebin.com/F1D2aatA

```
startup
...
2019-10-04 04:23:17,296 -- DEBUG -- ip disabled by the configuration file
...
exporting
...
2019-10-04 04:23:17,707 -- DEBUG -- Export ip stats to InfluxDB
2019-10-04 04:23:17,716 -- DEBUG -- http://HOSTNAME:PORT "POST /write?db=DB HTTP/1.1" 204 0
```

**Comment by nicolargo** [comment]
When i made a test on my side (for example with the CSV export module), when i disable a plugin, it also disable the export.

I do not understand. You said that the stats are exported but on your "Observed measurement data in influxdb" i do not see the stats but only the fact that the plugin is disable...

**Comment by Nicholi** [comment]
Is there a way to disable exporting completely for the ip plugin? I just
see no need to insert these records when it's disabled. Otherwise I guess I
just misunderstood.

All other plugins seemed to stop exporting any data when disabled. Such as
diskio or processlist.
