### ISSUE TITLE
[WebUI] Add a new TCP connections status plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1547]
The TCP connections status plugin as been added in the DEVELOP branch (see https://github.com/nicolargo/glances/issues/1526).

![image](https://user-images.githubusercontent.com/776747/66426705-b6e0af80-ea12-11e9-8ae1-0f393b0ea400.png)

Only the Curses interface is available.

The goal of this ER is to implement the WebUI for this new plugin.

**Comment by nicolargo** [comment]
Hi @notFloran 

I fail to include the connections plugin in the WebUI, can you have a look ==>See branch https://github.com/nicolargo/glances/tree/issue1547

Thanks !

**Comment by notFloran** [comment]
I'll take care of it soon

**Comment by notFloran** [comment]
I have some problems with the plugin, I use mac.

My config file:

```
[connections]
disable=False
# nf_conntrack thresholds in %
nf_conntrack_percent_careful=70
nf_conntrack_percent_warning=80
nf_conntrack_percent_critical=90
```

And I see nothing new in the curse interface.

**Comment by nicolargo** [comment]
This plugin is only available on Linux...

You can fake it by replacing [the line 81](https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_connections.py#L81) by:

```
stats = {u'nf_conntrack_percent': 0.59356689453125,      'ESTABLISHED': 53, u'initiated': 0, u'terminated': 0, u'nf_conntrack_count': 1556.0, 'SYN_RECV': 0,                   u'nf_conntrack_max': 262144.0, 'SYN_SENT': 0, 'LISTEN': 17}
```
