### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/etc/mtab'

### ISSUE THREAD

**Issue by jiaxiaolei** [nicolargo/glances#1552]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

In ubuntu16.04, I use `$ snap install glances` to install glances.  After it, use `$ glances`, find glances does not work well, and show `PermissionError: [Errno 13] Permission denied: '/etc/mtab'`.

#### Versions

* Glances v2.11.1 with psutil v5.4.2
* Ubuntu 16.04.5 LTS

#### Logs

infomgr@sltmhhnasen:~$ sudo glances 
Warning: Unable to set locale. Expect encoding problems.
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:515: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 13] Permission denied: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py:515: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 13] Permission denied: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/snap/glances/5/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.11.1', 'console_scripts', 'glances')()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 884, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 893, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/5/lib/python3.5/site-packages/glances/plugins/glances_fs.py", line 107, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/__init__.py", line 1979, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/snap/glances/5/lib/python3.5/site-packages/psutil/_pslinux.py", line 1102, in disk_partitions
    partitions = cext.disk_partitions()
PermissionError: [Errno 13] Permission denied: '/etc/mtab'

infomgr@sltmhhnasen:~$ snap connections glances 
Interface                Plug                             Slot             Notes
hardware-observe         glances:hardware-observe         -                -
log-observe              glances:log-observe              -                -
mount-observe            glances:mount-observe            -   -
network                  glances:network                  :network         -
network-observe          glances:network-observe          -                -
physical-memory-observe  glances:physical-memory-observe  -                -
system-observe           glances:system-observe           -                -
upower-observe           glances:upower-observe           :upower-observe  -

**Comment by jiaxiaolei** [comment]
After `$ sudo snap connect glances:mount-observe :mount-observe`, glances work well.

In my opinion, good packaging would have a wrapper and connect necessary interfaces itself.
So, I think it's a bug for `glances` .

Any reply will be appreciated.

**Comment by anonymouse64** [comment]
The snap author here can request auto-connection of these interfaces through the process documented at https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455

**Comment by nicolargo** [comment]
@Lin-Buo-Ren Can you have a look on ths issue concerning the Snap packaging ? Thanks !

**Comment by drewwells** [comment]
still an issue @Lin-Buo-Ren

**Comment by drewwells** [comment]
```
sudo snap connect glances:network
sudo snap connect glances:system-observe
sudo snap connect glances:mount-observe
sudo snap connect glances:hardware-observe
sudo snap connect glances:log-observe
sudo snap connect glances:network-observe
sudo snap connect glances:physical-memory-observe
sudo snap connect glances:upower-observe
```
I still had to do all of these things to start without errors

**Comment by nicolargo** [comment]
The followigng list is now configure in Glances 4.0.8 or higher:

```
    plugs:  # https://snapcraft.io/docs/supported-interfaces
      - network
      - system-observe
      - mount-observe
      - hardware-observe
      - log-observe
      - network-observe
      - physical-memory-observe
      - upower-observe
      - home
      - network-bind
      - uio
      - raw-volume
      - removable-media
      - power-control
      - process-control
      - network-setup-observe
```
