### ISSUE TITLE
GPU stats not showing on mobile web view

### ISSUE THREAD

**Issue by itzsimpl** [nicolargo/glances#1555]
I have the latest version of glances installed and running it in web server mode `glances -w`. If I access the web server from a desktop computer, the GPU stats are visible, but if I access it from a mobile (vertical or horizontal view) they are not displayed. Same is true if I access the web server from a pad in vertical view (stats are not displayed), however in a horizontal view they are.

**Comment by nicolargo** [comment]
@notFloran Can you have a look on it ?
