### ISSUE TITLE
Remove the static exportable_plugins list from glances_export.py

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1556]
For the moment the list is statical because some plugin are not compatible with the export function. This list should be removed (all plugin are exportable by default) and be configurable (see related issue #1443).

**Comment by nicolargo** [comment]
Replaced by a "non exportable" plugins list:

    non_exportable_plugins = [
        'alert',
        'amps',
        'help',
        'now',
        'plugin',
        'ports',
        'processlist',
        'psutilversion',
        'quicklook'
    ]

**Comment by alex-ruhl** [comment]
Hi @nicolargo

It would be awesome if we could use the processlist plugin with the export function. I don't really know why this plugin and the others shown above are not exportable.  

Could you please give a brief explanation as to why these plugins (especially the processlist plugin) are not exportable and if this functionality is something we can expect in future versions of glances?

Thank you very much for this great tool!

**Comment by nicolargo** [comment]
@alex-ruhl there is an open issue on this request: https://github.com/nicolargo/glances/issues/794#issuecomment-230712660

So to make it short, the export should be compliant with all kind of backend (CSV, JSON but also nosql database) and the related discussion has not identify the best solution to do it.

Please fill free to propose some implementation strategy in the issue https://github.com/nicolargo/glances/issues/1556.

**Comment by alex-ruhl** [comment]
@nicolargo thank you for pointing to issue #794

**Comment by amard33p** [comment]
@nicolargo Can you please reopen this issue? I would love to have `amps` plugin export-able.

**Comment by nicolargo** [comment]
@amard33p can you please open another issue ?
