### ISSUE TITLE
install / Systemd Debian

### ISSUE THREAD

**Issue by oursours** [nicolargo/glances#1560]
Hi, i tried to follow this :

https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

I want to Start a Glances client exporting stats to an InfluxDB server.  When i run **sudo systemctl start glances.service**, and then **sudo systemctl status glances.service**, i get :

glances.service - Glances
Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset: enabled)
Active: activating ( auto-restart)(Result: exit-code) since Sat 2019-11-16 15:27:45 CET; 7s ago
Process: 1215 ExecStart=/usr/local/bin/glances -- quiet --export-influxdb (code=exited, status=2)
Main PID: 1215 (code=exited, status=2)

And glances doesn't appear in the task manager.

I tried to run the command **/usr/local/bin/glances --quiet --export-influxdb**, the command doesn't work. With the command : 

**/usr/local/bin/glances --export influxdb &** 

It does work. Trying to replace the command in the service file with this one won't work.

**Comment by nicolargo** [comment]
The following configuration should work:

```
[Unit]
Description=Glances
After=network.target influxd.service

[Service]
ExecStart=/usr/local/bin/glances --quiet --export influxdb
Restart=on-failure
RestartSec=30s
TimeoutSec=30s

[Install]
WantedBy=multi-user.target
```

**Comment by nicolargo** [comment]
I have updated the Wiki documentation regarding this issue.
