### ISSUE TITLE
Glances writing lots of Docker Error message in logs file

### ISSUE THREAD

**Issue by souvikg10** [nicolargo/glances#1561]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances & psutil (glances -V): 3.1.1
* Operating System (lsb_release -a): RHEL 7

#### Logs
Hi,
Glances is writing a lot of logs with respect to errors related to docker plugin even though i have disabled it. 

Is it possible to stop logging all together ? 

Thanks

**Comment by nicolargo** [comment]
@souvikg10 can you please paste/bin us the log file in order to have a look on the message ?

**Comment by souvikg10** [comment]
Hi @nicolargo ,
Thanks for the reply
I need to check the server logs to see if they are still there because we restarted the server. 

Since we export the logs to influxdb, is it possible to disable logs alltogether otherwise i would have to configure a logger and create a logrotate cron which is quite tedious. It would be much more simple if we simply disable logging.

I will try to check the logs if they are any tomorrow.

Thanks again

**Comment by souvikg10** [comment]
Hi,
Here's an example log on the server
`2019-11-05 14:26:56,232 -- ERROR -- Cannot export s00vl9992241;.docker stats to InfluxDB (400: {"error":"unable to parse 's00vl9992241;.docker ': invalid field format"}
)
`
I have disabled the docker-plugin export but still this pops up.

If we use the log_config.json 
can we disable logging all together?

Thanks

**Comment by nicolargo** [comment]
Yes you can setup your own log configuration. Please read https://glances.readthedocs.io/en/stable/config.html#logging

Nevertheless, i will change the log level of this message to debug in the next release.

**Comment by souvikg10** [comment]
Hi @nicolargo ,
So if i just do this, it is enough to disable logging
````
{
    "version": 1,
    "disable_existing_loggers": "True"
}
````

**Comment by nicolargo** [comment]
You can try. Or put CRITICAL in the log level.

Le ven. 22 nov. 2019 à 11:13, SOUVIK GHOSH <notifications@github.com> a
écrit :

**Comment by souvikg10** [comment]
Hi,
I tried this
```
 [/etc/systemd/system/glances.service:7] Executable path is not absolute, ignoring: LOG_CFG=/applis/12401-icpyd-00/var/glances/glances.json /applis/12401-icpyd-00/miniconda3/envs/glances/bin/glances    --config /applis/12401-icpyd-00/var/glances/glances.conf --export influxdb --disable-plugin docker --disable-plugin sensors --quiet
```

as a systemd service but i received some errors

**Comment by nicolargo** [comment]
In the DEVELOP branch, i change the log level of this message to DEBUG. It should not be visible in the log file.

Can you try it ?

**Comment by souvikg10** [comment]
Hi,
I will test it this evening. I need to do this from my personal server

**Comment by souvikg10** [comment]
Hi,
Sorry for the delay. I tested this and i don't see the docker logs anymore atleast as INFO.

**Comment by nicolargo** [comment]
Ok thanks for the feedback @souvikg10
