### ISSUE TITLE
LDAP provider

### ISSUE THREAD

**Issue by CallMarl** [nicolargo/glances#1568]
#### Description

Hello,

I wasn't able to find any LDAP provider, for glance does it one?
Thanks.

**Comment by nicolargo** [comment]
Hi @CallMarl 

what do you mean by LDAP provider ?

Nicolas

**Comment by CallMarl** [comment]
Hello,

something able to secure access of the web app by ldap authentication.
Thank you.

**Comment by CallMarl** [comment]
I finally found a way to authenticate with ldap. Using nginx reverse proxy.

If needed:
[https://github.com/sto/ngx_http_auth_pam_module](url)

**/etc/nginx/site-available/glances.conf :**
```
server {
	listen 8448 ssl;
	listen [::]:8448 ssl;

	server_name _;

	ssl_certificate /etc/ssl/local-certs/glances.crt;
	ssl_certificate_key /etc/ssl/private/glances.key;

	location / {
		rewrite /glances/(.*) /$1 break;

		auth_pam    "Secure Zone";
		auth_pam_service_name   "nginx";

		proxy_pass http://127.0.0.1:61208/;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location ~ /\. {
		deny all;
	}
}
```
**/etc/pam.d :** (pam_ldap need to bee setup)
```
auth	required	pam_ldap.so
account	required	pam_ldap.so
```

I'm interrested in your project, it's very good.
Thank you.
