### ISSUE TITLE
ubuntu: glances package does not install a systemd service

### ISSUE THREAD

**Issue by ssbarnea** [nicolargo/glances#1570]
While https://github.com/nicolargo/glances/issues/1560 documented creation of a service this should not be a manual step taken by someone installing glance.

Like other packages like nginx, apache,... they should also include the service. In that particular case the services should not be installed by default because is an optional feature, the tool being usable even without a service.

**Comment by nicolargo** [comment]
Depends of the use case... 

Most of the time, users run the Curse interface as for htop or top.

I think that the best way to proceed is to ask to the package maintainer to create two installer. One glances-cli and one glances-server...

It is belong to the packager not the developer team so i close this issue.
