### ISSUE TITLE
Autostart as 'glances -s'  - possible security issue?

### ISSUE THREAD

**Issue by flyingrhinonz** [nicolargo/glances#1572]
I installed glances on raspberry pi buster via apt-get.
Works great. Love the program.

But then I found out that glances starts by default in -s mode , which is not what I expected or asked for during install.
Furthermore, it was accepting client connections with no password request, which exposes the data to anyone.

Suggestions:
1. Default install DOES NOT install server mode, or at least asks the user for the mode they want.
2. Default passwordless access blocked and either force the user to set a password, or generate a random password that the user can change later.

It was easy enough to disable it with: systemctl disable glances.service , but this is after I accidentally found the open port while troubleshooting an unrelated issue on the box.

Thanks

**Comment by nicolargo** [comment]
This is not a bug...

Please report this issue to the Glances' RPI package maintainer.
