### ISSUE TITLE
wireless-tools package on arch linux?

### ISSUE THREAD

**Issue by AdrienLemaire** [nicolargo/glances#1573]
#### Description

While reading the [wifi doc](https://glances.readthedocs.io/en/latest/aoa/wifi.html) , I see 

> You need to install the wireless-tools package on your system.

The manpage doesn't give information as to what is really used behind, all I can find is:

>        W      Show/hide Wifi module

And the WiFi plugin doesn't show up in my glances terminal view.
Unfortunately, I cannot find such wireless-tools package from arch linux repositories nor from aur:

```console
$ yay -Ss glances       
community/glances 3.1.3-2 (981.9 KiB 6.8 MiB) (Installed)
    CLI curses-based monitoring tool
$ yay -Ss wireless-tools
$
```

Can you tell us what is the tool used for the plugin, rather than the package containing the tool in some distribution package manager?
Thanks in advance!

#### Versions

* Glances & psutil (glances -V): Glances v3.1.3 with psutil v5.6.7
* Operating System (lsb_release -a):
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

**Comment by nicolargo** [comment]
You can try wireless_tools

**Comment by AdrienLemaire** [comment]
@nicolargo sorry about that, I should have thought about trying that one. wireless_tools installed now, but restarting glances still doesn't bring the wireless section up.

my config has this part:
```
# ~/.config/glances
[wifi]
disable=False
# Define the list of hidden wireless network interfaces (comma-separated regexp)
hide=lo,docker.*
# Define SIGNAL thresholds in db (lower is better...)
# Based on: http://serverfault.com/questions/501025/industry-standard-for-minimum-wifi-signal-strength
careful=-65
warning=-75
critical=-85
```
As an aparte, the config isn't picked up by glances automatically, so I need to append the command parameter.
I'm using the following command:
```console
$ glances --sparkline --theme-white -1 -6 -C .config/glances
```
(while we're at updating the documentation, clarifying `pip install sparklines` in the [quicklook section](https://glances.readthedocs.io/en/stable/aoa/quicklook.html) might be good too.


While in glances, pressing W doesn't change anything. Might it be that the arch linux `wireless_tools` doesn't provide the one used by glances?

**Comment by nicolargo** [comment]
Perhaps the Glances package for Arch Linux did not install the Wifi Python lib too...

Try to install it:

    # yay -Ss python-wifi

or via the Pip installer

    # pip install wifi

**Comment by AdrienLemaire** [comment]
the aur package python-wifi is orphaned, so I went the pip route
```
Successfully installed pbkdf2-1.3 wifi-0.3.8
```
But I still don't see wifi things after restarting glances and pressing W.
Here's what I have: https://i.imgur.com/tbsdydR.png

Even if it's still not solved yet, thanks for the fast and useful support @nicolargo !

**Comment by nicolargo** [comment]
Can you try to start Glances in debug mode -d and pastebin us the content
of the Glances log file.

Le mer. 18 déc. 2019 à 14:13, Adrien Lemaire <notifications@github.com> a
écrit :

**Comment by AdrienLemaire** [comment]
[glances-dori.log](https://github.com/nicolargo/glances/files/3981016/glances-dori.log)

@nicolargo looking at the log, I understood that the config file should be at `~/.config/glances/glances.conf`. Now, the config is automatically parsed.

The log regarding wifi is weird:
```log
2019-12-19 08:49:40,660 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2019-12-19 08:49:40,660 -- DEBUG -- Load section wifi in ['/home/dori/.config/glances/glances.conf', '/etc/glances/glances.conf']
2019-12-19 08:49:40,661 -- DEBUG -- Load configuration key: history_size = 28800.0
2019-12-19 08:49:40,661 -- DEBUG -- Load limit: wifi_disable = ['False']
2019-12-19 08:49:40,661 -- DEBUG -- Load limit: wifi_hide = ['lo', 'docker.*']
2019-12-19 08:49:40,661 -- DEBUG -- Load limit: wifi_careful = -65.0
2019-12-19 08:49:40,661 -- DEBUG -- Load limit: wifi_warning = -75.0
2019-12-19 08:49:40,661 -- DEBUG -- Load limit: wifi_critical = -85.0
2019-12-19 08:49:40,661 -- DEBUG -- Plugin glances_wifi.py started in 0.037612 seconds
2019-12-19 08:49:40,828 -- DEBUG -- Active plugins list: ['fs', 'irq', 'cpu', 'diskio', 'ip', 'cloud', 'wifi', 'memswap', 'raid', 'ports', 'docker', 'quicklook', 'amps', 'core', 'now', 'processcount', 'system', 'folders', 'uptime', 'psutilversion', 'connections', 'sensors', 'processlist', 'mem', 'percpu', 'help', 'load', 'network', 'alert', 'gpu']
2019-12-19 08:49:40,830 -- DEBUG -- Plugin wifi update return []

```
First, a warning saying it's not compliant and disabled, then it's loaded, then always returns an empty list.

**Comment by nicolargo** [comment]
Oik copy that...

The first log line explains why it did not work.

The WiFi Python lib is not compliant with Python 3. Have a look on this
other issue.

https://github.com/nicolargo/glances/issues/1377

Unfortunately no simple solution to this issue right now...

Le jeu. 19 déc. 2019 à 00:53, Adrien Lemaire <notifications@github.com> a
écrit :

**Comment by RazCrimson** [comment]
Closing issue as wifi plugin is currently not supposed in Python 3
