### ISSUE TITLE
log file under public/shared tmp/ folders must not have deterministic name

### ISSUE THREAD

**Issue by yarikoptic** [nicolargo/glances#1575]
#### Description

I had run into elderly https://github.com/nicolargo/glances/issues/474 on an elderly glances (2.1.1) on debian, which brought my attention to this issue.
To the date it seems (according to docs in https://github.com/nicolargo/glances/blob/16a9ce3ad1b0faf91bf791397743e0eac4b38389/docs/config.rst#logging) that 

    By default, the glances-USERNAME.log file is under the temporary directory

which could be a vector for attacks/information leaking etc etc, because temporary directory usually allows modifications to any user, so an attacker could (pre)create a log file (or symlink to e.g. /etc/passwd targetting a root user) causing glances to write into an "existing" file.  So it could potentially have many security implications.

That is why all tools avoid deterministic file names in temporary directories, so if you look under e.g. /var/tmp you would see that systemd always adds some randomly looking uuid, etc.

Anyways, we are talking about log files, so they ideally should not be in /tmp anyways, but somewhere where logs are expected to be found. E.g. XDG could be consulted (there is appdirs python module to assist with that): https://stackoverflow.com/questions/25897836/where-should-i-write-a-user-specific-log-file-to-and-be-xdg-base-directory-comp ; and for root they could even go under /var/log/glances.log or alike.

**Comment by nicolargo** [comment]
Thanks for the proposal @yarikoptic 

What i understand after reading some threads:
- the target folder for log file should be something like $HOME/.local/state, but for the moment its only a proposal and neither Linux OS implement this feature...
- another candidate is $HOME/.local/share (available thought the $XDG_DATA_HOME environment variable)
- last one is $HOME/.cache ($XDG_CACHE_HOME) 

After reading [this post](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), i propose, on Linux and BSD OS:
- check XDG_CACHE_HOME variable, if the path exist, create $XDG_CACHE_HOME/glances subfolder and use it to create the glances.log file
- if the  XDG_CACHE_HOME variable is not defined, check if the path $HOME/.local/share exist, create $HOME/.local/share/glances subfolder and use it to create the glances.log file
- else use the default /tmp/glances-$USER.log file

The glances -V file will display the location of the log file.

**Comment by nicolargo** [comment]
Implementation done in the DEVELOP branch (see commit ecb9db9c).
Will be release in Glances 3.1.4.
