### ISSUE TITLE
Install doesnt work on DietPi distro

### ISSUE THREAD

**Issue by Wibbbs** [nicolargo/glances#1576]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances & psutil (glances -V): Install not funtional
* Operating System (lsb_release -a): DietPi distro based on Debian GNU/Linux 10 (buster)

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

When installing on DietPi linux ditro the install fails with the following error.

```
Downloading https://files.pythonhosted.org/packages/d4/6f/5f5818496d69915f0e576f1dd4621aac7837118b67df2927849b092b38d9/Glances-3.1.3.tar.gz (44.1MB)
     |████████████████████████████████| 44.1MB 94kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-IHPCDs/glances/setup.py'"'"'; __file__='"'"'/tmp/pip-install-IHPCDs/glances/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-IHPCDs/glances/pip-egg-info
         cwd: /tmp/pip-install-IHPCDs/glances/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nicolargo** [comment]
As said in the manual (https://github.com/nicolargo/glances#source), you should install Python headers for your DietPi distro or use another installation method (see https://github.com/nicolargo/glances#pypi-the-simple-way)...
