### ISSUE TITLE
sort by clicking improvements and bug

### ISSUE THREAD

**Issue by orena1** [nicolargo/glances#1578]
#### Description
I found two issues when I used glances (great app!!!)  on windows and opening the monitor on chrome.
1. Clicking on CPU% will sort the processes by CPU usage, but in most monitoring software another click sort it by reverse (So that the lowest CPU usage will be at the top).
2. Clicking on IOR/s or IOW/s does not sort the processes correctly.

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.3 with psutil v5.6.3
* Operating System (lsb_release -a):
```
(base) C:\Users\oren>lsb_release -a
'lsb_release' is not recognized as an internal or external command,
operable program or batch file.
 ```
Just kidding ;-)
Windows 10 Pro 1909

**Comment by nicolargo** [comment]
Hi @orena1 

1) It is not a bug, it is a feature. Glances layout is made to show relevant information. Who want to see the lowest CPU usage ?).

2) Same issue on Linux OS. The IOR/r and IOR/w sort did not work on the Web UI. @notFloran can you have a look on this issue ?

**Comment by nicolargo** [comment]
@notFloran Can you have a quick look on the second issue concerning the sort of IOR/r and IOR/w ?

**Comment by notFloran** [comment]
@nicolargo @orena1 I made a PR, can you try it ?
