### ISSUE TITLE
Threading.isAlive was removed in Python 3.9. Use is_alive.

### ISSUE THREAD

**Issue by tirkarthi** [nicolargo/glances#1585]
https://bugzilla.redhat.com/show_bug.cgi?id=1791693

https://github.com/nicolargo/glances/blob/f0e8ef44f20db1d8ae77c179f08ff9325a41f946/glances/plugins/glances_ports.py#L85

Thanks for the library!

**Comment by nicolargo** [comment]
Corrected by @tirkarthi PR.

Thanks to him.
