### ISSUE TITLE
Hi, please make version support Kali Linux, sir

### ISSUE THREAD

**Issue by oldman20** [nicolargo/glances#1587]
Hello, i interested with glances app, but cant install in Kali, please make support it, thanks!
im not developer, so just request, cant do anything
thanks your attention!

**Comment by nicolargo** [comment]
Kali is based on Linux, so it should work.

Try this: https://installlion.com/kali/kali/main/g/glances/install/index.html

**Comment by oldman20** [comment]
> Kali is based on Linux, so it should work.
> 
> Try this: https://installlion.com/kali/kali/main/g/glances/install/index.html

thanks so much!
