### ISSUE TITLE
Hide function in sensors section

### ISSUE THREAD

**Issue by dtalens** [nicolargo/glances#1590]
New feature: 
Add hide function of some sensors. In the same way that can be done with the hard drive partitions.
For example, in glances.conf in Sensors section: 
hide=name_sensor01,name_sensor02...

* Glances v3.1.3 with psutil v5.6.7
* LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by kanyck** [comment]
3.1.4.1 still can't hide unneeded sensors.

**Comment by mabod** [comment]
I support this request! I already renamed a couple of sensors with the *_alias function:

```
[sensors]
Tctl_alias=CPU Temp2 
Tdie_alias=CPU Temp1
nct6797 2_alias=Fan CPU
nct6797 3_alias=Fan hinten
nct6797 4_alias=Fan unten
nct6797 5_alias=Fan oben
nct6797 7_alias=Fan sys
```
But I am seeing to many sensors which are not useful to me and are just confusing:

```
Composite             39C   
Sensor 1              39C   
Sensor 2              40C  
Composite             42C  
Sensor 1              42C   
Sensor 2              41C   
CPU TempCtl           54C   
CPU TempDie           54C
Tccd1                 41C   
SYSTIN                39C   
PCH_MCH_TEM            0C   
CPUTIN                36C
AUXTIN0               42C   
AUXTIN1             -128C   
AUXTIN2               61C   
AUXTIN3               -2C
PCH_CHIP_CP            0C   
PCH_CHIP_TE            0C
PCH_CPU_TEM            0C   
nct6797 1              0R   
Fan CPU              608R 
Fan hinten           598R   
Fan unten            213R   
Fan oben             193R   
nct6797 6              0R   
Fan sys              802R
```

**Comment by distributorofpain** [comment]
@mabod have you tried using an aliases?  Just wondering if you have been able to alias AUXTIN0 - 3.  I cant seem to get an alias to apply to them.

Also, if you use the web gui, the ones that are 0 are hidden.   glances -w -p <portnumber>

**Comment by mabod** [comment]
@distributorofpain:  What do you mean? I do not want to alias AUXTIN0 - 3. I want to hide them and the others.

**Comment by distributorofpain** [comment]
hiding is fine too, just wanted to know if you had tried to alias it since i cant seem to alias it.

**Comment by mabod** [comment]
Aliases work fine for me:

```
AUXTIN0_alias=aaaa
AUXTIN1_alias=bbbb
```

But no hiding.

**Comment by distributorofpain** [comment]
> Aliases work fine for me:
> 
> ```
> AUXTIN0_alias=aaaa
> AUXTIN1_alias=bbbb
> ```
> 
> But no hiding.

Thanks!  I see where i made my mistake.

**Comment by distributorofpain** [comment]
I was discussing this in the 1596 pull request mentioned above.  In Glances v3.1.5 with PsUtil v5.7.2 the hide function is working.  just add "hide=AUXTIN0,AUXTIN1" in the sensors section of the glances config.  Verified on my install just now.

**Comment by mabod** [comment]
I tested with Glances v3.1.6_b1 with PsUtil v5.7.2 and it is working. I used your hide example but AUXTIN0 and 1 still show up.

**Comment by modelrockettier** [comment]
Pull request #1596 will fix this issue, it just got closed for some reason without being applied.

**Comment by wolfallein** [comment]
I also want the hide function implemented, and I confirm pull request #1596 fix this. Just apply the suggested patch to `glances_sensors.py` if you want it now.

**Comment by dtalens** [comment]
I also confirm pull request #1596 fix this but this patch is not applied at version 3.1.6.1

**Comment by dtalens** [comment]
Manual #1596 fix of version 3.1.6.1 desapear in version 3.1.6.2. Hide settings do not work.
![image](https://user-images.githubusercontent.com/6631832/110708595-34f24880-81fb-11eb-970a-62a393a5c32c.png)

**Comment by nicolargo** [comment]
Re-apply in the develop branch => See commit https://github.com/nicolargo/glances/commit/871b4c32b22581242c326b67459c2a86f97c6c4a

Sorry for that !

**Comment by gauvins2** [comment]
Hiding sensors still not working for me. (pop_os 22.04)
(Alias IS working)

**Comment by nicolargo** [comment]
It works (tested on the latest Glances 3.2.6.4 version):

![sensors1](https://user-images.githubusercontent.com/776747/170856568-1fc953c0-f7c9-4726-941b-cfc40543d5c8.png)

![sensors2](https://user-images.githubusercontent.com/776747/170856571-ff0e458e-aa9a-4f66-a152-5017cef75c8f.png)

**Comment by hrandib** [comment]
Hi @nicolargo,
Your example doesn't hide the sensor in the upper case, as pointed out by @gauvins2 above. And I can observe that it doesn't really work.
```nct6776 2_alias=Fan
drivetemp 1_alias=WD 8TB
drivetemp 2_alias=WD 12TB
hide=AUXTIN
```
Result:
![image](https://user-images.githubusercontent.com/17005110/185351988-a797dbcb-0aa8-4d79-bf9e-1f7eb933f948.png)

Glances v3.2.7 with PsUtil v5.9.1

**Comment by dtalens** [comment]
Hi, It works for me if I add lowercase aliases.
No configuration changes:
![image](https://user-images.githubusercontent.com/6631832/186773657-36984adb-ca28-4213-9a7b-c315889c3b21.png)

Adding this:
```
SYSTIN_alias=systin
AUXTIN1_alias=auxtin1
AUXTIN2_alias=auxtin2
AUXTIN3_alias=auxtin3
hide=systin,auxtin1,auxtin2,auxtin3
```
![image](https://user-images.githubusercontent.com/6631832/186774029-0fcbefd0-defa-4c03-b279-232143c6312c.png)

Gllances version 3.2.7

**Comment by hrandib** [comment]
Hi,
Thank you very much for the solution.
Is it assumed that it will be resolved in the future and the direct way also will be available?

**Comment by nicolargo** [comment]
@kanyck Yes, it will be corrected in the next release.

**Comment by nicolargo** [comment]
Done on the develop branch (see commit 1bed69bc).

To be tested !

**Comment by gauvins2** [comment]
Perhaps late to the party (just back home).

The latest Glances 3.2.7 fixes display for *the first jc42 entry.  *(see
attached screen capture)
