### ISSUE TITLE
Kafka key name needs to be bytes

### ISSUE THREAD

**Issue by watsonb** [nicolargo/glances#1593]
https://github.com/nicolargo/glances/blob/3e5ec443cea6edfd705622b4c90da2783ff8bc35/glances/exports/glances_kafka.py#L88

when running glances as follows:

```shell
glances -d -t 5 -C C:\glances\glances.conf --disable-plugin ip --export kafka
```

I would see errors showing up on the local logs like this:

```text
2020-02-05 08:19:14,144 -- ERROR -- Cannot export system stats to Kafka ()
```

I played around with some local python code and kafka-python, and discovered that the `key` argument of the `KafkaProducer.send()` method must be of type byte.

I hacked the glances source locally and changed this:

```python
try:
            self.client.send(self.topic,
                             key=name),
                             value=data)
```

to this:

```python
try:
            self.client.send(self.topic,
                             key=bytes(name, 'utf-8'),
                             value=data)
```

and now my consumer can see the messages flowing.

**Comment by watsonb** [comment]
I may have come up with a solution a bit premature here.

While the above proposal does work for me on Windows with Python 3, under Linux with Python 2, I get the following error for each attempt to send:

```bash
str() takes at most 1 argument (2 given)
```

Apparently the `bytes` built-in in Py2 is essentially the same thing as `str`.  I did come up with a fix that seems to work for me across Windows and Linux, Py2 and Py 3.  Up towards the top:

```python
import codecs
```

And the send fix:

```python
try:
            self.client.send(self.topic,
                             key=name.encode('utf-8'),
                             value=data)
```

**Comment by nicolargo** [comment]
Thanks for the patch @watsonb.

Il will include it in the next release.

**Comment by nicolargo** [comment]
Done in the DEVELOP branch.

Thanks again @watsonb
