### ISSUE TITLE
Feature request: Include hostname in all (e.g. kafka) exports

### ISSUE THREAD

**Issue by watsonb** [nicolargo/glances#1594]
#### Description

When running Glances in standalone mode for the sake of exporting stats/metrics to a centralized collector (e.g. Kafka, elasticsearch), I've noticed that each stat "dimension" (e.g. system, uptime, gpu, cpu, docker, mem, etc.) is exported as its own document/message.  This is a great design, however there is no "nice" way to correlate all of these documents/messages to the host from which they came.

For example, I've setup a kafka exporter on a host, and when I subscribe to a topic and print out the received message's key/value, I see things like this:

```json
key is: load. value is: {u'min15': 0.08, u'load_careful': 0.7, u'load_disable': u'False', u'history_size': 28800.0, u'load_warning': 1.0, u'load_critical': 5.0, u'cpucore': 1, u'min1': 0.04, u'min5': 0.06}
```

```json
key is: uptime. value is: {u'seconds': 58527, u'history_size': 28800.0}
```

```json
key is: system. value is: {u'os_name': u'Linux', u'os_version': u'4.15.0-42-generic', u'linux_distro': u'Ubuntu 18.04', u'hostname': u'knemol-ar-glances-bionic-benlocal', u'platform': u'64bit', u'history_size': 28800.0, u'hr_name': u'Ubuntu 18.04 64bit'}
```

The `system` stat actually does include the hostname of the host, but none of the other ones do.  If it were just a single system reporting, this wouldn't be an issue, but I plan to onboard many more hosts.  I'd rather avoid creating a topic/index per host.  If the system's hostname were included in each stat export, it would make it easier to aggregate metrics in, say, Kibana or Grafana.

#### Versions

* Glances & psutil (glances -V):

Glances v3.1.3 with psutil v5.6.7

* Operating System (lsb_release -a):

Ubuntu 16.04 (xenial) and 18.04 (bionic)
EL 7 (CentOS and RedHat)
Windows Server 2016

**Comment by watsonb** [comment]
My hack to achieve this was to modify `glances_kafka.py` as follows:

Near the top of the code (around line 22)

```python
import socket
```

Modify the export method from this:

```python
        # Create DB input
        data = dict(zip(columns, points))
```

to this:

```python
        # Create DB input
        data = dict(zip(columns, points))
        data.update({"glances_fqdn": socket.getfqdn()})
```

There is probably a better and more efficient way to do this as you should only need to get the FQDN one time and make it available to other exporters, alas this serves my purpose for now.

**Comment by nicolargo** [comment]
Hi @watsonb 

i just commit the feature to add tag to Kafka messages. 

Tags can be defined in the Glances' configuration file:

    # Tags will be added for all events
    tags=foo:bar,spam:eggs

or

    # You can also use dynamic values
    tags=hostname:`hostname -f`

The feature is available in the DEVELOP branch and will be release in the next release (Glances 3.1.4).

**Comment by watsonb** [comment]
Wow, that's really cool.  I like having the ability to do it in the config file.  Thanks!

Question, is this tagging capability unique to the kafka exporter or is it generalized for the other exporters as well?

**Comment by nicolargo** [comment]
For the moment only for Kafka and Influxdb. But it will be interesting to have this feature available for all exporter.
