### ISSUE TITLE
FS filtering can be done on device name 

### ISSUE THREAD

**Issue by Inrego** [nicolargo/glances#1606]
I'm running glances on docker. I'm mounting /raid because I want to monitor it. But the other 4 entries are quite uninteresting for me.

![image](https://user-images.githubusercontent.com/2242329/75121305-20e0b500-5693-11ea-928b-b1b26c72da9a.png)

I tried meddling with the hide under [fs] in the conf, but to no avail.
I tried the following:

```
_olv.conf
/dev
/dev/sdb2
/dev*
/dev.*
/dev/sdb2*
/dev/sdb2.*
_*
```

**Comment by nicolargo** [comment]
Hi @Inrego ,

for the moment filtering is done on the mount point name.

In your case, you can try this to remove _hostname:

    .*hostname

In the next release, filtering on device name should also be allowed.

**Comment by nicolargo** [comment]
Implemented in the DEVELOP branch.
