### ISSUE TITLE
Glances 3.1.3: when no network interface with Public address -- Error while initializing the ip plugin ('NoneType' object has no attribute 'split')

### ISSUE THREAD

**Issue by spezialist1** [nicolargo/glances#1615]
Hi glances developers,

Under **CentOS-8.1 (4.18.0-147.5.1.el8_1.x86_64)** found a bug in the stable version of **Glances v3.1.3 with psutil v5.7.0**.

The point of the bug: if there is _no network interface with a public IP address_ in the system, i.e. no access to the Internet (any other network interfaces may be present), running glances will cause an error:
`2020-03-02 15:23:38,010 -- INFO -- Start GlancesStandalone mode`
`2020-03-02 15:23:40,759 -- CRITICAL -- Error while initializing the ip plugin ('NoneType' object has no attribute 'split')`
`2020-03-02 15:23:40,770 -- ERROR -- Traceback (most recent call last):`
`  File "/usr/local/lib/python3.6/site-packages/glances/stats.py", line 120, in _load_plugin
    self._plugins[name] = plugin.Plugin(args=args, config=config)`
`  File "/usr/local/lib/python3.6/site-packages/glances/plugins/glances_ip.py", line 65, in __init__
    self.public_address = PublicIpAddress().get()`
`  File "/usr/local/lib/python3.6/site-packages/glances/plugins/glances_ip.py", line 178, in get
    return ', '.join(set([x.strip() for x in ip.split(',')]))`
`AttributeError: 'NoneType' object has no attribute 'split'`

The bug has 100% repeatability: as soon as the system has a network interface with a public IP address, i.e. Internet access, glances is launched normally without the error above.

I installed the stable version of glances from the Internet with the command `curl -L https://bit.ly/glances | /bin/bash`.

Very thanks for the support.

**Comment by nicolargo** [comment]
Duplicated issue: https://github.com/nicolargo/glances/issues/1528

Already corrected in the DEVELOP branch.

Will be available in Glances 3.1.4 (soon...)

**Comment by spezialist1** [comment]
Ok, thanks for the support :-).
