### ISSUE TITLE
How to hide process-list columns, or at least show only CPU, MEM, and Command?

### ISSUE THREAD

**Issue by johnnyutahh** [nicolargo/glances#1617]
Can one hide process-list columns?

I seek to display only `CPU`, `MEM`, and `Command`.

I'm running macOS 10.14.6, Glances v3.1.3 with psutil v5.6.3.

[Standard disclaimer: I glances features and concepts hard to uptake and find all in one spot. I hunted around readthedocs, glances --help, this github repo for ~20 mins and could not find anything describing this.]

**Comment by nicolargo** [comment]
Duplicated enhancement request: https://github.com/nicolargo/glances/issues/1524

**Comment by Dibbyo456** [comment]
+1, glances show tons of useless things for me, I just only wants to seek, CPU, MEM, USER, COMMAND.
