### ISSUE TITLE
Lighttpd Reverse proxy glances web not working

### ISSUE THREAD

**Issue by gr01d** [nicolargo/glances#1619]
#### Description
I am trying to create a reverse host for glances, so I can access my glances with http://mydomain.ddns.net/monitor

But I am greeted with 404 not found.

Running glances web ui with this command:
`$ glances -w -B 127.0.0.1`

My lighttpd config file has this:
```
server.modules = (
        "mod_rewrite",
        "mod_proxy"
)

$HTTP["url"] =~ "^/monitor" {
proxy.server  = ( "" => ( (
        "host" => "127.0.0.1",
        "port" => 61208
) ) )
}
```

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances & psutil (glances -V):
* Operating System (lsb_release -a):

`
$ glances -V
Glances v3.1.3 with psutil v5.5.1`

` Raspbian 10 Buster `

**Comment by nicolargo** [comment]
Please have a look to this Wiki page: https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

**Comment by gr01d** [comment]
I forgot to mention that I am using lighttpd web server

**Comment by gr01d** [comment]
Giving up, now using nginx. Problem could be related to HTTP 1.0 in lighttpd
