### ISSUE TITLE
Docker container's used memory not correct

### ISSUE THREAD

**Issue by TsingJyujing** [nicolargo/glances#1639]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

I created a container to run MongoDB, and the memory is 9.7GB by using `docker stats` and the glances show it's 28GB.

#### Versions

* Glances & psutil (glances -V):Glances v3.1.4.1 with PsUtil v5.7.0
* Operating System (lsb_release -a):
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Strange,

not reproduced on my side:

![Selection_046](https://user-images.githubusercontent.com/776747/80308049-147cf380-87cd-11ea-8bb6-a9fc36fa3bf4.jpg)

I use Docker lib version 4.1.° (pip show docker) to grab the stats. What is your version ?

**Comment by TsingJyujing** [comment]
```
$ glances --version
Warning: Unable to set locale. Expect encoding problems.
Glances v3.1.4.1 with PsUtil v5.7.0
Log file: /home1/irteamsu/.local/share/glances/glances.log
```

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/7792749/80332458-dd1e4d80-8885-11ea-889a-2b369c015074.png">

**Comment by RazCrimson** [comment]
@TsingJyujing 
Could you confirm if you face this issue in the latest release of glances?

I'm not able to reproduce this on my end.

**Comment by Feriman22** [comment]
@RazCrimson I can reproduce the issue:
https://github.com/nicolargo/glances/issues/2637

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/2637
