### ISSUE TITLE
View by CPU is only showing 6 of 12 cores

### ISSUE THREAD

**Issue by UmbralSamurai** [nicolargo/glances#1640]
I just installed a new server with 12 cores, however, Glances is only showing 6 of the 12 cores, is this because it's a Xeon that 6 core with 12 Threads, or is there some setting I'm missing?

#### Versions

* Glances & psutil (glances -V): Glances v3.1.4.1 with PsUtil v5.6.2
* Operating System (lsb_release -a): Debian 10

Thanks as always for this awesome software!

**Comment by nicolargo** [comment]
Glances uses the PsUtil lib to grab this information.
It use https://psutil.readthedocs.io/en/latest/#psutil.cpu_times 

This function "a list of named tuples for each logical CPU on the system".  Logical cores means the number of physical cores multiplied by the number of threads that can run on each core (this is known as Hyper Threading).

I just update the documentation (see commit b573712f in the DEVELOP branch).
