### ISSUE TITLE
Question about using Grafana and Glances

### ISSUE THREAD

**Issue by steakhutzeee** [nicolargo/glances#1642]
Hi, i'm using the latest image of Glances, from Docker Hub.

I'm using it with Grafana with `- GLANCES_OPT= --quiet --export influxdb`

I know that the export does not work with the `-w` parameter. Point is i tried with `-c` but had issues and an error stating i could not use them together and/or some python errors i do not remember, so here i read that i should have used --quiet.

Of course now i can not see Glances because of --quiet, and only see my stats in Grafana.

How could i do to have both?

Hope it's clear, thanks in advance for your time!

**Comment by nicolargo** [comment]
Hi @steakhutzeee !

For the moment, it is not possible to have one Glances to export and serve. A request already exist (see https://github.com/nicolargo/glances/issues/1527).

So the only workaround is to run Glances twice. One to export and one to serve.

Nicolas
