### ISSUE TITLE
Glances should not phone home

### ISSUE THREAD

**Issue by fuzxxl** [nicolargo/glances#1646]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

When I run glances on my system (installed through the system's package management), it reports that a newer version is available.  This kind of “phone home” behaviour is uncalled for.  I did not consent to glances making contact to some server.  This is an infringement of my privacy.  Software should not contact any servers without consent from the user.  Please disable this feature by default.

#### Versions

* Glances & psutil (glances -V):

    Glances v3.1.3 with psutil v5.7.0

* Operating System (lsb_release -a):

    $ uname -mrsv
    FreeBSD 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64
    $ freebsd-version -rku
    12.1-RELEASE-p3
    12.1-RELEASE-p3
    12.1-RELEASE-p3

#### Logs

n/a

**Comment by mitchejj** [comment]
https://glances.readthedocs.io/en/stable/config.html#syntax

      [global]
      # Does Glances should check if a newer version is available on  PyPI?
      check_update=true

**Comment by fuzxxl** [comment]
I am aware of that.  The default is for this to be set, so glances phones home by default.  Without obtaining the user's consent first.  This is not something software should ever do.  Get consent first!

**Comment by nicolargo** [comment]
@fuzxxl I just disable by default the check_update on the master branch (the one used by packager to build Glances for OS). But i let it on the DEVELOP branch, because version can be unstable.

**Comment by fuzxxl** [comment]
Fair enough.  Thanks a lot!
