### ISSUE TITLE
No Sensor information

### ISSUE THREAD

**Issue by tdmsoares** [nicolargo/glances#1647]
I just installed Glances and I notice that sensors information (temperature, battery, fan) are missing.

Notes

I tried with python3, the codes

>>> import psutil
>>> psutil.sensors_
psutil.sensors_battery(       psutil.sensors_fans(          psutil.sensors_temperatures(  
>>> psutil.sensors_battery()
sbattery(percent=99.90471653168176, secsleft=<BatteryTime.POWER_TIME_UNLIMITED: -2>, power_plugged=True)
>>> psutil.sensors_fans()
{'dell_smm': [sfan(label='Processor Fan', current=2200), sfan(label='', current=2200)]}
>>> psutil.sensors_temperatures()
{'dell_smm': [shwtemp(label='CPU', current=47.0, high=None, critical=None), shwtemp(label='Other', current=42.0, high=None, critical=None), shwtemp(label='SODIMM', current=39.0, high=None, critical=None)], 'acpitz': [shwtemp(label='', current=25.0, high=107.0, critical=107.0)], 'coretemp': [shwtemp(label='Physical id 0', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 0', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 1', current=46.0, high=105.0, critical=105.0), shwtemp(label='Physical id 0', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 0', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 1', current=46.0, high=105.0, critical=105.0)]}

Glances v3.1.4.1 with PsUtil v5.7.0

Thanks!

**Comment by tdmsoares** [comment]
Sorry guys...
I found the reason: It's lack of space in screen. Hiding some information (Disks and Folders) and the sensors display appears.

Now, a question: Is there any way the sensors not be hidden even in different screens?

**Comment by nicolargo** [comment]
@tdmsoares not for the moment, perhaps disable others unnecessary plugins from the left columns or tweaks its to not display all the information (using hide configuration key in the Glances configuration file).
