### ISSUE TITLE
Cannot start Glances service on RPI

### ISSUE THREAD

**Issue by RienduPre** [nicolargo/glances#1649]
Hi,

I installed glances on my Raspbery Pi's in the folder:/home/pi/glances

I can start glances from the command line by ./home/pi/glances/bin/glances or go to the folder and start it from there by ./glances

When I try to start it as a service it won't work
glances.service is like this

`
[Unit]
Description=Glances
After=network.target

[Service]
ExecStart=/home/pi/glances/bin/glances -w
Restart=on-abort

[Install]
WantedBy=multi-user.target
`

With this status:

`● glances.service - Glances
   Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset: 
   Active: failed (Result: exit-code) since Fri 2020-04-24 15:13:16 CEST; 2h 9mi
  Process: 5317 ExecStart=/home/pi/glances/bin/glances -w (code=exited, status=1
 Main PID: 5317 (code=exited, status=1/FAILURE)`

I have the same issue on all my RPI's

Any help is more than welcome

Thanks,
Rien

**Comment by nicolargo** [comment]
Hi @RienduPre 

some questions:
1) what is your Glances version ?
2) what happen when you start Glances in Web server mode from the command line ?

    /home/pi/glances/bin/glances -w

3) Is there any /tmp/glances*.log file ?

Thanks !

**Comment by Dmole** [comment]
@RienduPre glances is to heavy for the rpi anyway (because it's python).
Make a rust clone, or use an alternative (screen splitting with iotop/top/iftop)

**Comment by RienduPre** [comment]
Ok,
I decided to loop for other options.

Thank you
