### ISSUE TITLE
 RuntimeWarning: ignoring FileNotFoundError

### ISSUE THREAD

**Issue by mariusud** [nicolargo/glances#1652]
#### Description
RuntimeWarning keeps on popping up so the UI moves and is unreadable. Have tried reinstalling, same error.
#### Versions
kernel 5.3.0-46-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
Glances v2.11.1 with psutil v5.4.2:

#### Logs

`/usr/lib/python3/dist-packages/psutil/_pslinux.py:1150: RuntimeWarning: ignoring FileNotFoundError(2, 'No such file or directory')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
/usr/lib/python3/dist-packages/psutil/_pslinux.py:1150: RuntimeWarning: ignoring FileNotFoundError(2, 'No such file or directory')
  warnings.warn("ignoring %r" % err, RuntimeWarning)`

**Comment by nicolargo** [comment]
Please upgrade your Glances version.

This issue is already corrected.
