### ISSUE TITLE
How to start glances with --username option on syetemd?

### ISSUE THREAD

**Issue by Baloneo** [nicolargo/glances#1657]
This is my service config
```
[Unit]
Description=Glances
After=network.target

[Service]
ExecStart=/usr/bin/glances -C /etc/glances/myglances.conf -w
Restart=on-abort

[Install]
WantedBy=multi-user.target
```
I want to start the web server, and limit user to access my glances web server.

**Comment by nicolargo** [comment]
Hi @Baloneo 

as said in the documentation (https://glances.readthedocs.io/en/stable/quickstart.html), you have to start Glances once from the command line with:

    glances -w --password

If will ask you a password for the default glances user.

![Screenshot from 2020-05-12 18-29-25](https://user-images.githubusercontent.com/776747/81720396-a566f680-947e-11ea-9345-be05c376bf29.png)

Next  time you start the Web server, every user will be asked for a login/password:

![Screenshot from 2020-05-12 18-29-43](https://user-images.githubusercontent.com/776747/81720464-bf083e00-947e-11ea-9bf7-b3d5639da98b.png)

Note: you can define multiple login/password. 

Password (hash) is stored in the ~/.config/glances/<login>.pwd file (on Linux).

**Comment by nicolargo** [comment]
Documentation updated.
