### ISSUE TITLE
Wiki page for starting as a service

### ISSUE THREAD

**Issue by soporificpanda** [nicolargo/glances#1661]
In addition to the instructions on the [wiki page](https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd) for starting glances as a service in webserver mode, I needed to add the line

`RemainAfterExit=yes`

under the [Service] section for the webserver to remain persistent/available.

**Comment by nicolargo** [comment]
Done !

https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

Thanks for the issue report :)
