### ISSUE TITLE
Docker image is not up to date

### ISSUE THREAD

**Issue by guillaumelamirand** [nicolargo/glances#1662]
#### Enhancement Description

Hi,

I am using glances in docker, and the latest tag has not getting any update since last year. Running the image I have got the following message : You are using Glances version 3.1.1b0, however version 3.1.4.1 is available.

I am probably going to build the image myself but could you consider pushing a updating one?
Thank you.

**Comment by hajo62** [comment]
And pls. for RaspberryPi, too.
