### ISSUE TITLE
missing temperature

### ISSUE THREAD

**Issue by m2c2lure67** [nicolargo/glances#1664]
I did not notice until after 20.04 upgrade, so it may have occurred a short time prior, but currently glances is missing the temperature?

**Comment by TimPreble** [comment]
Running Raspberry Pi4 4gb Ubuntu 20.04 and also confirm that temps are missing.

**Comment by nicolargo** [comment]
As said in the documentation this plugin is disable by default because there is some performance issue on some OS.

To enable it, just run Glances with:

    glances --enable-plugin sensors

**Comment by Yohan9206** [comment]
> As said in the documentation this plugin is disable by default because there is some performance issue on some OS.
> 
> To enable it, just run Glances with:
> 
> ```
> glances --enable-plugin sensors
> ```

Hi nicolargo,
How can I add this to my yml file?
Kind Regards,
Yohan
