### ISSUE TITLE
glances.conf FS hide not applying

### ISSUE THREAD

**Issue by stevietv** [nicolargo/glances#1666]
#### Description

For a bug: I've tried numerous ways to attempt to some drives from the file sys section.
This is my current conf:
```
[filesystem]
hide=/boot.*,/snap.*,/dev/loop*,^sd..$
```

whilst this works perfectly for the Disk I/O section adn shows me only sda, sdb and sdc nothing I do seems to have any impact on the file sys table.

![image](https://user-images.githubusercontent.com/1117625/82501440-9377fa00-9af5-11ea-8159-014428f8eee0.png)

#### Versions

* Glances & psutil (glances -V): latest docker build, not sure how to find version
* Operating System (lsb_release -a): Ubuntu 18.04.4 LTS

**Comment by nicolargo** [comment]
The section should be **[fs]** not **[filesystem]** .

Read https://glances.readthedocs.io/en/stable/aoa/fs.html.

**Comment by stevietv** [comment]
Hi @nicolargo 
thanks for your reply, but sorry, I have actually tried both in by glances.conf.
The reason I tried [filesystem] also is because you actually refer to that in your manual:

![image](https://user-images.githubusercontent.com/1117625/82569642-d03d0300-9b80-11ea-8670-61f36a895f83.png)

my current conf:

![image](https://user-images.githubusercontent.com/1117625/82569759-f793d000-9b80-11ea-9b8f-f4e09ff2749c.png)

and the output in glances:

![image](https://user-images.githubusercontent.com/1117625/82569834-0d08fa00-9b81-11ea-9857-99dd5de12370.png)

I think this is a valid problem and doesn't deserve to be tagged 'rejected' and 'RTFM', I did ;)

**Comment by nicolargo** [comment]
Can you try to add a point before the * (loop* is not a valid regexp: [https://regex101.com/r/5pB1UB/1](https://regex101.com/r/5pB1UB/1)):

```
[fs] 
hide=.*loop.*

```

**Comment by stevietv** [comment]
ok, so I puzzled some more.

```
[fs]
hide=.*boot.*,.*snap.*
#allow=zfs
```
gives me this result, i.e. the loop devices are hidden:

![image](https://user-images.githubusercontent.com/1117625/84566052-50b0e700-ad6e-11ea-8fa6-ad07acb3fd03.png)

whereas 
```
[fs]
hide=.*boot.*,.*snap.*,.*loop.*
#allow=zfs
```
gives the same result.
However taking out the  `.*snap.*` shows the loop devices:
![image](https://user-images.githubusercontent.com/1117625/84566115-02e8ae80-ad6f-11ea-8cf7-f482577c0a80.png)

so it appears that the snap text filters out those devices at /dev/loop*

Hope this info helps.
If theres any more info I can provide let me know.

I was also wondering why the same device is shown multiple times?

**Comment by Kjwon15** [comment]
I have this problem too.

**Comment by nicolargo** [comment]
Patch available in the develop branch.

Will be release in Glances 3.3.0.

Sorry for the delay @stevietv
