### ISSUE TITLE
Issue when adding a new specific container

### ISSUE THREAD

**Issue by gillesvs** [nicolargo/glances#1667]
Hello,

I do have glances in docker working fine to monitor everything except for 2 containers. The two containers that stop all docker to be monitored are watchtower and deepstack.
I use the --import influx setting for Glances:
sudo docker run -d --name="glances" --net=host --privileged --restart="unless-stopped" -p 61208-61209:61208-61209 
-e GLANCES_OPT="--quiet --export influxdb" -v /home/gilles/docker-data/glances/glances.conf:/glances/conf/glances.conf 
-v /var/run/docker.sock:/var/run/docker.sock --pid host docker.io/nicolargo/glances

I see nothing in the docker run parameters that causes this. Every time I started one of these two (watchtower or deepstack), all dockers monitoring stops (and are not recorded in influlx db anymore)

my docker run commands are:
 sudo docker run --name="watchtower" -d --restart="unless-stopped"-v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower
and
sudo docker run -d --name="deepstack" -e VISION-DETECTION=True --restart="unless-stopped" -v /home/gilles/docker-data/deepstack:/datastore -p 83:5000 deepquestai/deepstack

Any idea why glances immediatly stops monitoring all containers as soon as one of these two is started?

#### Versions

* Glances : Latest in docker
* Operating System : Linux Mint Tricia 19.3 Tricia

#### Logs

I did try to generate logs applying: (https://glances.readthedocs.io/en/latest/config.html#logging)
But no success. Even try so map -v /home/gilles/docker-data/glances/log:/var/log/ to be able to edit with no success either

Thanks
gilles

**Comment by BlackDark** [comment]
Could you retry this with the current `dev`  docker tag? @gillesvs

**Comment by RazCrimson** [comment]
Closing as stale issue
