### ISSUE TITLE
How to display the output of --export in a graphical way

### ISSUE THREAD

**Issue by amirouche** [nicolargo/glances#1672]
I am looking for a program to display in a graphical way the output of `--export`.

Thanks in advance.

**Comment by nicolargo** [comment]
What kind of export do you use ?
If it is CSV, you can use Excel.
For InfluxDB, you can use Grafana.
Glances can also directly generate graph: https://glances.readthedocs.io/en/stable/gw/graph.html

**Comment by amirouche** [comment]
The graph output is good enough for my use-case.

Thanks for the input.
