### ISSUE TITLE
Missing: Help command doesn't have info on TCP Connections

### ISSUE THREAD

**Issue by Mirppc** [nicolargo/glances#1675]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

In the help menu for Glances 3.1.4.1 with psutil 5.4.8 there is nothing about how to show/hide the newly implemented TCP Connections section.  See the Imgur link below.

https://imgur.com/a/wPJwRKr

#### Versions

* Glances & psutil (glances -V): See above Imgur link for pictures and above in the description
* Operating System (lsb_release -a):  See Photos on Imgur

#### Logs

Logs Not Needed

**Comment by Mirppc** [comment]
Solution would be to add a line in the help section with....

k Show/hide TCP connections

**Comment by nicolargo** [comment]
Had to refactor the help to display additional information.

**Comment by RazCrimson** [comment]
@nicolargo This issue is fixed seems to be fixed in latest develop by the below line. https://github.com/nicolargo/glances/blob/021ac4cea906977b448af2e3ff861715ee0892c2/glances/plugins/glances_help.py#L108

Could you please close this issue as its done?

**Comment by Mirppc** [comment]
i'll close it as i opened it.
