### ISSUE TITLE
GPU "proc" showing as 0% in both API and Web UI always

### ISSUE THREAD

**Issue by mkanet** [nicolargo/glances#1678]
#### Description

**ISSUE:**
The Glances API and Web UI display **GPU proc** value as "**_0_**" and "**_N/A_**", respectively.  I am using an NVIDIA GTX1050ti GPU.

**API URL:**
http://192.168.1.2:61208/api/3/gpu

**Returns:**
[
  {
    "key": "gpu_id",
    "gpu_id": 0,
    "name": "GeForce GTX 1050 Ti",
    "mem": 5.792331695556641,
    "proc": 0,
    "temperature": 26
  }
]

#### Versions
Glances v3.1.4.1 with PsUtil v5.7.0

The only way to see complete GPU information is by running Glances in standalone mode locally on a PC:
![GlancesGPU](https://user-images.githubusercontent.com/811008/84607952-f21a6480-ae64-11ea-98b5-02281f11f35b.png)

Maybe, I'm doing something wrong?  Is there a workaround or fix for this?  I'd really like to get this to work properly.

**Comment by mkanet** [comment]
@nicolargo could you please confirm this is a reproducible bug?  Or, maybe I'm doing something wrong?  GPU "Proc" works perfectly in Glances standalone mode; but, isn't passed to the API or web interface.

**Comment by mkanet** [comment]
@nicolargo I upgraded to the latest version of Glances (version 3.1.5).  I am still seeing the same issue.  I am already using the latest version  of **py3nvml**

I am able to also see the "proc" value when I execute **nvidia-smi**.  Is there anything that I can try as a work-around?  I just need to grab GPU "proc" percentage via a REST call.

Thank you for all your help.

**Comment by RazCrimson** [comment]
Seems to be working fine on Glances `v3.2.3` with PsUtil `v5.8.0` and python-py3nvml version `0.2.6-1`

![image](https://user-images.githubusercontent.com/52282402/140811587-8a406b35-e767-4e17-bfe0-ff4e602be1a0.png)

**Comment by nicolargo** [comment]
@RazCrimson on your screenshot, the API return proc = 0. This is the same issue reported by @mkanet. Do you see values != 0 on your configuration ?

**Comment by RazCrimson** [comment]
@nicolargo 

No, i get valid values for proc too.
![image](https://user-images.githubusercontent.com/52282402/141656310-609b53eb-9e79-44cf-95b4-ac123066c301.png)

**Comment by mkanet** [comment]
@nicalargo I was finally able to get different values from `proc` other than 0.  I think the problem might have been that my PC wasn't utilizing the GPU very much; since it's a headless server running backend tasks.  When I enabled GPU transcoding in Plex Media Server, the `proc` value changed from 0.

If it's okay with you, I'll go ahead and close this issue.  Thank you so much for your time.
