### ISSUE TITLE
Apply alias to Duplicate sensor name

### ISSUE THREAD

**Issue by distributorofpain** [nicolargo/glances#1686]
#### Description

For some reason, guessing cause the board is soo new, the sensor name for the system temp and CPU fan speed are the same when detected.  I wanted to alias both with different names but if you put two entries in, you get an error ( this makes sense ).  Would like to be able to alias a sensor type or add an option in the alias entry so that you can differentiate between a temp sensor and a fan speed.

For now, i just put a slash in the name....

![image](https://user-images.githubusercontent.com/18275482/86503886-63707780-bd80-11ea-9930-f4fef4c7131a.png)

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.4.1 with PsUtil v5.7.0

* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

#### Logs
`
  File "/usr/local/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 138, in main
    core = GlancesMain()
  File "/usr/local/lib/python3.8/dist-packages/glances/main.py", line 111, in __init__
    self.args = self.parse_args()
  File "/usr/local/lib/python3.8/dist-packages/glances/main.py", line 264, in parse_args
    self.config = Config(args.conf_file)
  File "/usr/local/lib/python3.8/dist-packages/glances/config.py", line 111, in __init__
    self.read()
  File "/usr/local/lib/python3.8/dist-packages/glances/config.py", line 146, in read
    self.parser.read_file(f)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/etc/glances/glances.conf' [line 255]: option 'it8622 1_alias' in section 'sensors' already exists
`

**Comment by kattjevfel** [comment]
I think I'm having the same issue, I cannot alias fan1 and temp1 separately, which makes the list unreadable.

**Comment by distributorofpain** [comment]
Thanks for adding this as an enhancement!

**Comment by nicolargo** [comment]
Done in the develop branch.

If a sensors has temperature and fan speed with the same name unit (example foo),  it is possible to alias it using:

```
foo_temperature_core_alias=Alias for temp
foo_fan_speed_alias=Alias for fan speed
```

By default, the following configuration line will apply the alias name for all:

```
foo_core_alias=Alias for speed/temp
```

**Comment by Herbs851** [comment]
Hi @nicolargo,

Sorry to comment on this closed ticket.

Is there a way to dissociate 2 sensors with exactly the same names ?

Example : 

![image](https://user-images.githubusercontent.com/51154851/218117220-a137e721-9eef-4064-b7da-d687a34e7f51.png)

```
>>> psutil.sensors_temperatures()
{'acpitz': [shwtemp(label='', current=16.8, high=20.8, critical=20.8), shwtemp(label='', current=16.8, high=20.8, critical=20.8), shwtemp(label='', current=27.8, high=105.0, critical=105.0)], 'nvme': [shwtemp(label='Composite', current=36.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=36.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=40.85, high=65261.85, critical=65261.85), shwtemp(label='Composite', current=38.85, high=81.85, critical=84.85), shwtemp(label='Sensor 1', current=38.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=45.85, high=65261.85, critical=65261.85)], 'coretemp': [shwtemp(label='Package id 0', current=35.0, high=100.0, critical=100.0), shwtemp(label='Core 0', current=35.0, high=100.0, critical=100.0), shwtemp(label='Core 1', current=32.0, high=100.0, critical=100.0), shwtemp(label='Core 2', current=33.0, high=100.0, critical=100.0), shwtemp(label='Core 3', current=33.0, high=100.0, critical=100.0), shwtemp(label='Core 4', current=33.0, high=100.0, critical=100.0), shwtemp(label='Core 5', current=34.0, high=100.0, critical=100.0)]}
```

These are 2 strictly identical nvme ssd.

**Comment by nicolargo** [comment]
@Herbs851 See https://github.com/nicolargo/glances/issues/2280

**Comment by Herbs851** [comment]
Thanks for the information !!!
