### ISSUE TITLE
class AmpsList method _build_amps_list() Windows fail (glances/amps_list.py)

### ISSUE THREAD

**Issue by darylkell** [nicolargo/glances#1689]
When comparing the .conf regex for an AMP, the regex is almost certain to fail on Windows OS.

The problem lies with the "for c in p['cmdline']:" line within the method. Some processes have a value of 'None' for the key 'cmdline' where a list is expected, meaning the except is tripped (NoneType object is not iterable) and the for loop exits; the regex search has failed. 
In my case it was failing when doing the regex comparison against Desktop Window Manager (dwm.exe) in Windows 10.

Recommend a check of the key p['cmdline'] prior to looping through it (prior to the "for c in p['cmdline']" loop) as that fixed it for me, just a simple:
`if p['cmdline'] is None:
    continue`

**Comment by nicolargo** [comment]
Done in commit 219c4de0

Thanks for the issue report/correction @darylkell
