### ISSUE TITLE
Enhancement Request: .conf parameter for AMP

### ISSUE THREAD

**Issue by darylkell** [nicolargo/glances#1690]
Could we please have a parameter in the conf for an AMP to disable the number of matching processes appearing in the output?

Something like:
`[amp_plex]
list_processes=false
...`

This way one could display any sort of notification they like, including ones where number of processes aren't relevant. In my case I'm querying Plex for the number and other detail of current streams, as an example. 

If I've missed this in the documentation then I've also missed it in the code and I apologise in advance.

Code suggestion:
glances_amp.py/GlancesAmp.update_wrapper()  -> Add a check for the conf parameter and if parameter==false, self.set_count('')

**Comment by nicolargo** [comment]
Proposal:

Instead of adding a new **list_processes** configuration key, if a AMP is defined without any **regex** option, it will be executed  every refresh time and the process count will not be displayed.

**Comment by nicolargo** [comment]
Implemented in commit 05897a61 (DEVELOP branch) for the Curses interface.

@darylkell : Can you test this version it with your AMP ?
@notFloran : Can you implement this for the WebUI ? (i just add a regex boolean in the JSON data, if it is False, than you should not display the process count and the style should be set to OK)

**Comment by darylkell** [comment]
Your proposal would work for my use-case, but I'm not sure if it would fit as well for most/all use cases.
It would mean a non-regex AMP would no longer have access to the process count, when it might still want that information in the AMP. It would mean the AMP would fire regardless of a particular process, which might still be something a user might need.
The second point above is already achievable by merely using regex on python, because you know it must trigger (Glances is running, after all). You just can't remove the process count.


For example:
If I wanted to make a request of an API every X seconds, I wouldn't need to match a regex - it'll just fire every X seconds (this would work for connecting to a Plex server on another device, for example).

But if I only want to fire every X seconds if a process is running locally (for example, if I'm running the Plex server on localhost), I would have to do a check on the process in my AMP, which is something Glances already has access to in its feature set. Instead of try/catch the request to the localhost server, I could avoid that by not firing the AMP at all if the process is not running.

Probably not the best example because best practice would be to try/catch API requests regardless of the server location, but I hope it gets the idea across.

**Comment by darylkell** [comment]
> @darylkell : Can you test this version it with your AMP ?

The implementation of your proposal worked for me without issue via windows-curses on my test device. 

I usually use WebUI for Windows machines, due to the curses crash on window resize (separate issue to this, something about catching a SIGWINCH handler, if a very quick online search is right) but obviously couldn't test that yet.

**Comment by nicolargo** [comment]
Additional features to be implemented: https://github.com/nicolargo/glances/issues/1731#issuecomment-691846741

**Comment by darylkell** [comment]
> Implemented in commit [05897a6](https://github.com/nicolargo/glances/commit/05897a61dd0a1da366e2f27231cbf0df19bebfb2) (DEVELOP branch) for the Curses interface.
> 
> @darylkell : Can you test this version it with your AMP ?
> @notFloran : Can you implement this for the WebUI ? (i just add a regex boolean in the JSON data, if it is False, than you should not display the process count and the style should be set to OK)

Just wondering if there's any movement from @notFloran on this, please? The latest Glances version has implemented the change so it's fine in the console, while the web server is still showing a process count (of 0).

**Comment by notFloran** [comment]
I made a PR for the webui https://github.com/nicolargo/glances/pull/1742

**Comment by nicolargo** [comment]
Merged in the develop branch !

Thanks to @notFloran
