### ISSUE TITLE
Regex fix for hide conf key

### ISSUE THREAD

**Issue by darylkell** [nicolargo/glances#1691]
EDIT: Title is incorrect, it's not just for network but obviously for all plugin objects. That's just where I started debugging.
#### Description

Regex in the .conf never matches the hide parameter. 
Probably this passed testing on Linux as most mounts and files are lowercase, but this breaks a lot on Windows. The simplest example is for [fs] where hide=C:\ will never match, because this is made .lower() and on top of that, the not all(j is None...) is asking if the value matched all regexes that were supplied in the conf, when it only needs to match one of the regexes to be hidden (if my guess at the designer's intention is accuarate).

Recommended fix: (glances/plugins/glances_plugin.py)
`def is_hide(self, value, header=""):` function should look like this: 
`return any(j for j in [re.match(i, value) for i in self.get_conf_value('hide', header=header)])` 
instead of this:
`return not all(j is None for j in [re.match(i, value.lower()) for i in self.get_conf_value('hide', header=header)])`

#### Versions

* Glances & psutil (glances -V): Glances v3.1.4.1 with PsUtil v5.7.0
* Operating System (lsb_release -a): Windows 10

**Comment by nicolargo** [comment]
Patched in the DEVELOP branch (see commit aa73127d).

@darylkell Thanks !
