### ISSUE TITLE
Enhancement: RSS for containers

### ISSUE THREAD

**Issue by anjz** [nicolargo/glances#1694]
Hello,

I think it'd be nice to get the `rss` and `cache` stats for containers back. They were removed long time ago because apparently Docker 1.11 removed them. AFAIK this is no longer the case.

I made some changes to put them back and also to display an RSS column in the web UI for container stats, since I believe this is a useful metric to show.

Thanks

**Comment by nicolargo** [comment]
Done in https://github.com/nicolargo/glances/pull/1695
