### ISSUE TITLE
GPU information is incomplete via web

### ISSUE THREAD

**Issue by nick-stocks** [nicolargo/glances#1697]
#### Description

GPU information is incomplete when viewed via the web portal, despite the API returning all the data. It works fine when running it via terminal. It is the same issue regardless of whether glances is running as my user or as a service.

Config located in /etc/glances

Via web:
![image](https://user-images.githubusercontent.com/22432139/88379165-53095680-cd9a-11ea-84b0-dc774d16e0d0.png)

When accessed via http://0.0.0.0:61208/api/3/gpu
`[{"key": "gpu_id", "gpu_id": 0, "name": "GeForce GTX 1050 with Max-Q Design", "mem": 2.5310529929467576, "proc": 0, "temperature": 42}]`

Via terminal
![image](https://user-images.githubusercontent.com/22432139/88379189-61f00900-cd9a-11ea-9035-49e7be46dafc.png)

#### Versions

* Glances v3.1.4.1 with PsUtil v5.7.2
* Operating System
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal

#### Logs

https://pastebin.com/qSd4HmEM

**Comment by nicolargo** [comment]
Hi @nick-stocks 

when i have a look on your log file, i saw that the GPU plugin update the stat to the following value :

```
2020-07-24 10:54:19,553 -- DEBUG -- Plugin gpu update return [{'key': 'gpu_id', 'gpu_id': 0, 'name': 'GeForce GTX 1050 with Max-Q Design', 'mem': 2.5310529929467576, 'proc': 0, 'temperature': 43}] in 0.000403 seconds
```
So the API return this value.

Can you show me a case, in the log file, where proc stats not equal 0 and the API return 0 ?

**Comment by RobOo-Github** [comment]
I have a similar situation.
On the console, the GPU info looks fine:
![Screenshot_2020-09-01_11-23-41](https://user-images.githubusercontent.com/65445647/91832468-ba41e280-ec45-11ea-81db-10c5bd753fa4.png)
The api view on http://127.0.0.1:61208/api/3/gpu is also OK most of the time:
![Screenshot_2020-09-01_11-25-37](https://user-images.githubusercontent.com/65445647/91832618-eeb59e80-ec45-11ea-8733-83575e032db2.png)
but not always-this is where I see N/A after 'Proc' in the web interface:
![Screenshot_2020-09-01_11-33-04](https://user-images.githubusercontent.com/65445647/91833443-ff1a4900-ec46-11ea-99e7-3d22c11e2237.png)

But the web view is sometimes (not always) showing the N/A for 'Proc',
and also, it is never showing the temperature.
![Screenshot_2020-09-01_11-39-39](https://user-images.githubusercontent.com/65445647/91834072-da72a100-ec47-11ea-999e-62944ee171f1.png)

[glances.log](https://github.com/nicolargo/glances/files/5155306/glances.log)

**Comment by nicolargo** [comment]
@notFloran In what case the Web UI display N/A ? When Proc = None ?

**Comment by nicolargo** [comment]
WebUI corrected in the deveop branch thanks to @notFloran
