### ISSUE TITLE
Can't start glances in web server mode on Ubuntu 20.04

### ISSUE THREAD

**Issue by somera** [nicolargo/glances#1701]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Can't start glances in web server mode.

```
$ glances -w
Bottle module not found. Glances cannot start in web server mode.
```

This one solutions isn't working too

```
[So Aug 02][15:02:57][root]@[nuc-mini-server]:[~]# sudo emerge -av dev-python/bottle
sudo: emerge: command not found
[So Aug 02][15:03:47][root]@[nuc-mini-server]:[~]# emerge

Command 'emerge' not found, did you mean:

  command 'esmerge' from deb tstools (1.13~git20151030-3)
  command 'merge' from deb rcs (5.9.4-6)
  command 'fmerge' from deb fhist (1.18-2build1)

Try: apt install <deb name>
```

#### Versions

* Glances & psutil (glances -V):
Glances v3.1.4.1 with PsUtil v5.7.2
Log file: /root/.local/share/glances/glances.log

* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by th0th1** [comment]
why are you trying to use emerge in ubuntu? Emerge is for gentoo...
why don't you try:
`sudo apt-get install python3-bottle`

**Comment by somera** [comment]
> why are you trying to use emerge in ubuntu? Emerge is for gentoo...
> why don't you try:
> `sudo apt-get install python3-bottle`

I think, I followed only this

`https://github.com/nicolargo/glances#pypi-the-simple-way`

installations guide.
