### ISSUE TITLE
API: Incorrect Network (Tx, Rx, Cx values)

### ISSUE THREAD

**Issue by mkanet** [nicolargo/glances#1704]
#### Description

I'm grabbing Tx, Rx,Cx values from the below endpoint.  However, I'm unsure if these values are in bits, kilobits, or megabits per second.

http://192.168.1.2:61208/api/3/network

If I presume these values are ALWAYS in bits per second, the values are wrong (not even close).

On the Web Interface, Rx and Tx are correct; however, they dynamically switch between Kbps to Mbps values.

I need a way to persistently return correct bits/second, Kbit/second, or Mbit/sec Tx, Rx, Cx values.

#### Versions

* Glances v3.1.4.1, PsUtil v5.7.0, Python 3.7
* Windows 10 Version 2004

**Comment by nicolargo** [comment]
Hi @mkanet 

the TC, Rx and Cx are in bytes / time_since_update.

For example:

If the API return :

```
{"time_since_update": 20.3142728805542, "cx": 2305153, "is_up": true, "key": "interface_name", "speed": 1048576000, "tx": 248281, "cumulative_rx": 78520107725, "rx": 2056872, "cumulative_cx": 97365276996, "cumulative_tx": 18845169271, "interface_name": "enp0s31f6"}
```

The received bitrate is = rx / time_since_update = 2056872 / 20.3142728805542 = 101252 KB/s

**Comment by mkanet** [comment]
@nicolargo Thank you so much for explaining!  Do I also need to do the same kind of calculation for "DiskIO" read and write bitrates?

If the API return:
```
[
    {
        "time_since_update": 15.662084341049194,
        "disk_name": "PhysicalDrive0",
        "read_count": 8,
        "write_count": 361,
        "read_bytes": 17408,
        "write_bytes": 2310144,
        "key": "disk_name"
    }
]
```
If I need to calculate PhysicalDrive0 read bitrate (**MB/sec**) ... Is the below calculation correct?

PhysicalDrive0 read bitrate (**MB/sec**) = (read_bytes / time_since_update) * 1000000 = (17408 / 15.662084341049194) * 1000000

Thanks again for all your help!

**Comment by nicolargo** [comment]
Yes, every time the time_since_update is available you should use it to compute the rate.

You are welcome :)

**Comment by mkanet** [comment]
Great. I got the answers I needed.

**Comment by danielstroehmann** [comment]
> Hi @mkanet
> 
> the TC, Rx and Cx are in bytes / time_since_update.
> 
> For example:
> 
> If the API return :
> 
> ```
> {"time_since_update": 20.3142728805542, "cx": 2305153, "is_up": true, "key": "interface_name", "speed": 1048576000, "tx": 248281, "cumulative_rx": 78520107725, "rx": 2056872, "cumulative_cx": 97365276996, "cumulative_tx": 18845169271, "interface_name": "enp0s31f6"}
> ```
> 
> The received bitrate is = rx / time_since_update = 2056872 / 20.3142728805542 = 101252 KB/s

Are you sure about your statement? if rx/tx is in bytes then your above calculation results in 101252 B/s and not KB/s. Typo?

Again I like to raise the question if values truely are in Bytes and not Bits.

Cheers & T(H)X,
Daniel.

**Comment by nicolargo** [comment]
Sorry type, you should read B/s and not KB/s.

The values are in Bytes (= 8 bits)

**Comment by danielstroehmann** [comment]
> Sorry type, you should read B/s and not KB/s.
> 
> The values are in Bytes (= 8 bits)

Thanks for clarification. I experimented and came to the same conclusion. 👍
