### ISSUE TITLE
merge conflict in manpage?

### ISSUE THREAD

**Issue by steve-thousand** [nicolargo/glances#1712]
Minor problem, but the [man page](https://github.com/nicolargo/glances/blob/43df8a887ade2727533a52e1d12580d25dd4b56c/docs/man/glances.1) appears to start with a merge conflict

```
<<<<<<< HEAD
.TH "GLANCES" "1" "Aug 19, 2020" "3.1.5" "Glances"
=======
.TH "GLANCES" "1" "Mar 25, 2020" "3.1.4.1" "Glances"
>>>>>>> master
```

**Comment by nicolargo** [comment]
Thanks !

Corrected in develop and master branch.
