### ISSUE TITLE
Error 501: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.

### ISSUE THREAD

**Issue by codecakes** [nicolargo/glances#1713]
Similar to #1343 but bottle is installed

<img width="709" alt="image" src="https://user-images.githubusercontent.com/7066977/91274937-17005180-e79d-11ea-84cf-efa2938c0222.png">

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.
pip3 install -u 'glances[all]'
```Successfully installed bernhard-0.2.6 bottle-0.12.18 docker-4.3.1 future-0.18.2 glances-3.1.5 ifaddr-0.1.7 pbkdf2-1.3 ply-3.11 protobuf-3.13.0 psutil-5.7.2 py-cpuinfo-7.0.0 py3nvml-0.2.6 pySMART.smartx-0.3.10 pyasn1-0.4.8 pycryptodomex-3.9.8 pygal-2.4.0 pymdstat-0.4.2 pysmi-0.3.4 pysnmp-4.4.12 pystache-0.5.4 scandir-1.10.0 sparklines-0.4.2 websocket-client-0.57.0 wifi-0.3.8 xmltodict-0.12.0 zeroconf-0.28.1```

#### Versions

* Glances & psutil (glances -V): Glances v3.1.5 with PsUtil v5.7.2
* Operating System (lsb_release -a): OS X 10.15.6

#### Logs
https://pastebin.com/gpTYEZ3r

**Comment by nicolargo** [comment]
Hi @codecakes 

what is the Bottle version installed on your system ?

```
pip freeze | grep bottle
```

?

**Comment by codecakes** [comment]
He @nicolargo 

`bottle==0.12.18`

**Comment by nicolargo** [comment]
Tested on my side with Bottle 0.12.18 and no issue on my Ubuntu OS...

Any others Mac OS users with this issue ?

**Comment by codecakes** [comment]
@nicolargo can you tell me what is the first route it is trying to get ?  I can inspect

**Comment by nicolargo** [comment]
You can try to get the following route via a curl command: **/api/3/all**

See all Glances API routes here: https://github.com/nicolargo/glances/wiki/The-Glances-RESTFULL-JSON-API#get-api3all

**Comment by codecakes** [comment]
```html5
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 501</p>
        <p>Message: Unsupported method ('GET').</p>
        <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
    </body>
</html>
```

**Comment by nicolargo** [comment]
@codecakes  Any news concerning the issue ?

**Comment by codecakes** [comment]
@nicolargo im gona look at this one next sat. haven't been able to look at it;

**Comment by act10** [comment]
I had a similar error if I ran in server mode and connected to the port 61209
fixed in start script
glances -w
and connect to  :61208

**Comment by ThomasCr** [comment]
I have the same error, but I installed glances from ubuntu package repository
```
$ apt policy glances
glances:
  Installed: 3.2.4.2+dfsg-1
  Candidate: 3.2.4.2+dfsg-1
  Version table:
 *** 3.2.4.2+dfsg-1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```
and modified service file to run not localhst only:

```
$ cat /etc/systemd/system/glances.service.d/override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/glances -s -w -p 61208
#ExecStart=/usr/bin/glances -s -w -B 127.0.0.1 -p 61208

$ systemctl status glances.service 
● glances.service - Glances
     Loaded: loaded (/lib/systemd/system/glances.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/glances.service.d
             └─override.conf
     Active: active (running) since Fri 2022-09-30 22:53:05 UTC; 14h ago
       Docs: man:glances(1)
             https://github.com/nicolargo/glances
   Main PID: 9813 (glances)
      Tasks: 1 (limit: 38076)
     Memory: 26.4M
        CPU: 15.890s
     CGroup: /system.slice/glances.service
             └─9813 /usr/bin/python3 /usr/bin/glances -s -w -p 61208

Sep 30 22:53:05 zentrale2 systemd[1]: Started Glances.
```

It makes no difference if I access glances with apache reverse proxy or direct - I get the 501 message:

> Unsupported method ('GET').
> 
> Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.

Any update to this issue?

**Comment by KingPin** [comment]
@ThomasCr did you by any chance resolve this issue? I'm having this issue currently on Debian bullseye with apt install glances.

**Comment by RazCrimson** [comment]
@nicolargo 

Does glances currently support running both XML-RPC Server mode and the Web UI mode on the same ports?

**Comment by nicolargo** [comment]
Nope...

**Comment by RazCrimson** [comment]
A very fast reply :)

@KingPin 
One solution if you want both Web API ( `-w`) and XML-RPC (`-s`) to be run at the same time, would be to start 2 glances instances (or systemd services) and use them

Here is an example to make a custom systemd service: https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

**Comment by RazCrimson** [comment]
Closing this as glances doesn't support both Web API & XMP-RPC at the same time.

Issue for that is tracked here: https://github.com/nicolargo/glances/issues/995
