### ISSUE TITLE
need to update doc on how to install ... use pip3 and not pip

### ISSUE THREAD

**Issue by scottstensland** [nicolargo/glances#1717]
You should update your doc to suggest install using

 pip3 and not pip

especially on linux as things like Ubuntu 20.04 only comes with python3 and no python2

```
sudo -H pip3 install glances
```

Glances v3.1.5 with PsUtil v5.7.2
Log file: /home/olga/.local/share/glances/glances.log

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by nicolargo** [comment]
Hi @scottstensland 

there is no symbolic link between pip3 and pip on Ubuntu OS ?

Nicolas

**Comment by scottstensland** [comment]
on Ubuntu 20.04 I just issued 

```
sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
```

which does the trick ... for details see https://stackoverflow.com/questions/44455001/how-to-change-pip3-command-to-be-pip
