### ISSUE TITLE
Ubuntu / KDE Neon 20.04: E: Unable to locate package python-pip

### ISSUE THREAD

**Issue by darkguy2008** [nicolargo/glances#1719]
Ref: https://stackoverflow.com/questions/61981156/unable-to-locate-package-python-pip-ubuntu-20-04
```
sudo add-apt-repository universe
sudo apt update 
sudo apt install python2
curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
sudo python2 get-pip.py
curl -L https://bit.ly/glances > script.sh
chmod +x script.sh
```
Edit the `script.sh` file, replace line 60 like this:
```
    # do_with_root apt-get install -y --force-yes python-pip python-dev gcc lm-sensors wireless-tools
      do_with_root apt-get install -y --force-yes python-dev gcc lm-sensors wireless-tools
```
Run the install script
```
./script.sh
```
Voilá!

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glancesautoinstall/issues/41

**Comment by maravento** [comment]
the solution is replace:

`python-dev` with `python-dev-is-python3`
`python-pip`with `python3-pip`

Tested in Ubuntu 22.04.2 x64
