### ISSUE TITLE
web ui of glances is not coming

### ISSUE THREAD

**Issue by sysadmin-imran** [nicolargo/glances#1721]
hi there,

i have just deployed glances app as a docker container, but web-ui is not coming on either of ports 61208 or 61209.

#### Description
this is step i use to deploy the container.

docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances

Could you guys check logs of this container(provided below in log section) and why web-ui is not coming and how to resolve it.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.6_b1 with PsUtil v5.7.2 (its inside docker container execution)
* Operating System (lsb_release -a): No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Docker Version (docker version):

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

#### Logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/6328c71fe374c19ecc3df6b7ab5528ffaaca8e8fcdb000c8aa270b9368ccbb7f/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/glances/__main__.py", line 29, in <module>
    glances.main()
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 145, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/__init__.py", line 110, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.8/dist-packages/glances/webserver.py", line 41, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.8/dist-packages/glances/stats.py", line 234, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.8/dist-packages/glances/plugins/glances_plugin.py", line 925, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/glances/plugins/glances_plugin.py", line 935, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/glances/plugins/glances_docker.py", line 221, in update
    container_stats['Image'] = container.image.tags
  File "/usr/local/lib/python3.8/dist-packages/docker/models/containers.py", line 40, in image
    return self.client.images.get(image_id.split(':')[1])
  File "/usr/local/lib/python3.8/dist-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 245, in inspect_image
    return self._result(
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: 6328c71fe374c19ecc3df6b7ab5528ffaaca8e8fcdb000c8aa270b9368ccbb7f: No such image: sha256:6328c71fe374c19ecc3df6b7ab5528ffaaca8e8fcdb000c8aa270b9368ccbb7f")
```
Please feel free to ask anything related to this issue.
Quick response will be appreciated.
Thanks & regards

**Comment by nicolargo** [comment]
Just tested on my computer and every thing is OK...

**Comment by sysadmin-imran** [comment]
yes its working, tried on few other ubuntu  18.04 version systems. Wonder why its not working on my local laptop system, even though it worked perfectly on a VM in that same laptop.
Anyways thanks for your help.

Just one thing i wanna know, does glances web-ui on port 61208(Glances Web User Interface started on http://0.0.0.0:61208/) support username and password authentication, if not till know, it would be wonderful addition to this great product(if it's applicable to this application)

**Comment by danielstroehmann** [comment]
> yes its working, tried on few other ubuntu 18.04 version systems. Wonder why its not working on my local laptop system, even though it worked perfectly on a VM in that same laptop.
> Anyways thanks for your help.
> 
> Just one thing i wanna know, does glances web-ui on port 61208(Glances Web User Interface started on http://0.0.0.0:61208/) support username and password authentication, if not till know, it would be wonderful addition to this great product(if it's applicable to this application)

Don’t know if authentification is Supported directly, I didn’t find any indication of it. Here is how I circumvent the problem: restricted  access to 61208 and put an nginx in front of glances with an internal port redirect, https and basic auth. Works like a charme.

**Comment by sysadmin-imran** [comment]
thanks for the hint @danielstroehmann 
i have used this [https://hub.docker.com/r/beevelop/nginx-basic-auth/](url) docker image for basic authentication.
```
# generate .htpassword
htpasswd -c /home/osboxes/.htpasswd admin

# Deploy Glances app
sudo docker run -d --restart="always"  -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --name glances docker.io/nicolargo/glances

# Deploy nginx-auth
sudo docker run -d -e HTPASSWD='admin:$apr1$VPhg24Eg$xBbkV5f/2862j2V7F/weU.' -e FORWARD_PORT=61208 -e FORWARD_HOST=glances --link glances:glances -p 8080:80 --name glances-auth beevelop/nginx-basic-auth
```

**Comment by nicolargo** [comment]
You can also used the builtin Glances password protection for WebU. Read ==> https://glances.readthedocs.io/en/stable/quickstart.html#client-server-mode

**Comment by nicolargo** [comment]
New procedure in the doc:

https://glances.readthedocs.io/en/stable/quickstart.html#how-to-protect-your-server-or-web-server-with-a-login-password
