### ISSUE TITLE
Do not shorten container names

### ISSUE THREAD

**Issue by aboettger-tuhh** [nicolargo/glances#1723]
#### Description

I would like to ask that the names of the containers not be cut off. I have relatively long names and so I can't tell which container it is.

#### Versions

* Glances v2.11.1 with psutil v5.6.3
* Ubuntu 18.04.5 LTS

**Comment by nicolargo** [comment]
A new configuration key has been added in the Glances configuration file:

```
[docker]
# Define the maximum docker size name (default is 20 chars)
max_name_size=20
```

Will be release in Glances 3.1.6 but implementation already available in the develop branch.
