### ISSUE TITLE
[FR] AMP-like addons that  just show the output of a shell command

### ISSUE THREAD

**Issue by NightMachinary** [nicolargo/glances#1731]
I want to display some additional info in glances, e.g., the date in Shamsi format. I am currently using this as a workaround:
```
[amp_msg]
# Use the default AMP (no dedicated AMP Python script)
enable=true
regex=.*
refresh=60
one_line=true
command=brishz.dash datej
```

But It is ugly, as it has the completely extra  part ```Msg               542```:
![image](https://user-images.githubusercontent.com/36224762/93017360-40aeda80-f5dd-11ea-9f91-c1e1847e3fbc.png)

It'd be good to either add an option to disable the boilerplate for a particular AMP, or just have another addon mechanism that periodically runs shell commands.

**Comment by darylkell** [comment]
This is similar (if not identical to) https://github.com/nicolargo/glances/issues/1690

**Comment by NightMachinary** [comment]
[**@darylkell**](https://github.com/darylkell) commented on [Sep 14, 2020, 6:46 AM GMT+4:30](https://github.com/nicolargo/glances/issues/1731#issuecomment-691772569 "2020-09-14T02:16:55Z - Replied by Github Reply Comments"):
> This is similar (if not identical to) [#1690](https://github.com/nicolargo/glances/issues/1690)

Yes, that is pretty much what I want. Can you disable the `AMP_Name            ` thing, too, when no regex is present? It takes a lot of space and has no use (The user can print that themselves if they want to.).
![image](https://user-images.githubusercontent.com/36224762/93051324-891bd600-f679-11ea-8cb2-771a404fdc37.png)

It'd also be nice if this was added to the docs.

Another issue: AMP doesn't support ANSI color codes:
![image](https://user-images.githubusercontent.com/36224762/93051735-2d9e1800-f67a-11ea-8f67-30ec461e0bfd.png)

**Comment by nicolargo** [comment]
I close this issue an add your previous comment as a feature request in https://github.com/nicolargo/glances/issues/1690
