### ISSUE TITLE
improve docker info layout

### ISSUE THREAD

**Issue by oppianmatt** [nicolargo/glances#1732]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Viewing the running docker containers on a machine that is part of a swarm is not that useful. Left column is full of gibberish from the service names which are the format (project_service_num.num.longhash.longhash) and glances shows the right side of the docker name. Right column just shows command which can often be the same as common pattern of a common init script and so can't tell what docker container/service it is.

Sorting doesn't change the order of docker containers.

Also lots of unused space on the side where it could have expanded some of the columns to see more info.

#### Versions

* Glances v3.1.5 with PsUtil v5.7.2
* linux ubuntu

#### Logs

![image](https://user-images.githubusercontent.com/48596/93201547-3f9abc00-f749-11ea-975a-dd400f8fd47b.png)

**Comment by nicolargo** [comment]
In the develop branch, a new configuration key has been added to define the maximum length of container's names.

See https://github.com/nicolargo/glances/issues/1723 for detail.

Perhaps, it will be nice to add others options like:
1) do not cut the docker name (display the left part of the name)
2) hide some columns (like the Command)

What do you think ?
