### ISSUE TITLE
Allow embedded AMP python script to be placed in a configurable location

### ISSUE THREAD

**Issue by ericbroda** [nicolargo/glances#1734]
This is a request for new functionality.

I would like to have the flexibility to access an embedded AMP (glances_*.py) in a directory specified in the glances configuration.  This addresses a relatively simple problem in that wish to segregate my customizations (ie. AMP) from the broader glances source/installation directory.  This, effectively, will allow the decoupling of customizations from the original source tree and implementation design for AMPs and ultimately make it simpler to setup and establish new embedded AMPs.

**Comment by nicolargo** [comment]
Hi @ericbroda 

I have made a first implementation in the https://github.com/nicolargo/glances/tree/issue1734 branch.

Example:

```
[amp_foo]
enable=true
plugin_path=/tmp
```

Put your glances_foo.py in the /tmp folder.

Can you please test it ?

Thanks !

**Comment by ericbroda** [comment]
Works for me.  Thanks!
