### ISSUE TITLE
Refactor alias configuration and allow alias for fs devices

### ISSUE THREAD

**Issue by boppy** [nicolargo/glances#1735]
#### Description

Feature Request (priority: super-low): **It would be nice if one could add aliases for fs devices.** Currently (on the web) there is something like that, what is not easy to read nor understand (FYI: I'm running inside docker).

```
FILE SYS	Used	Total
/rootfs (/dev/nvme1n1p1)	5.19G	78.2G
_tfs/boot (/dev/nvme1n1p2)	133M	1008M
_/var/app (/dev/sda3)		93.3M	2.00T
_r/backup (/dev/sda2)		457G	1.43T
_tfs/home (/dev/sda1)		256M	1.97T
_var/data (/dev/nvme0n1p1)	213G	445G
_/var/dev (/dev/nvme0n1p2)	949M	31.9G
_r/docker (/dev/nvme1n1p4)	28.9G	366G
_olv.conf (/dev/nvme1n1p4)	28.9G	366G
_hostname (/dev/nvme1n1p4)	28.9G	366G
_tc/hosts (/dev/nvme1n1p4)	28.9G	366G
```

Additionally to having aliases it would also be great to have an allow-list not only a hide-list and/or (even better) a switch to only show fs's that are aliased.

Since I did not find any "deeper-than-one" level of config anywhere, config might be like:

```
[fs]
show=.*nvme.*

# colon-separated (<path>:<alias>) + comma-separated
alias=/foo/bar/baz:personal,/bar/foo:backup

# Set this to True if only aliased fs should be shown
show_aliased_only=True
```

*Would like to provide some code, but as soon as I open `py`-files my brain issues some kind of kernel panic...* :-D

**Comment by nicolargo** [comment]
Partially implemented in the develop branch for the "show" feature.

For the other one, as alias are already used in others plugins (disk...), we need to refactor the way alias are configure in the Glances conf file. Your proposal is better than the actual one. I propose (in Glances v4) to move all alias from:

    foo_alias=value

to 

    alias=foo:value

**Comment by nicolargo** [comment]
Available in the devel branch.

Will be release in Glances 4.0.0.
