### ISSUE TITLE
Terminal UI: Colorscheme hard to read with light terminal background

### ISSUE THREAD

**Issue by cherti** [nicolargo/glances#1737]
#### Description

Apparently glances colors most text in explicit white instead in the specified terminal foreground color, making it very hard to read on light-background-Terminals due to very small contrast as it can be seen in the picture below.

![glances](https://user-images.githubusercontent.com/6452205/93723698-28245e80-fba1-11ea-8d51-a7af13da5be7.png)

#### Versions

Glances v3.1.5 with PsUtil v5.7.2

**Comment by nicolargo** [comment]
Please use the **--theme-white** option.
