### ISSUE TITLE
RIP Alpine?

### ISSUE THREAD

**Issue by auanasgheps** [nicolargo/glances#1741]
Hi,
I was happily using` glances:latest-alpine` when I discovered it is gone.
Alpine size was 100ish MB compared to the current latest which is 500ish MB.

Any reason for this change?

**Comment by marcinozga** [comment]
Dockerfile is still here https://github.com/nicolargo/glances/blob/6c1d7316dffabb1f92ce4092e47c59b22a4bab01/docker-files/devel-alpine/Dockerfile
I got the unwelcome surprise today too when I had to rebuild the container. Debian/Ubuntu image is just bloated.

**Comment by BlackDark** [comment]
![image](https://user-images.githubusercontent.com/9947112/95375712-48158b00-08e0-11eb-903b-f149106a8acd.png)

Feel free to provide a alpine based image which supports multiple architectures.

**Comment by auanasgheps** [comment]
Alpine is great. Just make it available as it was before to x86-64. I'm not asking for new architectures.

**Comment by marcinozga** [comment]
That dev tag image is mia too.

`$ docker pull nicolargo/glances:dev
dev: Pulling from nicolargo/glances
d121f8d1c412: Waiting 
ca572574cc82: Waiting 
38ead5def216: Waiting 
d66d8ce1705e: Waiting 
922f4bd7bc61: Waiting 
a601c6f52d00: Waiting 
707ab0248f7b: Waiting 
fc3f1c7a3536: Waiting 
error pulling image configuration: unknown blob`

**Comment by nicolargo** [comment]
@auanasgheps i just add the "old" Dockerfile (https://github.com/nicolargo/glances/commit/f600209757ac0665e095ded976a5e8e544141443) for Alpine and re-enable the build via Docker hub. It will be only availble for x86-64 architecture.

docker pull nicolargo/glances:latest-alpine

![image](https://user-images.githubusercontent.com/776747/95675928-0b38e500-0bbb-11eb-9167-f7fa63e2c0b4.png)

**Comment by auanasgheps** [comment]
It doesn't work:
`/bin/sh: python: not found`

Recalls #1720, that's ironic since was opened by me as well

**Comment by nicolargo** [comment]
Should be corrected by latest commit on the develop branch.

Image available for testing on https://hub.docker.com/repository/docker/nicolargo/glances
