### ISSUE TITLE
Alpine image is broken

### ISSUE THREAD

**Issue by marcinozga** [nicolargo/glances#1744]
There's a regression in alpine image. It was fixed in https://github.com/nicolargo/glances/commit/ed951421045eedec3eade18e1646677f03623b6c before.

**Comment by trolley** [comment]
Same issue here: `/bin/sh: python` not found over and over

**Comment by nicolargo** [comment]
Should be corrected by latest commit on the develop branch.

Image available for testing on https://hub.docker.com/repository/docker/nicolargo/glances
