### ISSUE TITLE
Python@3.8's  Openssl  Problem

### ISSUE THREAD

**Issue by haotianmichael** [nicolargo/glances#1745]
## Description
I installed glances using `brew install glances`. 
But once tapped `glances` on shell, it emitted:
> ImportError: dlopen(/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ssl.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

It seems to be openssl's version problem still, I tried to change $PATH but it didn't work.  I don't know how to fix it. My machine has several versions of python and its dependencies like openssl, which exists in `/usr/local/Cellar/`, `use/bin/` and `/usr/local/opt/`.  But I really don't  know the calling  connection.  Can anyone teach me how to manage them, Please?

#### Versions
* Glances v3.1.4.1 with PsUtil v5.7.0
* Darwin Kernel Version 19.6.0

#### Logs
```
----------:  Search glances.conf file in /usr/local/etc/glances/glances.conf
WARNING:  PsUtil can not grab processes io_counters ('Process' object has no attribute 'io_counters')
```
[glances.log](https://github.com/nicolargo/glances/files/5385650/glances.log)

**Comment by nicolargo** [comment]
It looks like a OpenSSL packaging issue ==> https://github.com/openssl/openssl/issues/13168
