### ISSUE TITLE
[Feature Request] Filter Docker containers

### ISSUE THREAD

**Issue by Generator** [nicolargo/glances#1748]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description
When running several of containers, TASKS get smaller, some containers don't need to be monitored all the time, excluding them from showing will improve TASKS monitor.

Ability to hide or show only selected containers. 
**Examples:** 
Hide selected container: `hide=nginx,portainer,endlessh`
Show selected containers: `Containers=All` (default, show all running conainers)  
`Containers=php,Apache,Debian` (show only selected containers)

**Comment by nicolargo** [comment]
Implemented in the latest commit in the develop branch:

You should use it by using the following syntax in the glances.conf file:

```
    [docker]
    ...
    # Only show specific containers (comma separeted list of container name or regular expression)
    # Comment this line to display all containers (default configuration)
    show=thiscontainer,andthisone,andthoses.*
    # Hide some containers (comma separeted list of container name or regular expression)
    # Comment this line to display all containers (default configuration)
    hide=donotshowthisone,andthoses.*
```

Note:
- i replace Containers by show
- if you want to display all containers, just comment thoses two lines

**Comment by nicolargo** [comment]
@Generator Can you test the feature on your side ?

**Comment by Generator** [comment]
Maybe i'm doing something wrong, but i'm not getting docker plugin to work with virtualenv (`pip install -i https://test.pypi.org/simple/ Glances`)

glances.conf :  
```
[docker]
disable=False
# Only show specific containers (comma separeted list of container name or regular expression)
# Comment this line to display all containers (default configuration)
# show=foobar
# Hide some containers (comma separeted list of container name or regular expression)
# Comment this line to display all containers (default configuration)
hide=nginx,php,endlessh
# Define the maximum docker size name (default is 20 chars)
max_name_size=20
#cpu_careful=50
# Thresholds for CPU and MEM (in %)
cpu_warning=70
cpu_critical=90
mem_careful=20
mem_warning=50
mem_critical=70
#
# Per container thresholds
#containername_cpu_careful=10
#containername_cpu_warning=20
#containername_cpu_critical=30
#
# By default, Glances only display running containers
# Set the following key to True to display all containers
all=False
```

Log: [glances-pip.log](https://github.com/nicolargo/glances/files/5543125/glances-pip.log)
