### ISSUE TITLE
Request: Version tag for docker image

### ISSUE THREAD

**Issue by michaelblight** [nicolargo/glances#1754]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Would it be possible for you to also tag the latest image with the version number? I prefer to pull by the specific version rather than latest. I then have a process which notifies me of changes to the major/minor version so I can do a planned upgrade.

#### Versions

* Glances & psutil (glances -V): Glances v3.1.6_b1 with PsUtil v5.7.2
* Operating System (lsb_release -a): Ubuntu 18.04.5

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by BlackDark** [comment]
I prepared the github workflow to build the versions on releases. So it should automatically release a tagged version as soon as we have a version release in github :)
