### ISSUE TITLE
Glances auto-update script is too intrusive

### ISSUE THREAD

**Issue by stdedos** [nicolargo/glances#1755]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

For a bug: 

The auto-install/update script, while mostly welcome, I think it pushes too much into the system in question.
I think it is too much to *force* `apt-get update -y --force-yes`, *and* `sudo pip install --upgrade pip`.

I understand where you are coming from, and why you might want to do this, but it is too much.
People might be withholding updates for a reason, and specifically for the `sudo pip install --upgrade pip`, I think at sometime it was even a recommendation to *absolutely not* update the system pip version (I have seen such bug).

Please consider masking this approach behind an explicitly passed flag.

#### Versions

* Glances & psutil (glances -V):
* Operating System (lsb_release -a):

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Done: https://github.com/nicolargo/glancesautoinstall/commit/e03902c3ae54a32fe92c114ebb810b488720ab45
