### ISSUE TITLE
Docker support not built into RPi Docker image

### ISSUE THREAD

**Issue by kenlasko** [nicolargo/glances#1757]
#### Description
While the standard Linux images seem to support Docker out of the box, the RPi Docker image does not. I have to run **pip install docker** from within the container and restart it to gain insight into Docker containers.  It would be helpful to have this installed as part of the base image.

#### Versions
Latest dev version for RPi

**Comment by nicolargo** [comment]
Hi @kenlasko ,

in fact, only the master branch of the standard Linux image install all the dependencies (see linehttps://github.com/nicolargo/glances/blob/develop/docker-files/Dockerfile#L33).

The develop version (as the RPI one) only install mandatory deps (see https://github.com/nicolargo/glances/blob/develop/docker-files/Dockerfile#L29-L30).

Need contributors to build a full dev images for standard Linux and RPi.

Nicolas

**Comment by eifinger** [comment]
If I didn't oversee some complexity this issue should be fixed by my PR. I just included the contents of optiona-requirements.txt in the Dockerfile. I tested this on Linux/amd64 and a rpi0w.

Let me know if I should change something.

**Comment by BlackDark** [comment]
Tried to build the dev image with the optional requirements but this kinda failed some builds: https://github.com/BlackDark/glances/runs/1450407761?check_suite_focus=true#step:6:3496

Not sure why they failed but didn't had time to investigate further.
Is the dev branch working for all different architectures? @nicolargo maybe you know.

Will provide a PR for speeding up the builds as soon as i have some time.
