### ISSUE TITLE
Installed with pip3 --> "bash: /usr/bin/glances: No such file or directory"

### ISSUE THREAD

**Issue by Niemand112233** [nicolargo/glances#1771]
Hi,
first I installed it with apt install glances on a Ubuntu 20.04 and it worked. Then I saw that it is quite outdated and removed it by "apt remove glances" and reinstalled it with "pip3 install glances[all]". The tab-autofill tells me "glances" is installed, but when I try to start it I get "bash: /usr/bin/glances: No such file or directory"

**Comment by nicolargo** [comment]
Can you try to run glances with:

`/usr/local/bin/glances 
`

**Comment by pankti11** [comment]
Same thing happening for me. Its not in /usr/local/bin/glances either

**Comment by Hierosme** [comment]
Hello,

If i understand well:
```
pip3 install glances[all]
```
will not install anything in ``/usr/local/`` that because only **root** can do it. generally in case of **pip** permission error pip use the **user** $HOME directory, then the use have to configure the $PATH env variable.

I sugess to try
```
sudo pip3 install glances[all]
```

**Comment by Hierosme** [comment]
I just have make the test, 
```
 └─ $ ▶ pip install glances[all]
....
└─ $ ▶ ls $HOME/.local/bin/glances 
-rwxr-xr-x 1 tuxa tuxa 205 févr. 16 17:23 /home/USER_NAME/.local/bin/glances
```

Then use 
```
sudo pip3 install glances[all]
```

if you want it to ``/usr/bin/glances``

**Comment by RazCrimson** [comment]
Closing as a solution is already provided.
