### ISSUE TITLE
Unable to connect to Influxdb 2.0

### ISSUE THREAD

**Issue by ROODAY** [nicolargo/glances#1776]
#### Description

I followed the [docs for connecting to influx](https://glances.readthedocs.io/en/stable/gw/influxdb.html) but whenever I try to run `glances --export influxdb` I get `Cannot connect to InfluxDB database 'glances' (401: {"code":"unauthorized","message":"Unauthorized"})`. I had similar authentication issues connecting Influxdb to Grafana, and was only able to fix it by using the Flux connection options that used Organization and Bucket instead of username and database. Is there a way to use similar connection options for glances? This is my current conf file:
```
[influxdb]
host=localhost
port=8086
protocol=http
user=ROODAY
password=**************
db=glances
```

#### Versions

* Glances & psutil (glances -V): Glances v3.1.5 with PsUtil v5.8.0
* Operating System (lsb_release -a): Ubuntu 20.04.1 LTS

#### Logs

```
2020-12-22 16:53:04,127 -- INFO -- Start Glances 3.1.5
2020-12-22 16:53:04,127 -- INFO -- CPython 3.8.5 and psutil 5.8.0 detected
2020-12-22 16:53:04,129 -- INFO -- Search glances.conf file in /home/rooday/.config/glances/glances.conf
2020-12-22 16:53:04,129 -- INFO -- Read configuration file '/home/rooday/.config/glances/glances.conf'
2020-12-22 16:53:04,133 -- INFO -- Start GlancesStandalone mode
2020-12-22 16:53:04,434 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2020-12-22 16:53:04,608 -- CRITICAL -- Cannot connect to InfluxDB database 'glances' (401: {"code":"unauthorized","message":"Unauthorized"})
```

**Comment by paularmstrong** [comment]
InfluxDB v2 requires using authentication `token`, `organization`, and `bucket` arguments. The influxdb API integration within glances will need an update to be able to use it first.

**Comment by nicolargo** [comment]
Quick analyse concerning the implementation of the InfluxDB 2 API:
- the "old" client (https://github.com/influxdata/influxdb-python) is only compatible with InfluxDB < 1.8 (before the Flux implementation)
- the "new" client (https://github.com/influxdata/influxdb-client-python) can be used for InfluxDB 1.8+ or 2.x
- the "new" client need the following information: bucket name, token, org ([see this post](https://medium.com/@dganais/getting-started-with-python-and-influxdb-v2-0-f22e5175aba5) to know how to get the information from an existing InfluxDB 2.x server)

Questions to be taken into account before the development:
- keep the double compatibility API v1 / API v2 ? if yes how to deal with the configuration file (one section ? two section ?)
- Docker environment are available for the new InfluxDB 2 version ==> https://docs.influxdata.com/influxdb/v2.0/get-started/

**Comment by nicolargo** [comment]
@paularmstrong Implementation for the new exporter (called **influxdb2**) done in the develop branch.

Read the doc ==> https://github.com/nicolargo/glances/blob/develop/docs/gw/influxdb.rst#influxdb-v2-from-influxdb-v18xflux-and-influxdb-v2x

Note: you need to install the https://pypi.org/project/influxdb-client/ InfluxDB client.

Tested with InfluxDB 2.0.3.
