### ISSUE TITLE
Error while initializing the quicklook plugin (py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.)

### ISSUE THREAD

**Issue by cskksdfklpz** [nicolargo/glances#1784]
**Describe the bug**

```
> glances
Error while initializing the quicklook plugin (py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.)
```

**To Reproduce**
1. Open iTerm 2
2. Type glances

**Expected behavior**
The quicklook plugin should have worked.

**Screenshots**

<img width="1430" alt="Screen Shot 2021-01-01 at 10 39 35 PM" src="https://user-images.githubusercontent.com/17721563/103450297-3b57c780-4c82-11eb-9ba4-02595b63a2b1.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (Apple M1 chip)
 - Glances Version [output of glances -V] (Glances v3.1.5 with PsUtil v5.7.2)

**Additional context**

**Comment by nicolargo** [comment]
I will have  a look. As a workaround you can try to disable the quucklook plugin.

I am interested to know if Glances works on a M1 architecture. Let me Know.

**Comment by cskksdfklpz** [comment]
The disable option doesn't work for me

```
> glances --disable-plugin quicklook
Error while initializing the quicklook plugin (py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.)
```

The second command line can be executed without any error. 

```
> python
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cpuinfo import cpuinfo
>>>
```

**Comment by trueb2** [comment]
How was glances installed?

**Comment by cskksdfklpz** [comment]
Using home-brew

```
brew install glances
```

**Comment by trueb2** [comment]
`brew uninstall glances` then `pip install glances` will fix the psutil version that you are using.

**Comment by cskksdfklpz** [comment]
Thank you that worked!
