### ISSUE TITLE
Docker images for different archs

### ISSUE THREAD

**Issue by escoand** [nicolargo/glances#1786]
**Is your feature request related to a problem? Please describe.**
According to https://hub.docker.com/r/nicolargo/glances/tags?page=1&ordering=last_updated is only the `dev` tag available for different architectures. I'm specifically interested in `latest-alpine` for `linux/arm/v6`

**Describe the solution you'd like**
Have not only the `dev` tag for different archs.

**Describe alternatives you've considered**
Currently I'm using the `dev` tag.

**Additional context**

**Comment by escoand** [comment]
@nicolargo As you already have travis integration you could use https://docs.travis-ci.com/user/build-stages/share-docker-image/ as an extension. Your `dev` images are already multi-arch, can't you copy the workflow?

**Comment by nicolargo** [comment]
@escoand the CI pipeline used to generate Docker images is based on Github, not Travis (see https://github.com/nicolargo/glances/blob/develop/.github/workflows/main.yml).

@BlackDark Can you have a look on the @escoand request ?

Thanks !

**Comment by BlackDark** [comment]
Will do

**Comment by BlackDark** [comment]
@escoand @nicolargo 
What do we want to achieve with the alpine image:
- should be as minimal as possible? Problem is that this will make it incompatible with multiple additional plugins which could be installed with glances
- Include all dependencies needed for installing the optional dependencies and be able to use them?

**Comment by escoand** [comment]
@BlackDark I would like to have it like https://github.com/nicolargo/glances/blob/develop/docker-files/Dockerfile but without all the gcc thingy...

**Comment by BlackDark** [comment]
Currently testing the image sizes between debian based and alpine based with all plugins installed.
So far i think it wouldn't be much benefit using alpine for this case. Image does not differ much and python is not the best solution with alpine base [some article](https://pythonspeed.com/articles/alpine-docker-python/).

So i think i would stay with the default image. Could try to remove unnecessary packages like gcc after successful builds maybe.

Prod image based on debian:
![image](https://user-images.githubusercontent.com/9947112/104811438-b03b0d80-57fb-11eb-9091-ef5927d4e6e3.png)

Try including all deps for alpine and install:
![image](https://user-images.githubusercontent.com/9947112/104811442-c0eb8380-57fb-11eb-83a4-ab0e17c5b21a.png)

**Comment by escoand** [comment]
I've no strong feelings against debian. My request was just to have a small stable image for my productive usecase. So I'm completly fine with your result so far.

**Comment by escoand** [comment]
@BlackDark Thanks.

**Comment by BlackDark** [comment]
Hey @escoand, made some progress in reducing the image sizes :)

Would you like to test both? You can find those under my user in docker hub `blackdark93/glances`
![image](https://user-images.githubusercontent.com/9947112/104817626-ad074800-5822-11eb-83f0-85cb5c5655d6.png)

**Comment by escoand** [comment]
I'm quite impressed by the final size. Fantastic and both are working with my simple setup.

**Comment by RazCrimson** [comment]
Closing as we have multi-arch images now.
