### ISSUE TITLE
Pressing Q to get rid of irq not working

### ISSUE THREAD

**Issue by Mirppc** [nicolargo/glances#1792]
**Describe the bug**
the IRQ panel will not go away.  the help file says uppercase Q is suppose to hide or show it.

**To Reproduce**
1. Start Glances with the followings options 'glances'
2. Press the key 'Q'
3. IRQ panel goes nowhere
4. Press h to confirm that 

**Expected behavior**
Pressing Q

**Screenshots**
![Screenshot from 2021-01-10 17-22-14b](https://user-images.githubusercontent.com/17001777/104141185-56a19180-536a-11eb-831a-a53062578bdf.png)

![Screenshot from 2021-01-10 17-37-51](https://user-images.githubusercontent.com/17001777/104141292-d16aac80-536a-11eb-92b5-3d9ebf771431.png)

**Desktop (please complete the following information):**
 - OS: PopOS 20.10, Opensuse Leap 15.2, SLED 15 SP2
 - Glances Version: glances in /usr/lib/python3.6/site-packages (3.1.5)
 - Glances logs file: n/a

**Additional context**
Trying to see the whole list of sensors and not being able to remove the irq panel makes it impossible to see all the available sensors.

**Install method**

pip install glances psutil

**Comment by nicolargo** [comment]
Not reproduced on my system (CentOS 7.9 with Glances 3.1.5):

![image](https://user-images.githubusercontent.com/776747/104216567-85873880-543a-11eb-91dc-0950160e1edc.png)

Press 'Q':

![image](https://user-images.githubusercontent.com/776747/104216608-9172fa80-543a-11eb-8572-6e8a2c17ff1c.png)

**Comment by Mirppc** [comment]
Let me uninstall glances and try agian.

**Comment by Mirppc** [comment]
Uninstalled using pip
Then checked /usr/lib for outdated python folders that might have an older outdated glances install
Found python 3.4 directory and nuked it since Python 3.4 is not installed  
Reinstalled glances using pip install glances
Issue persists
Check log file (attached) and found nothing of major note that would show signs as to why.

[glances.log](https://github.com/nicolargo/glances/files/5798654/glances.log)


https://user-images.githubusercontent.com/17001777/104246305-99bb3d80-541a-11eb-8fef-10995565925e.mp4

**Comment by imdebating** [comment]
I'm also seeing this issue. When I press Shift-Q to toggle the IRQ, it remains visible (or hidden) depending on my conf file. 
With the vanilla config file the issue occurs on my machine:
``` bash
$ glances -C /usr/local/share/doc/glances/glances.conf -V
Glances v3.1.6.2 with PsUtil v5.6.7
Log file: /home/user/.local/share/glances/glances.log
```
My log file for the command `glances -C /usr/local/share/doc/glances/glances.conf`
2021-02-08 18:07:37,467 -- INFO -- Start Glances 3.1.6.2
2021-02-08 18:07:37,467 -- INFO -- CPython 3.6.8 and psutil 5.6.7 detected
2021-02-08 18:07:37,472 -- INFO -- Search glances.conf file in /usr/local/share/doc/glances/glances.conf
2021-02-08 18:07:37,482 -- INFO -- Read configuration file '/usr/local/share/doc/glances/glances.conf'
2021-02-08 18:07:37,494 -- INFO -- Start GlancesStandalone mode
2021-02-08 18:07:37,719 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2021-02-08 18:07:38,047 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2021-02-08 18:07:38,055 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2021-02-08 18:07:44,618 -- INFO -- Stop Glances (keypressed: 113)

__My System Info__
``` bash
$ uname -srvmpio
Linux 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Mirppc** [comment]
It seems to be random on which machine of mine this happens to.  Currently i have this issue on a Dell Poweredge T410 running Opensuse Leap as well as a Dell XPS 8300 running Opensuse Tumbleweed.  I have tested one thinkpad L440 and two dell inspiron dekstops without this same issue.  I will continue testing some more.

Thanks @imdebating for posting you too are having the same issue.  I thought i was going mad there for a bit.

**Comment by Mirppc** [comment]
So i have a way of testing this.  seems to still be an issue and the following are the steps to replicate.

1. Do a fresh install of OpenSUSE/SUSE either Leap, Tumbleweed or SLE.
2. Once installed open a terminal and do 'sudo pip3 install glances psutil'
3. run glances
4. if the irq shows up press SHIFT and Q at the same time to get rid of it, or at least try to.

At step 4 I seem to have a 1 in 4 chance that it just will work depending on which machine i have.  Doesnt seem to care about brand or type.  If the IRQ info shows up it wont go away.

**Comment by dbf-io** [comment]
For what it's worth, I had this issue and upon running glances as sudo Shift-Q worked to toggle IQ.

**Comment by nicolargo** [comment]
Should be corrected in the develop branch (see previous commit).

Thanks for the issue report.

**Comment by Mirppc** [comment]
I haven't responded to this as i cannot test it.  following the instructions to get the test build via pip is not working so i have hit a brick wall there.  as of a few minutes ago the mainline one via pip has not been updated from 3.1.7 yet.

**Comment by nicolargo** [comment]
Yes the code is available in the develop branch.

Test is ok.

It will be release in Glances 3.2.0 (coming soon).
