### ISSUE TITLE
Add an option to  ompletely disable command paramaters in the process list

### ISSUE THREAD

**Issue by lifeike** [nicolargo/glances#1794]
command
baidudisk --no-sandbox
chrome --type=render --field-trial-handle=xxxxxxxxxxxxxxxxxxx

please disable the parameters or argumens appended

thanks

**Comment by nicolargo** [comment]
???

**Comment by lifeike** [comment]
![image](https://user-images.githubusercontent.com/46255758/105573342-0dfab880-5d1a-11eb-9a9f-2b2b4f4b74eb.png)

![image](https://user-images.githubusercontent.com/46255758/105573349-19e67a80-5d1a-11eb-8d4b-3b516f5034f9.png)

top command column has no parameters after command name.

**Comment by nicolargo** [comment]
You can use the --process-short-name option (https://glances.readthedocs.io/en/stable/cmds.html#cmdoption-process-short-name) but for the moment there is no feature to disable all the parameter...

**Comment by lifeike** [comment]
> You can use the --process-short-name option (https://glances.readthedocs.io/en/stable/cmds.html#cmdoption-process-short-name) but for the moment there is no feature to disable all the parameter...

yeah, I'm using a short-name option right now.
To disable all paratmeters is not an essential feature, I just request it here to make glances better potentially in the future.
thanks for the reply.

best
