### ISSUE TITLE
Command trimmed incorrectly.

### ISSUE THREAD

**Issue by ohreally** [nicolargo/glances#1795]
Hi,

**Describe the bug**
Incoming ssh connections are displayed in `ps' output like this:

```
sshd: userx@pts/0 (sshd)
sshd: usery@pts/1 (sshd)
sshd: userx@pts/2 (sshd)
sshd: userx@pts/3 (sshd)
```

In glances they are displayed like this:

```
0
1
2
3
```

**To Reproduce**
Ssh into the server.
Watch glances screen.

**Expected behavior**
Useful output.

**Server**
FreeBSD 12.2-RELEASE
Glances 3.1.4
OpenSSH 7.9p1

**Additional context**
I guess you trim all commands up to the last slash, to save space. I think you should make an exception here.
I haven't installed glances on a Linux machine, but I have verified that the `ps' output is the same there, for incoming ssh connections, so I think this is the same on Linux.

Cheers,
  Rob

**Comment by metayan** [comment]
Same on Linux. (Checked on Ubuntu and FunToo.)
