### ISSUE TITLE
Add option for alternate JSON MQTT output formats

### ISSUE THREAD

**Issue by deosrc** [nicolargo/glances#1798]
**Is your feature request related to a problem? Please describe.**

The current format for MQTT output results in a lot of messages because each property is output to a separate topic. Also other applications subscribing to the messages are triggered once for each message received rather than once for each update. They also have to try to re-combine data if they require multiple properties.

**Describe the solution you'd like**

It would be good to have messages send either all of the properties as either a topic per plugin or a topic per instances of glances. This would drastically reduce the number of messages and reduce the number of times other applications are triggered.

For example, the output for a topic of `glances/<machine_name>/mem` would be:

```json
{
    "total": 938467,
    "available": 22134,
    "percent": 40.3,
    ...
}
```

This would give an application receiving an update about memory usage all of the information at once.

I expect this would need to be configurable as an `output_format` setting with values such as `flat`, `topic-per-plugin` and `single-topic`.

**Describe alternatives you've considered**

I am currently processing messages individually.

**Additional context**

The JSON format is used by tools such as Home Assistant, zigbee2mqtt, samil-mqtt and owntracks.

**Comment by deosrc** [comment]
I had a play with the code. It seems the update method at https://github.com/nicolargo/glances/blob/develop/glances/exports/glances_mqtt.py#L84 is called once for each plugin.

I managed to add a `format` parameter which defaults to `simple`. Supplying `json` will output one topic per plugin. It does this in a hierarchy format. For example, the percpu output is:

```json
{
    "0": {
        "total": 41.5,
        ...
    },
    "1": {
        "total": 10.3,
        ...
    },
    ...
}
```

This currently on my branch at https://github.com/deosrc/glances/blob/mqtt-json-output/glances/exports/glances_mqtt.py

I'm currently testing it on my home cluster.

**Comment by nicolargo** [comment]
Hi @deosrc 

for the moment, as you said, the update method is called once for each plugin. So the simple or json (perhaps a better name could be found because simple is also a json format...) can be implemented (one topic per plugin) but not the topic per instance of Glances.

Feel free to propose a pull request on the develop branch !

Nicolas
