### ISSUE TITLE
zpool status

### ISSUE THREAD

**Issue by phynias** [nicolargo/glances#1807]
not a problem just started using glances and saw it had zfs support but what it shows while good isn't really what i want to see about my zpool. i would much rather see the status. make sure there is no problems (degraded zpool, silvering or scrubbing jobs) 

something like:

>zpool: my-pool
>    status: ONLINE

or

>zpool: my-pool
>status: Silvering...84%
 
or 
>zpool: my-pool
>status: Degraded [disk /dev/sdc DEGRADED]

**Comment by RazCrimson** [comment]
Closing as a duplicate of #873
