### ISSUE TITLE
Debian10: "glances -s" reports "Cannot start Glances server: [Errno 98] Address already in use"

### ISSUE THREAD

**Issue by r4dh4l** [nicolargo/glances#1821]
**Describe the bug**

After installing glances from Debian 10.8 standard repositories I wanted to try the Client/Server mode following https://glances.readthedocs.io/en/latest/quickstart.html#client-server-mode but the command line output reports:

```
$ glances -scritical alert detected
Cannot start Glances server: [Errno 98] Address already in use
```

**To Reproduce**
1. Install glances on Debian10:

```
# apt install glances
# apt policy glances
glances:
  Installed: 3.1.0-1+deb10u1
  Candidate: 3.1.0-1+deb10u1
  Version table:
 *** 3.1.0-1+deb10u1 500
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

2. Start glances in server mode:

```
$ glances -s
Cannot start Glances server: [Errno 98] Address already in use
```

`htop` reports one glances process:

![Screenshot_2021-03-06_00-31-04](https://user-images.githubusercontent.com/44623983/110185703-5629f200-7e13-11eb-9480-62936a0f1337.png)

```
# netstat -tulpen | grep 61209
tcp        0      0 127.0.0.1:61209         0.0.0.0:*               LISTEN      0          583251     26393/python3
```

Is glances already running in server mode when installing from Debian repositories?

**Expected behavior**

I've expected that `glances -s` would start the first and only background process.

**Desktop (please complete the following information):**
 - OS: `Debian 10.8`
 - Glances Version:
 
 ```
 $ glances -V
Glances v3.1.0 with psutil v5.5.1
 ```
 
 - Glances logs file: (sorry I couldn't find the log file location of glances)

**Comment by nicolargo** [comment]
The Debian package start a server: see https://salsa.debian.org/debian/glances/-/blob/master/debian/glances.service

If you want to disable it just enter the following command line:

```
systemctl disable glances
```
