### ISSUE TITLE
'/api/3/processlist/pid/3936'use this api can't get right info,all messy code

### ISSUE THREAD

**Issue by zbyzfw** [nicolargo/glances#1828]
**Describe the bug**
/api/3/processlist/pid/3936
/api/3/processlist/pid
api/3/processlist/name
have this error
this request /api/3/processlist all going well

**To Reproduce**
1. Start Glances with the followings options '...'
2. Press the key '....'
3. See error

**Expected behavior**

**Screenshots**
[](url)
![image](https://user-images.githubusercontent.com/35451402/112708544-86821f00-8eed-11eb-923a-bd9c83f53dab.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Glances Version 3.16
 - Glances logs file all going well

**Additional context**

**Comment by nicolargo** [comment]
Confirmed.

Have a look as soon as possible.

Thanks for the issue report @zbyzfw

**Comment by nicolargo** [comment]
Ok find the issue, the internal function _api_itemvalue should not be called with the process.

Corrected in the develop branch, it will be release in the next version (aka Glances 3.1.7).

Thanks for the issue report @zbyzfw

**Comment by zbyzfw** [comment]
thank you for your attention☺️
