### ISSUE TITLE
Out of date snap requests to upgrade with pip

### ISSUE THREAD

**Issue by ghost** [nicolargo/glances#1831]
**Describe the bug**
The Glances snap currently prompts the user to upgrade with pip. The following message is seen in the cli.
"You are using Glances version 3.1.5, however version 3.1.6.2 is available.
You should consider upgrading using: pip install --upgrade glances"

**To Reproduce**
1. Start Glances snap
2. Upgrade message shown in cli

**Expected behavior**
Presuming the snap builds were pushed inline with the other builds, I wouldn't expect to see any message as snaps silently update automatically.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi 3b+ Ubuntu Core 20
 - Glances Version 3.1.5

**Comment by nicolargo** [comment]
Snap packaging is a pain in the ass... An open issue blocks the build of the latest version ==> https://github.com/nicolargo/glances/issues/1801

Any contributor are welcome, i will not spend my time on it... :)

**Comment by nicolargo** [comment]
Related to https://github.com/nicolargo/glances/issues/1801
