### ISSUE TITLE
Unable to use export to Influxdb 1.8.x with filter influxdb2

### ISSUE THREAD

**Issue by kunago** [nicolargo/glances#1832]
**Describe the bug**
I need to use the export filter influxdb2 to export measurements to my influxdb 1.8 database. Influxdb however does not know all the required parameters, such as organisation, bucket and token. I tried a few configurations but cannot find a way to force Glances export stats to the database. I read and followed the manual.

**To Reproduce**
1. Start Glances with the followings options 'glances -C glances.conf --export influxdb2'
2. The container (using docker as a test environment) stops

**Expected behavior**
I expect Glances to export stats to InfluxDB

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Debian 10, docker
 - Glances Version : v3.1.6.2

**Additional context**
not applicable

**Comment by nicolargo** [comment]
It is not possible....

To connect to InfluxDB 1.8, use the influxdb export (not the influxdb2).

**Comment by kunago** [comment]
What am I missing here?

![image](https://user-images.githubusercontent.com/460971/113288428-4062fc00-92ef-11eb-9f5e-b22a50475c16.png)

This is a screenshot from the documentation of glances; on pypi website is a comment that "influxdb-python" does not support InfluxDB v 1.8.x and "influxdb-client" should be used instead. Sorry, I am confused.

**Comment by nicolargo** [comment]
Sorry my mistake i forgot that the InfluxDB2 client is also compatible with InfluxDB 1.8 !
Please can you run Glances in debug mode (-d) and send us back the log file ?

**Comment by nicolargo** [comment]
I just make the following test on y Ubuntu system:

1) Run a InfluxDB 1.8 server (inside a Docker)
2) Add the following section in the Glances conf file:

```
[influxdb2]
# Configuration for the --export influxdb2 option
# https://influxdb.com/
host=localhost
port=8086
protocol=http
org=nicolargo
bucket=glances
token=EjFUTWe8U-MIseEAkaVIgVnej_TrnbdvEcRkaB1imstW7gapSqy6_6-8XD-yd51V0zUUpDy-kAdVD1purDLuxA==
# Prefix will be added for all measurement name
# Ex: prefix=foo
#     => foo.cpu
#     => foo.mem
# You can also use dynamic values
#prefix=`hostname`
prefix=localhost
# Tags will be added for all measurements
#tags=foo:bar,spam:eggs
# You can also use dynamic values
#tags=system:`uname -s`
```

Note: the org, bucket and token will be not taken into account but are necessary in the conf file.

3) Start Glances with: glances --export influxdb2

The export works like a charm.

**Comment by kunago** [comment]
I am obivously failing to set up the token authorization with InfluxDB 1. Is this meant to be [JWT tokens](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#authenticate-using-jwt-tokens) as described here?

**Comment by nicolargo** [comment]
For the token creation, please read the following documentation: https://docs.influxdata.com/influxdb/cloud/security/tokens/create-token/
