### ISSUE TITLE
Refresh rate is not working?

### ISSUE THREAD

**Issue by GiganteX** [nicolargo/glances#1835]
I ran this:

docker run --name glances --detach --restart="always" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -e GLANCES_OPT="-w -t 10" -p 61208-61209:61208-61209 nicolargo/glances

...but refresh rate is still 3 seconds. What's wrong?

I found the same question here so it's seems it has been like this for some time?
https://superuser.com/questions/1336097/how-can-i-specify-a-refresh-rate-in-glances#:~:text=By%20default%2C%20glances%20refreshes%20itself%20every%203%20seconds.

**Comment by nicolargo** [comment]
Strange it works fine outside a Docker.

Just tested on my system:

    glances -w -t 10

Start Firefox...

The UI is refreshed every 10 seconds...

**Comment by GiganteX** [comment]
I just now did a fresh install on another Ubunto 16 server VM. 
Did a normal install with apt, no docker container (although docker is present on the VM).

glances -w -t 10

But here refresh rate seems to be about 5 seconds, not three.. and definitely not 10.
I also tried: glances -w -t 60
as well but same thing, refresh rate is 5 secs.

I am perplexed..

**Comment by GiganteX** [comment]
On a related note, I tried this for the docker version:

docker run --name glances --detach --restart="always" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -e GLANCES_OPT="-w --disable-plugin gpu,wifi,kafka,couchdb,cassandra,csv,elasticsearch,json,mqtt,rabbitmq,riemann,statsd,zeromq" -p 61208-61209:61208-61209 nicolargo/glances

But when I run --modules-list it shows the same list as before, seems nothing was disabled? Is there a general problem with reading the second GLANCES_OPT parameter?

**Comment by nicolargo** [comment]
Some remarks:
- In Glances version 2.3 the refresh did not work (see https://github.com/nicolargo/glances/pull/1548)
- In Glances version 3.1.3 or higher it must work
- The --modules-list is executed on the client side, not the server side

**Comment by nicolargo** [comment]
l will have a look on the Docker packaging and check if the second (and +) option is taken into account.

**Comment by nicolargo** [comment]
@GiganteX 

On my Ubutnu system, when i ran:

    docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w -t 10" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host nicolargo/glances:dev

The container is started and when i connect the Web Interface i confirm that the UI is refreshed every 10 seconds.

**Comment by GiganteX** [comment]
You're right. I just tested that exact line myself. 
Furthermore, when I tested my original command from the first post in the thread, that works correctly too! 
Oh wait, I see it was updated a day ago (on docker hub), did you find the issue and fixed it?
