### ISSUE TITLE
glancesautoinstall's install.sh checks for Arch twice

### ISSUE THREAD

**Issue by hintron** [nicolargo/glances#1838]
The following case appears twice in the switch statement in https://raw.githubusercontent.com/nicolargo/glancesautoinstall/master/install.sh:

    elif [[ $distrib_name == "arch" ]]; then
        # Arch support

        # Headers not needed for Arch, shipped with regular python packages
        do_with_root pacman -S python-pip lm_sensors wireless_tools --noconfirm

Also, since we are already here, it says `Arch` instead of `Alpine` in the comments (twice) under the Alpine case:

    elif [[ $distrib_name == "alpine" ]]; then
        # Arch support
        
        # Headers not needed for Arch, shipped with regular python packages
        do_with_root apk add py-pip python-dev linux-headers musl-dev lm_sensors wireless-tools

**Comment by nicolargo** [comment]
@hintron Thanks for the issue report.
Correct on the glancesautiinstall repository.
