### ISSUE TITLE
GPU temperature not shown in webview

### ISSUE THREAD

**Issue by ped22** [nicolargo/glances#1849]
In the webview, display of the GPU temperature is not yet implemented. 

With nvidia GPU and package py3nvml installed:
- run glances in curses mode and see GPU temperature displayed
- run glances in webview mode and do not see GPU temperature displayed

Tested on Ubuntu 18.04 and Windows 10 using glances v3.1.6.2

**Comment by nicolargo** [comment]
@notFloran Can you have a look ?

**Comment by nicolargo** [comment]
Implemented in the develop branch.

Will be available in Glances 3.1.7.

![Screenshot_2021-04-24 XPS13-9333 - Glances](https://user-images.githubusercontent.com/776747/115953346-3184f900-a4eb-11eb-8cfa-99add262d965.png)

@ped22  Thanks for the issue report.
