### ISSUE TITLE
Windows --export Influxdb -w not starting webserver

### ISSUE THREAD

**Issue by dayman226** [nicolargo/glances#1852]
Im trying to export to Influxdb and use Restful API at the same time on windows. If I use glances --export Influxdb -w it seems that only influxdb works. I could try two separate runs of the script but that normally ends up with the restful API only working every other update.
Any info or way around this would be appreciated

**Comment by nicolargo** [comment]
Last version of Glances display an error message if you try to do this:

```
$ glances -w --export influxdb
Export is only available in standalone or client mode
```

The -w ran Glances in Web server mode. Glances grabs stats ob ly on demand (via the WebUI or Rest/API). Export needs to grab stats every x seconds. These two options are not compatible.

If you want to export / run a Web mode, one workaround will be to lauch two Glances instances.
