### ISSUE TITLE
Docker image with additional  dependencies included?

### ISSUE THREAD

**Issue by Poeschl** [nicolargo/glances#1858]
**Is your feature request related to a problem? Please describe.**
I came to this idea while struggling with missing python dependencies for the exporter on the latest docker image. I found the issues which suggest to use the dev image since it has the dependencies, but that one is also not versioned and the name suggests that is might not be as stable as a versioned release.

**Describe the solution you'd like**
Would it be possible to release also a docker images like `nicolargo/glances:3.1.7-full` where all the additional dependencies are included? That way there would be versioned release with all dependencies. It would be bigger then the regular one, but as user of it you have the choice between the two.

**Describe alternatives you've considered**
As alternative the current docker image can be used as base image and the python packages can be installed individually. This is possible, but it also need to be active maintained on new releases.

**Comment by nicolargo** [comment]
It is already availble through the dev tag.

Latest(master with minimal plugins):
```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it nicolargo/glances:latest pip freeze
bernhard==0.2.6
bottle==0.12.19
certifi==2020.12.5
chardet==4.0.0
docker==5.0.0
future==0.18.2
Glances==3.1.6.2
idna==2.10
ifaddr==0.1.7
netifaces==0.10.9
pbkdf2==1.3
ply==3.11
protobuf==3.15.8
psutil==5.8.0
py-cpuinfo==4.0.0
py3nvml==0.2.6
pyasn1==0.4.8
pycryptodomex==3.10.1
pygal==2.4.0
pymdstat==0.4.2
pySMART.smartx==0.3.10
pysmi==0.3.4
pysnmp==4.4.12
pystache==0.5.4
requests==2.25.1
scandir==1.10.0
six==1.15.0
sparklines==0.4.2
urllib3==1.26.4
websocket-client==0.58.0
wifi==0.3.8
xmltodict==0.12.0
zeroconf==0.29.0
```

Dev with all plugins:
```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it nicolargo/glances:dev pip freeze
bernhard==0.2.6
bottle==0.12.19
cassandra-driver==3.24.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
CouchDB==1.2
docker==4.4.1
elasticsearch==7.10.1
future==0.18.2
geomet==0.2.1.post1
idna==2.10
ifaddr==0.1.7
influxdb==5.3.1
influxdb-client==1.14.0
kafka-python==2.0.2
msgpack==1.0.2
netifaces==0.10.9
paho-mqtt==1.5.1
pbkdf2==1.3
pika==1.1.0
ply==3.11
potsdb==1.0.3
prometheus-client==0.9.0
protobuf==3.14.0
psutil==5.8.0
py-cpuinfo==4.0.0
py3nvml==0.2.6
pyasn1==0.4.8
pycryptodomex==3.9.9
pygal==2.4.0
pymdstat==0.4.2
pySMART.smartx==0.3.10
pysmi==0.3.4
pysnmp==4.4.12
pystache==0.5.4
python-dateutil==2.8.1
pytz==2020.5
pyzmq==22.0.2
requests==2.25.1
Rx==3.1.1
six==1.15.0
sparklines==0.4.2
statsd==3.3.0
urllib3==1.26.3
websocket-client==0.57.0
wifi==0.3.8
xmltodict==0.12.0
zeroconf==0.28.8
```

**Comment by Poeschl** [comment]
My point is that the dev tag is not stable. When running the tag today and running the same tag next year it will happen that the packages inside are not the same and a configuration for today might not be compatible with the future dev tag.

**Comment by Poeschl** [comment]
I you ok with it, I would try to adjust the build to automatically release the image discussed above. 😉

I also have a question about the image bases. Any specific reason to not use alpine also for the release images?

**Comment by nicolargo** [comment]
With pleasure @Poeschl 

More information concerning the build process.

- latest tag is build from the master branch. It uses the https://github.com/nicolargo/glances/blob/develop/docker-files/Dockerfile file and it is triggered by push thanks to the buildx **Github action** https://github.com/nicolargo/glances/blob/develop/.github/workflows/build.yml
- 3.1.7 (and every tag) are build from the tag. It uses the https://github.com/nicolargo/glances/blob/develop/docker-files/Dockerfile file and it is triggered by push thanks to the buildx **Github action** https://github.com/nicolargo/glances/blob/develop/.github/workflows/build.yml
- develop tag is build from the develop branch. It uses the https://github.com/nicolargo/glances/blob/develop/docker-files/dev.Dockerfile file and it is triggered by push thanks to the buildx **Github action** https://github.com/nicolargo/glances/blob/develop/.github/workflows/build.yml. _For the moment, only this version includes all the plugins._
- latest-alpine tag is build from the master branch. It uses the https://github.com/nicolargo/glances/blob/develop/docker-files/devel-alpine/Dockerfile file and it is triggered by push thanks to the **DockerHub action**.

Concerning the release image choice (python:3-slim-buster - https://hub.docker.com/_/python), it includes by default all the tools to run Python scripts.

**Comment by Poeschl** [comment]
More question: 
* Should there be also a "full" version of the latest image?
* Should there be also the alpine variants available?

**Comment by nicolargo** [comment]
yes it should be nice to have a "minimal" and a "full" image for both master and alpine.

**Comment by nicolargo** [comment]
Note for myself: need to update the README.rst file.

**Comment by alceasan** [comment]
In my case I couldn't enable influxdb export because of missing dependencies on current docker image (latest). This is how I solved it, if it can help any of you using docker compose:


1. Don't use GLANCES_OPT environment variable.
2. Include the folowing startup command (if you want web interface, change -q to -w):

`command: bash -c 'python -m pip install -q influxdb && python -m glances -C /glances/conf/glances.conf --export influxdb -q'
`
