### ISSUE TITLE
https://raw.githubusercontent.com/nicolargo/glancesautoinstall/master/install.sh under RHEL-8.3: "Sorry, GlancesAutoInstall script is not compliant with your system."

### ISSUE THREAD

**Issue by spezialist1** [nicolargo/glances#1865]
Dear team,

If under **RHEL-8.3** environment you use the Glances Auto Install script by the link _https://bit.ly/glances_ as described on the official website _https://nicolargo.github.io/glances/_, you get an error: **"Sorry, GlancesAutoInstall script is not compliant with your system"**.

**The reason:** under RHEL-8.3 environment, the command _'lsb_release -is'_ returns _"RedHatEnterprise"_, not _"RedHatEnterpriseServer"_. Therefore, it is necessary to modify the above Glances Auto Install script accordingly. But I don't see where I could do that here on github?

I am waiting for a reply and thank you for your support.

**Comment by nicolargo** [comment]
The source are there: https://github.com/nicolargo/glancesautoinstall

I just commit a change to be able to install it on Redhat 8.3.

Can you retry ?

Thanks.

**Comment by spezialist1** [comment]
Great, thanks for the tip.
Now I tried it, I see that the script is already modified.
Thank you, I think the issue can be closed :-).

**Comment by nicolargo** [comment]
Ok !

Thanks for the issue report.
