### ISSUE TITLE
Glances:dev container not starting (message: psutil not found).

### ISSUE THREAD

**Issue by TrezOne** [nicolargo/glances#1867]
**Describe the bug**
Glances:dev container not starting (message: psutil not found).

**To Reproduce**
1. Creating container via Docker compose. Only extra option currently fed in is exporting influxdb2.
`GLANCES_OPT=--quiet --export influxdb2`

**Expected behavior**
Container to start normally. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Glances Version [output of glances -V]: Unable to console into container. 
 - Glances logs file [output of tail -10 <glances logs file>]

> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,
> psutil library not found. Glances cannot start.,

 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher): Unable to console into container.

**Additional context**
Container was updated via Watchtower on May 18th, which was when the container attempted to restart but failed.

**Comment by nicolargo** [comment]
Please @cliffordwhansen can you have a look ?

**Comment by nicolargo** [comment]
@TrezOne as a workaround, you can use the **latest** (aka stable) or **3.1.7** (last available tagged version) tag instead of the **dev** one.

**Comment by TrezOne** [comment]
Hi @nicolargo , I was using the dev one because the latest tagged version doesn't include certain modules, e.g., the influxdb_client. I know there's a discussion about having a stable full image being talked about in #1859 but until then the :dev tagged image is the only alternative I know of currently.

**Comment by cliffordwhansen** [comment]
Looks like this just affects the Debian version, I found the python module directory is different from the alpine one.

**Comment by nicolargo** [comment]
@TrezOne it is corrected and the last dev image rocks !

Thanks to the awesome @cliffordwhansen for the patch :)
