### ISSUE TITLE
Generate specific tag from stats' key for InfluxDB and InfluxDB2 export

### ISSUE THREAD

**Issue by alceasan** [nicolargo/glances#1871]
I'm currently working on a grafana dashboard using exported glances data on influxdb, but when I create a single graph for all containers (for cpu o mem usage), it's not easy to read because a I can't use tags to group by and set alias for tags.

It wold be nice to have a new config option for influxdb export so that docker container data has its container name as tag, and we could use it for querying. Maybe it's possible to do this with the current tags option, but I don't know how.

**Comment by nicolargo** [comment]
I propose to convert the 'key'  in tag. For example, in the Docker plugin key = name, so the name will be converted as a tag in InfluxDB.

It will works for all plugins with a key (network, diskio...).

**Comment by nicolargo** [comment]
Pushed on the https://github.com/nicolargo/glances/tree/issue1871 branch.

Need some test because the datamodel change.

No more key.stats in the measurements name.
Switch to stats and key as tag.

**Comment by nicolargo** [comment]
Hi @alceasan 

just pushed a new version of the InfluxDB exporter to the develop branch.

It will change the way that measurements are exported.

- add the hostname as a tag for all measurement
- add the stats key (container name for docker or network interface name for network for example)
- the default prefix=localhost has been removed from the glances.conf file

Read the updated documentation here: https://glances.readthedocs.io/en/develop/gw/influxdb.html

Any chance to test this on your side ?

**Comment by madisonpeople** [comment]
Thanks for your hard work as I stumble around learning slowly. thee so  much to read, and learn.  A new Linux GNU enthusiast..!
