### ISSUE TITLE
Quit from help should return to main screen, not exit

### ISSUE THREAD

**Issue by njthomas** [nicolargo/glances#1874]
**Describe the bug**
- entering 'h' to enter the help screen and then typing 'q' exits the program
- this violates POLA
- 'q' from the help screen should return to the main screen

**To Reproduce**
1. Start Glances 
2. Press the key 'h'
3. Press the key 'q'
4. see that you have exited the entire program

**Expected behavior**
After step 3, you should be returned to the main screen. Most programs work this way.

**Comment by nicolargo** [comment]
Done in last commit.

Thanks for the issue report @njthomas !

**Comment by njthomas** [comment]
Thanks so much!
