### ISSUE TITLE
Issue exporting to Kafka

### ISSUE THREAD

**Issue by BillMincey** [nicolargo/glances#1887]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

Followed the directions to export metrics to my Kafka cluster. Log is reporting that a connection is made but it can't send the metrics. I have installed python-kafka.

I looked at the exporter code and the only thing I can think is causing an issue is the serialization. An exception message is not being returned in the log.

I can send messages to this topic on my kafka cluster from another client and receive them successfully.

[glances.conf.txt](https://github.com/nicolargo/glances/files/6719389/glances.conf.txt)
[glances-vmadmin.log](https://github.com/nicolargo/glances/files/6719382/glances-vmadmin.log)

#### Versions

* Glances v3.1.3 & psutil v5.5.1
* Operating System Ubuntu 20.04.2 LTS

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Duplicated ==> https://github.com/nicolargo/glances/issues/1593

Please upgrade Glances to v3.1.4 or higher (higher is better...)
