### ISSUE TITLE
Glances+Docker: --browser keeps restarting the container.

### ISSUE THREAD

**Issue by gk7279** [nicolargo/glances#1889]
Dear Glances Team-

I am trying to run glances using docker with the below command

`sudo docker run -d --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="--browser" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances:latest-alpine`

However, as soon as the container starts, it says restarting and I cannot access the web interface.

I want to monitor two machines running glances with one of them being a central client. If I run the above command on one and another same docker command but with -w on the other one, can I achieve what I want?

I did read the docs on Glances site where it says I can use the -v `pwd`/glances.conf file. When I fed this parameter to the above command with --browser, the container is still in restarting mode. Please advice. Thanks.

**Comment by nicolargo** [comment]
Hi @gk7279 

i am not sure to understand what you try to do.

The --browser option is only available in terminal user interface not in the web interface (an issue is already existing: https://github.com/nicolargo/glances/issues/1121).

Nicolas
