### ISSUE TITLE
Make the process sort list configurable through the command line

### ISSUE THREAD

**Issue by peppelongo96** [nicolargo/glances#1903]
**Is your feature request related to a problem? Please describe.**
Hi. I think that the possibility to save and load custom views could be a great feature.

**Comment by nicolargo** [comment]
Hi @peppelongo96 

do you want to enable/disable some plugins at startup ?
If the respond is yes than you can do it by using the disable=True (or disable=False) in the glances.conf file for each relevant plugins (https://glances.readthedocs.io/en/latest/config.html).

**Comment by peppelongo96** [comment]
Hi @nicolargo and thanks for the answering!

I'm properly talk about some settings that I can choose from -h menu. For example, sorting processes by MEM when I open the local site directly

**Comment by nicolargo** [comment]
Ok copy that.

Can you give me a list of fonctions to be available through the command line:

- sort process by cpu
- sort process by MEM
- sort process by IO

Others stuffs ?

**Comment by nicolargo** [comment]
Processes sort option from the command line implemented in last commit on the DEVELOP branch.

Rad the doc here ==> https://glances.readthedocs.io/en/develop/aoa/ps.html

**Comment by peppelongo96** [comment]
Thanks mate!
