### ISSUE TITLE
[3.2.0/3.2.1] keybinding not working anymore

### ISSUE THREAD

**Issue by jeandestouches** [nicolargo/glances#1904]
Hello,
An user on gentoo forums noticed a strange issue related to keybinding with glances 3.2.0/3.2.1. I noticed the same bug on my Gentoo system and also on Arch Linux with 3.2.0/3.2.1. Keybinding works fine with previous release.
Here is a quote of the user message on the forum as it explains quite well the issue : 

----
So - this is odd - it started a couple of days ago, and I've no idea what to do about this. Glances, which I use a lot. has stopped responding to about half of it's normal commands. Now, I don't expect every keybinding to do something - for instance, I don't run docker, so I don't expect 'D' to produce any docker related output.

However, the following functions are doing nothing either while worked previously.
* (d) show/hide disk IO
* (n) show/hide network stats
* (s) show/hide sensors
* (2) show/hide sidebar
* (l) show/hide alerts
* (F) show/how fs free space

But all the process-list related options, such as the different sorts work, as do commands relating to change what an individual output is producing, such as change Kb to Kbit in the network stats.

It's almost like the sidebar is 'stuck' and I can't change what items it's displaying - though they're updating and I can change some of the output of the existing categories. However, this isn't completely uniform - I can toggle the IRQ stats with 'Q', and show/hide fs stats with 'f' - but that's the only things I can turn on/off on the sidebar.

I've ran glances via the emerged version and via a local install using pip. Both exhibit the same behaviour. Debug mode shows glances is noticing the keypress, but there are no errors or further messages concerning it.

I've removed the config file without any change, so it's not that either. Naturally, my keyboard is working fine. Any ideas??

Thanks

----

**Comment by jeandestouches** [comment]
Quoting an user on the forum for resolution : 

The problem seems in glances/outputs/glances_curses.py with this change (line 353) 

````
         # Actions (available in the global hotkey dict)...
+        logger.debug("Keypressed (code: {})".format(self.pressedkey))
         for hotkey in self._hotkeys:
             if self.pressedkey == ord(hotkey) and 'switch' in self._hotkeys[hotkey]:
-                setattr(self.args,
-                        self._hotkeys[hotkey]['switch'],
-                        not getattr(self.args,
-                                    self._hotkeys[hotkey]['switch']))
+                if self._hotkeys[hotkey]['switch'].startswith('enable_') or \
+                   self._hotkeys[hotkey]['switch'].startswith('disable_'):
+                    # Enable / Disable switch
+                    # Get the option name
+                    # Ex: disable_foo return foo
+                    #     enable_foo_bar return foo_bar
+                    option = '_'.join(
+                        self._hotkeys[hotkey]['switch'].split('_')[1:])
+                    if getattr(self.args,
+                               self._hotkeys[hotkey]['switch']):
+                        disable(self.args, option)
+                    else:
+                        enable(self.args, option)
+                else:
+                    # Others switchs options (with no enable_ or disable_)
+                    setattr(self.args,
+                            self._hotkeys[hotkey]['switch'],
+                            not getattr(self.args,
+                                        self._hotkeys[hotkey]['switch']))
             if self.pressedkey == ord(hotkey) and 'sort_key' in self._hotkeys[hotkey]:
                 glances_processes.set_sort_key(self._hotkeys[hotkey]['sort_key'],
                                                self._hotkeys[hotkey]['sort_key'] == 'auto')

**Comment by wembleyford** [comment]
I'm the original poster on the gentoo forums. I notice that this issue seems to occur with both tagged version 3.2.1 and 3.2.0. V 3.1.7 is a lot better - though in that version 'Q' to show/hide the IRQ stats seems to not work. As opposed to being one of the few keys that do work in 3.2.1 and 3.2.0.  This was compiled in Pyth9on 3.9 and ncurses 6.2-r1.

**Comment by nicolargo** [comment]
Corrected by last commit.

My fault (auto blame).

A new version 3.2.3 will coming soon...
