### ISSUE TITLE
Glances don't send hostname (tag) to influxdb2

### ISSUE THREAD

**Issue by alfonzso** [nicolargo/glances#1913]
**Describe the bug**
After a lot of investigation I figured out to glances ( 3.2.2 ) don't send hostname field to influxdb ( 2.0.6 )
And it's because of this ( I think ):
https://github.com/nicolargo/glances/blob/develop/glances/exports/glances_influxdb.py#L62
this line missing in:
https://github.com/nicolargo/glances/blob/develop/glances/exports/glances_influxdb2.py#L59
so this piece of code missing: **self.hostname = node().split('.')[0]**
because of that, self.hostname stay None, and influxdb will drop this :D

**To Reproduce**
1. Start Glances with glances -q --disable-plugin docker --export influxdb2

**Expected behavior**
hostname (tag) in influxdb2

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04 
 - Glances Version 3.2.2

**Additional context**
My config file for influxdb2 =>
$HOME/.config/glances/glances.conf
```
[influxdb2]
host=influxdb.my.net
port=80
protocol=http
org=influxdata
bucket=grafana
token=<token>
```

**Comment by nicolargo** [comment]
Correct ! 

Patch available on the develop branch.

Will be release in Glances 3.2.3.

Thanks @alfonzso !
