### ISSUE TITLE
batinfo not in docker image (and in requirements files...) ?

### ISSUE THREAD

**Issue by khaffner** [nicolargo/glances#1915]
**Describe the bug**
batinfo seems to not be in docker image. I have a laptop (Thinkpad T570) with 3 batteries, including the wireless mouse. batinfo and UPower can show all the information about these batteries, and I'd like them to show up in Glances.

**To Reproduce**
1. docker run -it nicolargo/glances python
2. \>\>\> import batinfo
3. "ModuleNotFoundError: No module named 'batinfo'"

**Expected behavior**
Looking at [the code](https://github.com/nicolargo/glances/blob/c022aa9501c0eb971dafeb2cdcc5e07ce320b0fb/glances/plugins/sensors/glances_batpercent.py) (I'm not too familiar with python though), a missing batinfo seems to be expected in non-linux environments. But this environment (allthough docker) is Linux.

**Screenshots**
I believe I got something working interactively using batinfo
![image](https://user-images.githubusercontent.com/13216618/128639130-f781fba5-3fe4-4268-8841-c44d6d1c1ab7.png)

**Desktop (please complete the following information):**
 - OS: (Docker 20.10.8 on) Pop OS 20.04 (based on Ubuntu)
 - Glances Version [Glances v3.1.6.2 with PsUtil v5.8.0]
 - Glances logs file:
root@57662d45c772:/glances# tail -10 /tmp/glances-root.log 
2021-08-08 16:41:05,583 -- INFO -- Start Glances 3.1.6.2
2021-08-08 16:41:05,583 -- INFO -- CPython 3.9.4 and psutil 5.8.0 detected
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**
I also tried to create a new image based on the latest tag, and just added RUN pip install batinfo. That did not solve the issue, and I do not know what to try next.

**Comment by nicolargo** [comment]
The issue came from the fact that the batinfo dep was not in the optional-requirements.txt file (do not remember why...).

I just add it. 

So the the problem will be solve when Glances 3.2.3 will be release.
