### ISSUE TITLE
Glances No Longer Available for Debian?

### ISSUE THREAD

**Issue by tmanok** [nicolargo/glances#1919]
I love glances. I love Debian. 
...
I've been using both peacefully with servers for a few years now. Until Proxmox 7 was released and my glances installation on all my nodes stopped working! 

So naturally "apt install --reinstall glances" but there's no way to redownload it... Ok "apt remove glances ; apt update ; apt install glances" no installation candidate, Ok add non-free to sources.list, still nada, Ok check https://packages.debian.org/search?keywords=glances&searchon=names&suite=stable&section=all still nada.

**Am I being super ignorant? Did I miss a memo? Why isn't glances available for Debian Bullseye via apt?** 
Why must I install without apt? Having an extra package manager defeats the purpose of using the centralized one (assuming you're ok with the older but stable packages). 

Thank you all for your time,

Tmanok
IT Manager and Sysadmin

**Comment by martadinata666** [comment]
seems the stable query is not the same as buster query, https://packages.debian.org/search?suite=buster&searchon=names&keywords=glances

weird enough, as stable should be buster

**Comment by nicolargo** [comment]
Any feedback from the Debian mainteners: @sbadia & epsilon77@gmail.com

**Comment by tmanok** [comment]
Yes I noticed that older versions have the package, but as you said and as I said, Bullseye does not have it. I can add an older Repo but I'd like to know why it isn't in the latest. Worst case scenario, I can add the package to my hw driver apt repository locally/privately.

Unlike some folks, I'm not installing it via python, or as a container. Not into that, I have enough on my plate and do not wish to make the main hypervisors that much more tedious to maintain. Thanks! 


Tmanok

**Comment by dawidd6** [comment]
It was removed from testing before migrating to bullseye because of some issues that lintian detected. Mainly this bug seems to be relevant: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990340

**Comment by tmanok** [comment]
Wow, that's actually painful. Well, screw that I'm hosting my own private apt repository for it. 
Thanks for updating me Dawidd6.

Tmaok

**Comment by rhernaus** [comment]
```
$ sudo apt install python3-pip
$ sudo pip3 install glances
```

**Comment by nicolargo** [comment]
Yes it is back in Debian.

https://packages.debian.org/fr/sid/glances
