### ISSUE TITLE
Incorrect processes disk IO stats

### ISSUE THREAD

**Issue by min-xu-ai** [nicolargo/glances#1922]
**Describe the bug**

I see that md5sum using same read and write disk IO bandwidth on my arch linux system on Ryzen. Md5sum should only be reading?

![image](https://user-images.githubusercontent.com/24926999/130185430-3a0f6532-070b-4019-b68e-3fc9c03e4b00.png)

**To Reproduce**
1. Start Glances without any options
2. run md5sum on a big file
3. See error

**Expected behavior**
write bandwidth should be 0?

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: arch linux (updated last week with pacman -Syu)
 - Glances Version [Glances v3.2.1 with PsUtil v5.8.0]
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**

**Comment by nicolargo** [comment]
Correct ! There is an issue.
Processes disk IO display wrong write value (= read).

I am going to generate a new Glances version with this reg patch.

**Comment by nicolargo** [comment]
Corrected in Glances version 3.2.3.1.

Thanks you for the issue report @min-xu-ai !
