### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [nicolargo/glances#1923]
Some alternatives as per the PEP : https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/nicolargo/glances/blob/b9a75478438e8ab3ce3c1e1aec119145066d6a7a/glances/outdated.py#L23

**Comment by nicolargo** [comment]
Use:

```
>>> from packaging.version import Version
>>> Version('3.2.1') > Version('3.2.1_RC1')
```

**Comment by nicolargo** [comment]
Done in latest commit.

@thebwt Thanks for the head up !
