### ISSUE TITLE
glances reports different amounts of used memory than `free -m` or `top`

### ISSUE THREAD

**Issue by bermudi** [nicolargo/glances#1924]
**Describe the bug**
On a brand new (virtual) install of Void Linux, installing the glances package reports more used memory than what is being reported by other utilities.

**To Reproduce**
1. Start Glances and note "Mem used:" metric
2. run `free -m` and note "used Mem:" metric
3. run `top` and note the "MiB Mem : used," metric
4. glances is reporting more than double the used memory than `free -m` and `top`

**Expected behavior**
I'd expect the values to remain the same or at least pretty similar across all different reporting utilities 

**Screenshots**
[![glances.png](https://i.postimg.cc/L5hjdpJC/glances.png)](https://postimg.cc/q6VNnWXy)

**Desktop (please complete the following information):**
 - OS: Void Linux fully updated as of (2021-08-28)
 - Glances Version 3.2.2 with PsUtil 5.8.0
 - [Glances logs file](https://rentry.co/c2zxw) [![log.png](https://rentry.co/c2zxw/png)](https://rentry.co/c2zxw/png)
 - [Glances test](https://rentry.co/97m4v) [![png](https://rentry.co/97m4v/png)](https://rentry.co/97m4v/png)

**Additional context**
Testing with VirtualBox 6.1

**Comment by nicolargo** [comment]
High @bermudi, 

It is a recurrent question regarding the way monitoring tools report used memory.

Glances uses more or less the Htop algorithm (see this post https://unix.stackexchange.com/questions/65835/htop-reporting-much-higher-memory-usage-than-free-or-top).

So the Glances used memory = total - free with free = available + buffers + cached.

An update of the documentation will be done.

Nicolas

**Comment by bermudi** [comment]
Don't mean to be a contrarian but `htop` agrees with `top` and `free -m` while `glances` reports double the amount reported by all the others.

[![glances-htop.png](https://i.postimg.cc/15zxHTGJ/glances-htop.png)](https://postimg.cc/F1wnFTnL)

**Comment by nicolargo** [comment]
Not reproduced on my system:

![Selection_008](https://user-images.githubusercontent.com/776747/131300270-fd8e641b-1ef6-478b-98f0-dfc44dd5c776.png)

**Comment by bermudi** [comment]
here's reproduced on baremetal but the difference is not as big as in VM with only 2 of ram. So it is an issue with scale and low-ram systems where the way glances calculates free ram can lead to very different impressions of system usage. 



[![Screenshot-at-2021-08-30-09-41-48.png](https://i.postimg.cc/NFH6ks0Z/Screenshot-at-2021-08-30-09-41-48.png)](https://postimg.cc/sG3GVR7J)
