### ISSUE TITLE
File age filter on Folders

### ISSUE THREAD

**Issue by Inrego** [nicolargo/glances#1925]
**Describe the solution you'd like**
I'd love to be able to set a file age filter on the folders integration. For example, I'd like to show the size of files in a folder that is more than 48 hours old.

**Additional context**
I'm running an upload script every night, that uploads files that are older than 48 hours old to the cloud. I'd love an overview to see how much is ready to be uploaded.

**Comment by nicolargo** [comment]
Hi @Inrego 

for this kind of need, please use AMP: https://glances.readthedocs.io/en/latest/aoa/amps.html

Example:

Create a shell script (/tmp/size.sh) with the following content:

    find /home/nicolargo/Downloads/ -mtime +10 -print0 | du -hc --files0-from - | tail -n 1

Add the following section at the end of your Glances configuration file:

```
[amp_size_old_files]
enable=true
refresh=60
one_line=true
command=sh /tmp/size.sh
```

Run Glances and...

![image](https://user-images.githubusercontent.com/776747/133880169-447536a1-5978-4db1-93cb-511cb4a48991.png)

**Comment by Inrego** [comment]
Awesome! I had looked for something in the documentation, but didn't think to look through amp. Thanks
