### ISSUE TITLE
Running glances under Docker image results in no smart support

### ISSUE THREAD

**Issue by zmanji** [nicolargo/glances#1926]
**Describe the bug**
When using the `latest-full` Docker container, the smart plugin does not work.

**To Reproduce**
1. Pull the latest `latest-full`  docker image
2. Run the docker image like so `/usr/bin/docker run --rm --name glances
    -v /var/run/docker.sock:/var/run/docker.sock:ro
    --device=/dev/sda:/dev/sda
    -e GLANCES_OPT="-w  --enable-plugin smart"
     nicolargo/glances:3.2.3.1-full`

3. Observe no smart data available even though the `/dev/sda` device is available

This is because inside the container there is no `smartctl` available. To fix this, the Dockerfile needs to be adjusted to include `smartmontools`

**Comment by michaelblight** [comment]
I'm struggling to get this to work still (using 3.2.6.4-full or latest). If I connect to the container, I can run smartctl and confirm it's enabled on '/dev/sda'. However, when I run it with the following docker command, I don't see any SMART info in the web interface. I have tried `--priveleged` and/or `--device`.
```
sudo docker run -it \
        --restart=unless-stopped \
        --pid host \
        --network host \
        --privileged \
        --device=/dev/sda:/dev/sda \
        -e TZ="Australia/Melbourne" \
        -v /etc/localtime:/etc/localtime \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -v /data/docker/glances/data/conf:/glances/conf \
        -v /data:/data:ro \
        -v /boot:/boot:ro \
        -e GLANCES_OPT="-w --enable-plugin smart" \
        --name glances \
        nicolargo/glances
```
