### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by GabrielSturtevant** [nicolargo/glances#1928]
I am not sure where else to bring this up, but upon installing glances on Ubuntu server 18.04 via apt, pip, and even the deb offered in the releases section of github, I am greeted with the same message: Bus error (core dumped).

If there is a better place to post this issue, please let me know and I will happily post it there.

**Comment by nicolargo** [comment]
Strange... try to uninstall all version:

```
apt-get remove glances
pip uinstall glances
```

Then install it again:

   pip install glances

Nicolas

**Comment by RazCrimson** [comment]
Closing stale issue.
