### ISSUE TITLE
No Nvidia GPU info in Webview (still)

### ISSUE THREAD

**Issue by Moondownr** [nicolargo/glances#1933]
**Describe the bug**
Nvidia gpu info is displayed correctly in 'normal' mode, but absent from webview. Previous issues mentioned that it should had been added in 3.1.7, but I'm using 3.2.2 and still don't see it.

**To Reproduce**
1. Start Glances in local mode - nvidia gpu temp and memory info present.
2. Start Glances in webview mode (with -w and --password via systemd service, as same user as in step 1) - no gpu info present.

**Expected behavior**
Webview displaying same info that normal mode does.

**Desktop (please complete the following information):**
 - OS: GNU/Linux Ubuntu 20.04
 - Glances Version - 3.2.2
 

![Screenshot at 2021-10-01 23-11-23](https://user-images.githubusercontent.com/23419209/135680941-99129f80-33b5-4d10-86cc-8a66a24c81cb.png)

![Screenshot 2021-10-01 at 23-11-31 minimoon - Glances](https://user-images.githubusercontent.com/23419209/135681276-6dc66780-9bf6-4dcd-93b9-eb20c5faaa7f.jpg)

**Comment by notFloran** [comment]
Can you paste here the content of http://0.0.0.0:61208/api/3/gpu ?

**Comment by Moondownr** [comment]
Sure

![Screenshot 2021-10-02 at 14-33-52 Screenshot](https://user-images.githubusercontent.com/23419209/135714340-deb8877f-0fbd-4d47-85cc-d43c6bc92a49.png)

JSON and RawData are empty.

**Comment by RazCrimson** [comment]
@Moondownr 
Does it happen even when u run it manually like `glances -w` or the it occur only when you run it as a systemd service?

**Comment by Moondownr** [comment]
@RazCrimson Both.

**Comment by Moondownr** [comment]
@RazCrimson @notFloran  @mjc  I apologize. Upon checking, I found out that now even regular glances (not web mode) wouldn't show GPU.
In fact, I had two versions of glances on my system (one from apt and one from pip) and that was what was causing all the issues. Everything is fixed and working properly now.
Sorry for wasting everyone's time, this can be closed.
