### ISSUE TITLE
--sort-processes option doesn't work in WebUI

### ISSUE THREAD

**Issue by ghost** [nicolargo/glances#1937]
`glances -w -B 127.0.0.1 --sort-processes memory_percent --hide-kernel-threads`

This isn't sorting by memory_percent, it's still sorting by cpu_percent. The kernel threads are hidden though.

But `glances --sort-processes memory_percent` in the terminal does work.

**Comment by nicolargo** [comment]
Not reproduced on Glances 4.0+
