### ISSUE TITLE
glances in clientmode quits to command-line with output 'alias'

### ISSUE THREAD

**Issue by sashanke** [nicolargo/glances#1938]
**Describe the bug**
When i start glances, it quits back to command-line with output 'alias'.

**To Reproduce**
1. Start Glances with the followings options '-c 192.168.xx.xx'
2. See output 'alias'

**Expected behavior**
Connect to glances server at 192.168.xx.xx

**Screenshots**
![glances error output](https://i.imgur.com/au54Lce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Glances Version: Glances v3.2.3.1 with PsUtil v5.8.0
 - Glances logs file:

        2021-10-27 13:40:08,831 -- WARNING -- PsUtil can not grab processes gids ('Process' object has no attribute 'gids')
        2021-10-27 13:40:08,831 -- INFO -- Start Glances 3.2.3.1
        2021-10-27 13:40:08,831 -- INFO -- CPython 3.9.7 and psutil 5.8.0 detected
        2021-10-27 13:40:08,846 -- INFO -- Start GlancesClient mode
        2021-10-27 13:40:08,940 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
        2021-10-27 13:40:08,940 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
        2021-10-27 13:40:09,643 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
        2021-10-27 13:40:09,643 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
        2021-10-27 13:40:09,956 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
        2021-10-27 13:40:10,471 -- CRITICAL -- 'alias'

 - Glances test: 

        ===========================================================
        Glances version [94m3.2.3.1[0m with PsUtil [94m5.8.0[0m[0m
        ===========================================================
        [94malert         [92m[OK]   [94m 0.00000s [0m[][0m
        [94mamps          [92m[OK]   [94m 0.00000s [0m[][0m
        [94mcloud         [92m[OK]   [94m 0.00000s [0m{}[0m
        [94mconnections   [92m[OK]   [94m 0.00000s [0m{'LISTEN': 31, 'ESTABLISHED': 30, 'SYN[0m
        [94mcore          [92m[OK]   [94m 0.00000s [0m{'phys': 4, 'log': 4}[0m
        [94mcpu           [92m[OK]   [94m 0.00000s [0m{'total': 12.4, 'user': 2.5, 'system':[0m
        [94mdiskio        [92m[OK]   [94m 0.00000s [93mkey=disk_name [0m[{'time_since_update': 3[0m
        [94mdocker        [92m[OK]   [94m 0.00000s [0m[][0m
        [94mfolders       [92m[OK]   [94m 0.00000s [0m[][0m
        [94mfs            [92m[OK]   [94m 0.01566s [93mkey=mnt_point [0m[{'device_name': 'C:\\',[0m
        [94mgpu           [92m[OK]   [94m 0.00000s [0m[][0m
        [94mhelp          [92m[OK]   [94m 0.00000s [0mNone[0m
        [94mip            [92m[OK]   [94m 0.01558s [0m{'address': '192.168.80.160', 'mask': [0m
        [94mirq           [92m[OK]   [94m 0.00000s [0m[][0m
        [94mload          [92m[OK]   [94m 0.00000s [0m{'min1': 0.0, 'min5': 0.0, 'min15': 0.[0m
        [94mmem           [92m[OK]   [94m 0.00000s [0m{'total': 16845619200, 'available': 11[0m
        [94mmemswap       [92m[OK]   [94m 0.00000s [0m{'total': 19395756032, 'used': 4929486[0m
        [94mnetwork       [92m[OK]   [94m 0.03127s [93mkey=interface_name [0m[{'interface_name':[0m
        [94mnow           [92m[OK]   [94m 0.00000s [0m2021-10-27 13:43:46 +0200[0m
        [94mpercpu        [92m[OK]   [94m 0.00000s [93mkey=cpu_number [0m[{'key': 'cpu_number', [0m
        [94mports         [92m[OK]   [94m 0.00000s [0m[][0m
        [94mprocesscount  [92m[OK]   [94m 0.64062s [0m{'total': 192, 'running': 188, 'sleepi[0m
        [94mprocesslist   [92m[OK]   [94m 0.00000s [93mkey=pid [0m[{'name': 'python.exe', 'cpu_t[0m
        [94mpsutilversion [92m[OK]   [94m 0.00000s [0m(5, 8, 0)[0m
        [94mquicklook     [92m[OK]   [94m 0.00000s [0m{'cpu': 12.4, 'percpu': [{'key': 'cpu_[0m
        [94mraid          [92m[OK]   [94m 0.00000s [0m{}[0m
        [94msensors       [92m[OK]   [94m 0.00000s [0m[][0m
        [94msmart[0m         [N/A][0m[0m
        [94msystem        [92m[OK]   [94m 0.00000s [0m{'os_name': 'Windows', 'hostname': 'LD[0m
        [94muptime        [92m[OK]   [94m 0.00000s [0m{'seconds': 3874}[0m
        [94mwifi          [92m[OK]   [94m 0.00000s [0m[][0m

**Additional context**

        $ pip list
        Package            Version
        ------------------ ---------
        bernhard           0.2.6
        bottle             0.12.19
        certifi            2021.10.8
        charset-normalizer 2.0.7
        chevron            0.14.0
        defusedxml         0.7.1
        future             0.18.2
        Glances            3.2.3.1
        idna               3.3
        ifaddr             0.1.7
        netifaces          0.11.0
        pbkdf2             1.3
        pip                21.3.1
        ply                3.11
        protobuf           3.19.0
        psutil             5.8.0
        py3nvml            0.2.6
        pyasn1             0.4.8
        pycryptodomex      3.11.0
        pygal              2.4.0
        pymdstat           0.4.2
        pySMART.smartx     0.3.10
        pysmi              0.3.4
        pysnmp             4.4.12
        pywin32            227
        requests           2.26.0
        scandir            1.10.0
        setuptools         57.4.0
        sparklines         0.4.2
        urllib3            1.26.7
        websocket-client   1.2.1
        windows-curses     2.2.0
        xmltodict          0.12.0
        zeroconf           0.36.9
        
        $ py --version
        Python 3.9.7

**Comment by nicolargo** [comment]
Hi @saschanke 

need more information concerning the Glances server side: version, OS ?

Can you also start the Glances client with the -d (debug) option and paste/bin the log ?

**Comment by saschanke** [comment]
server side: Glances v3.1.3 with psutil v5.5.1 (ubuntu repo)

    $apt info glances
    Package: glances
    Version: 3.1.3-1
    Priority: extra
    Section: universe/utils
    Origin: Ubuntu
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Original-Maintainer: Daniel Echeverry <epsilon@debian.org>
    Bugs: https://bugs.launchpad.net/ubuntu/+filebug
    Installed-Size: 6.377 kB
    Pre-Depends: init-system-helpers (>= 1.54~)
    Depends: adduser, lsb-base (>= 3.0-6), node-normalize.css, python3-pkg-resources, python3-future, python3-psutil (>= 2.0.0), python3:any
    Recommends: hddtemp, lm-sensors, python3-bottle, python3-docker, python3-influxdb, python3-matplotlib, python3-netifaces, python3-pysnmp4, python3-pystache
    Suggests: glances-doc, python3-pynvml
    Homepage: https://nicolargo.github.com/glances/
    Download-Size: 845 kB
    APT-Manual-Installed: yes
    APT-Sources: http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
    Description: Curses-based monitoring tool
     Glances is a curses-based monitoring tool for GNU/Linux or BSD OS.
     Glances uses the PsUtil library to get information from your system.
     .
     It monitors CPU, load, memory, network bandwidth, disk I/O, disk use, process.


glances debug output: 

https://pastebin.com/4kceiWVr

**Comment by RazCrimson** [comment]
Closing as it's not reproducible
