### ISSUE TITLE
Fix: Docker plugin - Invalid Network stats for Containers

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#1943]
**Describe the bug**
The networks stats shown by glances for docker containers always remains at 0b, even when the containers are transferring data

**To Reproduce**
1. Have Glances running with the docker plugin an a host with any container that transfers data over a port.
2. Connect to that port and transfer data.
3. See glances still showing 0b for network transfer

**Expected behavior**
Show the proper network usage

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/52282402/140536038-082cde15-46f2-4edb-bb2c-fced3bcad1a6.png)

Expected:
![image](https://user-images.githubusercontent.com/52282402/140534275-967922c9-c2b1-4332-9bef-b8a3e7f7ab03.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Glances Version: Glances v3.2.3 with PsUtil v5.8.0
 - Glances logs: [glances.log](https://github.com/nicolargo/glances/files/7487131/glances.log)
 - Glances test:
 ```=========================================================
Glances version 3.2.3 with PsUtil 5.8.0
=========================================================
alert         [OK]    0.00002s []
amps          [OK]    0.00002s key=name [{'key': 'name', 'name': 'Dropbox', 'result': None, 'refresh': 3.0, 'ti
cloud         [OK]    0.00002s {}
connections   [N/A]
core          [OK]    0.00108s {'phys': 6, 'log': 12}
cpu           [OK]    0.00002s {'total': 14.4, 'user': 11.5, 'nice': 0.0, 'system': 2.6, 'idle': 84.8, 'iowait'
diskio        [OK]    0.00001s key=disk_name [{'time_since_update': 1, 'disk_name': 'nvme0n1', 'read_count': 0,
docker        [OK]    0.00014s key=name [{'key': 'name', 'name': 'portainer', 'Names': ['portainer'], 'Id': '26
folders       [OK]    0.00002s []
fs            [OK]    0.00001s key=mnt_point [{'device_name': '/dev/nvme0n1p2', 'fs_type': 'btrfs', 'mnt_point'
gpu           [OK]    0.00001s []
help          [OK]    0.00001s None
ip            [OK]    0.00001s {'address': '10.15.75.51', 'mask': '255.255.255.0', 'mask_cidr': 24, 'gateway': 
irq           [N/A]
load          [OK]    0.00001s {'min1': 1.46, 'min5': 1.65, 'min15': 2.18, 'cpucore': 12}
mem           [OK]    0.00001s {'total': 16721416192, 'available': 8226201600, 'percent': 50.8, 'used': 8495214
memswap       [OK]    0.00001s {'total': 17179865088, 'used': 4722696192, 'free': 12457168896, 'percent': 27.5,
network       [OK]    0.00140s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update':
now           [OK]    0.00003s 2021-11-05 21:02:47 IST
percpu        [OK]    0.00002s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 7.8, 'user': 3.5
ports         [OK]    0.00001s [{'host': '10.15.75.241', 'port': 0, 'description': 'DefaultGateway', 'refresh':
processcount  [OK]    0.00001s {'total': 409, 'running': 1, 'sleeping': 284, 'thread': 1848, 'pid_max': 0}
processlist   [OK]    0.00005s key=pid [{'memory_info': pmem(rss=1304514560, vms=11737747456, shared=29544448, 
psutilversion [OK]    0.00002s (5, 8, 0)
quicklook     [OK]    0.00002s {'cpu': 14.4, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 7.8, 'u
raid          [N/A]
sensors       [OK]    0.00001s key=label [{'label': 'Composite', 'value': 51, 'warning': 84, 'critical': 84, 'u
smart         [N/A]
system        [OK]    0.00001s {'os_name': 'Linux', 'hostname': 'ryon', 'platform': '64bit', 'linux_distro': 'A
uptime        [OK]    0.00001s {'seconds': 18441}
wifi          [N/A]
```

The problem is due to a typo in the plugin's `get_docker_network` method

This commit will fix it: https://github.com/RazCrimson/glances/commit/3e7fa12faf2e8bb0392c2604546b19a58d9ed4c8

I also have a couple of typo fixes for comments and minor changes for the docker plugin on this branch:
https://github.com/RazCrimson/glances/tree/docker-plugin-network-stats-typo-bug-fix

Might fix #1918 partially, making this a separate issue as that includes IO stats not being displayed too.
I think I might have found the fix to IOs not being displayed, but am not sure about it, will update that issue shortly.

Is it fine if I make a PR? 😅

**Comment by nicolargo** [comment]
For sure for the PR ! I will include it in the next release.
