### ISSUE TITLE
usage scenario: multiple servers in a single web client

### ISSUE THREAD

**Issue by polishcode** [nicolargo/glances#1953]
This is not a problem, rather asking for guidance.

My scenario is: I have a few linux hosts accessible via Internet (not on a local network).

I would like to have a single webpage that would allow me to switch between configured hosts/servers and display their statistics when selected. I do not want a setup of one webpage <-> one host.

I would like some easy solution, do not want to setup other specialized tools, as the setup is for my spare time, non-commercial.

Thanks,
Piotr

**Comment by RazCrimson** [comment]
Its gonna be bit of a overkill, but if you plan to use glances along with some other services at a small scale, then something like [Organizr ](https://github.com/causefx/Organizr) is worth a shot.

**Comment by nicolargo** [comment]
Hi @polishcode 

a previous issue is already opened for this need: https://github.com/nicolargo/glances/issues/1121

Nicolargo

**Comment by polishcode** [comment]
Thanks @RazCrimson for suggestion.
Thanks @nicolargo for reference, did not find that issue before posting.
Closing then as a duplicate.
