### ISSUE TITLE
Add a code formatter

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#1964]
**Is your feature request related to a problem? Please describe.**
The code base is cluttered with different line sizes and complicated formatting. It would be better to standardize them.

**Describe the solution you'd like**
Add a code formatter that standardizes the code based on a set of linting rules (and possibly a workflow that tests the PRs for these rules/standard too)

Currently one simple option that I see is using [black](https://github.com/psf/black). Other options that I see include [autopep8](https://github.com/hhatto/autopep8) and [yapf](https://github.com/google/yapf).

**Comment by RazCrimson** [comment]
black seems to be the simplest solution.

**Comment by nicolargo** [comment]
@RazCrimson Agree, the linter (black looks great) should be included in the test pipeline. So it must be included in the test section of the Makefile  (https://github.com/nicolargo/glances/blob/develop/Makefile#L28-L31). Also do not forget to add the dep in the https://github.com/nicolargo/glances/blob/develop/dev-requirements.txt file.

For the rules we can start with a limited scope and harden it in the future...
