### ISSUE TITLE
Invalid version warning?

### ISSUE THREAD

**Issue by bulletmark** [nicolargo/glances#1966]
Glances updated from 3.2.3-2 to 3.2.4-1 on Arch Linux today. When I run it I get:
```
lt:~ glances
You are using Glances version 3.2.4, however version 3.2.4.2 is available.
You should consider upgrading using: pip install --upgrade glances
```
I was about to raise an Arch issue about this but I see from the [release page](https://github.com/nicolargo/glances/releases) here that glances is only released at X.X.X points so there is no release 3.2.4.2. Seems to me that the above version check should limit itself to an X.X.X check?

**Comment by nicolargo** [comment]
Nope the last release is https://github.com/nicolargo/glances/releases/tag/v3.2.4.2

But in your case, the packager should disable the version check feature by setting the **check_update=false** in the Glances configuration file (see https://github.com/nicolargo/glances/blob/develop/conf/glances.conf#L11). So you can raise an Arch issue :)

**Comment by bulletmark** [comment]
But why is that release not listed on the [release page](https://github.com/nicolargo/glances/releases)?

**Comment by bulletmark** [comment]
@nicolargo, well you never replied here but I see you did go and add 3.2.4.2 to the releases page.

**Comment by nicolargo** [comment]
I did not reply because there is no need to reply.
Packager have to look on the last official Pypi delivery not the Github release page that is not updated automatically.
