### ISSUE TITLE
Errno 21 when starting glances in docker on RPi4 with config stored locally

### ISSUE THREAD

**Issue by pluim003** [nicolargo/glances#1972]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

For any questions concerning installation or use, please open a discussion (https://github.com/nicolargo/glances/discussions), not an issue.

#### Description

For a bug: Describe the bug and list the steps you used when the issue occurred.

Installed nicolargo-3.2-full. First with the webserver option and no local config. That worked like a charm. When I wanted to modify the hostname as something with c7fsa5gsda isn´t very nice I modified file hostname to find out that after a reboot it was back to its original value. Then I decided to do the following: stopped this container, removed it and made a new one:

docker run -v /etc/docker-glances/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -it nicolargo/glances:3.2.0-full

when starting up the file /etc/docker-glances/glances.conf is created but seems to be a directory:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/usr/local/lib/python3.9/site-packages/glances/__main__.py", line 29, in <module>

    glances.main()

  File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 146, in main

    core = GlancesMain()

  File "/usr/local/lib/python3.9/site-packages/glances/main.py", line 101, in __init__

    self.args = self.parse_args()

  File "/usr/local/lib/python3.9/site-packages/glances/main.py", line 265, in parse_args

    self.config = Config(args.conf_file)

  File "/usr/local/lib/python3.9/site-packages/glances/config.py", line 115, in __init__

    self.read()

  File "/usr/local/lib/python3.9/site-packages/glances/config.py", line 149, in read

    with open(config_file, encoding='utf-8') as f:

IsADirectoryError: [Errno 21] Is a directory: '/glances/conf/glances.conf'

After deleting the directory glances.conf and making a blank glances.conf I was able to start it.

But then I hadn't the webserver sohad to figure out more...

For an enhancement or new feature: Describe your needs.

#### Versions

* Glances & psutil (glances -V):
* Operating System (lsb_release -a):

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

See above. I'll have to dig further into this and will use the method with no external glances.conf

**Comment by nicolargo** [comment]
The /glances/conf/glances.conf should be a file not a directory...

Please can you run again the installation and execute the following command line:

    cat /glances/conf/glances.conf

**Comment by pluim003** [comment]
Hadn't looked into it for a while as I didn't use it. But gave it another try. Seems to be working fine, but no glances.conf at all (/glances/conf exists). But it's fine for me now at least. I'll close this for now. Thanx.
