### ISSUE TITLE
Missing commands in help "h" screen

### ISSUE THREAD

**Issue by FastThenLeft** [nicolargo/glances#1973]
**Describe the bug**
The below options are missing in the help "h" screen

**To Reproduce**
1. Start Glances with the followings options
2. Press the key 'h'
3. The following key commands are missing:
   A - Enable/disable Application Monitoring Process
   E - Erase current process filter
   K - Show/hide TCP connections
   k - Kill process
   M - Reset processes summary min/max
   N - Show/hide current time
   R - Show/hide RAID plugin
   W - Show/hide Wifi module
   4 - Enable/disable all but quick look and load module

**Expected behavior**
These commands should be listed on the help "h" screen

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Glances Version: v3.2.4.2 with PsUtil v5.8.0

**Comment by Jahenr** [comment]
Hi Nicolas

I am a new contributor, may I help with this issue?

Thanks
Regards
J

**Comment by nicolargo** [comment]
@Jahenr With pleasure ! All the work should be done in the  https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_help.py file. You can propose a pull-request when it is done.

I propose to organize the help screen with common feature on top of the screen.

**Comment by Jahenr** [comment]
Ok, thank you. I will let you know if I need any more info etc. 
Regards
J

**Comment by Jahenr** [comment]
I can reproduce the steps mentioned above, and also get the same results of the options missing from the help menu.

The options above are displayed in the man page of glances, but not when h is pressed when glances is running.

OS info:
Linux Mint 20.2
Glances 3.2.4.2
psutil 5.5.1
