### ISSUE TITLE
"N" command freezes/unfreezes the current time instead of show/hide

### ISSUE THREAD

**Issue by FastThenLeft** [nicolargo/glances#1974]
**Describe the bug**
On this page: https://glances.readthedocs.io/en/latest/cmds.html it states that the "N" command key shows/hides the current time. Instead, it freezes/unfreezes the time.

**To Reproduce**
1. Start Glances
2. Press the key 'N'
3. The current time freezes/unfreezes instead of show/hide like the documentation states.

**Expected behavior**
The current time should show/hide instead of freeze/unfreeze.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Glances Version: v3.2.4.2 with PsUtil v5.8.0

**Comment by nicolargo** [comment]
Reproduced on my side....
