### ISSUE TITLE
glances_ip.py plugin relies on low rating / malicious site domain

### ISSUE THREAD

**Issue by talf** [nicolargo/glances#1975]
**Describe the bug**
The `glances_ip.py` plugin relies on the https://ip.42.pl/raw for retrieving a machines public ip address. 
42.pl is classified as a malicious site which alarms all sort of security related tooling.

https://otx.alienvault.com/indicator/domain/ip.42.pl

This one should probably be removed or replaced with another vendor such as www.icanhazip.com 
https://otx.alienvault.com/indicator/domain/icanhazip.com

**To Reproduce**
Start Glances

**Expected behavior**
No low rating / malicious site should be communicated.

**Comment by nicolargo** [comment]
Done !

Thanks for the security warning.
