### ISSUE TITLE
--time parameter being ignored for client/server mode

### ISSUE THREAD

**Issue by enajx** [nicolargo/glances#1978]
I'm trying to export monitoring data using client/server mode and I want to increase the refresh rate from default 3s to 60s.

I have tried both defining it in the configuration file, also on the client side using `glances -c servername --time 60 --export csv --export-csv-file /home/username/glances_logs/servername.csv` and also on the server side `glances -s --time 60`, but they all are ignored and the result .csv file has information saved every 3s not 60s.

How could this be achieved?

**Comment by nicolargo** [comment]
Correct and reproduced on my side. Refresh --time option is not taken into account in any client/server mode (with or without export).
