### ISSUE TITLE
Is statsd output working?

### ISSUE THREAD

**Issue by dotmpe** [nicolargo/glances#1981]
The StatsD export is not generating any data for me, but I cannot find any other recent issue wrt to this export module. So either its working fine and I'm wrong or maybe its in disuse. Can anyone confirm either?

I tried to use the StatsD as a source in log analyzer but I wasn't getting anything and confirmed that this end was receiving using netcat.

I then tried the same for the glances end, but I'm not getting any data:
```
nc -l localhost -p 8125
```
```
glances --export statsd
```
```
glances -V
Glances v3.1.3 with psutil v5.5.1
```

Tested on recent ubuntu and debian.

**Comment by nicolargo** [comment]
Just tested with a simple Graphite server and it works:

![Selection_063](https://user-images.githubusercontent.com/776747/147548624-a78497b6-0a3c-401b-89b1-33b75378ed43.jpg)

![Selection_062](https://user-images.githubusercontent.com/776747/147548637-bcd00e83-be21-4472-9899-8e551705aef1.jpg)

**Comment by dotmpe** [comment]
Thank you for the reply. I realized I had tried TCP but not UDP, I now can see the data I was expecting as well.
```
nc -l -u localhost 8125
```
