### ISSUE TITLE
Make the processlist columns configurable (ex: Hide `user` column)

### ISSUE THREAD

**Issue by samtuke** [nicolargo/glances#1982]
Hi, using a small screen, can't read the process names (even using `/`). The `user` column isn't useful to me; `virt` also not so much -- both certainly less than the process names they pertain to. Is there a way to hide these cols? Thanks!

**Comment by nicolargo** [comment]
Not for the moment. But the feature is interesting.

**Comment by ChillarAnand** [comment]
Any plans on adding this feature?

**Comment by nicolargo** [comment]
Duplicated: follow in https://github.com/nicolargo/glances/issues/1524
