### ISSUE TITLE
Get running processes with cpu/mem list output as CSV/ JSON

### ISSUE THREAD

**Issue by a-y-u-1** [nicolargo/glances#1983]
**Export current running processes in system.**

I am trying to export all the current running processes as json/csv

**Describe the solution you'd like**

I am expecting the output be in similar lines as below command

top -n 1 -b -c

![image](https://user-images.githubusercontent.com/70471957/147746504-16c75f5b-6201-4313-b64c-9e2495f902aa.png)

![image](https://user-images.githubusercontent.com/70471957/147746563-4d1c01e0-81b8-4861-964d-f50de17f1982.png)

**Comment by nicolargo** [comment]
Duplicated: https://github.com/nicolargo/glances/issues/794
