### ISSUE TITLE
Web server status check endpoint

### ISSUE THREAD

**Issue by tommyalatalo** [nicolargo/glances#1988]
When deploying Glances in a service mesh there doesn't seem to be a way to make a lightweight health check to make sure that the application is healthy and running.

It would be great to have a health check endpoint implemented in the Glances web server. Something like `/health`, `/status` or `/ping`, so that it's possible to check the application when using service discovery tools like Consul for instance. The endpoint doesn't need to do more than just respond with `200` if the server is okay, and possibly some error code if something is not working.

It's of course possible to keep requesting the `/` endpoint to check the server, but that requests unnecessary amounts of data frequently, and is a waste of system resources.

**Comment by nicolargo** [comment]
Good idea !

Will be implemented in the next version.

**Comment by nicolargo** [comment]
Run: 
```
glances -C ./conf/glances.conf -w --disable-webui
Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
```

Check:
```
curl -I http://0.0.0.0:61208/api/3/status
HTTP/1.0 200 OK
```

Implementation done in the develop branch.

Documentation updated: https://github.com/nicolargo/glances/blob/develop/docs/api.rst#get-api-status

**Comment by tommyalatalo** [comment]
When will this be released in a stable docker image?
