### ISSUE TITLE
Doc for 'alert' Restfull/JSON API response

### ISSUE THREAD

**Issue by 17Halbe** [nicolargo/glances#1994]
**Is your feature request related to a problem? Please describe.**
The alert plugin Restfull/JSON API response is undocumented and/or not in line with the rest of the responses. It is missing the 'key' values
**Describe the solution you'd like**
Preferably: Adding Key values; else please document the response.

**Additional context**
The current response looks like:
```
[
  1642961040,
  1642961256,
  "WARNING",
  "MEM",
  88.70418062659719,
  82.54486757324095,
  80.62008918458108,
  5613.0509949803845,
  68,
  [],
  "",
  "memory_percent"
]
```
Explaining those values to me, or where to find an answer to my question, would be greatly appreciated!

**Comment by nicolargo** [comment]
Hi @17Halbe !

you are right. There is a whole in the documentation.

A a quick respond, the list returned by the API contents the following fields:

      ["begin",
       "end",
       "WARNING|CRITICAL",
       "CPU|LOAD|MEM",
       MAX, AVG, MIN, SUM, COUNT,
       [top3 process list],
       "Processes description",
       "top sort key"]

With:

- begin: event begin date (EPOCH)
- end: event end date (EPOCH) or -1 if the event is not finished
-  state WARNING or CRITICAL 
- max value encountered during the event
- average value encountered during the event
- min value encountered during the event
- sum value encountered during the event
- number of time the event have been threshold
- List of top 3 process for this event
- Events description
- Processes sort key

**Comment by 17Halbe** [comment]
Thanks a lot!
