### ISSUE TITLE
[Feature Request] Add line separators in the terminal output

### ISSUE THREAD

**Issue by tur1ngb0x** [nicolargo/glances#1996]
**Is your feature request related to a problem? Please describe.**
`$ glances` shows the data without separators/sections, sometimes making it difficult to visualize the text.

**Describe the solution you'd like**
`$ glances --show-sections` (or something similar ) which can make the terminal output more legible and easier to read.

**Describe alternatives you've considered**
Default Behaviour
![image](https://user-images.githubusercontent.com/25666761/152303683-c6ca14d9-874d-443f-b61c-27b8590bea4a.png)

Proposed Solution
![image](https://user-images.githubusercontent.com/25666761/152303557-88dfa4e4-da16-4b06-9dda-29a63ee2f7ae.png)

**Additional context**
* Ubuntu 20.04.3 LTS
* Glances v3.2.4.2 with PsUtil v5.9.0
* Installed using ` $ python3 -m pip install --user --upgrade glances`

**Comment by nicolargo** [comment]
First try on the develop branch (but only for top plugins).
Enable thanks to the --enable-seprator option for the command line.

**Comment by FastThenLeft** [comment]
Looks nice! I'm hoping there will be a config file option for it in the future?

**Comment by RazCrimson** [comment]
Should be possible, but I think this should be a made as a part of #2019

Rich had Tables and Layouts so there should be options to have borders/seperators
