### ISSUE TITLE
glances -4,glances -6,glances -1 error

### ISSUE THREAD

**Issue by newyorkthink** [nicolargo/glances#2000]
![image](https://user-images.githubusercontent.com/87791643/153581386-ed5d0404-0f19-4b29-9752-efbaa968e544.png)
![image](https://user-images.githubusercontent.com/87791643/153581402-c7433eb2-c2a8-4275-a4f9-f081409be5fb.png)
![image](https://user-images.githubusercontent.com/87791643/153581465-7e41146f-a882-4b97-9cc6-610cfdfd27f5.png)

looking it ,cpu10 to cpu 16 not display cpu.

and g;amces -6 gpu, is not show gpu

**Comment by nicolargo** [comment]
Hi @newyorkthink 

It is not a bug, it's a feature to optimize space with high number of CPU core....
