### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by Artur2** [nicolargo/glances#2001]
**Describe the bug**
Memory consumption is too high, like for firefox process, but firefox is web browser

**To Reproduce**
1. Simple Start glances
2. Wait for 1 or 2 days of actively machine usage 
3. See in glances process started by python with consumption about 200-300mb memory

**Expected behavior**
Consumption about 50mb or less

**Desktop:**
 - OS: Mac OS X Monterey 12.2
 - Glances v3.1.7 with PsUtil v5.8.0
 
 Later I'll provide screenshots of running processes in glances
 So you can see amount of memory, consuming by glances process

Link for screenshots
Look at reserved memory of glances process

https://imgur.com/a/X1MZ5Lb

**Comment by nicolargo** [comment]
Memory consumption has been improved in Glances 3.2. Please upgrade and test again.

For your information, the first day Glances is ran, memory will increase because it stores the stats with a sliding window of 24h (see https://github.com/nicolargo/glances/blob/v3.1.7/conf/glances.conf#L10).

**Comment by Nuuki9** [comment]
I'm seeing what appears to be an ongoing memory leak, running the latest version.

Here's the memory usage of my Glances container over the last few months:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/30313491/186630847-fad66b37-b030-4c6f-aa8c-8f62a7b40672.png">

It starts at around 60Mb but has risen to as much as 1.4Gb.

**Comment by nicolargo** [comment]
Linked with issue https://github.com/nicolargo/glances/issues/1447
