### ISSUE TITLE
The gpu temperature unit are displayed incorrectly in web ui

### ISSUE THREAD

**Issue by yangyize** [nicolargo/glances#2002]
**Describe the bug**
The gpu temperature unit are displayed incorrectly in web ui. 

`glances -w`

Glances Version v3.2.4.2

![2022-02-20 13-59-04 的屏幕截图](https://user-images.githubusercontent.com/8913465/154830713-cf002257-10f3-4a69-9268-d55feb0de7de.png)

**Comment by nicolargo** [comment]
Corrected, thanks for the bug report @yangyize !
