### ISSUE TITLE
Docker Glances not measuring RDMA NFS traffic on interface?

### ISSUE THREAD

**Issue by sotiris-bos** [nicolargo/glances#2016]
**Describe the bug**
I am sorry if this is a stupid question and out of my "league". I have glances running on an Arch Linux host that has an RDMA NFS share. It seems as if glances is not seeing the RDMA traffic when it can see the Samba traffic just fine. Is this to be expected?

Thanks!

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.10.74-1-lts
 - Glances v3.2.4.2 with PsUtil v5.8.0
 - Docker image nicolargo/glances:latest

**Comment by nicolargo** [comment]
Hi @sotiris-bos 

there is no stupid question here :)
Glances do not see if it is a TCP or RDMA NFS share, it works at an higher level thanks to the PsUtil lib.

Please can you paste/copy the result of the following commands:

```
$ python
>>> import psutil
>>> psutil.version
>>> psutil.disk_partitions(True)
```

**Comment by RazCrimson** [comment]
@sotiris-bos 
Could you tell me what exactly you meant by glances being able to see Samba Traffic but not the RDMA Traffic?

Also more details about the RDMA setup would be helpful.

**Comment by RazCrimson** [comment]
Closing this as no response over a year.
