### ISSUE TITLE
Server/Client container mode

### ISSUE THREAD

**Issue by martadinata666** [nicolargo/glances#2020]
**Describe the bug**
glances cant run on server mode when containerized

**To Reproduce**
1. `glances -d -s -q` on docker mode

On normal condition (not docker) it will show export
```
glances -s -d -q                    
Glances XML-RPC server is running on 0.0.0.0:61209
/usr/lib/python3/dist-packages/psutil/_pslinux.py:1222: RuntimeWarning: ignoring OSError(61, 'No data available') for file '/sys/class/hwmon/hwmon4/temp1_input'
  warnings.warn("ignoring %r for file %r" % (err, path),
```
and continous run until user stopped. `Ctrl+C`

On other hand in docker case, as it no terminal to interact with glances throw error `couldn't find terminal`
```
glances_gitlab.1.waj9tla9ajd7@GITLAB    | Traceback (most recent call last):
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/local/bin/glances", line 8, in <module>
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     sys.exit(main())
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/local/lib/python3.9/dist-packages/glances/__init__.py", line 150, in main
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     start(config=core.get_config(), args=core.get_args())
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/local/lib/python3.9/dist-packages/glances/__init__.py", line 109, in start
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     mode = GlancesMode(config=config, args=args)
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/local/lib/python3.9/dist-packages/glances/standalone.py", line 108, in __init__
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     self.screen = GlancesCursesStandalone(config=config, args=args)
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/local/lib/python3.9/dist-packages/glances/outputs/glances_curses.py", line 139, in __init__
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     self.screen = curses.initscr()
glances_gitlab.1.waj9tla9ajd7@GITLAB    |   File "/usr/lib/python3.9/curses/__init__.py", line 29, in initscr
glances_gitlab.1.waj9tla9ajd7@GITLAB    |     setupterm(term=_os.environ.get("TERM", "unknown"),
glances_gitlab.1.waj9tla9ajd7@GITLAB    | _curses.error: setupterm: could not find terminal
```

**Expected behavior**
The server mode will run without error, something like `headless` mode. So glances doesn't need to interact with terminal.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 arm64, amd64
 - Docker `glances:latest`

Is there any suggestion what to change or add to my options beside `-s -d -q`, thanks.

**Comment by nicolargo** [comment]
Hi @martadinata666 !

what's your goal ?

**Comment by martadinata666** [comment]
Hi, my main purpose in to deploy glances on different server and monitor to single client with docker, i just cant make the server mode work.

**Comment by gkieninger** [comment]
Hi @martadinata666!
did you have any success on this. I also want to monitor several servers from one single point with webserver mode, but nothing is working. I use everywhere glances with docker

**Comment by martadinata666** [comment]
> Hi @martadinata666! did you have any success on this. I also want to monitor several servers from one single point with webserver mode, but nothing is working. I use everywhere glances with docker

So my workaround is like this, deploy glances on all server i had, then use webterminal i use `wetty`, install glances there and run glances client mode from it. I just hope one day glances web will support server/client mode.

**Comment by RazCrimson** [comment]
> did you have any success on this. I also want to monitor several servers from one single point with webserver mode, but nothing is working. I use everywhere glances with docker

Issue for Web server and XML-RPC server running at the same: https://github.com/nicolargo/glances/issues/995
