### ISSUE TITLE
Update external IP address

### ISSUE THREAD

**Issue by vvstubbs** [nicolargo/glances#2028]
At the top of the display where:

     **machine.name (openSUSE Tumbleweed 20220408 64bit / Linux 5.17.1-1-default) - IP 192.168.0.150/24 Pub 111.111.111.111**

is shown the Pub 111.111.111.111 is only refreshed when glances is loaded. If that IP where to change in the case of a VPN address the new address is never refreshed.

I was wondering if this might be something that could be looked into?

**Comment by RazCrimson** [comment]
@nicolargo 
Right now the IP is set during initialization of the IP plugin.
We could change it so that it gets refreshed every `t` seconds.

What do you think?

**Comment by vvstubbs** [comment]
Yes if it could be refreshed somewhere around every 200-300 seconds it would no cause to much additional load and in my case my VPN scripts only check / change VPN connects every 300 seconds. That way if a VPN connect has gone stale down time is 5 min or less. So an up date of that amount of time would keep things is sync.

For more flexibility, the IP refresh time should configurable in the glances.conf file with a suggested range in the #remarks, and maybe a set minimum no lower than say 120 sec.

**Comment by vvstubbs** [comment]
Well that was quick, wast his something already in the pipeline?

**Comment by RazCrimson** [comment]
Nah, I was just a bit bored and it wasn't that big of a change :)

**Comment by vvstubbs** [comment]
Cool, so when will it be merged in to try it out

**Comment by RazCrimson** [comment]
We'll need to wait for the maintainer to merge it. It would probably be around the weekend.

If you are really interested to try it out and wanna try it out ASAP, you can clone the repo and try running it.
I can guide you if you want some help for that.

**Comment by vvstubbs** [comment]
That's okay I'll wait til the weekend, I do appreciate all your help

**Comment by nicolargo** [comment]
Merged on the develop branch.

Thanks for the issue @vvstubbs and @RazCrimson for the contribution ! :)

**Comment by vvstubbs** [comment]
Thanks @nicolargo and @RazCrimson I'll be eager to give it a try later today. Thanks for the quick turn around, it will help a lot.
