### ISSUE TITLE
Api endpoint does not exist

### ISSUE THREAD

**Issue by patrickelectric** [nicolargo/glances#2032]
**Describe the bug**
`http://0.0.0.0:61208/api/3/` returns 404

**To Reproduce**
1. Start Glances with the followings options 'glances -w --disable-webui'
2. Open browser: `http://0.0.0.0:61208/api/3/`
![image](https://user-images.githubusercontent.com/1215497/163577574-fa67c48b-1706-486c-b4e8-efec40a90f77.png)

**Expected behavior**
I don't know, it should shows something like an swagger api or any documentation format since this is what the commandline outputs as address.

**Screenshots**
![image](https://user-images.githubusercontent.com/1215497/163577206-067f9e34-3ae1-47a6-8c45-16f3ef1d8b69.png)

**Desktop (please complete the following information):**
 - OS: Arch
 - Glances Version: Glances v3.2.4 with PsUtil v5.9.0
 - Glances logs file:
```
2022-04-15 10:31:38,425 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2022-04-15 10:31:38,426 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2022-04-15 10:31:38,428 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2022-04-15 10:31:38,428 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2022-04-15 10:31:38,429 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2022-04-15 10:31:38,437 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2022-04-15 10:31:38,615 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2022-04-15 10:31:38,617 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2022-04-15 10:36:58,286 -- INFO -- Start Glances 3.2.4
2022-04-15 10:36:58,286 -- INFO -- CPython 3.10.4 (/usr/bin/python) and psutil 5.9.0 detected
```
 - Glances test:
```
================================================================================================================
Glances 3.2.4 (/usr/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.4 (/usr/bin/python)
PsUtil 5.9.0 (/usr/lib/python3.10/site-packages/psutil/__init__.py)
================================================================================================================
alert         [OK]    0.00002s []
amps          [OK]    0.00017s key=name [{'key': 'name', 'name': 'Dropbox', 'result': None, 'refresh':
cloud         [OK]    0.00003s {}
connections   [N/A]
core          [OK]    0.00069s {'phys': 8, 'log': 16}
cpu           [OK]    0.00032s {'total': 10.6, 'user': 7.3, 'nice': 0.0, 'system': 3.0, 'idle': 89.4, 
diskio        [OK]    0.00041s key=disk_name [{'time_since_update': 3.134064197540283, 'disk_name': 's
docker        [OK]    0.00003s []
folders       [OK]    0.00002s []
fs            [OK]    0.00038s key=mnt_point [{'device_name': '/dev/sda1', 'fs_type': 'ext4', 'mnt_poi
gpu           [OK]    0.00002s []
help          [OK]    0.00000s None
ip            [OK]    0.00032s {'address': '192.168.0.40', 'mask': '255.255.255.0', 'mask_cidr': 24, '
irq           [N/A]
load          [OK]    0.00003s {'min1': 1.6787109375, 'min5': 1.5107421875, 'min15': 1.47265625, 'cpuc
mem           [OK]    0.00012s {'total': 33668722688, 'available': 16312672256, 'percent': 51.5, 'used
memswap       [OK]    0.00017s {'total': 17179865088, 'used': 0, 'free': 17179865088, 'percent': 0.0, 
network       [OK]    0.00045s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since
now           [OK]    0.00001s 2022-04-15 10:37:50 -03
percpu        [OK]    0.00056s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 13.1, '
ports         [OK]    0.00001s [{'host': '192.168.0.1', 'port': 0, 'description': 'DefaultGateway', 'r
processcount  [OK]    0.09613s {'total': 501, 'running': 1, 'sleeping': 382, 'thread': 2781, 'pid_max'
processlist   [OK]    0.00033s key=pid [{'status': 'S', 'memory_percent': 1.1314367091679793, 'name': 
psutilversion [OK]    0.00002s (5, 9, 0)
quicklook     [OK]    0.00028s {'cpu': 10.6, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total'
raid          [N/A]
sensors       [OK]    0.00000s key=label [{'label': 'acpitz 1', 'value': 16, 'warning': 20, 'critical'
smart         [N/A]
system        [OK]    0.00001s {'os_name': 'Linux', 'hostname': 'pichau', 'platform': '64bit', 'linux_
uptime        [OK]    0.00010s {'seconds': 62313}
wifi          [N/A]
You are using Glances version 3.2.4, however version 3.2.5 is available.
You should consider upgrading using: pip install --upgrade glances
You are using Glances version 3.2.4, however version 3.2.5 is available.
You should consider upgrading using: pip install --upgrade glances

```

**Additional context**
Nops

**Comment by nicolargo** [comment]
The --disable-webui disable the webui (what a surprise :)).
So the call to http://0.0.0.0:61208/api/3/ will bring you to a 404 error but a call to http://0.0.0.0:61208/api/3/mem/used will work like a charm (see the list of API call here: https://github.com/nicolargo/glances/blob/develop/docs/api.rst).

**Comment by ewoks** [comment]
Thanks for this @nicolargo I didn't know about api.rst :+1:  
I run glances in a container on synology and start it **just** with `-w` OPT, but get 404 on accessing  `local-ip:port`, `local-ip:port/api/4/status` or any other endpoint. Probably beginner issue but it would be helpful to know how to use bind/port OPTS. 

I tried "GLANCES_OPT=-w --bind 192.168.42.42 --port 4242", without success

```
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Address not available
```

**Comment by nicolargo** [comment]
What is your version ?

URL for Glances version 3: /api/3/status
URL for Glances version 4: /api/4/status

**Comment by ewoks** [comment]
Version of my container is `nicolargo/glances:latest-alpine` deployed today, so I'm surprised if api v4 isn't there...
Doesn't matter which I try, both you mentioned were returning 404

Now I am even more confused. As I was trying to undestand how to use `--bind` (probably `--bind 0.0.0.0` is the way), I realized it might even not be important. 

Starting it again just with `GLANCES_OPT=-w` ENV, `/api/3/status` or `/api/4/status` aren't available.
However, `/api/3/status/` returned **400** instead of 404. Bad Request?! I'm puzzled.
Turns out, there are few endpoints available ('alert', 'core', 'cpu', 'diskio', 'docker', ... 'system', 'uptime'), but the `status` isn't one of them. 

Few questions to understand why is this the case:
- is the image I referenced not the oldest, so I don't have v4 API? if so, how to find the latest image? Maybe latest built image doesn't have the latest code?
- is it so old that even `status` is not available?

**Comment by nicolargo** [comment]
Latest means latest release. Glances version 4 is under delopment. The
latest release if Glances 3.4.0.5.

**Comment by ewoks** [comment]
ok, that explains why v4 isn't available, it wasn't obvious to me.

It is still unclear why `api/3/status/` returns 404, while some other endpoints are available.

**Comment by danktankk** [comment]
same issue here as well

**Comment by ewoks** [comment]
@nicolargo regarding previously commented _"It is still unclear why api/3/status/ returns 404"_
is there an explanation of we missed something obvious?
