### ISSUE TITLE
Glances for Raspberry Pi OS 64Bit

### ISSUE THREAD

**Issue by Tatteredpql012542** [nicolargo/glances#2035]
Hello i really enjoy Galnces i was using it on my raspberry pi mini server but the Raspberry pi os has officially gone 64 bit 
And i took the chance to upgrade to 64 bit and i was sad to see ther is no Glances package found by apt-get

It would be really nice to add it to the officially repositorys
Thank you for your work

![εικόνα](https://user-images.githubusercontent.com/60512572/163851938-6653b0dd-a3dc-4716-8a2e-b7b310225899.png)

**Comment by nicolargo** [comment]
Hi @golem5G 

the Glances packaging for Debian like system encounters some issues: https://github.com/nicolargo/glances/issues/2021

My advice is to use the Pypi installation procedure: https://github.com/nicolargo/glances#pypi-the-standard-way

**Comment by RazCrimson** [comment]
Closing as pypi procedure is a viable installation method.

Any direct packagers for RPi repository are welcome to package glances directly.
