### ISSUE TITLE
Glances API not returning valid json

### ISSUE THREAD

**Issue by tomlut** [nicolargo/glances#2036]
**Describe the bug**
The glances API does not return valid json. It returns strings with single quotes. The json specification _requires_ double quotes. 

**To Reproduce**
1. Use any API query listed here: https://glances.readthedocs.io/en/latest/api.html

**Expected behavior**
Valid json to be returned. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: not relevant
 - Glances Version: 3.2.5
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**

**Comment by nicolargo** [comment]
It's just an issue when the API documentation is generated, the API return double quote:

```
$ curl http://localhost:61208/api/3/pluginslist
["now", "uptime", "ip", "percpu", "mem", "quicklook", "gpu", "amps", "sensors", "help", "psutilversion", "diskio", "processcount", "network", "processlist", "memswap", "load", "alert", "system", "folders", "ports", "core", "fs", "cpu", "cloud", "docker"] 
$ curl http://localhost:61208/api/3/alert
[[1650447206.0, -1, "WARNING", "MEM", 84.66831223320426, 83.93024259060182, 82.7343366766514, 251.79072777180548, 3, [], "", "memory_percent"]] 
$ curl http://localhost:61208/api/3/cpu
{"total": 12.4, "user": 8.1, "nice": 0.0, "system": 3.7, "idle": 87.9, "iowait": 0.0, "irq": 0.0, "softirq": 0.3, "steal": 0.0, "guest": 0.0, "guest_nice": 0.0, "time_since_update": 15.593244552612305, "cpucore": 4, "ctx_switches": 78493, "interrupts": 59521, "soft_interrupts": 27662, "syscalls": 0}
```
