### ISSUE TITLE
Glances v3.2.5 doesn't work with Home Assistant

### ISSUE THREAD

**Issue by SvbZ3r0** [nicolargo/glances#2038]
The latest version of Glances doesn't work in HomeAssistant.

I'm opening an issue here just in case somebody has some insight on what might have caused the issue.
The most that I understand is that it has something to do with Docker containers.

Ref: https://github.com/home-assistant/core/issues/70373

**Comment by nicolargo** [comment]
Duplicated issue: https://github.com/nicolargo/glances/issues/2031
