### ISSUE TITLE
Glances - battery sensor disappear when power supply disconnected

### ISSUE THREAD

**Issue by enricocelegon** [nicolargo/glances#2041]
**Describe the bug**
Battery charge is monitored when PC is conneted to power supply; when I disconnect the power supply "battery charge" sensor will be disable also. I'm not be able to monitoring battery charge.

**To Reproduce**
1. Start Glances
2. View "battery" sensor in Glances screen (at left of screen)
3. Disconnect power supply
4. You see that the "battery" sensor will disappear

**Desktop:**
 - OS: Ubuntu 20.04
 - Glances Version: Glances v3.1.3 with psutil v5.5.1

**Comment by nicolargo** [comment]
Do not reproduced on my side (Ubuntu 20.04, Glances 3.2.5 with PsUtil 5.5.1.

Start Glances with power supply plugged:

![Selection_034](https://user-images.githubusercontent.com/776747/166094673-f42dd34d-a21e-47ca-a52c-2a1aabd4d935.jpg)

Unplug power supply:

![Selection_035](https://user-images.githubusercontent.com/776747/166094686-cfd61fb9-810d-455a-875c-8be8fbe8cf1a.jpg)

Try to upgrade your Glances version to the latest one.

**Comment by enricocelegon** [comment]
Hi Nicolas.

I just upgrade glances in my Ubuntu machine but I still have this issue.

Maybe is necessary to modify glances.conf file. Please, could you suggest me the right config to monitor battery (in this moment I enabled sensor only (no other line was change in glances.conf))?




Thanks.

Bye.

Enrico

**Comment by RazCrimson** [comment]
Not reproducible on my end too.

@enricocelegon 
Could you give more specifics about your hardware setup?

**Comment by RazCrimson** [comment]
Closing as issue not reproduced and lack of response.
