### ISSUE TITLE
Exporting to prometheus as a service failing

### ISSUE THREAD

**Issue by WilliamG-LORA** [nicolargo/glances#2044]
**Describe the bug**
When I run `glances --export prometheus` as a linux service, it failed with 

**To Reproduce**
1. Create `/etc/systemd/system/glances.service` with the following contents:
```
[Unit]
Description=Glances
After=network.target
[Service]
User=me
ExecStart=/usr/bin/glances --export prometheus
Restart=always
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
```

2. `sudo systemctl daemon-reload`
3. `sudo systemctl start glances.service`
4. `sudo systemctl enable glances.service`
5. `sudo systemctl status example.service` <- See error

**Expected behavior**
To be able to target machine's prometheus endpoint for glances data after reboot.

**Error Log**
5월 03 15:11:13 pc1 glances[377650]:     start(config=config, args=args)
5월 03 15:11:13 pc1 glances[377650]:   File "/usr/lib/python3/dist-packages/glances/__init__.py", line 108, in start
5월 03 15:11:13 pc1 glances[377650]:     mode = GlancesMode(config=config, args=args)
5월 03 15:11:13 pc1 glances[377650]:   File "/usr/lib/python3/dist-packages/glances/standalone.py", line 98, in __init__
5월 03 15:11:13 pc1 glances[377650]:     self.screen = GlancesCursesStandalone(config=config, args=args)
5월 03 15:11:13 pc1 glances[377650]:   File "/usr/lib/python3/dist-packages/glances/outputs/glances_curses.py", line 122, in __init__
5월 03 15:11:13 pc1 glances[377650]:     self.screen = curses.initscr()
5월 03 15:11:13 pc1 glances[377650]:   File "/usr/lib/python3.8/curses/__init__.py", line 29, in initscr
5월 03 15:11:13 pc1 glances[377650]:     setupterm(term=_os.environ.get("TERM", "unknown"),
5월 03 15:11:13 pc1 glances[377650]: _curses.error: setupterm: could not find terminal

**Desktop (please complete the following information):**
 - OS: GNU/Linux Ubuntu 20.04
 - Glances Version: Glances v3.1.3 with psutil v5.5.1
 - Glances logs file: I can't find where my log file is. Documentation is incomplete I think.

**Additional context**
I noticed that I get the same error when trying to run `glances --export prometheus &` (detached).

**Comment by nicolargo** [comment]
Hi,

could you please try to run Glances from the command line in debug mode:

    glances --export prometheus -d

Then paste/bin (https://pastebin.fr/) us the glances.log file.

In your service, do you try to run Glances without the UI ?

```
[Unit]
Description=Glances
After=network.target
[Service]
User=me
ExecStart=/usr/bin/glances --export prometheus --quiet
Restart=always
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
```

Nicolas

**Comment by WilliamG-LORA** [comment]
Where can I find the log file?

**Comment by nicolargo** [comment]
The log file path is display when you enter the **glances -V** command line

**Comment by WilliamG-LORA** [comment]
I don't see a path when I do `glances -V`, however it turns out running with the `--quiet` flag fixes the issue. Thank you.
