### ISSUE TITLE
latest Glances v3.2.5 PsUtil v5.9.0 broke Home-Assistant due to docker error

### ISSUE THREAD

**Issue by ranrinc** [nicolargo/glances#2047]
**Describe the bug**
I used Glances to monitor many of my machine. However upon upgrade to the latest Glances the Home-Assistant which regularly retrive information from Glances getting an `docker` error message. I'm not sure if this related to the other threads which running glances in docker. 

I usually install glances using `pip3 install glances[all]` so wondering what is broken.

This are the error messages coming from the home-assistant which clearly shown error on `docker`
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/glances/sensor.py", line 50, in async_setup_entry
    elif client.api.data[description.type]:
KeyError: 'docker'
```

**To Reproduce**
The error coming from third party home-assistant which will not get any information from glances

**Expected behavior**
usually Home-Assistant will get information from Glances API like
<img width="298" alt="Screen Shot 2022-05-07 at 10 57 20 AM" src="https://user-images.githubusercontent.com/15801696/167237330-d0fc222c-50f1-43f6-a2e0-8cc71cf95691.png">

Those are glances running version 3.2.4.2

**Screenshots**
working screenshots
<img width="298" alt="Screen Shot 2022-05-07 at 10 57 20 AM" src="https://user-images.githubusercontent.com/15801696/167237330-d0fc222c-50f1-43f6-a2e0-8cc71cf95691.png">

not working screenshots
<img width="299" alt="Screen Shot 2022-05-07 at 11 00 05 AM" src="https://user-images.githubusercontent.com/15801696/167237395-f14ad78a-c3cb-4d06-bd48-718162e7eb37.png">

**Desktop (please complete the following information):**
 - OS: Linux Debian 11
 - Glances Version  Glances v3.2.5 with PsUtil v5.9.0
 - Glances logs file 
```2022-05-07 10:44:21,159 -- INFO -- Start Glances 3.2.5
2022-05-07 10:44:21,159 -- INFO -- CPython 3.9.2 (/usr/bin/python3) and psutil 5.9.0 detected
```

P.S.
Temporary solution is there away for me to download my installation to Glances v3.2.4.2 with PsUtil v5.6.6?

**Comment by nicolargo** [comment]
Duplicated: Have a look on https://github.com/nicolargo/glances/issues/2031
