### ISSUE TITLE
Display Glances version in GUI?

### ISSUE THREAD

**Issue by scadaguru** [nicolargo/glances#2050]
I may be missing something but I don't see the Glances version number any where in the GUI?

Is that possible to add please?
Thanks

**Comment by nicolargo** [comment]
Hi @scadaguru 

The version is displayed when when click on the 'h' (help) key.

Nicolas

**Comment by scadaguru** [comment]
> Hi @scadaguru
> 
> The version is displayed when when click on the 'h' (help) key.
> 
> Nicolas

Love it! 
It's little hard to find but finally figured out that on web page GUI anywhere if I press "h" key on keyborad it opens new page which has the version and few other details!
thanks
