### ISSUE TITLE
Create a Show option in the configuration file to only show some stats

### ISSUE THREAD

**Issue by GBT55** [nicolargo/glances#2052]
**Is your feature request related to a problem? Please describe.**
When you edit the glances.conf file in the **[fs]** section, you have the option to hide or show the multiple FSs on your host. 
For me, who build glances as a docker, many filesystems are shown so I have to hide them one by one and it is especially difficult when the names of each filesystem are cut off by the window.

**Describe the solution you'd like**
It'd be nice if we could hide all fs and then show only the ones we want. 
Example:
```
[fs]
disable=False
show=/,/dev/sda
careful=50
warning=70
critical=90
```
And then with this configuration Glances would only show **/** and **/dev/sda** filesystems

**Comment by nicolargo** [comment]
Some requirements:
- Show and hide option can not be used together
- Hide is a black list (remove the configured items from the list)
- Show is a white list (only show the configured items in the list)

**Comment by nicolargo** [comment]
Pushed of the develop branch.

Show option available for the following plugins:

	modified:   glances/plugins/glances_diskio.py
	modified:   glances/plugins/glances_docker.py
	modified:   glances/plugins/glances_fs.py
	modified:   glances/plugins/glances_network.py
	modified:   glances/plugins/glances_sensors.py
	modified:   glances/plugins/glances_wifi.py

Thanks for the proposal @GBT55
