### ISSUE TITLE
Prometheus Export doesn't affect smart plugin

### ISSUE THREAD

**Issue by kjboa** [nicolargo/glances#2053]
**Describe the bug**

Contrary to other values the SMART attributes picked up by the smart plugin are not exported to prometheus when running --export prometheus.

**To Reproduce**

I setup a prometheus export job using `glances --quiet --enable-plugin smart --export prometheus &`.
`glances --enable-plugin smart` however shows all SMART Attributes
Other values such as cpu usage or usage per docker container are being picked up by  prometheus

**Expected behavior**

It would be useful if Smart Values were exported as well e.g. for visualization using grafana

**Additional context**

I am on glances version 3.2.5

**Comment by nicolargo** [comment]
Hi @kjboa 

is the following line works:

    glances --enable-plugin smart --stdout smart

Nicolas

**Comment by atpage** [comment]
Related?  When I run `glances --enable-plugin smart --stdout smart`, I see all the expected SMART data.  But I don't see this data in the web UI, CLI UI, or exports (using `influxdb2`).
