### ISSUE TITLE
In the sensor plugin configuration file limits should overwrite system ones

### ISSUE THREAD

**Issue by gauvins2** [nicolargo/glances#2058]
**Is your feature request related to a problem? Please describe.**
Memory module sensor (jc42) values are displayed properly, but in red (critical)

**Describe the solution you'd like**
Being able to set values as we can for core (ex: temperature_core_careful=60)

**Additional context**
I've tried temperature_jc42_careful=50 and jc42_careful=50, to no avail

**Comment by nicolargo** [comment]
Hi @gauvins2 

the temperature_jc42_careful=50 should work.

Are you sure that you read the good Glances configuration file ?

Please start Glances in debug mode (-d) and [paste/bin](https://pastebin.com/) the Glances log file.

**Comment by gauvins2** [comment]
tried several variants of the sensors' names (jc42 / jc42* / jc42 1 / jc42[1-8]) but didn't work. Log shows that glances uses values of 0 for careful/warning/critical.

Log can be seen [here](https://pastebin.com/5Rpnsuxe)

**Comment by nicolargo** [comment]
Your sensors are named: 
- jc42 1
- jc42 2
- ...
- jc42 8

So your configuration file should be:

```
[sensors]
temperature_jc42 1_careful=50
temperature_jc42 2_careful=50
temperature_jc42 3_careful=50
temperature_jc42 4_careful=50
temperature_jc42 5_careful=50
temperature_jc42 6_careful=50
temperature_jc42 7_careful=50
temperature_jc42 8_careful=50
```

**Comment by gauvins2** [comment]
Hi again (and thanks for your time)

not working. See [here](https://pastebin.com/P28ZSBj8)

**Comment by nicolargo** [comment]
Strange... perhaps the values configured in the Glances conf file is overwrite by the system one...

Can you please copy/paste the result of the following command:

```
python
>>> import psutil
>>> psutil.sensors_temperatures()
```

**Comment by gauvins2** [comment]
as per your request: here <https://pastebin.com/58ehxy8c> (critical: 0 ...)

**Comment by nicolargo** [comment]
Bug confirmed: if the system give a default value (0) then the values defined in the Glances conf file are not taken into account:

```
2022-07-14 09:44:31,963 -- DEBUG -- Load limit: sensors_temperature_acpitz 1_carful = 40.0
2022-07-14 09:44:31,963 -- DEBUG -- Load limit: sensors_temperature_acpitz 1_warning = 50.0
2022-07-14 09:44:31,963 -- DEBUG -- Load limit: sensors_temperature_acpitz 1_critical = 60.0
2022-07-14 09:44:32,804 -- DEBUG -- Plugin sensors update return [{'label': 'acpitz 1', 'value': 27, 'warning': 105, 'critical': 105, 'unit': 'C', 'type': 'temperature_core', 'key': 'label'}...
```

**Comment by nicolargo** [comment]
Corrected by the latest commit in the develop branch.

@gauvins2 Can you test it ?

**Comment by gauvins2** [comment]
Will take a while. I am out of the office till mid August. Will do then and
update.

Thanks for following up on this

SG - mobile
