### ISSUE TITLE
MQTT docker issue

### ISSUE THREAD

**Issue by Anian-igor** [nicolargo/glances#2061]
**Describe the bug**
New dev image cannot connect to MQTT server
glances-mqtt    | Connection to MQTT server failed : [Errno 111] Connection refused
glances-mqtt    | Traceback (most recent call last):
glances-mqtt    |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
glances-mqtt    |     return _run_code(code, main_globals, None,
glances-mqtt    |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
glances-mqtt    |     exec(code, run_globals)
glances-mqtt    |   File "/glances/glances/__main__.py", line 29, in <module>
glances-mqtt    |     glances.main()
glances-mqtt    |   File "/glances/glances/__init__.py", line 189, in main
glances-mqtt    |     start(config=core.get_config(), args=core.get_args())
glances-mqtt    |   File "/glances/glances/__init__.py", line 118, in start
glances-mqtt    |     mode = GlancesMode(config=config, args=args)
glances-mqtt    |   File "/glances/glances/standalone.py", line 108, in __init__
glances-mqtt    |     self.screen = GlancesCursesStandalone(config=config, args=args)
glances-mqtt    |   File "/glances/glances/outputs/glances_curses.py", line 151, in __init__
glances-mqtt    |     self.screen = curses.initscr()
glances-mqtt    |   File "/usr/local/lib/python3.10/curses/__init__.py", line 29, in initscr
glances-mqtt    |     setupterm(term=_os.environ.get("TERM", "unknown"),
glances-mqtt    | _curses.error: setupterm: could not find terminal

**To Reproduce**
1. Start Glances with the followings options docker-compose
version: "3"
services:
  glances-mqtt:
    container_name: glances-mqtt
    image: nicolargo/glances:dev
    restart: unless-stopped
    network_mode: host
    pid: host
    hostname: hp
    volumes:
      - ./data/glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - GLANCES_OPT= --export mqtt

**Expected behavior**
Worked on previous dev version

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by nicolargo** [comment]
Hi @Anian-igor 

the error message is not related to the MQTT connection.

Can you try the following options:

GLANCES_OPT= --export mqtt --quiet

**Comment by Anian-igor** [comment]
Didn't help
Connection to MQTT server failed : [Errno 111] Connection refused
I tried from another virtual machine on same host and work OK. Also worked 2 dev versions ago.

**Comment by nicolargo** [comment]
I have added a log message on failed connection.

Please can you try with the latest dev version ?

**Comment by Anian-igor** [comment]
glances-mqtt    | Connection to MQTT server localhost:8883 failed with error: [Errno 111] Connection refused
glances-mqtt    | MQTT client initialization failed

It's a strange. Because I had another IP and port.

**Comment by Anian-igor** [comment]
`[mqtt]
host=192.168.248.2
port=9083
user="glances"
password="password"
topic=glances
tls=false
topic_structure=per-metric`

**Comment by Anian-igor** [comment]
```
glances-mqtt    | Traceback (most recent call last):
glances-mqtt    |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
glances-mqtt    |     return _run_code(code, main_globals, None,
glances-mqtt    |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
glances-mqtt    |     exec(code, run_globals)
glances-mqtt    |   File "/glances/glances/__main__.py", line 19, in <module>
glances-mqtt    |     glances.main()
glances-mqtt    |   File "/glances/glances/__init__.py", line 179, in main
glances-mqtt    |     start(config=core.get_config(), args=core.get_args())
glances-mqtt    |   File "/glances/glances/__init__.py", line 108, in start
glances-mqtt    |     mode = GlancesMode(config=config, args=args)
glances-mqtt    |   File "/glances/glances/standalone.py", line 104, in __init__
glances-mqtt    |     self.screen = GlancesCursesStandalone(config=config, args=args)
glances-mqtt    |   File "/glances/glances/outputs/glances_curses.py", line 143, in __init__
glances-mqtt    |     self.screen = curses.initscr()
glances-mqtt    |   File "/usr/local/lib/python3.10/curses/__init__.py", line 29, in initscr
glances-mqtt    |     setupterm(term=_os.environ.get("TERM", "unknown"),
glances-mqtt    | _curses.error: setupterm: could not find terminal

**Comment by nicolargo** [comment]
Sorry forget the --quiet:

    GLANCES_OPT= -C /glances/conf/glances.conf --quiet --export mqtt

**Comment by nicolargo** [comment]
Container is started now...

Any log ?

    docker logs 77203060427b

**Comment by Anian-igor** [comment]
No logs

**Comment by nicolargo** [comment]
And no data in the MQTT server ???

**Comment by Anian-igor** [comment]
Yes. No connection to MQTT server

**Comment by nicolargo** [comment]
Can you try to run the container without docker-compose:

    docker run --rm -v `pwd`/data/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -e GLANCES_OPT="-C /glances/conf/glances.conf --quiet --export mqtt" -it docker.io/nicolargo/glances:dev

if it do not work, please replace `pwd`/data/glances.conf by the full pass of your glances.conf file.

**Comment by Anian-igor** [comment]
the same. I run a container with full path
```
docker run --rm -v /media/docker/system/glances-mqtt/data/glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -e GLANCES_OPT="-C /glances/conf/glances.conf --quiet --export mqtt" -it docker.io/nicolargo/glances:dev
```
And no logs

**Comment by Anian-igor** [comment]
No error. But container not started correct  - still stuck on this string. And no mqtt connections (I see from server logs)

**Comment by nicolargo** [comment]
Ok last chane:

1) Start your container with the previous docker run command line
2) on another terminal, get the docker id (<dockerid>) with a docker ps command line
3) run a shell inside the container:

```
docker exec -it <dockerid> /bin/sh
```

4) Check the Glances log file:

```
# tail -f /tmp/glances-root.lo
```

Works on my side:

![Screenshot from 2022-07-15 19-41-41](https://user-images.githubusercontent.com/776747/179281070-aee43025-aa11-4664-92e0-3d872121a8cd.png)

**Comment by nicolargo** [comment]
.log ....

**Comment by Anian-igor** [comment]
```
tail -f /tmp/glances-root.log
2022-07-15 17:46:59,804 -- INFO -- Start Glances 3.2.7_beta01
2022-07-15 17:46:59,805 -- INFO -- CPython 3.10.5 (/usr/local/bin/python3) and psutil 5.9.1 detected
2022-07-15 17:46:59,813 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2022-07-15 17:46:59,977 -- INFO -- Start GlancesStandalone mode
2022-07-15 17:47:00,607 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-07-15 17:47:02,178 -- INFO -- Quiet mode is ON, nothing will be displayed
```

**Comment by Anian-igor** [comment]
A lot of information. I don't know that part need to copy. But still not connections to mqtt

**Comment by nicolargo** [comment]
Please pastebin s all the file to investigate.

**Comment by Anian-igor** [comment]
[https://pastebin.com/RpBwRsyD](url)

**Comment by nicolargo** [comment]
Very strange... the export seems to work:

...
2022-07-15 18:12:09,005 -- DEBUG -- Export stats using the mqtt module
2022-07-15 18:12:09,011 -- DEBUG -- Stats exported duration: 0.006104 seconds
...

**Comment by Anian-igor** [comment]
Yes. I also see these lines. But no connections to mosquitto.

**Comment by Anian-igor** [comment]
Now works OK
I rewrite docker-compose config
```
version: "3.7"
services:
  glances-mqtt:
    container_name: glances-mqtt
    image: nicolargo/glances:dev
    restart: unless-stopped
    pid: host
    hostname: hp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/glances.conf:/glances/conf/glances.conf"
    environment:
      GLANCES_OPT: "-C /glances/conf/glances.conf --quiet --export mqtt"
    ports:
      - "61208:61208"
```
and glances.conf
```
[mqtt]
host=192.168.0.1
port=8083
tls=false
user=glances
password=password
topic=glances
topic_structure=per-metric
```
