### ISSUE TITLE
Must escape argument to install modules on OS X Catalina

### ISSUE THREAD

**Issue by ttrezren** [nicolargo/glances#2073]
On a newly installed glances I tried to add the docker module, with this result:

```
~❯ pip --version && pip install glances[docker] --user
pip 22.1.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
zsh: no matches found: glances[docker]
```

Adding quotes fixed it for me

`
pip install 'glances[docker]' --user
`

As noted in the issue below

Try escaping the argument with quotes:

`pip install pip install 'glances[action,browser,cloud,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]' --user`

_Originally posted by @kevintraver in https://github.com/nicolargo/glances/issues/1088#issuecomment-304237552_

**Comment by nicolargo** [comment]
Quote are already in the documentation.
