### ISSUE TITLE
physical network interfaces of host not all detected 

### ISSUE THREAD

**Issue by mamema** [nicolargo/glances#2079]
**Describe the bug**
i've several network cards (1 GB, 10GB), only eth0 is detected

**To Reproduce**
just install glances via docker and take a look

**Expected behavior**
interfaces above eth0 should be shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS:debian 11 , openmediavault
 - Glances Version [output of glances -V]
 Glances v3.2.0 with PsUtil v5.8.0
  Log file: /tmp/glances-root.log
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
2022-07-07 05:38:30,605 -- INFO -- Start Glances 3.2.0
2022-07-07 05:38:30,605 -- INFO -- CPython 3.9.6 and psutil 5.8.0 detected
2022-07-07 05:38:30,612 -- INFO -- Read configuration file '/glances/conf/glances.conf'
2022-07-07 05:38:30,643 -- INFO -- Start GlancesWebServer mode
2022-07-07 05:38:30,991 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-07-07 05:38:32,395 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2022-07-07 05:38:32,401 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2022-07-07 09:18:19,656 -- INFO -- Start Glances 3.2.0
2022-07-07 09:18:19,656 -- INFO -- CPython 3.9.6 and psutil 5.8.0 detected

**Comment by nicolargo** [comment]
Same behavior if you run Glances not from Docker but directly from your host ?

**Comment by elpigeondindo** [comment]
hi !
i have the same problem with the glances docker. i have a network name enp0s25 and i put in my config "show=enp0s25" but glances don't show it.

`###################################
  #            GLANCES              #
  ###################################      
  glances:
    container_name: Glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=Europe/Paris
      - GLANCES_OPT=--quiet --config /etc/glances.conf --export influxdb2
      #- GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /docker/glances:/glances/conf
      - /docker/glances/glances.conf:/etc/glances.conf
    labels:
      - "diun.enable=true"`



What do you want to know?

**Comment by nicolargo** [comment]
@elpigeondindo: to reproduce the **--network host** option (present in the example provided in the main README.rst file) in a Docker file, you can use the **network_mode** option in the container section of the Docker file:

    network_mode: host

**Comment by elpigeondindo** [comment]
Thanks. The problem for me is solved.

**Comment by nicolargo** [comment]
In order to limit the security behavor intriduced by the network_mode: host option, you can limit the access to one network interface in Docker compose file:

```
networks:
      - eth0
```

**Comment by elpigeondindo** [comment]
thanks. i found my interfaces. But how can i delete in glances br-0c44a44827e70 and ceth02ce3e2 ?

i try this hide=docker.*,lo,br*,veth*

**Comment by elpigeondindo** [comment]
oki i try network_mode: host and i found my interfaces. But now, nothing is export in influxdb2

**Comment by nicolargo** [comment]
> thanks. i found my interfaces. But how can i delete in glances br-0c44a44827e70 and ceth02ce3e2 ?
> 
> i try this hide=docker._,lo,br_,veth*

As said in the documentation, you need to use a regular expression.

veth* is not a regular expression
veth**.*** is a regular expression

**Comment by elpigeondindo** [comment]
oki thanks i understand sorry for that.

do you know why my conainter doesn't export my data ti influxdb but when i launch like this glances -C /etc/glances.conf --export influxdb2 that's export?

**Comment by nicolargo** [comment]
> oki i try network_mode: host and i found my interfaces. But now, nothing is export in influxdb2
> 
> but when i go in console with portainer and i launch "glances -C /etc/glances.conf --export influxdb2", i have my data exported in influxdb2

Is you InfluXDB server ran in another container ? The docker network between the two containers is configured ?

Here is a simple Docker compose file with an InfluxDB2 + Glances stack: https://github.com/nicolargo/docker-influxdb2-grafana-glances

**Comment by elpigeondindo** [comment]
Thank you very much, you are a chef.

Maybe I should have looked a little more. your solution works perfectly.

**Comment by RazCrimson** [comment]
Closing as issue fixed

**Comment by twilsonco** [comment]
Hi @nicolargo, I'm having an apparently similar issue as OP here. Thought I'd comment here rather than open a new issue.

I'm running glances on Ubuntu 24 via Docker Compose, and the network section isn't showing in the glances web gui. I must be making a mistake somewhere.

I also have glances running via docker on a Synology NAS, although not using docker compose (so using `--net=host --privileged`), and there everything is working as expected.

Here's some details of my setup:

Docker compose yml:
```yaml
services:
  glances:
    image: nicolargo/glances
    container_name: glances
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # To monitor Docker containers
      - /home/haiiro/docker/appdata/glances:/etc/glances # Optional: To use a custom configuration
      - /etc/os-release:/etc/os-release:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - "GLANCES_OPT=-w" # Optional: To use the Web interface by default
```

glances.conf (just to be safe):
```ini
[network]
disable=False
```

log output:
```
Glances Web User Interface started on http://0.0.0.0:61208/
Glances RESTful API Server started on http://0.0.0.0:61208/api/4
INFO:     Started server process [1596402]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:61208 (Press CTRL+C to quit)
```

screenshot of web gui:
![CleanShot 2024-11-19 at 08 34 46](https://github.com/user-attachments/assets/a6f9772c-1000-43fe-9aae-def887021deb)

**Comment by twilsonco** [comment]
Nevermind! Following up, I'm still not sure why it wasn't showing *all* network interfaces given the setup I had, but by adding 
```
show=enp1s0
```
to my glances.conf file (where the interface name was taken from the output of `ifconfig`), it now shows the desired network interface. 

Thanks, and great work on this tool!
