### ISSUE TITLE
keybind(s) for modifying nice level

### ISSUE THREAD

**Issue by xfnw** [nicolargo/glances#2081]
**Is your feature request related to a problem? Please describe.**
there seems to be no way to renice a process in glances

**Describe the solution you'd like**
adding keybind(s) for changing the nice level of a process. not sure what a good key to use for this would be, since both `n` and `N` are taken.

**Describe alternatives you've considered**
using htop's `F7` and `F8` keybinds for decrementing and incrementing nice level

**Additional context**
the niceness of a process controls how "nice" it is to other processes, a higher value means it will let other processes use more of the cpu, essentially the inverse of priority. [renice(1)](https://www.mankier.com/1/renice) changes the niceness of a running process.

**Comment by nicolargo** [comment]
Hi @xfnw !

Done and pushed on the develop branch.

**+**  to Increase selected process nice level / Lower the priority (need right) - Only in standalone mode.
 **-**  to Decrease selected process nice level  / Higher the priority (need right) - Only in standalone mode.

Please test/comment.

**Comment by xfnw** [comment]
seems like it works perfectly. thanks!
