### ISSUE TITLE
Add example for using Prometheus Exporter functionality in a container

### ISSUE THREAD

**Issue by dbrennand** [nicolargo/glances#2087]
**Is your feature request related to a problem? Please describe.**
The [Prometheus Exporter documentation](https://glances.readthedocs.io/en/latest/gw/prometheus.html) `glances.conf` example is for when Glances is installed on the host, and doesn't work correctly when used in a container.

**Describe the solution you'd like**
A note added to the docs with working configuration for usage in a container. To work in a container, the `host` needs to be set to `0.0.0.0` otherwise, you'll see errors in Prometheus similar to `connect: connection refused`.

I can raise a PR for this if that would help 🙂

**Comment by nicolargo** [comment]
Merged into develop branch.

Thanks for the contrib !
