### ISSUE TITLE
Sensor area only show 1 disk temperature

### ISSUE THREAD

**Issue by s0urcelab** [nicolargo/glances#2090]
**Describe the bug**
I get 2 disk, i can see them in 'DISK I/O', but i can only see 1 temp in 'SENSOR' after i install hddtemp.

**To Reproduce**
1. Start Glances with the followings options 'GLANCES_OPT=-w'
2. running Glances in Docker

**Expected behavior**
should show 2 temp.

**Screenshots**
![微信图片_20220717210357](https://user-images.githubusercontent.com/13177782/179399673-6509980a-be73-4118-bb4f-85f785b3d208.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux Debian11 kernel 5.16.0-0.bpo.3-amd64
 - Glances Version: nicolargo/glances:latest-full

**Comment by nicolargo** [comment]
Hi @s0urcelab !

Please install netcat (if it is not already installed) and run:

    netcat localhost 7634

What's the result ?

**Comment by s0urcelab** [comment]
> Hi @s0urcelab !
> 
> Please install netcat (if it is not already installed) and run:
> 
> ```
> netcat localhost 7634
> ```
> 
> What's the result ?

I forgot to pass a default params to hddtemp, it works now!
