### ISSUE TITLE
Migration from AngularJS to Angular/React/Vue

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2100]
AngularJS is deprecated (see https://angularjs.org/) and will not be upgraded...

There is some CVE on this composant: https://github.com/nicolargo/glances/issues/2066#issuecomment-1200110075

A migration from AngularJS to Angular should be done: https://angular.io/guide/upgrade or to a brand new framework like React ?

@notFloran have you some time to work on this issue ?

**Comment by notFloran** [comment]
> A migration from AngularJS to Angular should be done: https://angular.io/guide/upgrade or to a brand new framework like React ?

Angular is like a new framework compared to AngularJS so it's a good idea to also look at competitors like React or Vue.

To simplify the migration, it might be necessary to find a way to move forward gradually with AngularJS and the new framework in parallel, but I don't know if it's feasible and if it's really a good idea.

> @notFloran have you some time to work on this issue ?

Sorry, I don't have much time for open source at the moment (a lot of personal / professional projects): I could help if needed but I can't take the lead on this subject, it's really a big piece.

**Comment by nicolargo** [comment]
Some ressources...

For a AngularJS to a VueJS migration

- https://maartenvandenhoven.com/blog/migrating-angularjs-to-vue-js/
- https://www.holistics.io/blog/why-and-how-we-migrated-from-angularjs-to-vuejs/#howweincrementallymigrated
- https://medium.com/@JohnSardine/progressively-migrating-from-angularjs-to-vue-js-at-unbabel-581eb4ae022d

For a AngularJS to a React migration

- https://www.babbel.com/en/magazine/how-we-moved-from-angularjs-to-react
- https://medium.com/telostouch/how-we-migrated-from-angularjs-to-react-redux-in-2-weeks-16ba765fd6d5
- https://www.freecodecamp.org/news/how-to-convert-an-angular-app-to-a-react-app-one-component-at-a-time-ba985eaae66e/

**Comment by jonathanspw** [comment]
Any updates on this so CVEs can be resolved?

**Comment by nicolargo** [comment]
@jonathanspw Nope... need contributors...

**Comment by nicolargo** [comment]
Migration to VueJS done in the develop branch thanks to  @fr4nc0is  !

Just a  little issue on the Network plugin:

![Screenshot from 2022-09-03 10-15-26](https://user-images.githubusercontent.com/776747/188262431-12ceae84-4f78-466c-9dc7-f013936a39d8.png)

**Comment by nicolargo** [comment]
Ok Network plugin issue corrected by removing the  line just before <section>.
