### ISSUE TITLE
CPU% reported incorrectly on Windows

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [nicolargo/glances#2110]
**Describe the bug**

CPU% reported by glances for top processes reported 10 times higher than actual.

**To Reproduce**

1. Start Glances from PowerShell as "glances"
2. Observe CPU% usage reported by glances for the python process running glances itself
3. Observe CPU% usage reported for the same process reported by ProcExp.exe or by native Windows task manager by pressing Ctrl-Shift-Esc

**Expected behavior**

CPU% should match the values reported by native OS performance monitoring tools

**Desktop (please complete the following information):**
 - OS: Windows 21H2 Build 22000.856
 - Glances Version: 3.2.7

**Comment by nicolargo** [comment]
If you want Glances to display CPU processing as % of the global processing, then use "glances --disable-irix".
