### ISSUE TITLE
Can I export only the fields I need in csv report？

### ISSUE THREAD

**Issue by zhengwenhao07** [nicolargo/glances#2113]
Now there are many unnecessary fields in the CSV file I exported, and there is no time stamp. Can I specify fields everywhere and add timestamps.
This is my export command 
glances --export-csv /usr/glances1.csv

**Comment by nicolargo** [comment]
Yes, for example if you only want CPU stats (with Glances 3.2.7 or higher):

    glances --quiet --export csv --export-csv-file /tmp/glances.csv --disable-plugin all --enable-plugin now,cpu

**Comment by zhengwenhao07** [comment]
> Yes, for example if you only want CPU stats (with Glances 3.2.7 or higher):
> 
> ```
> glances --quiet --export csv --export-csv-file /tmp/glances.csv --disable-plugin all --enable-plugin now,cpu
> ```

Thank you for your reply [nicolargo](https://github.com/nicolargo) , but my Glances version is  v2.5.1, should I upgrade?

**Comment by nicolargo** [comment]
Yes.

**Comment by RazCrimson** [comment]
Closing as the question is answered
