### ISSUE TITLE
Broken `code-block` sections in current Docs

### ISSUE THREAD

**Issue by cauterize** [nicolargo/glances#2115]
**Describe the bug**
Code Examples in the current docs are missing. F.e. all code blocks form this #1777 are not in the current docs. Because of this the section in question is very confusing and crucial information is missing.

**To Reproduce**
compare https://glances.readthedocs.io/en/latest/docker.html with #1777

**Expected behavior**
Code blocks are in the docs

**Screenshots**
![image](https://user-images.githubusercontent.com/895680/187065906-a450a946-e8de-4205-912b-939add9bd46c.png)

**Comment by nicolargo** [comment]
Corrected on the develop branch.

Thanks for the issue report @cauterize !
