### ISSUE TITLE
[WEBUI] After the VueJS migration, Glances top screen is no more dynamic

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2122]
Following the VueJS migration (thanks again @fr4nc0is ) the top of the screen is no more dynamic if the browser width is reduced:

![Screenshot 2022-09-09 at 10-15-22 XPS13-9333 - Glances](https://user-images.githubusercontent.com/776747/189305306-8aea1f33-2c39-426d-b96d-37904ea3c7b8.png)

Anyone to solve this issue ?

**Comment by fr4nc0is** [comment]
I got the same issue when rebuilding from `master`

**Comment by nicolargo** [comment]
I need to release Glances 3.3.0 in order to make the master branch ok.

Thanks !
