### ISSUE TITLE
[REQUEST] Output log to stdout

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nicolargo/glances#2128]
**Is your feature request related to a problem? Please describe.**

Most containers show log data in the regular stdout; when looking at my glances container log it's blank.

**Describe the solution you'd like**

Output log to stdout. :)

**Describe alternatives you've considered**

It's possible to tail the log file itself at `/tmp/glances-root.log` which is great, but it's also more convenient at times to just look at the log stuff in something like [Dozzle](https://dozzle.dev/) log viewer, or the built in Portainer log viewer, etc.

It can be done in the dockerfile like:

```
# Forward access and error logs to Docker's log collector
RUN ln -sf /dev/stdout /tmp/glances-root.log \
    && ln -sf /dev/stderr /var/log/error.log
```

**Comment by nicolargo** [comment]
Just add it to the *dev* image (and only dev image, because it display starting and ending message on the console:

```
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it glances:local-alpine-dev
2022-09-24 14:45:55,330 -- INFO -- Start Glances 3.3.0_beta1
2022-09-24 14:45:55,330 -- INFO -- CPython 3.10.5 (/usr/bin/python3) and psutil 5.9.2 detected
2022-09-24 14:45:55,343 -- INFO -- Read configuration file '/etc/glances.conf'
2022-09-24 14:45:55,381 -- INFO -- Start GlancesStandalone mode
2022-09-24 14:45:55,401 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
```

**Comment by YouveGotMeowxy** [comment]
@nicolargo ty.

Quick side note: is it possible to also include the Glances version on the top line where it says:

`glances (Alpine Linux 3.16.2 64bit / Linux 5.10.102.1-microsoft-standard-WSL2)`

i.e.

`Glances v3.2.7 (Alpine Linux 3.16.2 64bit / Linux 5.10.102.1-microsoft-standard-WSL2)`
