### ISSUE TITLE
Virus scanning service plugin project

### ISSUE THREAD

**Issue by Airick73** [nicolargo/glances#2130]
Our team of 5 is looking to develop a plugin that will integrate virus scanning services, for example, virustotal, metadefender cloud, etc... into glances. The two main features of the plugin will be 
1. The ability to scan a process for viruses via a virus scanning service 
2.  Add an additional column to glances to show how many anti virus engines have detected a threat on a given process

In the future our team may update this post with mock ups of the described features of the plugin. Any insight and support from the community would be greatly appreciated. 

Kindest Regards,
Eric Kemmer

**Comment by nicolargo** [comment]
Hi Eric !

Did you have a look on the Glances AMP feature (https://glances.readthedocs.io/en/latest/aoa/amps.html) ? Perhaps it is not necessary to write a dedicated plugin...

For example, to monitor my Dropbox synchronization process, i use the following AMP configuration:

```
[amp_dropbox]
# Use the default AMP (no dedicated AMP Python script)
# Check if the Dropbox daemon is running
# Every 3 seconds, display the 'dropbox status' command line
enable=true
regex=.*dropbox.*
refresh=3
one_line=false
command=dropbox status
countmin=1
```

It displays:

![image](https://user-images.githubusercontent.com/776747/190888964-d84778d1-b0dd-46c8-a359-761bdda80f11.png)


Nicolas

**Comment by cgreenland** [comment]
Hi Nicolas,

I'm also on the team Eric mentioned. Thank you for the information on the AMP feature. It looks like it could be useful for returning a summery of results, but I'm not sure it can provide the per-process information and interactivity we're looking for.

Ideally, we want to add the ability for a user to upload and scan one or more processes in the process list and display the results as a new column in the list. Similar to how VirusTotal integrates into projects like Process Explorer and Process Hacker. We'd also like to add the ability to select and open detailed results in a web browser.

It seems like the process list is itself a plugin, is this correct? Does the app architecture support plugins altering the behavior of other plugins? Or would we have to modify the process list plugin to implement these features?

We appreciate your feedback!

Chris

**Comment by Airick73** [comment]
To add to Christopher's comment this is a mockup of what we were hoping to develop. 
![image](https://user-images.githubusercontent.com/72322466/191321294-026d0ceb-3300-45e0-8367-fd5087606fd8.png)

**Comment by nicolargo** [comment]
Hi @cgreenland 

for the moment, Glances architecture implement all the processes features in two plugins (processcount and processlist).
For your needs, you should modify the processlist plugin.

Some points to discuss:
- the feature should be configurable from the glances configuration file (in the processlist section)
- the feature should be disable by default (could be enable from the glances configuration file)

Additional notes:
- for cyber security reason, the process selection/action is not available in the Web UI 
- the feature should be implemented with both Python 2 and Python 3 support if you want to integrate it in the 3.x version (develop branch). If only Python 3 is targeted, your PR should be done on the glancesv4 branch.

Nicolas

**Comment by RazCrimson** [comment]
@Airick73 @cgreenland 

Any interest on continuing this?
