### ISSUE TITLE
Failed to export data from Glances to prometheus

### ISSUE THREAD

**Issue by vishalkalal22** [nicolargo/glances#2133]
Failed to export data from Glances to prometheus

**To Reproduce**
I installed glances and Prometheus on the machine. Now I am trying to export the data from glances to Prometheus but failed with the below error.

C:\Users\viskal71\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts>glances --export prometheus 

**Can not start Prometheus exporter on None:None (int() argument must be a string, a bytes-like object or a number, not 'NoneType')**

**Expected behavior**
Data should be exported to Prometheus without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/114053504/191431323-46ec9aab-3a9f-46d3-a48a-cc93da9343bb.png)

**Comment by nicolargo** [comment]
Please fill the issue with the following information:
- Glances version
-  Copy/paste the configuration file

**Comment by RazCrimson** [comment]
Closing issue as no response from author
