### ISSUE TITLE
Sensors default values (follow up to #2058)

### ISSUE THREAD

**Issue by gauvins2** [nicolargo/glances#2140]
**Describe the bug**
The fix applies only to the first sensor (see capture)

**To Reproduce**
N.A.
**Expected behavior**
All values should be rewritten
**Screenshots**
![image](https://user-images.githubusercontent.com/50712114/193286791-ba1f2987-08c1-4ad3-8a4e-5a3d01b33c25.png)

**Desktop (please complete the following information):**
 - OS: POP_OS 22.04
 - Glances Version : 3.2.7
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**

**Comment by nicolargo** [comment]
Hi @gauvins2 

can you please copy/paste the sensors section of you Glances configuration files **and** the output of the following command:

    glances --stdout-json sensors

Nicolas

**Comment by gauvins2** [comment]
Thanks for your follow-up. My config file was only referencing jc42 1. Adding the other sensors did the trick. Obviously my mistake. Sorry about that

**Comment by nicolargo** [comment]
No problem @gauvins2 :)
