### ISSUE TITLE
simple --password and multiple users

### ISSUE THREAD

**Issue by narcisgarcia** [nicolargo/glances#2142]
This command with no more parameters:
`glances --username john --password`
should prompt for new password for "john" and create or update ~/.config/glances/john.pwd
And END. This could allow integrating glances setup in a wider installation process.

These commands:
```
glances --password -w
glances --username john --password -w
```
should start Glances in web server mode, and validate any ~/.config/glances/USERNAME.pwd specified by WebUI client.

**Comment by nicolargo** [comment]
Already done.
