### ISSUE TITLE
Password files in same configuration dir in effect

### ISSUE THREAD

**Issue by narcisgarcia** [nicolargo/glances#2143]
This command:
`glances --config /path/to/glances.conf`
should change base directory to look for any glances.pwd file instead of default ~/.config/glances/

**Comment by nicolargo** [comment]
The --config option is dedicated to the Glances configuration file. I think that it's better to add a new section in the configuration file in order to configure the default path for password file.

Example:

```
[passwords]
path=/my/path/to/password/
```

What do you think @narcisgarcia ?

**Comment by narcisgarcia** [comment]
Sure.
Note that [passwords] section content hasn't any effect for me. Tested with Glances v3.2.4.2

**Comment by nicolargo** [comment]
For the moment the [passwords] section is only to define password for the Glances central client (https://glances.readthedocs.io/en/latest/quickstart.html#central-client)

**Comment by narcisgarcia** [comment]
To avoid -local instance- versus -remote accesses- confusions, I think config file sections should be clearly named and separated for each purpose.
Parameter can be better named "localpasswordspath"

**Comment by nicolargo** [comment]
Done in the develop branch and will be release in Glances 3.3.0 (see commit 0302cdcd)

A new configuration key has been added:

```
[passwords]
# Define the path of the local '.pwd' file (default is system one)
local_password_path=/tmp
```

Thanks for the enhancement request @narcisgarcia 

Nicolas
