### ISSUE TITLE
Possible missing comma in fs export to influxdb?

### ISSUE THREAD

**Issue by matthewaaronthacker** [nicolargo/glances#2149]
**Describe the bug**
Error when exporting fs info from Windows host to influx db. I believe there is a comma missing between two tags - mnt_point and device_name.

Error message in debug logs:
`2022-10-04 11:38:07,080 -- DEBUG -- Cannot export fs stats to InfluxDB (400: {"error":"unable to parse 'fs,hostname=WIN10-HOME,mnt_point=C:\\\\ device_name=\"C:\\\\\",free=56599896064.0,fs_careful=50.0,fs_critical=90.0,fs_type=\"NTFS\",fs_warning=70.0,history_size=28800.0,key=\"mnt_point\",percent=47.0,size=106763907072.0,used=50164011008.0': invalid tag format\nunable to parse 'fs,hostname=WIN10-HOME,mnt_point=E:\\\\ device_name=\"E:\\\\\",free=1872505081856.0,fs_careful=50.0,fs_critical=90.0,fs_type=\"NTFS\",fs_warning=70.0,history_size=28800.0,key=\"mnt_point\",percent=6.4,size=2000395694080.0,used=127890612224.0': invalid tag format"})
`

**To Reproduce**
Start glances with '-export influxdb' on a Windows 10 host.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Glances v3.2.7 with PsUtil v5.9.2
 - No other relevant log entires
 `========================================================================================================================
Glances ←[94m3.2.7←[0m (C:\Users\matthew\AppData\Local\Programs\Python\Python310\Lib\site-packages\glances\__init__.py)
Python ←[94m3.10.7←[0m (C:\Users\matthew\AppData\Local\Programs\Python\Python310\python.exe)
PsUtil ←[94m5.9.2←[0m (C:\Users\matthew\AppData\Local\Programs\Python\Python310\Lib\site-packages\psutil\__init__.py)
========================================================================================================================
←[94malert         ←[92m[OK]   ←[94m 0.00000s ←[0m[[1664899032.0, -1, 'CRITICAL', 'MEMSWAP', 92.2379462071486, 92.2379462071486, ←[0m
←[94mamps          ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m
←[94mcloud         ←[92m[OK]   ←[94m 0.00000s ←[0m{}←[0m
←[94mconnections   ←[92m[OK]   ←[94m 0.00201s ←[0m{'LISTEN': 34, 'ESTABLISHED': 32, 'SYN_SENT': 27, 'SYN_RECV': 0, 'initiated': 2←[0m
←[94mcore          ←[92m[OK]   ←[94m 0.00000s ←[0m{'phys': 8, 'log': 8}←[0m
←[94mcpu           ←[92m[OK]   ←[94m 0.00099s ←[0m{'total': 6.8, 'user': 2.3, 'system': 3.9, 'idle': 93.2, 'interrupt': 0.2, 'dpc←[0m
←[94mdiskio        ←[92m[OK]   ←[94m 0.00100s ←[93mkey=disk_name ←[0m[{'time_since_update': 3.941995620727539, 'disk_name': 'PhysicalD←[0m
←[94mdocker        ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m
←[94mfolders       ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m
←[94mfs            ←[92m[OK]   ←[94m 0.00300s ←[93mkey=mnt_point ←[0m[{'device_name': 'C:\\', 'fs_type': 'NTFS', 'mnt_point': 'C:\\', ←[0m
←[94mgpu           ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m
←[94mhelp          ←[92m[OK]   ←[94m 0.00000s ←[0mNone←[0m
←[94mip            ←[92m[OK]   ←[94m 0.00000s ←[0m{}←[0m
←[94mirq           ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m
←[94mload          ←[92m[OK]   ←[94m 0.00000s ←[0m{'min1': 0.0, 'min5': 0.0, 'min15': 0.0, 'cpucore': 8}←[0m
←[94mmem           ←[92m[OK]   ←[94m 0.00000s ←[0m{'total': 6441906176, 'available': 2115604480, 'percent': 67.2, 'used': 4326301←[0m
←[94mmemswap       ←[92m[OK]   ←[94m 0.00000s ←[0m{'total': 5648662528, 'used': 5205757952, 'free': 442904576, 'percent': 92.2, '←[0m
←[94mnetwork       ←[92m[OK]   ←[94m 0.01200s ←[93mkey=interface_name ←[0m[{'interface_name': 'Ethernet', 'alias': None, 'time_since_u←[0m
←[94mnow           ←[92m[OK]   ←[94m 0.00000s ←[0m2022-10-04 11:57:19 -0400←[0m
←[94mpercpu        ←[92m[OK]   ←[94m 0.00100s ←[93mkey=cpu_number ←[0m[{'key': 'cpu_number', 'cpu_number': 0, 'total': 2.1, 'user': 2.←[0m
←[94mports         ←[92m[OK]   ←[94m 0.00100s ←[0m[]←[0m
←[94mprocesscount  ←[92m[OK]   ←[94m 0.90210s ←[0m{'total': 180, 'running': 177, 'sleeping': 0, 'thread': 2229, 'pid_max': 0}←[0m
←[94mprocesslist   ←[92m[OK]   ←[94m 0.00000s ←[93mkey=pid ←[0m[{'name': 'MemCompression', 'cpu_times': pcputimes(user=0.0, system=360←[0m
←[94mpsutilversion ←[92m[OK]   ←[94m 0.00000s ←[0m(5, 9, 2)←[0m
←[94mquicklook     ←[92m[OK]   ←[94m 0.00000s ←[0m{'cpu': 6.8, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 2.1, 'u←[0m
←[94mraid          ←[92m[OK]   ←[94m 0.00000s ←[0m{}←[0m
←[94msensors       ←[92m[OK]   ←[94m 2.01904s ←[0m[]←[0m
←[94msmart←[0m         [N/A]←[0m←[0m
←[94msystem        ←[92m[OK]   ←[94m 0.00000s ←[0m{'os_name': 'Windows', 'hostname': 'WIN10-HOME', 'platform': '64bit', 'os_versi←[0m
←[94muptime        ←[92m[OK]   ←[94m 0.00000s ←[0m{'seconds': 682558}←[0m
←[94mwifi          ←[92m[OK]   ←[94m 0.00000s ←[0m[]←[0m`

**Comment by nicolargo** [comment]
Hi @matthewaaronthacker 

when Glances export stats to InfluxDB, it automatically transform plugin key (mnt_point for fs) to a tag. All the others fields are stored as fields.  

So the space between mnt_point (a tag ) and device_name (a field) is "normal" as the InfluxDB describe it: https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/

**Comment by matthewaaronthacker** [comment]
Anything I can do to aid in the troubleshooting efforts?
