### ISSUE TITLE
Add a options to show a configurable clock/time module to display

### ISSUE THREAD

**Issue by Cornelius-Figgle** [nicolargo/glances#2150]
I use Glances in Web-Server mode, to monitor stats on my PC and a VM I run

Think it would be nice if we could add a clock somewhere on the screen, just to view the current time - ideally configurable (if not then just ISO 8601 formatting, b/c, global recognition), and * hopefully * should be easy to implement? idk how Glances works but iirc python has a `datetime` module to handle this

Could be added to the top bar (w. the IP and Uptime) I guess :D

**Comment by nicolargo** [comment]
Hi @Cornelius-Figgle 

the current time module is displayed in the console UI but not in the WebUI. It's an issue.

@fr4nc0is is it possible to add it in the bottom of the left column ?

Nicolas

**Comment by nicolargo** [comment]
Merged in the develop branch.

Thanks to @fr4nc0is !

**Comment by Cornelius-Figgle** [comment]
Not to be a pain, but when showing the current processes, the time is displayed at [the very bottom of the list](https://imgur.com/a/IWFzQnB) (as are the log messages). Previously, log messages were show above the list, and it makes it kinda unreadable having to scroll all the way down just to see the time

Is there anyway to change this? Thanks
