### ISSUE TITLE
csv export dependent on sort order for docker container cpu

### ISSUE THREAD

**Issue by the01** [nicolargo/glances#2156]
**Describe the bug**
I am attempting to export the cpu load of two docker containers to csv (`worker_1`, `worker_2`), which means I need the columns `docker_worker_1_cpu_percent` and `docker_worker_2_cpu_percent`. In my use case, the two workers are load balanced. So for the first request worker_1 is busy for a minute and on the second request it is the same for worker_2.
However, according to the export all load happened in the same container. Lets say the column `docker_worker_2_cpu_percent` is before  `docker_worker_1_cpu_percent` in the csv-file then a simplified table may look like this

| docker_worker_2_cpu_percent | docker_worker_1_cpu_percent |
| --- | --- |
| 0.1208 | 0.1460 |
| 34.8 | 0.1351 |
| 0.1534 | 0.0967 |
| 0.7878 | 0.1244 |
| 0.1364 | 0.1044 |

but the 34.8 value should be under `docker_worker_1_cpu_percent` instead (other values possibly as well, but hard to tell while idling).

**To Reproduce**
1. Start two docker container (need to idle - `sleep` with a long timeout might be an option)
1. Start glances
    1.  I used `glances --disable-process -1 --disable-left-sidebar -t 1 --export-csv-file "./export.csv" --export csv --disable-plugin swap,alert,amps,cloud,connections,core,diskio,folders,fs,gu,ip,irq,memswap,network,ports,processcount,processlist,psutilversion,raid,sensors,smart,uptime,wifi`
    1. but this should be enough `glances --export-csv-file "./export.csv" --export csv`
1. Put load on the first container (e.g. enter the container with `docker exec` and run a program)
1. Put load on the second container
1. Stop glances
1. Examine the csv file - all load will show under only one of the two container while the other idled

**Expected behavior**
The load produced by a container should be placed in the right column referenced by the column name. From the above example:
| docker_worker_2_cpu_percent | docker_worker_1_cpu_percent |
| --- | --- |
| 0.1208 | 0.1460 |
| 0.1351 | 34.8 |
| 0.1534 | 0.0967 |
| 0.7878 | 0.1244 |
| 0.1364 | 0.1044 |

It should work independently from the process sort order (see additional context).

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04.5
 - Glances v3.3.0.1 with PsUtil v5.9.2 (latest from pip installed in a virtualenv)

**Additional context**
I have narrowed the problem down to the applied sorting in the cli UI. By default process and containers are sorted by cpu, which means the order of the list changes when the workers take turns.
I confirmed this by running it with `glances --sort-processes name` which gave me the expected behavior.

**Comment by nicolargo** [comment]
Corrected in the develop branch by forcing a sort by plugin key before CSV export.

@the01 can you test it ?

@the01 additionnal note, you can use the foollowing command line to disable all plugins but docker:

    glances --disable-process -1 --disable-left-sidebar -t 1 --export-csv-file "./export.csv" --export csv --disable-plugin all --enable-plugin docker

**Comment by nicolargo** [comment]
I close the issue because i want to release Glances 3.3.1. 

@the01 If the test is not ok on your side, please tell me, i will reopen the issue and it will be corrected in a future release.
