### ISSUE TITLE
Can't see current time b/c it's beneath the processes list

### ISSUE THREAD

**Issue by Cornelius-Figgle** [nicolargo/glances#2157]
Not to be a pain, but in web-server mode, when showing the current processes, the time is displayed at [the very bottom of the list](https://imgur.com/a/IWFzQnB) (as are the log messages). Previously, log messages were show above the list, and it makes it kinda unreadable having to scroll all the way down just to see the time

Is there anyway to change this? Thanks

I have a 16:9 1080p monitor if resolution affects layout at all

_Originally posted by @Cornelius-Figgle in https://github.com/nicolargo/glances/issues/2150#issuecomment-1282031514_

**Comment by nicolargo** [comment]
@fr4nc0is Can you have a look on this issue. I think that is a regression introduced with the VueJS migration.

**Comment by Cornelius-Figgle** [comment]
> It will be nice if the WebUI limits the number of displayed processes to fit the screen height

personally, idm the list going off the bottom of the page, but it's annoying that that pushes some other UI elements downwards as well  ¯\(ツ)/¯

**Comment by fr4nc0is** [comment]
@nicolargo ,

I time-travelled to version 3.2.7 but didn't find any way to limit the number of displayed processes except with the process list limit  (**max_processes_display** configuration variable) which seems to be OK.
The 3.2.7 layout seems to be a fluid height layout which is required with responsive design when rows displayed widgets become columns displayed ones under a specific width resolution. And widgets are not height limited with scrolling overflow.

are theses specifications the good ones ? do you have any details about layout height handling or a specific version with the layout required ?

Thanks

**Comment by nicolargo** [comment]
Hi @fr4nc0is 

not sure that the max_processes_display is a good choice for the WebUI. 

Do you think that the following layout is possible:

![glances-web-layout](https://user-images.githubusercontent.com/776747/197336959-85d52c31-23c7-4a19-bb94-9e255b404fa9.png)

The UI will fit the window browser height and a scrollbar will allow users to navigate through the process list.

What do you think ?

**Comment by Cornelius-Figgle** [comment]
ツ

**Comment by fr4nc0is** [comment]
@nicolargo,

It's possible but will only work under a specific configuration. There is no silver bullet to handle fixed height layout with so many sections vs screen sizes. You can handle a fixed height layout with 2 sections max but above it becomes a puzzle.

For example, for a tablet in landscape (+/- 768px height), if i have many docker containers and warnings, the height available for processlist section will be too small and the height should be handle for the sidebar too where more plugins are displayed. 

Maybe time plugin should be displayed under the uptime plugin.

**Comment by Cornelius-Figgle** [comment]
> Maybe time plugin should be displayed under the uptime plugin

I know you aren't talking to me, but this seems good

**Comment by nicolargo** [comment]
Or just bellow the Sensor plugin (in the left side bar)...

**Comment by fr4nc0is** [comment]
If we have lot of rows for each plugin (network / disk / file / sensors / etc...) the time plugin could be not visible at first glance too.
But It's may be a good-enough solution.
Your call

**Comment by nicolargo** [comment]
Ok to implement the  "good-enough solution" when you have time @fr4nc0is . Thanks !
