### ISSUE TITLE
API GET uptime returns formatted string, not seconds as the doc says

### ISSUE THREAD

**Issue by ACrazyConcept** [nicolargo/glances#2158]
**Describe the bug**
The API request
https://glances.readthedocs.io/en/latest/api.html#get-uptime
returns a string in double quotes, and not a delta in seconds as indicated by the docs.

**To Reproduce**
$ curl http://localhost:61208/api/3/uptime
"112 days, 13:56:50"

**Expected behavior**
$ curl http://localhost:61208/api/3/uptime
{"seconds": 221446}

**Screenshots**

**Desktop (please complete the following information):**
  Distro......: Raspbian GNU/Linux 11 (bullseye)
  Kernel......: Linux 5.15.32-v7+
  Glances v3.3.0.1 with PsUtil v5.8.0

**Additional context**
Installed with
`pip3 install glances[web,cpuinfo,ip]`

https://github.com/nicolargo/glances/discussions/2025

**Comment by marcolamberto** [comment]
@nicolargo are you currently planning to correct the documentation or fix the output? I'd love to extend the python-glances-api and home-assistant code in order to support uptime values too, knowing in advance if the format will be changed could be useful for supporting both.

**Comment by nicolargo** [comment]
Documentation corrected.

Thanks for the issue report @marcolamberto !

**Comment by nicolargo** [comment]
The format will be the same for Glances 3.0 branch

It could change with Glances version 4 (but the URL will also change (api/4)
