### ISSUE TITLE
Replace Bottle by FastAPI

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2181]
Trade-off should be made between the current Bottle Framework and a new one like FastAPI (see https://fastapi.tiangolo.com/#requirements).

**Comment by RazCrimson** [comment]
Another possible option to consider: 
https://github.com/starlite-api/starlite

**Comment by nicolargo** [comment]
Should be linked to https://github.com/nicolargo/glances/issues/2114

**Comment by Tronic** [comment]
Consider https://sanic.dev/en/ - one of the fastest Python frameworks (talking about 100 kreq/s) and has API very similar to FastAPI or Flask+async. Already proven, used in large projects (e.g. Italian government Covid tracing app). Can directly run a public web server incl. HTTP/3, and comes with other advanced features while staying low level and unopionated. Just almost nobody seems to know it exists. Disclaimer: I am a developer of it.

**Comment by RazCrimson** [comment]
@Tronic 

Assuming that the FastAPI are not biased, it might be better to just stick with FastAPI
Ref: https://fastapi.tiangolo.com/alternatives/#sanic


Litestar/Starlite seemed interesting but seems to be quite less used than FastAPI. FastAPI also has a huge userbase with lot of community support, so I think sticking with it would be the best bet in a long term standpoint. 

@nicolargo What do you think?

**Comment by Tronic** [comment]
@RazCrimson Starlette is an ASGI server and can be used with Sanic as well. However, the preferred way to run Sanic is using its integrated HTTP server which runs much faster than what is possible via ASGI. That being said, FastAPI can run fairly quick too. I've yet to see useful conclusive benchmarking between the two, and we do not intend to compete with it for users (rather, we are interested on how to awake Flask and Django users, as well as NodeJS Express users, to that there are modern alternatives).

**Comment by RazCrimson** [comment]
@Tronic 

My bad, I should have put that a bit better.

The reason I preferred FastAPI to Sanic was not really the performance but the huge community behind it. So in the end FastAPI would end up being more tested for bugs and vulnerabilities than other frameworks as the larger user base would be having more diverse use cases.

**Comment by Tronic** [comment]
@RazCrimson Not sure whether you'll get that, as it is a very young framework and only built for JSON APIs (rather than diverse use cases). But yes, it certainly seems more popular at this time and has more active developers, so I understand why you'd go with that.

**Comment by nicolargo** [comment]
Work started on branch issue2181

**Comment by nicolargo** [comment]
Merged into develop.

**BREAKING CHANGE**: API version is now 4.
