### ISSUE TITLE
docker version 3.3.0.4 breaks nvidia gpu sensors

### ISSUE THREAD

**Issue by vajonam** [nicolargo/glances#2185]
**Describe the bug**
Moving from 3.3.0.2 docker image to 3.3.0.4 broke my GPU sensors.

**To Reproduce**
Upgrade to 3.3.0.4

**Expected behavior**
gpu sensors and nvidia-smi works

Latest 3.3.0.4, causes the nvidia-smi command to stop work working, as well see nvml initialization errors in the log. downgrading back to 3.3.0.2 fixes the problem. Looking through the commits its not obvious as to what the issue is.

**Comment by vajonam** [comment]
Suspect its the move from debian to apline, and its missing some libs that prevent it from working as intended.

**Comment by vajonam** [comment]
Would request you provide debian images still for sometime until nvidia can run in alpine based distros.

https://github.com/NVIDIA/nvidia-docker/issues/1606

**Comment by hadim** [comment]
I confirm that GPU monitoring is broken using `3.3.0.4-full` while `3.3.0.2-full` works well.

**Comment by nicolargo** [comment]
Default Glances images are now Alpine based...

Any contributor is welcome to create and maintain a Debian (or other OS) based image.

**Comment by nicolargo** [comment]
A new docker file provided by @imyhxy is available in the develop (see branch: https://github.com/nicolargo/glances/pull/2234).

For the moment, the image is not automatically published to Docker Hub (some test should be done).

**Comment by nicolargo** [comment]
Github action failed when Ubuntu Dockerfile is used: see error https://github.com/nicolargo/glances/actions/runs/4396480385/jobs/7698953147

    ERROR: failed to solve: nvidia/cuda:12.1.0-base-ubuntu22.04: no match for platform in manifest 

Need investigation.

**Comment by RazCrimson** [comment]
Verified to be working on my end

**Comment by vajonam** [comment]
@nicolargo  will this be available with the non -dev tag, I would like to use this but maybe on a stable?

**Comment by RazCrimson** [comment]
@vajonam 
This would be in stable with the next release (3.4.0)
