### ISSUE TITLE
Glances process staying asleep instead of reporting

### ISSUE THREAD

**Issue by spikeygg** [nicolargo/glances#2186]
I have glances installed on six machines in my house (two orange pis, a raspberry pi, a small ITX board, a NUC, and a server). It works great on all of them except for the raspberry Pi (which is a Voron 2.4 running raspbian). I watch all the data from a dashboard on Home Assistant and it seems the glances process on the Voron 2.4 raspberry Pi machine (Pi4 /w 8GB ram) is always sleeping. What's strange is that I can hit the URL and it will eventually respond (albeit very slow to come up on the first hit, takes literally 10s to pop up) and then it will record some data in Home Assistant for a while but eventually it goes back to sleep and stops reporting to Home Assistant.

I tried making the glances process on that machine "less nice" setting the "nice" number to -1 ahead of nearly all other processes but it still sleeps most of the time. I think it might be related to the raspbian OS preferring a low-power state... I just don't know where to look for that kind of a switch. I ran raspi-config but didn't see anything that looked promising in there.

**To Reproduce**
1. I start glances on the Voron 2.4 Pi
2. Allow it to run for some time, the process goes to sleep
3. I see that the values in the Home Assistant chart are static for hours: 
![image](https://user-images.githubusercontent.com/1015891/200860015-0308e3b4-c4bb-4f19-b522-16c7892a4a50.png)

4. Attempt to navigate to the glances URL and see that the process isn't dead - URL takes about 10 seconds to come up.
5. After bringing up the glances URL, the Home Assistant chart refreshes and shows a new datapoint, revealing that the history was stuck: 
![image](https://user-images.githubusercontent.com/1015891/200860102-358ab27d-3ddc-4475-bf41-d02465521e4f.png)

**Expected behavior**
As all the other machines in my house, I'd expect to have continuous data points recorded in Home Assistant as the process serves them up. I assume that the process is going to sleep shortly after I manually visit the glances URL.

**Screenshots**
I have attached screenshots above in my "To Reproduce" section.

**Desktop (please complete the following information):**
 - OS: 
```
 $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
$
```

 - Glances Version [output of glances -V]
```
$ glances -V
Glances v3.2.4.2 with PsUtil v5.8.0
Log file: /home/spikeygg/.local/share/glances/glances.log
$
```

 - Glances logs file [output of tail -10 <glances logs file>]
```
$ tail -10 /home/spikeygg/.local/share/glances/glances.log
2022-10-24 22:34:09,706 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2022-10-24 22:34:09,723 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2022-10-24 22:34:09,723 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2022-10-24 22:34:09,726 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2022-10-24 22:34:09,731 -- WARNING -- Error loading Docker Python Lib. Docker plugin is disabled (No module named 'docker')
2022-10-24 22:34:09,732 -- ERROR -- docker plugin - Can not connect to Docker (name 'docker' is not defined)
2022-10-24 22:34:17,108 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2022-10-24 22:34:17,121 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/
2022-11-09 07:46:01,782 -- INFO -- Start Glances 3.2.4.2
2022-11-09 07:46:01,782 -- INFO -- CPython 3.9.2 (/usr/bin/python3) and psutil 5.8.0 detected
$
```

 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
```
$ glances --issue
====================================================================================================================================================================================
Glances 3.2.4.2 (/usr/local/lib/python3.9/dist-packages/glances/__init__.py)
Python 3.9.2 (/usr/bin/python3)
PsUtil 5.8.0 (/usr/lib/python3/dist-packages/psutil/__init__.py)
====================================================================================================================================================================================
alert         [OK]    0.00005s []
amps          [OK]    0.00020s []
cloud         [OK]    0.00014s {}
connections   [OK]    0.08662s {'LISTEN': 15, 'ESTABLISHED': 10, 'SYN_SENT': 0, 'SYN_RECV': 0, 'initiated': 0, 'terminated': 0}
core          [OK]    0.00127s {'phys': 4, 'log': 4}
cpu           [OK]    0.00107s {'total': 22.9, 'user': 2.8, 'nice': 17.1, 'system': 2.3, 'idle': 77.4, 'iowait': 0.0, 'irq': 0.0, 'softirq': 0.3, 'steal': 0.0, 'guest': 0
diskio        [OK]    0.00215s key=disk_name [{'time_since_update': 3.1026041507720947, 'disk_name': 'loop0', 'read_count': 0, 'write_count': 0, 'read_bytes': 0, 'write_b
docker        [OK]    0.00017s []
folders       [OK]    0.00012s []
fs            [OK]    0.00148s key=mnt_point [{'device_name': '/dev/root', 'fs_type': 'ext4', 'mnt_point': '/', 'size': 31234383872, 'used': 9218088960, 'free': 207150858
gpu           [OK]    0.00011s []
help          [OK]    0.00002s None
ip            [OK]    0.00012s {}
irq           [OK]    0.00154s key=irq_line [{'irq_line': 'IPI3', 'irq_rate': 1747, 'key': 'irq_line', 'time_since_update': 3.1008026599884033}, {'irq_line': '27_arch_tim
load          [OK]    0.00021s {'min1': 0.79, 'min5': 1.07, 'min15': 1.05, 'cpucore': 4}
mem           [OK]    0.00059s {'total': 4025393152, 'available': 3478884352, 'percent': 13.6, 'used': 546508800, 'free': 3478884352, 'active': 397754368, 'inactive': 932
memswap       [OK]    0.00085s {'total': 104853504, 'used': 0, 'free': 104853504, 'percent': 0.0, 'sin': 0, 'sout': 0, 'time_since_update': 3.167245626449585}
network       [OK]    0.00118s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update': 3.103731155395508, 'cumulative_rx': 7416378363, 'rx': 3658
now           [OK]    0.00005s 2022-11-09 07:47:21 MST
percpu        [OK]    0.00105s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 19.2, 'user': 1.0, 'system': 2.0, 'idle': 80.8, 'nice': 15.6, 'iowait': 0.0
ports         [OK]    0.00052s []
processcount  [OK]    0.11726s {'total': 168, 'running': 2, 'sleeping': 105, 'thread': 227, 'pid_max': 0}
processlist   [OK]    0.00092s key=pid [{'ppid': 18800, 'io_counters': [0, 0, 0, 0, 1], 'gids': pgids(real=1001, effective=1001, saved=1001), 'cpu_times': pcputimes(user=
psutilversion [OK]    0.00013s (5, 8, 0)
quicklook     [OK]    0.00082s {'cpu': 22.9, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 19.2, 'user': 1.0, 'system': 2.0, 'idle': 80.8, 'nice': 15.6, 'iow
raid          [OK]    0.00007s {}
sensors       [OK]    0.00002s key=label [{'label': 'cpu_thermal 1', 'value': 55, 'warning': None, 'critical': None, 'unit': 'C', 'type': 'temperature_core', 'key': 'labe
smart         [N/A]
system        [OK]    0.00002s {'os_name': 'Linux', 'hostname': 'voron', 'platform': '32bit', 'linux_distro': 'Raspbian GNU/Linux 11', 'os_version': '5.15.61-v7l+', 'hr_n
uptime        [OK]    0.00029s {'seconds': 1329224}
wifi          [OK]    0.00007s []
$
```

**Additional context**
This has been an issue for nearly a year and I periodically Google to try to find a resolution but I have never found anyone else with the same kind of problem. I'd love to get to the bottom of this so if you have any suggestions of things to try, I'm all ears.

**Comment by nicolargo** [comment]
Hi @spikeygg, first of all thanks for this complete issue report.

It is not easy to investigate on my side because i did not have any Raspberry Pi. So can you please make a simple test by disabling the top comsuming plugins ? 

Just run Glances with the **--disable-plugin processcount,connections** option.

Is it better ?

**Comment by spikeygg** [comment]
Thanks for the response @nicolargo! I understand the difficulty you pointed out. I'm happy to help debug on my end if you have any more suggestions. I just restarted the service with the switches you recommended, I'll let it run for 24hrs and let you know tomorrow how it responds.

**Comment by spikeygg** [comment]
I took a look at the Home Assistant charts just now and it looks like they're stagnating just like before. :(

It's probably some indirect environment variable in raspbian and not directly related to glances. :-/

**Comment by spikeygg** [comment]
I tried something different, tonight. I realized recently that there's a docker container for glances. I really like running things in containers so I uninstalled the glances app from my Linux installation and installed the docker container version. When I got it up and running I verified that the web interface worked and looked correct.

I reconnected Home Assistant to it and watched it, it was working. However, I closed the web interface tab for glances and within a minute or two after closing the web interface tab the Home Assistant entities went unavailable. They stay that way until I manually reopen the web interface in my browser. This problem is super weird!

The other thing I notice, is when I navigate back to the web interface page after it has gone dormant. It takes a while to pull it up, like 10 seconds of a blank webpage, then it displays all the glances stuff. Anyway, more data points.

**Comment by bignay2000** [comment]
> I tried something different, tonight. I realized recently that there's a docker container for glances. I really like running things in containers so I uninstalled the glances app from my Linux installation and installed the docker container version. When I got it up and running I verified that the web interface worked and looked correct.
> 
> I reconnected Home Assistant to it and watched it, it was working. However, I closed the web interface tab for glances and within a minute or two after closing the web interface tab the Home Assistant entities went unavailable. They stay that way until I manually reopen the web interface in my browser. This problem is super weird!
> 
> The other thing I notice, is when I navigate back to the web interface page after it has gone dormant. It takes a while to pull it up, like 10 seconds of a blank webpage, then it displays all the glances stuff. Anyway, more data points.

I have a similar experience with Glances 3.4.0 running in Docker on a Linux VM...  The page hangs and then after a few attempts the page loads.   I use Uptime Kuma and it graphs the uptime.  Glances regularly exceeds 48000ms load time (Glances set to retry 3 times and then fail).  I have many docker applications that run on the same VM and they have 100% uptime, so I am confident that their is something with Glances that causes it to "Go to sleep" or something.  Docker logs only shows a single line that Glances Started..  

![Glances_Uptime](https://github.com/nicolargo/glances/assets/11713022/3f5079c2-afea-42d5-afbb-69724c2ccb51)

**Comment by spikeygg** [comment]
I ran a little test today after re-installing the OS (32-bit bookworm now) on this system. Previously, it was 64-bit bullseye. Anyway, I installed the docker setup and ran the glances container. I then held a browser tab open to the glances webpage for an hour (on a remote PC) while also watching the Home Assistant history. I could see that it was getting some data periodically but it also had dropouts. Eventually, I closed the tab and kept watching and at that point the connection dies between Home Assistant and the glances host. Here's a visual representation of that:
![image](https://github.com/nicolargo/glances/assets/1015891/e875c04f-7db0-44ce-9da6-bb65c58ccca3)

This "Voron" system also hosts services for controlling a connected 3D printer via web-services and those work flawlessly; so, I'm pretty sure the problem is something inside the glances container.

**Comment by Joe13183** [comment]
I'm having the same issue on ubuntu :-(

**Comment by nicolargo** [comment]
Anyone encounter this issue with Glances 4 ?

**Comment by nicolargo** [comment]
I close the issue because no news about it after upgrading to Glances 4.x.
