### ISSUE TITLE
Hide public IP by default on web ui

### ISSUE THREAD

**Issue by sfn-git** [nicolargo/glances#2190]
**Is your feature request related to a problem? Please describe.**
Currently on the web ui for glances, the public IP of the server is revealed by default. For my specific use case, I like to keep this window open on my web browser and it is not ideal to have the public IP displayed all the time when the window is visible. 

**Describe the solution you'd like**
Make the public IP hidden by default and add some functionality to reveal it by either clicking it or hovering over it on the web ui. 

**Describe alternatives you've considered**
I could possibly disable the public IP to appear but it can be useful to gain that information from glances since it is something I am already using. 

**Additional context**
This is only in reference to the web ui.

**Comment by nicolargo** [comment]
Hi @sfn-git 

It's already implemented in Glances 3.2.6 or higher.

Just use the following option in the Glances configuration file:

```
[ip]
public_ip_disabled=True
```
