### ISSUE TITLE
action_repeat not appending to file

### ISSUE THREAD

**Issue by samcro1967** [nicolargo/glances#2206]
**Describe the bug**
`iowait_critical_action_repeat=echo {{iowait}} {{percent}} >> /glances/alerts/iowait.alert` does not append to existing file.

**To Reproduce**
1. add repeating action to glances.conf
2. touch /glances/alerts/iowait.alert
3. chmod 777 /glances/alerts/iowait.alert
4. Restart glances container
5. tail /glances/alerts/iowait.alert -f - file never changes and is always blank

**Expected behavior**
`iowait_critical_action_repeat=echo {{iowait}} {{percent}} >> /glances/alerts/iowait.alert` appends to existing file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
-  Docker: 20.10.19
 - Glances Version: Glances v3.3.0.2 with PsUtil v5.9.3
 - Glances logs file 
[glances.txt](https://github.com/nicolargo/glances/files/10050329/glances.txt)

 - Glances test
<details>

```
glances --issue
==================================================================================================================================
Glances 3.3.0.2 (/usr/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.5 (/usr/bin/python3)
PsUtil 5.9.3 (/usr/lib/python3.10/site-packages/psutil/__init__.py)
==================================================================================================================================
alert         [OK]    0.00001s []
amps          [OK]    0.00005s []
cloud         [OK]    0.00002s {}
connections   [OK]    0.28246s {'LISTEN': 2, 'ESTABLISHED': 0, 'SYN_SENT': 0, 'SYN_RECV': 0, 'initiated': 0, 'terminated
core          [OK]    0.00073s {'phys': 4, 'log': 8}
cpu           [OK]    0.00207s {'total': 56.6, 'user': 28.9, 'nice': 11.1, 'system': 14.3, 'idle': 43.0, 'iowait': 0.4,
diskio        [OK]    0.00119s key=disk_name [{'time_since_update': 3.6256816387176514, 'disk_name': 'loop0', 'read_coun
docker        [OK]    0.38130s key=name [{'key': 'name', 'name': 'bettercovers', 'Id': 'd0094a0eea7cb01c420cb8c6187f18ab
folders       [OK]    0.00007s []
fs            [OK]    0.00053s key=mnt_point [{'device_name': '/dev/sda1', 'fs_type': 'ext4', 'mnt_point': '/etc/timezon
gpu           [OK]    0.00002s []
help          [OK]    0.00000s None
ip            [OK]    0.00016s {'gateway': '172.19.0.1', 'address': '172.19.0.33', 'mask': '255.255.0.0', 'mask_cidr': 1
irq           [OK]    0.00026s key=irq_line [{'irq_line': 'CAL', 'irq_rate': 53466, 'key': 'irq_line', 'time_since_updat
load          [OK]    0.00004s {'min1': 3.72900390625, 'min5': 4.29296875, 'min15': 5.57373046875, 'cpucore': 8}
mem           [OK]    0.00015s {'total': 33410748416, 'available': 15013367808, 'percent': 55.1, 'used': 18397380608, 'f
memswap       [OK]    0.00020s {'total': 6442446848, 'used': 2928746496, 'free': 3513700352, 'percent': 45.5, 'sin': 863
network       [OK]    0.00031s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update': 2.673405
now           [OK]    0.00001s 2022-11-20 11:37:36 CST
percpu        [OK]    0.00040s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 52.3, 'user': 22.1, 'syst
ports         [OK]    0.00025s []
processcount  [OK]    0.39192s {'total': 1192, 'running': 4, 'sleeping': 1101, 'thread': 6263, 'pid_max': 0}
processlist   [OK]    0.00120s key=pid [{'name': 'tracker-miner-fs-3', 'num_threads': 6, 'pid': 44256, 'io_counters': [9
psutilversion [OK]    0.00004s (5, 9, 3)
quicklook     [OK]    0.00035s {'cpu': 56.6, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 52.3, 'user': 22
raid          [OK]    0.00013s {}
sensors       [OK]    0.00056s []
smart         [OK]    0.00100s []
system        [OK]    0.00001s {'os_name': 'Linux', 'hostname': 'glances', 'platform': '64bit', 'linux_distro': 'Alpine
uptime        [OK]    0.00008s {'seconds': 283036}
wifi          [OK]    0.00002s []
==================================================================================================================================
Total time to update all stats: 1.08377s
==================================================================================================================================
```
</details>

**Additional context**
`iowait_critical_action_repeat=echo {{iowait}} {{percent}} > /glances/alerts/iowait.alert` does work creating a new file each alert.

**Comment by samcro1967** [comment]
I also tried piping an echo to `tee -a` and it also does not work.  If I try either from the container cli after connecting via docker exec, I can append to a filer without issue.  Seems to only not work in the running context of glances.

**Comment by nicolargo** [comment]
Hi @samcro1967 

concerning the pipe, as written in the documentation (https://glances.readthedocs.io/en/develop/aoa/amps.html), for security reason, pipe is not directly allowed in a AMP command but you create a sheel script with your command:

```
$ cat /usr/local/bin/mycommand.sh
#!/bin/sh
ps -aux | wc -l
```

and use it in the amps:

```
[amp_amptest]
enable=true
regex=.*
refresh=15
one_line=false
command=/usr/local/bin/mycommand.sh
```

Not sure that the redirection works...

**Comment by samcro1967** [comment]
@nicolargo I missed that in the docs.  Sorry about that.  Unfortunately I am not a developer let along a python developer.  Appreciate you pointing out though why it is not working.  Was driving me crazy.  I will keep looking for another solution to my quandary.

**Comment by nicolargo** [comment]
@samcro1967 

A possible implementation for your need:

1. Create a shell script (for example located in /usr/local/bin/myscript.sh) **with the following content**:

```
#!/bin/sh
echo $1 $2 >> /glances/alerts/iowait.alert
```

2. Make this script executable:

```
chmod a+x /usr/local/bin/myscript.sh
```

3. Configure your AMP in your Glances configuration file:

```
[amp_myamp]
enable=true
regex=.*
refresh=15
one_line=false
command=/usr/local/bin/myscript.sh {{iowait}} {{percent}}
```

4. Start Glances, it should update the file every 15 seconds...

**Comment by samcro1967** [comment]
Did not realize they was a generic AMP for commands.  That does work in appending the file, but variables are not expanded so I end up with `date {{iowait}} {{percent}}` instead of the real values.

I did `pip install pystache` in the container, restarted it, and the variables are expanded in my `iowait_critical_action_repeat` with just one `>`.

Looks like AMP just runs every 15s rather than only on critical correct?
