### ISSUE TITLE
Erroung while mounting the /etc/glances.conf

### ISSUE THREAD

**Issue by pokemaster974** [nicolargo/glances#2210]
**Describe the bug**
I receive errors when trying to install Glances into my QNAP NAS via the Docker way.
My command line :
```
docker run -d \
	--name=glances \
	--restart always \
	--net=reverseproxy \
	-p 61208-61209:61208-61209 \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /share/Docker/Config/Glances/glances.conf:/etc/glances.conf \
	-e GLANCES_OPT="-w -C /etc/glances.conf" \
	--pid=host \
	nicolargo/glances:latest-full
```
Normally it works using the -v argument to mount volumes with my other containers, but I get errors with Glances :

> docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/share/Docker/Config/Glances/glances.conf" to rootfs at "/etc/glances.conf": mount /share/Docker/Config/Glances/glances.conf:/etc/glances.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

After this, I see that a folder glances.conf is created.
If I remove it and let the sock mounting only, no issue.

**To Reproduce**
1. Copy and paste the command line
2. See error

**Expected behavior**
Using the glances.conf file and not creating a glances.conf folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux Ubuntu 20.04]
 - Glances Version [output of glances -V]
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**
None

**Comment by RazCrimson** [comment]
@pokemaster974 
Just to clarify, this issue is related to docker rather than glances itself.

Now to fix/make it work, could you check the file path once more to make sure there are no typos?
Docker usually creates a directory if it can't find a file/directory in the path specified.
So most probably there is some typo in the path.

Ref for more details: [StackOverflow](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume)

Feel free to tag in case you need more help.

**Comment by pokemaster974** [comment]
> @pokemaster974 Just to clarify, this issue is related to docker rather than glances itself.
> 
> Now to fix/make it work, could you check the file path once more to make sure there are no typos? Docker usually creates a directory if it can't find a file/directory in the path specified. So most probably there is some typo in the path.
> 
> Ref for more details: [StackOverflow](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume)
> 
> Feel free to tag in case you need more help.

My bad, it was glances.conf.txt.
Thanks for the reply !
