### ISSUE TITLE
[WINDOWS] Glances quit when terminal is resized

### ISSUE THREAD

**Issue by Silentdoer** [nicolargo/glances#2213]
**Describe the bug**
Windows 10, latest glances, powershell and nushell
resize terminal/console glances will quit

**To Reproduce**
1. Start Glances with the following options '...'
2. Press the key '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux Ubuntu 20.04]
 - Glances Version [output of glances -V]
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**

**Comment by Silentdoer** [comment]
I'm sorry, but I exited without an error after narrowing the window

**Comment by nicolargo** [comment]
@Silentdoer if you reproduce the error, please copy paste the error message. it will help us to correct the isssue.

Thanks !

**Comment by ackhh** [comment]
Glances crashes without giving an error message, same problem as reported by me some time ago. Would a .dmp-file help?

**Comment by nicolargo** [comment]
I close the current issue. 

If someone with Glances 4.x on Windows can reproduce this issue, please open a new issue with a .dmp-file

**Comment by nicolargo** [comment]
May be related to https://github.com/nicolargo/glances/issues/2213
