### ISSUE TITLE
Inconsistent data from different mdadm RAID0 arrays

### ISSUE THREAD

**Issue by gregewing** [nicolargo/glances#2235]
**Describe the bug**
I have the :dev docker image installed on 2 docker hosts which have physical RAID Arrays, one is a raid5 array, the other is a raid 0. The data in glances for the raid 5 array correctly identifies it as 5 elements available, 5 in use, but the raid 0 array identifies 2 elemenets available 512k in use ( that's the chunk size )

**To Reproduce**
1 install or create suitable raid arrays and check if glances identifies the available/in-use raid elements correctly.

**Expected behavior**
correctly identify the number of elements in use.

**Screenshots**
see scteenshots of mdadm --detail for each array and corresponding output from glances.

**Desktop (please complete the following information):**
Systems in use:
Desktop-U is Ubuntu 22.04.1 LTS
room101 is Ubuntu 20.04.5 LTS
All packages are up-to-date on both systems. 

Docker image in use of both hosts :  nicolargo/glances:dev
output from glances -V 👍 /glances # glances -V
2023-01-05 10:51:03,335 -- INFO -- Start Glances 3.3.0.4
2023-01-05 10:51:03,335 -- INFO -- CPython 3.10.9 (/usr/bin/python3) and psutil 5.9.4 detected
Glances v3.3.0.4 with PsUtil v5.9.4
Log file: /tmp/glances-root.log

 - OS: [e.g. GNU/Linux Ubuntu 20.04]
 - Glances Version [output of glances -V]
 - Glances logs file [output of tail -10 <glances logs file>]
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

**Additional context**
![Screenshot 2023-01-05 104657](https://user-images.githubusercontent.com/31736614/210762544-0897a494-1bc7-41f5-8ae9-9bfbf3b75f09.png)
![Screenshot 2023-01-05 104801](https://user-images.githubusercontent.com/31736614/210762547-ee3cb891-f836-4e23-8205-ee96b90a6bb5.png)

**Comment by nicolargo** [comment]
Hi @gregewing 

first of all thanks for the bug report.

Can you please copy paste the content of your /proc/mdstat file ?

**Comment by gregewing** [comment]
sure, no problem.  from the same two machines in the same order :



root@Desktop-U:~# cat /proc/mdstat
Personalities : [raid0] [linear] [multipath] [raid1] [raid6] [raid5] [raid4] [raid10]
md0 : active raid0 sda1[0] sde1[1]
      488130560 blocks super 1.2 512k chunks

unused devices: <none>


and


root@room101:~# cat /proc/mdstat
Personalities : [raid6] [raid5] [raid4] [linear] [multipath] [raid0] [raid1] [raid10]
md5 : active raid5 sdf1[8] sde1[7] sdd1[5] sdc1[1] sdb1[6]
      15619063808 blocks super 1.2 level 5, 512k chunk, algorithm 2 [5/5] [UUUUU]
      bitmap: 4/30 pages [16KB], 65536KB chunk

unused devices: <none>


Thanks
Greg

**Comment by nicolargo** [comment]
Hi @gregewing 

i have made a patch on PyMdStat. Please can you test the latest dev docker images ?

It should  solve the issue.

Nicolas

**Comment by gregewing** [comment]
Hi, thanks very much, but I'm not convinced that this has solved the problem.

I now get the following on the command line:

***@***.***:~#
***@***.***:~# curl -X GET http://127.0.0.1:61208/api/3/raid
***@***.***:~#
***@***.***:~#
***@***.***:~#



________________________________

**Comment by nicolargo** [comment]
Strange, it works on my side:

![image](https://user-images.githubusercontent.com/776747/216771105-43faa88d-3a6d-4150-81f5-51c6b29eb465.png)

and also in the Console UI (glances -C ./conf/glances.conf --enable-plugin raid):

![image](https://user-images.githubusercontent.com/776747/216771175-f3bdb7cc-bd62-416b-8f54-cb547100ce40.png)

**Comment by gregewing** [comment]
Hi,  I just wanted to feed back that I have checked I'm using the latest dev build of glances, and I can see the output of the RAID Plugin at the command line, and I see the data in HomeAssistant, so that integration is picking up the data correctly, but it does not show up in the WebUI.  I can toggle it in the console, but not in the WebUI.  I can toggle other thing line network and disks fine in console and webUI.  ( another issue to log perhaps ?)  But this is as it was before I logged the issue.

I don't currently have access to the other server with RAID in it to check this all out on that machine ( my eldest is using it to make games whith GameMaker ).  but will check it when I have an opportunity and let you know what I see.

Thanks
Greg
________________________________

**Comment by nicolargo** [comment]
@gregewing any news concerning the issue ?

**Comment by gregewing** [comment]
Apologies. Started a new job and not had the time to follow up. Thanks for the reminder.

Thanks and Regards
Greg Ewing
________________________________

**Comment by nicolargo** [comment]
Ok @gregewing !

I let the issue open, if you have any chance to test the new version, do not hesitate to tell us. 

Good luck for your new job.
