### ISSUE TITLE
Mustache not available in actions in official docker

### ISSUE THREAD

**Issue by attilabalazsy** [nicolargo/glances#2238]
**Describe the bug**
I'm using the official docker image (nicolargo/glances) on my system and trying to setup a notification through apprise. The main logic is working, the notification arrives, but I cannot include the metric numbers as the mustache variables are not propagated. It seems, that the required chevron library is not installed in the container

**To Reproduce**
INFO -- Action triggered for mem (critical): echo "Memory usage is {{percent}}" > /tmp/x.alert && /glances/conf/notify.sh

**Expected behavior**
INFO -- Action triggered for mem (critical): echo "Memory usage is 80" > /tmp/x.alert && /glances/conf/notify.sh

**Additional context**
Current workaround is to install chevron manually into the image:

apk add py3-pip
pip install chevron

**Comment by RazCrimson** [comment]
Are you using the base image (plain glances) or the `glances-full` one?

If you are using the plain image, please try the ones tagged with full and check if you experience the issue again.

**Comment by attilabalazsy** [comment]
@RazCrimson thanks for the hint, yes, I was using the base image. Now, I've switched to the full one, and the mustache is working as expected.
