### ISSUE TITLE
AMP is not triggered when web is not opened

### ISSUE THREAD

**Issue by attilabalazsy** [nicolargo/glances#2240]
**Describe the bug**
I'm using a the default AMP to trigger push to my monitoring system (uptime-kuma). This is monitoring the availability of the server (if heartbeat is not coming, the server is taken as off). Glances is running in web mode (-w switch). When the web is opened, then all is good, the push notifications are sent to the monitoring system, but when I close the website, the push is not triggered anymore. When I start the web, all is good again.

**To Reproduce**
[amp_heartbeat]
enable=true
regex=.*
refresh=27
one_line=true
command=curl -s -X GET https://status.domain.com/api/push/ID

**Expected behavior**
The AMP should be executed all time disregard of the web is opened or not

**Desktop (please complete the following information):**
 - Official docker image (latest-full)

**Comment by attilabalazsy** [comment]
Is this the same as #1879?

**Comment by nicolargo** [comment]
Hi @attilabalazsy ,

it is not directly related to the issue https://github.com/nicolargo/glances/issues/1879.

For the moment, the Glances architecture do not allow actions to be triggered if no client are connected (in order to avoid resource consumption is no client are connected).

We know that it's a limitation that will be solved by design in future version (perhaps version 4). For the current branch (Glances 3.x), i will try to have a look if a workaround is possible.

Any ideas are welcomes.

**Comment by attilabalazsy** [comment]
Hi @nicolargo,

Thanks for your answer and confirmation. Unfortunately I cannot really do any suggestion from architectural side. From user side, I can:
In my opinion the notifications are one of the most critical things in a monitoring system as nobody is really sitting before a dashboard to watch if everything is OK. Mainly if you have more servers. The system should be able to catch the issue(s) automatically and notify the admin (in the best case can also try to solve it), so it can act.
In my configuration, I'm using a simple bash script which is sending the notifications out through Apprise/ntfy.sh. It is working fine, when I'm connected to the portal.

As a workaround I'm using a cron job (through Ofelia) to read the web:
ofelia.job-exec.datecron.command: "curl http://localhost:61208"

This is correctly triggering the actions.

If this is an issue for limited number of users, then maybe you can just make it optionally (enable-auto-trigger: on/off). As an easiest workaround would be the same, I'm doing, but internally. There could be an internal cron job :)

Hope this helps!

**Comment by Metatropics** [comment]
Hey @attilabalazsy can you explain your solution? How and why are you calling Kuma instead of a directly to notification service?

**Comment by attilabalazsy** [comment]
Hi @Metatropics, currently I'm doing the following:
1) There is an amp trigger, which is doing a heartbeat to Kuma to monitor the monitoring (Glances). If the heartbeat is not coming, then Kuma notifies me, that something is wrong with Glances, so I cannot expect any other notifications from Glances.
2) I've several actions configured in Glances for critical memory, disk space etc, which are calling directly the notification service (apprise). Example:
total_critical_action=echo CPU usage is critical ({{total}}%) > /tmp/x.alert && /glances/conf/notify.sh

notify.sh:
#!/bin/sh
value=`cat /tmp/x.alert`
curl -X POST -d "{\"tag\":\"dockerwarn\",\"body\":\"$value\",\"title\":\"RPI4 alert\"}" -H "Content-Type: application/json" https://notify.mydomain.com/notify/apprise

The issue here is, that Glances is triggering AMP and alerts only, when you open it in a browser. Which is wrong in my case, as I would like to use it as a background monitoring service. As a workaround I use a cron job (through Ofelia) to simulate the web (wget), which is then triggering all othe other internal processes, described above.

**Comment by nicolargo** [comment]
@attilabalazsy 

I have a possible workaround for your need.  As i said, Glances actions are only triggered if a client is connected. When a server with a -w option is launch, nothing is done until a client send a request. By client we mean the Glances Web UI or a simple "curl" process ran every 'n' minutes.

My proposal is to create a simple glancestrigger.sh script:

```
#!/bin/sh  
curl -s -o /dev/null http://<YOUR GLANCES SERVER>:61208/api/3/all
```

-s si for silent mode
-o is to redirect the output to a file (nothing with /dev/null)
<YOUR GLANCES SERVER> is the IP @ or name of your Glances server (or localhost if your script is ran on the same host.

Then [cron](https://crontab.guru/#*_*_*_*_*) this script every 'n' minutes. 

```
# crontab -e
* * * * * /path/to/glancestrigger.sh
```

With this configuration, actions should be triggered.

Can you give it a try on your configuration and tell us if it is working ?

Additional note: if you want to go lower than every minute (why ?), please [read this](https://stackoverflow.com/questions/30295868/how-to-setup-cron-job-to-run-every-10-seconds-in-linux).  Lower n is, higher is the CPU consumption.

**Comment by attilabalazsy** [comment]
@nicolargo thanks for your response. Currently I'm using a very similar approach, but instead of calling the API endpoint, I'm requesting the site itself, using "curl http://localhost:61208". Is there any difference calling "curl http://localhost:61208" and "curl -s -o /dev/null http://<YOUR GLANCES SERVER>:61208/api/3/all"?

I'm not executing the cron tasks directly but through ofelia.

**Comment by nicolargo** [comment]
It is more or less the same thinks. When you use the site, it will request the static page (JS) then the static page calls the API end-point.

Note that if you never use the "page" you can run Glances with the --disable-webui in order to disable the JS and only expose the API.
