### ISSUE TITLE
no local processes

### ISSUE THREAD

**Issue by Shadow27374** [nicolargo/glances#2250]
Hello,

I have run glances as follows via docker-compose:

> glances:
>   image: nicolargo/glances:latest-full
>   container_name: glances
>   restart: always
>   network_mode: "host"
>   volumes:
>     - /var/run/docker.sock:/var/run/docker.sock
>   environment:
>     - "GLANCES_OPT=-w"

All containers are displayed and some sensors and the NVMe but no local processes are displayed at all like e.g. htop would do.

![1](https://user-images.githubusercontent.com/12917384/213465068-8c37c2ce-7d5f-4f21-88ef-5c0b553d6294.png)

Have I configured something wrong?

**Comment by nicolargo** [comment]
Glances provides a simple "out-of-the-box" Docker-Compose file with all the needed parameters, please have a look on it:

https://github.com/nicolargo/glances/blob/develop/docker-compose/docker-compose.yml

**Comment by Shadow27374** [comment]
I have now tried it with this:

pid: "host
privileged: true

It works now probably it is because of pid: "host" sounds at least logical.
I couldn't find anything in the "manual", so an explanation would have been nice. A RTFM is out of place here!
