### ISSUE TITLE
Smartmontools missing from full docker image

### ISSUE THREAD

**Issue by oracleguy** [nicolargo/glances#2262]
**Describe the bug**
The bug first reported in issue #1926 has returned. It looks like after the PR that fixed that issue, the docker files were redone and smartmontools is no longer installed in the full image.

**To Reproduce**
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -e GLANCES_OPT="--enable-plugin smart --enable-plugin raid" --privileged -it nicolargo/glances:latest-full`

**Expected behavior**
The SMART status of the drives should show up.

The smartmontools should be installed so that the smart plugin can work.

**Additional context**
After adding the smartmontools into the image, the SMART status shows up through the console via docker but if I pass the -w and run it in webserver mode, the SMART status (and the RAID status) do not show up in the web server. So there is likely some other bug going on as well.

**Comment by nicolargo** [comment]
Smartmontools should be included in the new Alpine image.

==> https://pkgs.alpinelinux.org/package/edge/main/x86/smartmontools

**Comment by nicolargo** [comment]
Done on the develop branch.

**Comment by nicolargo** [comment]
To be tested !
cc @oracleguy

**Comment by oracleguy** [comment]
@nicolargo I tested it with the command
```docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -e GLANCES_OPT="--enable-plugin smart --enable-plugin raid" --privileged -it nicolargo/glances:dev```

And the smart data didn't come up. I went into the container and the smartmon tools are there so perhaps something else is going on?

**Comment by nicolargo** [comment]
Have you pull the latest Docker image (_**docker pull nicolargo/glances:dev**_) before making your test ?

**Comment by Rjaap** [comment]
Coping with the same problem and seeing there was no additional feedback given I thought I might add my own. 

I tested the following:
1. docker install of dev
2. docker install of latest-full
3. docker install of alpine latest full
4. regular install on Ubuntu 22.04, terminal mode

Docker run with: docker run -d --name glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w --enable-plugin smart" --privileged -it -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances:alpine-latest-full

Results:
1, 2 and 3: no smartinfo in webserver or console mode. Glances sees /dev/sda but no information on disk space / tempsensors
4. Glances sees /dev/sda, disk IO, mount points and disk space but, no tempsensors, out of the box without specifying any plugin.

Just a quick guess, could this be a case of missing administrator rights? The smart plugin does only work with administrator rights, does it?

**Comment by HarlemSquirrel** [comment]
Anyone figure this out? It would be great to get smart info from glances running in Docker.
