### ISSUE TITLE
API fs/mnt_point// return 404 not found 

### ISSUE THREAD

**Issue by yuriko-aya** [nicolargo/glances#2265]
**Describe the bug**
API GET /api/3/fs/mnt_point// return Error 404 not found when checking for root fs

**To Reproduce**

1. Start glances with -w and --disable-webui options
2. Send GET request to To http://localhost:61208/api/3/fs/mnt_point//
3. Got Error 404 Not Found
![](https://cloud.sanusi.id/s/YbKAB5R3oLi8wsF/preview)

**Expected behavior**
Should display root fs information as described in the docs
https://glances.readthedocs.io/en/latest/api.html#get-fs

OS: Ubuntu 22.04 and Ubuntu 22.10
Glances version: Glances v3.3.1.1 with PsUtil v5.9.1

**Comment by RazCrimson** [comment]
@yuriko-aya 

Can you try this `curl "http://localhost:61208/api/3/fs/mnt_point"` and let me know if it works?

**Comment by yuriko-aya** [comment]
yeah, the `curl "http://localhost:61208/api/3/fs/mnt_point"` is working,
The result is

`{"mnt_point":["\/","\/snap\/bare\/5","\/snap\/core\/14399","\/snap\/core\/14447","\/snap\/core18\/2667","\/snap\/core18\/2679","\/snap\/core20\/1778","\/snap\/core20\/1822","\/snap\/doctl\/1214","\/snap\/doctl\/1235","\/snap\/gnome-3-28-1804\/161","\/snap\/gnome-3-34-1804\/72","\/snap\/gnome-3-34-1804\/77","\/snap\/gnome-3-38-2004\/115","\/snap\/gnome-3-38-2004\/119","\/snap\/gtk-common-themes\/1534","\/snap\/gtk-common-themes\/1535","\/snap\/hunspell-dictionaries-1-7-2004\/2","\/snap\/musixmatch\/18","\/snap\/qt515-core20\/25","\/snap\/qt515-core20\/26","\/snap\/snap-store\/599","\/snap\/snap-store\/638","\/snap\/snapd\/17950","\/snap\/snapd\/17883","\/snap\/whatsie\/138","\/snap\/whatsie\/140","\/boot","\/boot\/efi"]}`

Well, it's good if there's a fix already.
I also checked using the develop branch and it is working.

**Comment by RazCrimson** [comment]
@yuriko-aya 

If the APIs from the develop branch are working as expected without any issues, could you go ahead and close this issue?
