### ISSUE TITLE
apt on ubuntu does not carry the required packages anymore

### ISSUE THREAD

**Issue by vans163** [nicolargo/glances#2266]
```
python-psutil
python-defusedxml
python-future
python-packaging
```
The release deb depends on these but on modern ubuntu they have been renamed to:

```
python3-psutil
python3-defusedxml
python3-future
python3-packaging
```

**Comment by RazCrimson** [comment]
@vans163 

Ubuntu's apt packaging is not handled here. They are handled by the Ubuntu team themselves. 
Reference: [https://packages.ubuntu.com/kinetic/glances](https://packages.ubuntu.com/kinetic/glances)

If you want the ubuntu package to get fixed, maybe try filing a bug report on their [bugtracker](https://bugs.launchpad.net/ubuntu/+source/glances/+filebug/+login). 
FYI, this link was in the above package page in the right sidebar.

Other methods of installation supported by this repo's maintainer can be found in the [README.rst](https://github.com/nicolargo/glances#installation)

**Comment by vans163** [comment]
Got it.
