### ISSUE TITLE
Links to documents in sample glances.conf are not valid.

### ISSUE THREAD

**Issue by shulist** [nicolargo/glances#2271]
When using the sample [glances.config](https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf) there are numerous reference links (URLs) to the supporting documents. Selecting any one of the links leads to a 404 error.

**To Reproduce**
1. Open the sample glances.conf  and select an URL to a document reference. For example under the [raid] section:
```
 [raid]
 # Documentation: https://glances.readthedocs.io/en/stable/aoa/raid.html
 # This plugin is disabled by default
 disable=True
```
2. Attempt to open this link in a browser
3. Receive a 404 error

**Expected behavior**
The associated URL opens to the correct bookmark in the document

**Recommended Solution**
The sample glances.conf needs to be updated to include current document references. For example the correct URL for the [raid] section is `https://glances.readthedocs.io/en/latest/aoa/raid.html`

**Comment by RazCrimson** [comment]
@shulist 

Are you interested in making these fixes and raising a PR?

**Comment by shulist** [comment]
@RazCrimson could possibly do it in the next few weeks as I will have some time. Let me look at it for a day.

**Comment by nicolargo** [comment]
Done on the develop branch.

Thanks for the issue report @shulist !
