### ISSUE TITLE
3.3.1.1 is available, but not on GitHub?

### ISSUE THREAD

**Issue by dataprolet** [nicolargo/glances#2276]
When closing glances it shows a short message, that version 3.3.1.1 is available, but there is only version 3.3.1 available on GitHub. Why is that?

I have installed glances using pacman, not pip.

**Comment by nicolargo** [comment]
Note for mainteners: add an how to disable message in the warning message.

**Comment by dataprolet** [comment]
Thanks, had to [find the config file](https://glances.readthedocs.io/en/latest/config.html), but now it works.
