### ISSUE TITLE
All times displayed in UTC; Container not using TZ/localtime (Docker)

### ISSUE THREAD

**Issue by NeuroDawg** [nicolargo/glances#2278]
**Describe the bug**
All times in Glances are displayed in UTC, not my local time (PST; America/Los_Angeles)

**To Reproduce**
1. Create container using nicolargo/glances:latest-full
2. Connect to glances via IP
3. Times shown are correct, but in UTC (8 hours ahead of PST)

**Expected behavior**
Times should be shown in the local timezone.

**System Info**
OS: Ubunu Server 22.04.2
Docker: 23.0.1
I also use Portainer to manipulate containers occasionally.
Glances container was created via CLI with "--PID host" since Portainer doesn't support setting a value for PID when creating a container. However, recreating/duplicating a container (to change variables) with Portainer keeps the PID setting.

**What I've Done**
I have attempted to change the timezone of my container (via Portainer) with:
1. environment variable TZ set to "America/Los_Angeles"
2. volume map /etc/localtime:/etc/localtime:ro
3. volume map /etc/timezone:/etc/timezone:ro
I've tried these alone, and in differing combinations, including setting all at once. No matter what I do, Glances shows UTC time.

This may be something I'm doing wrong, but all my other containers work with either the TZ variable set, or with mapping of /etc/timezone. 

Any/all help/advice is appreciated.

**Comment by nicolargo** [comment]
Hi @NeuroDawg 

perhaps a package (tzdata) is missing in the  Dockerfile: https://stackoverflow.com/questions/68996420/how-to-set-timezone-inside-alpine-base-docker-image ?

I will have a look as soon as possible.

Nicolas

**Comment by nicolargo** [comment]
Reproduced on my side:

make run
==> CET

make run-docker-alpine-full
==> UTC

**Comment by nicolargo** [comment]
Hi @NeuroDawg 

The next release (Glances version 3.4) will take into account the TZ environment variable.

In the meanwhile, you can test it on the **nicolargo/glances:dev** image:

    docker pull nicolargo/glances:dev
    docker run --rm -e TZ="${TZ}" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it nicolargo/glances:dev

Result on my CET (Europe) timezone:

![image](https://user-images.githubusercontent.com/776747/222950280-30b09ef8-4dca-45cc-a22d-91caad8b0263.png)

**Comment by NeuroDawg** [comment]
Downloaded the :dev image and times are showing correctly. Thanks for a quick response!
