### ISSUE TITLE
Dissociate 2 sensors with exactly the same names

### ISSUE THREAD

**Issue by ABEIDO** [nicolargo/glances#2280]
Im using Glances on my to monitor my Unraid server by importing the sensors into Home Assistant.

The issues is that im using 2 nvme disk in that machine.  The temp sensors on those is shown as Composite and Sensor 1 which is fine. I tested a spare nvme disk of other make and still same issue.

But as i have 2 nvme drive  the sensor is doubled and i dont which is which. Ive made sure that the sensors are just not the same as they do show diffrent temps from time to time
![image](https://user-images.githubusercontent.com/78364151/222913567-25c403ca-818c-470f-b7da-5cba4641c3db.png)

When trying to set alias (Composite_alias=test) its the same, the alias hits both sensors:
![1](https://user-images.githubusercontent.com/78364151/222913604-a75c0d66-3329-4059-b9b8-eec17bc53768.JPG)

Also i saw that one other had the same issue but posted in closed ticket:
https://github.com/nicolargo/glances/issues/1686#issuecomment-1425900864

**Steps to reproduce the behavior:**
1. Start Glances with the following options  -w
2. Check sensor naming in GUI

**Expected behavior**
Sensors should be named with some other naming standard when duplicate is present. For example by using more details from device and adding that or by adding a number after so user can use alias to rename if needed.

**Desktop**
Hardware:
Dell 7080 USFF

OS:
Unraid 6.11.5
NAME=Slackware
VERSION="15.0"

**Glances Version:**
Glances v3.3.1.1 with PsUtil v5.9.4

Glances logs file:
2023-03-04 15:22:01,360 -- WARNING -- Missing Python Lib (No module named 'py3nvml'), Nvidia GPU plugin is disabled
2023-03-04 15:22:01,361 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2023-03-04 15:22:01,369 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2023-03-04 15:22:01,369 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2023-03-04 15:22:01,396 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2023-03-04 15:22:01,397 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2023-03-04 15:22:01,397 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2023-03-04 15:22:01,548 -- INFO -- Issue mode is ON
2023-03-04 15:24:24,349 -- INFO -- Start Glances 3.3.1.1
2023-03-04 15:24:24,349 -- INFO -- CPython 3.10.9 (/usr/bin/python3) and psutil 5.9.4 detected

**Glances test:**

Glances 3.3.1.1 (/usr/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.9 (/usr/bin/python3)
PsUtil 5.9.4 (/usr/lib/python3.10/site-packages/psutil/__init__.py)
alert         [OK]    0.00001s []
amps          [OK]    0.00003s []
cloud         [OK]    0.00005s {}
connections   [OK]    0.00528s {'LISTEN': 24, 'ESTABLISHED': 7, 'SYN_SENT': 1, 'SYN_RECV': 0, 'initiated': 1, 'terminated': 1, 'nf_conntr
core          [OK]    0.00063s {'phys': 6, 'log': 12}
cpu           [OK]    0.00033s {'total': 9.0, 'user': 1.2, 'nice': 0.0, 'system': 0.8, 'idle': 97.9, 'iowait': 0.1, 'irq': 0.0, 'softirq'
diskio        [OK]    0.00061s key=disk_name [{'time_since_update': 2.1537704467773438, 'disk_name': 'loop0', 'read_count': 0, 'write_cou
docker        [OK]    0.01306s key=name [{'key': 'name', 'name': 'Glances', 'Id': '3f8aa298fc9fe6c8b781ae4d0608960820f69c6b60de248d70444e
folders       [OK]    0.00003s []
fs            [OK]    0.00151s key=mnt_point [{'device_name': '/dev/loop2', 'fs_type': 'btrfs', 'mnt_point': '/', 'size': 21474836480, 'u
gpu           [OK]    0.00002s []
help          [OK]    0.00000s None
ip            [OK]    0.00002s {}
irq           [OK]    0.00046s key=irq_line [{'irq_line': 'LOC', 'irq_rate': 4831, 'key': 'irq_line', 'time_since_update': 2.150282144546
load          [OK]    0.00003s {'min1': 0.09130859375, 'min5': 0.14453125, 'min15': 0.10888671875, 'cpucore': 12}
mem           [OK]    0.00014s {'total': 16489205760, 'available': 12611817472, 'percent': 23.5, 'used': 3877388288, 'free': 12611817472,
memswap       [OK]    0.00019s {'total': 0, 'used': 0, 'free': 0, 'percent': 0.0, 'sin': 0, 'sout': 0, 'time_since_update': 2.15030765533
network       [OK]    0.00093s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update': 2.026085615158081, 'cumul
now           [OK]    0.00001s 2023-03-04 15:22:03 UTC
percpu        [OK]    0.00006s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 78.0, 'user': 0.0, 'system': 1.0, 'idle': 
ports         [OK]    0.00014s []
processcount  [OK]    0.07115s {'total': 298, 'running': 1, 'sleeping': 157, 'thread': 564, 'pid_max': 0}
processlist   [OK]    0.00022s key=pid [{'name': 'glances', 'cpu_percent': 5.2, 'status': 'R', 'pid': 24068, 'num_threads': 5, 'cpu_times
psutilversion [OK]    0.00002s (5, 9, 4)
quicklook     [OK]    0.00041s {'cpu': 9.0, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 78.0, 'user': 0.0, 'system': 1.0, 
raid          [OK]    0.00002s {}
sensors       [OK]    0.00000s key=label [{'label': 'acpitz 1', 'unit': 'C', 'value': 27, 'warning': 119, 'critical': 119, 'type': 'tempe
smart         [OK]    0.00003s {}
system        [OK]    0.00000s {'os_name': 'Linux', 'hostname': UNRAID', 'platform': '64bit', 'linux_distro': 'Alpine Linux 3.17.
uptime        [OK]    0.00015s {'seconds': 73759}
wifi          [OK]    0.00002s []
Total time to update all stats: 0.09920s

**Additional context**
Unrelated to Glances but worth mentioning:
This causes to only one of them to be added to Home Assistant Glances integration as it decides it as duplicate sensor and one of them never get imported in HA with error:

From HA
ERROR (MainThread) [homeassistant.components.sensor] Platform glances does not generate unique IDs. ID 51941837daad45af6849c5e72b086478-Composite-temperature_core already exists - ignoring sensor.unraid_composite_temperature
ERROR (MainThread) [homeassistant.components.sensor] Platform glances does not generate unique IDs. ID 51941837daad45af6849c5e72b086478-Sensor 1-temperature_core already exists - ignoring sensor.unraid_disk_1_temperature

Regardesly of the HA part they should have different names by default.

**Comment by nicolargo** [comment]
Implementation done in the develop branch:  If a sensors has multiple identical features names (see #2280), then  Glances will add a suffix to the feature name.   

For example, if you have one sensor with two Composite features:

- the first one is named: Composite
- the second one will be renamed to: Composite_1

@ABEIDO can you test it on the develop branch ?

**Comment by ABEIDO** [comment]
I tested now.

And i got same sensor names:
![image](https://user-images.githubusercontent.com/78364151/222953722-25bf423c-50b3-4b4f-8cff-c8560c2b0808.png)

But im not sure i got to run it as 3.4.0_beta1 as logs and version says diffrent about which version im running. -V says 3.3.1.1 and logs says 3.4.0_beta1, i installed the docker with nicolargo/glances:dev

Glances -V
2023-03-05 01:52:30,894 -- INFO -- Start Glances 3.3.1.1
2023-03-05 01:52:30,894 -- INFO -- CPython 3.10.10 (/usr/bin/python3) and psutil 5.9.4 detected
Glances v3.3.1.1 with PsUtil v5.9.4
Log file: /tmp/glances-root.log

Log
2023-03-05 01:51:41,186 -- INFO -- Start Glances 3.4.0_beta1
2023-03-05 01:51:41,186 -- INFO -- CPython 3.10.10 (/usr/bin/python3) and psutil 5.9.4 detected
2023-03-05 01:51:41,190 -- INFO -- Read configuration file '/etc/glances.conf'
2023-03-05 01:51:41,206 -- INFO -- Start GlancesWebServer mode
2023-03-05 01:51:41,443 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2023-03-05 01:51:42,179 -- INFO -- Glances RESTful API Server started on http://0.0.0.0:61208/api/3/
2023-03-05 01:51:42,181 -- INFO -- Glances Web User Interface started on http://0.0.0.0:61208/

**Comment by nicolargo** [comment]
The image tales time to be available in docker hub. Try later.

Thanks !

**Comment by ABEIDO** [comment]
Ok will check back a bit later. Thanks for the quick response

**Comment by ABEIDO** [comment]
Nice it seems to work fine, thank you for taking your time.

![image](https://user-images.githubusercontent.com/78364151/222958860-39857a8b-b84f-470e-9678-d718e1b1a587.png)

**Comment by nicolargo** [comment]
Ok perfect !

Issue closed, will be release in Glances 3.4.
