### ISSUE TITLE
1.6.1 always try to create /etc/glances

### ISSUE THREAD

**Issue by codeb2cc** [nicolargo/glances#230]
Use pip to upgrade Glances to 1.6.1 and error occurs:

```
error: could not create '/etc/glances': Permission denied
```

I have python installed in my home directory and want glances installed locally too. Any workout except install from source?

**Comment by usharf** [comment]
@asergl installing from pip in a virtualenv will try to create that file under `/etc`... how should one install Glances in a virtualenv? 
Wouldn't be useful if it can also read it's configuration from a dotfile under user's $HOME...?
