### ISSUE TITLE
Support for email alerts/notifications

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#2326]
Original Issue: https://github.com/nicolargo/glances/issues/2317

**Comment by RazCrimson** [comment]
**Question to address**
1. Initial support through plain SMTP or some managed provider like SendGrid?
2. What format should the alerts mail be in? Is it user configurable? (let user give template and we fill values like AMPs)

**Ref**
SMTP: https://docs.python.org/3/library/smtplib.html
Sendgrid: https://github.com/sendgrid/sendgrid-python

**Comment by nicolargo** [comment]
Hi @RazCrimson 

the standard (in Glances point of view) way to do this kind of things is to make the Docker/Container plugin compliant with the **action** feature (more info here https://glances.readthedocs.io/en/latest/aoa/actions.html).

What do you think @RazCrimson  ?

Nicolas

**Comment by RazCrimson** [comment]
@nicolargo 
Actions, will indeed work. 

My idea when I created this issue was to provide a glances native way to send emails rather than user making their program for sending emails.

What are your thoughts on this?
Do you think its better to not bring in unnecessary complexity and let the user deal with this as it could be accomplished through actions? 🤔

**Comment by RazCrimson** [comment]
Makes sense.

Will close this and open another issue for that.
