### ISSUE TITLE
Parameters in the VIRT column

### ISSUE THREAD

**Issue by maravento** [nicolargo/glances#2343]
**Describe the bug**
What is the meaning of the "T" "G" "M" parameters in the VIRT column? 

![Captura de pantalla -2023-04-13 17-27-23](https://user-images.githubusercontent.com/14880802/231897198-9c533d70-eb6d-4b27-9354-c41964620ce6.png)

One of the lines associated with "chrome" and nvmen1p2 shows 1.10T in VIRT column

I'm assuming it is:

- M = Megabyte (MB) = 1,024KB = 1,048,576 bytes
- G = Gigabyte (GB) = 1,024 MB = 1,073,741,824 bytes
- T = Terabyte (TB) = 1,024 GB = 1,099,511,627,776 bytes

But this is impossible as I don't have 1TB capacity on my PC in nvme. 
And it's also impossible for a chrome tab to say 1.10TB. So it must mean something else, or this is a bug.

Ubuntu Mate 22.04.2 x64
Glances v3.2.4.2 with PsUtil v5.9.0
RAM 16GB
For OS and software: nvme PCIe 4 gen 500 GB
For Files: SSD Sata 500 GB

THK

**Comment by nicolargo** [comment]
Hi @maravento 

Units are corrects. 

"Virtual memory uses both hardware and software to enable a computer to compensate for physical memory shortages, temporarily transferring data from random access memory (RAM) to disk storage. "

"Virtual memory is usually much larger than physical memory, making it possible to run programs for which the total code plus data size is greater than the amount of RAM available."

Complete story here: https://www.quora.com/Can-virtual-memory-exceed-physical-memory

Nicolas

**Comment by Tyri0n** [comment]
I don't think this is working correctly, on mac at least

mac monterey 4GB ram:

<img width="181" height="798" alt="Image" src="https://github.com/user-attachments/assets/65abb60f-f22a-48b6-80ab-0b3110e2b75f" />

(a more believable) windows 11 pro 12GB ram:

<img width="129" height="768" alt="Image" src="https://github.com/user-attachments/assets/12dd1c36-c060-473c-bdde-30b8999b2a90" />

**Comment by maravento** [comment]
Hi,

Thank you for the clarification. I now understand that the VIRT column in Glances reflects the virtual address space size (VmSize) reported by the kernel — not the actual RAM in use — and that’s why it can show values in terabytes even on machines with far less physical memory or swap.

However, many users (myself included) initially interpret “VIRT” as “memory used” and get alarmed by such large numbers. The units and values are technically correct, but the label is confusing for users.

As a usability improvement, would you consider renaming the column (e.g. “VirtAddr” or “VmSize”) or hiding it by default? This would preserve the information for advanced users while reducing confusion for others.

Thank you for your great work on Glances.
