### ISSUE TITLE
Fix failing Alpine builds (break by the Cryptography lib used by Cassandra plugin)

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#2368]
Current alpine builds are failing when trying to compile `cryptography` for ARM architectures.

Some details mentioned in #1985.

**Comment by RazCrimson** [comment]
@nicolargo 

We should probably give the workaround mentioned here a try:
https://github.com/pyca/cryptography/issues/6673

**Comment by nicolargo** [comment]
@RazCrimson can not find any "~/.cargo/registry/index" inside the container. 

A possible workaround is to remove the cassandra-driver lib in the  optional-requirements.txt (this lib has cryptography as dep). Not sure that the Cassandra export is very used...

If you find another way to solve the issue...
