### ISSUE TITLE
better support for white / light terminal background

### ISSUE THREAD

**Issue by j-lakeman** [nicolargo/glances#2387]
**Is your feature request related to a problem? Please describe.**
glances should be executed with the `--theme-white` flag on white / light terminal backgrounds automatically.

**Describe the solution you'd like**
glances needs to autodetect the current terminal theme

**Describe alternatives you've considered**
tinkering with aliases, doesn't work if terminal theme changes while glances is running though

**Comment by nicolargo** [comment]
There is no standard way to detect the terminal background. There are a few ways that work on some terminals, but on most terminals it is impossible AFAIK.

**Comment by nicolargo** [comment]
Some implementation exist, but not work on standard Gnone terminal, terminator... 

https://github.com/rocky/shell-term-background

**Comment by j-lakeman** [comment]
What about adopting to the current OS theme? Would that be easier? That would solve my issue as well.

**Comment by nicolargo** [comment]
@j-lakeman do not find any Pythonific way to get the OS theme... Any idea and tips are welcome.

**Comment by j-lakeman** [comment]
https://github.com/albertosottile/darkdetect
Does that help?

**Comment by nicolargo** [comment]
Darkdetect only work for Gnome theme and not for the terminal background color :(

No simple and cross platform way to retrieve terminal background: https://stackoverflow.com/a/78629028/1919431
