### ISSUE TITLE
Glances CPU consumption of version 3.4.0_RC1 is higher (~ 30 %) than 3.3.1

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2390]
![3 3 4vs3 3 1](https://github.com/nicolargo/glances/assets/776747/8d14846d-6f91-41cf-9fa6-654a53ba8e42)

Profiling (flame) should be done to identify the issue.

**Comment by nicolargo** [comment]
Glances flame profiling for Glances 3.3.1:

![glances-3 3 1](https://github.com/nicolargo/glances/assets/776747/91daca4b-bb3a-4f27-9ac3-91469292ed0c)

Glances flame profiling for Glances 3.4.0-RC1:

![glances-3 4 0_RC1](https://github.com/nicolargo/glances/assets/776747/2aef7c3f-8e85-4547-b1c6-fc4211e4b3fd)

**Comment by nicolargo** [comment]
Seems to be related to the Docker Plugin:

![podmanhightcpu](https://github.com/nicolargo/glances/assets/776747/edb1b456-ccf7-422f-8f7b-40ecb1182e50)

**Comment by nicolargo** [comment]
@RazCrimson do you think that it is related to [the temporary patch](https://github.com/nicolargo/glances/blob/develop/glances/plugins/containers/glances_podman.py#L91-L94) to get Podman lib work ?

**Comment by RazCrimson** [comment]
@nicolargo 

Yea, it's probably that as the hacky generator is a bit greedy for the CPU.

Let me try to make a small fix on this.

**Comment by RazCrimson** [comment]
@nicolargo 
Could you give https://github.com/nicolargo/glances/tree/issue2390 a try?

It's again a bit of a hacky solution, but it should ease the CPU usage.

**Comment by nicolargo** [comment]
It looks better ! CPU consumption more or less the same than Glances 3.3.1 :)

**Comment by nicolargo** [comment]
You can merge to develop.
