### ISSUE TITLE
Docker plugins do not work as expected inside Glances docker images 

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2392]
Following PR https://github.com/nicolargo/glances/pull/2386 Glances Docker plugin do not work as expected.

How to reproduce ?

    make docker

Then: 

- [x] **make run-docker-alpine-dev**

no Docker plugin displayed 

In log (docker exec -it glances:local-alpine-dev cat /tmp/glances-root.log): 
ERROR -- Unable to import 'packaging' module (No module named 'packaging'). Glances cannot check for updates
ERROR -- containers (Podman) plugin - Can't get containers list (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.5.0/libpod/containers/json (GET operation failed))

==> Inside the container:

```
/venv/bin/python
Python 3.11.3 (main, May 10 2023, 12:26:31) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.11/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/venv/lib/python3.11/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/venv/lib/python3.11/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/venv/lib/python3.11/site-packages/docker/auth.py", line 7, in <module>
    from .utils import config
  File "/venv/lib/python3.11/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/venv/lib/python3.11/site-packages/docker/utils/utils.py", line 9, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

- [x] **make run-docker-alpine-full**

no Docker plugin displayed 

In log: 
ERROR -- Unable to import 'packaging' module (No module named 'packaging'). Glances cannot check for updates
ERROR -- containers (Podman) plugin - Can't get containers list (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.5.0/libpod/containers/json (GET operation failed))

- [x] **make run-docker-alpine-minimal**

no Docker plugin displayed 

In log: 
ERROR -- Unable to import 'packaging' module (No module named 'packaging'). Glances cannot check for updates
No error message concerning the containers... 

- [x] **make run-docker-ubuntu-dev**

Only Docker containers (no Podman) are displayed in the UI

In log: 
ERROR -- containers (Podman) plugin - Can't get containers list (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.5.0/libpod/containers/json (GET operation failed))

- [x] **make run-docker-ubuntu-full**

Only Docker containers (no Podman) are displayed in the UI

In log: 
ERROR -- containers (Podman) plugin - Can't get containers list (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.5.0/libpod/containers/json (GET operation failed))

- [x] **make run-docker-ubuntu-minimal**

Only Docker containers (no Podman) are displayed in the UI

In log: 
No error message

**Comment by nicolargo** [comment]
Patch done ff504b98 for the "Unable to import 'packaging' module (No module named 'packaging'). Glances cannot check for updates" message (not a big deal... and nothing related to the Docker plugin packaging error).

**Comment by nicolargo** [comment]
Another patch done https://github.com/nicolargo/glances/commit/c56f07673ec1a65545da5c90e4240e3b4ecfdb19 to force `packaging` lib in the Docker image but not a success...

**Comment by nicolargo** [comment]
Always teh same issue. `packaging` lib is not installed inside the Docker images, do not understand why because it is in:

- https://github.com/nicolargo/glances/blob/develop/docker-requirements.txt#L6
- https://github.com/nicolargo/glances/blob/develop/optional-requirements.txt#L18
- and here https://github.com/nicolargo/glances/blob/develop/requirements.txt#L3

@RazCrimson if you have any idea...

**Comment by RazCrimson** [comment]
The `packaging` issue should be fixed now

**Comment by RazCrimson** [comment]
@nicolargo 

There seems to be some issue with podman plugin not working with the minimal images. 

Some basic investigation of the issue led me to the conclusion that its due to some version mismatch of `urllib3`. 
But podman plugin seems to be working fine with full & dev images.

I'll try to see if there is a way to get it working with minimal images too.

**Comment by nicolargo** [comment]
After a quick test on my side, all images work to monitor Docker containers but none work for Podman (same error message: ERROR -- containers (Podman) plugin - Can't connect to Podman (http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v4.5.0/libpod/_ping (HEAD operation failed))).

**Comment by RazCrimson** [comment]
@nicolargo 
Did you forward the podman socket as a volume mount in docker?

It works for the dev & full images on my end 🤔 

Here is the compose that I use:
```
version: '3.8'

services:
  monitoring:
    image: glances:local-ubuntu-full
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

**Comment by nicolargo** [comment]
My bad, it is working for both dev and full images. Not for minimal.

**Comment by nicolargo** [comment]
Following error is displayed in the Glances minimal (Alpine) log file:

    2023-05-14 07:02:53,600 -- ERROR -- containers (Podman) plugin - Can't connect to Podman (HTTPConnection.request() got an unexpected keyword argument 'chunked')

Google  found https://github.com/docker/docker-py/issues/3113 on the Docker lib. I think that same kind of error occurs in the Podman lib... It has been fixed on the Docker lib with https://github.com/docker/docker-py/pull/3117.

On the Podman lib Github i just found https://github.com/containers/podman-py/issues/267 

So this bug should be corrected on the upstream.

===

Workaround 

On Alpine minimal image:

- docker-6.1.2.dist-info
- podman-4.5.0.dist-info
- requests-2.30.0.dist-info
- urllib3-**2.0.2**.dist-info

On Alpine dev image:

- docker-6.1.2.dist-info
- podman-4.5.0.dist-info
- requests-2.30.0.dist-info
- urllib3-**1.26.15**.dist-info

Trying to pin the urllib3 to version <2.0.0 in the docker-requirements.txt file "solve" the issue (waiting for the https://github.com/containers/podman-py/issues/267 patch).
