### ISSUE TITLE
The Snap package is not up to date

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2413]
The current Snap is not up to date:

- it use core20 (instead of core22)
- dep libs are old and incomplete

I have made some tests but all failed (Snap is definitively not my cup of tea):

- https://github.com/nicolargo/glances/commit/5f7e7132549f7368cddf604866ce1175b5d7673e
- https://github.com/nicolargo/glances/commit/c3c0cb6e6c8f79d8bd0b812765c19a2f38995524
- https://github.com/nicolargo/glances/commit/ef57106facef39d0d2bc9dcf9e188063f3b18380
- https://github.com/nicolargo/glances/commit/2da2cb714ee6382a7e3cdf0b3a627f0b6acf8488
- get back to old version: https://github.com/nicolargo/glances/commit/ed46b6a3e26c115e8ec17843d3ea04a9cd4356ec 

@brlin-tw Can you have a look ?

**Comment by brlin-tw** [comment]
Sure, I'll check it out.

**Comment by nicolargo** [comment]
Edge and beta version version align with Glances version 4 (beta)
