### ISSUE TITLE
Refactor the way stats are grabbed and compute

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2414]
For the moment all plugins implement its way to get/compute stats. The current proposal is to bring some commons functions in order to:

- define the stats and how to grab it in the fields_description variable
- define global methods to grab stats from external lib (like PsUtil)
- define global methods to compute stats from internal method

**Comment by nicolargo** [comment]
Tracking (it is no necessary/possible to refactor all plugins, make the best we can):

- [ ] alert  
- [ ] cloud       
- [ ] containers  
- [ ] cpu     
- [ ] folders  
- [ ] gpu
- [ ] irq   
- [ ] mem      
- [ ] network  
- [ ] percpu  
- [ ] ports         
- [ ] processlist  
- [ ] raid        
- [ ] sensors  
- [ ] system  
- [ ] wifi
- [ ] amps   
- [ ] connections  
- [ ] core        
- [ ] diskio  
- [ ] fs       
- [ ] help  
- [ ] ip           
- [ ] load  
- [ ] memswap  
- [ ] now     
- [ ] processcount  
- [ ] psutilversion  
- [ ] quicklook
- [ ] smart    
- [ ] uptime

**Comment by RazCrimson** [comment]
This approach make things simple, but we would be losing a lot of info that IDE/mypy could provide based on static code analysis.

For example, say we make a typo in function name in the `getter` for some stat, if we were using an IDE, it would give us the squiggle lines indicating that such a method does not exist.

Another case would be the typing, say some function has typing returns a int and we assign it to a field that is supposed to contain a string. An IDE will again give us the squiggles but when its all plain text we get nothing.

Assuming the above problems can be ignored, how do we handle passing parameter to such `getter` methods?

**Comment by nicolargo** [comment]
Yes... i know, more i go deeper in the implementation more i have doubt about the value added... I need to go deeper in the implementation.

For the parameters/arguments, something like: https://github.com/nicolargo/glances/blob/feature/issue2414/glances/plugins/cpu/model.py#L33

**Comment by nicolargo** [comment]
I give a try (done on cpu, percpu, mem, memswap and core and not convinced by the value added of the refactoring.

Some tips are interesting, for example the way rate are computed globally without any coding from the developer (for example if a stat return a cumulative stats and we want rate).

But for the rest i am agree with you that i do not improve the code quality.

I put my work on the **issue2414-dead-branch** branch.

The new **feature/issue2414** branch will implement the minimal refactoring for the plugins.

**Comment by nicolargo** [comment]
First think done: in the fields_description data model, if rate=True for a field  then do the following:

- add a field_gauge with the value of the field
- add a field_rate_per-sec with the computed rate (thanks to time_since_update)
- the field value becomes the delta between new and old value (same behavor in Glances 3.0)

**Comment by nicolargo** [comment]
Other refactoring to be done: most of the plugins return a list of disk instead of a pure dict (network, diskio, processlist...). 

It will be better if all plugin return a dict.

Keep in mind that this is an huge change on the API (api/4).

**Comment by nicolargo** [comment]
Try something on the DiskIO plugin, but something is wrong with the implementation of the wrapper (_manage_rate). Stats are going crazy...

**Comment by nicolargo** [comment]
Solved and merged into develop branch.

Only done for some simple plugins in order to manage the rate.
