### ISSUE TITLE
Action plugin should be refactor to take into account the new decision tree

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2416]
See: https://github.com/nicolargo/glances/blob/develop/glances/plugins/alert/__init__.py

**Comment by ariel-anieli** [comment]
@nicolargo, could you tell me what is expected? I'll work on this task.
I see how to refactor the function, but I don't know what (and where) is the new decision tree.

**Comment by ariel-anieli** [comment]
> Hi @ariel-anieli
> 
> infact this is already the new decision tree...
> 
> But the code need to be refactor.
> 
> :)

:slightly_smiling_face: Thanks. I'll work on it.
