### ISSUE TITLE
Docker image: psutil not found. Glances cannot start.

### ISSUE THREAD

**Issue by SDS1337** [nicolargo/glances#2418]
System:
Docker on Unraid 6.11.5

Ever since 3.4.0, container refuses to start. Gives this log before stopping.
```
psutil library not found. Glances cannot start.
```

No change in 3.4.0.1 or 3.4.0.2.

Running the Docker image with latest-full tag
Have tried ubuntu-full as well.

Configuration:
```
python -m glances --webserver --enable-process-extended --disable-irix --hide-kernel-threads --time=1
```

**Comment by RazCrimson** [comment]
@SDS1337 
Could you change the command to:
`/venv/bin/python -m glances --webserver --enable-process-extended --disable-irix --hide-kernel-threads --time=1` ?

**Comment by SDS1337** [comment]
@RazCrimson Thanks! That fixed it. 
I see what happened here.
