### ISSUE TITLE
Feature Request: Ability to hide Engine and Pod columns in Containers

### ISSUE THREAD

**Issue by blackthroat** [nicolargo/glances#2423]
Since all of my containers are Docker-based, the newly-added `Engine` and `Pod` columns do not provide any useful information in my environment. In result, those columns are taking up a lot of screen real estate when viewing the dashboard.

It would be great to have the ability to hide those columns by defining the visibility in a configuration file.

Referenced:
https://glances.readthedocs.io/en/latest/aoa/containers.html
https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf

**Comment by RazCrimson** [comment]
@blackthroat 
Do you have any opinion on what do you think should be the default behavior when there is just one engine?

Say you just have one engine running, then in that case how about hiding the Engine field in that case?

We could probably have something similar for pod field where its just visible when there are any actual pods running.

**Comment by blackthroat** [comment]
@RazCrimson Thanks for asking.  Perhaps the following default behaviors:

- If all Engines are Docker, don't show Engine or Pod fields
- If all Engines are Podman, don't show Engine or Pod fields
- If Engines are mixed, show Engine field

In mixed environments, I can definitely see the value in knowing the Engine so that I can quickly determine which tool or method I will use to manage it. I use docker compose and Portainer to manage my Docker environment, so the container ID isn't something I ever pay attention to but rather I reference the container name.  

I'm not familiar with Podman or managing the containers/pods, so I don't know how "useful" it is to have the Pod ID visible.
