### ISSUE TITLE
Unable to collect docker stats when using --export influxdb2

### ISSUE THREAD

**Issue by Mindstorm1750** [nicolargo/glances#2459]
**Describe the bug**
Unable to collect docker stats when using --export influxdb2

**To Reproduce**
Steps to reproduce the behaviour:
This is just the glances section but i can give the full compose if needed.
glances:
     image: nicolargo/glances:dev
     pid: host
     volumes:
       - /srv/dev-disk-by-uuid-47cba485-a5b1-4427-9f5c-a435bfef959b/dockerShare/Docker-Configs/glances/glances.conf:/etc/glances.conf
       - /var/run/docker.sock:/var/run/docker.sock:ro
     environment:
         GLANCES_OPT: "-C /etc/glances.conf --export influxdb2 -q"
     networks:
        gluetun_network:
          ipv4_address: 172.42.0.39

**Expected behaviour**
I have glances hooked up to infuxdb2 with grafana. Some information does work properly both in grafana and by querying influx directly, but any information regarding containers except their name is not there.
![image](https://github.com/nicolargo/glances/assets/78426901/34ada9c4-2e4d-43c0-9d84-33c8ca51e998)
![image](https://github.com/nicolargo/glances/assets/78426901/06904d8f-cab6-45df-99bf-30a83689f43b)

**Environment (please complete the following information)**
 - No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
 - Glances 4.0.0_beta01, CPython 3.11.3 (/venv/bin/python3) and psutil 5.9.5 detected
 - How do you install Glances (Pypi package, script, package manager, source): `Docker-compose`
 - Glances test (only available with Glances 3.1.7 or higher):

**Additional context**
EBUG -- containers (Docker) ID: ad1e99f8a1501066ac4d0155344404fdf0d8ae0730c7de10fac2c43426e43729 - Missing blockIO usage fields (None)
2023-06-16 16:44:24,097 -- DEBUG -- {}
2023-06-16 16:44:24,097 -- DEBUG -- containers (Docker) ID: ad1e99f8a1501066ac4d0155344404fdf0d8ae0730c7de10fac2c43426e43729 - Can't grab CPU stats ('cpu_stats')
2023-06-16 16:44:24,097 -- DEBUG -- {}
2023-06-16 16:44:24,097 -- DEBUG -- containers (Docker) ID: ad1e99f8a1501066ac4d0155344404fdf0d8ae0730c7de10fac2c43426e43729 - Missing MEM usage fields (None)
2023-06-16 16:44:24,097 -- DEBUG -- {}
2023-06-16 16:44:24,098 -- DEBUG -- containers (Docker) ID: ad1e99f8a1501066ac4d0155344404fdf0d8ae0730c7de10fac2c43426e43729 - Missing Network usage fields (None)
2023-06-16 16:44:24,098 -- DEBUG -- {}
2023-06-16 16:44:24,110 -- DEBUG -- containers (Docker) ID: 5fd0346c398834d827bab2a8b5ccd601ca9f7ea4eea704105d8dcf6df73176ca - Missing blockIO usage fields (None)

The debug log shows this alot, i can do docker stats and it shows the stats properly so i dont know whats wrong.
Any help would be appreciated. 

You can also [pastebin](https://pastebin.com/):
https://pastebin.com/yj4nFL0K -d log
https://pastebin.com/V44sCyue glances.conf

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by RazCrimson** [comment]
@Mindstorm1750 
It seems that container plugin is not working and is failing to fetch stats.

Are you able to see the docker stats when you run glances in standalone mode?

**Comment by Mindstorm1750** [comment]
![image](https://github.com/nicolargo/glances/assets/78426901/11c2051c-d670-44b6-bcb2-52cbfcbd59ff)
Yes, i ran:
 docker run -e TZ="${TZ}" -v `pwd`/glances.conf:/etc/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro --pid host -e GLANCES_OPT="-C /etc/glances.conf" -it nicolargo/glances:dev

and it showed the stats successfully.

**Comment by RazCrimson** [comment]
@Mindstorm1750 
Thanks for the fast reply.

Could you also try the glances in export mode once with all the other docker options remaining the same?

The `dev` tag gets updated frequently, so just want to confirm if the issue is still present.

**Comment by Mindstorm1750** [comment]
Ran my original docker stack and deleted and repulled dev 
![image](https://github.com/nicolargo/glances/assets/78426901/bff8d6e0-88ac-4cfe-8484-22f48061fdad)
influx still shows nothing being logged
![image](https://github.com/nicolargo/glances/assets/78426901/096693e8-fc7a-49b9-9cb4-b7c42105252d)
ran with debug as well to get this ^^

**Comment by JulienSambre** [comment]
Hi!

I run the dockerized version of glances and I have the same issue : 
- nicolargo/glances:3.3.1.1-full => export influxdb2 docker ok
- nicolargo/glances:3.4.0.3-full => export influxdb2 docker ko

The system metrics (CPU, RAM, etc) works perfectly in both versions, only the containers info are missing.

I run this container in a classical docker engine (version 24.0.2).

**Comment by jdespraz** [comment]
Good news, I do not experience this issue anymore with the latest version of glances:
tag: nicolargo/glances:latest-full from 7 days ago
DIGEST:sha256:01fcafb39e64230e79f82422813332f62729f71cab476056374fa2caea403666

**Comment by ryanovas** [comment]
I was having this issue running as a daemon on my machine. I looked at the queries in the grafana charts and several have incorrect values. I suspect the grafana JSON provided is out of date to the current field values. You can open your influxdb browser and check for up to date values and adjust your grafana dashboard as desired.

**Comment by ryanovas** [comment]
@seal-82 it does still work, it's been very useful for me. My gist has some values that are specific to my setup though, you probably need to read through and swap to match your environment. It's been a few months since I did this though so the details are hazy to me now. Can't remember which ones exactly.

Can you share a few details of what you've done so far and what you're seeing now? I can try to help as best I can.

**Comment by seal-82** [comment]
@ryanovas: That sounds great. Let me explain...

I run Glances (v10.4.2), InfluxDB2 (v2.7.6) and Glances (latest-full, v3.4.0.5) in Docker (stack with 3 containers).

Glances >>> working, can be reached glances.mydomain.com
InfluxDB2 >>> working, can be reached influx.mydomain.com
Glances export to InfluxDB3 bucket (glances) >>> working (I can see Glances' data with Influx web interface)
Grafana access to InfluxDB2 bucket (glances) >>> working (when testing data source in Grafane I get the following message: "datasource is working. 4 buckets found")

When I create a new dashboard using your json (https://gist.github.com/ryanovas/5720fe4117e8d8e41003f8a65e1faa52) or the original json (https://github.com/nicolargo/glances/blob/master/conf/glances-grafana-flux.json), it shows empty values - see screenshot:

![grafik](https://github.com/nicolargo/glances/assets/104196091/4554bad0-641e-42c9-bd46-e1fb07142c2a)

The host dropdown menue is empty. If I type the hostname of the host, it at least shows some data:

![grafik](https://github.com/nicolargo/glances/assets/104196091/1937a3e1-ad18-4450-af35-8c525bce11c3)

Seems like the dashboard cannot select the host correctly. 

Thanks for your help ;-)

I really love Glances, would be a pitty if I had to switch to a different monitoring system...

**Comment by seal-82** [comment]
see: https://github.com/nicolargo/glances/discussions/2543#discussioncomment-9404017

**Comment by ryanovas** [comment]
@seal-82 glad to hear you've made progress. Looking at my JSON now I think what you need to do is get your host into the hosts drop-down (I'm sorry I don't remember how now, would need to really dig) and then looks like there's several places in my JSON where my host name got hard coded. You'll need to swap those values to whatever your host name is. Mine is called "mobile lab" (it's a mini server I carry with me while I travel). I believe pretty much everything in this dashboard ultimately derives from the host name. 

I also had trouble getting glances to connect to my docker, you gotta make sure you're using the main docker.sock, not the one from Docker desktop if you're using that. 

Lmk if that's enough to point you in the right direction, if not I can try to find time this week to dig a little deeper but can't promise it'll be quick.
