### ISSUE TITLE
Package is also available via Nix

### ISSUE THREAD

**Issue by expelledboy** [nicolargo/glances#2463]
```sh
nix run nixpkgs#glances

# or

nix-shell -p glances -c glances
```

**Comment by nicolargo** [comment]
Message ID: ***@***.***>ThThis is not a
Glances issue. Please open a request on the Nix packet manager Github:
https://github.com/NixOS/nixpkgs

**Comment by expelledboy** [comment]
Just letting you know its packaged in nixpkgs. Its not an issue, its info for your README

**Comment by RazCrimson** [comment]
@nicolargo 
Are we planning to add installation info for *nix distributions into our Readme?

**Comment by nicolargo** [comment]
https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=glances
