### ISSUE TITLE
Lost data on reboot

### ISSUE THREAD

**Issue by ljchuello** [nicolargo/glances#2465]
I'm not sure if it's a bug or not; But when I restart the computer and start again using the command glances -w I don't have the history or network log.

Is there a way to keep the log after a reboot or is losing it part of the Glances feature?

Thank you.

**Comment by nicolargo** [comment]
Nope for the moment there is no "storage" from one Glances session to another.

**Comment by ljchuello** [comment]
I understand, it was more of a request I think. I don't see it as a mistake. I will close!.
