### ISSUE TITLE
Glances showing snap volume in FS

### ISSUE THREAD

**Issue by helsan74** [nicolargo/glances#2513]
in glances.conf
under FS

```
Define the list of file system to hide (comma-separated regexp)
hide=/boot.*,/snap.*,/dev/loop*

```
But when glances is launched
![image](https://github.com/nicolargo/glances/assets/23530303/4d6a913f-baf3-4753-bcfd-94d0eb7941dd)

Running under Ubuntu 22.04 64bit / Linux 5.15.0-78-generic
Galnces version Glances v3.4.0.3 with PsUtil v5.9.5

**Comment by nicolargo** [comment]
Hi @helsan74

As sais in the documention (https://glances.readthedocs.io/en/latest/aoa/fs.html), you should use a regular e, pression.

Ex:

hide=/boot.*,/snap.*

**Comment by helsan74** [comment]
Update: 
I found the issue... the glances.conf file in /etc/glances/ had a typo in the name. (glances with no 's')
glances was using the default config since no file glances.conf was found.
Sorry for the trouble. Thanks for taking the time to answer
