### ISSUE TITLE
MongoDB and CouchDB documentation flipped

### ISSUE THREAD

**Issue by retrodaredevil** [nicolargo/glances#2565]
Was reading the documentation and wanted to point out that [CouchDB](https://glances.readthedocs.io/en/latest/gw/couchdb.html) and [MongoDB](https://glances.readthedocs.io/en/latest/gw/mongodb.html) seem to have their content flip flopped.

**Comment by nicolargo** [comment]
Swap done. Thanks @retrodaredevil .

CouchDB seems broken. The Python CouchDB lib is no longer updated: https://github.com/djc/couchdb-python/

I open another issue to try to find an alternative (https://github.com/cloudant/python-cloudant ? )
