### ISSUE TITLE
Link address in Wiki page is wrong

### ISSUE THREAD

**Issue by monochromec** [nicolargo/glances#2575]
A link in a page of  the repo wiki points to a non-existent URL.

**To Reproduce**
Click on "existing plugins" and get a 404.

**Expected behavior**
The correct web page should open (https://glances.readthedocs.io/en/latest/aoa ).

**Additional context**

Replace incorrect URL "http://glances.readthedocs.io/en/stable/aoa/index.html" with correct one: "https://glances.readthedocs.io/en/latest/aoa"

**Comment by shubhalgupta** [comment]
@monochromec please assign me this issue!

**Comment by monochromec** [comment]
@shubhalgupta Not possible with current privileges on the repo.

**Comment by nicolargo** [comment]
Done !

Thanks for the PR @monochromec
