### ISSUE TITLE
[fs]not get device_name and percent in action_repeat

### ISSUE THREAD

**Issue by hugebig** [nicolargo/glances#2597]
**Describe the bug**
fs Actions not get device_name and percent on careful_action_repeat .

**To Reproduce**

1. modify swarm_glances.conf

```
[fs]
hide=/boot.*,/snap.*,.*/tableCheck/.*
careful_action_repeat = echo {{device_name}} {{percent}} > /tmp/fs.alert
```

2. glances -w -C swarm_glances.conf

3. cat /tmp/fs.alert
`{{device_name}} {{percent}}`

**Expected behavior**

- cat /tmp/fs.alert
`/dev/vda1 55.3`

**Screenshots**
![image](https://github.com/nicolargo/glances/assets/20080970/7508e06b-f24e-49ae-8d99-f20da2202a8d)

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): 
`Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
`
 - Glances & psutil versions: **Glances v3.4.0.3 with PsUtil v5.9.6**
 - How do you install Glances (Pypi package, script, package manager, source): **conda，Pypi package**
 - Glances test (only available with Glances 3.1.7 or higher):

 ```
 fs            [OK]    0.00058s key=mnt_point
[{'device_name': '/dev/vda1',
  'free': 4502933504,
  'fs_type': 'ext4',
  'key': 'mnt_point',
  'mnt_point': '/',
  'percent': 55.3,
  'size': 10534256640,
  'used': 5563678720}, ...]
 ```

**Additional context**

- /api/3/fs

`[{"device_name":"\/dev\/vda1","fs_type":"ext4","mnt_point":"\/","size":10534256640,"used":5563678720,"free":4502933504,"percent":55.3,"key":"mnt_point"}]`

**Comment by hugebig** [comment]
Hi，result of above configuration：

`tail -f glances.log`
![image](https://github.com/nicolargo/glances/assets/20080970/acc3b736-3be4-41c6-805a-a799e03a0cb7)

`ls -lt`
28 Nov  2 09:36 fs.alert

`cat fs.alert`
{{device_name}} {{percent}}

I will try on other serveres.

**Comment by nicolargo** [comment]
@hugebig i think that i understand. You need the [Chevron Python lib](https://pypi.org/project/chevron/) in order to put "{{ mustache }}" inside your actions. How do you install Glances on your system ? 

Via Pypi ? Can you check that the lib is installed:

```
$ python
>>> import chevron
chevron.render('Hello, {{ mustache }}!', {'mustache': 'World'})
```

**Comment by hugebig** [comment]
this is exactly the problem ！
**pip list**
```
Package            Version
------------------ ---------
bottle             0.12.25
certifi            2022.12.7
charset-normalizer 3.3.1
defusedxml         0.7.1
dnspython          2.3.0
Glances            3.4.0.3
idna               3.4
packaging          23.2
pip                22.3.1
psutil             5.9.6
pymongo            4.5.0
requests           2.31.0
setuptools         65.6.3
ujson              5.7.0
urllib3            2.0.7
wheel              0.38.4
```
after `pip install chevron` [🥂 ] 

2023-11-02 16:31:28,068 -- INFO -- Action triggered for fs_/ (careful): echo /dev/vda1 55.4 > /tmp/fs.alert

finally the problem may：

- when  `pip install glances[web] `，**chevron** not automatic installed、

Thanks a lot !

**Comment by hugebig** [comment]
pip install chevron
Thanks a lot !
