### ISSUE TITLE
Plugin - Hello World

### ISSUE THREAD

**Issue by kkm** [nicolargo/glances#2611]
Is https://github.com/nicolargo/glances/wiki/How-to-create-a-new-plugin-%3F_ outdated?

I tried but it didn't work so well, can someone give me an example hello world plugin?

**Comment by nicolargo** [comment]
Yes, it is outdated, i currently works on Glances 4.x and it will change some file concerning plugin management. I will update the documentation and make a simple "Hello worl" plugin before the release.

**Comment by nicolargo** [comment]
Documentation updated but need to be improved.
