### ISSUE TITLE
Please add a startup flag to select an alternate web server static file path

### ISSUE THREAD

**Issue by greenmoss** [nicolargo/glances#2612]
**Is your feature request related to a problem? Please describe.**
As mentioned in #2021, the glance package in Ubuntu/Debian requires extra manual steps in order to work around the blank startup web page. However the workaround as it currently stands will not survive a glance package reinstall or upgrade.

**Describe the solution you'd like**
Add a flag `--static-web-file-path`, which directs glance to look in a different location for the required static files. If we start up with `-w`, and glance does *NOT* find these static files, suggest/warn the user that the web page will be blank, and they should consider downloading the files themselves, while specifying the path using `--static-web-file-path`.

**Describe alternatives you've considered**
Does Debian/Ubuntu have other recommendations for these types of files? I don't know much about apt packaging best practices, or why these files were removed from the package. If there's a way to put them back that follows packaging guidelines, that would of course be the simplest, and then this flag would not be needed.

Maybe the package maintainers require something like a "glance-static-js" package instead? If so, one would still need this flag to point to the hypothetical additional package directory.

**Additional context**
The workaround as currently documented (`sudo cp -r glances-${GLANCES_VERSION}/glances/outputs/static/public/ /usr/lib/python3/dist-packages/glances/outputs/static/`) copies files directly into the glance package directory. The next time Debian/Ubuntu updates the glance package, it will remove the local changes, and glance web server will revert to a blank web page.

Creating this extra flag allows the user to save the static files somewhere safe, for instance `/var/local/glance-static`.

**Comment by nicolargo** [comment]
https://github.com/nicolargo/glances/blob/develop/glances/outputs/glances_restful_api.py#L91C1-L92C107

**Comment by nicolargo** [comment]
Done in the develop branch.

New key in the configuration file:

```
[outputs]
...
# Set root path for WebUI statics files
# Why ? On Debian system, WebUI statics files are not provided.
# You can download it in a specific folder
# thanks to https://github.com/nicolargo/glances/issues/2021
# then configure this folder with the webui_root_path key
# Default is folder where glances_restfull_api.py is hosted
webui_root_path=/path/to/my/static/files/
```
