### ISSUE TITLE
Getting field information (description, unit) from the API

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2630]
### Discussed in https://github.com/nicolargo/glances/discussions/2629

<div type='discussions-op-text'>

<sup>Originally posted by **am-dave** December 21, 2023</sup>
Hello,
I'm thinking about developing an application, say A, that queries glances via [REST API](https://github.com/nicolargo/glances/blob/support/glancesv3/docs/api.rst) periodically. IIUC, it is impossible to get the unit of measurement (byte, Celsius degrees, etc.) of retrieved data at runtime, however. Thus, units should be hardcoded in A and I would like to avoid this. Is it possible to find a better solution?
Thanks in advance.</div>

===

Glances version 4 will implement a fields_description variable (for each plugin), extract from CPU plugin:

```
fields_description = {
    'total': {'description': 'Sum of all CPU percentages (except idle).', 'unit': 'percent'},
    'system': {
        'description': 'percent time spent in kernel space. System CPU time is the \
time spent running code in the Operating System kernel.',
        'unit': 'percent',
    },
    'user': {
        'description': 'CPU percent time spent in user space. \
User CPU time is the time spent on the processor running your program\'s code (or code in libraries).',
        'unit': 'percent',
    },
    'iowait': {
        'description': '*(Linux)*: percent time spent by the CPU waiting for I/O \
operations to complete.',
        'unit': 'percent',
    }
   ...
``` 

An entry point in the API will be added to retrieve this information.

Proposal:

- http://0.0.0.0:61208/api/4/cpu/total/description will return: "Sum of all CPU percentages (except idle)."
- http://0.0.0.0:61208/api/4/cpu/total/unit will return: "percent"

**Comment by nicolargo** [comment]
Done in the develop branch.

A specific work should be done on the Alarm plugin in order to change the data model from a list of list to a list of dict => https://github.com/nicolargo/glances/issues/2633

**Comment by am-dave** [comment]
> Done in the develop branch.
> 
> A specific work should be done on the Alarm plugin in order to change the data model from a list of list to a list of dict => #2633

Thank you!

**Comment by am-dave** [comment]
> Done in the develop branch.
> 
> A specific work should be done on the Alarm plugin in order to change the data model from a list of list to a list of dict => #2633

FYI
We have started to use Glances in tandem with our IIoT ecosystem [ToloMEO](https://tolomeo.io/2024/03/30/connecting-grafana-to-tolomeo/).
