### ISSUE TITLE
Showing the full arguments on the command column of the TASKS Section of the Web UI.

### ISSUE THREAD

**Issue by janusn** [nicolargo/glances#2634]
**Is your feature request related to a problem? Please describe.**

Not really.

**Describe the solution you'd like**

On the WebUI, please show the full arguments on the Command column of the TASKS section similar to the Command column of the Containers section.

Showing multiple processes of "python3" without the arguments is not really helpful when they are actually unrelated processes.

**Describe alternatives you've considered**

Cannot think of one.

**Additional context**

None.

**Comment by nicolargo** [comment]
Implemented on the develop branch:
- default behavior (option -w): display short command line (no argument)
- new behavior (option: -w --process-long-name); display command line with arguments  
-  New short key: '**S**' to switch from short to long command line

Will be release in Glances 4.0.0.
