### ISSUE TITLE
Docker memory usage is incorrect

### ISSUE THREAD

**Issue by Feriman22** [nicolargo/glances#2637]
**Describe the bug**
Docker memory usage is incorrect, while comparing the glances and the `docker stats` command at the same time.

**To Reproduce**
1. Open Glances webUI
2. Run the `docker stats` command
3. Compare the memory usage of any docker container

**Expected behavior**
It should be the same or very similar.

**Screenshots**
![glances](https://github.com/nicolargo/glances/assets/22872515/2cf5753e-644f-4be5-8a40-d2516d492cd6)

**Environement (please complete the following information)**
 - Operating System: Debian 12, Docker image from nicolargo/glances (latest)
 - Glances & psutil versions: v3.4.0.3
 - How do you install Glances: Docker

**Comment by nicolargo** [comment]
Glances displays the stats returned by the https://github.com/docker/docker-py library.

![image](https://github.com/nicolargo/glances/assets/776747/c3f8ce0d-b6a0-45ea-85d9-4fbb0f1e1165)

As you can see in this screenshot, the Glances value (1.55 MB is ~ to the one given by Docker-Py 1.6 MB). Do not know what is the value returned by "docker stats"...

**Comment by nicolargo** [comment]
I just open an issue on the upper lib: https://github.com/docker/docker-py/issues/3210

**Comment by Feriman22** [comment]
Thank you!

**Comment by nicolargo** [comment]
Have to algorithm inside Glances because Docker-Py return the stats "as it".

So the following computation will be added under the weeod: usage - inactive_file.

**Comment by nicolargo** [comment]
Branch 2637-docker-memory-usage-is-incorrect to be tested and merged into develop.
