### ISSUE TITLE
Unable to Autostart glances using the systemd instructions [SOLVED]

### ISSUE THREAD

**Issue by ddetton** [nicolargo/glances#2673]
[SOLVED]  See first comment below.

I followed the instructions from here to autostart glances using systemd.
https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

=====================================
After systemctl enable and start, I run systemctl status glances.service, I get this:
![image](https://github.com/nicolargo/glances/assets/3335359/53da1768-ffdb-4b89-954a-80b1365d7b6d)

====================================
My glances.service file looks like this:
![image](https://github.com/nicolargo/glances/assets/3335359/6dcdfdb1-ed84-49b1-9119-f3fd80018dc5)

===================================
My Operating System:
![image](https://github.com/nicolargo/glances/assets/3335359/c167d7fe-ac39-4776-8427-67730453563f)

===================================
My Glances & psutil versions
![image](https://github.com/nicolargo/glances/assets/3335359/52224498-7284-49fb-b4c5-05a1e098eb9c)

==================================
My Install method:
```
pip install --user 'glances[all]'
```
It was installed in $HOME/.local/bin.  I added this to my path in my .zshrc script.  I can run 'glances -w' just fine from the terminal and it responds to the REST API calls.  I just can not get it to autostart with systemd.  I am open to other autostart methods if systemd is not going to work for me.  

Thanks!

**Comment by ddetton** [comment]
This stackoverflow article solved this issue for me.  

https://stackoverflow.com/questions/35641414/python-import-of-local-module-failing-when-run-as-systemd-systemctl-service

I needed to tell systemd which user to run as.  I also put in WorkingDirectory but don't know if that was required or not.

**Comment by nicolargo** [comment]
Note added to https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

**Comment by Vigrond** [comment]
for Fedora with SELinux enabled, this needs a couple extra steps:

*/etc/systemd/system/glances.service
`[Unit]
Description=Glances
After=network.target

[Service]
User=user
ExecStart=/home/user/.local/bin/glances -w
Restart=always
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
`

then

`sudo systemctl enable glances.service
sudo systemctl start glances.service`

then by virtue of `journalctl | grep glances`, SELinux tells you to  create a local policy:

`
ausearch -c '(glances)' --raw | audit2allow -M my-glances
semodule -X 300 -i my-glances.pp
`

finally refresh the security context:
`/sbin/restorecon -v /home/user/.local/bin/glances`

and the service is now working.
