### ISSUE TITLE
ubuntu-latest-full with docker stat support

### ISSUE THREAD

**Issue by itsgiff** [nicolargo/glances#2674]
Is it possible for the ubuntu-latest-full image to support docker stats? 

I am running Ollama in a container and would really like to be able to see both the Docker container stats and the GPU stats simultaneously.

**Comment by RazCrimson** [comment]
You should already be able to do it?

Just make sure all prerequisites mentioned here are met: https://docs.docker.com/config/containers/resource_constraints/#gpu

Use a docker run command as follows:
```
docker run --rm -e TZ="${TZ}" -v /var/run/docker.sock:/var/run/docker.sock:ro -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro --gpus all --pid host --network host -it nicolargo/glances:ubuntu-latest-full
```
