### ISSUE TITLE
Release 3.4.0.2's Alpine docker base out of date; Release 3.4.0.2 on newer Alpine 3.19.1 and 3.18.6 tags

### ISSUE THREAD

**Issue by bignay2000** [nicolargo/glances#2680]
Current release in hub.docker.com is 9 months old and on the 3.18.0 Alpine docker image.  
This is missing updates from Alpine Linux - better to provide new tags in docker hub than have end users try to update the Alpine container themselves.

**Describe the solution you'd like**
Add more tags to hub.docker.com for users to select their Alpine release.

1. Update 3.4.0.2  (same image as 3.4.0.2-alpine3.19.1)
2. Add 3.4.0.2-alpine  (same image as 3.4.0.2-alpine3.19.1)
3. Add 3.4.0.2-alpine3.19.1
4. Add 3.4.0.2-alpine3.18.6
5. Add 3.4.0.2-alpine3.18.0 (same as the current 3.4.0.2 image)

**Describe alternatives you've considered**
I can update the Alpine Linux container by building and adding the apk update and apk upgrade --available commands, but prefer this to come from the parent image.

**Additional context**
Avoid using "latest" tag as this is hard to track for updating docker containers.

**Comment by RazCrimson** [comment]
Closing as the current `latest` images are based on 3.19.1
