### ISSUE TITLE
Custom system header information

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2695]
### Discussed in https://github.com/nicolargo/glances/discussions/2693

<div type='discussions-op-text'>

<sup>Originally posted by **eBarazi** March  7, 2024</sup>
Hi,
Is there a way I can change header information (like adding correct server name and OS information) 
![glances](https://github.com/nicolargo/glances/assets/57766467/f6ab5dbc-4fa1-444f-8feb-286fafb2979b)
</div>

**Comment by nicolargo** [comment]
@eBarazi in the develop branch it is now possible to configure the system information message:

```
[system]
# This plugin display the first line in the Glances UI with:
# Hostname / Operating system name / Architecture information
# Set to true to disable a plugin
disable=False
# Default refresh rate is 60 seconds
#refresh=60
# System information to display (a string where {key} will be replaced by the value)
# Available information are: hostname, os_name, os_version, os_arch, linux_distro, platform
system_info_msg=({linux_distro} {platform} / {os_name} {os_version})
```

**Comment by eBarazi** [comment]
Amazing, Thank you so much 👍

**Comment by nicolargo** [comment]
Also done in the WebUI.
