### ISSUE TITLE
Missing GitHub release for 3.4.0.4

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#2704]
Can see a tag and a PyPI package for 3.4.0.4, but am not seeing a GitHub release. Is that just an oversight or should we hold off packaging in other places for a bit?

**Comment by nicolargo** [comment]
3.4.0.4 is broken...

A build for the version 3.4.0.5 will be release in Pypi in few hours...

**Comment by jakirkham** [comment]
Thanks Nicolas! How is 3.4.0.5 looking?
