### ISSUE TITLE
GPU Stats disappear in 3.4.0.4

### ISSUE THREAD

**Issue by cobalt027** [nicolargo/glances#2705]
After updating to 3.4.0.4 the GPU stats disappeared. Reverting back to 3.4.0.3 brought the GPU stats back

Unraid 6.12.8
GPU: Nvidia Quadro P620
Glances as a docker container. Image nicolargo/glances:ubuntu-latest-full (as of 3/23/2024 this points to 3.4.0.4)
Variables:
Extra Params: --gpus all --pid=host
GLANCES_OPT: -w
NVIDIA_VISIBLE_DEVICES: GPU-my-id

Screenshot from 3.4.0.3
![image](https://github.com/nicolargo/glances/assets/164455/fabfa1ad-0029-4e9e-860b-247b34b492ca)

Screenshot from -latest-
![image](https://github.com/nicolargo/glances/assets/164455/9ce09a20-180c-467f-81c5-45c3c7ab0df1)

**Comment by nicolargo** [comment]
Exact, there is an error in the merge of the version.

A new 3.4.0.5 build is on-going.

**Comment by cobalt027** [comment]
> Exact, there is an error in the merge of the version.
> 
> A new 3.4.0.5 build is on-going.

Thank you for the reply! I'll wait patiently.

**Comment by cobalt027** [comment]
3.4.0.5 fixed the GPU stats. They are back now. Thank you!
