### ISSUE TITLE
 Glances installation not work on windows

### ISSUE THREAD

**Issue by gilvaju** [nicolargo/glances#2708]
**Describe the bug**
 Glances installation not work 

**To Reproduce**
1. Install python 3.12
2. Install glances [all]
3. After install process, glances show in pip list but is not possible run Glances from powershell, the error is: "Cmd dont find"

**Expected behavior**
Open Glances via terminal.

**Environement (please complete the following information)**
 - Windows 11
 - .
 - pip install glances[all]

 ```
 To be completed with result of: glances --issue
 ```
 
 
![image](https://github.com/nicolargo/glances/assets/677039/ae4f8201-00de-421d-aea6-d3ed10d9fb0c)

**Comment by nicolargo** [comment]
Hi @gilvaju 

Do not know where Glances is installed when --user option is not used for the pip command line...

Try to install Glances with:

    pip install --user glances[all]

**Comment by gilvaju** [comment]
Hi, dont work:

![image](https://github.com/nicolargo/glances/assets/677039/9c668b59-a957-4f34-b3bc-e90f5da8be78)

**Comment by Tomasz-Marciniak** [comment]
Not Glances but glances. Did you add the directory with the app to PATH variable?

**Comment by gilvaju** [comment]
> C:\Users[your-user-name]\AppData\Roaming\Python\Python312\Scripts

Hi, worked, thank you so much, but the folder link is other:

C:\Users\Gilvaju\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts

But now Glances doesnt work:

![image](https://github.com/nicolargo/glances/assets/677039/830b8fb6-9e3d-4ed6-86eb-760fa19f4199)

**Comment by nicolargo** [comment]
Duplicated: related to https://github.com/nicolargo/glances/issues/2689#issuecomment-2050009675
