### ISSUE TITLE
Union filesystem (mergerfs) read as individual drives

### ISSUE THREAD

**Issue by deafmute1** [nicolargo/glances#2717]
**Describe the bug**
Union file system (mergerfs) shows up _only_ as its constituent drives, and there is no statistic for the overall filesystem.

**To Reproduce**
1. Have a union file system, it doesn't show up.
 To be clearer, I have glances in docker, so in order to get fs data I did:
```
volumes:
    /:/hostroot:ro
```

**Expected behavior**
I would expect to see at least the union system, although seeing both union and constituent drives also makes sense.

**Screenshots**
<img width="270" alt="Screenshot 2024-04-05 at 14 14 44" src="https://github.com/nicolargo/glances/assets/32427188/adde378d-67c9-4c58-9595-e660f40b0679">

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Debian 11/OMV 6/ Linux 6.1.0-0.deb11.17-amd64
 - Glances & psutil versions: docker:latest (ID 	sha256:4bb4cc3dd9cd6c8e788655505a3239cb477fa5acb6185c0059a82e3be3c08033
 - How do you install Glances (Pypi package, script, package manager, source): docker
 - Glances test (only available with Glances 3.1.7 or higher):

 ```
 To be completed with result of: glances --issue
 ```

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Hi  @deafmute1 

Did you try to add MergeFS to the Glances configuration file ?

```
[fs]
# Allow additional file system types (comma-separated FS type)
allow=mergefs
```

Not sure it works but you can give it a try...

**Comment by Orski174** [comment]
> Did you try to add MergeFS to the Glances configuration file ?

It does indeed work!!

Thanks a lot for this amazing project!!
