### ISSUE TITLE
Windows Install Issues

### ISSUE THREAD

**Issue by soulvoid86** [nicolargo/glances#2728]
**Describe the bug**
Unsure if this is a bug or a system issue.

I'm receiving the below DLL Load Error on a fresh install of Glances/Python. I've reinstalled v3.4, 3.10.1 and 3.12.3 of Python, following the install steps exactly as described. I have 4 other systems running Glances perfectly fine, all in the same windows environments as this VM. Not sure why I'm hitting the error below. I've uninstalled and reinstalled Python countless time, clearing all directories for Python including Program Files and Local AppData. I've installed all dependencies to their exact version manually based on what the other systems have installed, but I still hit this error. Unsure if it's this VM or a bug.

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\glances.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\glances\__init__.py", line 35, in <module>
    from glances.compat import PY3
  File "C:\Program Files\Python310\lib\site-packages\glances\compat.py", line 25, in <module>
    from glances.logger import logger
  File "C:\Program Files\Python310\lib\site-packages\glances\logger.py", line 20, in <module>
    from glances.globals import safe_makedirs
  File "C:\Program Files\Python310\lib\site-packages\glances\globals.py", line 16, in <module>
    import ujson
ImportError: DLL load failed while importing ujson: The specified module could not be found.

**To Reproduce**
Simply following the basic Windows install.
Install Python v3.10.1 for all users>pip install glances

**Expected behavior**
Glances to install

**Screenshots**

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Windows Server 2019 Standard
 - Glances & psutil versions: Unable to run command, same error occurs.
 - How do you install Glances (Pypi package, script, package manager, source): CMD>pip install glances

Unable to provide any of the below.

 - Glances test (only available with Glances 3.1.7 or higher):

 ```
 To be completed with result of: glances --issue
 ```

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by soulvoid86** [comment]
I want to add I just created a fresh VM, Windows Server 2019 Standard just the same as this live system above, and the same issue persists. Nothing custom or special about the OS. It's just the standard eval ISO directly from Microsoft.

**Comment by nicolargo** [comment]
Perhaps related to https://github.com/nicolargo/glances/issues/2689#issuecomment-2050009675

**Comment by nicolargo** [comment]
How do you install Glances ?

The ujson dependency is not installed:

```
File "C:\Program Files\Python310\lib\site-packages\glances\globals.py", line 16, in
import ujson
ImportError: DLL load failed while importing ujson: The specified module could not be found.
```

**Comment by soulvoid86** [comment]
ujson is installed though.. I installed Glances per the guidelines using "pip install glances". I have Glances running on 6 other machines and have been using it for a few years now.

Yes, I've also tried updating pip as the warning states below too, no change. As I stated above, I even went through and version matched every package and installed them manually based on a working system. Same issue both on an existing machine and a freshly build VM, but the machines with Glances installed a long time ago still work fine.

I've also tried Python versions 3.4.0, 3.10.1, 3.12.3, same issue with all 3 versions across multiple machines.

C:\Users\Administrator>pip list
Package         Version
--------------- -----------
bottle          0.12.25
defusedxml      0.7.1
future          1.0.0
Glances         3.4.0.5
packaging       24.0
pip             21.2.4
psutil          5.9.8
pyparsing       3.1.2
python-dateutil 2.9.0.post0
setuptools      58.1.0
six             1.16.0
ujson           5.9.0
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\Administrator>glances -w
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\glances.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\glances\__init__.py", line 35, in <module>
    from glances.compat import PY3
  File "C:\Program Files\Python310\lib\site-packages\glances\compat.py", line 25, in <module>
    from glances.logger import logger
  File "C:\Program Files\Python310\lib\site-packages\glances\logger.py", line 20, in <module>
    from glances.globals import safe_makedirs
  File "C:\Program Files\Python310\lib\site-packages\glances\globals.py", line 16, in <module>
    import ujson
ImportError: DLL load failed while importing ujson: The specified module could not be found.

**Comment by soulvoid86** [comment]
Bump?

**Comment by nicolargo** [comment]
Did you try with Glances 4.0.7 ?

**Comment by michaelblight** [comment]
I'm getting the same thing on a new Windows 11 VM. I've added everything I can think of to PYTHONPATH. I ran everything as administrator.

![image](https://github.com/nicolargo/glances/assets/373079/aa7a8026-53b7-45a3-8f37-06de5fbbcc82)

**Comment by nicolargo** [comment]
There is a bug in the packaging of Glances 4.0.7.

A new version 4.0.8 is coming.
