### ISSUE TITLE
The cpulist of the percpu parameter cannot be fully displayed due to too many cores.

### ISSUE THREAD

**Issue by Char11e** [nicolargo/glances#2734]
**Describe the bug**
The model I am currently using has 144 cores, which causes the CPU list to be too long and cannot be displayed completely.

**To Reproduce**
glances --percpu

**Expected behavior**
You need to be able to see the total number of CPU cores and move them with the mouse wheel.

**Screenshots**
![image](https://github.com/nicolargo/glances/assets/41237079/f078f4f6-6c34-42ff-bd89-05bebcd9a730)

**Environement (please complete the following information)**
 - ubuntu 22.04
 - Glances v3.2.4.2 , PsUtil v5.9.0
 - apt-get install glances

 ```
 To be completed with result of: glances --issue
 ```
![image](https://github.com/nicolargo/glances/assets/41237079/27afa8cd-825a-46a8-938b-42c1b5bbac1f)

**Comment by nicolargo** [comment]
Whaou ! that a lot of cores :)

The Curses interface is not compatible with mouse button. and i want to keep Glances as simple as possible with all the "useful" information on the screen.

Another proposal is to sort the CPU core per consumption and only display the top 'n' (n will be configurable from the Glances configuration file). 

What do you think ?

**Comment by Char11e** [comment]
@nicolargo 

Thank you very much for your information!

Because I tried with the "more" directive, but it doesn't seem to work.

$ glances --percpu | more

**Comment by Char11e** [comment]
@nicolargo 

Another proposal is to sort the CPU core per consumption and only display the top 'n' (n will be configurable from the Glances configuration file).

By "n", do you mean that only the first "n" cores can be displayed?

For example: the first "40" cores or the first "25" cores?

Is there a way to specify the core number to display?
Example: 50th to 75th core or 100th to 140th etc.

Thanks again.

**Comment by nicolargo** [comment]
My proposal is the following:

First 'n' process sorrted by CPU consumption (with n = 3):

```
CPU10: [...
CPU2:   [...
CPU22: [....
CPU*  : [....
```

The last line (CPU*) display the sum of all others CPUs.

**Comment by Char11e** [comment]
Because sometimes when I test, I need to monitor the working condition of a specific core group.

For example, is it possible to add in the config to allow the user to set the number of CPU displays per page and support the page change function?

**Comment by nicolargo** [comment]
First implementation done in the develop branch.

Configuration file:

```
[percpu]
# Define the maximum number of CPU displayed at a time
# If the number of CPU is higher than the one configured in max_cpu_display then:
# - display top 'max_cpu_display' (sorted by CPU consumption)
# - a last line will be added with the mean of all other CPUs
max_cpu_display=4
```
