### ISSUE TITLE
V3.6.1.2 Docker Hub Image

### ISSUE THREAD

**Issue by trexx** [nicolargo/glances#2738]
**Describe the bug**
On Docker Hub, there appears to be an image tagged as v3.6.1.2 (https://hub.docker.com/layers/nicolargo/glances/3.6.1.2/images/sha256-5808b2290759cc4a22b4d1324c08111c11522ffb93a2dee1bad06c88be66d301). It seems like this maybe a mistake since this version is many years older than the latest version registered in Github.

I'm running Renovate to keep my images up to date, however it keeps suggesting 3.6.1.2 is the latest image when its infact several years old.

Could it be cleaned up?

**Comment by nicolargo** [comment]
Done.

Thanks for the head up 👍
