### ISSUE TITLE
Switch to forks of pysnmp as it is unmaintained

### ISSUE THREAD

**Issue by RazCrimson** [nicolargo/glances#2741]
Currently used `pysnmp` dep of glances is unmaintained. We should move towards on the forks that are currently maintained.

Context: https://github.com/etingof/pysnmp/issues/429

Forks:
- https://github.com/pysnmp/pysnmp
- https://github.com/lextudio/pysnmp

Downloads:
https://pypistats.org/packages/pysnmplib
https://pypistats.org/packages/pysnmp-lextudio

The fork from lextudio seems to be more maintained and receiving updates and seems to have more usage too. From a first look, we should probably switch to that.

**Comment by nicolargo** [comment]
Thanks for the information @RazCrimson 

I just test the new lib and after some changes, it run on my system:

    ./venv/bin/python -m glances -C ./conf/glances.conf -c localhost --disable all --enable system,cpu,mem,load


Give:

![image](https://github.com/nicolargo/glances/assets/776747/9a397c07-c726-4aac-bd3d-15af7c409b19)

**Comment by nicolargo** [comment]
Merged into develop.

**Comment by lextm** [comment]
An important change in `pysnmp-lextudio` 6.2 release is that we removed the sync API this repo might rely on.

Thus, either you migrate fully to PySNMP asyncio based async API, or you cap the dependency to 6.1.x.

**Comment by RazCrimson** [comment]
Thanks for the heads up! @lextm
