### ISSUE TITLE
Home assistant can't connect to Glances Unraid Docker 

### ISSUE THREAD

**Issue by RuneMason1** [nicolargo/glances#2764]
**Describe the bug**
Home assistant can't connect to Glances Unraid Docker 

**To Reproduce**
Glances is accessible by IP:Port in my PC's browser, but not by Home Assistant running in VM on Unraid (It's worked before.)

**Expected behavior**

**Screenshots**

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `To be completed with result of: lsb_release -a`
 - Glances & psutil versions: `To be completed with result of: glances -V`
 - How do you install Glances (Pypi package, script, package manager, source): `To be completed`
 - Glances test (only available with Glances 3.1.7 or higher):

 ```
 To be completed with result of: glances --issue
 ```

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by RazCrimson** [comment]
Glances had a new release yesterday, where a new version of the API was released. Currently not all client libs have upgraded to the change.

This issue can be resolved with you downgrade back to the old image (3.x) for a while and upgrading back later to 4.x (after the client libs handle the change).

Docker Image Tags are listed here for reference: https://hub.docker.com/r/nicolargo/glances/tags

Closing this as there is nothing glances team can do to resolve this. 
Please comment or open a discussion if you are facing issues with the downgrade.

P.S.

It would be really helpful if you fill in the issue template next time :)
