### ISSUE TITLE
Please make `pydantic` optional dependency, not required one

### ISSUE THREAD

**Issue by barracuda156** [nicolargo/glances#2777]
@nicolargo Please consider making `pydantic` an optional dependency: forcing a dependency on Rust is undesirable for several reasons (it is a very heavy dependency to build, it is broken on some platforms and cannot be built there at all, it is questionable from security point of view, since it requires itself to build).

**Comment by RazCrimson** [comment]
@barracuda156 

I understand that you would like to avoid using Pydantic. But currently the Webserver dependency (fastapi) would require it. 

Could you please list the platform which you use and currently don't have pydantic binaries?

Btw rust being required to build rust is totally normal in the compiler world? Even gcc and clang are Self-hosting compilers. 

I don't really understand your security concern. But I get that it's going to be a pain to build when no binaries are available.

**Comment by barracuda156** [comment]
@RazCrimson Thank you for responding! Rust does not build on older macOS (all powerpc, some older x86), I think it does not build for powerpc on OpenBSD as well (perhaps even on FreeBSD for ppc 32-bit). I am pretty sure there are other non-mainstream platforms where Rust does not build.

P. S. Both gcc and clang can be built with other C/C++ compilers, they do not require themselves to build.

**Comment by barracuda156** [comment]
@RazCrimson It will be sufficient to add a configure option to disable Pydantic and whatever needs it. I.e. nothing will change by default, but at the same time we could unbreak the package for Rustless systems.

**Comment by RazCrimson** [comment]
Sure, I think that should be possible as long as we don't require the webserver package.

**Comment by barracuda156** [comment]
@RazCrimson That would be awesome!

**Comment by nicolargo** [comment]
The default "pip install glances" do not install the Webserver requirements.

Pydantic should be installed only if you use "pip install glances[web]" or "pip install glances[all]".

**Comment by nicolargo** [comment]
So we have to move pydantic from requirements.txt to requirements-webui.txt ?

**Comment by RazCrimson** [comment]
Yea, but I think there was some pydantic import that was failing.

We'll probably have to fix that and check if everything works right.
