### ISSUE TITLE
GET /1272f6e9e8f9d6bfd6de.png results in 404

### ISSUE THREAD

**Issue by Emporea** [nicolargo/glances#2781]
Docker image 4.0.4
Behind nginx reverse proxy

When accessing glances via web ui I get a 404 error in the console because the 1272f6e9e8f9d6bfd6de.png file can not be found, even tho its present in the glances/outputs/static/public directory.

**Comment by RazCrimson** [comment]
@Emporea 

Could you please share the docker-compose file for this setup?

**Comment by nicolargo** [comment]
Same issue here.

It is not a proxy issue.

**Comment by nicolargo** [comment]
The URL should be http://localhost:61208/static/1272f6e9e8f9d6bfd6de.png not http://localhost:61208/1272f6e9e8f9d6bfd6de.png.

The file 1272f6e9e8f9d6bfd6de.png is dynamically generated from glances/outputs/static/images/glances.png by the make webui target (ref in ./glances/outputs/static/css/style.scss).

**Comment by nicolargo** [comment]
Logo removed from the landing page.

No more error.

Available in the develop branch.
