### ISSUE TITLE
Home Assistant add-on doesn't work with 4.0

### ISSUE THREAD

**Issue by jtenniswood** [nicolargo/glances#2793]
When trying to use the home assistant add-on for glances, it doesn't connect since updating to the latest version, sorry not sure why.
<img width="497" alt="image" src="https://github.com/nicolargo/glances/assets/10881541/7cdc1dd2-1a39-4cbb-ba2f-4d6315896363">

**Comment by iball** [comment]
Glances 4.x now has a different API that the HA plugin hasn't been updated to work with yet.

Until then, use the 3.4.0.5 version which does still work with the HA plugin.

**Comment by RazCrimson** [comment]
Please track the issue here for the integration: https://github.com/home-assistant/core/issues/117360
