### ISSUE TITLE
[WIP] FastAPI import error. Glances cannot start in web server mode

### ISSUE THREAD

**Issue by bibitocarlos** [nicolargo/glances#2797]
**Describe the bug**
When i launch glances, i get this error : 
"FastAPI import error. Glances cannot start in web server mode"

**To Reproduce**
1. Start Glances with the following options '-w'

**Expected behavior**
To work

**Environement (please complete the following information)**
 - Archlinux
 - glances --v
Glances version:        4.1.0_beta01
Glances API version:    4
PsUtil version:         5.9.8
Log file:               /root/.local/share/glances/glances.log

 - pacman

 ```


You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file 
2024-05-24 17:31:28,457 -- INFO -- Start Glances 4.1.0_beta01
2024-05-24 17:31:28,457 -- INFO -- CPython 3.12.3 (/usr/bin/python) and psutil 5.9.8 detected
2024-05-24 17:31:28,461 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2024-05-24 17:31:28,464 -- CRITICAL -- FastAPI import error. Glances cannot start in web server mode.

**Comment by bibitocarlos** [comment]
Resolved  with 
pacman -S python-fastapi  uvicorn

**Comment by RazCrimson** [comment]
Arch packager probably didn't package the optional requirements

**Comment by gatonero** [comment]
Also python-orjson is needed.

**Comment by nicolargo** [comment]
Yes, as all requirements listed in the documention.

Requirements

python>=3.8 (use Glances 3.4.x for lower Python version)

psutil (better with latest version)

defusedxml (in order to monkey patch xmlrpc)

packaging (for the version comparison)

orjson (an optimized alternative to the standard json module)

**Comment by kusmi** [comment]
Mhhh, orjson is not included in the standard debian packages, so it seems no API support on my Debian.

**Comment by nicolargo** [comment]
Issue should be open in the Glances Debian package repo.

**Comment by bcutter** [comment]
Original issue with "glances -w" after switching from 32 to 64 bit kernel: `Bus-Zugriffsfehler`

Tried to upgrade/reinstall glances. Now: `FastAPI import error. Glances cannot start in web server mode.`

So:
`sudo pip install --user 'glances[web]'`:

```
Collecting orjson>=3.2.1 (from fastapi->glances[web])
  Using cached orjson-3.10.3.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Stuck with a broken glances web. It was working fine before...

**Comment by fliespl** [comment]
Had same problem with pipx. These steps worked on ubuntu 24.04

```
pipx install 'glances[all]'
pipx inject glances 'uvicorn'
pipx inject glances 'fastapi'
```

**Comment by markiatheus** [comment]
> pipx install 'glances[all]'
> pipx inject glances 'uvicorn'
> pipx inject glances 'fastapi'

don't forget
> pipx install jinja2
> pipx inject glances 'jinja2'
