### ISSUE TITLE
Add support for automatically hiding network interfaces that are down or that don't have any IP addresses

### ISSUE THREAD

**Issue by spencerhakim** [nicolargo/glances#2799]
**Is your feature request related to a problem? Please describe.**
Currently, Glances requires users to manually specify which network interfaces to hide (potentially using regex), but I would prefer only legitimately active interfaces be displayed and which can appear/disappear automatically (such as when toggling wifi)

**Describe the solution you'd like**
A new option (or options, there may be a potential desire to hide down interfaces but not hide ones without an IP address) to enable automatic filtering similar to what the code below does

**Describe alternatives you've considered**
Currently, I've been patching `update_local()` in the network plugin with the following:
```patch
         net_status = {}
         try:
             net_status = psutil.net_if_stats()
+            net_addrs = psutil.net_if_addrs()
+
+            # Filter out interfaces that are not up
+            net_status = {k: v for k, v in net_status.items() if v.isup}
+
+            # Filter out interfaces that only have an AF_LINK address in net_addrs
+            net_status = {k: v for k, v in net_status.items() if k in net_addrs and any(a.family != psutil.AF_LINK for a in net_addrs[k])}
         except OSError as e:
             # see psutil #797/glances #1106
             logger.debug(f'Can not get network interface status ({e})')
```
It works very well, but it'd be nice not to have to patch that anymore.

**Additional context**
Before my patch:
![20240525_024414-CapturFiles](https://github.com/nicolargo/glances/assets/606857/52750fc3-1b4a-4294-8800-b8b8377a8f9b)

After:
![20240525_024450-CapturFiles](https://github.com/nicolargo/glances/assets/606857/0a7e399b-7c12-4740-a5ed-0e2a0dc578d3)

**Comment by nicolargo** [comment]
Proposal for the Glances configuration file:

```
[network]
...
# Automatically hide not up interfaces (default is False == do not hide)
hide_no_up=False
# Automatically hide interfaces without IP address (default is False = do not hide)
hide_no_ip=False
```

**Comment by nicolargo** [comment]
Pushed on the develop branch.

@spencerhakim please can you test it on your configuration ?

**Comment by spencerhakim** [comment]
Trying to following the directions in the README to install the development version, but I'm running into issues getting pip to be happy with whatever constraints its imposing (I'm not really a Python dev and barely familiar with the tooling, though I did try to use a venv without luck either). Probably better off asking someone else to test it, but looking at the commit it seems to more or less be exactly what I came up with, plus the code to read the options, so I'm thinking it should be fine?

**Comment by spencerhakim** [comment]
It seems this made it into v4.0.8 but wasn't part of the release notes. Anyway, now that I'm actually using it, it works perfectly. Thanks!
