### ISSUE TITLE
Unknown instance unknown?

### ISSUE THREAD

**Issue by ChillarAnand** [nicolargo/glances#2805]
**Describe the bug**
When running glances, I am noticing this error.

"Unknown Unknown instance Unknown (Unknown)"

<img width="1280" alt="Screenshot 2024-05-30 at 12 59 50" src="https://github.com/nicolargo/glances/assets/4463796/286f8ac1-ac14-4d84-b4e8-3658610fcee4">

**To Reproduce**

Start glances with influxdb2 export and wait for ~10 seconds.

```
❯ sudo glances -t 5 --export influxdb2 -C ~/.glances.conf
```

**Expected behavior**

**Screenshots**

<img width="1280" alt="Screenshot 2024-05-30 at 12 59 50" src="https://github.com/nicolargo/glances/assets/4463796/286f8ac1-ac14-4d84-b4e8-3658610fcee4">

**Environement (please complete the following information)**
macOS

```
❯ sudo glances -V
Glances version:	4.0.7
Glances API version:	4
PsUtil version:		5.9.1
Log file:		/Users/chillaranand/.local/share/glances/glances.log
```

**Comment by nicolargo** [comment]
Hi @ChillarAnand 

can you run the following command line and copy/paste the result:

```
glances --stdout cloud --stop-after 1
```

the cloud plugin is disable by default, check in your configuration file  (~/.glances.conf) that:

```
[cloud]
# Documentation: https://glances.readthedocs.io/en/latest/aoa/cloud.html
# This plugin is disabled by default
disable=True
```

Additional question: why do you run Glances with sudo, it is not secure....

**Comment by ChillarAnand** [comment]
```
❯ glances --stdout cloud --stop-after 1
cloud: {}
```

I don't have "cloud" section in config.

https://github.com/ChillarAnand/init/blob/main/glances.conf

If I run without sudo, output is as below. Horizontal lines are messed up.

<img width="1280" alt="Screenshot 2024-05-30 at 14 08 12" src="https://github.com/nicolargo/glances/assets/4463796/da3b7baf-823a-4565-8607-fd3198314b15">

**Comment by nicolargo** [comment]
My advice is to use the default glances.conf file (https://github.com/nicolargo/glances/blob/master/conf/glances.conf) and add your amp section inside it. If you overwrite the glances.conf, some sections (like the cloud one) are missing.

**Comment by nicolargo** [comment]
Concerning the strange behavor with the separators, you can disable its from tge configuration file:

```
[outputs]
separator=False
```

Can you copy/paste the result of the following command:

```
# echo $TERM

# sudo echo $TERM
```

**Comment by ChillarAnand** [comment]
> Concerning the strange behavor with the separators, you can disable its from tge configuration file:
> 
> ```
> [outputs]
> separator=False
> ```
> 
> Can you copy/paste the result of the following command:
> 
> ```
> # echo $TERM
> 
> # sudo echo $TERM
> ```

<img width="267" alt="Screenshot 2024-06-02 at 17 17 09" src="https://github.com/nicolargo/glances/assets/4463796/c95c89db-6469-4030-87eb-7e0e4fadb3de">

**Comment by ChillarAnand** [comment]
> My advice is to use the default glances.conf file ([`master`/conf/glances.conf](https://github.com/nicolargo/glances/blob/master/conf/glances.conf?rgh-link-date=2024-06-01T08%3A00%3A21Z)) and add your amp section inside it. If you overwrite the glances.conf, some sections (like the cloud one) are missing.

Even if some sections are missing, should they take "default" values by default?

By using the above config file, "Unknown" issue is resolved now.

**Comment by nicolargo** [comment]
For the separator issue, another issue has been opened: https://github.com/nicolargo/glances/issues/2817
