### ISSUE TITLE
Give a try to Reflex to replace de WebUI by a pure Python implementation

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2807]
https://github.com/reflex-dev/reflex

**Comment by nicolargo** [comment]
- Flex layout: https://reflex.dev/docs/library/layout/flex/

**Comment by nicolargo** [comment]
https://reflex.dev/docs/hosting/self-hosting/

**Comment by velaia** [comment]
> * Flex layout: https://reflex.dev/docs/library/layout/flex/

Have you heard of [FastHTML](https://fastht.ml/). I've been playing with it a little and it might be a (fun) alternative to reflex for the WebUI replacement ...
