### ISSUE TITLE
test `test_107_fs_plugin_method` fails on aarch64-linux

### ISSUE THREAD

**Issue by gador** [nicolargo/glances#2819]
**Describe the bug**
When trying to compile the current glances version for `aarch64-linux` it fails. This happens since version `4.0.6`

**To Reproduce**

1. Compile `glances` version `4.0.7` from source for `aarch64-linux` 
2. See the error:

```
FAIL: test_107_fs_plugin_method (__main__.TestGlances.test_107_fs_plugin_method)
Test fs plugin methods
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/unittest-core.py", line 634, in test_107_fs_plugin_method
    self._common_plugin_tests('fs')
  File "/build/source/unittest-core.py", line 105, in _common_plugin_tests
    self.assertTrue(res)
AssertionError: False is not true
```
Full log at https://hydra.nixos.org/build/262259380/log

**Expected behavior**
All tests to pass

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `NixOS unstable 24.04`
 - Glances & psutil versions: `4.0.7`
 - How do you install Glances (Pypi package, script, package manager, source): `nix`
 - Glances test (only available with Glances 3.1.7 or higher): Unable

**Additional context**

For anyone to try on a nix-enabled system:
`nix build --system "aarch64-linux" github:nixos/nixpkgs/0c11f909d79e6f1485a73c29c21e65f9b2b64294#glances`

**Comment by gador** [comment]
small update: Test `107` seems to be flakey. Sometimes it fails, sometimes it doesn't. 
For some reason test `105` now fails consistently.

Everything on `aarch64`

**Comment by nicolargo** [comment]
Should be corrected in the develop branch.

Please can you test @gador ?

**Comment by gador** [comment]
@nicolargo thanks for the quick reply. I am getting the following error:
```
glances-aarch64-linux> ======================================================================
glances-aarch64-linux> ERROR: test_105_network_plugin_method (__main__.TestGlances.test_105_network_plugin_method)
glances-aarch64-linux> Test network plugin methods
glances-aarch64-linux> ----------------------------------------------------------------------
glances-aarch64-linux> Traceback (most recent call last):
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 625, in test_105_network_plugin_method
glances-aarch64-linux>     self._common_plugin_tests('network')
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 123, in _common_plugin_tests
glances-aarch64-linux>     current_stats[0]['foo'] = 'bar'
glances-aarch64-linux>     ~~~~~~~~~~~~~^^^
glances-aarch64-linux> IndexError: list index out of range
glances-aarch64-linux>
glances-aarch64-linux> ----------------------------------------------------------------------
glances-aarch64-linux> Ran 37 tests in 234.431s
```

commit a6b7de8a4b80df30cd3b4d1391cac7b978f342df (current head of `develop`)

**Comment by gador** [comment]
@nicolargo just tested with commit 051006e12f7c90281dda4af60871b535b0dcdcb9 and all test pass :+1:

**Comment by RazCrimson** [comment]
Closing as this is fixed
