### ISSUE TITLE
Release 4.1.1 Linux browse mode crashes

### ISSUE THREAD

**Issue by ronligt** [nicolargo/glances#2861]
**Describe the bug**
After installing release 4.1.1 the browse mode is no longer working. The application crashes immediately after starting with `glances --browse`

**To Reproduce**
1. Install glances with `pip`
2. Start glances with browse mode `glances --browse`
3. See error:

```raw
Traceback (most recent call last):
  File "/home/ronald/glances/env/bin/glances", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/__init__.py", line 173, in main
    start(config=core.get_config(), args=core.get_args())
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/__init__.py", line 121, in start
    mode.serve_forever()
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/client_browser.py", line 234, in serve_forever
    return self.__serve_forever()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/client_browser.py", line 218, in __serve_forever
    self.screen.update(self.get_servers_list())
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/outputs/glances_curses_browser.py", line 214, in update
    self.flush(stats)
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/outputs/glances_curses_browser.py", line 238, in flush
    self.display(stats)
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/outputs/glances_curses_browser.py", line 260, in display
    return self.__display_server_list(stats, x, y, screen_x, screen_y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ronald/glances/env/lib/python3.12/site-packages/glances/outputs/glances_curses_browser.py", line 362, in __display_server_list
    self.term_window.addnstr(y, xc, value, c[2], decoration)
TypeError: expect bytes or str, got NoneType
```

**Expected behavior**
Up till the previous version the following screen would show:

```raw
2 Glances servers available
ONLINE: 2
  Name               LOAD     CPU%    MEM%    STATUS      IP                OS
> bla            3.70     1.9     2.2     ONLINE      10.0.0.1          Ubuntu 24.04 64b
  bloe             0.00     0.0     0.7     ONLINE      10.0.0.2          Ubuntu 24.04 64b
```

**Environement (please complete the following information)**
 - Operating System:
```raw
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
``` 
 - Glances & psutil versions:
 ```raw
Glances version:	4.1.1
Glances API version:	4
PsUtil version:		6.0.0
Log file:		/home/ronald/.local/share/glances/glances.log
```
 - How do you install Glances (Pypi package, script, package manager, source): **Pypi package**

**Comment by nicolargo** [comment]
@ronligt Sorry for that :(

For the moment pin your Glances version to 4.1.0, a new 4.1.2 release with a patch will be done asap.

**Comment by nicolargo** [comment]
@ronligt i can not reproduce on my side.

Is all your Glances server instances updated to 4.1.1 ?

**Comment by ronligt** [comment]
Yes, when I updated to 4.1.1 and tested, all instances were 4.1.1.

**Comment by ronligt** [comment]
By the way: also 4.1.0 gives the same error. Only version 4.0.8 has no problem!

**Comment by nicolargo** [comment]
It is perhaps a side effect of https://github.com/nicolargo/glances/issues/2859

When it is release, can you test Glances 4.1.2 ?

**Comment by nicolargo** [comment]
@ronligt Can you give a chance to Glances 4.1.2 ?

**Comment by ronligt** [comment]
I'm afraid I still get the exact same error.

I've started the server `glances -s` and the browse client `glances --browse`.

```bash
$ glances -V
Glances version:	4.1.2
Glances API version:	4
PsUtil version:		6.0.0
Log file:		/home/ronald/.local/share/glances/glances.log
```

**Comment by ronligt** [comment]
Ah, I've commented out:

```python
                    # if c[0] == 'name' and 'alias' in server_stat:
                    #     value = server_stat['alias']
```

And now I get the names of the servers back in the table!

**Comment by ronligt** [comment]
Following I added a value for `server_1_alias` and `server_2_alias` in `/etc/glances/glances.conf`, uncommented the code in the previous comment and everything works as it should.

Is the `server_*_alias` required?

**Comment by nicolargo** [comment]
It should not but there is perhaps a bug...
I will have a look.

**Comment by nicolargo** [comment]
@ronligt can you try the following patch: https://github.com/nicolargo/glances/commit/6f7a09686c4ec3a90f1aa16897dbc981202aafe9

It only manage the case when the hostname coming from the server is empty.

**Comment by ronligt** [comment]
Looks good! I tested this patch starting the patched server instance and the browse client. No errors! 🥳

**Comment by RazCrimson** [comment]
Closing as issue is fixed
