### ISSUE TITLE
Ip not showing on rest api v4

### ISSUE THREAD

**Issue by Amine-Smahi** [nicolargo/glances#2864]
Hi glances team,

i'm not able to see or access the ip information, how can i fix that
![image](https://github.com/nicolargo/glances/assets/24621701/4759ffac-8780-43c8-9aca-385cefdfc599)

Info:
Glances version:	4.1.2
Glances API version:	4
PsUtil version:		6.0.0

**Comment by nicolargo** [comment]
Can not reproduce on my side with the same version.

![image](https://github.com/nicolargo/glances/assets/776747/3d16a066-dc01-47a1-9f51-13b59e98b05d)

Can you copy paste your configuration file ?

**Comment by Amine-Smahi** [comment]
i did 

`pip install --user glances[all] --break-system-packages`

did i forgot something ?

**Comment by nicolargo** [comment]
Nope, please copy/paste the Glances log file.
Path to the log file can be found using the followin command line:

```
glances -V
Glances version:	4.1.2
Glances API version:	4
PsUtil version:		6.0.0
Log file:		**/home/nhe/.local/share/glances/glances.log**
```

**Comment by Amine-Smahi** [comment]
I found the issue, thank you for your time :D

the issue was that i had previously installed glances via apt and it think both versions collided and created an issue
