### ISSUE TITLE
Make fields labelled in Green easier to see 

### ISSUE THREAD

**Issue by techno156** [nicolargo/glances#2882]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/11d7b035-004e-4c31-a226-c046a62161b2)
Currently, glances will highlighted some fields in green, but use dark grey text. This makes the text in the box rather difficult to see at a quick glance, compared to the either the boxes highlighted in red, or ones that have no highlighting at all.

**Describe the solution you'd like**
Ideally, the text colour would be changed from grey to something that has better contrast when highlighted in green, such as black, which would make it stand out more compared to the white text on red.

**Describe alternatives you've considered**
One alternative I considered was to remove the green box entirely, and just label the text green, but that could be more confusing, since it would be mixed with the other text that is coloured green.

**Additional context**
![image](https://github.com/user-attachments/assets/07c41e59-eff9-49b0-ad83-081d2bdc1594)

I've included an example testing other colours (in MS Paint). Either black or white would be more legible than the original grey.

**Comment by nicolargo** [comment]
Hi @techno156 

on the develop branch, the default colors binding are the following:

![image](https://github.com/user-attachments/assets/e46755a8-52de-4c27-af22-16a8b73903e4)

and

![image](https://github.com/user-attachments/assets/f3934422-2f4b-4643-b5c4-9168a9e32b42)

On your screenshot, it looks like you have change the Glances configurable file to log user, system and iowait CPU thresholds and not the total. Is it correct ?

PS: We also plan to make the color configurable: https://github.com/nicolargo/glances/issues/2048

**Comment by nicolargo** [comment]
Can you copy/paste your Glances configuration file ?

**Comment by RazCrimson** [comment]
Will make fix for now as WHITE seems more prominent in  a colored bg

Current: 
![image](https://github.com/user-attachments/assets/638dde31-58ad-4d3e-af85-7d6e246d679c)

White Version:
![image](https://github.com/user-attachments/assets/c6b67e93-278a-4923-bcba-0ef365cda43a)

**Comment by Praful** [comment]
I can't read the numbers in kitty terminal but can in Linux Mint Terminal. I've never changed the config file in /etc/glances/glances.conf. I renamed it and the result was the same.

```
❯ glances --version    
Glances version:	4.3.3
Glances API version:	4
PsUtil version:		7.0.0
```

In Linux Mint Terminal, I see this:

<img width="256" height="63" alt="Image" src="https://github.com/user-attachments/assets/b7559ffd-6805-4311-86c8-13ea06c67339" />

<img width="542" height="43" alt="Image" src="https://github.com/user-attachments/assets/c300395e-8590-45c8-a520-85dae01fe64a" />

This is fine. 

However, in latest kitty 0.42.1, I see this:

<img width="355" height="46" alt="Image" src="https://github.com/user-attachments/assets/b9b59d37-319c-405e-83ad-4d33cb7da2ee" />

<img width="602" height="47" alt="Image" src="https://github.com/user-attachments/assets/113587b4-c357-4dda-80ab-b59f32fdd38f" />

which is not very legible!

How can I change the colours?

**Comment by nicolargo** [comment]
@Praful  in Kitty it looks like the default font color is white and not  grey...

**Comment by nicolargo** [comment]
@Praful Perhaps have a llok on https://www.reddit.com/r/KittyTerminal/comments/169iat2/setting_tab_foregroundbackground_color/

**Comment by Praful** [comment]
@nicolargo thank you for the quick response. This seems to be a property of the theme I'm using in Kitty (catppucchin Macchiato), which is configured using `kitten themes`. I'd forgotten I changed this!

Terminal is picking up the Linux Mint system theme.

I'll play around with the themes/config in Kitty and look at the link you provided.

**Comment by nicolargo** [comment]
Nevertheless Glances should be configurable in term of color, there is an open issue (https://github.com/nicolargo/glances/issues/2048) waiting for a kind contributor... :)

**Comment by Praful** [comment]
Changing white to #FFFFFF in the theme did improve things but the background colours are too light, so I'll play with those too.

I'll have a look at the glances source code and see if theming it is within my capabilities!

Edit: is this dependent on #2114?

**Comment by nicolargo** [comment]
Nope.
If you can just have a look on the TUI .

Thanks !
