### ISSUE TITLE
Unable to kill

### ISSUE THREAD

**Issue by binny1024** [nicolargo/glances#2909]
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/04a3d55a-95ab-43bd-be6c-71d2d81473fb">

Cannot be killed, after killing the pid, it will restart

**Comment by RazCrimson** [comment]
@binny1024 

Please fill the details mentioned in the issue template

**Comment by binny1024** [comment]
Thank you very much for your response; there are no issues now.
