### ISSUE TITLE
Show only active Disk I/O (and network interface)

### ISSUE THREAD

**Issue by dfadev** [nicolargo/glances#2929]
**Is your feature request related to a problem? Please describe.**
DISK I/O section takes up too much space when you have 10+ disks and each are using device mapper.

**Describe the solution you'd like**
A toggle key that makes the DISK I/O section only show active disks where R/s or W/s is greater than zero.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/user-attachments/assets/d0ff719f-54c8-4fe8-9798-8744dc8a11f6)

**Comment by nicolargo** [comment]
@dfadev As a workaround you can hide dm and sd disk from the Glances configuration file:

```
[diskio]
...
hide=loop.*,/dev/loop.*,dm.*,sd.*
...
```

**Comment by nicolargo** [comment]
Implemented in the develop branch by adding a hide_zero option.

To enable the feature:

```
[diskio]
...
hide_zero=True
...
```

**Comment by nicolargo** [comment]
@dfadev can you test the develop branch ?

**Comment by dfadev** [comment]
![image](https://github.com/user-attachments/assets/348ab0b9-646a-406c-b458-33e6a3d1e7d8)

"Works on my machine"

Of course now that I see it I think `hide_threshold_bytes` also makes sense, so the tiny 14K writes don't show up.

Would be nice to have this on network interfaces too:
![image](https://github.com/user-attachments/assets/f93c69e8-8f57-4138-9bf7-251beffadd51)

**Comment by dfadev** [comment]
Also while I'm at it, a small delay before removing it from the list could make sense.  Sort of debounce the removal so if activity drops for a few seconds then picks back up the entry doesn't phase in and out.

**Comment by dfadev** [comment]
I see this was implemented for network interfaces too, very cool.  Here's a quick video of it in action that shows why an entry removal delay and a configurable threshold could be nice.

https://github.com/user-attachments/assets/c06d8163-8d89-41de-81e7-6ca75c80d6d8

**Comment by nicolargo** [comment]
@dfadev Thanks for all your remarks regarding this feature. I close the current one (will be release in Glances 4.2) and i open another issue (https://github.com/nicolargo/glances/issues/2958) to follow the enhancement regarding delay and min_bytes options.
