### ISSUE TITLE
Please make `py-orjson` optional: it pulls in dependency on Rust

### ISSUE THREAD

**Issue by barracuda156** [nicolargo/glances#2930]
We are back to a breakage which was fixed once: another new dependency now pulls in Rust. This is generally undesirable, since it is an unjustifiably heavy dependency to build, but also it breaks `glances` for every platform where Rust is broken.

Could we please make this optional or replace with something properly cross-platform?

**Comment by RazCrimson** [comment]
@barracuda156 

I've tried making the orjson dependency optional.
Could you try using the latest develop to test and see if things work as expected?

**Comment by barracuda156** [comment]
@RazCrimson Thank you! I will try this.

BTW, earlier `ujson` has been used as a drop-in replacement. If a bug was discovered in it which led to `orjson` switch, maybe bring that to `ujson` upstream? (I cannot do that from my side, since I have no idea what exactly stopped working with `ujson`.)

**Comment by RazCrimson** [comment]
@barracuda156 

We are moving to orjson as ujson is currently on maintenance mode and their maintainers recommend moving to orjson.

Does your platform support ujson?

I could add callbacks such that it we try

```
orjson > ujson > json (builtin)
```

**Comment by barracuda156** [comment]
@RazCrimson Yes, `ujson` seems to work fine. I replaced all instances of `orjson` with `ujson` and the app works.

**Comment by nicolargo** [comment]
@RazCrimson i have added some comment in https://github.com/nicolargo/glances/commit/1e278fa2cbc039412abca9ec75c07c20bcc3beec

In fact orjson is only used to encode (loads) and not decode (dumps). The only file that uses JSON dumps is server.py and it directly import json and not orjson.

**Comment by RazCrimson** [comment]
@barracuda156 
Please let me know if this works fine for you with ujson. Even the web server should work.

@nicolargo 
I've just centralized the json imports and we try to use faster libs if they are available if not, we use the builtin json. Does this work fine with you?

**Comment by barracuda156** [comment]
@nicolargo Sorry, missed it back then. Yes, I just updated to 4.2.1, and everything works fine now without patching. Thank you!
