### ISSUE TITLE
AMDGPU not showing any info just blank box on homepage? the only image that works to show cpu ,mem ,network is nicolargo/glances:4.1.2.1-full

### ISSUE THREAD

**Issue by Tw1zT3d2four7** [nicolargo/glances#2936]
AMDGPU not showing any info just blank box on homepage? the only image that works to show cpu ,mem ,network is nicolargo/glances:4.1.2.1-full However in glances web ui i see the gpu ingo being populated after adding version: 4 to the service.yml

any help would be great guys!

**Comment by RazCrimson** [comment]
@Tw1zT3d2four7 

If the glances webui is showing the info correctly and working fine, then please go through homepage's FAQ and if it doesn't work (or you have already gone through it), try to open an issue at [home](https://github.com/gethomepage/homepage)

Closing it for now. Just comment to reopen later if there is some contract violation on glances end.
