### ISSUE TITLE
The Web interface ignores the strftime_format parameter

### ISSUE THREAD

**Issue by alnviana** [nicolargo/glances#2939]
**Describe the bug**
Changing the strftime_format global parameter in the configuration file to change the current date has no effect on the web interface, only when run from the console.

**To Reproduce**
1. Change the strftime_format parameter in the configuration file.
2. Start the Glances container.
3. Access the web interface and see if it works (in my case, the default appears).
4. Access the container shell.
5. Run glacier as a console and see if it has taken effect. (In my case, what I configured appears)

**Expected behavior**
The configuration of the strftime_format parameter should be reflected in the web interface, or if this parameter is not expected to work in the web interface, the documentation should be updated.

**Screenshots**
Web:
![image](https://github.com/user-attachments/assets/4253f958-07fd-4c60-8884-b6482972900b)
Console:
![image](https://github.com/user-attachments/assets/b68d2c48-b7af-4089-80a1-6d929f5dfdc9)

**Environement (please complete the following information)**
 - Operating System:
   - Debian GNU/Linux 12 64bit / Linux 6.1.0-25-amd64
 - Glances & psutil versions:
   - Glances version:        4.1.2
   - Glances API version:    4
   - PsUtil version:         6.0.0
 - Glances installation:
   - Docker: nicolargo/glances:latest - Image ID: sha256:11ccce46a17bb28b5d2d77f30fa05658fb01e738097d39a11bc94ddbeee22160
 - Glances test:
   - I don't think it's necessary to send it, because all the active plugins are OK. If it's really necessary, just let me know and I'll send it.

**Comment by nicolargo** [comment]
Thanks for the issue report @alnviana 

Corrections done on the develop branch and will be release in Glances 4.2.0:

- strftime_format option is now also taken into account in the WebUI
- remove " from the glances.conf example:

```
before:   strftime_format="%Y-%m-%d %H:%M:%S %Z"
after:  strftime_format=%Y-%m-%d %H:%M:%S %Z
```
