### ISSUE TITLE
Run "browser" mode in a WebUI

### ISSUE THREAD

**Issue by hyharry** [nicolargo/glances#2940]
**user scenario**
i have a bunch of servers to monitor, and `glances --browser` mode is very handy to get an overview of them in _terminal_. could i start the monitoring via `glances --browser` on a machine and then view then with a web browser (knowing the ip address and port of my `glances --browser`), i.e. a combination of browse + webserver mode.

basically, i would like to do

on host 1, `glances -s`
on host 2, `glances -s`
on host 3, `glances --browser -w` (knowing the serverlist via a `glances.conf`)
on host 4, on a web browser i can do `host3:61208` then view my list of servers. 

it seems not implemented yet. Would you add this functionality? Or someone has already faced the same issue and tried to solve it?

Thanks for your help.

**Comment by hyharry** [comment]
by looking into your discussion #2292 and your issue #995 I guess this can be only done by some customizing with glances REST api instead of easy command line options. is it correct?

**Comment by nicolargo** [comment]
For the moment, it is not possible, but the feature request is interresting.

**Comment by nicolargo** [comment]
Additional information to take into account before the developement.

1. On hosts, servers should be run with glances -w
2. The Web browser client should be ran with glances --browser -w 
3. The Web browser client should detect clients on the same LAN (thanks to zeroconf, like it is already done in --browser XMLRPC client/server mode)
4. The Web browser client should read server list from the configuration file (adapt existing serverlist  section)
5. When the Web browser client start, it should display a list of server with basic stats (configurable in the configuration file columns option in the severlist section 
6. When user click on a server, it should redirect to the WebUI of the server.
7. In the WebUI a link should be available to return to the server list

**Comment by nicolargo** [comment]
I close this issue because the subject is already covered by https://github.com/nicolargo/glances/issues/1121
