### ISSUE TITLE
Incomplete pipx install to allow webui + containers

### ISSUE THREAD

**Issue by fliespl** [nicolargo/glances#2955]
**Check the bug**
Not found...

**Describe the bug**
On ubuntu 24.04 installation glances 4.1.2 simply won't work due to additional steps required.

```
pipx install 'glances[all]'
pipx inject glances fastapi
pipx inject glances uvicorn
pipx inject glances python-dateutil
pipx inject glances jinja2
```

It's possible more injects are required - didn't test all apps.

**Comment by nicolargo** [comment]
Corrected on the develop branch. Will be release in Glances 4.2.0.
