### ISSUE TITLE
Migrate from setup.py to pyproject.yml

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2956]
Source: https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

Example:
```
[project]
name = "foo"
version = "0.0.1"
authors = [{ name="Bat Man", email="bat.man@gotham.com"}]
description = "Test"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: TBD ",
    "Operating System :: OS Independent",
]

dependencies = ["stomp-py", "toml", "importlib_metadata"]

[project.optional-dependencies]
dev = [
    "bandit",
    "ruff",
    "pytest",
    "pytest-docker",
    "pytest-cov",
    "twine",
    "build"]



[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
```

In the code, we can reuse the version of the pyproject.yml:

```
from importlib_metadata import version, PackageNotFoundError
__appname__ = "foo"
try:
    __version__ = version(__appname__)
except PackageNotFoundError:
    __version__ = f"Version not found for {__appname__}"
```

**Comment by nicolargo** [comment]
@branchvincent i have a question. When Glances is ran locally (during dev) or for example in the Docker:dev image, Glances return 0.0.0.0 as version, is there a way to read the content of the pyproject.toml file ?

**Comment by branchvincent** [comment]
hi, `importlib.metadata` reads from installed metadata so the package would need to be installed. so for local dev, the general recommendation is to install in editable mode: `pip install -e .`

I wouldn't recommend reading from `pyproject.toml` yourself, if installing is too inconvenient we can instead move the version from `pyproject.toml` (marking it as `dynamic`) back to `glances/__init__.py`: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

**Comment by nicolargo** [comment]
Thanks @branchvincent 

i just push an ugly patch to read directly into the pyproject.toml but your link to dynamic metadata looks a better solution. I will give a try as soon as possible.

**Comment by branchvincent** [comment]
Went ahead and created #2990 with the `dynamic` approach
