### ISSUE TITLE
Improve hide_zero option

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2958]
After the implementation of https://github.com/nicolargo/glances/issues/2929

Some improvement will be useful:
- Of course now that I see it I think hide_threshold_bytes also makes sense, so the tiny 14K writes don't show up. See Of course now that I see it I think hide_threshold_bytes also makes sense, so the tiny 14K writes don't show up.
- Also while I'm at it, a small delay before removing it from the list could make sense. Sort of debounce the removal so if activity drops for a few seconds then picks back up the entry doesn't phase in and out. See Also while I'm at it, a small delay before removing it from the list could make sense. Sort of debounce the removal so if activity drops for a few seconds then picks back up the entry doesn't phase in and out.

**Comment by nicolargo** [comment]
Thanks again @Tacitor 

In the PR i have change the line from:

    if field in self.hide_zero_fields and i[field] >= self.hide_threshold_bytes:

to:

    if field in self.hide_zero_fields and i[field] > self.hide_threshold_bytes:

And add some documentation for the new option.

**Comment by Tacitor** [comment]
You're welcome, my pleasure!

Thanks for taking care of the documentation. For any future contributions I'll be sure to do that as well.
