### ISSUE TITLE
Filter Docker containers

### ISSUE THREAD

**Issue by G4Zz0L1** [nicolargo/glances#2962]
I believe the commit https://github.com/nicolargo/glances/commit/bc0cf31a12f7ab2b8ab6db38fb16b6dfa308b02b for the issue https://github.com/nicolargo/glances/issues/1748 might have been lost in the various versions.

I have tried every possible regex, but when I looked into the code for the method "is_hide," I found that it is declared in the file https://github.com/nicolargo/glances/blob/develop/glances/plugins/plugin/model.py but is only used in the file https://github.com/nicolargo/glances/blob/develop/glances/plugins/fs/__init__.py for the "fs" plugin.

Is it possible to bring that function back into the docker plugin?

Thanks in advance!

**Comment by nicolargo** [comment]
Thanks @G4Zz0L1 !

I will remerge it on the develop branch.

**Comment by nicolargo** [comment]
Corrected in the develop branch.
