### ISSUE TITLE
Password tag disambiguation

### ISSUE THREAD

**Issue by foralesergi** [nicolargo/glances#299]
Right now we have two ways to define a password in the server/client mode:

```
-P PASSWORD    Define a client/server password
--password     Define a client/server password from the prompt
```

Since the new method is a far way better solution than the other one, I would like to propose to maintain only the latter.
Also, I don't really like the first one for a security reason: the password is being passed directly as an argument and thus logged in the shell history.

**Comment by wdhif** [comment]
Hi,

The -P arg doesn't seems to be working.
This command doesn't work :

glances -w -P myPassword

Any idea @nicolargo @asergi ?

Thanks

**Comment by nicolargo** [comment]
Hi @wdhif.

First of all i think that you use an "old" Glances version. The -P option is deprecated and as been replaced by --password.

Nevertheless, the login/password feature for the Web UI is only available in 2.5 or higher. What is you glances version ?

**Comment by wdhif** [comment]
I'm using Glances 2.6.2

The problem is that I want to put my password in the command (for a script), with --password, I only get a prompt.

**Comment by nicolargo** [comment]
Nope, it was a security issue.

Nevertheless, if you use the --password tag, the login/password (hash) is saved in a file and the client is not prompted anymore.

Server side:

    glances -s --password
    > Enter a password
    > The password is saved

Client side:

    glances -c <@server> --password
    > Enter the password
    > The password is saved
    > Glances starts
    CTRL-C
    glances -c <@server> --password
    > Glances starts

**Comment by wdhif** [comment]
Ok I see
Actually it was more to use ansible for glances, but I'll figure it out.

Thanks for your time :)
