### ISSUE TITLE
[WEBUI] Came back to default Black Theme / Reduce font size

### ISSUE THREAD

**Issue by mihcox** [nicolargo/glances#2993]
**Is your feature request related to a problem? Please describe.**
The previous version of glances had an All Black appearance, which has now been changed to grey. Please allow us to have a black based color scheme again.

**Describe the solution you'd like**
Bring back the black based color scheme from the previous version, or at least a flag for it

**Describe alternatives you've considered**
None, just don't like the grey

**Additional context**

**Comment by ilcardella** [comment]
+1 for this request. The new layout seems to have issues in optimizing the use of the available screen space. In my case I know have to scroll down to see the containers table and then scroll down again for the processes table. Before everything was visible without requiring any scrolling.

**Comment by nicolargo** [comment]
Ok copy that.

I am going to get back to a default "black" theme and reduce the font size.

**Comment by nicolargo** [comment]
Done in the develop branch.

Thanks for the report  @mihcox

**Comment by jslegers73** [comment]
I have installed version 4.2.1 and the screen is not correct as the previous versions. The containers are below the sensors. I have tested it in Edge. If the zoom level is 67% then it show ok but the font is to small then.

**Comment by the-night-wing** [comment]
> I have installed version 4.2.1 and the screen is not correct as the previous versions. The containers are below the sensors. I have tested it in Edge. If the zoom level is 67% then it show ok but the font is to small then.

Same for me, containers are below sensors + word wrapping is now disabled:
![image](https://github.com/user-attachments/assets/6cb60afb-879f-4b75-8048-74d3e66249a5)

on 67%: zoom they again sit next to the sensors
![image](https://github.com/user-attachments/assets/67626f3f-b322-4204-9a55-aec7a228cc61)

**Comment by httpsWina** [comment]
> containers are below sensors + long command or container names are wrapped

any solution for this?
