### ISSUE TITLE
Podman plugin logs messages flooding when no internet access

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2994]
```
2024-10-31 08:31:13,003 -- ERROR -- containers (Podman) plugin - Can't get containers list (503 Server Error: Service Unavailable (
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!-- 
...
```

**Comment by RazCrimson** [comment]
The API call is responding with 503, which probably either means the podman socket is set to something that is not actually running podman, or something else is wrong with the podman instance running on the socket.

**Comment by nicolargo** [comment]
Yes my proxy was not configured as expected. It was used to access to Podman.
SO it is not a Glances issue. Nevertheless i have made a little change in the way log are displayed. Only the first ERROR message concerning the containers list is displayed in the log, the others use DEBUG.

**Comment by nicolargo** [comment]
Done in commit https://github.com/nicolargo/glances/commit/ac7ab9ea842c6a538b630f21789d1e328232f976
