### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by asergi** [nicolargo/glances#300]
Python 2.6 just came to end (2.6.9 was released a few days ago): no more support, bug fixes or security patches.
Python 2.7 is the only 2.x version planned to last before 3.x completely takes over [1].

Most Linux distributions (Ubuntu, Arch Linux, Fedora, etc.) have had Python 2.7 as the default Python 2.x implementation for a long time now. Debian 7 (wheezy), the current stable version, has Python 2.7 as default.
FreeBSD has Python 2.7 as default as well.

Only current RHEL/CentOS stable version are still on Python 2.6 (shame on them).
The old Debian stable version, squeeze, has Python 2.6 as default.

Dropping support for Python 2.6 will have the following benefits:
* Reduce the number of versions to support. This will allow us to focus on writing (modern) code, not on legacy support.
* No more Python 2.6 compatibility issues (str.format(), with statement, etc.).
* Gives us access to argparse (and save a lot of lines of code) [2].
* Remove need for unittest2 dependency (tests are currently broken under Python 2.6).

Feel free to add further benefits or drawbacks as comments.

[1] http://docs.python.org/dev/whatsnew/2.7.html
[2] http://docs.python.org/2/library/argparse.html?highlight=argparse#argparse

**Comment by asergi** [comment]
Added deprecation warning for Python 2.6: 45820e9.

**Comment by nicolargo** [comment]
@asergi Is there any way in the setup.py file to prevent users to install/upgrade Glances 2.7 if Python 2.6 is used.

"Glances 2.7 is not compliant with Python 2.6. Please use Glances version 2.6.1"

**Comment by asergi** [comment]
@nicolargo just changing this line: https://github.com/nicolargo/glances/blob/master/setup.py#L8.
And this https://github.com/nicolargo/glances/blob/master/glances/__init__.py#L52 to avoid people running it directly from source or virtualenv.

**Comment by nicolargo** [comment]
@asergi Nice ! Can you work on this issue ?

**Comment by nicolargo** [comment]
First part of the job is done in the latest commit: https://github.com/nicolargo/glances/commit/830caf970355d8115dc686556987cad78f9f4cfe

Had to check if there is no specific 2.6 code inside the sources...

**Comment by asergi** [comment]
Done.
