### ISSUE TITLE
[WEBUI] Go back to default Grey Theme / Increase font size

### ISSUE THREAD

**Issue by duloo0** [nicolargo/glances#3001]
**Is your feature request related to a problem? Please describe.**
The previous version of Glances had a grey appearance, which has now been changed to black. Please allow us to have a grey based color scheme again.

**Describe the solution you'd like**
Bring back the grey color scheme from the previous version.

**Describe alternatives you've considered**
None, just like the grey.

**Additional context**

**Comment by nicolargo** [comment]
The current version of the Glances WebUI theme reproduce the style of the TUI (console user interface). 

A feature request is open to make the theme configurable: https://github.com/nicolargo/glances/issues/2048

Any contributor are welcome.

PS: @duloo0 thanks for the issue report, i close it, you can follow the feature request in https://github.com/nicolargo/glances/issues/2048
