### ISSUE TITLE
Network problem when no bitrate available

### ISSUE THREAD

**Issue by tags147** [nicolargo/glances#3014]
I run the command glances and it no longer works.

So when i run the command 'glances' this is what i get:
https://pastebin.com/XP4DnA1Q

Here is my conf and log
https://pastebin.com/n6VYkrfK
https://pastebin.com/FzprPYFb

 - Operating System: proxmox-ve: 8.2.0 (running kernel: 6.8.12-2-pve)
 - Glances & psutil versions: Glances version: 4.2.1, PsUtil version: 6.1.0
 - How do you install Glances: I have tried various methods but the current one i have install i used this command: pip install glances[all]
 - Glances test: https://pastebin.com/apNEQBnh

**Comment by nicolargo** [comment]
Thanks for the issue report @tags147 

In order to reproduce it on my side, can you please run from a terminal the following command and paste/bin the result:

```
$ python
>>> import psutil
>>> psutil.net_io_counters(pernic=True)
```

Thanks !

**Comment by tags147** [comment]
Here you go! 
https://pastebin.com/fja76mwh

**Comment by tags147** [comment]
@nicolargo is there anything I can change or do to at least temporarily fix it? I've been trying different things when I have time but nothing is making it work. The other strange thing is I had the same problem towards the beginning and then randomly it started working. Then after about a week I did a reboot and I haven't got it to work again since.

**Comment by nicolargo** [comment]
Nope. Nothing to do for the moment. I had to review the code with your data.
As a workaround you can disable the network plugin by adding --disable-plugin network to the command line.

I will have a look on the issue this weekend.

**Comment by tags147** [comment]
Thank you so much! And no rush. The only problem with that command is I can't access the webserver anymore. I'm trying to use glances for Homepage. But let me know what happens! Thank you again!!!!

**Comment by nicolargo** [comment]
Try this to disable the network plugin and start the Webserver:

```
glances -w --disable-plugin network
```

**Comment by tags147** [comment]
Yeah I've done that before. It won't work unless normal glances command works for some reason. That's also why I figured out was a network problem

**Comment by nicolargo** [comment]
@tags147  just publish a patch on the develop branch. Can you test it ?

**Comment by tags147** [comment]
@nicolargo YOU ARE THE BEST!!!!! It works now. Thank you so much!!!
