### ISSUE TITLE
Uptime for Docker containers not working

### ISSUE THREAD

**Issue by janreinhardt** [nicolargo/glances#3021]
**Check the bug**
this might relate to #2902, but Im not sure

**Describe the bug**
The uptime for Docker containers ist not working i.e. is wrong in the WebUI

**To Reproduce**
Start Glances as a Docker container; take a look at the WebUI

**Expected behavior**
See first screenshot

**Screenshots**
<img width="482" alt="Screenshot 2024-11-17 at 12 24 27" src="https://github.com/user-attachments/assets/c56e4c0b-092d-4bfe-96da-facd423d7fca">
Glances 4.1.2.1 = uptime correct

<img width="488" alt="Screenshot 2024-11-17 at 12 19 19" src="https://github.com/user-attachments/assets/bbf5a6e7-c761-4331-ad2f-91daab8c1f17">

Glances 4.2.1 = uptime does funny things, is frozen and never changes

**Environement (please complete the following information)**
 - Raspberry Pi OS latest version 64bit (headless) = Debian GNU/Linux 12 64bit / Linux 6.6.51+rpt-rpi-2712
 - Glances 4.2.1 
 - Docker container pulled from Docker hub

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment]
Sorry, you are right !

The issue as been introduced in the commit https://github.com/nicolargo/glances/commit/f6279baacd4cf0b27ca10df6dc01f091ea86a40a. I just revert it on the develop branch.

**Comment by nicolargo** [comment]
Just pushed the patch on the develop branch.

Will be release in next Glances version.

**Comment by janreinhardt** [comment]
Thank youuuu
