### ISSUE TITLE
test_105_network_plugin_method fails on aarch64-linux

### ISSUE THREAD

**Issue by gador** [nicolargo/glances#3040]
**Describe the bug**
When trying to compile the current glances version for `aarch64-linux` it fails. This happens since version `4.2.0`

**To Reproduce**

1. Compile `glances` version `4.2.0` from source for `aarch64-linux` 
2. See the error:

```
glances-aarch64-linux> ======================================================================
glances-aarch64-linux> ERROR: test_105_network_plugin_method (__main__.TestGlances.test_105_network_plugin_method)
glances-aarch64-linux> Test network plugin methods
glances-aarch64-linux> ----------------------------------------------------------------------
glances-aarch64-linux> Traceback (most recent call last):
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 720, in test_105_network_plugin_method
glances-aarch64-linux>     self._common_plugin_tests('network')
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 246, in _common_plugin_tests
glances-aarch64-linux>     first_history_field = self.chk_hist_maybe_add_third_elem(plugin_instance)
glances-aarch64-linux>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 200, in chk_hist_maybe_add_third_elem
glances-aarch64-linux>     first_history_field = self.get_first_history_field(plugin_instance)
glances-aarch64-linux>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
glances-aarch64-linux>   File "/build/source/unittest-core.py", line 182, in get_first_history_field
glances-aarch64-linux>     return first_history_field
glances-aarch64-linux>            ^^^^^^^^^^^^^^^^^^^
glances-aarch64-linux> UnboundLocalError: cannot access local variable 'first_history_field' where it is not associated with a value
glances-aarch64-linux>
glances-aarch64-linux> ----------------------------------------------------------------------
glances-aarch64-linux> Ran 37 tests in 8.678s
glances-aarch64-linux>
glances-aarch64-linux> FAILED (errors=1)

```

**Expected behavior**
All tests to pass

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `NixOS unstable 25.04`
 - Glances & psutil versions: `4.2.0`
 - How do you install Glances (Pypi package, script, package manager, source): `nix`
 - Glances test (only available with Glances 3.1.7 or higher): Unable

**Additional context**

For anyone to try on a nix-enabled system:
`nix build --system "aarch64-linux" github:nixos/nixpkgs/ccaf4694a0ea752e33d70942d9ee06a18c3da805#glances`

**Comment by nicolargo** [comment]
The PR https://github.com/nicolargo/glances/commit/98e8e32457dcf6129c8c6084e03675268ac20f9f breaks this test.
@ariel-anieli (
https://github.com/ariel-anieli) Can you have a look on it ?

**Comment by ariel-anieli** [comment]
> The PR [98e8e32](https://github.com/nicolargo/glances/commit/98e8e32457dcf6129c8c6084e03675268ac20f9f) breaks this test.
> 
> @ariel-anieli Can you have a look on it ?

Sure, @nicolargo.

@gador, for me to understand: you used this command; and got back the error you showed before. Is that right?
```
nix build --system "aarch64-linux" github:nixos/nixpkgs/ccaf4694a0ea752e33d70942d9ee06a18c3da805#glances
```

**Comment by gador** [comment]
> @gador, for me to understand: you used this command; and got back the error you showed before. Is that right?
> 
> ```
> 
> nix build --system "aarch64-linux" github:nixos/nixpkgs/ccaf4694a0ea752e33d70942d9ee06a18c3da805#glances
> 
> ```

Yes, correct. This just pins the commit I used and accounts for the system. I suspect the error will also show without using nix when compiling glances on aarch64-linux

**Comment by ariel-anieli** [comment]
@nicolargo, #3045 reverts 98e8e32457dcf6129c8c6084e03675268ac20f9f.
I will redo the refactor.

**Comment by ariel-anieli** [comment]
For me to have a reference, @gador: before that commit, the test passed. Is this right?
On my computer, after revert (which is also, before the commit I introduced), all tests are passing:
```shell
# make test-core | grep -P '^ok|^fail'
.....................................
----------------------------------------------------------------------
Ran 37 tests in 7.635s

OK
```

**Comment by gador** [comment]
@ariel-anieli yes, this fixes the issue (yay!) 

For anyone to try, this is my fork of nixpkgs from the above commit with the patch applied:
```bash
nix build --system "aarch64-linux" github:gador/nixpkgs/8923dfa16cff4e5436641c7b3bdbf94669a7157a#glances
```
(https://github.com/NixOS/nixpkgs/commit/8923dfa16cff4e5436641c7b3bdbf94669a7157a)

Thanks!
