### ISSUE TITLE
[WEBUI] Clear old alert messages in the WebUI

### ISSUE THREAD

**Issue by FS1961** [nicolargo/glances#3042]
### Discussed in https://github.com/nicolargo/glances/discussions/3041

<div type='discussions-op-text'>

<sup>Originally posted by **FS1961** December  7, 2024</sup>
I love this tool. It's been helpful identifying issues for me. However, when I reboot my system, Glances seems to find "old" alerts. How do I clear them? I'm just webbing into the port 61208. 

You can see the alerts are from Nov 7th. I am pressing 'h' for help, 'x' and 'w' appears to have no effect.

here is my docker config:

> `version: "3.9"
services:
  glances:
    container_name: Glances
    image: nicolargo/glances:latest
    healthcheck:
     test: curl -f http://localhost:61208/ || exit 1
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    pid: host
    privileged: true
    network_mode: host
    restart: on-failure:5
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: -w
      TZ: Europe/Berlin`

<img width="1552" alt="Screenshot 2024-12-07 at 12 27 01 PM" src="https://github.com/user-attachments/assets/e923ad68-c30b-4eb0-9f68-23998b7895f1">
</div>

**Comment by nicolargo** [comment]
Hi @FS1961 

unfortunatly it is not possible for the moment in the WebUI.

The only workaround is to restart your Glances container.

**Comment by FS1961** [comment]
Thanks for the response, but this doesn't work. I restarted the container. See below.
<img width="1543" alt="Screenshot 2024-12-09 at 11 19 44 AM" src="https://github.com/user-attachments/assets/54b660ea-3ecf-4f29-8394-d9955465160e">

**Comment by FS1961** [comment]
Sorry, maybe I'm confused? Is the critical warning/alert misformated and really 2024-11-12? So from today? Is this why I think they are older than they are?

<img width="1525" alt="Screenshot 2024-12-11 at 9 19 05 AM" src="https://github.com/user-attachments/assets/e4d5f973-4cc5-4020-b8dc-4445c038046f">

**Comment by FS1961** [comment]
I think I see part of the problem. - the Warnings are misformated. It is giving the wrong month.Please see this which is after a recent restart. Should be 2024-12-11 or Dec 12th however you want to format it.

<img width="1542" alt="Screenshot 2024-12-19 at 12 03 57 PM" src="https://github.com/user-attachments/assets/1fea7e71-9191-416e-a1d1-76713a4dd9c2" />

**Comment by nicolargo** [comment]
A new button has been added in the WebUI in order to clear the list (all the alert):

[Capture vidéo du 2024-12-22 19-16-48.webm](https://github.com/user-attachments/assets/20713d5a-5936-4128-83f1-3821c2684061)

Pushed on the develop branch.

Will be release in Glances 4.3.
