### ISSUE TITLE
Adapt process nice color according to definition

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#3050]
For the moment (Glances < 4.3), Glances display process nice level with the following color:
- not WARNING ==> COLOR_DEFAULT
- WARNING => COLOR_MAGENTA

WARNING can be defined in the Glances conf file (default WARNING: all but 0):

`nice_warning=-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19`

We want 3 level according to nice definition:

`NI -- Nice Value The nice value of the task. A negative nice value means higher priority, whereas a positive nice value means lower priority.Zero in this field simply means priority will not be adjusted in determining a task's dispatch-ability`

So:
- 0 ==> COLOR_DEFAULT
- lower than 0 ==> COLOR_BLUE
- higher than 0 ==> COLOR_MAGENTA

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the color assignment for process nice levels to use three levels: default for 0, blue for negative values, and magenta for positive values.

You can review changes in this commit: https://github.com/wwqwq2313/nicolargo-glances-3050/commit/f533669dfccf0e5871c8e557207e3cb76dbccbb2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by nicolargo** [comment]
Already done by conf
