### ISSUE TITLE
CONTAINERS section missing in 4.3.0 WebUI 

### ISSUE THREAD

**Issue by janreinhardt** [nicolargo/glances#3052]
**Describe the bug**
On iPad Air / latest iPad OS using Safari and also Firefox, the Glances 4.3.0 Docker container does not show the „Containers“ section in the right column of the WebUI anymore. TASKS is there, CONTAINERS is missing.
On iPhone (= single browser column) everything works fine.

**To Reproduce**
Fire up the nicolargo/glances:latest Docker container, use iPad Air to browse its output

**Screenshots**
![IMG_2021](https://github.com/user-attachments/assets/1fe6b015-1d17-45d5-97a7-9d3bb65dfba9)

**Comment by nicolargo** [comment]
It is not only on Air Pad but on all version, something was broken during the release. I will have a look asap.

Thanks for the head up @janreinhardt

**Comment by nicolargo** [comment]
Corrected in Glances 4.3.0.1 (build is ongoing).
