### ISSUE TITLE
WebUI errors in 4.3.0.4 on iPad Air (and Browser with low resolution)

### ISSUE THREAD

**Issue by janreinhardt** [nicolargo/glances#3057]
**Describe the bug**
So I am on Docker image nicolargo/glances:4.3.0.4 now. The CONTAINERS section is back, thank you!
But, depending on my Apple device, some other stuff is weird now.
Safari on iPhone 12: date + time is shown after the SENSORS section = everything is fine (screenie 1)
Safari on MacOS: everything fine (screenie 2)
Safari and also Firefox on iPad Air: date and time are missing. The ‚Name‘ column of the CONTAINERS section has got its width wrong (screenie 3) 

Unfortunately, that iPad Air is my main device, so Im looking at Glances with it most of the time… could you please look into this?

**To Reproduce**
get nicolargo/glances:latest image from hub.docker.com, fire up a container in -w mode

**Screenshots**
![IMG_2145](https://github.com/user-attachments/assets/dd2da51c-d9b1-4d91-9fd5-166184c4ba72)
![Screen Shot 2024-12-28 at 11 34 43 AM](https://github.com/user-attachments/assets/7e4d5d83-3048-474e-9464-996570087028)
![IMG_2022](https://github.com/user-attachments/assets/20d8e70b-3b78-4e9b-a874-1e2203981255)

**Comment by nicolargo** [comment]
Hi @janreinhardt 

the time plugin is now displayed on the top right (if space is available) and no more on the bottom left. I will have a look on that, it should be displayed on your IPad because space is available.

For containers name, it should not be displayed on multiple line.:

![Capture d’écran du 2024-12-28 13-28-04](https://github.com/user-attachments/assets/320ba831-6aa5-4210-b41d-55a115fdea4f)

Is it possible on the Ipad to hard refresh the page in order to make the CSS reloaded ? Perhaps, the CSS parameters is not taken into account on the Ipad Web browser...

**Comment by nicolargo** [comment]
Ok also reproduce on my side if there is "-" in the Docker name...

![image](https://github.com/user-attachments/assets/02a62708-9b34-4e05-bc78-8cf554dec6cc)

**Comment by janreinhardt** [comment]
> the time plugin is now displayed on the top right (if space is available) and no more on the bottom left.

Hmmm on my Mac Im running 4K resolution and there is lots of space in the browser window. time + date are **always** bottom left there, never top right.
(Not talking about „Uptime“ which is top right)

**Comment by janreinhardt** [comment]
> Is it possible on the Ipad to hard refresh the page in order to make the CSS reloaded ? Perhaps, the CSS parameters is not taken into account on the Ipad Web browser...

Ive done this before reporting here. I have quit and restarted the browser a few times, and Ive hit reload a dozen times to clear all browser caching and reload everything.

**Comment by nicolargo** [comment]
Glances 4.3.0.5 is ongoing, it should be available in few minutes, can you test it ? 

It should solve the container name issue and (perhaps) the current time.

Thanks @janreinhardt !

**Comment by janreinhardt** [comment]
yes I will test this! I feel happy to help 👍🏻

**Comment by janreinhardt** [comment]
Both issues are resolved!
Date + time are in the top row now. And container names dont get a line break anymore.
😎 thank you!
