### ISSUE TITLE
Add Load Average (similar to Linux) on Windows

### ISSUE THREAD

**Issue by t2y** [nicolargo/glances#344]
Windows doesn't have the load average value like Linux. However, we can measure Performance Counters to calculate it.

Observing Processor Queue Length
http://technet.microsoft.com/en-us/library/cc940375.aspx

the difference against Linux Load Average:
- The counter of Processor Queue Length is NOT included running processes
- The counter of Processor Queue Length is at the moment, so it must measure during 15-minutes to calculate the average

To implement this, we need 2 modules as a dependency as below.
- http://sourceforge.net/projects/pywin32/
- https://pypi.python.org/pypi/WMI/

I will implement this feature. What do you think?

Then, I know `develop` branch is for v2.0 and better pluggable architecture. So, I will add this feature to `develop` branch. When will you release v2.0?

**Comment by giampaolo** [comment]
@nicolargo since you know psutil do you think this should be integrated (in psutil)? I don't have time right now to look into how this works and I was wondering whether you did and whether you have an idea on what API this should have.

**Comment by nicolargo** [comment]
Hi @giampaolo , the main issue with the proposed implementation is the two dependencies: PyWin32 and WMI. 

I am not sure that it's a good idea to add such modules to the PsUtil Core. Is there others dependencies in the PsUtil ecosystem ?

**Comment by giampaolo** [comment]
Like any other Windows feature included in psutil my intention was to write this in C (hence no pywin32 nor WMI). But first we should figure out what information we can extract from the OS (in C), by using what (C) Windows syscall, and once we know that decide what to return (in terms of psutil / Python API), if possible by trying to mimick UNIX os.getloadavg() as much as possible.

**Comment by giampaolo** [comment]
@t2y:

> The counter of Processor Queue Length is at the moment, so it must measure during 15-minutes to calculate the average

Does this mean you have to wait 15 mins before getting any value?

**Comment by giampaolo** [comment]
Good news. This is now emulated on Windows and can be accessed via `psutil.getloadavg()` (on UNIX this just calls `os.getloadavg()`:
https://github.com/giampaolo/psutil/pull/1485

**Comment by nicolargo** [comment]
Implementation done in Glance.

Need PsUtil 5.6.1 or higher !

Thanks to @giampaolo and @ammaraskar

**Comment by giampaolo** [comment]
Actually it needs 5.6.2 which I didn’t release yet; and maybe i will call it 5.7.0 (still not sure) so you may want to hold on.

**Comment by nicolargo** [comment]
No problem. The code is compatible with old and future version of PsUtil.

Thanks @giampaolo

**Comment by bmxp** [comment]
A new release of psutil would be great and would ease the job to make our software also run on windows.
