### ISSUE TITLE
Add autodiscover & multiple servers support to the client mode 

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#418]
For the moment, Glances client can only hande one connection to a Glances server.

This feature will add the following features:
- Multi servers support: from the configuration file, user can define a list of Glances server to monitor, when Glances is started with  the --browser option, it will display a list of Glances server with minimal stats summary (CPU, LOAD and MEM...). When a server is selected (UP and DOWN keys + ENTER) then the 'classical' Glances curses interface will be displayed. When the ESC (or 'q')  key is pressed, Glances return to the servers list.
- Additionnaly to this first function (with static servers definition), an autodiscover function will be ran based on the ZeroConf implementation (https://github.com/jstasiak/python-zeroconf). All Glances servers availables in the user network will be displayed. The client autodiscover mode can be disable using the --disable-autodiscover option.

Note 0: the configuration file should be defined as following:

```
[serverlist]
server_1_name=host.domain.com
server_1_alias=My host
server_1_port=61208
```

alias is optionnal (default value is the server name)
port is optionnal (default value id 61209)

Note 1: server should be ran with a specific tag in order to be invisible (--disable-autodiscover).
Note 2: Web server mode should also enable the autodiscovery mode (another enhancement ?).
Note 3: the autodiscovered servers will be added to the statics list (defined in the Glances configuration file).
Note 4: if no server is defined in the configuration file,  only visible Glances servers of the LAN will be displayed in the list.

**Comment by xeon927** [comment]
Is there any way to specify a password for a particular server in the config file? I have a few servers I like to keep on top of, and am just generating a random one for each. If I try connect via the server browser, server specified and everything in the config, I get an error - checking the logs, it shows up: "-- ERROR -- Connection to server failed (bad password)"

Is there anything (say, server_x_pass or something?) that can be used to achieve this?
