### ISSUE TITLE
Enable alarm for the network plugin

### ISSUE THREAD

**Issue by Gamoth** [nicolargo/glances#437]
Bonjour,

J'utilise très régulièrement glances pour surveiller mon parc et je souhaitais vous remercier pour votre formidable outil.
Dernièrement, je souhaitais mettre en place une surveillance des débits réseaux sur ma machine.
J'ai donc modifié ma configuration comme suit (à des fins de tests) : 
 [network]
 hide=bond1
 # Default limits (in bits per second aka bps) for interface bitrate
 bond0_tx_careful=10000
 bond0_rx_careful=10000
 bond0_tx_warning=20000
 bond0_rx_warning=20000
 bond0_tx_critical=30000
 bond0_rx_critical=30000

Je constate bien le passage en rouge de mon interface quand celle ci est utilisée cependant aucune alarme n'est jamais logguée.

Ma configuration : Ubuntu 10 (64Bit), Glances v2.0.1 with psutil v2.1.1

Merci de votre réponse

**Comment by nicolargo** [comment]
To enable the alarm/log:

```
[network]
# Define the list of hidden network interfaces (comma separeted)
hide=lo
# WLAN0 Default limits (in bits per second aka bps) for interface bitrate
wlan0_rx_careful=4000000
wlan0_rx_warning=5000000
wlan0_rx_critical=6000000
wlan0_rx_log=True
wlan0_tx_careful=700000
wlan0_tx_warning=900000
wlan0_tx_critical=1000000
wlan0_tx_log=True
```

**Comment by nicolargo** [comment]
Done in the latest commit 7273343 (in the DEVELOP branch)
