### ISSUE TITLE
Allow logical mounts points in the FS plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#448]
"Is there a way to specify what mount points/directories display for FILE SYS?  I have a zpool mounted to /storage and I'd like to be able to see the space utilization on it within Glances.  Currently, only /, /boot, /home, and /app (a separate HDD I'm using for one of my applications) is on the list.  I poured through the documentation but couldn't find anything on it.  Thank you for your work on this program."

Ask by bartleyrx (forum: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/glances-users/aTvTskofIDk)

**Comment by nicolargo** [comment]
Testbed for ZSF:

```
$ sudo apt-get install zfs-fuse
$ dd if=/dev/zero of=~/tmp/zfs.img bs=1M count=100
$ sudo zpool create testzfs ~/tmp/zfs.img 
```

Will give:

```
$ sudo zpool status
  pool: testzfs
 state: ONLINE
 scrub: none requested
config:

	NAME                           STATE     READ WRITE CKSUM
	testzfs                        ONLINE       0     0     0
	  /home/nicolargo/tmp/zfs.img  ONLINE       0     0     0

errors: No known data errors
```

**Comment by nicolargo** [comment]
Done in the commit: 0003e0e

![selection_305](https://cloud.githubusercontent.com/assets/776747/6097381/8f4278f4-afbc-11e4-922d-08d893d0a515.png)

**Comment by VeloAddict** [comment]
How can I make this work when running glances from docker?
