### ISSUE TITLE
setup install conf in /usr/etc instead of /etc

### ISSUE THREAD

**Issue by Madko** [nicolargo/glances#471]
This is the extract of build.log on Fedora 22 chroot:
```
creating /builddir/build/BUILDROOT/glances-2.2.1-1.fc22.noarch/usr/etc
creating /builddir/build/BUILDROOT/glances-2.2.1-1.fc22.noarch/usr/etc/glances
copying conf/glances.conf -> /builddir/build/BUILDROOT/glances-2.2.1-1.fc22.noarch/usr/etc/glances
```

Don't know yet why it's now trying to use /usr/etc instead of /etc. It was working fine in 2.1.x

Full build log is here https://kojipkgs.fedoraproject.org//work/tasks/882/8510882/build.log

**Comment by Madko** [comment]
Found it!

```
--- setup.py.bak	2014-12-14 11:45:26.211000000 +0100
+++ setup.py	2014-12-14 11:46:00.963000000 +0100
@@ -15,7 +15,7 @@
         ('share/man/man1', ['man/glances.1'])
     ]
 
-    if os.name == 'posix' and os.getuid() == 0:  # Unix-like + root privileges
+    if os.name == 'posix':  # Unix-like + root privileges
         if 'bsd' in sys.platform:
             conf_path = os.path.join(sys.prefix, 'etc', 'glances')
         elif 'linux' in sys.platform:
```

Not sure it's a good idea to be root. Is it mandatory?

**Comment by nicolargo** [comment]
It is mandatory to create/write file in the /etc root folder.

@asergi can you have a look ?

**Comment by Madko** [comment]
Create files in /etc or root? why?
this is why there is such option as --root for setup.py ;)

**Comment by asergi** [comment]
This is because the package is built in chroot, so the uid is not 0.
Please test: https://gist.github.com/asergi/5259ad8c6c9d70204337

**Comment by Madko** [comment]
This patch works perfectly . Thanks. 
Complete build log is here : https://kojipkgs.fedoraproject.org//work/tasks/5/8520005/build.log

**Comment by asergi** [comment]
Travis-CI is not happy: https://travis-ci.org/nicolargo/glances/jobs/45870158

**Comment by asergi** [comment]
Travis-CI is happy again :-) https://travis-ci.org/nicolargo/glances/builds/45930740

**Comment by asergi** [comment]
Done. Patch applied in develop.

P.S. Python packaging is a mess.
