### ISSUE TITLE
New WebUI with AngularJS

### ISSUE THREAD

**Issue by sylvainmouquet** [nicolargo/glances#473]
Hi,

I have tested a reimplementation of the WebServer with angularjs (available on my glances fork)
Today glances_bottle generates the html content and sends it to the browser.
The refresh is managed by a full refresh of the html page.

With angularjs the approch is different, angularjs uses http REST for getting the content (the data, the model) and angularjs generates the view. It's a MVC framework. Model : model json, View : html, css3, Controller : angularjs
AngularJS has been created by Google and it's a very good and popular framework. It's compatible with frameworks like http://getbootstrap.com

My test is based only on the result of /api/2/all
The result of this url is a json which contains data but not display information (color)
I have not a full vision of the architecture of the project and i am wondering if the team in charge of this project could tell me if my solution is good (angularjs) and what is the best solution to adopt (add the display information in the url?, create another url ?, ...)

Thanks

**Comment by nicolargo** [comment]
Hi Sylvain !

It is a great enhancement proposal :)
I am sure that AngularJS is a good solution to have a dynamic and client side Glances's Web UI interface.

For the display information (color), you can use the limit get method (GET /api/2/:plugin/limits). See https://github.com/nicolargo/glances/wiki/The-Glances-RESTFULL-JSON-API. It will return the limit for the given plugin. Perhaps a new /api/2/all/limits (with all the plugins' limits in a single JSON reply) will be better for you ?

I think that the best way to process is to come closer to Maxime @desbma in order to mix the angular JS view and the refactoring based on BootStrap done in the DEVELOP branch. 

Nethertheless, if you need another method in the REST API or deeper information about the Glances architecture, you can contact me directly.

Nicolas

**Comment by desbma** [comment]
@nicolargo, I think you are mixing me up with @nclsHart who implemented the new web UI :)

**Comment by desbma** [comment]
Also, this may be an opportunity to solve issue #468.

**Comment by nclsHart** [comment]
:+1: 

Great idea :) ! Let me know if you need some help to implement it.

This enhancement could also fix #468 without any API changes (using a client side sorting).

**Comment by nicolargo** [comment]
@nclsHart @sylvainmouquet Any news ?

**Comment by sylvainmouquet** [comment]
@nicolargo 

Yes sorry i have gone lot of work this week.

The development is in progress. I have used urls /plugins and /plugins/:plugin/limit. For getting better performance, only one url like /plugins/all/limit would be better.

REFRESH TIME : The refresh time has been changed to a client value with 2 buttons (- and +)
It allows to the user to set this value. There is a bug with it i need some times to solve it.

CSS : the css has been changed. Currently the css used the id but it's better to use the class value. The difference between the id and the class values is the id is unique to one marker only in all the page and the class can be used for multiple markers. 

SORT : A sort has been added on all columns. It's possible to sort in ascending order and descending order

TIME COLUMN : I have had an error with the time column (more informations in a next post)

MOCK AND TEST : Currently i have not found a solution for testing and validating the new implementation. I am wondering if it is not possible to use an "abstraction" with the psutil framework ? Example in java : http://pastebin.com/Ssz4ysSP

I don't know how you would like organize the team. I can provide a pull request with my current development 

Sylvain

**Comment by nicolargo** [comment]
@sylvainmouquet Thanks for the feedback.

GET ALL METHOD: I can implement a /all/limit in the API (see: https://github.com/nicolargo/glances/issues/477)

TIME COLUMN: is it linked to https://github.com/nicolargo/glances/issues/453 ?

MOCK AND TEST: I do not think so...

ORGANISATION:  Best way to proceed is to create a specific branch for this issue.  We use the git flow workflow (http://danielkummer.github.io/git-flow-cheatsheet/ & https://github.com/nicolargo/glances/wiki/How-to-contribute-to-Glances-%3F) but you can manage it as you want. 

I plan to integrate this enhancement in the version 2.4 (next version will be the 2.3). 
It's a realy great and important enhancement so take your time ;)

**Comment by nclsHart** [comment]
Hi @sylvainmouquet,

> CSS : the css has been changed. Currently the css used the id but it's better to use the class value. The difference between the id and the class values is the id is unique to one marker only in all the page and the class can be used for multiple markers.

Be carefull, you are currently working on the master branch of Glances which is the production-ready branch. The latest version is available on the develop branch (It contains the new bootstrap UI).

> MOCK AND TEST : Currently i have not found a solution for testing and validating the new implementation. I am wondering if it is not possible to use an "abstraction" with the psutil framework ? Example in java : http://pastebin.com/Ssz4ysSP

I think the best solution is to mock $http. See https://docs.angularjs.org/api/ngMock/service/$httpBackend

> I don't know how you would like organize the team. I can provide a pull request with my current development

Great idea. Because at the moment I don't know what I can do to help you :disappointed:   

@nicolargo 

> I don't know how you would like organize the team. I can provide a pull request with my current development

What about open a https://gitter.im room for Glances ? This could enhance our collaboration on feature developpement like this one. 

> I plan to integrate this enhancement in the version 2.4 (next version will be the 2.3). 

:+1:

**Comment by nicolargo** [comment]
I just create an open chat room dedicated to the Glances project: https://gitter.im/nicolargo/glances?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by nicolargo** [comment]
@sylvainmouquet (AngularJS implementation) & @nclsHart (Web UI design ): My feedback for this first pull of the AngularJS feature:

* when the WebUI start, it display that processes are "sorted automatically by cpu_percent, flat view", but there is no sort (the automatic sort algorithm is implemented in the 'server' side, have a look on the get_sort_key function => https://github.com/nicolargo/glances/blob/feature/issue480/glances/core/glances_processes.py#L701)
*it's not easy to know that we should click on the CPU (or MEM...) to sort the processes list, Web UI refactor should be done
* how to return to the automatic sort (perhaps via a menu ?) 
* when you click twice to the CPU link sort is done UP to DOWN and DOWN to UP. Only the UP to down should be available (user do not have to scroll down to show the top process)
* the LOAD plugin is not displayed
* the SENSORS plugin is not displayed
* the CPU plugin only display short stats (no Nice, IRQ, IOWait and Steal stats)
* the MEMORY plugin only display short stats (no active, inactive, buffers or cached stats)
* in the NETWORK plugin, there is a '}' char at the end of the interfaces names
* the NETWORK plugin should (by default) display bitrate in bit per second, not byte per second
* the MONITORING list is not displayed 
* the refresh time button should be put in a menu (floating, content appear when you click on it) ( @nclsHart : any idea ?)
* CPU consumption look very high, perhaps we had to limit the number of processes displayed in the UI (only visible one). Another solution should be to add a new POST request in the API to set the sort key and the maximum number of processes to return.
* when you stop the Glances -w command, the Web UI is not refresh anymore but there is no message to warn the user (for example display the message on the header like that: https://github.com/nicolargo/glances/blob/master/docs/glances-doc.rst#header)
* is it possible in a WebUI to implement the same shortcut than the Curse interface (for example, click on `c` to sort by CPU...) ?

Nevertheless,  it is a nice first shot ! 

We can discuss on the Gitter if you have any question: https://gitter.im/nicolargo/glances

**Comment by nclsHart** [comment]
Current state of the feature : 

- [x] LOAD plugin
- [X] SENSORS plugin
- [x] CPU
- [x] MEMORY
- [x] send the refresh_time in the url
- [x] log for debug mode
- [x] remove refresh time
- [ ] The automatic sort
- [ ] NETWORK
- [ ] MONITORING
- [ ] shortcuts
- [ ] alert display
- [ ] network combination
- [ ] network cumulative
- [ ] Docker plugin
- [ ] RAID plugin
- [ ] quicklook plugin

**Comment by nicolargo** [comment]
Final status for the 2.4 release:
- [x] LOAD plugin
- [x] SENSORS plugin
- [x] CPU
- [x] MEMORY
- [x] send the refresh_time in the url
- [x] log for debug mode
- [x] remove refresh time
- [x] The automatic sort
- [x] NETWORK
- [x] MONITORING
- [x] shortcuts
- [x] alert display
- [ ] network combination
- [ ] network cumulative
- [x] Docker plugin
- [ ] RAID plugin
- [ ] Quicklook plugin
- [x] IP plugin
- [ ] Message when the server is offline
