### ISSUE TITLE
Request: Navigation with arrow keys (and kill function)

### ISSUE THREAD

**Issue by cblervacques** [nicolargo/glances#476]
Hi,

Glances is a very great tool but i think navigation in process list is missing for totally replace others tools like htop.
- Can you add a feature for navigate in the process list with the arrow keys ?
- And can you add a function for kill selected proccess with list of signal ?

Charly.

**Comment by nicolargo** [comment]
Glances aims at providing processes' quick view in order ti to found problems. By default, processes are sorted dynamicaly (by CPU time, memory, IO disk...). If the user navigate through the list and go down it, he will loose the ability to view the top processes.

One possible solution:
- user can scroll (up/down) through the process list, when he did this, the dynamic sort is disable
- after a timeout (no arrow keys pressed during the last X seconds), the dynamic sort is enable again and the cursor came back to the first process in the list

What do you think ?

**Comment by cblervacques** [comment]
Sorry for delay, I had not seen the message 

Yes it's a great solution ! 

But after timeout can you leave visible the last line selected and start as this point for the next scrolling ?

**Comment by Globegitter** [comment]
I think these two are great enhancements and could have used them both today :) Would love to see these making it in.

**Comment by wapiflapi** [comment]
Could we have horizontal scroll as well? Left/Right for when the terminal is to small to show the whole Command lines? I'm not sure if this should be the same issue.
