### ISSUE TITLE
Allow CORS on API 

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#479]
It could be interesting for third party application developpers to allow CORS.

I find this example of implementation with bottle : https://gist.github.com/richard-flosi/3789163.

**Comment by nicolargo** [comment]
Done: 8a51ba5
Can you test ? I do not realy understand the need...

**Comment by nclsHart** [comment]
Thanks @nicolargo. It works : 

```
HTTP/1.0 200 OK
Date: Sun, 11 Jan 2015 20:57:02 GMT
Server: WSGIServer/0.1 Python/2.7.3
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
Access-Control-Allow-Headers: Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token
Content-Length: 235
```

> I do not realy understand the need...

For example, this allow to develop Javascript dashboards that use Glances API without the need of a proxy API.

**Comment by instantdreams** [comment]
How can I enable CORS using this switch with Glances hosted in docker? I found no reference in the [configuration template](https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf) and this:
```yaml
environment:
      - GLANCES_OPT=--webserver --enable_cors --config /glances/conf/glances.conf
```
and this:
```yaml
environment:
      - GLANCES_OPT=--webserver --enable-cors --config /glances/conf/glances.conf
```

Do not work.

**Comment by instantdreams** [comment]
Ah never mind, I found out how to get past this using the built in Dashy proxy. :)
