### ISSUE TITLE
Bug: Crash my shell after no server detecting in browser mode.

### ISSUE THREAD

**Issue by cblervacques** [nicolargo/glances#482]
@cblervacques Please use the following procedure to report a bug: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#how-to-report-a-bug-

**Comment by nicolargo** [comment]
Not reproduce.

I start Glances in browser mode:

    glances --browser

No server are detected, the following mesage is displayed:

    No Glances servers available

**Comment by cblervacques** [comment]
Sorry i have send my post before completing it...
So,

After starting glances with --broswser and no server detected on quitting glances my shell crash..

See the screenshot : 

![noserveravailable](https://cloud.githubusercontent.com/assets/9450627/5760650/84e472ac-9cd6-11e4-9653-0a125887f7a4.PNG)

Trying typing cmd and crtl + c : 
![noserveravailable2](https://cloud.githubusercontent.com/assets/9450627/5760651/86315076-9cd6-11e4-8603-69e686c3f70d.PNG)

Trying clear cmd : 
![noserveravailable3](https://cloud.githubusercontent.com/assets/9450627/5760653/87942574-9cd6-11e4-8966-98ffc9672aaf.PNG)

I'm using glances in Debian Jessie .. 
Don't know solution for restore my shell after this. 
Just kill and restart..

I'm not understand why did that !?..

More info, i'm unsing Glances v2.3_BETA with psutil v2.1.3
and using on : Linux Jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux
with : Python 2.7.8

**Comment by nicolargo** [comment]
@cblervacques Thk for the complete bug report :)

First of all, to restore your shell, just type 'reset' + enter key and the terminal will be refreshed.

Can you start Glances in debug mode:

    glances --browser -d

and send us (via http://pastebin.com/) the /tmp/glances.log output log file ?

**Comment by cblervacques** [comment]
Thk for the command "reset", I did not know it

I had not followed the wiki instructions to test the branch "develop".
I had installed it on cloning git branche develop and use setup.py

I trying to reinstall with you method.

**Comment by cblervacques** [comment]
`glances --browser -d` :

> 2015-01-15 04:43:27,633 -- INFO -- Start Glances 2.3_BETA
> 2015-01-15 04:43:27,633 -- INFO -- CPython 2.7.8 and PSutil 2.1.3 detected
> 2015-01-15 04:43:27,636 -- INFO -- Read configuration file '/etc/glances/glances.conf'
> 2015-01-15 04:43:27,636 -- INFO -- Start client mode (browser)
> 2015-01-15 04:43:27,641 -- DEBUG -- Zeroconf version 0.16.0 detected.
> 2015-01-15 04:43:27,643 -- WARNING -- No [serverlist] section in the configuration file. Cannot$
> 2015-01-15 04:43:27,643 -- INFO -- Init autodiscover mode (Zeroconf protocol)
> 2015-01-15 04:43:29,057 -- DEBUG -- Keypressed (code: [10, -1])
> 2015-01-15 04:43:29,058 -- DEBUG -- Server number 1 selected

**Comment by cblervacques** [comment]
Hey !

Retrying testing of Glances (develop) with virtualenv and it's work fine !!
You can close this issue. :wink: 

I would test the new version of glances to collect metrics to influxdb in production environement.
Can I install this version instead of 2.2 ? With setup.py ? Or another way ?

**Comment by nicolargo** [comment]
You have a wiki page to install the DEVELOP branch without uninstalling the stable one.
https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by cblervacques** [comment]
Ok, thanks for reply.
