### ISSUE TITLE
Password support for multiple servers

### ISSUE THREAD

**Issue by xeon927** [nicolargo/glances#498]
I have noticed that the support for multiple servers will work, unless there is a password. When attempting to connect, it simply displays "-- ERROR -- Connection to server failed (bad password)".

Is there any way to have it either prompt for a password, or be able to specify a password in the glances.conf file (ie, server_*x*_password or something, where *x* is, of course, the server ID)? Or maybe both of these so that servers in config can be set, and then any that are autodiscovered can also still work?

**Comment by nicolargo** [comment]
Be aware that there is a bug with the latest Glances 2.2 (and behind) concerning the authentication.

Can you retry your test with client AND server in the same 2.3RC1 version ?

**Comment by xeon927** [comment]
Connection is working with the password and single server (with --client flag), as did previously. Maybe I didn't make myself hugely clear - that's my fault, sorry about that. What I'm meaning is through the server browser (--browser flag). There doesn't seem to be an option for configuring a password for individual servers in the config, or entering one at runtime.

From (very) quick checking, it seems that maybe a part could be added to glances/core/glances_staticlist.py, around L58. At its simplest, something to get a preconfigured password to allow connection to password-protected servers from the browser. Then maybe something for the runtime interface to prompt for any that are incorrect passwords or not configured for password.

But anyway, that's just my suggestion - I won't tell you what you should do - I'll leave that to you :P

**Comment by nicolargo** [comment]
In the current version, there is no option to configure the password in the configuration file, but if the Glances browser detect a Glances client protected by a password, it prompt for it in the UI.

Here is a simple test made with the Glances 2.3 RC (both client and server should be in 2.3 or higher version).

I ran the server with the --password and the client with the --browser option:

![selection_290](https://cloud.githubusercontent.com/assets/776747/5926052/66a68c44-a668-11e4-8ae9-d111cd30f678.png)

When i press enter, the Glances browser ask me for the Glances server password:

![selection_291](https://cloud.githubusercontent.com/assets/776747/5926051/66a36834-a668-11e4-8f28-185fb8e92aaf.png)

The server is now available.

![selection_292](https://cloud.githubusercontent.com/assets/776747/5926053/672f9782-a668-11e4-9590-a0a7f8c091fb.png)

Can you check it on your side ?

Nevertheless, i open another enhancement request issue to configure the password from the configuration file.

**Comment by xeon927** [comment]
Yep - it's all working here. One thing though, I noticed that passwords display as plaintext. Is this intended?
![screen shot 2015-01-29 at 1 08 58 pm](https://cloud.githubusercontent.com/assets/3516827/5951246/87b638e8-a7b8-11e4-954a-745612d8199c.png)

**Comment by nicolargo** [comment]
Next version will hide the password text *****
