### ISSUE TITLE
Grab FAN speed in the Glances sensors plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#501]
Asked by Jez Noake: "I have no doubt this has been asked before - can I get Glances to show FAN speeds?" in the Google groups https://groups.google.com/forum/#!topic/glances-users/JKE91aHHQkY

**Comment by nicolargo** [comment]
Had to change the __update__ method in the GlancesGrabSensors class (https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_sensors.py#L215).

**Comment by nicolargo** [comment]
Done.

Screenshot:
![selection_304](https://cloud.githubusercontent.com/assets/776747/6092831/fd7721ca-aef0-11e4-8f78-657b2fed77f3.png)

**Comment by jnoake** [comment]
BOOM!
@nicolargo  I'm blown away.

Thanks.

**Comment by archusr** [comment]
Thanks! On Arch this currently needs https://aur.archlinux.org/packages/python-py3sensors-hg/
