### ISSUE TITLE
glances ignores /etc/sensors.d

### ISSUE THREAD

**Issue by rmenessec** [nicolargo/glances#506]
I have some bogus - unconnected - thermistors on some of the systems I'm monitoring, so I wrote a few extra bits of configuration under /etc/sensors.d (Debian). glances ignores or doesn't use the extra config, so whereas sensors(1) is parsing and using lines like "ignore temp2", glances displays the bogus sensor reading.

It does respect the same settings if added to /etc/sensors3.conf.

**Comment by jasker5183** [comment]
I have tried adding the lines from the file I made in sensors.d to the sensors3.conf file and it made no difference, do I need to restart something? Already tried lm_sensors.service.

**Comment by Mirppc** [comment]
I ran into the same issue.  the only temps i get with glances on any of my distros and machines is the hard drive temps, and that is only some of the time or if there is a Hitachi drive installed.  I get nothing in the sensors panel for any other temperature monitors.

**Comment by nicolargo** [comment]
Could you try again with the latest Glances version (2.8.5) ?

**Comment by jasker5183** [comment]
Seems to ignore what is in /etc/sensors.d I'm looking at:

acpitz 1 - Think these might be ram
acpitz 2
Physical id 0 - system temp?
Core 0
Core 1

**Comment by Mirppc** [comment]
Tested on my workstation, and it seems to be reporting them all.  the command i used to upgrade was ># pip install glances -U

**Comment by nicolargo** [comment]
With Glances 2.8.3 and higher, it uses PsUtil to grab the sensors stats. I think that this error/enhancement should be reported to PsUtil (cc: @giampaolo).
