### ISSUE TITLE
glances portscan on loopback interface

### ISSUE THREAD

**Issue by Lompik** [nicolargo/glances#515]
Hi,

Everytime I start glances, it looks like it start to portscan all the ports above one by one on the loopback (lo) interface with orignating port 7634. I do not have hddtemp installed on my system. 
Results of `tcpdump -i lo` :

    23:56:01.332706 IP 127.0.0.1.34329 > 127.0.0.1.7634: Flags [S], seq 1239364664, win 43690, options [mss 65495,sackOK,TS val 400394 ecr 0,nop,wscale 7], length 0
    23:56:01.332725 IP 127.0.0.1.7634 > 127.0.0.1.34329: Flags [R.], seq 0, ack 1239364665, win 0, length 0
    23:56:01.333674 IP 127.0.0.1.34330 > 127.0.0.1.7634: Flags [S], seq 4208810321, win 43690, options [mss 65495,sackOK,TS val 400394 ecr 0,nop,wscale 7], length 0
    23:56:01.333685 IP 127.0.0.1.7634 > 127.0.0.1.34330: Flags [R.], seq 0, ack 4208810322, win 0, length 0
    23:56:04.451829 IP 127.0.0.1.34331 > 127.0.0.1.7634: Flags [S], seq 3005628434, win 43690, options [mss 65495,sackOK,TS val 401330 ecr 0,nop,wscale 7], length 0
    23:56:04.451846 IP 127.0.0.1.7634 > 127.0.0.1.34331: Flags [R.], seq 0, ack 3005628435, win 0, length 0
    23:56:04.452873 IP 127.0.0.1.34332 > 127.0.0.1.7634: Flags [S], seq 2605467854, win 43690, options [mss 65495,sackOK,TS val 401330 ecr 0,nop,wscale 7], length 0
    23:56:04.452886 IP 127.0.0.1.7634 > 127.0.0.1.34332: Flags [R.], seq 0, ack 2605467855, win 0, length 0

Any idea what going on ?

**Comment by nicolargo** [comment]
The TCP port 7634 is the default port for the HDDtemp server.
When Glances is started, it try, every x second to grab the HDD temerature by connecteing to the localhost:7634 port.
You can use the --disable-sensors to disable this behavor.

**Comment by Lompik** [comment]
Ok it makes sense. I mistakenly through 7634 was the  originating port from glances.

FYI, using `glances 2.3` and `--disable-sensors` does not disable the behavior which generate 1kb/s of harmless traffic on the loopback.

**Comment by nicolargo** [comment]
Ok, i let the issue open and i will enhance the feature by disabling the port request if the --disable-hddtemp is set.

**Comment by Lompik** [comment]
Thanks !
Thinking about it, if `hddtemp` is an optional dependency, it makes more sense to have the  option to enable it rather than disable it, doesn't it ? Or you could have hddtemp as requirement.
I guess the best is to check if hddtemp is running before opening the socket connection.

**Comment by nicolargo** [comment]
Nope, i want to keep Glances simple.

I just push a patch for the current issue:

* a new --disable-hdd option for the command line
* when Glances detect a connection error on the HDDTemp port, it will not retry anymore
