### ISSUE TITLE
Add tags support for the influxdb export module

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#516]
InfluxDB version 0.9 introduces a new featue: support of tags: http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html

It should be nice to allow Glances users to define tags inside the configuration file.

Example:

```
[influxdb]
host=localhost
port=8086
user=root
password=root
db=glances
tag_host=localhost
tag_titi=toto
```

Will define 2 tags (host and titi).

**Comment by emidln** [comment]
I didn't actually see this before, but I added support via a tags parameter in the form of 

```
[influxdb]
tags=host:localhost,titi:toto
```

as part of the InfluxDB 0.9.x PR #630. Unless you want the refactor the tags support to this format, I think we could close this issue.

**Comment by nicolargo** [comment]
Ok.
Also done for the OpenTSDB export module.
Thk for the contrib.
