### ISSUE TITLE
CRITICAL: InfluxDB database did not exist

### ISSUE THREAD

**Issue by BarthV** [nicolargo/glances#518]
Building from dev branch : 
* Ubuntu 14.04.2
* commit 929b832b74ba874d4add74c6478fafab859db998
* Python 2.7.6 (in a venv)
* pip 6.0.8
* InfluxDB 0.8.6

The same error occurs when building from v2.3 tag

```bash
> .venv/bin/pip install -r requirements.txt
> .venv/bin/pip install influxdb #needed since influxdb lib is not in the requierements
> .venv/bin/python setup.py install
[...]
Installed .venv/lib/python2.7/site-packages/Glances-2.4b0-py2.7.egg
Processing dependencies for Glances==2.4b0
Searching for psutil==2.2.1
Best match: psutil 2.2.1
Adding psutil 2.2.1 to easy-install.pth file

Using .venv/lib/python2.7/site-packages
Finished processing dependencies for Glances==2.4b0
```

```bash
> .venv/bin/glances --export-influxdb -C influx.conf
.venv/local/lib/python2.7/site-packages/influxdb/client.py:451: FutureWarning: get_database_list is deprecated, and will be removed in future versions. Please use ``InfluxDBClient.get_list_database`` instead.
  FutureWarning)
CRITICAL: InfluxDB database 'glances' did not exist. Please create it
```

BUT : my db exists :'(
```bash
> influxdb-cli -h dev.influx.acme.org -u root -p root -d glances --pretty
glances> Connecting to http://dev.influx.acme.org:8086/db/glances ...
glances> ✔ ready
glances> list series
┌─────────────────┬─────────────────┬──────┐
│       time      │ sequence_number │ name │
└─────────────────┴─────────────────┴──────┘
Query took  2 ms
```

my influx.conf file :
```
[influxdb]
host=dev.influx.acme.org
port=8086
user=root
password=root
db=glances
```

**Comment by BarthV** [comment]
Maybe glances is only compatible with Influx 0.9+ ?

**Comment by nicolargo** [comment]
Works like a charm on my configuration:
- InfluxDB v0.8.7 (git: a0fd0cd) (leveldb: 1.15)
- influxdb-python 0.3.1

Can you start Glances with the -d (debug) option and have a look into the /tmp/glances.log file ?

**Comment by tomochikahara** [comment]
@BarthV 
I had same issue as yours but I fixed it in my case.
I hope that this helps you.

Run the below and confirm to display databases all.

```
$ curl 'http://dev.influx.acme.org:8086/db?u=root&p=root'
```
If you could NOT see any of your databases in console, you might need to give a **cluster admin** or **database admin** permission to `root` user.
To use [InfluxDBClient#get_database_list] (https://github.com/nicolargo/glances/blob/ea1bb83b61c89b94d65db29e4e3f284329ac8404/glances/exports/glances_influxdb.py#L83) in `export-influxdb` need the admin permissions.
(but it is still strange. the `root` user already has had the admin permissions in default...)

By the way, I suppose that the `export-influxdb` should not need the admin permissions on security grounds.

**Comment by asergi** [comment]
No issue here.

- InfluxDB v0.8.8 (stable)
- influxdb-python 0.3.1

**Comment by BarthV** [comment]
I'll test it back and check if there is some permission issues here as reported by @tomochikahara.

Thanks for your tests and comments

**Comment by nicolargo** [comment]
@BarthV any head up ?
