### ISSUE TITLE
Relatively high CPU usage

### ISSUE THREAD

**Issue by aaronjwood** [nicolargo/glances#519]
This might be a low priority issue but is there any way that  the CPU usage of glances can be cut down? It's not usually an issue for me since, at most, it seems to take between 10% and 20% CPU across differing hardware but fluctuates every few seconds and usually drops a bit lower. The only times where I see this to be more of a problem is when I'm monitoring servers that are under very high loads.

For example, lets say I'm looking at a server with 40 cores, 128 GB RAM, and 4 SSDs in a RAID setup. This server is hit incredibly hard because it's sole purpose is to host a RDBMS. It would be nice to not have glances suck up as much CPU as it does now so there's more available to the RDBMS that really needs it.

I should note that I'm always running glances with the system default python which is 2.x (I'm either using it on RHEL, CentOS 6/7, or some version of Ubuntu Server). Is there a noticeable improvement when using this with Python 3.x instead of 2.x?

**Comment by nicolargo** [comment]
Hi @aaronjwood 

I do not think that the CPU usage will be reduce by using Python 3. The main consumption came from the PSUtil lib. An optimization was already done in the version 2.1.1: https://github.com/nicolargo/glances/issues/401

As a workaround you can reduce the refresh time using the -t command line option. For example, on my server, is use to set the refresh time to 15 seconds.

**Comment by aaronjwood** [comment]
Hi there. Thanks for the info! Too bad that psutil is so heavy. I'll reduce the refresh time, that should work well enough for me!

**Comment by jrenner** [comment]
If you need general system info and not specific process information, you can press 'z' to disable process, or start with `--disable-process` from the command line and you will see CPU usage reduced by something like 90%

**Comment by nicolargo** [comment]
For information, the next PsUtil release will implement a new oneshot function (used by default through the as_dict process method) to speed up process' stats grab. See https://github.com/giampaolo/psutil/issues/799
