### ISSUE TITLE
Web Server Mode: theme issue

### ISSUE THREAD

**Issue by k0nsl** [nicolargo/glances#525]
Hi,

What happened with the "theme" for when Glances is run in web server mode? It appears to have been changed and currently looks like this for me after upgrading to the latest version:

![glances-boring-theme01_k0nsl](https://cloud.githubusercontent.com/assets/2517921/6614346/4f2e5698-c899-11e4-95ac-fa511f81acd2.png)

As a comparison, the one on the Glances documentation page was a far better theme, for example:

![glances-web-nice01_k0nsl](https://cloud.githubusercontent.com/assets/2517921/6614356/7650ce7c-c899-11e4-89b2-a237caf23134.png)

Perhaps I am just missing something, but can one switch to this theme somehow, or do I have to downgrade to another version?

Thanks in advance and keep up the excellent work on this fine project.

**Comment by nicolargo** [comment]
Hi,

what is your Glances' version ?
How do you install it on your system ?

It look like you do not have the CSS file.

Nicolas

**Comment by k0nsl** [comment]
Hi,
It's version 2.3 (with psutil v2.2.1); installed via pip. At any rate, I forgot to submit and close the issue as it was a caching issue on CloudFlare's end. It now looks the way it should :)

Sorry for the inconvenience.

**Comment by nicolargo** [comment]
Ok, no problem.
Thk for the message.
