### ISSUE TITLE
Feature Request: sort processes by user

### ISSUE THREAD

**Issue by jrenner** [nicolargo/glances#531]

**Comment by asergi** [comment]
Please test: https://gist.github.com/asergi/219f6607b6d68e3350ef

To sort processes by user, just hit the 'u' key.
This means the cumulative network I/O stats are accessible now via the 'U' (capital U) key.

Any comment or contribution is welcome.

**Comment by nicolargo** [comment]
Hi Alessio,

works like a charm on my PC. Ok to pull the patch on the develop branch.

Nice end of  week-end.
 
Nicolas

**Comment by asergi** [comment]
Done https://github.com/nicolargo/glances/commit/4f2e051b05484517ba55926ee98b7e8593360141.
