### ISSUE TITLE
/etc/glances (non root install)

### ISSUE THREAD

**Issue by ink1** [nicolargo/glances#541]
Hi, I just wanted to try Glances but the installer wants to create /etc/glances. Does the configuration have to be there? If it is really necessary, can it be local (e.g. $HOME/.glances)?
Thanks

**Comment by ink1** [comment]
To recap the problem: when installing Glances as non-root into a custom location the installation breaks with an error: "error: could not create '/etc/glances': Permission denied"

The problem stems from chroot detection in setup.py. The server in question has an NFS mount as root "/" so os.stat('/').st_ino does not give 2 hence assuming chroot environment. Therefore the chroot detection is at fault.
```
is_chroot = os.stat('/').st_ino != 2
```
A simple fix is something like
```
27c27
<             conf_path = os.path.join(os.environ['HOME'], 'glances')
---
>             conf_path = os.path.join('/etc', 'glances')
```
and then running Glances with --config CONF_FILE but this by no means is a proper fix.

**Comment by asergi** [comment]
Since I got fed up with this type of issues (see also #471 and #383) and since I don't want to deal with them anymore, I took the plunge to fix the problem once and for all (I hope so).

So, no system-wide configuration file will be provided anymore. See `glances-doc.html` for more information.

Thanks for your understanding.

**Comment by nicolargo** [comment]
Completely agree with you @asergi 

Do you think that it is possible to display a message at the end of the installation process in order to warn the user that they had to copy the glances.conf file in one of the available directory ?

**Comment by asergi** [comment]
I dunno. I think that is a job of the packager to inform the user of the change with a proper post-install message.
