### ISSUE TITLE
glances --tree hangs on FreeBSD/OS X

### ISSUE THREAD

**Issue by lxsndl** [nicolargo/glances#542]
Calling glances --tree on OSX (10.10.3) keeps hanging (does not show anything) until you interrupt it via ctrl+c
The regular glances call works flawlessly.

```
% python --version
Python 2.7.9
% glances --version
Glances v2.3 with psutil v2.2.1
```

Can anyone reproduce this or direct me to a fix?
TIA

**Comment by nicolargo** [comment]
@desbma can you have a look on it ?

**Comment by froz** [comment]
Same thing happens with --enable-history.

File "/usr/local/lib/python2.7/site-packages/glances/__init__.py", line 72, in end
standalone.end()
NameError: global name 'standalone' is not defined

**Comment by desbma** [comment]
I could not reproduce with Python 2.7 or 3.4, master or develop branch with psutil version 2.1.3, 2.2.0 or 2.2.1.

**Comment by desbma** [comment]
Can not reproduce either with matplotlib installed, and with :
* `--tree`
* `--tree --enable-history`
* `--enable-history`

It is most likely Mac specific.

**Comment by asergi** [comment]
I can confirm this bug as well on FreeBSD.

**Comment by asergi** [comment]
I can confirm this bug as well on FreeBSD.
Glances is unsable using the `--tree` option.

@froz please open another issue for that, if it's really a different thing.

**Comment by nicolargo** [comment]
@asergi can you send us the output error on your FreeBSD OS ?

**Comment by asergi** [comment]
Here's the traceback: https://gist.github.com/asergi/f3af561f480712da716e
(FreeBSD 10.1-R, glances develop, python 2.7.9, psutil 2.2.1)

**Comment by nicolargo** [comment]
@desbma Can you have a look on the @asergi traceback ?

**Comment by desbma** [comment]
All I can say is the obvious: there is an infinite loop in `ProcessTreeNode.build_tree` that does not occur on Linux or Windows, but only on FreeBSD or OSX (both BSD derivatives).

Unfortunately I don't have a FreeBSD or OSX system to investigate any further, and I don't want to make random changes in the blind...

**Comment by asergi** [comment]
The '--tree' option has been disabled for now on non-Linux platforms.

Waiting for better times.

**Comment by desbma** [comment]
It worked fine on Windows too last time I tested it, only BSD (or derivatives) are affected by this bug.

**Comment by mapio** [comment]
@asergi I'm perfectly fine with disabling `--tree`, but I think it should be mentioned in the docs.

**Comment by nicolargo** [comment]
--tree as been removed from the master branch.
