### ISSUE TITLE
Glances display of time trims the hours showing only minutes and seconds

### ISSUE THREAD

**Issue by felipeam86** [nicolargo/glances#543]
I'm using glances v2.3 with psutil v2.2.1. I have some long running processes that take more than 1 hour. When they go beyond the hour, htop or top correctly show they have been running for 1hxxm.. but glances trims the hours and shows only the minutes and seconds

**Comment by nicolargo** [comment]
Glances display the TIME+ column with the HH:MM:SS format.

For example, in the following screenshot, the spotify process is running since 49h 56m 14sec:

![capture d ecran de 2015-04-16 14 05 22](https://cloud.githubusercontent.com/assets/776747/7180410/d4dacb78-e441-11e4-948e-e92826c7e26a.png)

**Comment by felipeam86** [comment]
Take a look at the example below. You can see that for the first process, glances (top) displays 6:59.10 whereas htop (bottom) displays 1h07:02

![glances](https://cloud.githubusercontent.com/assets/5644836/7226914/1198f090-e74d-11e4-8539-09d2a3b4b8a0.png)

**Comment by nicolargo** [comment]
I will have a loo and keep you inform.
Thks for the feedback.

**Comment by asergi** [comment]
Actually, we display CPU times as mm:ss.ms only. If you agree, I could work on this.

**Comment by asergi** [comment]
First 'quick' draft:
![cpu_times_hours](https://cloud.githubusercontent.com/assets/325166/7228750/a7208ca4-e75c-11e4-8fbf-1409bcae38c4.png)

**Comment by nicolargo** [comment]
Nice Alessio !

**Comment by asergi** [comment]
Done https://github.com/nicolargo/glances/commit/e446d380a1c0b84577f5a2d20f8e9ee6dc371274.
