### ISSUE TITLE
Wrong CPU% on Docker

### ISSUE THREAD

**Issue by florianbeer** [nicolargo/glances#548]
I have installed glances via `curl -L http://bit.ly/glances | /bin/bash` on Ubuntu 14.04 64bit / Linux 3.13.0-49-generic and get the following odd behaviour on a Docker instance I have running on that host.

![screen shot 2015-04-27 at 20 55 11](https://cloud.githubusercontent.com/assets/800047/7355093/fbe5a4ae-ed1f-11e4-8081-4dc7afbbff39.png)

**Comment by nicolargo** [comment]
Hi. Thk for the report.

The next Glances release will change the way to compute the Docker CPU usage.
You can try the develop branch and check if it solve the issue: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by florianbeer** [comment]
It's not that important to me, the host CPU% is what I mainly watch anyway.
I will upgrade to the new glances version when it comes out.

Thanks for your reply and an awesome app that found its way into my arsenal instantly!
