### ISSUE TITLE
Easier module integration

### ISSUE THREAD

**Issue by lefred** [nicolargo/glances#549]
It would be nice to have something more generic to load modules. I mean instead of modifying glances_curses.py to populate a new global variable for the stats and display the window.

It would be cool if just the plugin will be enough for everything (key binding, help, etc..)

**Comment by nicolargo** [comment]
Interesting...

Agree with you to integrate key binding and help message directly in the Glances' plugins scripts.

Nevertheless, it is difficult to dynamically change the Curses (and also Web interface). I want to keep Glances easy to use and the UX is designed to display relevant informations. If a new plugin is created, where will be added in the UI ?
