### ISSUE TITLE
[Web UI] New feature in the AngularJS Web interface

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#552]
- [x] network combination
- [x] network cumulative
- [x] RAID plugin
- [x] Quicklook plugin
- [x] Message when the server is offline
- [ ] Processes filter => See https://github.com/nicolargo/glances/issues/691

**Comment by nclsHart** [comment]
Could we add the process filter feature which is also missing ?

**Comment by notFloran** [comment]
Hi @nicolargo , I don't have a machine with RAID. Can you send me the response returned by the RAID plugin API  ?

**Comment by nicolargo** [comment]
@notFloran Here it is some sample (output from the curse Interface + RESTFUL API):

![selection_378](https://cloud.githubusercontent.com/assets/776747/9427748/389446ac-498d-11e5-9ff4-dbe7ae0e047a.png)

{"md_d0": {"status": "active", "available": "5", "used": "5", "components": {"sdc1": "1", "sdb1": "5", "sde1": "0", "sdd1": "2", "sdf1": "4"}, "config": "UUUUU", "type": "raid5"}}

![selection_379](https://cloud.githubusercontent.com/assets/776747/9427754/593a2f48-498d-11e5-9c69-3153cc20ed3e.png)

{"md0": {"status": "active", "available": "4", "used": "3", "components": {"sdb1": "1", "sdd1": "2", "sda1": "0"}, "config": "UUU_", "type": "raid5"}}

![selection_380](https://cloud.githubusercontent.com/assets/776747/9427757/7e76ce10-498d-11e5-9cf7-683805f37fb9.png)

{"md2": {"status": "active", "available": "2", "used": "2", "components": {"sdb3": "1", "sda3": "0"}, "config": "UU", "type": "raid1"}, "md3": {"status": "active", "available": "10", "used": "10", "components": {"sdk1": "8", "sdj1": "7", "sde1": "2", "sdl1": "9", "sdg1": "4", "sdf1": "3", "sdh1": "5", "sdc1": "0", "sdd1": "1", "sdi1": "6"}, "config": "UUUUUUUUUU", "type": "raid5"}, "md0": {"status": "active", "available": "2", "used": "2", "components": {"sdb1": "1", "sda1": "0"}, "config": "UU", "type": "raid1"}, "md1": {"status": "active", "available": "2", "used": "2", "components": {"sdb2": "1", "sda2": "0"}, "config": "UU", "type": "raid1"}}

![selection_381](https://cloud.githubusercontent.com/assets/776747/9427761/a2b7d0d0-498d-11e5-91cc-7d37d5a0cab2.png)

{"md127": {"status": "active", "available": "6", "used": "5", "components": {"sde1": "2", "sdg1": "4", "sdf1": "3", "sdh1": "6", "sdc1": "0", "sdd1": "1"}, "config": "UUUUU_", "type": "raid5"}}

![selection_382](https://cloud.githubusercontent.com/assets/776747/9427763/c94b4d76-498d-11e5-9501-525c5b05230c.png)

{"md0": {"status": "active", "available": "7", "used": "7", "components": {"sde1": "1", "sdf1": "0", "sdc1": "3", "sdb1": "4", "hdb1": "6", "sdd1": "2", "sda1": "5"}, "config": "UUUUUUU", "type": "raid6"}}

![selection_383](https://cloud.githubusercontent.com/assets/776747/9427768/e964b138-498d-11e5-9e56-02b110390f36.png)

{"md1": {"status": "active", "available": "6", "used": "4", "components": {"sdc1": "2", "sdb1": "4", "sde1": "6", "sdd1": "3", "sdg1": "1"}, "config": "_UUUU_", "type": "raid1"}}

![selection_384](https://cloud.githubusercontent.com/assets/776747/9427770/22b5a53c-498e-11e5-8ebf-db6147f30772.png)

{"md0": {"status": "inactive", "available": "4", "used": "4", "components": {"sdc1": "2", "sdd1": "3", "sda1": "0"}, "config": "UUUU", "type": "raid5"}}

![selection_385](https://cloud.githubusercontent.com/assets/776747/9427775/42539926-498e-11e5-8d98-25c4ccff1699.png)

{"md2": {"status": "inactive", "available": null, "used": null, "components": {"sdb": "0"}, "config": null, "type": null}, "md0": {"status": "active", "available": "2", "used": "2", "components": {"sde1": "0", "sdf1": "1"}, "config": "UU", "type": "raid1"}, "md1": {"status": "active", "available": "2", "used": "2", "components": {"sde2": "0", "sdf2": "1"}, "config": "UU", "type": "raid1"}}

**Comment by notFloran** [comment]
I made a PR for the raid plugin #676

**Comment by nicolargo** [comment]
Process filter will be postpone in the next release.
