### ISSUE TITLE
[Web UI] Help page not responsive

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#553]
The help page has a strange behaviour on small devices : 

![glances-help](https://cloud.githubusercontent.com/assets/833625/7461242/1e5f0316-f2a9-11e4-9b08-dcfc38e918c1.png)

**Comment by nicolargo** [comment]
@nclsHart : there is also some non existing shortcut: 'T' for exemple is not implemented. But 't' exist.

**Comment by nclsHart** [comment]
Fixed by #642. 

For the shortcut problem, it'll be fixed by #554.
