### ISSUE TITLE
[Web UI] Cpu and mem additional data are displayed on small devices

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#556]
On small devices : 

![glances-responsive](https://cloud.githubusercontent.com/assets/833625/7463184/913edb6e-f2b7-11e4-9822-f7a15fd200fd.png)

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/c0f473df13e56c1708f8ab8eaabe286a2360709a
