### ISSUE TITLE
[Web UI] Wrong unit

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#560]
Glances 2.4RC1

The web UI and the curses interface show different value for the same thing.

Example with swap total size : 

- curse interface : 2.00G
- web UI : 2.15GB

Curse interface  :
![capture d ecran 2015-05-06 a 13 05 42](https://cloud.githubusercontent.com/assets/523981/7492145/112b025a-f3f1-11e4-9e1b-e5c6e230c91a.png)

Web UI : 
![capture d ecran 2015-05-06 a 13 05 50](https://cloud.githubusercontent.com/assets/523981/7492144/1128343a-f3f1-11e4-9889-f0f0dd8ede0d.png)

In cuse interface 1K = 1024
In web UI 1K = 1000

**Comment by nclsHart** [comment]
I suspected a conversion issue but I was not able to prove it. The issue come from the filters ?

**Comment by nicolargo** [comment]
Yes, it is a conversion issue.

The curse interface uses the classical byte to kilobyte conversion factor => * 1024
The Web UI uses => * 1000

The Web UI should use the 1024 factor.

**Comment by nclsHart** [comment]
I think @notFloran has already started a patch for this issue. Can you confirm @notFloran ?

**Comment by notFloran** [comment]
Yes, I started a branch to fix that https://github.com/notFloran/glances/tree/web-ui-fix-unit

**Comment by nicolargo** [comment]
Ok ! Perfect ;)

**Comment by asergi** [comment]
Other issues:
- irq, iowait, steal, buffers and cached shouldn't be displayed on OS X
- load values are not rounded

**Comment by nicolargo** [comment]
Fixed
