### ISSUE TITLE
[Web UI] Problem with long message in the monitoring list plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#561]
Glances 2.4RC1

With a long message:

```
[monitor]
...
list_3_description=Test
llist_3_regex=^python.*
list_3_command=echo "A very long message... A very long message... A very long message... A very long message... A very long message..." 
```

The Web UI display:

![selection_349](https://cloud.githubusercontent.com/assets/776747/7498439/17c95afa-f421-11e4-9a5b-e12c8f4ba09b.png)

The message had the 'splittable' tag. So the message can be cutted if needed.

@nclsHart : Any idea to solve this issue ? (not necessary for the 2.4 release)

**Comment by nclsHart** [comment]
The problem is more global because the web UI is not currently using the view endpoint. I'll add an issue for that.

For the splittable case we should try to do it using css in order to be as responsive as possible.
