### ISSUE TITLE
[Web UI] Wrong system info

### ISSUE THREAD

**Issue by asergi** [nicolargo/glances#570]
![bad-system-info](https://cloud.githubusercontent.com/assets/325166/7510043/6d3882dc-f498-11e4-811b-1f5ba4ada0e7.png)

System info format is hard coded (Linux-only).

Also, IP plugin is always displayed even when netifaces is not installed.

**Comment by nicolargo** [comment]
@asergi Can you test and close the issue if it is ok for you ?

**Comment by asergi** [comment]
Fixed with commit https://github.com/nicolargo/glances/commit/de0dc0c25c73c8e09c5a8502eb0e019429b55261.
