### ISSUE TITLE
[Web UI] Regressionwith the CPU plugin: IOWait, IRQ, Steal do not displayed anymore

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#577]
The additional CPU information are not displayed anymore in the Web UI if the value is 0.0:

![capture du 2015-05-07 14 13 05](https://cloud.githubusercontent.com/assets/776747/7515044/9768dc02-f4c3-11e4-8a23-930bf69915d1.png)

Same monitoring on the Curse interfaces:

![capture du 2015-05-07 14 16 35](https://cloud.githubusercontent.com/assets/776747/7515056/b013acb4-f4c3-11e4-81de-b23128d7922c.png)

**Comment by notFloran** [comment]
I think is my fault (PR #575), I will look at that.

**Comment by nicolargo** [comment]
Ok @notFloran ;)

**Comment by nicolargo** [comment]
Fixed !
