### ISSUE TITLE
Export not working with InfluxDB 0.8

### ISSUE THREAD

**Issue by webworxshop** [nicolargo/glances#579]
Out of the box the InfluxDB export does not work (at least with 0.8 and the latest version of python-influxdb). This appears to be due to a problem/change in the return value of get_database_list, which is now deprecated.

I am submitting a pull request which works for me, however it will probably now only work with 0.8 as I imported the influxdb08 module.

**Comment by nicolargo** [comment]
Fixed. Thk for the pull.
I will patch the plugin as soon as the stable version of InfluxDB 0.9 will be released

**Comment by webworxshop** [comment]
Awesome, thanks.
