### ISSUE TITLE
[Web UI] Sidebar display problem

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#586]
With the latest commit (Glances 2.4 RC2)

* Used and Total are bring closer
* Battery: 96 % should be displayed in green (it is perhaps a AGYR API issue...)

![selection_358](https://cloud.githubusercontent.com/assets/776747/7536149/60e08fca-f58d-11e4-8d20-40ebde5a601e.png)

**Comment by nclsHart** [comment]
I take this one. 

I'll also fix the unit issue for the battery value.
