### ISSUE TITLE
[Web UI] Load should take core number into account

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#587]
The load limit depends of the number of Core.
https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_load.py#L127

Web UI:
![selection_359](https://cloud.githubusercontent.com/assets/776747/7536322/25ede41a-f58f-11e4-95e8-e273161843c3.png)

Curses:
![selection_360](https://cloud.githubusercontent.com/assets/776747/7536323/293c2d2a-f58f-11e4-8c4b-fd217db4dd8a.png)

**Comment by notFloran** [comment]
I will look at that.

**Comment by nicolargo** [comment]
@notFloran / @nclsHart / @asergi : I am back from Ireland. Thanks for the amazing job done on the 2.4 release during my vacation. Glances 2.4 has never been so close to the final release !
