### ISSUE TITLE
Load values are not displayed in curse on OSX

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#589]
With the latest commit (Glances 2.4 RC2)

* Load values are not displayed in curse on OSX

With Glances 2.3 no problems.

Glances 2.4 RC2 : 
![capture d ecran 2015-05-08 a 16 31 38](https://cloud.githubusercontent.com/assets/523981/7538382/bc8cb1c0-f59f-11e4-8964-2c6f1c5a1528.png)

Glances 2.3 : 
![capture d ecran 2015-05-08 a 16 32 08](https://cloud.githubusercontent.com/assets/523981/7538387/cdf1c9be-f59f-11e4-9ade-fa658962199e.png)

**Comment by asergi** [comment]
If you press '3' the load values are being displayed instead?
At first glance, I guess that is more an issue of the quick look plugin.
In fact, the MEM bar is not being displayed at all.

**Comment by notFloran** [comment]
If I press '3" : no problem

**Comment by asergi** [comment]
I am not able to reproduce on Linux and I don't have OS X to test.

The quick look plugin was displayed correctly in the screenshot you attached in # 560.
Could you try with commit https://github.com/nicolargo/glances/commit/9798fb41ca87b1545b3fec0f8425afc5b4baf122 reverted please?

**Comment by notFloran** [comment]
After a reboot, I'm not able to reproduce the bug. So I close the issue ?

**Comment by asergi** [comment]
Yes, thanks.
