### ISSUE TITLE
Action event for the [monitor] plugin

### ISSUE THREAD

**Issue by vsn4ik** [nicolargo/glances#598]
Is it possible to use the action events for [monitor] section (countmin, countmax, process return code...)?

If not, do you plan to add?

**Comment by nicolargo** [comment]
Thk for the proposal.
Added to the 2.5 roadmap.

**Comment by telethonic** [comment]
This would be a great feature, enabling the sending of an alert when a certain process fails.

If I do a git clone of the current repo, is it in there?

**Comment by nicolargo** [comment]
Nope. It is scheduled in the 2.6 version.

Follow this issue to stay in touch.

**Comment by telethonic** [comment]
That was quick :)

ok, thanks.

**Comment by nicolargo** [comment]
Sorry, but i have to postpone this feature for a future milestone.
I have to refactor the action / monitor class to take into account this feature.

**Comment by telethonic** [comment]
ok, thanks for the update :)

**Comment by nicolargo** [comment]
To be reported on the AMP plugins
