### ISSUE TITLE
Quick look doesn't work

### ISSUE THREAD

**Issue by davidkulak** [nicolargo/glances#605]
With big screen size
![capture d ecran 2015-05-21 a 20 25 49](https://cloud.githubusercontent.com/assets/7256045/7755912/dd1555ac-fff7-11e4-8269-b0a60c26bed4.jpg)

But it works with small screen size
![capture d ecran 2015-05-21 a 20 26 45](https://cloud.githubusercontent.com/assets/7256045/7755924/ec44e2d6-fff7-11e4-9b68-5bfaf5d0b7ee.jpg)

**Comment by nicolargo** [comment]
Linked to https://github.com/nicolargo/glances/issues/608

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/ee6d7e4b5c9acc14e9646519afbd9a3fdb95f3f8
