### ISSUE TITLE
No disk information with OpenVZ machine

### ISSUE THREAD

**Issue by davidkulak** [nicolargo/glances#606]
Can't see my disk information on an OpenVZ machine because of the following line in glances_fs.py : 
fs_stat = psutil.disk_partitions(all=False)

When all=True it works 

![capture d ecran 2015-05-21 a 20 39 00](https://cloud.githubusercontent.com/assets/7256045/7756140/7af1d038-fff9-11e4-979b-45522ced9f29.jpg)

**Comment by nicolargo** [comment]
If you use Glances 2.1 or higher you can add the simfs filesystem to the list of allowed file system in the fs plugin by adding the following lines to your configuration file:

```
[fs]
allow=simfs
```

This is in the documentation: https://github.com/nicolargo/glances/blob/master/docs/glances-doc.rst#file-system
