### ISSUE TITLE
Graphical percentage bar displays "?"

### ISSUE THREAD

**Issue by rverchere** [nicolargo/glances#608]
Using glances 2.4.1 with psutil 2.2.1 on a Debian Wheezy server.
When I connecting via SSH from a Mac OS X based computer using the Terminal.app, the graphical % bar displays "?" instead of full green values.
I have not the issue when using a Debian client.

![screen shot 2015-05-22 at 13 58 39](https://cloud.githubusercontent.com/assets/232433/7770138/4d699082-008b-11e5-9b45-4b0a9d369419.png)

**Comment by nicolargo** [comment]
It came from the use of the ASCII instead of UTF in the Mac OS X terminal. @asergi will propose a patch (2.4.2) to solve this issue.

**Comment by asergi** [comment]
Patch: https://gist.github.com/asergi/f0f9b5ccc832b555c19d

Please test.

**Comment by nicolargo** [comment]
Test OK on my conf (Ubuntu + Terminator)

**Comment by rverchere** [comment]
Ok for me, from a mac client:

![screen shot 2015-05-25 at 10 07 18](https://cloud.githubusercontent.com/assets/232433/7793964/f5a0fe52-02c5-11e5-8bcb-9c53b0d11574.png)

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/ee6d7e4b5c9acc14e9646519afbd9a3fdb95f3f8

**Comment by davidkulak** [comment]
Works perfectly with all screen size on Mac OSX and iTerm.
Good work thanks.
