### ISSUE TITLE
Short process name displays arguments

### ISSUE THREAD

**Issue by justmytwospence** [nicolargo/glances#609]
It would be nice if there was a third format for process names, that displayed just the commands basename while also including all of the arguments.  I want to know the arguments to all my Python processes, but I can't see them easily because the path to the Python executable is something crazy like 

```
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /
```

and if I toggle the process-short-name, I can no longer see the arguments either.

**Comment by nicolargo** [comment]
Best way to respond to the need without adding a new process name format will be to extend the current short process name (without the crazy folder) with the arguments.

**Comment by nicolargo** [comment]
Done.
