### ISSUE TITLE
Backspace in filter

### ISSUE THREAD

**Issue by mrvkino** [nicolargo/glances#616]
The backspace is not working in the filter test box. We need to go the start of the line overwrite the string and add space to erase the letter left from the previous filter that are not overwritten.

Could clear the dialog box and/or make the backspace work?

Thanks

**Comment by nicolargo** [comment]
The backspace key works like a charm on my PC...
What is your OS configuration & Glances version.

**Comment by mrvkino** [comment]
I am on OSx 10.10.3 using iTerm latest release and I use Glances v2.3 with psutil v2.2.1.

**Comment by notFloran** [comment]
Same thing on OSx 10.10.3 using iTerm latest release and Glances v2.5beta with psutil v2.2.1

**Comment by notFloran** [comment]
It seems that iterm use **^?** for backspace.

See https://bugs.python.org/issue23598

**Comment by nicolargo** [comment]
Use as it (with the notFloran's work around).
