### ISSUE TITLE
Hide Core temp if is virtual machine

### ISSUE THREAD

**Issue by LeDistordu** [nicolargo/glances#617]
HDD temp is useless when you are on virtual machine, can you automatically hide it when glances is on virtual machine ?

**Comment by nicolargo** [comment]
Do not understand the issue description.

With Glances 2.4.2:
* The HDDTemp plugin is displayed only if HDDTemp daemon is detected.
* You can use the --disable-hddtemp to force it

What is your OS/VM, what is your Glances version ?

**Comment by LeDistordu** [comment]
actually I had the package installed hddtemp, i purge it but always the same

Glances 2.4.2
Debian Jessie

![hddtemp](https://cloud.githubusercontent.com/assets/7805145/8031939/a4de6afa-0dd2-11e5-80b5-3bbf3ae03f8d.jpg)

**Comment by LeDistordu** [comment]
erf '-_- it's not hdd temp but core temp sorry....

Glances 2.4.2
Debian Jessie

![hddtemp](https://cloud.githubusercontent.com/assets/7805145/8032044/6a931ee4-0dd3-11e5-9bdf-77e6da4d11f4.jpg)

**Comment by nicolargo** [comment]
Ok, you can disable the sensor plugin using the --disable-sensors option.

**Comment by nicolargo** [comment]
Use as it.
