### ISSUE TITLE
Implement IRIX mode on/off

### ISSUE THREAD

**Issue by MaxiBul** [nicolargo/glances#628]
I have CPU with 8 cores.
Total CPU usage: 16%
But [monitor] group for PHP-FPM sometime output CPU: >100%. Looks like has to be divided on number of cores?

**Comment by nicolargo** [comment]
Nope, the processes CPU is given "per core". If a process use all CPU of the first core, Glances displays 100%. If it use 2 Core, Glances displays 200%...

**Comment by MaxiBul** [comment]
But you have "'1' Switch between global CPU and per core stats". May be better sync this setting with all CPU data? In my case I use "global CPU stats", but for PHP-FPM I see > 100%. This is little confuse...

**Comment by nicolargo** [comment]
I understand your point of view.

I have a look on the top's man page:

```
          The task's share of the elapsed CPU time since the last screen update, expressed as a percentage of total CPU time.

           In a true SMP environment, if a process is multi-threaded and top is not operating in Threads mode, amounts greater than  100%  may  be
           reported.  You toggle Threads mode with the `H' interactive command.

           Also  for  multi-processor environments, if Irix mode is Off, top will operate in Solaris mode where a task's cpu usage will be divided
           by the total number of CPUs.  You toggle Irix/Solaris modes with the `I' interactive command.
```

For Glances, i think that the default behavor is to stay with the current Irix mode on. I can add a shortcut and a command line option  to switch to Irix mode off.

**Comment by nicolargo** [comment]
Implemented in the latest commit:

IRIX mode can be switched off using: --disable-irix command line tag or '0' shortkey.
