### ISSUE TITLE
glances vs glances -w, diferent config?

### ISSUE THREAD

**Issue by muhahacz** [nicolargo/glances#632]
Hi, can you please explain to me a difference between running glances from console and running it as a web server? 
Because in console there are things like.. sensors with temperature below 1°C are not shown.
Processes are shown with ps -full flag, etc.
I didnt find any default config on my system,

( ~/.config/glances, /etc/glances )

I want same settings in web server mode, as in console mode.

Thanks

**Comment by nicolargo** [comment]
You should have the same result in the console and Web server mode. If not, it's a bug. 
For the process list, there is some additional infomation displayed in the console.

Please, can you post your issues ?

**Comment by muhahacz** [comment]
Look at these images, that i just uploaded..
glances
http://s12.postimg.org/vfhybl1rx/glances_shell.jpg
glances -w 
http://s12.postimg.org/x60zd2jb1/glances_web.jpg

**Comment by nicolargo** [comment]
For the process name it's a feature, not a bug. In the Web UI, only short name is display in the current version.

For the SENSOR module it's an issue => @nclsHart can you have a look ?

**Comment by nclsHart** [comment]
Hi @muhahacz, can you send us the response returned by the sensors plugin API (http://0.0.0.0:61208/api/2/sensors by default) ?

**Comment by muhahacz** [comment]
Sure
```
[{"type": "temperature_core", "value": 50, "unit": "\u00b0C ", "label": "SYSTIN"}, {"type": "temperature_core", "value": 50, "unit": "\u00b0C ", "label": "CPUTIN"}, {"type": "temperature_core", "value": 46, "unit": "\u00b0C ", "label": "AUXTIN"}, {"type": "temperature_core", "value": 0, "unit": "\u00b0C ", "label": "PCH_CHIP_TEMP"}, {"type": "temperature_core", "value": 0, "unit": "\u00b0C ", "label": "PCH_CPU_TEMP"}, {"type": "temperature_core", "value": 0, "unit": "\u00b0C ", "label": "PCH_MCH_TEMP"}, {"type": "temperature_core", "value": 35, "unit": "\u00b0C ", "label": "temp1"}, {"type": "temperature_core", "value": 35, "unit": "\u00b0C ", "label": "temp1"}, {"type": "fan_speed", "value": 0, "unit": "RPM", "label": "fan1"}, {"type": "fan_speed", "value": 0, "unit": "RPM", "label": "fan2"}, {"type": "fan_speed", "value": 0, "unit": "RPM", "label": "fan3"}, {"type": "fan_speed", "value": 0, "unit": "RPM", "label": "fan4"}, {"type": "fan_speed", "value": 0, "unit": "RPM", "label": "fan5"}, {"type": "battery", "unit": "%", "value": [], "label": "Battery"}]
```
