### ISSUE TITLE
[Request] Support /sys/class/thermal/thermal_zone* directly

### ISSUE THREAD

**Issue by mbirth** [nicolargo/glances#637]
Please add support to read and display temperature from e.g.

```
/sys/class/thermal/thermal_zone0/temp
```

directly without the need for lm-sensors. lm-sensors doesn't detect any sensors on my Raspberry Pi 2 board, but the `thermal_zone0` is already detected by the kernel so no lm-sensors needed.

**Comment by nicolargo** [comment]
Hi Markus,

here are others folders in /sys/class/thermal/ ?

Nicolas

**Comment by nicolargo** [comment]
File format: http://kernelreloaded.blog385.com/index.php/archives/formatting-output-from-raspberry-pi-temperature-sensors/

**Comment by mbirth** [comment]
@nicolargo On my RasPi, the folder looks like this:

```
> ls -l /sys/class/thermal/
total 0
lrwxrwxrwx 1 root root 0 Jan  1  1970 thermal_zone0 -> ../../devices/virtual/thermal/thermal_zone0/
```

On my Acer Aspire Revo 3610, it looks like this:

```
> ls -l /sys/class/thermal/
total 0
lrwxrwxrwx 1 root root 0 Jul 23 15:11 cooling_device0 -> ../../devices/virtual/thermal/cooling_device0/
lrwxrwxrwx 1 root root 0 Jul 23 15:11 cooling_device1 -> ../../devices/virtual/thermal/cooling_device1/
lrwxrwxrwx 1 root root 0 Jul 23 15:11 cooling_device2 -> ../../devices/virtual/thermal/cooling_device2/
lrwxrwxrwx 1 root root 0 Jul 23 15:11 cooling_device3 -> ../../devices/virtual/thermal/cooling_device3/
lrwxrwxrwx 1 root root 0 Jul 23 15:11 thermal_zone0 -> ../../devices/virtual/thermal/thermal_zone0/
```

I'd assume, it's possible to have thermal_zone1, thermal_zone2, etc.

**Comment by Mirppc** [comment]
This will be very useful on other device like the Odroid or the CHIP.  The Odroid thermal sensor for the SoC is in the thermal_zone and for some reason will not show up in lm-sensors.  Not entirely sure where it is on the CHIP but it is likely the R8 SoC has a tempature monitor.

**Comment by nicolargo** [comment]
Too specific,  a possible workaround is to use AMP: http://glances.readthedocs.io/en/stable/aoa/amps.html
