### ISSUE TITLE
ENH: CPU utilization on each core

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#639]
It would be nice to be able to see CPU usage for each core independently instead of an average. Ideally, this would be similar to how `htop` displays this information.

**Comment by nicolargo** [comment]
RTFM...

Click '1' in the interface to switch to per CPU, 
or use the --per-cpu tag from the command line.

**Comment by jakirkham** [comment]
Sorry, I don't think we are understanding each other. I am hoping to see bars like the one you have for each CPU like can be seen with `htop` here.

![screen shot 2015-07-27 at 10 38 32](https://cloud.githubusercontent.com/assets/3019665/8908749/ce9b918e-344b-11e5-9639-ca35b268a18e.png)

**Comment by jakirkham** [comment]
Also, I tried using the `--per-cpu` flag does not work. See result of attempted use below.

    # glances --per-cpu
    usage: glances [-h] [-V] [-d] [-C CONF_FILE] [--disable-network]
                   [--disable-ip] [--disable-diskio] [--disable-fs]
                   [--disable-sensors] [--disable-hddtemp] [--disable-raid]
                   [--disable-docker] [--disable-left-sidebar] [--disable-process]
                   [--disable-log] [--disable-quicklook] [--disable-bold]
                   [--enable-process-extended] [--enable-history]
                   [--path-history PATH_HISTORY] [--export-csv EXPORT_CSV]
                   [--export-influxdb] [--export-statsd] [--export-rabbitmq]
                   [-c CLIENT] [-s] [--browser] [--disable-autodiscover] [-p PORT]
                   [-B BIND_ADDRESS] [--password]
                   [--snmp-community SNMP_COMMUNITY] [--snmp-port SNMP_PORT]
                   [--snmp-version SNMP_VERSION] [--snmp-user SNMP_USER]
                   [--snmp-auth SNMP_AUTH] [--snmp-force] [-t TIME] [-w] [-q]
                   [-f PROCESS_FILTER] [--process-short-name]
                   [--hide-kernel-threads] [--tree] [-b] [-1] [--fs-free-space]
                   [--theme-white]
    glances: error: unrecognized arguments: --per-cpu

**Comment by nicolargo** [comment]
You have a old Glances version, please use '-1' tag

**Comment by jakirkham** [comment]
I am using the latest release version.

    $ glances --version
    Glances v2.4.2 with psutil v2.2.1

**Comment by jakirkham** [comment]
Ah, its `--percpu`. Then it works. Is there some reason this doesn't show up in the usage dialog? FWIW, it does show up with `glances -h`.

**Comment by jakirkham** [comment]
I tried to provide a clearer explanation of what I meant with this issue here ( https://github.com/nicolargo/glances/issues/640 ).
