### ISSUE TITLE
ENH: CPU bar visualizing utilization on each core

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#640]
It would be nice to be able to see bars visualizing the CPU usage for each core independently instead of an average. Ideally, this would be similar to how `htop` displays this information. See example bars in `htop` below.

![screen shot 2015-07-27 at 11 10 34](https://cloud.githubusercontent.com/assets/3019665/8909628/552c2476-3450-11e5-95f7-af9a6badc29e.png)

**Comment by nicolargo** [comment]
Implemented in the develop branch

**Comment by jakirkham** [comment]
Thanks @nicolargo. I'll try taking this for a spin.

**Comment by jakirkham** [comment]
Had a chance to try this today. It works very nicely. Thanks again @nicolargo.
