### ISSUE TITLE
Container name problem

### ISSUE THREAD

**Issue by crepererum** [nicolargo/glances#643]
![screenshot from 2015-07-30 14-14-19](https://cloud.githubusercontent.com/assets/1529400/8982849/4b13ec90-36c5-11e5-8a3d-9e5ef7a966bf.png)

The leading underscore and the too short container names seem to be kinda wrong.

**Comment by nicolargo** [comment]
Already corrected in the develop branch: https://github.com/nicolargo/glances/commit/e116ff4d4509a7f97ae58f939dee086f01813a63

Thanks for the report.

**Comment by crepererum** [comment]
Thank you :+1:
