### ISSUE TITLE
Value for free disk space is counterintuative on ext file systems

### ISSUE THREAD

**Issue by EduardBaer** [nicolargo/glances#644]
The value for free disk space is counterintuitive on file systems like ext2/3/4, possibly others as well.
By default, 5% of the disk space is reserved for root, at least on ext file systems.

At the moment, glances includes these 5% when showing the free space. But since this space is reserved no one but root can actually use it. Therefore it would make more sense to show only the remaining usable space.

Glances uses psutil to get the disk usage and psutil knows about the free space without the reserved blocks. To fix this I would suggest to change the line 132 in glances_fs.py to
```python
fs_current = {
    ...
    'free': fs_usage.free,
    ...}
```
https://github.com/nicolargo/glances/blob/master/glances/plugins/glances_fs.py#L132

**Comment by nicolargo** [comment]
Thks for the head up.

Corrected in develop branch.
