### ISSUE TITLE
CRITICAL: Curses module not found. Glances cannot start in standalone mode

### ISSUE THREAD

**Issue by zwb-ict** [nicolargo/glances#645]
I installed glances with pip, then I run, get an error: CRITICAL: Curses module not found. Glances cannot start in standalone mode.

OS verison: Mac OS X 10.11 Beta (15A234d), python version: 2.7.10 (installed by brew) Pip version: 7.1.0

**Comment by nicolargo** [comment]
Hi,

can you check that Curses is installed ?

```
python
> import curses
```

**Comment by zwb-ict** [comment]
@nicolargo I checked , I have it curses installed(with brew), version is 5.9, import curses got no error.

**Comment by zwb-ict** [comment]
@nicolargo  It's very strange， I removed brew's python, run Mac system python, import curses OK, but install brew;s python, import curses get error:

Python 2.7.10 (default, Jul 18 2015, 17:21:56)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
>>>

**Comment by nicolargo** [comment]
Open the issue on Brew issue tracker.

**Comment by zwb-ict** [comment]
@nicolargo Thank you for your help! I open the issue on Brew issue tracker, and have solved this problem.

**Comment by summyer** [comment]
➜  # 解决 import sqlite3 报错
➜  yum install sqlite-devel

**Comment by summyer** [comment]
➜  # 解决 import curses 报错
➜  yum install  ncurses-devel
