### ISSUE TITLE
Improve IP plugin to display public IP address

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#646]
Before:

    IP 172.30.5.39/24

After:

    IP Priv: 172.30.5.39/24 | Pub: 89.39.10.1

Note: | Pub: 89.39.10.1 is optional (only if space available)

See: http://stackoverflow.com/questions/9481419/how-can-i-get-the-public-ip-using-python2-7 (! not Python3 compliant)

**Comment by nicolargo** [comment]
Pb: very slow. Can only done when Glances is started.

**Comment by nicolargo** [comment]
Done in the latest commit:

![Uploading Sélection_005.png…]()

**Comment by nicolargo** [comment]
@nclsHart Can you report this new feature to the WebUI ?

**Comment by nicolargo** [comment]
There is a problem with Python 3.

**Comment by nicolargo** [comment]
Python 3 issue should be corrected.

Please test !

**Comment by tusharjambhekar** [comment]
How can I run Glances web server at Public IP.
I have installed glances on my AWS instance want to access glances -w to my public ip.

Kindly assist me.

**Comment by alkaphreak** [comment]
Newer version of Glances doesn't display public IP address anymore is that normal ?
