### ISSUE TITLE
Can't delete filter text (Mac OS 10.9, Python 2.7, psutil 3.1.1, glances latest)

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#647]
After entering filter text, using the delete key fails to delete text.

**Comment by nicolargo** [comment]
Try ctrl-d

**Comment by jakirkham** [comment]
ctrl-d also does not work.

**Comment by nicolargo** [comment]
Give a chance to **CTRL-H**...

**Comment by jakirkham** [comment]
Actually, `ctrl-h` does work.

**Comment by nicolargo** [comment]
Docs should be updated.

**Comment by jakirkham** [comment]
Is there some reason that the delete key doesn't work here?
