### ISSUE TITLE
WebUI - Glances Web mode do not support debug mode

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#650]
Glances 2.4.2.

```
$ glances -w -d
Glances web server started on http://0.0.0.0:61208/
Bottle v0.12.8 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:61208/
Hit Ctrl-C to quit.
 
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_bottle.py", line 387, in _enable_cors
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_bottle.py", line 220, in _api_all
    f = open(filepath)
IOError: [Errno 2] No such file or directory: '~/glances/debug.json'
...
```
Glances just sits there forever with the Glances "an eye on your system".

Source: https://groups.google.com/d/msgid/glances-users/82d16936-e133-46eb-80cb-8f989c679a14%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by nclsHart** [comment]
@nicolargo There is a particular reason for having chosen `~/glances/` as base path for the web UI debug file ?

**Comment by nicolargo** [comment]
Nope...

**Comment by nclsHart** [comment]
Maybe the glances conf directory could be a better place for this ? 

Which behavior do you want if the file does not exist ? We can just ignore it or display a warning message.

**Comment by nicolargo** [comment]
The configuration file and the debug file should be in a different folder.
Most of the time the default configuration file is hosted in a folder with read-only right.

**Comment by nicolargo** [comment]
Verifie
