### ISSUE TITLE
Docker plugin crashs with webserver mode

### ISSUE THREAD

**Issue by notFloran** [nicolargo/glances#654]
If I execute glances in webserver mode and I have a docker container running, I get : 

``` 
$ LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances -w
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vagrant/dev/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 190, in main
    args=core.get_args())
  File "glances/core/glances_webserver.py", line 42, in __init__
    self.stats.update()
  File "glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "glances/plugins/glances_plugin.py", line 654, in wrapper
    ret = fct(*args, **kw)
  File "/home/vagrant/dev/glances/glances/plugins/glances_docker.py", line 205, in update
    t = ThreadDockerGrabber(self.docker_client, container['Id'], self.args.time)
AttributeError: 'NoneType' object has no attribute 'time'
```

With standalone mode : no problems

**Comment by notFloran** [comment]
More infos : 

It seems that *args* are not passed to *GlancesStats* in the webserver (see [here](https://github.com/nicolargo/glances/blob/develop/glances/core/glances_webserver.py#L35)).

If I passed *args* to *GlancesStats*, the web server starts.
But I can not stop Glances with CTRL + C, API stops but the process continues to run. 
I have to kill the process manually.

**Comment by nicolargo** [comment]
For the first point, the Docker plugin needs args to get the refresh time.
For the second poind, Docker stats are grabbed using a slow HTTP API, so the plugin needs to fork one thread per container. To kill all the threads, best way to process is to call the exit() method of the GlancesPlugin. For example, the Curses interfaces use this code to call all the plugins' exit() method: https://github.com/nicolargo/glances/blob/develop/glances/core/glances_stats.py#L231-L233

**Comment by nicolargo** [comment]
Ok Floran, i have corrected the Glances Core to correct the args and thread bug.

**Comment by nicolargo** [comment]
Anothers thinks:

[ ] the plugin do not show the MEM
[ ] the plugin do not show the network interface bitrate
[ ] the Docker (container) name can be long. The Web UI should cut it.

**Comment by nicolargo** [comment]
All done in the latest commit.
Also correct a bug in the network WebUI. The bitrate should be divide by the time_last_udate var.
