### ISSUE TITLE
[Web UI] Wrong value in filesystem plugin

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#662]
In curse interface : 

![glances-fs-curse](https://cloud.githubusercontent.com/assets/833625/9563271/6b1f4b6c-4e7e-11e5-9454-c41e33f5c155.png)

In web UI : 

![glances-fs-webui](https://cloud.githubusercontent.com/assets/833625/9563272/6e49da3c-4e7e-11e5-8467-34e731e1ac88.png)

**Comment by nicolargo** [comment]
In the Web UI, you should use the 'used' stat not "fs.size - fs.free".

I have patch it.
