### ISSUE TITLE
[WebUI] hddtemp not displayed in Web UI

### ISSUE THREAD

**Issue by HLFH** [nicolargo/glances#687]
Hi,

hddtemp is not displayed in Web UI but is displayed in console (here, crosh terminal, Chrome OS). You don't see sda temp in Web UI...

**In console:**
![screenshot 2015-09-26 at 03 42 01](https://cloud.githubusercontent.com/assets/2359059/10115201/aaf62624-6400-11e5-9d15-6612b2cacf5b.png)

**In Web UI:**
![screenshot 2015-09-26 at 03 59 31](https://cloud.githubusercontent.com/assets/2359059/10115290/0cd3c99e-6403-11e5-8769-3b819d491f37.png)

Have you an idea of how to fix this issue? I'm using Glances 2.4.2 on ArchLinux.

Thanks in advance,

**Comment by notFloran** [comment]
Hi,

Can you give it a try with the develop branch (see https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version) ?

Can you dump the result of http://HOST:61208/api/2/sensors ? I need this dump to reproduce the bug.

**Comment by HLFH** [comment]
Hi @notFloran 

```bash
[root@arch-server ~]# wget http://0.0.0.0:61208/api/2/sensors
--2015-10-07 06:11:34--  http://0.0.0.0:61208/api/2/sensors
Connexion à 0.0.0.0:61208… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 776 [application/json]
Sauvegarde en : « sensors »

sensors                               100%[========================================================================>]     776  --.-KB/s   ds 0s     

2015-10-07 06:11:35 (63,9 MB/s) — « sensors » sauvegardé [776/776]

[root@arch-server ~]# cat sensors 
[{"value": 28, "unit": "\u00b0C", "label": "Core 0", "type": "temperature_core", "key": "label"}, {"value": 28, "unit": "\u00b0C", "label": "Core 1", "type": "temperature_core", "key": "label"}, {"value": 29, "unit": "\u00b0C", "label": "Core 2", "type": "temperature_core", "key": "label"}, {"value": 29, "unit": "\u00b0C", "label": "Core 3", "type": "temperature_core", "key": "label"}, {"value": 28, "unit": "\u00b0C", "label": "Core 4", "type": "temperature_core", "key": "label"}, {"value": 28, "unit": "\u00b0C", "label": "Core 5", "type": "temperature_core", "key": "label"}, {"value": 28, "unit": "\u00b0C", "label": "Core 6", "type": "temperature_core", "key": "label"}, {"value": 28, "unit": "\u00b0C", "label": "Core 7", "type": "temperature_core", "key": "label"}][root@arch-server ~]#

**Comment by notFloran** [comment]
No values for sda in the dump provided by @HLFH, maybe a bug with the API.

@nclsHart Can you look at that ? I do not have a linux pc with sensor for HDD

**Comment by nicolargo** [comment]
@HLFH Can you test the DEVELOP branch ? It should solve your issue.

**Comment by HLFH** [comment]
@nicolargo @nclsHart With [Glances Develop](https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version) and Python 2.7, I got this issue on webserver mode:
```js
TypeError: Cannot read property 'length' of undefined
    at setData (glances_alert.js:8)
    at getPlugin (glances_stats.js:76)
    at GlancesStats.getData.then.$scope.is_disconnected (stats_controller.js:61)
    at J (angular.js:11749)
    at angular.js:11881
    at h.$eval (angular.js:12961)
    at h.$digest (angular.js:12678)
    at h.$apply (angular.js:13015)
    at m (angular.js:8404)
    at w (angular.js:8594)
```

Console mode is working perfectly, not the webserver mode where it's loading and loading and loading undefinitely these lines:
```bash
127.0.0.1 - - [15/Dec/2015 14:01:53] "GET /api/2/all HTTP/1.0" 200 0
127.0.0.1 - - [15/Dec/2015 14:01:53] "GET /api/2/all/views HTTP/1.0" 200 12757
```

**Comment by notFloran** [comment]
@HLFH Can you retry with [Glances develop](https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version) ?

**Comment by HLFH** [comment]
@notFloran 

I retried:
```js
TypeError: Cannot read property 'total' of undefined
    at setData (glances_cpu.js:18)
    at getPlugin (glances_stats.js:76)
    at GlancesStats.getData.then.$scope.is_disconnected (stats_controller.js:62)
    at J (angular.js:11749)
    at angular.js:11881
    at h.$eval (angular.js:12961)
    at h.$digest (angular.js:12678)
    at h.$apply (angular.js:13015)
    at m (angular.js:8404)
    at w (angular.js:8594)
```

**Comment by notFloran** [comment]
Very strange, it seems that data are missing from the API.

@HLFH  Can you make a dump of ```http://0.0.0.0:61208/api/2/all``` or see if data are present ?

**Comment by HLFH** [comment]
@notFloran I migrated my testing environment towards Glances develop branch with Python 3.5.1, just FYI.

Is that enough?
```bash
[root@arch-server ~]# curl http://0.0.0.0:61208/api/2/all
[root@arch-server ~]# curl http://0.0.0.0:61208/api/2/sensors
[{"key": "label", "unit": "C", "label": "Core 0", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 1", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 2", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 3", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 4", "value": 25, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 5", "value": 25, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 6", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "Core 7", "value": 26, "type": "temperature_core"}, {"key": "label", "unit": "C", "label": "sda", "value": 33.0, "type": "temperature_hdd"}][root@arch-server ~]# 
```

The hddtemp is displayed in the Web UI but the Web UI does not load as seen here:
```js
TypeError: Cannot read property 'total' of undefined
    at setData (glances_cpu.js:18)
    at getPlugin (glances_stats.js:76)
    at GlancesStats.getData.then.$scope.is_disconnected (stats_controller.js:62)
    at J (angular.js:11749)
    at angular.js:11881
    at h.$eval (angular.js:12961)
    at h.$digest (angular.js:12678)
    at h.$apply (angular.js:13015)
    at m (angular.js:8404)
    at w (angular.js:8594)
```
Do you have some other questions?

**Comment by notFloran** [comment]
@HLFH  What the result of ```curl http://0.0.0.0:61208/api/2/cpu``` with the develop and master branch ?

The WebUI does not load because data are missing from the API, example for your last error : data for the cpu plugin are missing, same for your previous error but this time for the alert plugin.

**Comment by HLFH** [comment]
@notFloran At least with the develop branch:

```bash
[root@arch-server ~]# curl http://0.0.0.0:61208/api/2/cpu
{"softirq": 0.0, "total": 0.4, "irq": 0.0, "guest": 0.0, "iowait": 0.0, "steal": 0.0, "user": 0.3, "system": 0.1, "guest_nice": 0.0, "idle": 99.6, "nice": 0.0}[root@arch-server ~]# 
```

Should I really try also with the master branch?

**Comment by notFloran** [comment]
@HLFH can you try without the debug mode?

**Comment by HLFH** [comment]
@notFloran I tested without the debug mode right now and it fully works!

```bash
cd ~/tmp/glances-develop
LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances -C ~/tmp/glances-develop/conf/glances-test.conf -w
```

It that related to this issue? Should we fix the debug mode again? https://github.com/nicolargo/glances/issues/650

**Comment by notFloran** [comment]
@HLFH Can you check if you have a **glances-debug.json** file in **/tmp** ?

When glances is executed with the debug mode and the file is present, the API endpoint **/api/2/all** use data from the file instead of the real data.

**Comment by HLFH** [comment]
@notFloran Yes there is an empty glances-debug.json in /tmp. I did `rm -rf /tmp/glances-debug.json` then `cd ~/tmp/glances-develop
LANGUAGE=en_US.utf8  ~/glances-venv/bin/python -m glances -d -C ~/tmp/glances-develop/conf/glances-test.conf -w` and it seems to work. Thanks!!
