### ISSUE TITLE
[feature] Change username for server and web server authentication

### ISSUE THREAD

**Issue by HLFH** [nicolargo/glances#693]
Hi, 

We now have web server authentication in 2.5 release thanks to this PR: https://github.com/nicolargo/glances/pull/615

We could do that to create a password: 
```bash
python -m glances -w --password 
```
but I would love to create also a username for full web server authentication: 
```bash
python -m glances -w --username
```
With that, I could replace the default *glances* username by my username.

Thanks in advance,

**Comment by nicolargo** [comment]
Done in the latest commit.
@HLFH : Please test !

**Comment by nclsHart** [comment]
Tested and working fine on Ubuntu 15.10.

**Comment by BirkhoffLee** [comment]
How do I use this if I use the Docker image?
