### ISSUE TITLE
Replace Matplolib by Pygal

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#697]
Matplolib is a good but heavy lib.

Replace it by: ???

**Comment by asergi** [comment]
I occasionally used [pygal](http://pygal.org/). It's simple, lightweight (no required dependency by default) and you can export charts in svg or png.

**Comment by nicolargo** [comment]
Note: Pygal needs following libs (cairosvg, tinycss, cssselect) to render png

**Comment by nicolargo** [comment]
Done in the latest commit.

See documentation here ==> https://github.com/nicolargo/glances/blob/develop/docs/gw/graph.rst
