### ISSUE TITLE
Change Docker's plugin displayed information

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#702]
For the moment, the Glances Docker's plugin displays the "not so useful" command line. The current enhancement proposes to replace the Command column by the latest logs (using the docker-py logs client stream => See https://docker-py.readthedocs.org/en/latest/api/#logs).

Before:

```
_dbgrafana_grafana_1                Up 11 mins   0.0  2.25M    0b    0b    0b    0b /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini cfg:default.p... 
```

After:

```
_dbgrafana_grafana_1                Up 11 mins   0.0  2.25M    0b    0b    0b    0b 2015/10/11 14:26:32 [I] Listen: http://0.0.0.0:3000
```

It should be possible to get back to the old command line layout using --docker-commandline option.

**Comment by widgetpl** [comment]
In my opinion last line of logs won't be useful but maybe it depends how heavily your applications is logging or maybe just show latest [ERROR|WARN] logs or sth like this. More useful would be showing all containers such as Exited ones which could be useful in production environments, so Glances could show some warning ( with bolded red etc. ) with such containers and you will know that sth wrong is happening with your environment.
