### ISSUE TITLE
/dev/ram shows up under disk I/O (Ubuntu 15.10) 

### ISSUE THREAD

**Issue by rogerfachini** [nicolargo/glances#710]
When running under Ubuntu 15.10, under the Disk I/O section the /dev/ramN entries show up among the list of other devices. Tested across several different systems running 15.10, it affects them all. 
![dev ram as disk io](https://cloud.githubusercontent.com/assets/7243587/10785767/732d24ae-7d23-11e5-9550-425f61cdeedb.PNG)

**Comment by nicolargo** [comment]
It is possible to hide ram disk using the following section in the glances.conf file:

    [diskio]
    hide=ram0,ram1,<etc ...>

https://github.com/nicolargo/glances/blob/master/docs/glances-doc.rst#disk-i-o
