### ISSUE TITLE
How to control console log level/format?

### ISSUE THREAD

**Issue by themalkolm** [nicolargo/glances#712]
Hey, is it possible to disable curses UI completely and simply output logs on stdout?

**Comment by nicolargo** [comment]
With Glances 2.5 or higher, you can use the --quiet option to disable the curse interface.

**Comment by themalkolm** [comment]
OK, I got the quite option. But how to do this combo:

```
1. Disable curse interface
2. Redirect log to console and control it's level (DEBUG/INFO/...)
```

**Comment by themalkolm** [comment]
Hm, I see that default log level for console is CRITICAL and no way to change it. Is it possible to provide custom logging.conf somehow?

**Comment by themalkolm** [comment]
Just to give the context. I'm evaluating glances if it could be used on Windows as collectd-like daemon to send metrics to statsd server. So, I can disable curses UI - check. Now the question how to control console logs format/level/etc.

**Comment by themalkolm** [comment]
And to save some time, is there any support for adding plugins via cfg somehow? I understand that I can add them to `plugins` folder and rebuild the project. But it would be nice to somehow use the version from pip and simply configure to have extra plugins.

**Comment by nicolargo** [comment]
Why don't you use directly the statsD plugin to populate your StatsD database ?
=> https://github.com/nicolargo/glances/blob/master/docs/glances-doc.rst#statsd

**Comment by themalkolm** [comment]
1. `--export-statsd` works fine, no problems here. Exports as expected.
2. I want to have glance logs being printed to stdout and somehow control their format.
3. I would like to implement custom plugins and this way extend exported metrics whenever required.

**Comment by nicolargo** [comment]
2. You can have a look in the https://github.com/nicolargo/glances/blob/develop/glances/core/glances_logging.py file in order to change the log/format.

3. All the plugins are exported. So if you add a new plugin to the https://github.com/nicolargo/glances/tree/develop/glances/plugins folder it should work. Best way to processed to write a new plugin is to start from an existing one and adapt to your needs. The plugin file should be named glances_xxx.py (where xxx is your plugin name).

Perhaps you can describe what kind of new metrics do you need ?

**Comment by nicolargo** [comment]
@themalkolm anuy head up ?

I plan to make the Glances logging system configurable through the configuration file. Is it responding to yours needs ?

**Comment by themalkolm** [comment]
@nicolargo yes, this will solve logging issue. I would say an essential part of any headless daemon.

**Comment by nicolargo** [comment]
Implementation done through the issue #900 .

Read the doc https://github.com/nicolargo/glances/blob/develop/docs/config.rst#logging to configure your own logger.

**Comment by themalkolm** [comment]
Thanks!
