### ISSUE TITLE
Glances server did not start/can not be stopped

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#720]
@asergi Following this push (https://github.com/nicolargo/glances/commit/7b1dc3cf6d1abb0ce52457b1a709408f0cd12bb3), the Glances server did not start anymore:

    $ python -m glances -s 
    Cannot start Glances server: must be type, not classobj

Can you have a look ?

**Comment by asergi** [comment]
https://github.com/nicolargo/glances/commit/4fb83d156c9501f41e2a77f0f36ec0cd5b151f5a

Fixed. Sorry, I did the tests only on Python 3.

**Comment by nicolargo** [comment]
Corrected, but the Glances server can not be stopped with the CTRL-C key.

**Comment by asergi** [comment]
Works for me:
```
(py27-glances) % glances -s
Glances server is running on 0.0.0.0:61209
^C
(py27-glances) %

**Comment by nicolargo** [comment]
Mmmhhh, i will test it on another PC...

**Comment by nicolargo** [comment]
Tested !
