### ISSUE TITLE
[WebUI] Make web page title configurable

### ISSUE THREAD

**Issue by telethonic** [nicolargo/glances#724]
a minor feature request: can you make it so I can set the web page title in the config file?

this way, when I have multiple tabs open on multiple servers, I can see which is which
(now they all say "Glances")

thanks :)

**Comment by nicolargo** [comment]
Another solution is to fill the title with the client IP address / name instead of the default Glances text. What do you think ?

**Comment by telethonic** [comment]
That would work. 

But in my case (running glances on Amazon AWS instances) the names and IP addresses are not always very informative (they're typically "ip-<internal ip address>"). That said, I can of course change the hostname :)

So whatever is easiest.

**Comment by nicolargo** [comment]
Ok.

@notFloran Can you have a look to implement this feature into the WebUI ?

**Comment by notFloran** [comment]
@nclsHart I made a PR for that :)

**Comment by nicolargo** [comment]
@telethonic Implemented in the latest commit (see issue #726). Can you test the develop branch ?
