### ISSUE TITLE
Glances from inside a Docker container

### ISSUE THREAD

**Issue by YannickB** [nicolargo/glances#728]
Hello,

I am trying to create a container with glances inside, to monitor the server running Docker. I'm doing this because I only want to have the docker process running on the host system.

I launched the container with --pid host argument so it have access to the whole system (I get the tip from a forum speaking of htop inside container), thanks to this I see CPU/RAM/etc... of all the processes.

The only problem I have, the docker plugin is not visible, I guess it can't find the docker containers from inside a container. Docker-py is installed and I also tried to run it in privileged mode. That's a problem for me because monitoring the containers is the main purpose of the glances installation.

Is there any way to be able to see the containers in glances, when it is itself installed in a container?

Best regards,
Yannick.

EDIT : Sorry I saw the contributing rules too late... I shall have posted this in the google groups.

**Comment by nicolargo** [comment]
Hi @YannickB .

Thanks for the --pid host argument, did not know that :)

The docker plugin uses the Docker-py lib. This lib grabs Docker stats using the Docker API (using the unix://var/run/docker.sock file). So the container running Glances should read this file to do the jobs. Perhaps you can use a data volume to export /var/run to the container.

Keep me inform.

**Comment by YannickB** [comment]
Perfect, I figured that would be something like this but I didn't know which volume I'd have to map.

Here are my arguments : -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host

If you are curious, glances will be used in this project : https://github.com/clouder-community/clouder/commit/aef185c2eba97f3d5aae341ea4edc4ec785b6ce3 , strongly linked to Odoo you may expect some use of glances from the Odoo community in the next months. 
I needed a complete tool for easily monitoring the server and I believe glances would do just fine.

Thanks for your help!

**Comment by nicolargo** [comment]
Nice !

I will add a new section in the documentation with your command line: -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host

**Comment by nicolargo** [comment]
Just create a official Glances docker image: https://hub.docker.com/r/nicolargo/glances-docker/
