### ISSUE TITLE
[WebUI] Display issue with the file system plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#731]
Display issue with long device name.

Curse:
![selection_421](https://cloud.githubusercontent.com/assets/776747/11443159/e7e0d958-951a-11e5-92b4-3060ae09436d.png)

WebUI:
![selection_420](https://cloud.githubusercontent.com/assets/776747/11443162/ed8d602e-951a-11e5-830b-7c059fe6af74.png)

**Comment by nicolargo** [comment]
@notFloran Can you have a look ?

**Comment by nicolargo** [comment]
@notFloran or @nclsHart Can you make a patch for this issue ?

**Comment by nclsHart** [comment]
@nicolargo Yep. I'll fix this one.

**Comment by nicolargo** [comment]
@nclsHart : I want to release the 2.6 version in march. Can you do it ? (or perhaps @notFloran can have a look on it...).

**Comment by nclsHart** [comment]
@nicolargo yes, sorry for the delay... No problem I'll do it asap.

**Comment by nicolargo** [comment]
@nclsHart I want to release Glances 2.6 next week. Is it possible for you to work on this issue ?
