### ISSUE TITLE
Add global attribute in {{mustache}}

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#733]
Glances allows you to define action on trigger (see: http://glances.readthedocs.org/en/latest/glances-doc.html#actions). Inside the action's command line, it is possible to use {{mustache}} where mustache is one of the attribute of the current plugin section. It should be great to allow user to define external global attribute like: hostname... (TODO: define other attributes).

**Comment by nicolargo** [comment]
Any user needs ?

**Comment by RazCrimson** [comment]
Closing as issue is very old and no interest from community.
