### ISSUE TITLE
New "Ports scanner" plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#734]
The "ports scanner" plugin aims at monitoring local or remote TCP/ICMP ports status. A list of remote host/port is define in the configuration file and the result is displayed in the UI.

Configuration file example:

    [ports]
    port_1_description=Internet connection
    port_1_hostport=www.google.fr:80
    port_2_description=Ping my router
    port_2_hostport=192.168.0.254

Note: if no port is provided, use ICMP instead of TCP.

UI:

    Internet connection    Port unreachable (red)
    Ping my router         10ms (green)

Source:

* https://docs.python.org/2/library/asyncore.html#module-asyncore
* http://stackoverflow.com/questions/1205863/how-can-i-get-non-blocking-socket-connects

For ICMP: all need **root** right !!!
* For ICMP: https://github.com/volftomas/pyicmp/blob/master/ping.py
* For ICMP (bis): https://github.com/samuel/python-ping/blob/master/ping.py
* For ICMP (ter): https://gist.github.com/pklaus/856268
* For ICMP (last but not least): https://bitbucket.org/delroth/python-ping/src/7084c31fa1603a1071c30525ae0431da42ce93cd/ping.py?at=default&fileviewer=file-view-default

Also have a look on http://denilson.sa.nom.br/prettyping/ (for the nice graph idea)

**Comment by nicolargo** [comment]
See and complete the following Gift for this plugin core: https://gist.github.com/nicolargo/d220f67da6d826cc9137

**Comment by nicolargo** [comment]
![selection_033](https://cloud.githubusercontent.com/assets/776747/16008747/ae62daf4-3179-11e6-96bb-6eaf48555978.png)

**Comment by nicolargo** [comment]
Nice proposal from Twitter:

Maxime Carron @mxcarron
@nicolargo it would be nice to get "default gateway” from system config (and keep the ip updated), and have tested by default ;-)

**Comment by nicolargo** [comment]
Implemented in the latest HEAD version (develop branch).

Please test !

**Comment by nicolargo** [comment]
@notFloran or @nclsHart : Can you update the Web UI with this new plugin ? Thanks !

**Comment by nclsHart** [comment]
@nicolargo I'll do it.

**Comment by nicolargo** [comment]
Thks in advance @nclsHart !!!

**Comment by nclsHart** [comment]
@nicolargo There is no shortcut for hiding/displaying this plugin?

**Comment by nicolargo** [comment]
@nclsHart The shortcut for hidding.dislaying this plugin is the same thanfor the Network plugin.

**Comment by nclsHart** [comment]
@nicolargo After some investigations I found this: https://github.com/nicolargo/glances/blob/develop/glances/outputs/glances_curses.py#L417, which seems to be not listed on the help page. 

Should I use the same shortcut and add it to the help page or change it in order to use the network plugin shortcut?

**Comment by nicolargo** [comment]
Yes please!

**Comment by nclsHart** [comment]
Yes for the first or the second option :p ?

**Comment by nicolargo** [comment]
First one, i forgot it :(
