### ISSUE TITLE
Add hide configuration key for FS Plugin

### ISSUE THREAD

**Issue by Schlunze** [nicolargo/glances#736]
Hello,

i wonder if there is an option to hide FILE SYS too.
Point is, i use bind mounts, and don´t want to see them in this list.

Thanks for your work, cheers.

**Comment by nclsHart** [comment]
Hello,

If you want to hide the filesystem plugin, you can launch glances using :

```
glances --disable-fs
``` 

or press the `f` key while glances is running.

**Comment by Schlunze** [comment]
Hi,
yes the hide option like the diskio one. Maybe in further versions....
thanks for your reply.

**Comment by nicolargo** [comment]
Planned for a next release.

**Comment by nicolargo** [comment]
Implemented in the develop branch:

Example:

    [fs]
    # Define the list of hidden file system (comma separeted)
    hide=/boot/efi
