### ISSUE TITLE
Glances not working on Windows 8.1, python 3.4?

### ISSUE THREAD

**Issue by Bart274** [nicolargo/glances#745]
Hi,

I use python 3.4 on my Windows 8.1 machine.
When I use 'glances -w' I get a message that the webserver has started on the default port.
But when I try to access the webpage, it just remains on the loading screen (still after 30 minutes)
when I press CTRL+C I get the following error and it won't stop:
```
C:\Python34\Scripts>glances -w
Glances web server started on http://0.0.0.0:61208/
Traceback (most recent call last):
  File "C:\Python34\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Python34\Scripts\bottle.py", line 979, in __call__
    return self.wsgi(environ, start_response)
  File "C:\Python34\Scripts\bottle.py", line 954, in wsgi
    out = self._cast(self._handle(environ))
  File "C:\Python34\Scripts\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python34\Scripts\bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "C:\Python34\lib\site-packages\glances\outputs\glances_bottle.py", line 3
96, in _enable_cors
    return fn(*args, **kwargs)
  File "C:\Python34\lib\site-packages\glances\outputs\glances_bottle.py", line 2
22, in _api_all
    self.stats.update()
  File "C:\Python34\lib\site-packages\glances\core\glances_stats.py", line 156,
in update
    self._plugins[p].update()
  File "C:\Python34\lib\site-packages\glances\plugins\glances_processcount.py",
line 58, in update
    glances_processes.update()
  File "C:\Python34\lib\site-packages\glances\core\glances_processes.py", line 6
31, in update
    self.processcount['thread'] += proc.num_threads()
  File "C:\Python34\lib\site-packages\psutil\__init__.py", line 752, in num_thre
ads
    return self._proc.num_threads()
  File "C:\Python34\lib\site-packages\psutil\_pswindows.py", line 282, in wrappe
r
    return fun(self, *args, **kwargs)
  File "C:\Python34\lib\site-packages\psutil\_pswindows.py", line 433, in num_th
reads
    return ntpinfo(*cext.proc_info(self.pid)).num_threads
  File "C:\Python34\lib\site-packages\glances\__init__.py", line 65, in __signal
_handler
    end()
  File "C:\Python34\lib\site-packages\glances\__init__.py", line 88, in end
    sys.exit(0)
SystemExit: 0
```

**Comment by nicolargo** [comment]
Hi @Bart274 , thanks for the report.

We need additional information:

* Glances and PsUtil version (glances -V)
* Can you http://pastebin.com/ the log file (under %APPDATA%\Local\temp\glances.log)

**Comment by Bart274** [comment]
I just installed it, I'm running glances v2.5.1 and psutil v3.3.0
my log is here: http://pastebin.com/a3GY3S0Z

**Comment by nicolargo** [comment]
Does the API respond ?

=> http://0.0.0.0:61208/api/2/all

**Comment by Bart274** [comment]
No, I get an error that that page isn't available

**Comment by nicolargo** [comment]
Strange. We will have a look as soon as i found a Windows 8.1.

**Comment by Bart274** [comment]
thanks a lot! :) I want to use it together with Home Assistant :)

**Comment by nicolargo** [comment]
Last question: does Glances works in standalone / debug  mode ?

glances -d 

+ log file via pastebin

Thks

**Comment by Bart274** [comment]
yes, it does work. it generates the view I need to have in the webserver I guess.

![glances debug](https://cloud.githubusercontent.com/assets/1118630/11630139/603372ec-9cfc-11e5-8584-dbe434119760.JPG)

this is my new log: http://pastebin.com/f4gcLTz3

**Comment by Bart274** [comment]
any progress with my issue?

**Comment by nicolargo** [comment]
Nope but can you try with the DEVELOP branch ?

**Comment by Bart274** [comment]
I uninstalled the install I did using python3 and installed it with python2, same result.
I uninstalled that install and used git clone to install the development branch, but I still have the same result.
However now I get an error 404 when I try to access localhost:61208/api/2/all: Cannot get stats ('utf8' codec can't decode byte 0xb5 in position 108: invalid start byte)

**Comment by nicolargo** [comment]
Did you have a look on this issue ? => https://github.com/nicolargo/glances/issues/205

**Comment by Bart274** [comment]
I did, I'm running it as administrator, opened that port in my firewall, but still nothing

**Comment by nicolargo** [comment]
And when you did not run it as admin ?

**Comment by Bart274** [comment]
just before you said to look at that 205 issue. then I just ran as my normal user (which is an admin user)

**Comment by nicolargo** [comment]
It it a French version of Windows 8.1 ?

**Comment by Bart274** [comment]
no, it's a Dutch version

**Comment by nicolargo** [comment]
Looks like an encoding issue on username or process command line...

**Comment by Bart274** [comment]
any idea how to fix that? my username is just 'Bart'

**Comment by nicolargo** [comment]
Nope for the moment, we need to found the script and line number involved in the Cannot get stats ('utf8' codec can't decode byte 0xb5 in position 108: invalid start byte) error... Perhaps in the Glances log file in debug mode...

**Comment by Bart274** [comment]
I deleted my glances.log and restarted glances using 'glances -d' as admin
this is my glances.log: http://pastebin.com/HEEvYEWF
this is the output in my command prompt: http://pastebin.com/YQzRvPT7

(note that the debug worked 2 days ago when using the release version)

**Comment by nicolargo** [comment]
I just commit a quick add dirty hack on the develop branch.
Can you test it ?

**Comment by Bart274** [comment]
no difference as normal user

**Comment by nicolargo** [comment]
You have the same issue with the latest DEVELOP branch ???

**Comment by Bart274** [comment]
yes, I went into my glances dir, did a git pull, did pip uninstall glances and a new setup.py install, after that I still had the same result :s

**Comment by nicolargo** [comment]
I have added a try/except around the line 907. Can you double check the file "C:\Python27\lib\site-packages\glances-2.5.1-py2.7.egg\glances\outputs\glances_curses.py" ?

**Comment by Bart274** [comment]
I had to run 'python2 -m pip uninstall glances' twice to completely delete Glances.
Then I ran 'python3 -m setup.py install' from within my Glances directory that uses the development branch and now I have it working! :)

**Comment by nicolargo** [comment]
Nice, have to code a "not dirty" work arround.

Thanks for the message.
