### ISSUE TITLE
Filter processes by others stats (username)

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#748]
Source: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/glances-users/4sh4eT9ZTtk/SIwpDS8OCAAJ

It should be great to filter processes by user.

**Comment by nicolargo** [comment]
Question: how to switch between process command line regexp and user name filtering ?

**Comment by nclsHart** [comment]
Maybe using a similar pattern than GitHub search : 

Examples : 

1. `mysql` => filter by command line
2. `user:mysql` => filter by user name
3. `cmd:mysql` => filter by command line
4. `cmd:mysql user:mysql` => filter by command line AND user name

**Comment by nicolargo** [comment]
Done on the develop  branch.

Only the following syntax as been implemented: https://github.com/nicolargo/glances/blob/develop/docs/aoa/ps.rst#process-filtering

To be tested
