### ISSUE TITLE
Cannot export  stats to InfluxDB 

### ISSUE THREAD

**Issue by ruudboon** [nicolargo/glances#750]
I'm running glances like
``` glances --export-influxdb -t 60 -d -q ```

When exporting to InfluxDB i'm seeing multiple errors in the log file

```
Cannot export myserver.ip stats to InfluxDB (400: unable to parse 'myserver.ip ': invalid field format
Cannot export myserver.network stats to InfluxDB (400: write failed: field type conflict: input field "tun0.time_since_update" on measurement "myserver.network" is type float64, already exists as type integer
Cannot export myserver.sensors stats to InfluxDB (400: unable to parse 'myserver.sensors ': invalid field format
)
Cannot export myserver.docker stats to InfluxDB (400: unable to parse 'myserver.docker ': invalid field format
```
I'm running InfluxDB v0.9.3.

**Comment by nicolargo** [comment]
Issue confirmed.

With InfluxDB 0.9.3

===

2015-12-11 15:10:13,564 -- ERROR -- Cannot export localhost.load stats to InfluxDB (400: unable to parse 'localhost.load cpucore=4i,load_careful=0.7,load_critical=5.0,load_warning=1.0,min1=0.07,min15=0.13,min5=0.12': invalid number
)
2015-12-11 15:10:13,566 -- ERROR -- Cannot export localhost.ip stats to InfluxDB (400: unable to parse 'localhost.ip address="192.168.176.128",gateway="192.168.176.1",mask="255.255.255.0",mask_cidr=24i': invalid number
)
2015-12-11 15:10:13,569 -- ERROR -- Cannot export localhost.memswap stats to InfluxDB (400: unable to parse 'localhost.memswap free=16701263872i,memswap_careful=50.0,memswap_critical=90.0,memswap_warning=70.0,percent=0.5,sin=295927808i,sout=700071936i,total=16777211904i,used=75948032i': invalid number

===

**Comment by ruudboon** [comment]
Could this magic 'i' be related to https://github.com/influxdb/influxdb/issues/3519 
And the conflict error with this one: https://github.com/influxdb/influxdb/issues/3032 ?

**Comment by nicolargo** [comment]
+1 for @ruudboon

**Comment by nicolargo** [comment]
The first bug (the 'i' one) is corrected by upgrading InfluxDB to 0.9.4 or higher.

The other one (float), should be corrected in the scope of this issue (have a look on https://github.com/influxdb/influxdb/issues/3032).

**Comment by ruudboon** [comment]
Upgrading to 0.9.4  is keeping the same issues for me. How can I see the extended info you are seeing @nicolargo ?

**Comment by nicolargo** [comment]
@ruudboon what extended info ? it's only the Glances log file...

**Comment by ruudboon** [comment]
I'm missing the data in the log. Only seeing 
```Cannot export myserver.sensors stats to InfluxDB (400: unable to parse 'myserver.sensors ': invalid field format) ```

**Comment by nicolargo** [comment]
Can you try with the latest DEVELOP branch version or disable the Sensor plugin (--disable-sensors)

**Comment by nicolargo** [comment]
The latest commit of the develop branch should solve this issue and the issue #749 .

Please:
- download the develop branch
- upgrade InfluxDB to 0.9.5 or higher
- upgrade the InfluxDB Python lib
- drop your existing database (sorry for that but InfluxDB is under development)
- run Glances and it should works like a charm

**Comment by ruudboon** [comment]
Cool will try to compile Glances myself. Running the Freebsd port now.

**Comment by nicolargo** [comment]
No need to compile, you are in a Python world...

**Comment by ruudboon** [comment]
Owh cool. Didn't realize it was written in Python.

**Comment by Jestre** [comment]
I'm getting similar errors, and after reading this I went ahead and pulled the develop branch and installed it in a venv.  Since I found this project (and InfluxDB) this morning, I am running glances-dev, influx 0.9.6 (from their influxdb-0.9.6.1-1.x86_64.rpm), and fresh pip installs of the requisite Python modules.

I get the same types of errors as OP:
"unable to parse 'localhost.ip' : invalid field format
and the float64 vs integer errors on localhost.network and localhost.diskio

Logs available as needed.

Thanks.

**Comment by unlikelyzero** [comment]
I'm seeing that same issue as Jestre with Ubuntu 14.04

**Comment by nicolargo** [comment]
I confirm that it is working like a charm with the following configuration:
* Glances DEVELOP branch
* InfluxDB 0.9.6
* Python lib InfluxDB 2.10.0

"unable to parse 'localhost.ip' : invalid field format 
=> this is a warning message.

and the float64 vs integer errors on localhost.network and localhost.diskio
=> Please delete and re-create your InfluxDB database.

**Comment by Jestre** [comment]
So @nicolargo what OS are you on?  I find it hard to believe that this is purely an issue on Ubuntu and Fedora.  I have the same versions of things as you list, and I had deleted and recreated my DB without success.  Is there some command other than 'drop database' to get rid of the old one with InfluxDB?

**Comment by nicolargo** [comment]
Tested on both Ubuntu 14.04 LTS and CentOS 7.0

**Comment by Jestre** [comment]
@nicolargo Thank you.  I will try back in a few months to see if the issues have been resolved.  Appreciate the input.

**Comment by unlikelyzero** [comment]
@nicolargo how do I ensure that I'm running on the development branch? I run the following command:
root@test:~# cd ~/tmp/glances-develop
root@test:~/tmp/glances-develop# LANGUAGE=en_US.utf8  /usr/bin/python -m glances -d -C ~/tmp/glances-develop/conf/glances.conf

**Comment by kalashnikov** [comment]
Hi, I think I got similar issue. 

Just try to re-install glances using `pip install --upgrade glances`

```
2016-01-06 02:03:08,728 -- DEBUG -- Export docker stats to InfluxDB
2016-01-06 02:03:08,730 -- DEBUG -- Setting read timeout to None
2016-01-06 02:03:08,730 -- DEBUG -- "POST /write?db=glances HTTP/1.1" 400 83
2016-01-06 02:03:08,732 -- ERROR -- Cannot export docker stats to InfluxDB (400: {"error":"unable to parse 'docker ': invalid field format"}
)
2016-01-06 02:03:08,732 -- DEBUG -- Export network stats to InfluxDB
2016-01-06 02:03:08,741 -- DEBUG -- Setting read timeout to None
2016-01-06 02:03:08,741 -- DEBUG -- "POST /write?db=glances HTTP/1.1" 400 149
2016-01-06 02:03:08,742 -- ERROR -- Cannot export network stats to InfluxDB (400: {"error":"write failed: field type conflict: input field \"ip6gre0.time_since_update\" on measurement \"network\" is type float64, already exists as type integer"}
)
```

The measurement is created but it's empty. 

Environment: 
Ubuntu 14.04 
InfluxDB 0.9.6.1
Glances-2.5.1
psutil 3.0.0

I am not sure how to use develop branch, any instruction ?

**Comment by nicolargo** [comment]
The InfluxDB interface is breaked between Glances 2.5.1 and InfluxDB 0.9.2 or higher.

Please use the lastest Glances Development branch AND the latest InfluxDB AND the latest Python InfluxDB lib.

**Comment by Josue-T** [comment]
Hello,

When I try to lunch glances as client I have an error : 

```
# glances --export-influxdb -c 127.0.0.1
Traceback (most recent call last):
  File "/opt/yunohost/glances/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
  File "/opt/yunohost/glances/lib/python3.4/site-packages/Glances-2.5.1-py3.4.egg/glances/__init__.py", line 150, in main
    if not client.login():
  File "/opt/yunohost/glances/lib/python3.4/site-packages/Glances-2.5.1-py3.4.egg/glances/client.py", line 127, in login
    self.stats = GlancesStatsClient(config=self.config, args=self.args)
  File "/opt/yunohost/glances/lib/python3.4/site-packages/Glances-2.5.1-py3.4.egg/glances/stats.py", line 304, in __init__
    self.load_plugins_and_exports(self.args)
  File "/opt/yunohost/glances/lib/python3.4/site-packages/Glances-2.5.1-py3.4.egg/glances/stats.py", line 91, in load_plugins_and_exports
    self.load_exports(args=args)
  File "/opt/yunohost/glances/lib/python3.4/site-packages/Glances-2.5.1-py3.4.egg/glances/stats.py", line 134, in load_exports
    export_module = __import__(os.path.basename(item)[:-3])
ImportError: No module named 'glances_influxdb'
```
Thank

**Comment by gabrieljames** [comment]
Ubuntu 14.0 Influx 0.10

apt-get installation

$ glances --help
Glances version 1.7.3 with PsUtil 1.2.1

Will this work?

**Comment by nicolargo** [comment]
Nope. ou need Glances 2.5.1 or higher...

**Comment by gabrieljames** [comment]
Where from? Don't know why this is not the latest?

On Wednesday, 2 March 2016, Nicolas Hennion <notifications@github.com>
wrote:

> Nope. ou need Glances 2.5.1 or higher...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolargo/glances/issues/750#issuecomment-190742784>.
>


-- 

*Gabriel James, PhD*

Director



*Heliase Genomics*

Level 3, 3A Symonds St, Auckland 1010, New Zealand

Institute of Innovation in Biotechnology, University of Auckland

DDI +64 9 923 1786 | Mobile +64 21 466 422

gabriel.james@heliase.com | www.heliase.com



[image: Heliase Genomics Text and Logo 50% 96 DPI]



This correspondence is for the named person’s use only. It may contain
information that is confidential, proprietary or the subject of legal
privilege. No confidentiality or privilege is waived or lost by any
mistransmission. If you receive this correspondence in error, please
immediately delete it from your system and notify the sender. You must not
disclose, copy or relay any part of this correspondence if you are not the
intended recipient

**Comment by nicolargo** [comment]
@gabrieljames RTFM: https://github.com/nicolargo/glances#installation

**Comment by gabrieljames** [comment]
Thanks will pull from git repo. 

 

UTFR Ubuntu package repo is way out of date (btw)

**Comment by gabrieljames** [comment]
Ubuntu 14.04

sudo apt-get install git
sudo apt-get install python-pip
sudo apt-get install python-dev
git clone -b develop https://github.com/nicolargo/glances.git
pip install --upgrade glances

Requirement already up-to-date: glances in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking psutil>=2.0.0 (from glances)
  Downloading psutil-4.0.0.tar.gz (293kB): 293kB downloaded
  Running setup.py (path:/tmp/pip_build_gabrieljames/psutil/setup.py) egg_info for package psutil

    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no files found matching '*.rst' under directory 'scripts'
    warning: no files found matching '*README' under directory 'scripts'
Installing collected packages: psutil
  Found existing installation: psutil 1.2.1
    Not uninstalling psutil at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for psutil
    building 'psutil._psutil_linux' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=400 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so
    building 'psutil._psutil_posix' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so
    error: could not create '/usr/local/lib/python2.7/dist-packages/psutil': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_gabrieljames/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w5GRqp-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/psutil

copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil

copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil

creating build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/runner.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests

copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests

running build_ext

building 'psutil._psutil_linux' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/psutil

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=400 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so

building 'psutil._psutil_posix' extension

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so

running install_lib

creating /usr/local/lib/python2.7/dist-packages/psutil

error: could not create '/usr/local/lib/python2.7/dist-packages/psutil': Permission denied

----------------------------------------
  Can't roll back psutil; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_gabrieljames/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w5GRqp-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_gabrieljames/psutil
Storing debug log for failure in /home/gabrieljames/.pip/pip.log

**Comment by gabrieljames** [comment]
$ sudo pip install --upgrade glances
Requirement already up-to-date: glances in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: psutil>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from glances)
Cleaning up...
$ glances --help
Glances version 1.7.3 with PsUtil 1.2.1

**Comment by nicolargo** [comment]
@gabrieljames Please swith to the Glances user forum. Your problem is not a development issue...

=> https://groups.google.com/forum/?hl=en#!forum/glances-users

**Comment by gabrieljames** [comment]
Okay, thanks for your help.

**Comment by gabrieljames** [comment]
Alright, not getting any responses in the user forum. 

As mentioned in feature suggestion, https://github.com/nicolargo/glances/issues/794

We are testing several other data collectors (collectd, telegraf, logstash, topbeat) so we can come up with a comprehensive metrics solution for our development and production needs. 

I was optimistic to see the feature suggestion for logging of all processes and associated metrics. It would be good to test glances as a service with Influx and Elasticsearch to see if it adds value to the stacks.  

My main concern at the moment is getting timely support to solve relatively simple issues like software installation, configuration and updates. 

I have to say the other vendors and developers in this space have been very responsive to help address these sorts of issues as they arise. They have not drawn subtle distinctions between developer and user support channels, and have been more concerned with helping their users get up and running. 

The update installation upgrade procedure has not been successful and am reluctant to waste time on this if is going to be a pain. 

Anyway, we are genuinely in interested in using your software, but if the support is going to be a problem, then we can do without the headache. 

Please let me know if you are willing to help us so we can make a call on it.

**Comment by nicolargo** [comment]
@gabrieljames i just post a respond on the forum. 

I ask you to switch to the forum because the Github issue tracker is dedicated to enhancement request and bug report. Glances is installed more or less 14.000 times per week, i do not think that the installation process is "bugged".

You are welcome to contribute to the documentation if you think that it should be enhance.

**Comment by hflamboauto1** [comment]
Having same problem here
```
glances --version
Glances v2.10 with psutil v5.2.2
```

Errors on logs

```
2017-06-18 11:11:36,532 -- ERROR -- Cannot export localhost.docker stats to InfluxDB (400: {"error":"unable to parse 'localhost.docker ': invalid field format"}
)
2017-06-18 11:11:39,580 -- ERROR -- Cannot export localhost.sensors stats to InfluxDB (400: {"error":"unable to parse 'localhost.sensors ': invalid field format"}
)
2017-06-18 11:11:39,638 -- ERROR -- Cannot export localhost.docker stats to InfluxDB (400: {"error":"unable to parse 'localhost.docker ': invalid field format"}
)
2017-06-18 11:11:42,791 -- ERROR -- Cannot export localhost.sensors stats to InfluxDB (400: {"error":"unable to parse 'localhost.sensors ': invalid field format"}
)
2017-06-18 11:11:42,795 -- ERROR -- Cannot export localhost.docker stats to InfluxDB (400: {"error":"unable to parse 'localhost.docker ': invalid field format"}
)
```

Errors show up even with
```
LOG_CFG=/usr/local/etc/glances/glances.json glances --export-influxdb -C /usr/local/etc/glances/glances.conf --disable-sensor
```
I will investigate on my own but would like to keep track on this and ask for any advice.

Thanks for this nice tool. Cheers
