### ISSUE TITLE
Monitor for reboot required or update available 

### ISSUE THREAD

**Issue by jasker5183** [nicolargo/glances#752]
A feature request, title says it all.

**Comment by nicolargo** [comment]
If i understand your need, you want a new plugin (ou update an existing one) to monitor system update (and additional info if a reboot is necessary).

Following points should be take into account:
* how to monitor system update on GNU/Linux (distrib dependant), *Bsd, Mac OS , Windows ?
* how to check if a reboot is mandatory to apply the patchs 
* where to display this plugin (a new one) or update the system one ?

**Comment by jasker5183** [comment]
Just came up with the idea because on Ubuntu I have landscape installed and it puts scripts in the /etc/update.motd.d that tells you if a reboot is required or updates are available when you ssh in, and I thought it would be great if Glances monitored for this. No idea how to make it distro agnostic though.

**Comment by nicolargo** [comment]
Perhaps, the best way to process is to use the existing [monitor] section of the Glances configuration file: 

    [monitor]
    list_1_description=System update
    list_1_regex=.*glances.*
    list_1_countmin=1
    list_1_command=sed '5!d' /etc/motd

Note: please replace 5 by the line number where the update info is available.

**Comment by jasker5183** [comment]
The file /etc/update-motd.d/90-updates-available contains

    #!/bin/sh
    if [ -x /usr/lib/update-notifier/update-motd-updates-available ]; then
    exec /usr/lib/update-notifier/update-motd-updates-available
    fi

The 98-reboot-required contains:

    #!/bin/sh
    if [ -x /usr/lib/update-notifier/update-motd-reboot-required ]; then
    exec /usr/lib/update-notifier/update-motd-reboot-required
    fi

How do I work that into the monitor section my /etc/motd seems to be auto-generated though landscape-sysinfo running it's scripts and adding my issue.net. For the reboot required could I just run for example:

    list_1_command=if [ -f /var/run/reboot-required ]; then echo 'Restart required'; fi


Or how would I go about doing this?

**Comment by nicolargo** [comment]
Is this configuration works ?

Edit your glances.conf file:

    [monitor]
    list_1_reg=.*glances.*
    list_1_countmin=1
    list_1_command=if [ -f /var/run/reboot-required ]; then echo 'Restart required'; fi

Run Glances with:

    glances -C <pathto>/glances.conf

**Comment by nicolargo** [comment]
@jasker5183 Any head up ?

**Comment by jasker5183** [comment]
I never got that to work and have since switched from Ubuntu to Centos. On Centos they just monitor for kernel changes to know if a reboot is required (script below), I also only run Glances in web server mode so that might have been why it didn't work on Ubuntu. 

`#!/bin/bash
LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1)
CURRENT_KERNEL=$(uname -r)

test $LAST_KERNEL = $CURRENT_KERNEL || echo ***REBOOT REQUIRED***`

I just run that as a script in /etc/profile.d so when I ssh in it will tell me if a reboot is required. Still no idea how you would implement this and make it distro agnostic.

**Comment by vena** [comment]
fwiw - the reason that workaround wasn't working appears to be that monitor lists need a description or they won't display.  the description can be empty, it just has to exist.  this worked for me:

```
[monitor]
list_1_description=
list_1_reg=.*glances.*
list_1_countmin=1
list_1_command=if [ -f /var/run/reboot-required ]; then echo 'Restart required'; fi
```

**Comment by nicolargo** [comment]
Workaround OK. Need to be migrated to the [AMP module](http://glances.readthedocs.io/en/stable/aoa/amps.html) in Glances 2.7 or higher:

[amp_monitor]
enable=true
regex=.*glances.*
refresh=60
one_line=false
command=if [ -f /var/run/reboot-required ]; then echo 'Restart required'; fi
countmin=1
