### ISSUE TITLE
glances not running on Raspberry Pi (py-cpuinfo)

### ISSUE THREAD

**Issue by krmnn** [nicolargo/glances#754]
I installed glances on a Raspberry Pi (Modell B) via the auto install script provided in Readme.mst.

When running glances it returns following error message:

    root@host ~ # glances -w
    py-cpuinfo currently only works on X86 and ARM CPUs.

The Raspberry runs an ARM processor. So either this is a bug or the error message is misleading.

    root@host ~ # cat /proc/cpuinfo
    Processor       : ARMv6-compatible processor rev 7 (v6l)
    BogoMIPS        : 697.95
    Features        : swp half thumb fastmult vfp edsp java tls
    CPU implementer : 0x41
    CPU architecture: 7
    CPU variant     : 0x0
    CPU part        : 0xb76
    CPU revision    : 7
    Hardware        : BCM2708
    Revision        : 000d
    Serial          : 0000000066564a8f

**Comment by nicolargo** [comment]
Strange, can you entre the following command and paste me back the result in a new comment:

    $ python
    >>> import cpuinfo

Thanks in advance

**Comment by krmnn** [comment]
Problem might be related to python version?

    root@host ~ $ python
    Python 2.7.9 (default, Mar  8 2015, 00:52:26)
    [GCC 4.9.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cpuinfo
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named cpuinfo
    >>> 

And:

    root@host ~ $ python3.4
    Python 3.4.2 (default, Oct 19 2014, 13:31:11)
    [GCC 4.9.1] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cpuinfo
    >>>


The system used to be a Debian Wheezy and was updated to Debian Jessie via dist-upgrade.

**Comment by nicolargo** [comment]
Nope, i investigate on my side and the problem came from the Cpuinfo lib. When the lib is loaded on a non supported CPU, the lib call an ugly sys.exit(0) (see https://github.com/workhorsy/py-cpuinfo/blob/master/cpuinfo/cpuinfo.py#L1478).

I just publish a (also ugly) work around on the develop branch...
