### ISSUE TITLE
Add IOps in the DiskIO plugin

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#763]
Add IO per second R/W thanks to the psutil.disk_io_counters(perdisk=True):
* read_count: number of reads
* write_count: number of writes

Add a command line option and a short key to switch between rate and IO.

**Comment by nicolargo** [comment]
Done for the core / Curses interface.

@nclsHart : Can you implement it on the WebUI ?

**Comment by notFloran** [comment]
@nicolargo I 'm on it

**Comment by nicolargo** [comment]
Thks @notFloran  !
