### ISSUE TITLE
How can i show the state of some  node server

### ISSUE THREAD

**Issue by kevincaradant** [nicolargo/glances#767]
Hi

Sorry i begin with this dashboard very usefull and powerfull but in my case i have two node server ( api and front ) which run on my server and i want to see if they run or not ( running,  error , turn off ) like you can see with pm2 when you write this command in the console `pm2 list` 

Thank you to help me with that :) , maybe there are some  files to config or something to create but i dont understand how is it work :/
Like this image , you have the status for each server , that will be perfect in my case if i can see that in the web interface :) 
 
![image](https://cloud.githubusercontent.com/assets/6093175/12127494/c68d2710-b3f7-11e5-9595-a3164df8896f.png)

I see that http://blog.nicolargo.com/2013/08/presentation-des-nouveautes-de-glances-1-7.html , that speak about glances.conf but where is this file because i install glances with the shell script but i don't know where is the file to config :)

And also if you have any idea , how can i configure that ? thank you :)

**Comment by nicolargo** [comment]
Not possible for the moment.
Have to create a new Node JS PM plugin (https://github.com/Unitech/pm2).

**Comment by kevincaradant** [comment]
Ah yes but in your app that Will be very better  because,  i used keymetrics but its free only for one server and the Web site is not on local,  you have to create à account so i dont like this :/. Do you know if you Will decide soon to do this feature ? :).  Thank and great job for your monitoring app

**Comment by nicolargo** [comment]
The roadmap is frozen for the next release 2.6. 
Perhaps in the 2.7. Wait for another users asked for this feature.

**Comment by kevincaradant** [comment]
oki i hope for the 2.7 :D

**Comment by nicolargo** [comment]
Any other users interested by this feature ?

**Comment by nclsHart** [comment]
If there is no other users interested in this feature, I think this feature could be related to #549.

**Comment by nicolargo** [comment]
Or related to this one: https://github.com/nicolargo/glances/issues/780

**Comment by nicolargo** [comment]
REJECTED: use the AMP module in Glances 2.7.
