### ISSUE TITLE
What is the protocol to install it on CentOS6 with python 2.6.6 

### ISSUE THREAD

**Issue by kevincaradant** [nicolargo/glances#769]
Hi

I wish to install it on centOS but every tricks or install that i found are too old and server dead :/

Thank you in advance to help me to install it :)

**Comment by widgetpl** [comment]
hi,
if you have tried to install it with `yum` i would suggest to try that:
`curl -L http://bit.ly/glances | /bin/bash`
or
`wget -O- http://bit.ly/glances | /bin/bash`
as @nicolargo said linux repos have old versions.

**Comment by kevincaradant** [comment]
ok  thank you, in fact , i had a problem with python-pip , it's good now :)
