### ISSUE TITLE
Fahrenheit rounding problem

### ISSUE THREAD

**Issue by justindoran** [nicolargo/glances#776]
There is some minor rounding issue in the display of Fahrenheit temperatures from sensors. I've attached a gif demonstrating the problem. It works fine on Celsius, and the temperatures are displayed as whole numbers. I couldn't quite figure out why the format function wasn't catching it, but it's returning unrounded decimals for some reason. This messes up the entire display.

![out](https://cloud.githubusercontent.com/assets/3846066/12224702/8a13268a-b7bd-11e5-8315-32cc5bee932f.gif)

**Comment by nicolargo** [comment]
@justindoran waht is your Glances version ?

**Comment by justindoran** [comment]
Glances v2.5.1 with psutil v3.3.0

**Comment by nicolargo** [comment]
Already corrected in the develop branch.

Just wait the version 2.6 ;)

**Comment by justindoran** [comment]
Thanks. :+1:  :)
