### ISSUE TITLE
Relatively high CPU use by glances

### ISSUE THREAD

**Issue by rogorido** [nicolargo/glances#777]
Hi, first of all many thanks for the great app. I'm using it on a laptop with archlinux (version 2.5.1). Glances uses (in my opinion) too much resources, since it uses always in my computer 12-17% CPU. I tried the options -2, -3, -4 with no change. 

Is this normal?

**Comment by nicolargo** [comment]
Duplicated thread: https://github.com/nicolargo/glances/issues/519

**Comment by rogorido** [comment]
sorry. I checked only the opened issues... thanks!
