### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by ZeroManArmy** [nicolargo/glances#778]
**OS:** Windows 8.1
**Python Version:** 2.7
**Setup Tools:** Installed
**Pip Addons Installed:** bottle, pysnmp, zeroconf, netifaces, influxdb, statsd, pystache, matplotlib, pika, and py-cpuinfo

When I double click the executable in the `C:\Python27\Scripts` folder, the command line version loads up. When launching the executable with the `-w` flag it says `Glances web server started on http://0.0.0.0:61208/` and then sits there with no errors.

When I go to `http://localhost:61208/` I just get the loading eye with the 3 moving dots and nothing else. Is there something else I am supposed to do or make a change to?

**Comment by notFloran** [comment]
Can you go to ```http://localhost:61208/```, open the web console (for [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) , for [Chrome](https://developer.chrome.com/devtools/docs/console)) and paste me back the result in a new comment.

Thanks in advance

**Comment by Cozza38** [comment]
Hi @notFloran,

I'm receiving the same issue as described above, very similar environment. Here's my console log, the error counts up every few seconds:

```
ReferenceError: nice is not defined
    at setData (glances_processlist.js:33)
    at getPlugin (glances_stats.js:76)
    at GlancesStats.getData.then.$scope.is_disconnected (stats_controller.js:74)
    at J (angular.js:11749)
    at angular.js:11881
    at h.$eval (angular.js:12961)
    at h.$digest (angular.js:12678)
    at h.$apply (angular.js:13015)
    at m (angular.js:8404)
    at w (angular.js:8594)
```

**Comment by notFloran** [comment]
Hi @Cozza38,

Ok, actually it a known bug and corrected in the develop version (PR #717).

@nicolargo I do the same PR for master branch ?

**Comment by nicolargo** [comment]
@notFloran Nope. No pull on the master branch.

**Comment by mattman86** [comment]
When will the fix be merged to the master branch?

**Comment by nicolargo** [comment]
March 2016.
But you can use the develop version by following this procedure: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version
