### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by ncstdc** [nicolargo/glances#779]
I'm trying to reverse proxy using nginx, but all the xhr requests are trying to pull resources from the server root. Here is my location block -

```
location /glances/ {
 rewrite /glances/(.*) /$1 break;
 proxy_pass http://localhost:61208/;
 proxy_set_header Host $http_host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
}
```

http://domain/glances/ loads properly, but app.js is trying to pull stats.html from http://domain/ rather than http://domain/glances/. I've tried various rewrite and proxy_redirect rules and can't get it to work properly.

**Comment by nicolargo** [comment]
Never done this with Nginx, but one user post me the reverse proxy configuration for Apache. Hope it will help.

https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

**Comment by ncstdc** [comment]
I saw that and tried to use rewrite/redirect rules based on it, but without success. I have several other apps working using standard nginx reverse proxy configurations, but can't get this one to work.

**Comment by notFloran** [comment]
Try this : 

```
location / {
  if ($http_referer ~ "^https?://[^/]+/glances"){
    rewrite ^/(.*) /glances/$1 redirect;
  }
}

location /glances/ {
  rewrite /glances/(.*) /$1 break;
  proxy_pass http://localhost:61208/;
  proxy_redirect     off;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by ncstdc** [comment]
that seems to be working

**Comment by nicolargo** [comment]
Thanks @notFloran you are a (web)genious !

**Comment by nicolargo** [comment]
New section added to the Wiki: https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

**Comment by jgillman** [comment]
:+1: Worked for me! Thanks for adding the wiki article.

**Comment by LastStarFighter** [comment]
Has anyone tried to get glances to reverse proxy with caddy server? Was thinking of trying to use caddy instead of nginx since caddy can handle the https certs automatically.
