### ISSUE TITLE
Add a new Application Monitoring Process

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#780]
In the current version (2.x), Glances displays 3 kinds of process information:
- the monitoring process plugins (configurable through the Glances conf file) which allows user to define a list of process (or group of processes) to monitor on top of the others. For each item in the list, a command line could be executed and the result display in the Glances UI. If the command line is not defined then Glances display the item CPU and MEM.
- the process list display the list of running processes sorted dynamically depending on the environment.
- optionally (using the --enable-process-extended option or the `e`short key), additional information are displayed for the top process.

We propose to add a new feature to improve (or replace) process monitoring. 

For each process, an Application Monitoring Process Plugin (AMPP) could be execute to grab additional information.  For example, the Nginx AMPP will grab:
- Req/s – How many requests per second is NGINX handling
- Conn/s – How many incoming connections clients are making each second

The plugin should be defined in the new glances/plugins/amp/ folder. For example glances/plugins/amp/glances_nginx.py

A new section should be defined in the configuration file to enable the application monitoring and define mandatory or optional configuration. For example for the Nginx application:

    [amp_nginx]
    enable=true
    regex=\/usr\/bin\/nginx
    refresh=60
    one_line=false
    status_url=http://localhost/nginx_status

With:
- enable: the AMP is enabled (mandatory)
- regex: the regular expression to match the Nginx application (mandatory)
- refresh: the refresh rate (in second). The Nginx AMP will be executed every 60 seconds (in a separated thread). (mandatory)
- one_line: If true, force the AMP plugin to display the result in one line
- the variable status_url should be set to http://localhost/nginx_status inside the glances_nginx.py script

Questions to be discussed:
- Where to display this plugin in the Glances UI ? 
==> On top of the process list.
- How to display the result ? One line ? Multiple line ? 
==> Could be configured via the configuration file (one_line parameter)
- Merge AMP and Monitoring process plugin ?
==> Yes, a default AMP will be used if no one existing in the amps folder. This default behavior will execute the 'command' parameter. Note: add to implement countmin/countmax parameter for all the AMP.

**Comment by nicolargo** [comment]
AMP scripts are defined in the glances/amps folder. For example, the Nginx AMP will be defined in the glances/amps/glances_nginx.py script.

**Comment by nicolargo** [comment]
@asergi / @nclsHart  / @nclsHart : Need your feedback about this *under development* feature.

**Comment by nicolargo** [comment]
Merged to the develop branch.

To test it, edit and use the new conf file:

    python -m glances -C ./conf/glances.conf

@nclsHart or @notFloran : Need some help to finalized the WebUI. The AMP plugins should:

- not display line if result is empty.
- should replace '\n' by <br /> in the result.
- be disable if 'A' shortkey is pressed (have done something but did not work...)

**Comment by nclsHart** [comment]
@nicolargo the new 'A' shortcut is missing from the help page (curse and webui), should I add it?

**Comment by nicolargo** [comment]
@nclsHart be my guest...

**Comment by carlba** [comment]
Where do you put these amps files are they read from the config directory or do they have to be in the source?

**Comment by nicolargo** [comment]
@carlba the embeded AMP Python files (https://glances.readthedocs.io/en/stable/aoa/amps.html#embeded-amp) should be hosted in the glances/amps/ source folder. The script should be named glances_foo.py (replace foo by your AMP name).
