### ISSUE TITLE
File System Plugin: does not display network mount & displays wrong stats (afpfs)

### ISSUE THREAD

**Issue by mannibis** [nicolargo/glances#782]
Hi,

I edited the .conf file with 

[fs]
allow = zfs,misc

But my /mnt directory still does not show up under File System

Is there anything else I should add to the configuration file to display free/used space on the /mnt mountpoint?

Right now, all I see is:

/ (/dev/disk0s2)

I'm running OSX 10.9.5 (Mavericks)

**Comment by nicolargo** [comment]
Hi @mannibis can you send us the following information:
- your Glances and PsUtil versions (*glances -v*)
- an output of the *mount* command line

Thanks

**Comment by mannibis** [comment]
Glances v2.5.1 with psutil v3.4.2

/dev/disk0s2 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
map auto_nas on /mnt/QNAP (autofs, automounted, nobrowse)
//admin@qnappro/Public on /mnt/QNAP/Public (afpfs, nodev, nosuid, automounted, nobrowse, mounted by Manny-MacMini)

Thank you @nicolargo

**Comment by nicolargo** [comment]
Try this:

    [fs]
    allow=zfs,misc,afpfs,autofs

**Comment by mannibis** [comment]
Wonderful! Thank you so much, that worked.

How do I hide shares from the FileSystem module (same goes for Network)? I read in the docs that this is possible and to use the [network] tag in the conf, but what exactly do I put?

**Comment by nicolargo** [comment]
To hide /boot/efi folder from the Filesystem plugin:

    [fs]
    hide=/boot/efi

**Comment by mannibis** [comment]
Thank you,

Now that I look at the FS plugin again, it looked right, but the numbers are definitely off

With F mode off it shows:

/mnt/QNAP/Public (//admin@qnappro/Public)	-2985566257152	5.59T

with F mode on it shows:

/mnt/QNAP/Public (//admin@qnappro/Public)	-2985566257152	5.59T

With F mode on it shows:

/mnt/QNAP/Public (//admin@qnappro/Public)	8.30T	5.59T

So something is def wrong, maybe I can edit the plugin file? Seems like a math problem

**Comment by mannibis** [comment]
df -h displays this:

Filesystem                         Size   Used  Avail Capacity    iused              ifree             %iused       Mounted on
//admin@qnappro/Public   22Ti   13Ti  8.3Ti  62%          3566069303 2228848228   62%   /mnt/QNAP/Public

**Comment by mannibis** [comment]
Looks like the problem is in PSUtils....

>>> fs_usage = psutil.disk_usage('/mnt/QNAP/Public')
>>> fs_usage
sdiskusage(total=6143796170752, used=-2980872179712, free=9124668350464, percent=-48.5)

**Comment by nicolargo** [comment]
Not a Glances bug.
=> PsUtil issue: https://github.com/giampaolo/psutil/issues/735

**Comment by giampaolo** [comment]
It turns out this is probably an OSX bug:
https://github.com/giampaolo/psutil/issues/735#issuecomment-175455659
