### ISSUE TITLE
Issues with vendored minified javascript files

### ISSUE THREAD

**Issue by sbadia** [nicolargo/glances#788]
Hi, just for tracking/information, we (in Debian) remove vendored minified js because of those two lintian issues.

* https://lintian.debian.org/tags/source-contains-prebuilt-javascript-object.html
* https://lintian.debian.org/tags/source-is-missing.html

I feed this issue just in order to know if we can do something upstream side ;-)

**Comment by sbadia** [comment]
For the record https://lists.debian.org/debian-mentors/2016/01/msg00341.html

**Comment by nicolargo** [comment]
Hi Sebastien,

thanks for the head up (and also for your work on the next Glances Debian package).

@nclsHart or @notFloran : Can you have a look on the orphan js file ?

**Comment by notFloran** [comment]
Hi,

Errors : 

* source-contains-prebuilt-javascript-object
* source-is-missing

Files : 

* glances/outputs/static/js/vendors/angular-route.min.js
* glances/outputs/static/js/vendors/angular.min.js
* glances/outputs/static/js/vendors/lodash.min.js

If we replace the files by their no minified versions is it going to fix the problem ?

**Comment by nicolargo** [comment]
@notFloran I think so.

**Comment by nicolargo** [comment]
@sbadia Should be corrected in the latest commit (DEVELOP branch).
Can you have a look ?

**Comment by sbadia** [comment]
Hi here!

Yes, perfect :-) thanks @notFloran @nicolargo !
