### ISSUE TITLE
Use wildcard (regexp) to the hide configuration option for network, diskio and fs sections 

### ISSUE THREAD

**Issue by rmenessec** [nicolargo/glances#799]
On the systems I usually run glances on (Ubuntu / Debian), there are as many as 16 ram[0-9][0-9] devices littering the block device I/O display, forcing out storage devices I want to be able to see, and in some cases even pushing the sensors completely out of the UI.

Some way to exclude block devices by regex would be appreciated. Hiding ramdisks by default would be great, too.

Thanks!

**Comment by nicolargo** [comment]
Duplicated issue: https://github.com/nicolargo/glances/issues/714

**Comment by rmenessec** [comment]
Please add at least basic wildcard support.

Is it possible to hide filesystems as well? This isn't mentioned in the documentation, and I have bind mounts and AuFS mounts on some systems that I'd like to be able to hide. These are not "physical" filesystems as described in the documentation, but they're appearing in the filesystem list. I assume union mounts and fuse mounts might have the same problem...

Filtering by both filesystem mount type and by name regex would be appreciated.

Thanks!

**Comment by chesedo** [comment]
It would also be nice to see the wildcard support for the `hide` on `Network` devices (to hide all virtual docker interfaces)

**Comment by nicolargo** [comment]
Functions implemented for network, diskio and filesystem plugins in the latest commit: 5497ae1

For example, if you want to hide the loopback interface (lo) and all the virtual docker interface (docker0, docker1...):

    [network]    
    hide=lo,docker.*

For example, if you want to hide the loopback disks (loop0, loop1..) and the specific sda5 disk:

    [diskio]
    hide=sda5,loop.*

For example, if you want to hide boot mount points:

    [fs]
    hide=/boot.*   

@rmenessec / @chesedo : Please test the develop branch !

**Comment by chesedo** [comment]
This seems to be working for me (tested diskio and network).

A note diskio's does also work in the web interface mode, but not network's.

**Comment by nicolargo** [comment]
@notFloran: Can you have a look on the diskio hide option support for the Web UI (see lasts comments) ?

**Comment by notFloran** [comment]
@nicolargo In the diskio plugin hiding is done in the *update* method so it works in the web interface, but for the network plugin hiding is done in the *msg_curse* method.

What is the correct method?

**Comment by nicolargo** [comment]
I think that msg_curse method is better. I will have a look why it is done in the update method for the diskio plugin...

**Comment by notFloran** [comment]
One problem is that the WebUI doesn't have access to the values stored in the configuration file.

**Comment by nicolargo** [comment]
@notFloran Ok, i will manage it on the Core side through the update method.

**Comment by nicolargo** [comment]
@notFloran : Done c9dce8a
