### ISSUE TITLE
Glances wont work with Windows 10 python 2.7 and 3.4

### ISSUE THREAD

**Issue by Exasis** [nicolargo/glances#800]
I have an issue with running Glances on my computer running Windows 10

The issue is that: When i use the Webserver (glances -w) and access it through "127.0.0.1:61208" it will just show the loading screen and not move on from there (i've let it run for an hour)

**Which versions are you running?**
I have tried:
Python: 2.7 and 3.4
Glances: 2.5.1 and 2.6beta
psutil: 4.0.0

**What about standalone?**
The standalone server works, i got to the right screen in my CMD

**Does the API respond?**
Yes, it responds with something like this:
<img width="500" alt="screenshot 2016-02-23 09 50 53" src="https://cloud.githubusercontent.com/assets/13125021/13246291/07cf8736-da13-11e5-931a-53ac4b87b2d6.png">

**Comment by nicolargo** [comment]
Hi @Exasis . Thanks for the report.

Is there any message in the log file (%APPDATA%\Local\temp\glances.log) ?

**Comment by Exasis** [comment]
This is the log:
http://pastebin.com/CdB7EiSc

**Comment by Exasis** [comment]
I dont know if it makes a difference, but Glances is installed using pip

**Comment by nicolargo** [comment]
Can you paste/bin the result of "pip list" command ?

**Comment by nicolargo** [comment]
Ok found:

2016-02-21 18:39:10,242 -- CRITICAL -- Bottle module not found. Glances cannot start in web server mode.

You need to install the Bottle Python lib in order to make the WebUI works.
Read: https://github.com/nicolargo/glances#requirements

**Comment by Exasis** [comment]
<img width="174" alt="screenshot 2016-02-23 11 16 59" src="https://cloud.githubusercontent.com/assets/13125021/13248512/089435ca-da1f-11e5-8614-ad007fe24419.png">

**Comment by Exasis** [comment]
I installed the bottle module when i recieved the error

**Comment by nicolargo** [comment]
Oopss, just read the first error message...

**Comment by nicolargo** [comment]
One more think,can you run Glances 2.6 with the debug mode enable and send us back the log file ?

    glances -d -w

Thanks !

**Comment by Exasis** [comment]
Here it is: http://pastebin.com/vh4vtFzC

I have also taken the liberty to remove the logs posted before today, to minimize the amount of text you have to sift through :)

**Comment by nicolargo** [comment]
Strange, do not see any issue... 

@notFloran or @nclsHart : can you have a look on the log file (http://pastebin.com/vh4vtFzC) the WebUI is not displayed...

**Comment by Exasis** [comment]
It is showing some additional information in the CMD as well. I am getting this information:
<img width="450" alt="screenshot 2016-02-23 11 35 20" src="https://cloud.githubusercontent.com/assets/13125021/13248953/9c461f7a-da21-11e5-83e5-fcf12f62c8ba.png">

**Comment by notFloran** [comment]
The error in the CMD is fixed in develop (#760).

Can you run glances without debug and go to ```http://localhost:61208/```, open the web console (for [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) , for [Chrome](https://developer.chrome.com/devtools/docs/console)) and paste me back the result in a new comment.

**Comment by Exasis** [comment]
So i should download the develop branch and see if it works?

**Comment by Exasis** [comment]
@notFloran The fix in the develop-branch worked!

**Comment by Exasis** [comment]
Oh i'm sorry i clicked the wrong button in my eagerness. The fix worked and the only "issues" shown is a few with bootstrap
<img width="1275" alt="screenshot 2016-02-25 10 32 48" src="https://cloud.githubusercontent.com/assets/13125021/13315488/3d6d5636-dbab-11e5-9807-9239e285e43d.png">
