### ISSUE TITLE
Crash on running a new Docker container

### ISSUE THREAD

**Issue by bacondropped** [nicolargo/glances#802]
Running any non-privileged Docker container results in consistent glances crash with the following stack trace:

![2016-02-24-162330_787x268_scrot](https://cloud.githubusercontent.com/assets/9872501/13286567/4c4eeee6-db13-11e5-80bf-6689619913df.png)

Steps to reproduce:

```
$ # login as non-privileged user
$ glances # glances is running, switch to another terminal
$ docker run -t -i ubuntu /bin/bash # glances displays Docker stats for less than a second (apparently, loading) and crashes
```

Or, alternatively,
```
$ # login as non-privileged user
$ docker run -t -i ubuntu /bin/bash # interactive session is running, switch to another terminal
$ glances # crashes immediately
```

My current configuration:

1.  Ubuntu 16.04
2.  Linux 4.4.0-7-generic x86_64
3.  glances from pip (v2.5.1 with psutil v3.3.0), also able to reproduce with curl installation and direct Git clone [at commit bcff182](https://github.com/nicolargo/glances/commit/bcff18231d0c6866af85a654f2af6f2251601af9)
4.  docker version 1.6.2, build 7c8fca2, setup to run without sudo via usermod as per [this stackoverflow answer ](http://stackoverflow.com/a/29754871/2759849)
5.  docker-py from pip (version 1.7.2)
6.  python 2.7.11

**Comment by bacondropped** [comment]
Update: could not reproduce on `ubuntu/trusty64` Vagrant box with the following configuration:

1.  Ubuntu 14.04.3 LTS image
2.  Linux 3.13.0-79-generic x86_64
3.  Direct Glances clone [at bcff182](https://github.com/nicolargo/glances/commit/bcff18231d0c6866af85a654f2af6f2251601af9) with psutil v4.0.0
4.  Docker version 1.10.2, build c3959b1, usermod setup
5.  docker-py from pip (version 1.7.2)
6.  python 2.7.6

**Comment by nicolargo** [comment]
Not reproduce on my configuration:

1.     CentOS 7.1
2.     Linux 3.10.0-327.4.5.el7.x86_64
3.     Direct Glances clone at bcff182 with psutil v4.0.0
4.     Docker version 1.8.2, usermod setup
5.     docker-py (1.6.0)
6.     python 2.7.5

**Comment by bacondropped** [comment]
Further debugging detected the configuration error. I had docker installed from the `docker.io` package (`universe/admin`), and it seemed to be outdated, so I purged it and switched to `docker-engine` [as per official instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/).

This error can be detected by either checking installed packages, or running the following in Python REPL:
```
>>> from docker import Client
>>> cli = Client(base_url='unix://var/run/docker.sock')
>>> cli.containers()
```

Erroneous configuration error out with the "client and server don't have same version" message.
