### ISSUE TITLE
CPU additionnal stats monitoring: Context switch, Interrupts...

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#810]
PSUtil 4.1.0 introduces a new function to monitor the context switch (CS) (http://pythonhosted.org/psutil/#psutil.cpu_stats).

A context switch occurs when the kernel switches the processor from one thread to another—for example, when a thread with a higher priority than the running thread becomes ready. Context switching activity is important for several reasons. A program that monopolizes the processor lowers the rate of context switches because it does not allow much processor time for the other processes' threads. A high rate of context switching means that the processor is being shared repeatedly—for example, by many threads of equal priority. A high context-switch rate often indicates that there are too many threads competing for the processors on the system. (source https://technet.microsoft.com/en-us/library/cc938606.aspx).

The goal is to implement the monitoring of CPU CS into Glances:
- where ? CPU plugin ?
- optionnal ?
- limit rate ? (http://stackoverflow.com/questions/2794499/how-expensive-is-a-context-switch-is-it-better-to-implement-a-manual-task-switc)

Other resources:
- http://www.thomaskoetzing.de/index.php?option=com_content&task=view&id=196&Itemid=85

**Comment by nicolargo** [comment]
Implemented in the latest commit.

Tested on Linux.
Need tests on others OS: BSD, Mac and Windows.

@nclsHart : Can you implement the WebUI part ?

**Comment by nclsHart** [comment]
Tested under osx (Glances v2.7_BETA with psutil v4.1.0).

I get some negative values : 

<img width="340" alt="cpu" src="https://cloud.githubusercontent.com/assets/833625/14245006/acc2b8ba-fa5e-11e5-88b7-8d7730c67ddb.png">

**Comment by nicolargo** [comment]
@nclsHart can you enter the following command on a terminal and copy/paste the result ?

```
# python
>>> import psutil
>>> psutil.cpu_stats()
Wait 3 seconds...
>>> psutil.cpu_stats()
```

**Comment by nclsHart** [comment]
@nicolargo Yep, I got the following result: 

```
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.cpu_stats()
scpustats(ctx_switches=465588, interrupts=641985, soft_interrupts=52389351, syscalls=683396)
>>> psutil.cpu_stats()
scpustats(ctx_switches=465294, interrupts=641591, soft_interrupts=52390466, syscalls=683397)
```

**Comment by nicolargo** [comment]
Clearly a PsUtil issue... 

The cpu_stats() method should return the number of stats since boot (http://pythonhosted.org/psutil/#psutil.cpu_stats). So it is not possible to have 465588 and 465294 ctx_switches...

Can you open an issue on the PsUtil tracker (and add the link in the Glances issue): https://github.com/giampaolo/psutil/issues ?
