### ISSUE TITLE
[feature] Support system authentication like LDAP/Kerberos

### ISSUE THREAD

**Issue by ImNtReal** [nicolargo/glances#811]
Would it be possible to add a feature to require users to authenticate as a user on the system instead of an arbitrary password? Thanks.

**Comment by nicolargo** [comment]
Duplicated ? https://github.com/nicolargo/glances/issues/693

**Comment by ImNtReal** [comment]
This would be a little different that specifying a username/password. In theory, if integrated properly it would also work with external authentication mechanisms that the system is set up to use like LDAP/Kerberos.

**Comment by nicolargo** [comment]
Ok, i understand your need. 

Is there another user interested by this feature ?

**Comment by towo** [comment]
Need no, interested yes; it would probably be sufficient to just hook into PAM and let that do the heavy lifting.
