### ISSUE TITLE
[WebUI] Glances will not get past loading screen - Windows OS

### ISSUE THREAD

**Issue by jjbrunton** [nicolargo/glances#815]
http://localhost:61208/api/2/all

returns

Cannot get stats ('utf8' codec can't decode byte 0xb5 in position 0: invalid start byte)

**Comment by nicolargo** [comment]
Hi, what is your Glances version ?

**Comment by jjbrunton** [comment]
Glances v2.7_BETA with psutil v3.3.0

**Comment by nicolargo** [comment]
@asergi Any idea ? Looks like an encoding issue (one more time)

**Comment by nicolargo** [comment]
@jjbrunton Can you try the following commands:

    glances -w --disable-sensors

Is it working ?

Then additionnaly, run glances in debug mode and send us back the Glances log file (http://glances.readthedocs.org/en/latest/config.html#logging):

    glances -w -d

Thanks in advance !

**Comment by jjbrunton** [comment]
> Glances web server started on http://0.0.0.0:61208/
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:61208/
Hit Ctrl-C to quit.

192.168.0.3 - - [17/Mar/2016 22:47:09] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:09] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:11] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:11] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:14] "GET / HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /normalize.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /bootstrap.min.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /style.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /vendors/angular.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /app.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /filters.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /variables.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /directives.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/core/glances_stats.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_plugin.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_alert.js H
TTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_cpu.js HTT
P/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_diskio.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_docker.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_fs.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_folders.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_ip.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_load.js HT
TP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_mem.js HTT
P/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_memswap.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_monitor.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_network.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_percpu.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_processcou
nt.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_processlis
t.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_quicklook.
js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_raid.js HT
TP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_sensors.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_system.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /services/plugins/glances_uptime.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:16] "GET /stats_controller.js HTTP/1.1" 304 0

192.168.0.3 - - [17/Mar/2016 22:47:37] "GET / HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /normalize.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /bootstrap.min.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /style.css HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /vendors/angular.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /vendors/angular-route.js HTTP/1.1"
304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /vendors/lodash.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /app.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /filters.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /variables.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /directives.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /services/core/glances_stats.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /services/plugins/glances_plugin.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:37] "GET /services/plugins/glances_alert.js H
TTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_cpu.js HTT
P/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_diskio.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_docker.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_fs.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_folders.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_ip.js HTTP
/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_load.js HT
TP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_mem.js HTT
P/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_memswap.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_monitor.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_network.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_percpu.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_processcou
nt.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_processlis
t.js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_quicklook.
js HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_raid.js HT
TP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_sensors.js
 HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_system.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /services/plugins/glances_uptime.js
HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /stats_controller.js HTTP/1.1" 304 0

192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /api/2/all/limits HTTP/1.1" 200 2059

192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /api/2/help HTTP/1.1" 200 2345
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /api/2/args HTTP/1.1" 200 1497
192.168.0.3 - - [17/Mar/2016 22:47:38] "GET /stats.html HTTP/1.1" 304 0
192.168.0.3 - - [17/Mar/2016 22:47:40] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:40] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:43] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:43] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:46] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:46] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:49] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:49] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:52] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:52] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:55] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:47:55] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:47:58] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:48:13] "GET /api/2/all/views HTTP/1.1" 200 8264
192.168.0.3 - - [17/Mar/2016 22:48:15] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:48:16] "GET /api/2/all/views HTTP/1.1" 200 8265
192.168.0.3 - - [17/Mar/2016 22:48:18] "GET /api/2/all HTTP/1.1" 404 811
192.168.0.3 - - [17/Mar/2016 22:48:18] "GET /api/2/all/views HTTP/1.1" 200 8264

**Comment by nicolargo** [comment]
@notFloran / @nclsHart : Any idea ?

**Comment by jjbrunton** [comment]
Here's the full log:

http://pastebin.com/htDbmRz8

**Comment by notFloran** [comment]
@jjbrunton Can you go to "http://0.0.0.0:61208/api/2/all" with your browser ? What is the output ?

**Comment by nicolargo** [comment]
@notFloran : i think that the answer is in the first comment: https://github.com/nicolargo/glances/issues/815#issue-141530554
It return: Cannot get stats ('utf8' codec can't decode byte 0xb5 in position 0: invalid start byte)

**Comment by nclsHart** [comment]
We need to know if this is a global error or an error due to a specific plugin.

Please @jjbrunton, can you try if you have the same error on this 2 plugin endpoints : 

* [http://localhost:61208/api/2/uptime](http://localhost:61208/api/2/uptime)
* [http://localhost:61208/api/2/system](http://localhost:61208/api/2/system)

**Comment by jjbrunton** [comment]
Both of those endpoints return 200 with the correct information @nclsHart

**Comment by nclsHart** [comment]
Ok. So the problem seems to come from one of the plugins.

Can you try all of the plugins availables [here](http://localhost:61208/api/2/pluginslist) like you have done for the uptime and system plugin (http://localhost:61208/api/2/:plugin_name), and tell us if you encounter an error on one of this endpoints.

**Comment by jjbrunton** [comment]
@nclsHart 

```
Sorry, the requested URL 'http://jhomeserver:61208/api/2/processlist' caused an error:

Cannot get plugin processlist ('utf8' codec can't decode byte 0xb5 in position 0: invalid start byte)
```

```
psutilversion returns null
```

Everything else looks good

**Comment by nclsHart** [comment]
Could you try to update psutil ?

**Comment by jjbrunton** [comment]
psutil version 4.1.0 - same issue. @nclsHart

**Comment by nicolargo** [comment]
Another user has this kind of error message => See https://github.com/nicolargo/glances/issues/745

@jjbrunton is there any error message in the console where you start Glances ?

@jjbrunton (again): can you run the script unitest-restful.py (in the Glances root folder) ?

**Comment by jjbrunton** [comment]
```
C:\Users\Jamie\Documents\glances>python unitest-restful.py
RESTful API unitary tests for Glances 2.7_BETA

==============================================================================
INFO: [TEST_000] Start the Glances Web Server
Run the Glances Web Server on port 61234
Please wait...
.
==============================================================================
INFO: [TEST_001] Get all stats
HTTP RESTful request: http://localhost:61234/api/2/all
Glances web server started on http://0.0.0.0:61234/
F
==============================================================================
INFO: [TEST_002] Plugins list
HTTP RESTful request: http://localhost:61234/api/2/pluginslist
.
==============================================================================
INFO: [TEST_003] Plugins
HTTP RESTful request: http://localhost:61234/api/2/load
HTTP RESTful request: http://localhost:61234/api/2/docker
HTTP RESTful request: http://localhost:61234/api/2/help
HTTP RESTful request: http://localhost:61234/api/2/ip
HTTP RESTful request: http://localhost:61234/api/2/memswap
HTTP RESTful request: http://localhost:61234/api/2/processlist
F
==============================================================================
INFO: [TEST_004] Items for the CPU method
HTTP RESTful request: http://localhost:61234/api/2/cpu/idle
HTTP RESTful request: http://localhost:61234/api/2/cpu/total
HTTP RESTful request: http://localhost:61234/api/2/cpu/user
HTTP RESTful request: http://localhost:61234/api/2/cpu/system
.
==============================================================================
INFO: [TEST_005] Item=Value for the PROCESSLIST method
http://localhost:61234/api/2/processlist/pid/0
.
==============================================================================
INFO: [TEST_006] Get all limits
HTTP RESTful request: http://localhost:61234/api/2/all/limits
.
==============================================================================
INFO: [TEST_007] Get all views
HTTP RESTful request: http://localhost:61234/api/2/all/views
.
==============================================================================
INFO: [TEST_008] Plugins limits
HTTP RESTful request: http://localhost:61234/api/2/load/limits
HTTP RESTful request: http://localhost:61234/api/2/docker/limits
HTTP RESTful request: http://localhost:61234/api/2/help/limits
HTTP RESTful request: http://localhost:61234/api/2/ip/limits
HTTP RESTful request: http://localhost:61234/api/2/memswap/limits
HTTP RESTful request: http://localhost:61234/api/2/processlist/limits
HTTP RESTful request: http://localhost:61234/api/2/uptime/limits
HTTP RESTful request: http://localhost:61234/api/2/monitor/limits
HTTP RESTful request: http://localhost:61234/api/2/percpu/limits
HTTP RESTful request: http://localhost:61234/api/2/system/limits
HTTP RESTful request: http://localhost:61234/api/2/diskio/limits
HTTP RESTful request: http://localhost:61234/api/2/folders/limits
HTTP RESTful request: http://localhost:61234/api/2/core/limits
HTTP RESTful request: http://localhost:61234/api/2/fs/limits
HTTP RESTful request: http://localhost:61234/api/2/raid/limits
HTTP RESTful request: http://localhost:61234/api/2/mem/limits
HTTP RESTful request: http://localhost:61234/api/2/alert/limits
HTTP RESTful request: http://localhost:61234/api/2/psutilversion/limits
HTTP RESTful request: http://localhost:61234/api/2/hddtemp/limits
HTTP RESTful request: http://localhost:61234/api/2/sensors/limits
HTTP RESTful request: http://localhost:61234/api/2/now/limits
HTTP RESTful request: http://localhost:61234/api/2/quicklook/limits
HTTP RESTful request: http://localhost:61234/api/2/network/limits
HTTP RESTful request: http://localhost:61234/api/2/processcount/limits
HTTP RESTful request: http://localhost:61234/api/2/batpercent/limits
HTTP RESTful request: http://localhost:61234/api/2/cpu/limits
.
==============================================================================
INFO: [TEST_009] Plugins views
HTTP RESTful request: http://localhost:61234/api/2/load/views
HTTP RESTful request: http://localhost:61234/api/2/docker/views
HTTP RESTful request: http://localhost:61234/api/2/help/views
HTTP RESTful request: http://localhost:61234/api/2/ip/views
HTTP RESTful request: http://localhost:61234/api/2/memswap/views
HTTP RESTful request: http://localhost:61234/api/2/processlist/views
HTTP RESTful request: http://localhost:61234/api/2/uptime/views
HTTP RESTful request: http://localhost:61234/api/2/monitor/views
HTTP RESTful request: http://localhost:61234/api/2/percpu/views
HTTP RESTful request: http://localhost:61234/api/2/system/views
HTTP RESTful request: http://localhost:61234/api/2/diskio/views
HTTP RESTful request: http://localhost:61234/api/2/folders/views
HTTP RESTful request: http://localhost:61234/api/2/core/views
HTTP RESTful request: http://localhost:61234/api/2/fs/views
HTTP RESTful request: http://localhost:61234/api/2/raid/views
HTTP RESTful request: http://localhost:61234/api/2/mem/views
HTTP RESTful request: http://localhost:61234/api/2/alert/views
HTTP RESTful request: http://localhost:61234/api/2/psutilversion/views
HTTP RESTful request: http://localhost:61234/api/2/hddtemp/views
HTTP RESTful request: http://localhost:61234/api/2/sensors/views
HTTP RESTful request: http://localhost:61234/api/2/now/views
HTTP RESTful request: http://localhost:61234/api/2/quicklook/views
HTTP RESTful request: http://localhost:61234/api/2/network/views
HTTP RESTful request: http://localhost:61234/api/2/processcount/views
HTTP RESTful request: http://localhost:61234/api/2/batpercent/views
HTTP RESTful request: http://localhost:61234/api/2/cpu/views
.
==============================================================================
INFO: [TEST_999] Stop the Glances Web Server
Stop the Glances Web Server
.
======================================================================
FAIL: test_001_all (__main__.TestGlances)
All.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unitest-restful.py", line 70, in test_001_all
    self.assertTrue(req.ok)
AssertionError: False is not true

======================================================================
FAIL: test_003_plugins (__main__.TestGlances)
Plugins.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unitest-restful.py", line 92, in test_003_plugins
    self.assertTrue(req.ok)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 11 tests in 108.875s

FAILED (failures=2)

C:\Users\Jamie\Documents\glances>
```

**Comment by jjbrunton** [comment]
Is this still an issue?

What version is this fixed in? I did a pip install glances --upgrade which got me 2.6.1 but the issue still exists.

**Comment by nicolargo** [comment]
@jjbrunton Sorry to hear that the patch did not correct your issue. @nclsHart : Any idea to try to reproduce the problem ?

**Comment by nclsHart** [comment]
@nicolargo If the problem come from one of the process name, we should be able to reproduce it with a complete list of processes. 

@jjbrunton Could you find a way to send us a list of your processes ?

**Comment by asergi** [comment]
@nicolargo @nclsHart @jjbrunton sorry, I should have made it more clear (with a comment here) that I only fixed part of the issue.

Anyway, to reproduce the bug, simply install µTorrent on Windows (0xb5 is the micro sign).
The problem is that I have yet to understand why it works flawlessy in console mode, but not in web.

**Comment by jjbrunton** [comment]
Any movement on this?

**Comment by nclsHart** [comment]
@jjbrunton I've successfully reproduced your bug on python 2.7.11 and I'm now working on a patch.

Python 3.5.x seems to be not affected by this issue.

**Comment by jjbrunton** [comment]
@nclsHart - Sounds good, I'm following this issue so let me know if I can test/do anything to help.

**Comment by nclsHart** [comment]
@nicolargo or @asergi I haven't find a way to solve this issue. 

The problem seems to come from the json dumps function and his behavior with unicode on python 2.x.

**Comment by stumueller** [comment]
Hi I have python 2.7 installed as I'm running program that aren't compatible with python 3.5. Can I still install python 3.5 and get just glances to use 3.5 and none of my other programs? maybe by setting my path to only use python 2.7?

Stuart

**Comment by nicolargo** [comment]
@nclsHart / @asergi : i try to make a quick test and can not reproduce the error on my side.

Here it is:

```
$ ipython
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython 5.0.0 -- An enhanced Interactive Python.

In [1]: import json

In [2]: d = {'name': 'µTorrent'}

In [3]: j = json.dumps(d)

In [4]: dec = json.loads(j)

In [5]: print(dec['name'])
µTorrent

```

@jjbrunton : Can you try the previous command (replace ipython by python if needed).

**Comment by nclsHart** [comment]
On my windows I get the following error: 

``` 
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19)
>>> import json
>>> d = {'name': 'µTorrent'}
>>> j = json.dumps(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 0: invalid continuation byte
```

**Comment by nicolargo** [comment]
@nclsHart : Nice !

Can you try this:

    j = json.dumps(d, ensure_ascii=False)

**Comment by nclsHart** [comment]
@nicolargo This is fixing error on dump but now it's failing on step 4:

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19)
>>> import json
>>> d = {'name': 'µTorrent'}
>>> j = json.dumps(d, ensure_ascii=False)
>>> dec = json.loads(j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 0: invalid continuation byte
```

**Comment by nicolargo** [comment]
And with:

    dec = json.loads(j.decode("utf-8", "ignore"))

**Comment by nclsHart** [comment]
I get the following result: 

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19)
>>> import json
>>> d = {'name': 'µTorrent'}
>>> j = json.dumps(d, ensure_ascii=False)
>>> dec = json.loads(j.decode("utf-8", "ignore"))
>>> print(dec['name'])
Torrent
```

**Comment by nicolargo** [comment]
@nclsHart Better...

**Comment by nicolargo** [comment]
If you want i can write the following patch:

- try the default method
- If an UnicodeDecodeError occur on dumps or loads use the alternative encoding option

Is it ok for you @nclsHart ?

**Comment by nclsHart** [comment]
@nicolargo Yes, it seems to be the best option we have.

Thank you :).

**Comment by nicolargo** [comment]
@jjbrunton and @nclsHart : Can you test the latest HEAD version on the develop branch ? It should correct the issue...

**Comment by halali** [comment]
I have same issue on 
Glances 2.8.1
psutil 5.2.0

**Comment by Digmarx** [comment]
I also have the same issue, running WS2012R2, psutil 5.2.0 and the latest version of Glances.

**Comment by nicolargo** [comment]
@halali and @Digmarx Can you have a look inside the Web browser console log ?

**Comment by Digmarx** [comment]
The following entry is logged every couple of seconds:
GET http://localhost:61208/api/2/all 404 (Not Found) vendor.min.js:12410

**Comment by halali** [comment]
this is console output:

vendor.min.js:12410 GET http://localhost:61208/api/2/all/views 404 (Not Found)
(anonymous) @ vendor.min.js:12410
sendReq @ vendor.min.js:12155
serverRequest @ vendor.min.js:11908
processQueue @ vendor.min.js:16648
(anonymous) @ vendor.min.js:16692
$eval @ vendor.min.js:17972
$digest @ vendor.min.js:17786
$apply @ vendor.min.js:18080
tick @ vendor.min.js:13025
vendor.min.js:12410 GET http://localhost:61208/api/2/all 404 (Not Found)
(anonymous) @ vendor.min.js:12410
sendReq @ vendor.min.js:12155
serverRequest @ vendor.min.js:11908
processQueue @ vendor.min.js:16648
(anonymous) @ vendor.min.js:16692
$eval @ vendor.min.js:17972
$digest @ vendor.min.js:17786
$apply @ vendor.min.js:18080
tick @ vendor.min.js:13025

**Comment by nicolargo** [comment]
Strange... vender.min.js is provided in the pip install archive (https://github.com/nicolargo/glances/tree/master/glances/outputs/static/public/js).

@notFloran Can you have a look ?

@Digmarx and @halali : can you clean your Web browser cache in order to be sure that you load the good Glances Web UI version ?

**Comment by Digmarx** [comment]
Yep, had tried that already, tried it again, no dice.

**Comment by nclsHart** [comment]
Reproduced on Windows 10.

@nicolargo The unicode's nightmare is back :(.

As @Digmarx said previously, requests to http://localhost:61209/api/2/all` return the following error : 

```
Cannot get stats ('utf8' codec can't decode byte 0xe9 in position 14: invalid continuation byte)
```

I also get the following warnings when starting Glances : 

![glances-warning](https://cloud.githubusercontent.com/assets/833625/24323485/75477198-1176-11e7-9aed-22bb72c3a4dc.PNG)

Python 2.7 only is affected by this issue.

**Comment by Digmarx** [comment]
updated to v 2.9.1 and the error seems to have been resolved

**Comment by halali** [comment]
For me still dont work, same issue
