### ISSUE TITLE
glances is not installable

### ISSUE THREAD

**Issue by devalru** [nicolargo/glances#817]
Hi,

I tried a from-source-installation.

ENV: SLES 11 SP4, Python 2.6

$ ./sudo python setup.py install
...
Processing dependencies for Glances==2.6
Searching for logutils
Reading https://pypi.python.org/simple/logutils/
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'logutils' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or download links found for logutils
error: Could not find suitable distribution for Requirement.parse('logutils')

It is not listed as a requirement on your GitHub page.

**Comment by nicolargo** [comment]
Hi,

in the log:
Download error...

You need an Internet access. If it is not possible, follow the offline installation procedure: https://github.com/nicolargo/glances/wiki/Glances-offline-installation
