### ISSUE TITLE
Browsing for servers which are in the [serverlist] seems to be broken

### ISSUE THREAD

**Issue by HiBit** [nicolargo/glances#819]
Hello,

I've 2 servers in my glances.conf in the [serverlist] section.
When i start glances with --browser I see the two machines but the menu seems to be broken.
I cant change the cursor and can't access any of the maschines.
Does someone experienced similar issues?
If I start glances with -c XXX.XXX.XXX I can connect to both maschines.

My glances.conf:
[serverlist]
# VM-WEB01
server_1_alias=VM-WEB01
server_1_name=10.230.1.1
server_1_port=61209
# VM-WEB02
server_2_alias=VM-WEB02
server_2_name=10.230.2.1
server_2_port=61209

Here a screenshot:
http://www.directupload.net/file/d/4297/izrh8ppc_png.htm

It would be nice if someone can help me with my problem.

**Comment by nicolargo** [comment]
Confirmed. It is a regression... I will have a look on it.

**Comment by nicolargo** [comment]
@HiBit : just commit a patch on the DEVELOP branch. Can you test it ?

**Comment by furkanmustafa** [comment]
I still have the same issue. 10 servers configured, shows up in the list, but I cannot go up/down. Pressing <Enter> works and I can open the first server only.

```
$ glances --version
Glances v2.10 with psutil v5.2.1
```

**Comment by furkanmustafa** [comment]
I figured out uppercase `A` and `B` keys do the navigation :/ is this intentional?

In `output/glances_curses_browser.py`, I have imported `curses`, and changed conditions like below, and it worked;

```diff
-elif self.pressedkey == 65:
+elif self.pressedkey == 65 or self.pressedkey == curses.KEY_UP:
```

```diff
-elif self.pressedkey == 66:
+elif self.pressedkey == 66 or self.pressedkey == curses.KEY_DOWN:
```
