### ISSUE TITLE
[Web UI] Display ongoing alert counter in the favicon

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#823]
When there is at least one ongoing alert, a red counter could be displayed in the favicon.

This can be achieved using this lib: https://github.com/ejci/favico.js.
There is some examples available here : http://lab.ejci.net/favico.js.

**Comment by nicolargo** [comment]
+1 for the idea

**Comment by nicolargo** [comment]
Done https://github.com/nicolargo/glances/commit/ba9db27bf6cb2f285ed873072cfdb79bf65e78ee
