### ISSUE TITLE
 [Folders] Differentiate permission issue and non-existence of a directory

### ISSUE THREAD

**Issue by nclsHart** [nicolargo/glances#828]
#### Description

Currently if we have a permission issue on a monitored folders, the ui display a question mark. As said in the [documentation](http://glances.readthedocs.org/en/latest/aoa/folders.html), this symbol is used to report non-existent folders to user. This could be confusing.

So we could use another symbol (maybe exclamation mark) in order to clearly identify this issue.

**Comment by nicolargo** [comment]
Done in the latest commit. 

@nclsHart : Can not see the plugin in the WebUI even after applying the PR: https://github.com/nicolargo/glances/pull/829#issuecomment-202432949 / Can you have a llok ?

**Comment by nclsHart** [comment]
@nicolargo Tested under curse and web interface.

Maybe you have some browser cache on html templates. Can you try in private navigation?

There is just one decoration issue on Web UI: the exclamation mark is green (OK). I'll fix this.
