### ISSUE TITLE
Installation fails on osx el capitan 

### ISSUE THREAD

**Issue by julien101** [nicolargo/glances#830]
On OSX El Capitan, the following command fails:
`pip install glances`
with the following error :
`byte-compiling /Library/Python/2.7/site-packages/glances/webserver.py to webserver.pyc
    running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted`
Using sudo does not help as this is not a permission issue for a specific user.
Please read the following, as it explains well this new behavior of OSX (starting with El Capitan):
http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really/193379
A simple fix is to use user accessible directories (/Library) instead of /System.
A simple workaround: Install from source: Fast and no issue.

**Comment by nicolargo** [comment]
It is not a Glances issue but a Pip one.

Have a look on http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade
