### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#836]
#### Description

Firefox high CPU consumption when the  the WebUI is displayed.

Without Glances but with Firefox open:

![selection_009](https://cloud.githubusercontent.com/assets/776747/14231743/f0ab88a2-f98e-11e5-9447-193958835855.png)

With Glances -w started and the WebUI openned in Firefox:

![selection_010](https://cloud.githubusercontent.com/assets/776747/14231748/0658f964-f98f-11e5-908d-9f4d73956012.png)
#### Versions
- Glances (glances -V): Glances v2.6.1 with psutil v4.1.0 (also tested with Glances 2.7 beta)
- Operating System (lsb_release -a): Ubuntu 14.04
- Firefox: 45.0

**Comment by nicolargo** [comment]
@nclsHart / @notFloran : Do you think that the CPU consumption is normal ?

**Comment by nclsHart** [comment]
This is a screenshot taken while monitoring one instance of chrome and another of firefox with only the glances web UI opened on it: 

![cpu-consumption](https://cloud.githubusercontent.com/assets/833625/14260189/96e532d8-faaa-11e5-90b0-f9d93b66de80.png)

The CPU consumption seems to be particulary high on firefox.

I will look for possible performance enhancements with angularjs. But the first enhancement I see is the reduction of item number in the process list.

**Comment by nicolargo** [comment]
@nclsHart +1 for the proposal to reduce the number of items in the process list (it is what is done in the Curses interface). The point is to find a way to compute the number of item regarding to the screen/font size. Any proposal ?

**Comment by jasker5183** [comment]
I believe this is why my laptop sounds like its taking off while I have a glances tab open in either chrome or firefox. Wouldn't happened to be fixed in dev version?

**Comment by nicolargo** [comment]
@nclsHart How can we looking forward this issue ? Some ideas:

1) limit statically the number of items in the processing list
2) compute the number of item dynamically (stop displaying when the item is not visable, perhaps JS can do that...).
3) other trick...

**Comment by nicolargo** [comment]
@nclsHart : Any head up ? What do you think of https://github.com/nicolargo/glances/issues/836#issuecomment-205691627

**Comment by nclsHart** [comment]
I already made some tests and this is not an acceptable solution. Each trick brings more complexity than any real performance gain.

I think most of our problems are due to how angularjs 1.x works. I'll try an upgrade to angularjs 2 during the 2.8 milestone, and I hope it'll solve our performance problems.

**Comment by nicolargo** [comment]
Ok, looking forward the AngularJS 2 optimisation...

**Comment by nicolargo** [comment]
@nclsHart Any head up ?

**Comment by nicolargo** [comment]
Another proposal: in the [outputs] section of the Glances configuration file, add an optional key which define the maximum number of processes to display. This value will be applied on both Web and Curses interface. The default behavior (if the key is not defined) is the same than today:
* Curse UI: the number is dynamically adapted to the terminal height
* Web UI: display all the processes

@asergi / @notFloran and @nclsHart : What do you think ?

**Comment by nicolargo** [comment]
@notFloran : I just a add a new entry point in the Restful API to retrieve configuration items from the configuration file.

For example, if my configuration file is:

    [outputs]
    # Theme name for the Curses interface: black or white
    curse_theme=black 

Then the Restfull api return:

    curl http://0.0.0.0:61208/api/2/config
    {"outputs": {"curse_theme": "black"}}

Can you implement the current enhancement request by adding a new configuration key and by limiting the number of processes to display in the WebUI:

    [outputs]
    # Theme name for the Curses interface: black or white
    curse_theme=black 
    # Limit the number of processes to display
    max_processes_display=30

**Comment by nicolargo** [comment]
@notFloran or @nclsHart : Can you implement the proposed solution (https://github.com/nicolargo/glances/issues/836#issuecomment-259980417) in the Web UI ?

**Comment by nicolargo** [comment]
Solved by the latest commit (thanks @notFloran ):

Before:
![selection_273](https://cloud.githubusercontent.com/assets/776747/21498818/64050bb0-cc30-11e6-8f92-0fa3fd83bf86.png)

After (with max_processes_display=30):
![selection_274](https://cloud.githubusercontent.com/assets/776747/21498819/68655e8a-cc30-11e6-980b-19ad12f8cdf3.png)
