### ISSUE TITLE
Process naming issue (Chromium is displayed as Asy)

### ISSUE THREAD

**Issue by bacondropped** [nicolargo/glances#838]
#### Description

![2016-04-04-031536_1598x877_scrot](https://cloud.githubusercontent.com/assets/9872501/14235959/6a3210f2-fa15-11e5-9711-2998b174615e.png)

Glances prints `Asy` instead of the Chromium command line, actual command line is shown in the bottom right (`ps aux | grep Asy`). Maybe it has something to do with the forward slash in the `--force-fieldtrials` argument?

#### Versions

* Glances (glances -V): `v2.7_BETA` @ 1806d14
* PSutil (glances -V): `v4.1.0`
* Operating System (lsb_release -a): `Ubuntu 16.04`

#### Logs

[/tmp/glances.log](http://pastebin.com/TTdsaLG2)

**Comment by nicolargo** [comment]
Hi @bacondropped !

First of all, thanks for the complete report. The issue is already knoxn: https://github.com/nicolargo/glances/issues/826

A patch will be release soon.


REJECTED: duplicated https://github.com/nicolargo/glances/issues/826

**Comment by bacondropped** [comment]
Oh, sorry for the duplicate. Thanks!
