### ISSUE TITLE
[WebUI] Process list not display at every refresh

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#839]
Perhaps an issue after this pull request: https://github.com/nicolargo/glances/pull/835 
==> @nclsHart 

#### Description

For a bug: The process list is not displayed every time.

![selection_012](https://cloud.githubusercontent.com/assets/776747/14240529/d4044eca-fa45-11e5-8dd7-d01f02bb1f65.png)

#### Versions

* Glances (glances -V): latest DEVELOP HEAD

**Comment by nclsHart** [comment]
@nicolargo Bug confirmed on firefox but i can't reproduce on chrome: 

```
process.cmdline.join is not a function
```

**Comment by nicolargo** [comment]
Bug corrected: works nice on my Firefox 45.0 after applying the patch https://github.com/nicolargo/glances/issues/841

Thanks @nclsHart
