### ISSUE TITLE
[WebUI] Add 'x' and 'w' shortcuts to clean logs messages

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#843]
#### Description

Enhancement: Add 'x' and 'w' shortcuts to clean logs messages

![selection_013](https://cloud.githubusercontent.com/assets/776747/14251704/8af79266-fa84-11e5-94f2-d8bda6c77921.png)

#### Versions

* Glances (glances -V): Glances 2.6.1

#### Notes for dev

Create Resful API post command to clean:

* 'w' > Delete finished warning logs
* 'x' > Delete finished warning and critical logs

After that, change the WebUI and modify the Help screen.

**Comment by nclsHart** [comment]
Duplicate of #808. Should I close #808?

**Comment by nicolargo** [comment]
Oups...
No, i close this one...

REJECTED: duplicated https://github.com/nicolargo/glances/issues/808
