### ISSUE TITLE
Unable to use `glances --browser`

### ISSUE THREAD

**Issue by ketzacoatl** [nicolargo/glances#846]
I have read through the docs, and I believe I have my network and host configurations correct, though I am not seeing the results I expect.

#### Description

I have a cluster of nodes on EC2 AWS, and they all have a glances server running. I start a client on one of the hosts with `--browser`, but it errors out: `No Glances server available`

`ps aux | grep glances` shows me glances is running on each host:
```
/usr/bin/python /usr/local/bin/glances --bind 10.30.1.32 -s
```
I am running glances with upstart, eg:

```
    description "Run the glances agent"
    start on filesystem
    stop on runlevel [!2345]
    
    setuid glances
    setgid glances
    
    script
      /usr/local/bin/glances  --bind 10.10.10.32 -s 
    end script
```

I have UFW enabled, but glances is setup with an application definition:

```
    [glances]
    title=glances
    description=allow glances collection agent to be accessed by browser clients
    ports=61209
```

When I use `glances -c 10.10.10.32`, I can connect to the host and see glances functioning correctly.

#### Versions

```
# glances -V
Glances v2.5.1 with psutil v3.3.0
```
This is on `Ubuntu 14.04.4 LTS`

**Comment by nicolargo** [comment]
Hi @ketzacoatl .

You need to configure your nodes into the client configuration file. The Glances auto discover protocol only works when Glances servers and clients are on the same Ethernet subnet( broadcast and multicast enable).

**Comment by ketzacoatl** [comment]
OK, so I need to add a configuration file to each of the hosts.. that makes sense. I see http://glances.readthedocs.org/en/latest/config.html, but it's not clarifying for me, what should the config look like for client/server?

**Comment by ketzacoatl** [comment]
Oh, I see https://github.com/nicolargo/glances/blob/master/conf/glances.conf#L178, so I think that is more clear. I will update my CM formula for saltstack and see if I can get these servers chatting. 

Also, I am really impressed with glances so far, great work! Thanks!
