### ISSUE TITLE
Crash with Docker 1.11

### ISSUE THREAD

**Issue by dbarboza** [nicolargo/glances#848]
#### Description
Glances CLI errors with the following trace:

```
$ glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.1', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.4/dist-packages/glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "/usr/local/lib/python3.4/dist-packages/glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python3.4/dist-packages/glances/standalone.py", line 88, in __serve_forever
    self.stats.update()
  File "/usr/local/lib/python3.4/dist-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.4/dist-packages/glances/plugins/glances_plugin.py", line 658, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/glances/plugins/glances_docker.py", line 226, in update
    container['memory'] = self.get_docker_memory(container['Id'], self.thread_list[container['Id']].stats)
  File "/usr/local/lib/python3.4/dist-packages/glances/plugins/glances_docker.py", line 297, in get_docker_memory
    ret['rss'] = all_stats['memory_stats']['stats']['rss']
TypeError: 'NoneType' object is not subscriptable
```

In the brief time glances is displayed, I noticed the docker stats are mostly "?" instead of numeric:
```
docker0       0b     0b    Name                               Status  CPU%    MEM IOR/s IOW/s  Rx/s  Tx/s Command 
eth0          0b     0b    gemstash_server          Up About an hour   0.0      ?     ?     ?     ?     ? gemstash start --no-daemonize
```

I have one container running and `docker stats gemstash_server` appears normal:
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
gemstash_server     0.01%               35.75 MB / 25.23 GB   0.14%               4.994 kB / 648 B    0 B / 0 B           0
```
If I have no containers running, glances will run fine without the docker section.
I did upgrade docker to the newest this morning (v 1.11.0). I don't see anything obvious in the release notes that would have broken stats API: https://github.com/docker/docker/releases
I downgraded docker-engine to 1.10.3 and glances did not error out. Here's the output of docker stats again:
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O
gemstash_server     0.00%               35.7 MB / 25.23 GB   0.14%               4.125 kB / 648 B    0 B / 0 B
```

#### Versions

* Glances (glances -V): Glances v2.6.1 
* PSutil (glances -V): psutil v4.1.0
* Operating System (lsb_release -a): Ubuntu 14.04.4

#### Logs

Nothing relevant in glances.log:
2016-04-14 12:37:49,663 -- INFO -- Start Glances 2.6.1
2016-04-14 12:37:49,663 -- INFO -- CPython 3.4.3 and PSutil 4.1.0 detected
2016-04-14 12:37:49,665 -- INFO -- Read configuration file '/home/dbarboza/.config/glances/glances.conf'
2016-04-14 12:37:49,665 -- INFO -- Start standalone mode
2016-04-14 12:37:49,741 -- WARNING -- Can not connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Connection refused)

**Comment by nicolargo** [comment]
Hi @david-guenault.

First of all, thanks for the bug report. I have not tested Glances with this latest Docker version.

One additional question: do you have updated your docker-py (Docker Python lib) ?

**Comment by dbarboza** [comment]
I was running docker-py 1.7.2 at the time of this report. I have now upgraded to the latest (1.8.0). The Glances error remains.

**Comment by nicolargo** [comment]
Bug confirmed:

```
$ python -m glances
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nicolargo/Dropbox/dev/glances/glances/__main__.py", line 38, in <module>
    glances.main()
  File "glances/__init__.py", line 133, in main
    standalone.serve_forever()
  File "glances/standalone.py", line 107, in serve_forever
    return self.__serve_forever()
  File "glances/standalone.py", line 88, in __serve_forever
    self.stats.update()
  File "glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "glances/plugins/glances_plugin.py", line 660, in wrapper
    ret = fct(*args, **kw)
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_docker.py", line 226, in update
    container['memory'] = self.get_docker_memory(container['Id'], self.thread_list[container['Id']].stats)
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_docker.py", line 297, in get_docker_memory
    ret['rss'] = all_stats['memory_stats']['stats']['rss']
TypeError: 'NoneType' object has no attribute '__getitem__'

``` 

Docker version:

```
$ docker info
Containers: 19
 Running: 2
 Paused: 0
 Stopped: 17
Images: 245
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.705 GiB
Name: xps
ID: RK63:UNT6:TBQO:RNNX:VWRQ:VMI4:H26V:MT2X:CD7P:CPC2:4DVM:G73H
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Docker API is broken... again...

Workarounds:
- Use Docker 1.8 (or 1.9)
- Disable the Docker plugin --disable-docker

**Comment by nicolargo** [comment]
No more stats in the dict:

    u'memory_stats': {u'usage': 27185152, u'limit': 8273551360, u'failcnt': 0, u'stats': None, u'max_usage': 27455488}

Docker issue ?

Here is the contain of the all_stats var:

`2016-04-17 22:32:04,120 -- INFO -- {u'blkio_stats': {u'io_service_time_recursive': [], u'sectors_recursive': [], u'io_service_bytes_recursive': [{u'major': 8, u'value': 16388096, u'minor': 0, u'op': u'Read'}, {u'major': 8, u'value': 8466432, u'minor': 0, u'op': u'Write'}, {u'major': 8, u'value': 8450048, u'minor': 0, u'op': u'Sync'}, {u'major': 8, u'value': 16404480, u'minor': 0, u'op': u'Async'}, {u'major': 8, u'value': 24854528, u'minor': 0, u'op': u'Total'}], u'io_serviced_recursive': [{u'major': 8, u'value': 270, u'minor': 0, u'op': u'Read'}, {u'major': 8, u'value': 1407, u'minor': 0, u'op': u'Write'}, {u'major': 8, u'value': 1403, u'minor': 0, u'op': u'Sync'}, {u'major': 8, u'value': 274, u'minor': 0, u'op': u'Async'}, {u'major': 8, u'value': 1677, u'minor': 0, u'op': u'Total'}], u'io_time_recursive': [], u'io_queue_recursive': [], u'io_merged_recursive': [], u'io_wait_time_recursive': []}, u'precpu_stats': {u'cpu_usage': {u'usage_in_usermode': 1160000000, u'total_usage': 2391341953, u'percpu_usage': [639120985, 541961535, 654108751, 556150682], u'usage_in_kernelmode': 670000000}, u'system_cpu_usage': 101306630000000, u'throttling_data': {u'throttled_time': 0, u'periods': 0, u'throttled_periods': 0}}, u'read': u'2016-04-17T22:32:03+02:00', u'memory_stats': {u'usage': 27185152, u'limit': 8273551360, u'failcnt': 0, u'stats': None, u'max_usage': 27455488}, u'pids_stats': {}, u'networks': {u'eth0': {u'tx_dropped': 0, u'rx_packets': 97, u'rx_bytes': 19159, u'tx_errors': 0, u'rx_errors': 0, u'tx_bytes': 2866, u'rx_dropped': 0, u'tx_packets': 32}}, u'cpu_stats': {u'cpu_usage': {u'usage_in_usermode': 1160000000, u'total_usage': 2396055013, u'percpu_usage': [640138573, 542208288, 656563196, 557144956], u'usage_in_kernelmode': 670000000}, u'system_cpu_usage': 101310650000000, u'throttling_data': {u'throttled_time': 0, u'periods': 0, u'throttled_periods': 0}}}
`

Also have a look on the net interface not working anymore...

**Comment by nicolargo** [comment]
The issue should be corrected with the latest commit of the DEVELOP branch.

@dbarboza Can you test it ?

**Comment by dbarboza** [comment]
Confirmed - With d64ee55, glances does not crash and the container section reports valid information. Thank you!

**Comment by nicolargo** [comment]
Note: i just release a official patch (Glances 2.6.2) for this issue. Please upgrade your Glances software using Pipy.
