### ISSUE TITLE
Fails to output degrees character on non-unicode terminals

### ISSUE THREAD

**Issue by h3xx** [nicolargo/glances#855]
## Symptoms:

* Outputs temperatures in the `SENSORS` panel as e.g. "41C" instead of "41°C" when outputting to a latin1 terminal. It should output the symbol in the appropriate encoding for the terminal.

![screenshot-2016-0425-1708](https://cloud.githubusercontent.com/assets/615684/14800624/85de63ce-0b08-11e6-80e3-5311c4a57529.png)

## Steps to reproduce:

Use a latin1 terminal to run glances:

    LC_CTYPE=en_US xterm -e glances

This was previously fixed in 52aeecc897761ec54d6db0332ce4136cf15392b6.

It broken again by commit 7d4e713016748701e5229071844c677bc386850a.

Reproducible in both the master and develop branches.

**Comment by asergi** [comment]
This is not a bug. We don't display the degree symbol anymore: a3f6f81.

**Comment by h3xx** [comment]
Ah, okay. Thanks for the clarification.
