### ISSUE TITLE
Network I/O is off in InfluxDB/Grafana

### ISSUE THREAD

**Issue by clrung** [nicolargo/glances#856]
#### Description

The network I/O in my grafana dashboard does not match what I see when I run glances from the command line.  See picture below:

<img width="555" alt="screen shot 2016-04-27 at 5 15 40 pm" src="https://cloud.githubusercontent.com/assets/5472850/14868503/cf0dec92-0c9b-11e6-9fa2-6b959d364aa1.png">

As you can see, it's not something straightforward like not using the correct units – glances is currently displaying KBps and Grafana is displaying the graph with bytes/sec units.  I considered trying to figure out a multiplier to add to the measurements, but I'm having trouble figuring out an appropriate value.

In the example above, I would want to multiply the value Grafana (via InfluxDB) sees by ~1/3.

Glances: Rx/s: 15Kbps    Tx/s: 49Kbps
Grafana: Rx/s: 50Kbps    Tx/s: 153Kbps

My suggestion of editing the Grafana query to multiply the result by 0.33333 would get close results (~16Kbps and ~51Kbps) in this example, but it doesn't always work out that nicely, and I find that to be a  hacky solution.  I also don't understand the significance of why Grafana would report the value ~3 times higher than it is.

Thank you so much for your help!

#### Versions

* Glances (glances -V): Glances v2.7_BETA
* PSutil (glances -V): v4.1.0
* Operating System (lsb_release -a): Ubuntu 14.04 LTS

**Comment by nicolargo** [comment]
Be aware that the refresh time between the Glances UI (default 3 seconds) and the Grafana dashboard (default 300 seconds) is different. Nevertheless, do you use the Grafana Glances dashboard or a specific one ?

**Comment by clrung** [comment]
My apologies for leaving out that detail.  I am using the Grafana Glances dashboard.  I don't think that this is a refresh time issue; the graph below shows a period of time when I was downloading a large file while maxing out my internet connection, which is about 10MBps.

<img width="222" alt="screen shot 2016-04-28 at 8 34 55 am" src="https://cloud.githubusercontent.com/assets/5472850/14886003/7727f6c2-0d1c-11e6-92d0-32ad1c8a1991.png">

As you can see, grafana shows that I was downloading the file at around 30MBps – I wish my internet was that fast!  And here we see the odd 3x multiplier again :/

Here are my network settings in Grafana, which I believe are the default settings in the Grafana Glances dashboard:

<img width="549" alt="screen shot 2016-04-28 at 8 39 48 am" src="https://cloud.githubusercontent.com/assets/5472850/14886062/cf620706-0d1c-11e6-85ef-86e06d7ed12d.png">

<img width="285" alt="screen shot 2016-04-28 at 8 40 19 am" src="https://cloud.githubusercontent.com/assets/5472850/14886068/da773d3c-0d1c-11e6-874a-886f423b9752.png">

If it would help, I can provide the full glances-grafana.json that I am using.

Thanks again!

**Comment by nicolargo** [comment]
One question.

Glances display and populate the InfluxDB database in Kbps (Kilo bits per second).
When i saw the latest screenshot, your dashboard uses Bps (Byte per second unit).
You should configure your dashboard to use bps (bits per second).

**Comment by clrung** [comment]
Here is what appears when I use bits/sec:

<img width="449" alt="bits s" src="https://cloud.githubusercontent.com/assets/5472850/14886933/7267e1f6-0d21-11e6-80e5-51070768d2d6.png">

This shows ~30Mbps ~= 3.75MBps

And bytes/sec:

<img width="430" alt="bytes s" src="https://cloud.githubusercontent.com/assets/5472850/14886939/7cc4aa8a-0d21-11e6-9361-d03db8ac00bf.png">

This shows ~30MBps.

This should read ~10MBps.

**Comment by nicolargo** [comment]
Also reproduced on my side:

Ran a iperf (1Mbps on the Tx Interface):

![selection_017](https://cloud.githubusercontent.com/assets/776747/14887453/3877e10a-0d56-11e6-9f29-4768c0507c72.png)

Display 1 Mbps in the Glances UI:

![Uploading Sélection_016.png…]()

But display 435Kbps in the Grafana dashboard:

![selection_018](https://cloud.githubusercontent.com/assets/776747/14887487/577423c0-0d56-11e6-962d-7ff31b0863bf.png)

**Comment by clrung** [comment]
Ah that's great! Reproducibility 👍 

Please let me know if there's anything I can do to assist.

**Comment by nicolargo** [comment]
I understood...

Glances store the current bitrate en Byte per second every refresh (3 by default) seconds. So you need to modify the Grafana dashboard as following:

![selection_019](https://cloud.githubusercontent.com/assets/776747/14889457/2d1ab6bc-0d5f-11e6-979a-c5b57c96209b.png)

I will update the official dashboard on the Github.

Perhaps there is the same issue on the disk IO plugin...

**Comment by clrung** [comment]
Thank you!! This resolved my issue.  And you're right; this problem may be affecting disk I/O too.
