### ISSUE TITLE
Allow theme to be set in configuration file

### ISSUE THREAD

**Issue by dwt** [nicolargo/glances#862]
#### Description
I use a white terminal all the time, therefor the default theme doesn't make sense to me. I'd like to change it via the configuration file, but neither the help texts, nor studying the default config file gave me any hint how to set this up. (I expressly don't want to aliases to work around this).

Am I missing something or is this feature missing? If so I'd say: If it's a command line switch, there ought to be a way to set that same option via the config file.

#### Versions

* Glances v2.6.1 with psutil v4.1.0
* Operating System (lsb_release -a): Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64

**Comment by nicolargo** [comment]
Hi @dwt . First of all thanks for the enhancement request.

Do you want to be able to configure the "whte theme" (the one linked to the --theme-white command line option) through the configuration file or define an "home made theme" (choosing background, foreground, warning and critical color) ?

**Comment by dwt** [comment]
> Do you want to be able to configure the "whte theme" (the one linked to the --theme-white command line option) through the configuration file or define an "home made theme" (choosing background, foreground, warning and critical color) ?
> 
I would definitely start by just allowing the command line flags in the config file first. Creating my own themes is not something I consider. If you want, you can add this later and I’m sure other users will use it. :)

Best Regards,
Martin Häcker

**Comment by nicolargo** [comment]
Ok @dwt, thanks for the clarification.

The implementation of this enhancement request will be in included into the 2.7 roadmap.

A new section will be added to the configuration file:

    [outputs]
    curse_theme=white

curse_theme could be default (black) or white.

**Comment by nicolargo** [comment]
Implemented in the DEVELOP branch. Will be available in the 2.7 release.

@dwt : Thanks for the enhancement request making Glances better ;)

**Comment by dwt** [comment]
Sure. :)

**Comment by jan-schulz-k24** [comment]
It would be nice if the "theme white" example could be added to the docs :-)
