### ISSUE TITLE
No influxdb configuration found

### ISSUE THREAD

**Issue by SharpLu** [nicolargo/glances#866]
Hello guys, I'm first time use the glances ,trying to deploy with Influxdb and Grafana but seems have some issues below.
![capture](https://cloud.githubusercontent.com/assets/8836246/15240932/23e2f228-18ed-11e6-8a31-4f8ec890f6ce.PNG)

I have checked with my glances.conf and influxDB seems is correct

glances.conf below
![glance conf](https://cloud.githubusercontent.com/assets/8836246/15240995/6934277a-18ed-11e6-9c9a-a3146c3b1bba.PNG)
Because i used annaconda2 for my python environment ,so the glances.conf belong my annaconda site-packages folder.

the influxDB below
![influxdb](https://cloud.githubusercontent.com/assets/8836246/15241018/8a29fde2-18ed-11e6-94f6-2eb2feb4f860.PNG)
 
![influxdb2](https://cloud.githubusercontent.com/assets/8836246/15241020/8d6beb64-18ed-11e6-8389-83904edf9f3f.PNG)

![influxdb3](https://cloud.githubusercontent.com/assets/8836246/15241021/91fdc882-18ed-11e6-8de6-4c452d57f8bc.PNG)

![influxdb4](https://cloud.githubusercontent.com/assets/8836246/15241025/957a27e4-18ed-11e6-89b7-030b51ff0bea.PNG)

**Comment by nicolargo** [comment]
I think that Glances uses a wrong configuration file.

Press 'h' in the Curse interface to check the loaded configuration file.

**Comment by SharpLu** [comment]
![a](https://cloud.githubusercontent.com/assets/8836246/15259943/49ffc6e0-1954-11e6-9296-0a7b02592148.png)

Hi nicolargo,

I have checked the glances  with h,  seems here dont have any configuration files.

I used ubuntu 14 desktop version 
and i have installed by 
pip install glances
sudo apt-get install glances
and also try to download glances and installed 
i try all method above respectively. but does not work. do you have any better solution? Thank you

**Comment by nicolargo** [comment]
As said in the documentation (http://glances.readthedocs.io/en/latest/config.html), the configuration file should be on one of the following folder: ~/.config/glances, /etc/glances

f not, create a new one (based on the default conf file: https://github.com/nicolargo/glances/blob/master/conf/glances.conf) and put it wherever you want.

and run glances with -C path/to/conf/file

**Comment by SharpLu** [comment]
I have try to glances -C /home/ubuntu/documents/glances.conf  but seems like this execution only temporary,and after close the glances and open again,  still old problem. 
but the way i try to use  glances -C /home/ubuntu/documents/glances.conf  --export-influxdb
seems still not work.

**Comment by nicolargo** [comment]
Can you:

1) paste/bin the glances.conf file (http://pastebin.com/)
2) Start Glances with the goods options and past/bin us the /tmp/glances.log file

**Comment by SharpLu** [comment]
Hi Nicolargo,

The glances.log file
http://pastebin.com/6t9JC2Sp

The glances conf file 
http://pastebin.com/CRLX2uhe

**Comment by nicolargo** [comment]
Try to put your glances.conf file in the ~/.config/glances folder (create it if it did not exist).

Restart Glances. It should solve this issue.

**Comment by SharpLu** [comment]
Hi Nicolargo ,
Thank you so much for the help,  now it works,

I just wondering can you tell me where to modify the time period? because I need changed to only show the past hours performances they are separated by each 10 minutes.

![01](https://cloud.githubusercontent.com/assets/8836246/15283220/1b239f8a-1b49-11e6-81bd-79863ac10e4b.PNG)

**Comment by SharpLu** [comment]
I have changed the time range,  now it works. Thanks again.

**Comment by SharpLu** [comment]
Everything works perfect now.
seems like have some issues with the Disk IO matrix dosnt work.

![03](https://cloud.githubusercontent.com/assets/8836246/15284127/cd3588b8-1b4f-11e6-9b6d-351e0d30f0b8.PNG)
![04](https://cloud.githubusercontent.com/assets/8836246/15284131/d00cbc50-1b4f-11e6-8419-d5a00ee201e4.PNG)

**Comment by nicolargo** [comment]
The default Grafana dashboard is given for a machine where the hard drive
is mapped to sda2. Are you sure that your system is ok with that ?
Run Glances in cosole mode and check that you have a sda2 disk...

___________________________________________________
*Avant donc que d'écrire, apprenez à penser. -+- Nicolas Boileau, Art
poétique -+-*

2016-05-16 10:21 GMT+02:00 L <notifications@github.com>:

**Comment by SharpLu** [comment]
Yes, you are right.  now it works correctly.

**Comment by nicolargo** [comment]
REJECTED cause: not an issue.
