### ISSUE TITLE
Temperature sensors fiels for Mac OSX Yosemite (10.10.x)

### ISSUE THREAD

**Issue by nicolasvilchez** [nicolargo/glances#867]
#### Description

I installed on our Mac server, it works perfectly.

Unfortunately (for us), We would like to have temperature sensors too (In practice we are VERY interested about our CPU temperatures).
Glances uses hddtemp for temperature sensors. But unfortunately it is available only on Linux. (I tried to install it on Mac without success)

Do you know a way to get also temperature sensors on our Mac server please ?
In case of it helps, I found this tool which can provide Temperature on Mac Osx with command line (istats)

http://apple.stackexchange.com/questions/54329/can-i-get-the-cpu-temperature-and-fan-speed-from-the-command-line-in-os-x
and also here: 
https://github.com/Chris911/iStats
#### Versions

Glances v2.6.2 with psutil v4.2.0
Darwin 14.5.0 Darwin Kernel Version 14.5.0  (Mac OSX Yosemite => 10.10.5)
#### Logs

Try to install hddtemp, 
the error during the Make step:

clang: warning: argument unused during compilation: '-rdynamic'
ata.c:39:10: fatal error: 'linux/hdreg.h' file not found
# include <linux/hdreg.h>

1 error generated.
make[2]: **\* [hddtemp-ata.o] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

Of course there is no no  linux/hdreg.h  ^^

**Comment by nicolargo** [comment]
HDDTemp is only used to grab HDD température. Glances uses the following libraries to get sensors stats:

* Py3Sensors (https://bitbucket.org/gleb_zhulik/py3sensors) for CPU and core temperature
* Batinfo (https://github.com/nicolargo/batinfo) for batteries %
* hddtemp (linux only) for hard disk temperature

Solution to respond to the current issue:

* Contribute to the Py3Sensors lib and add the support for Mac OS X (but the project has not been updated since 3/21/2013)
* Create a new lib with a binding to the SMC code (https://github.com/lavoiesl/osx-cpu-temp)

Any idea or alternative solution is welcome (@asergio ?).

**Comment by animehunter** [comment]
Maybe this could help https://github.com/lavoiesl/osx-cpu-temp ?

**Comment by jlsjonas** [comment]
I'd say bind to https://github.com/lavoiesl/osx-cpu-temp?

**Comment by nicolargo** [comment]
@nicolasvilchez Can you try the latest 2.8.5 version with PsUtil 5.2.0 ? Perhaps it will be compliant with your needs... Keep us inform.

**Comment by nicolargo** [comment]
@nicolasvilchez Can you try the latest Glances release ?

**Comment by nicolargo** [comment]
@nicolasvilchez Any head up ?

**Comment by notFloran** [comment]
No changes with PsUtil 5.2.0  and the develop branch.

And when I try to get data manually:

```
>>> psutil.sensors_temperatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'
```

**Comment by nicolargo** [comment]
This enhancement request should be reported to PsUtil.

**Comment by Kabouik** [comment]
I have the exact same issue as notFloran with psutil on Linux. `sensors` in terminal does show the temperatures correctly, and `ls /sys/class/hwmon/hwmon*/temp*_*` returns lots of results.

I'm not familiar with `pip` though, and I'm seriously considering that I may just have not installed psutil correctly (I did `sudo pip install psutil` after getting a permission denied without `sudo`?). I am guessing this is not what I should have done, and I'd be grateful if someone could help making it work.
