### ISSUE TITLE
Expose glances config file when running in docker

### ISSUE THREAD

**Issue by maxpower47** [nicolargo/glances#868]
It would be nice to have an easy way to provide a custom glances config when running in docker, i.e. expose a config volume that can be mapped to the host where a glances.conf file is kept persistent.

**Comment by nicolargo** [comment]
@maxpower47 Agree, but all should be done in the DockerFile. The Glances code should not be Docker specific.

**Comment by nicolargo** [comment]
Done in the latest commit.

Alternatively, if you want to use your own glances.conf file, you can create your
own Dockerfile:

    FROM nicolargo/glances
    COPY glances.conf /glances/conf/glances.conf
    CMD python -m glances -C /glances/conf/glances.conf $GLANCES_OPT
