### ISSUE TITLE
Will affect the performance of the machine？

### ISSUE THREAD

**Issue by lpn520** [nicolargo/glances#874]
Will affect the performance of the machine?

**Comment by nicolargo** [comment]
Please follow the template to describe mire precisely the issue.

**Comment by NightMachinary** [comment]
[**@Linpn**](https://github.com/linpn) commented on [Jun 17, 2016, 6:47 AM GMT+4:30](https://github.com/nicolargo/glances/issues/874#issue-160799190 "2016-06-17T02:17:41Z - Replied by Github Reply Comments"):
> Will affect the performance of the machine?

Yes, it did on my machine. You can run it and check its CPU usage from, e.g., Activity Monitor or htop. Using `--time 10` solved this problem for me.
