### ISSUE TITLE
Docker limits and actions

### ISSUE THREAD

**Issue by gmiotto** [nicolargo/glances#875]
It would be interesting if the docker plugin could have alerts related to the containers metrics, like CPU,  memory and network usage. With these functionalities, actions related to alerts could be triggered for a specific container, so it would be nice if these alerts/actions could be specified with a list (container name, id, etc) just like the monitor list.

Gustavo.

**Comment by nicolargo** [comment]
Hi Gustavo, big thanks for this nice enhancement request.

First of all, you should know that the monitor list will be replaced by the Application Monitoring Process (AMP) in the release 2.7 of Glances (see https://github.com/nicolargo/glances/issues/780). Nevertheless, i propose to implement the alert/action inside the Docker plugins.

I propose the following features, feel free to comment, add or remove:

1) Add default limits thresholds:

```
[dockers]
# Thresthold for CPU (in %)
cpu_careful=50
cpu_warning=70
cpu_critical=90
# Thresthold for MEM (in MB)
mem_careful=20
mem_warning=50
mem_critical=70
```

2) Define per container limits thresholds. Container identification is done by the container name:

For example, to define limits for a container named *dockerinfluxdbgrafana_influxdb_1*:

```
[dockers]
# Thresthold for CPU (in %)
dockerinfluxdbgrafana_influxdb_1_cpu_careful=10
dockerinfluxdbgrafana_influxdb_1_cpu_warning=15
dockerinfluxdbgrafana_influxdb_1_cpu_critical=20
```

3) Define action on trigger:

```
[dockers]
dockerinfluxdbgrafana_influxdb_1_cpu_critical_action=echo {{name}} {{Image}} {{Id}} {{cpu}} > /tmp/dockerinfluxdbgrafana_influxdb_1.alert
```

You can use all the variables ({{foo}}) available in the Docker plugin:

> {u'Status': u'Up 15 minutes', 'name': u'dockerinfluxdbgrafana_grafana_1', 'io': {'iow': 0, 'time_since_update': 3.131945848464966, 'cumulative_ior': 180224, 'ior': 0, 'cumulative_iow': 0}, u'Created': 1466859490, u'Image': u'grafana/grafana:latest', u'Labels': {u'com.docker.compose.service': u'grafana', u'com.docker.compose.config-hash': u'c41926802c256a8787b07953743bedd79a4df3387c305ca6ef9ca3aacf065f47', u'com.docker.compose.project': u'dockerinfluxdbgrafana', u'com.docker.compose.version': u'1.7.1', u'com.docker.compose.oneoff': u'False', u'com.docker.compose.container-number': u'1'}, u'NetworkSettings': {u'Networks': {u'bridge': {u'NetworkID': u'', u'MacAddress': u'02:42:ac:11:00:03', u'GlobalIPv6PrefixLen': 0, u'Links': None, u'GlobalIPv6Address': u'', u'IPv6Gateway': u'', u'IPAMConfig': None, u'EndpointID': u'90e276b3f91b1f94f8e3d32405c49f297100a50455351a94ad5c33538ee01dbc', u'IPPrefixLen': 16, u'IPAddress': u'172.17.0.3', u'Gateway': u'172.17.0.1', u'Aliases': None}}}, u'HostConfig': {u'NetworkMode': u'default'}, u'ImageID': u'sha256:edd194742cf58a86f20b1d2cfd76e2fd2c7d246eae3caec13a93f609c1622e08', u'State': u'running', u'Command': u'/run.sh', u'Names': [u'/dockerinfluxdbgrafana_grafana_1'], 'key': 'name', 'memory': {'usage': 6148096, 'limit': 8273534976, 'max_usage': 7294976}, u'Mounts': [{u'RW': True, u'Name': u'cd60cc48b850c401349fc41c4e18094fe7d394feb6d4672811bd64b30a4b9539', u'Propagation': u'rprivate', u'Destination': u'/etc/grafana', u'Driver': u'local', u'Source': u'/var/lib/docker/volumes/cd60cc48b850c401349fc41c4e18094fe7d394feb6d4672811bd64b30a4b9539/_data', u'Mode': u'rw'}, {u'RW': True, u'Name': u'ca39212efa63f91c6ee5f6d74af9902a2e42b9dde0f9745f0a93349bb707b322', u'Propagation': u'rprivate', u'Destination': u'/var/lib/grafana', u'Driver': u'local', u'Source': u'/var/lib/docker/volumes/ca39212efa63f91c6ee5f6d74af9902a2e42b9dde0f9745f0a93349bb707b322/_data', u'Mode': u'rw'}, {u'RW': True, u'Name': u'214db44ad449341a90b116a1f74700609b7996b1e9e7bc25efae53bdafa0e649', u'Propagation': u'rprivate', u'Destination': u'/var/log/grafana', u'Driver': u'local', u'Source': u'/var/lib/docker/volumes/214db44ad449341a90b116a1f74700609b7996b1e9e7bc25efae53bdafa0e649/_data', u'Mode': u'rw'}, {u'RW': True, u'Name': u'd9d4d96740f38e3861c77fff27c8784f84d55c0031d7c50f04d23149bc099604', u'Propagation': u'', u'Destination': u'/var/lib/grafana/plugins', u'Driver': u'local', u'Source': u'/var/lib/docker/volumes/d9d4d96740f38e3861c77fff27c8784f84d55c0031d7c50f04d23149bc099604/_data', u'Mode': u''}], 'cpu': {'total': 0.0}, u'Id': u'df63433e1895f2796fee3e8ed9bf9f793bdad495775c4d088074974f1cce595e', u'Ports': [{u'IP': u'0.0.0.0', u'Type': u'tcp', u'PublicPort': 3000, u'PrivatePort': 3000}], 'network': {'time_since_update': 3.1319429874420166, 'rx': 0, 'cumulative_tx': 9136, 'tx': 0, 'cumulative_rx': 33640}}

**Comment by nicolargo** [comment]
Implemented in the HEAD of the DEVELOP branch.

@gmiotto : Please test ;)

**Comment by nicolargo** [comment]
@gmiotto : Any head up ?
