### ISSUE TITLE
Web app not working correctly behind HTTPS nginx reverse proxy

### ISSUE THREAD

**Issue by gavinws** [nicolargo/glances#876]
#### Description

I followed the instructions here for setting up a reverse proxy for glances: https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI

I actually have 2 nginx servers involved here: 
1.  public, internet-facing server with HTTPS and authentication services (oauth2_proxy). It proxies requests to the following server over a VPN:
2. private, internal server which proxies multiple localhost web apps, including glances. It does not use HTTPS. This is where the config from the wiki was applied.

In the Chrome web console, I can see that all resources (css, js, etc) are blocked because they are being requested over HTTP while the root page was requested over HTTPS. It seems that HTTP is hard-coded somehow in the web app for glances, but I don't see where or how to change that from a quick search through the code. I also could not figure out how to rewrite the protocol in nginx, though the public nginx server has a global HTTP->HTTPS redirect (301) rule in place.
#### Versions
- Glances (glances -V): Glances v2.6.2 with psutil v3.1.1
- PSutil (glances -V): Glances v2.6.2 with psutil v3.1.1
- Operating System (lsb_release -a): Ubuntu 14.04.4 LTS
#### Logs

Screenshot of chrome web console:
![glances](https://cloud.githubusercontent.com/assets/944756/16360909/919535e2-3b2f-11e6-90e9-3b59575ffe86.png)

**Comment by gavinws** [comment]
I took another try at nginx rewrites and solved my issue. Here is my updated config on the private/internal server (which is not running HTTPS):

```nginx
location /glances/ {
        rewrite /glances/(.*) /$1 break;
        proxy_pass http://localhost:61208;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; #doesn't do anything?
}

location / {
        if ($http_referer ~ "^https?://[^/]+/glances"){
                rewrite ^/(.*) https://$http_host/glances/$1 redirect;
        }
}
```
The trick that did it was adding `https://$http_host/` in the root location's rewrite.

This does mean that glances can only be accessed via the public/external nginx server which is using HTTPS. That's fine for my needs, but it would be nice if all URIs in the web app were protocol-agnostic. It would also be nice if a base path could be set so that the proxy config can be simplified (the double rewrite is a little scary if you think about it...).

**Comment by nicolargo** [comment]
Hi Gavin, thanks for the report and the workaround.

@nclsHart Can you have a look on this issue and implement a correct patch ?

**Comment by notFloran** [comment]
To manage the following url `http://@server:61208/10` for the refresh time we enabled the html5 mode in AngularJs (see https://docs.angularjs.org/guide/$location for explanation) and with this mode we have to hard code the base url (`<base href="/">` in `index.html`).

Without this mode, the web ui works without problem behind a reverse proxy.

We can disable the html5 mode but the url of the webui with refresh time must be change to : 

* `http://@server:61208/#!/10`
* or `http://@server:61208?refresh_time=10`

**Comment by seanvree** [comment]
Anyone have an idea how to fix this on IIS?  

right now my code looks like this:

http://pastebin.com/hTHUqZcn

**Comment by jknight2014** [comment]
@notFloran Couldent you still get your base url in that file from an env variable that is set with a switch? So If I use `glances -w --base_url=/glances/` then its sets `$base_url` to `/glances/`. Although you would need to ether edit the file or use php. On the other hand you could jet set a baseurl by default so it will work for everyone. Set the root to redirect to the base.

**Comment by notFloran** [comment]
@jknight2014 I'm working on a big refactoring of the WebUI that fix all the problems of Glances and reverse proxy.

If you want to try, a wip version (half of the plugins are not available, help and shortcuts do not work) if available here : https://github.com/notFloran/glances/tree/webui-move-to-components

**Comment by seanvree** [comment]
Any updated on getting support for this on the master branch?

**Comment by nicolargo** [comment]
Is anyone can test the DEVELOP branch. The latest commit should solve the issue...

**Comment by nicolargo** [comment]
@gavinws Have you tested the DEVELOP branch ?
