### ISSUE TITLE
Auto-start on Ubuntu

### ISSUE THREAD

**Issue by Drewster727** [nicolargo/glances#880]
Hello,

I'm having an issue getting glances to autostart on my system. Here are my system specs and details:

**Ubuntu 15.10 Server
Glances 2.6.2**

Here's what I've tried so far:
- I have created an init script in /etc/init that simply calls **"glances --export-influxdb"** and it simply doesn't do anything on startup...
- I have added **"glances --export-influxdb"** to my /etc/rc.local startup script, but it never starts with the system at boot
- After the above items didn't work... I fell back to using apt-get to install glances installs an older version. However, this method did install the init.d script, and even though glances STILL never started at boot, I could run it via "sudo service glances start" command and it appeared to be running BUT still had trouble getting the daemon args with --export-influxdb working. I fell back to running **"wget -O- https://bit.ly/glances | /bin/bash"** to install the latest version + dependencies.

Other notes... I have configured my config in **/etc/glances/glances.conf** to point correctly to influxdb. When I run the "glances --export-influxdb" command directly, everything works fine, but there in lies the problem, I don't want to have to run it manually.

Can anyone give me details on how to get this working? I'd just like to have glances auto start in the background on my system and export to influxdb.

Thanks!

**Comment by nicolargo** [comment]
Hi @Drewster727 first of all you need the latest version to export stats to InfluxDB (the apt one did not have this feature).

When you start the Glances daemon, can you have a look on the Glances log file (/tmp/glances.log) and double check that Glances read the correct glances.conf file (/etc/glances/glances.conf). Also have a look if there is other warning or error.

**Comment by Drewster727** [comment]
hey @nicolargo thanks for the reply. 

I followed the systemd service setup via this post: https://groups.google.com/forum/#!topic/glances-users/KrszowyWt8w

Here it is:
```
Unit]
Description=Glances

[Service]
ExecStart=/usr/local/bin/glances --export-influxdb
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

It appears to start properly, but I get no data rolling into influxdb. However, running it manually via command line "glances --export-influxdb" works just fine.

And here is what I see in the glances.log file (cleared it right before starting the systemd service):
```
2016-07-05 22:53:39,992 -- INFO -- Start Glances 2.6.2
2016-07-05 22:53:39,992 -- INFO -- CPython 2.7.10 and PSutil 4.3.0 detected
2016-07-05 22:53:39,996 -- INFO -- Read configuration file '/etc/glances/glances.conf'
2016-07-05 22:53:39,997 -- INFO -- Start standalone mode
2016-07-05 22:53:40,103 -- INFO -- Starting new HTTP connection (1): localhost
2016-07-05 22:53:40,106 -- INFO -- Stats will be exported to InfluxDB server: http://localhost:8086
2016-07-05 22:53:40,124 -- WARNING -- Can not connect to an HDDtemp server (127.0.0.1:7634 => [Errno 111] Connection refused)
```

I *think* the HDDtemp error is unrelated. Pretty sure I saw that in the logs even after running it manually.

Any ideas? Just can't get the thing to export to influx when it's running as a service...

**Comment by nicolargo** [comment]
Hi @Drewster727 , i confirm that the HDDtemp error is not related to this issue (it's not an error, just a warning). 

Concerning your issue, no idea for the moment, i am going to build a testbed to reproduce it on my side.

**Comment by nicolargo** [comment]
@Drewster727 perhaps Glances did not work because it try to display the Curses (CLI) interface can you try the following configuration:

```
[Unit]
Description=Glances

[Service]
ExecStart=/usr/local/bin/glances --quiet --export-influxdb
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by Drewster727** [comment]
I think you just solved it @nicolargo, the --quiet must be needed to run in the background. Thank you sir!

**Comment by nicolargo** [comment]
Done my lord: https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

**Comment by Drewster727** [comment]
@nicolargo well I have bad news... I thought this was working, but it's not quite.

running **sudo systemctl start glances.service** works great. The data starts flowing into influxdb with no problems. However, after a reboot, I get nothing. The service should start automatically at boot, but it doesn't work. I have to run the systemctl start command again manually for it to kick off again.

**Comment by Drewster727** [comment]
more info... Here's what I see when I run **sudo systemctl status glances.service** right after a reboot:

```glances.service - Glances
   Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset:                                                                                                        enabled)
   Active: failed (Result: exit-code) since Fri 2016-07-08 14:24:07 CDT; 48s ago
  Process: 1198 ExecStart=/usr/local/bin/glances --quiet --export-influxdb (code                                                                                                       =exited, status=1/FAILURE)
 Main PID: 1198 (code=exited, status=1/FAILURE)

Jul 08 14:24:07 vdserver glances[1198]: File "/usr/local/lib/python2.7/dist-...e
Jul 08 14:24:07 vdserver glances[1198]: return list(self.query("SHOW DATABAS...)
Jul 08 14:24:07 vdserver glances[1198]: File "/usr/local/lib/python2.7/dist-...y
Jul 08 14:24:07 vdserver glances[1198]: expected_response_code=expected_resp...e
Jul 08 14:24:07 vdserver glances[1198]: File "/usr/local/lib/python2.7/dist-...t
Jul 08 14:24:07 vdserver glances[1198]: raise e
Jul 08 14:24:07 vdserver glances[1198]: requests.exceptions.ConnectionError:...)
Jul 08 14:24:07 vdserver systemd[1]: glances.service: Main process exited, ...RE
Jul 08 14:24:07 vdserver systemd[1]: glances.service: Unit entered failed state.
Jul 08 14:24:07 vdserver systemd[1]: gl```

But, running **sudo systemctl start glances.service** manually after bootup runs just fine and glances starts.

**Comment by nicolargo** [comment]
You should configure systemd to start InfluxDB before Glances...

**Comment by Drewster727** [comment]
Good call. Unfortunately, that did not get it working on startup. Using the following service file:

```
[Unit]
Description=Glances
After=influxd.service
Requires=influxd.service

[Service]
ExecStart=/usr/local/bin/glances --quiet --export-influxdb
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

Not much in the logs telling me what happened. Still works when I start the service manually.

**Comment by nicolargo** [comment]
Try this:

```
[Unit]
Description=Glances

[Service]
ExecStart=/usr/local/bin/glances --quiet --export-influxdb
Restart=on-abort
TimeoutStartSec=1m

[Install]
WantedBy=multi-user.target
```

**Comment by Drewster727** [comment]
@nicolargo tried that already. Didn't work :(

**Comment by nicolargo** [comment]
No idea.. Sorry.

**Comment by Drewster727** [comment]
```
● glances.service - Glances
   Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since Mon 2016-07-11 10:02:59 CDT; 2min 30s ago
  Process: 2491 ExecStart=/usr/local/bin/glances --quiet --export-influxdb (code=exited, status=1/FAILURE)
 Main PID: 2491 (code=exited, status=1/FAILURE)

Jul 11 10:02:59 vdserver systemd[1]: glances.service: Unit entered failed state.
Jul 11 10:02:59 vdserver systemd[1]: glances.service: Failed with result 'exit-code'.
Jul 11 10:02:59 vdserver systemd[1]: glances.service: Service hold-off time over, scheduling restart.
Jul 11 10:02:59 vdserver systemd[1]: Stopped Glances.
Jul 11 10:02:59 vdserver systemd[1]: glances.service: Start request repeated too quickly.
Jul 11 10:02:59 vdserver systemd[1]: Failed to start Glances.
Jul 11 10:03:00 vdserver systemd[1]: glances.service: Unit entered failed state.
Jul 11 10:03:00 vdserver systemd[1]: g
```

**Comment by Drewster727** [comment]
Figured it out. Had to set the service to restart on failure and set a delay between restarts, in addition to the dependency requirements:

```
[Unit]
Description=Glances
After=network.target influxd.service

[Service]
ExecStart=/usr/local/bin/glances --quiet --export-influxdb
Restart=on-failure
RestartSec=30s
TimeoutSec=30s

[Install]
WantedBy=multi-user.target
```

This may only be necessary for influxdb (or other exporting options). Can you update the wiki @nicolargo? Thanks for your help!

**Comment by nicolargo** [comment]
Done thanks you !

**Comment by PrathikGopal** [comment]
I think it is now:  

>  --export influxdb

 for exporting stats to multiple locations. Someone please update [wiki](https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd), it threw me off..
