### ISSUE TITLE
Aliases not supported in web UI?

### ISSUE THREAD

**Issue by vena** [nicolargo/glances#882]
Using a fresh docker pull, attempting to use aliases in diskio and sensors, the aliases only apply in console mode.  The web UI always shows the real device names.

Glances v2.7_BETA with psutil v4.1.0

used a minimal conf to test:
```
[diskio]
sdb1_alias=Disk B

[sensors]
fan1_alias=CPU Fan
```

**Comment by nicolargo** [comment]
@nclsHart / @nclsHart : Can you have a look ?

**Comment by nclsHart** [comment]
@nicolargo Aliases are not availables through the API.

**Comment by nicolargo** [comment]
@nclsHart : Done.

Disk with alias:

```
    {
        "read_count": 0,
        "alias": "IntDisk",
        "write_bytes": 0,
        "write_count": 0,
        "time_since_update": 1,
        "read_bytes": 0,
        "key": "disk_name",
        "disk_name": "sda1"
    }
```

and without:

```
    {
        "read_count": 0,
        "write_bytes": 0,
        "write_count": 0,
        "time_since_update": 1,
        "read_bytes": 0,
        "key": "disk_name",
        "disk_name": "sda1"
    }
```

Idem for sensors...

**Comment by hkapanen** [comment]
sensor aliases still not supported?
