### ISSUE TITLE
PermissionError/OSError when starting glances

### ISSUE THREAD

**Issue by jakirkham** [nicolargo/glances#885]
When trying to start up `glances`, it crashes due to a `PermissionError` or `OSError` (on Python 2.x). Traceback is shown below. I have tried a few different versions of `glances` and `psutil`. If I revert back to `psutil` version `2.2.1`, the issue goes away. Though my guess is that is only because this code path is not present there. It is probably possible to get around this issue by running with `sudo`. However, that is really not an option for the machine I'm trying to use this on. I used `conda` to install these from `conda-forge`. So, it should be reproducible that way.

```
$ lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	Scientific
Description:	Scientific Linux release 6.3 (Carbon)
Release:	6.3
Codename:	Carbon
$ glances -V
Glances v2.6.2 with psutil v4.3.0
$ glances 
Traceback (most recent call last):
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/bin/glances", line 6, in <module>
    sys.exit(glances.main())
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/__init__.py", line 130, in main
    args=core.get_args())
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/standalone.py", line 67, in __init__
    self.stats.update()
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/plugins/glances_plugin.py", line 658, in wrapper
    ret = fct(*args, **kw)
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/plugins/glances_network.py", line 90, in update
    netstatus = psutil.net_if_stats()
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/psutil/__init__.py", line 1961, in net_if_stats
    return _psplatform.net_if_stats()
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/psutil/_pslinux.py", line 791, in net_if_stats
    isup, duplex, speed, mtu = cext.net_if_stats(name)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by nicolargo** [comment]
I think that the bug should be reported to the PsUtil community. Nevertheless, i just code a work around on the DEVELOP branch. 

I don't know if you can test it on your system... (i do not use Anaconda). Or you can try to patch the /groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/glances/plugins/glances_network.py file by changing the except line:

            try:
                netstatus = psutil.net_if_stats()
            except:
                pass

**Comment by jakirkham** [comment]
Happy to try any proposed fixes. Also, if this needs to be referred upstream, happy to do that as well. Though I'm not exactly sure what we want to ask to have changed at this point.

**Comment by nicolargo** [comment]
@jakirkham just open an issue on the PsUtil Github and copy/paste the result of the following command line on your system:

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.net_if_stats()
{'lo': snicstats(isup=True, duplex=0, speed=0, mtu=65536), 'docker0': snicstats(isup=True, duplex=0, speed=0, mtu=1500), 'wlan0': snicstats(isup=True, duplex=0, speed=0, mtu=1500)}
```

Also add a link to the current Glances issue.

Thanks !

**Comment by jakirkham** [comment]
Sorry running into some issues with things not getting update correctly in the GitHub interface.

**Comment by jakirkham** [comment]
So, you are using Docker to test, correct? Are you `root` in your test Docker container? If so, you may be able to reproduce this by creating a new user that has ordinary permissions and switching to it first. Just a thought.

**Comment by nicolargo** [comment]
Nope, i do not use Docker to test Glances.

**Comment by jakirkham** [comment]
Sorry, I thought I saw a reference to Docker in the snippet above.
