### ISSUE TITLE
Install Glance v2.6.2 on windows server 2008 french 

### ISSUE THREAD

**Issue by alpern95** [nicolargo/glances#886]
#### Description
hello i have this error when using glances in Windows.

    'msgdict': self.msg_curse(args),
  File "c:\python27\lib\site-packages\glances\plugins\glances_processlist.py", l
ine 412, in msg_curse
    ret.extend(self.get_process_curses_data(p, first, args))
  **File "c:\python27\lib\site-packages\glances\plugins\glances_processlist.py", l
ine 216, in get_process_curses_data**
    msg = ' {0:9}'.format(str(p['username'])[:9])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 16:
 ordinal not in range(128)

#### Versions
glances --version Glances v2.6.2 with psutil v4.3.0
Windows Server 2008 R2 Entreprise

#### Workaround

I change the line 216 in c:\python27\lib\site-packages\glances\plugins\glances_processlist.py
            msg = ' {0:9}'.format((p['username'])[:9])
            #msg = ' {0:9}'.format(str(p['username'])[:9])

#### Question 
Did you correct this bug in future version?

**Comment by nicolargo** [comment]
Yes, it is already corrected in the develop branch: https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_processlist.py#L232

Nevertheless, thanks for your time to complete this issue.
