### ISSUE TITLE
System uptime in export

### ISSUE THREAD

**Issue by Drewster727** [nicolargo/glances#890]
Is it possible to get the system uptime information in the export? I'm currently exporting system info to influxdb via **glances --quiet --export-influxdb** and I don't see that information anywhere. Thanks!

#### Versions

* Glances (glances -V):  2.6.2
* PSutil (glances -V): 4.3.0
* Operating System (lsb_release -a): Ubuntu Server 15.10

**Comment by nicolargo** [comment]
For the moment (Glances 2.6.2 and probably 2.7), Glances only export float because InfluxDB did not accept other types. One work around is to export a timestamp. Should be discussed...

**Comment by stephane-martin** [comment]
Much more ease with influxdb v0.13:

https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/

"Field values can be one of four types. The first value written for a given field on a given measurement defines the type of that field for all series under that measurement."

Integers, floats, booleans, strings

**Comment by nicolargo** [comment]
Postpone until InfluxDB 0.13 or higher will be installed on all system.

**Comment by thomasbl** [comment]
collectd is exporting the uptime as a unix timestamp... maybe it can be done this way in glances, too?

**Comment by nicolargo** [comment]
Done in the latest HEAD version of the DEVELOP branch (will be available in the 2.8 version).

Uptime is exported in seconds.

![selection_265](https://cloud.githubusercontent.com/assets/776747/19625686/ada19138-991f-11e6-8fe9-6b320a18ec97.png)

**Comment by thomasbl** [comment]
thx
