### ISSUE TITLE
Error  Unicode Windows 2008 R2

### ISSUE THREAD

**Issue by alpern95** [nicolargo/glances#891]
#### Description
Error  Unicode
#### Versions
Glances v2.6.2 with psutil v4.3.0
#### Logs
c:\python27\lib\site-packages\psutil\_pswindows.py:295: UnicodeWarning: Unicode equal comparison failed to convert both
arguments to Unicode - interpreting them as being unequal
  ret[name] = _common.snicstats(isup, duplex, speed, mtu)
Glances server is running on 0.0.0.0:61209

###
Glances works but display this error (above)

I would like to launche glances as a service with this power shell scrip but it's failed 'i think this due to the error unicode??

my script for create a service: install-service-glances.ps1
`#` delete service if it already exists
if (Get-Service glances -ErrorAction SilentlyContinue) {
  $service = Get-WmiObject -Class Win32_Service -Filter "name='glances'"
  $service.StopService()
  Start-Sleep -s 1
  $service.delete()
}

$workdir = Split-Path $MyInvocation.MyCommand.Path

`#` create new service
New-Service -name glances `
  -displayName glances `
  -binaryPathName "`"$workdir\\glances.exe`" -s`""

**Comment by nicolargo** [comment]
The unicode issue is just a warning (UnicodeWarning). I do not think that it is the cause of the service error. Can you have a look on the Glances log file (http://glances.readthedocs.io/en/latest/config.html#logging)?

**Comment by alpern95** [comment]
I have this error (1053) when starting glances service in windows.

![2016-07-15 18_57_57-192 168 112 169 - connexion bureau a distance](https://cloud.githubusercontent.com/assets/1835110/16882256/5cb7b824-4abe-11e6-840b-8382e95d84af.png)

**Comment by nicolargo** [comment]
REJECTED cause: can not reproduce.

@alpern95  Have a look on this related issue: https://github.com/nicolargo/glances/issues/915
