### ISSUE TITLE
/tmp/glances.log not writeable when different users run glances

### ISSUE THREAD

**Issue by stephane-martin** [nicolargo/glances#892]
How to reproduce:
- run glances with some user: `sudo -u user1 glances`
- stop it
- run glances with another user: `sudo -u user2 glances`

On the first run, `/tmp/glances.log` is created, owned by user1
On the second run, `/tmp/glances.log` is not writeable by user2.

Suggestions:

- add the current user name in the log filename. 

In `glances/logger.py` replace:
```python
'filename': os.path.join(tempfile.gettempdir(), 'glances.log'
```
with:
```python
'filename': os.path.join(tempfile.gettempdir(), 'glances[{}].log'.format(getpass.getuser())
```
(with a `import getpass` at top of file obviously)

- or add a commandline option to specify the logfile destination

Thanks !

**Comment by nicolargo** [comment]
Already done since Glances 2.3. See issue https://github.com/nicolargo/glances/issues/474.
