### ISSUE TITLE
Wiki: Systemd entry

### ISSUE THREAD

**Issue by boppy** [nicolargo/glances#898]
What about adding some information on how to auto-start the unit? :) [Since the wiki is read-only I attached a possible markdown (as txt file because github doesn't allow md)](https://github.com/nicolargo/glances/files/376967/wiki-systemd.txt):

---

## Create unit
Create a new unit by creating a file called `glances.service` in the `/etc/systemd/system/` folder.

### Example: Start a Glances server
```ini
[Unit]
Description=Glances

[Service]
ExecStart=/usr/local/bin/glances -s
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

### Example: Start a Glances webserver
```ini
[Unit]
Description=Glances

[Service]
ExecStart=/usr/local/bin/glances -w
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

### Example: Start a Glances server exporting stats to an InfluxDB server
```ini
[Unit]
Description=Glances
After=network.target influxd.service

[Service]
ExecStart=/usr/local/bin/glances --quiet --export-influxdb
Restart=on-failure
RestartSec=30s
TimeoutSec=30s

[Install]
WantedBy=multi-user.target
```

## Enable unit for automatic start while booting
```bash
sudo systemctl enable glances.service
```

**Comment by nicolargo** [comment]
Wiki updated: https://github.com/nicolargo/glances/wiki/Start-Glances-through-Systemd

Thanks for the contribution !
