### ISSUE TITLE
Glances installation via install.sh script fails on VPS

### ISSUE THREAD

**Issue by thorian93** [nicolargo/glances#902]
#### Description
When installing glances via the install.sh script on a VPS hosted by Strato the installation fails with the following messages:
Server 1:
`Detected system: strato`
Server 2:
`Detected system: plesk`

The scripts seems to be unable to use the `lsb_release` tool on the servers although it is installed. When using the workaround:
`find /etc -type f -maxdepth 1 \( ! -wholename /etc/os-release ! -wholename /etc/lsb-release -wholename /etc/\*release -o -wholename /etc/\*version \) 2> /dev/null`
it gets the following outputs:
`/etc/strato-release /etc/debian_version`
and
`/etc/plesk-release /etc/debian_version /etc/strato-release`

which result in the error that this is a unsupported system.
#### Servers
Ubuntu 14.04 LTS 64bit
Ubuntu 14.04 LTS 64bit + Plesk 12.5

As far as I can see that this issue is related to the way the distribution detection is done.
Maybe the script simply needs to be expanded with the values I stated above. I would create a pull request if that is the case. If further development would be needed, the I personally can't help.

If further information is needed I will provide it.

I appreciate any support!

**Comment by nicolargo** [comment]
Hi,

first of all thanks for your proposal. A pull request on the auto install script will be welcome.

Please, can you open an issue (just a copy/paste) on the Glances auto installation script repository: https://github.com/nicolargo/glancesautoinstall

You can also make the pull request to this repo.

Thanks.

Nicolas

**Comment by thorian93** [comment]
I have not been aware of the dedicated repo, my apologies.

I opened an issue there and will work on the improvement soon.

**Comment by nicolargo** [comment]
REJECTED: cause, not a Glances issue. Reported to https://github.com/nicolargo/glancesautoinstall/issues/8
