### ISSUE TITLE
Ability to disable swap

### ISSUE THREAD

**Issue by Kami-no** [nicolargo/glances#903]
Option --disable-swap do not hide swap bar under MEM bar. I've 4 cores (soon up to 8) and don't use swap at all. Extra line there without any usable info makes it worse.

BTW it would be nice to disable swap using config file (aliases are boring).

**Comment by nicolargo** [comment]
Already corrected in the DEVELOP branch (using the boring --disable-swap option).

I note the idea to configure the enable/disable status from the conf file.
