### ISSUE TITLE
IRQ monitoring plugin

### ISSUE THREAD

**Issue by angelopoerio** [nicolargo/glances#905]
I have been using glances since few months and I find it to be very useful. I think it could be useful to monitor the IRQs that happen on a system to have a better understanding of what it is happening. I wrote a plugin that parses /proc/interrupts and show the top 5 (by rate/s). 
I hope it can help.
Regards,
Angelo

**Comment by nicolargo** [comment]
Hi Angelo,

thanks for the proposal. It will be a great feature. But i think that your pull request should be done on the PSUtil lib (https://github.com/giampaolo/psutil/issues). Glances uses PsUtil to grab the system stats. PSUtil is multi-plateform (Linux, BSD, Unix, Mac OS, Windows).

What do you think ?

Nicolas

**Comment by angelopoerio** [comment]
Hi Nicolas,

I agree with you, it would be better to add this feature to psutil (a great
lib!). But before doing this it would be better if you could take a look to
my code (and run glances with my plugin).

P.S: I tried to publish my feature branch (called "irq_monitoring") but I
get an access denied error.
Regards,
Angelo

2016-08-19 21:45 GMT+02:00 Nicolas Hennion <notifications@github.com>:

**Comment by nicolargo** [comment]
Use the Pull request feature https://github.com/nicolargo/glances/pulls from the DEVELOP branch.

You can also read the following Wiki page: https://github.com/nicolargo/glances/wiki/How-to-contribute-to-Glances-%3F

**Comment by angelopoerio** [comment]
Can't push my code, still getting access denied.

2016-08-19 22:09 GMT+02:00 Nicolas Hennion <notifications@github.com>:

**Comment by nicolargo** [comment]
Can you send me the patch by mail ? contact@nicolargo.com

**Comment by nicolargo** [comment]
Additionnal information about the /proc/interrupts file:

- https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-proc-interrupts.html


>     XT-PIC — This is the old AT computer interrupts.
> 
>     IO-APIC-edge — The voltage signal on this interrupt transitions from low to high, creating an edge, where the interrupt occurs and is only signaled once. This kind of interrupt, as well as the IO-APIC-level interrupt, are only seen on systems with processors from the 586 family and higher.
> 
>     IO-APIC-level — Generates interrupts when its voltage signal is high until the signal is low again.

- http://www.thegeekstuff.com/2014/01/linux-interrupts/
- http://www.crashcourse.ca/wiki/index.php/Proc_interrupts

**Comment by angelopoerio** [comment]
Hi Nicolas,

I send you the patch files for my plugin. Your link are very useful! An other useful metric is also monitoring softirqs. It is a kind of mechanism of the linux kernel to execute deferred jobs (such as processing a network packet in the TCP/IP stack).
Take a look at this: https://0xax.gitbooks.io/linux-insides/content/interrupts/interrupts-9.html

**Comment by nicolargo** [comment]
Great jobs !

Some remarks on your code:

1. the code is not PEP 8 compliant (indentations issues, mix tab and space...)
2. in the Curses interface, the plugin is not align:

![selection_039](https://cloud.githubusercontent.com/assets/776747/17831460/79c643a8-66e9-11e6-811b-496c99e93a99.png)

3. if the /proc/interrupts file is not found (for exemple on BSD, Mac OS or Windows OS, then Glances crach with the following error message):

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nicolargo/Dropbox/dev/glances/glances/__main__.py", line 29, in <module>
    glances.main()
  File "glances/__init__.py", line 127, in main
    args=core.get_args())
  File "glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "glances/plugins/glances_plugin.py", line 726, in wrapper
    ret = fct(*args, **kw)
  File "/home/nicolargo/Dropbox/dev/glances/glances/plugins/glances_irq.py", line 62, in update
    with open('/proc/interrupt') as irq_proc:
IOError: [Errno 2] Aucun fichier ou dossier de ce type: '/proc/interrupts'
```

4. In the Web UI, the rate should be right align and the plugin should be placed after the FS (like in the Curse interface)

![selection_040](https://cloud.githubusercontent.com/assets/776747/17831500/c64ec2bc-66ea-11e6-9e3a-ad3bffcae7ef.png)

**Comment by angelopoerio** [comment]
git patch fucked up the indentation of the code (I will re-run pylint). Thanks for feedback!

**Comment by nicolargo** [comment]
@angelopoerio I just push a big PR (https://github.com/nicolargo/glances/pull/906) concerning the WebUI. Do not forget to make a pull on your repository before applying your change.

**Comment by angelopoerio** [comment]
ok
