### ISSUE TITLE
PSutil library not found. Glances cannot start.

### ISSUE THREAD

**Issue by ky0ncheng** [nicolargo/glances#910]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

PSutil library not found. Glances cannot start.

#### Versions

* Glances (glances -V): 2.62
* PSutil (glances -V):PSutil library not found. Glances cannot start. but `pip freeze` display psutil==4.3.0
* Operating System (lsb_release -a): CentOS Linux release 7.2.1511

#### Logs

➜  ~glances -w
PSutil library not found. Glances cannot start.
➜  ~  pip install glances
Requirement already satisfied (use --upgrade to upgrade): glances in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): psutil>=2.0.0 in /usr/lib64/python2.7/site-packages (from glances)
➜  ~ glances -w
PSutil library not found. Glances cannot start.
➜  ~
➜  ~  pip install psutil
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib64/python2.7/site-packages
➜  ~ glances -w
PSutil library not found. Glances cannot start.

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

------------------

hon 2.7.5 (default, Aug 18 2016, 15:58:25)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help ('modules')

Please wait a moment while I gather a list of all available modules...

/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/usr/lib64/python2.7/site-packages/matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
BaseHTTPServer      bz2                 ipaddress           rexec
Bastion             cPickle             itertools           rfc822
CDROM               cProfile            json                rlcompleter
CGIHTTPServer       cStringIO           keyword             robotparser
ConfigParser        calendar            ldap                rpm
Cookie              catcher             ldapurl             rpmUtils
Crypto              cgi                 ldif                runpy
DLFCN               cgitb               lib2to3             sched
DocXMLRPCServer     chardet             liblzma             scipy
HTMLParser          chunk               linecache           select
IN                  cmath               linuxaudiodev       selinux
M2Crypto            cmd                 locale              sensors
MimeWriter          code                lockfile            sets
OpenSSL             codecs              logging             setuptools
PIL                 codeop              logutils            sgmllib
Queue               collections         lxml                sha
SimpleHTTPServer    colorsys            lzma                shelve
SimpleXMLRPCServer  commands            macpath             shlex
SocketServer        compileall          macurl2path         shutil
StringIO            compiler            mailbox             signal
TYPES               configobj           mailcap             site
UserDict            contextlib          mako                six
UserList            cookielib           markupbase          slip
UserString          copy                markupsafe          smtpd
_LWPCookieJar       copy_reg            marshal             smtplib
_MozillaCookieJar   cpuinfo             math                snack
__builtin__         crypt               matplotlib          sndhdr
__future__          csv                 md5                 socket
_abcoll             ctypes              mhlib               socketio
_ast                curl                mimetools           spwd
_bisect             curses              mimetypes           sqlite3
_bsddb              cycler              mimify              sqlitecachec
_codecs             daemon              mmap                sre
_codecs_cn          datetime            modulefinder        sre_compile
_codecs_hk          dateutil            multifile           sre_constants
_codecs_iso2022     dbhash              multiprocessing     sre_parse
_codecs_jp          dbm                 mutex               ssl
_codecs_kr          dbus                netifaces           stat
_codecs_tw          decimal             netrc               statsd
_collections        decorator           new                 statvfs
_crypt              difflib             nis                 string
_csv                dircache            nntplib             stringold
_ctypes             dis                 ntpath              stringprep
_curses             distutils           nturl2path          strop
_curses_panel       dl                  numbers             struct
_dbus_bindings      dns                 numpy               subprocess
_dbus_glib_bindings docker              opcode              sunau
_elementtree        doctest             operator            sunaudio
_functools          dsml                optparse            symbol
_hashlib            dumbdbm             ordereddict         symtable
_heapq              dummy_thread        os                  sys
_hotshot            dummy_threading     os2emxpath          sysconfig
_imaging            easy_install        ossaudiodev         syslog
_imagingft          elasticsearch       parser              tabnanny
_imagingmath        email               passlib             tarfile
_io                 encodings           pdb                 telnetlib
_json               enum                perf                tempfile
_ldap               errno               pickle              tempita
_locale             exceptions          pickletools         termios
_lsprof             exconsole           pika                test
_multibytecodec     fcntl               pip                 textwrap
_multiprocessing    filecmp             pipes               this
_osx_support        fileinput           pkg_resources       thread
_psutil_linux       firewall            pkgutil             threading
_psutil_posix       fnmatch             platform            time
_pyio               formatter           plistlib            timeit
_random             fpformat            ply                 timing
_snack              fractions           popen2              toaiff
_socket             ftplib              poplib              token
_sqlite3            functools           posix               tokenize
_sqlitecache        future_builtins     posixfile           trace
_sre                gc                  posixpath           traceback
_ssl                gdbm                post                tty
_strptime           genericpath         potsdb              tuned
_struct             get                 pprint              types
_symtable           getopt              profile             unicodedata
_sysconfigdata      getpass             pstats              unittest
_threading_local    gettext             psutil              urlgrabber
_warnings           gevent              pty                 urllib
_weakref            geventwebsocket     public              urllib2
_weakrefset         gi                  pwd                 urllib3
_webp               glances             py_compile          urlparse
abc                 glob                pyasn1              user
acutil              gpgme               pyclbr              uu
aifc                greenlet            pycurl              uuid
antigravity         grp                 pydoc               validate
anydbm              gzip                pydoc_data          warnings
argparse            hashlib             pyexpat             wave
array               heapq               pygtkcompat         weakref
asciidocapi         hmac                pylab               webbrowser
ast                 hotshot             pymdstat            websocket
asynchat            htmlentitydefs      pyparsing           whichdb
asyncore            htmllib             pysmi               wsgiref
atexit              httplib             pysnmp              xattr
audiodev            idlelib             pystache            xdrlib
audioop             ihooks              pytz                xml
backports           imageop             pyudev              xmllib
base64              imaplib             query_string        xmlrpclib
batinfo             imghdr              quopri              xxsubtype
bdb                 imp                 random              yum
beaker              importlib           re                  zeroconf
bernhard            imputil             readline            zipfile
binascii            influxdb            reconfigure         zipimport
binhex              iniparse            repr                zlib
bisect              inspect             request
bottle              io                  requests
bsddb               iotop               resource

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose descriptions contain the word "spam".

**Comment by nicolargo** [comment]
REJECTED: can not reproduce.

Workaround: use the Glances auto installation script.

**Comment by wucl202000** [comment]
I met the same situation.

**Comment by imcdona** [comment]
I'm in the same situation as well.

**Comment by ky0nch3ng** [comment]
@wucl202000 
try this
apt-get install python3-dev

**Comment by bussiere** [comment]
I'am in the same situation also : 
```

-> % sudo pip3 install glances
The directory '/home/bussiere/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bussiere/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting glances
  Downloading https://files.pythonhosted.org/packages/2c/5b/a27e4c2d2e4d64e66d9b184cb314579ac68784785af628f2b17527573082/Glances-2.11.1.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 1.5MB/s 
Requirement already satisfied: psutil>=2.0.0 in /usr/lib/python3/dist-packages (from glances) (5.0.1)
Installing collected packages: glances
  Running setup.py install for glances ... done
Successfully installed glances-2.11.1
bussiere@kusanagi [22:47:33] [~] 
-> % glance
zsh: command not found: glance
bussiere@kusanagi [22:47:38] [~] 
-> % glances
PSutil library not found. Glances cannot start.
bussiere@kusanagi [22:48:24] [~] 
-> % sudo pip3 install psutil 
The directory '/home/bussiere/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bussiere/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (5.0.1)
bussiere@kusanagi [22:49:13] [~] 
-> % 



```

**Comment by bingfengfeifei** [comment]
I'm already install psutil. This issus still occured. It maybe caused by change the default python version.I changed my system python3 version from 3.6 to 3.7. But the psutil's dynamic library is still python3.6 version.
->cd /usr/lib/python3/dist-packages/psutil
->ls
_psutil_linux.cpython-36m-x86_64-linux-gnu.so 
_psutil_posix.cpython-36m-x86_64-linux-gnu.so

If these two file's version is not match your python version, copy two new files and rename to correct python version like this：
->cp _psutil_linux.cpython-36m-x86_64-linux-gnu.so _psutil_linux.cpython-37m-x86_64-linux-gnu.so
->cp _psutil_posix.cpython-36m-x86_64-linux-gnu.so _psutil_posix.cpython-37m-x86_64-linux-gnu.so

After doing this, my problem is resolved.

**Comment by aroldo-biz** [comment]
pip install --upgrade pip && yum install glances -y

be happy

**Comment by marcusnewton** [comment]
@aroldo-biz What yum repo did you use?

**Comment by Abdulaziz-Alhefdhi** [comment]
pip install glances --upgrade

That solved it for me

**Comment by Abdull** [comment]
the following resovled the problem for me on Ubuntu Server 20 LTS Raspberry Pi.

```
# remove snap version:
snap remove glances

# remove apt version:
apt remove glances

# install or upgrade pip version:
pip install glances --upgrade
```
