### ISSUE TITLE
Error: Curses module not found. Glances cannot start in standalone mode.

### ISSUE THREAD

**Issue by COLABORATI** [nicolargo/glances#913]
Following the instructions I did a `pip install glances` but glances does not work after that:
```
Curses module not found. Glances cannot start in standalone mode.
```

Please add information to the installation docs about what shold be done when hitting that error. 
Also if there is any dependency to run glances, please add that dependency to setup script, thanks!

**Comment by COLABORATI** [comment]
Forget it, just the usual Python Package MumboJumbo.
Fix: https://github.com/yyuu/pyenv/issues/240

**Comment by anselal** [comment]
Had the same issue on openSuSE 42.3. Fixed it by installing python3-curses.
@nicolargo I think that python-curses and/or python3-curses package must be added to the requirements in the README.md file

**Comment by jaredthirsk** [comment]
I'm on Windows powershell and this worked:

```ps1
pip install windows-curses
curses.exe
```

**Comment by SH4D0WBROK3R** [comment]
Hi, I tried what jaredthirsk suggested and it didn't work for me.
