### ISSUE TITLE
Installation fails because of cassandra dependency

### ISSUE THREAD

**Issue by mitzkia** [nicolargo/glances#916]
#### Description
Can not install glances with the suggested installation step: `curl -L https://bit.ly/glances | /bin/bash`
Error message:
```
...
Collecting bernhard
  Downloading bernhard-0.2.4.tar.gz
Collecting cassandra
  Could not find a version that satisfies the requirement cassandra (from versions: )
No matching distribution found for cassandra
```

(Of course the `pip install glances` works, so I can use it)

#### Versions

* Glances (glances -V):
* PSutil (glances -V):
* Operating System (lsb_release -a):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

* pip version:
```
$ pip --version
pip 8.1.2 from /home/micek/.local/lib/python2.7/site-packages (python 2.7)
```

**Comment by nicolargo** [comment]
I just correct the glances auto install script: https://github.com/nicolargo/glancesautoinstall/issues/10

**Comment by brianlinuxing** [comment]
The web page at https://pypi.python.org/pypi/Glances as of 21st Jan 2017, still shows the old "cassandra" not "cassandra-driver" in the installation instructions.

**Comment by nicolargo** [comment]
Just release the Glances 2.8 version and the  https://pypi.python.org/pypi/Glances is up to date with the new cassandra-driver dep.
