### ISSUE TITLE
problem when installing glances under ubuntu 14.04 64 bits

### ISSUE THREAD

**Issue by superservidor** [nicolargo/glances#920]
When I try to install glances using:

#  curl -L http://bit.ly/glances | /bin/bash

I get the following messages on console and nothing more happens:

Running setup.py install for cassandra-driver
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'

At this point I must press CTRL +  C to cancell the install.

What can I do to be able to finish the install?

Thanks !

**Comment by nicolargo** [comment]
Please open the issue on the cassandra-driver issue tracker (https://github.com/datastax/python-driver)
