### ISSUE TITLE
Hdd view not correct

### ISSUE THREAD

**Issue by renat2985** [nicolargo/glances#921]
What's the problem. Look please:
![Image](http://storage8.static.itmages.com/i/16/0917/h_1474103925_5541687_7ddc39103e.png)

**Comment by nicolargo** [comment]
REJECTED: already corrected in https://github.com/nicolargo/glances/issues/714
Please update your Glances software.

**Comment by renat2985** [comment]
How can I upgrade to the new version?

```
pip install --upgrade glances
Requirement already up-to-date: glances in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: psutil>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from glances)

glances -V                        
Glances v2.3 with psutil v3.4.2

```
