### ISSUE TITLE
High CPU consumption with py3sensors on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#922]
#### Description

On my Ubuntu 16.04, if i install Py3sensor (https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz), the Glances CPU consumption increases from 3% to 30%.

WORKAROUND: uninstall Py3Sensor...

```
sudo rm -rf /usr/local/lib/python2.7/dist-packages/sensors
```

Note: No problem on my CentOS test bed...
#### Versions
- Glances (glances -V): 2.7.1
- PSutil (glances -V): 4.3.1
- Operating System (lsb_release -a): Ubuntu 16.04

**Comment by nicolargo** [comment]
Note: PySensors is available in Pypi: https://pypi.python.org/pypi/PySensors/

**Comment by asergi** [comment]
PySensors != Py3Sensors.
The first doesn't have Python 3 support yet.
The latter is a fork of the first that adds Python 3 support.

**Comment by nicolargo** [comment]
Closed: no more useful, future Glances version will use PsUtil. See https://github.com/nicolargo/glances/issues/1018
