### ISSUE TITLE
/bin/sh: 1: python: not found in the latest Docker image

### ISSUE THREAD

**Issue by thbkrkr** [nicolargo/glances#925]
Hi,

Thank you for this great tool.

Today I started glances in Docker on a new machine and got a fresh image built automatically after the last merge https://github.com/nicolargo/glances/pull/924 that fixes the 'docker build'.

When I run the latest image, Python is not installed:
```
> docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -it docker.io/nicolargo/glances
/bin/sh: 1: python: not found
```

On my machine I tagged the image before to pull it to see the difference:
```
nicolargo/glances                                      latest                   4a5fedf7a909        2 hours ago         143.4 MB
nicolargo/glances                                      ok                       3814deda9477        5 months ago        468.2 MB
```

The problem comes from the install script https://github.com/nicolargo/glancesautoinstall/blob/master/install-develop.sh#L16 used by the Dockerfile https://github.com/nicolargo/glances/blob/master/Dockerfile#L12.

A PR has already been opened to remove a forgotten exit:
https://github.com/nicolargo/glancesautoinstall/pull/11/commits/ef330f4e5cbc59b8a7996ad401490d810c52a5d4

**Comment by nicolargo** [comment]
Done: https://github.com/nicolargo/glancesautoinstall/commit/e11e53007add3daea25c5f059335c4464a1b7cfe !

**Comment by thebwt** [comment]
In addition, can we get you to rerun the latest dockerhub build so it can fetch the updated script? 

https://hub.docker.com/r/nicolargo/glances/builds/bd7qrcvzfem7fx3hyucs7fj is the last run.

Then I can kick it out to my environments! The docker build worked locally so we should be all green from here.

**Comment by thebwt** [comment]
Looks like it is online! Thanks for your hard work @nicolargo !!
