### ISSUE TITLE
Glances RAID plugin Traceback

### ISSUE THREAD

**Issue by Lanvin2219** [nicolargo/glances#927]
Hi everyone,

I don't know why but I got this error since I upgraded Ubuntu.

#### Description

When I type 'glances', I get this error : 

Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/glances/__init__.py", line 130, in main
    standalone.serve_forever()
  File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "/usr/local/lib/python3.5/dist-packages/glances/standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python3.5/dist-packages/glances/outputs/glances_curses.py", line 555, in display
    args=self.args)
  File "/usr/local/lib/python3.5/dist-packages/glances/plugins/glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python3.5/dist-packages/glances/plugins/glances_raid.py", line 102, in msg_curse
    status = self.raid_alert(self.stats[array]['status'], self.stats[array]['used'], self.stats[array]['available'])
  File "/usr/local/lib/python3.5/dist-packages/glances/plugins/glances_raid.py", line 148, in raid_alert
    if used < available:
TypeError: unorderable types: NoneType() < NoneType()

#### Versions

Glances v2.7.1 with psutil v4.3.1
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by nicolargo** [comment]
Strange... As a workaround disable the raid plugin from the command line (--disable-raid).

**Comment by nicolargo** [comment]
@Lanvin2219 Please can you execute the following code on a terminal and copy/paste the result:

```
$ python
> from pymdstat import MdStat
> mds = MdStat()
> print(mds.get_stats()['arrays'])
```

**Comment by Lanvin2219** [comment]
Sorry for the late answer.

--disable-raid option works.
root@SERV-TAL-JT2:~# python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymdstat import MdStat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pymdstat
>>>

**Comment by nicolargo** [comment]
Try this before:

   pip install pymdstat

(or sudo pip install pymdstat)

**Comment by Lanvin2219** [comment]
root@SERV-TAL-JT2:~# pip install pymdstat
Requirement already satisfied (use --upgrade to upgrade): pymdstat in /usr/local/lib/python3.5/dist-packages
root@SERV-TAL-JT2:~# pip install pymdstat --upgrade
Requirement already up-to-date: pymdstat in /usr/local/lib/python3.5/dist-packages

**Comment by nicolargo** [comment]
You use Python 2.7 but install it for Python 3.5...

Please retry this:

```
$ python3
> from pymdstat import MdStat
> mds = MdStat()
> print(mds.get_stats()['arrays'])
```

**Comment by Lanvin2219** [comment]
Yeah sorry :(

>>> from pymdstat import MdStat
>>> mds = MdStat()
>>> print(mds.get_stats()['arrays'])
{'md2': {'status': 'active', 'available': None, 'config': None, 'components': {'sdb2': '1', 'sda2': '0'}, 'used': None, 'type': 'raid0'}}

**Comment by nicolargo** [comment]
Ok, the problem came from the  'available': None and 'used': None values...

I will write a patch to manage the None value.

**Comment by Lanvin2219** [comment]
Thanks for being so responsive !

**Comment by nicolargo** [comment]
Should be corrected in the DEVELOP branch.

**Comment by Lanvin2219** [comment]
lanvin@SERV-TAL:~/glances-develop# python3 setup.py 
/usr/local/lib/python3.5/dist-packages/setuptools/dist.py:340: UserWarning: The version specified ('2.8_DEVELOP') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version

**Comment by nicolargo** [comment]
Please read this page: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version

**Comment by Lanvin2219** [comment]
The standalone mode works.
