### ISSUE TITLE
Error received after run install  script under a clean ubuntu 14.04 64 bits 

### ISSUE THREAD

**Issue by superservidor** [nicolargo/glances#929]
Under a just installed Ubuntu Server 14.04 64 bits:

I run: 

apt-get update && apt-get install curl -y

and then:

curl -L https://bit.ly/glances | /bin/bash

And I get:

*********************************************************************************************
  Running setup.py install for pymdstat

  Running setup.py install for potsdb
    warning: pypandoc module not found, could not convert Markdown to RST

  Running setup.py install for pystache
    pystache: using: version '3.3' of <module 'setuptools' from '/usr/lib/python2.7/dist-packages/setuptools/__init__.pyc'>

    Installing pystache script to /usr/local/bin
    Installing pystache-test script to /usr/local/bin
  Running setup.py install for py-cpuinfo

    Installing cpuinfo script to /usr/local/bin
  Running setup.py install for bernhard

  Running setup.py install for cassandra-driver
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'

*********************************************************************************************

At this point I must press CTRL+C to cancel the setup and get:
*********************************************************************************************
^CCleaning up...
Operation cancelled by user
Storing debug log for failure in /root/.pip/pip.log
*********************************************************************************************
Then I run:

nano /root/.pip/pip.log

*********************************************************************
And get the last part of log file:
*********************************************************************
warning: manifest_maker: standard file '-c' not found

    reading manifest file 'bernhard.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'bernhard.egg-info/SOURCES.txt'
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/bernhard
    copying build/lib.linux-x86_64-2.7/bernhard/__init__.py -> /usr/local/lib/python2.7/dist-packages/bernhard
    copying build/lib.linux-x86_64-2.7/bernhard/pb.py -> /usr/local/lib/python2.7/dist-packages/bernhard
    byte-compiling /usr/local/lib/python2.7/dist-packages/bernhard/__init__.py to __init__.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/bernhard/pb.py to pb.pyc
    running install_egg_info
    Copying bernhard.egg-info to /usr/local/lib/python2.7/dist-packages/bernhard-0.2.4.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-xQQDWj-record/install-record.txt'
  Running setup.py install for cassandra-driver
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cassandra-driver/setup.py';exec(compile(getattr(tokenize, 'open', ope$
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Operation cancelled by user
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 690, in call_subprocess
    line = console_to_str(stdout.readline())
KeyboardInterrupt

*********************************************************************************
Somebody can help me to solve this problem?

Thanks

Carlos from Santiago, Chile

**Comment by nicolargo** [comment]
The Cassandra lib installation could be very long. Please wait until the installation finish...
