### ISSUE TITLE
Glances to collect data for X seconds and exit 

### ISSUE THREAD

**Issue by tuwid** [nicolargo/glances#935]
Hi,
i'm using Glances v2.7.1 with psutil v4.3.1 and it looks really promising. My current issue is related to an already addressed issue here ( the export to influxdb bug ,  glances crashes after a few seconds ) 
so i thought of running glances in an interval like every minute or so via cron but I didnt find it possible since glances doesnt have such option to run for X seconds end then exit

Is it possible to have a flag like this ? 

Thanks in advance and keep up the good work,
Artur

**Comment by nicolargo** [comment]
You can use the timeout command directly from your shell:

    timeout 60 glances

will execute glances and exit after 60 seconds.

Is it what you want ?

**Comment by tuwid** [comment]
looks like it, thanks
testing it right away
