### ISSUE TITLE
What about improve project description?

### ISSUE THREAD

**Issue by bocharsky-bw** [nicolargo/glances#936]
Now it sounds like:

> Glances an Eye on your system

What about to add a bit more description? It's difficult to find it even when I've starred it on GitHub. Sometimes I forget about its name :) . I think it would be nice to use some keywords like "`top`/`htop` analog" in the project description.

**Comment by nicolargo** [comment]
@all Any proposal ?

**Comment by nicolargo** [comment]
Done but only for the Github repository description.

**Comment by bocharsky-bw** [comment]
Much better now! Thanks!

**Comment by nicolargo** [comment]
@bocharsky-bw thanks you for the proposal :)
