### ISSUE TITLE
Add hotspot Wifi informations

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#937]
#### Description

Thanks to the Wifi lib (https://wifi.readthedocs.io/en/latest/scanning.html), grab and display Wifi hotspot information.

> > > from wifi import Cell, Scheme
> > > Cell.all('wlan0')

This returns a list of Cell objects. Under the hood, this calls iwlist scan and parses the unfriendly output.

Each cell object should have the following attributes:

```
ssid
signal
quality
frequency
bitrates
encrypted
channel
address
mode
```

For cells that have encrypted as True, there will also be the following attributes:

```
encryption_type
```

**Comment by nicolargo** [comment]
Oopsss...

In [4]: w = wifi.Cell.all('wlan0')
---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
<ipython-input-4-d03dc42953ac> in <module>()
----> 1 w = wifi.Cell.all('wlan0')

/usr/local/lib/python2.7/dist-packages/wifi/scan.pyc in all(cls, interface)
     39                                                   stderr=subprocess.STDOUT)
     40         except subprocess.CalledProcessError as e:
---> 41             raise InterfaceError(e.output.strip())
     42         else:
     43             iwlist_scan = iwlist_scan.decode('utf-8')

InterfaceError: wlan0     Interface doesn't support scanning.

**Comment by nicolargo** [comment]
̀``
In [4]: w = wifi.Cell.all('wlp2s0')

In [5]: w
Out[5]: 
[Cell(ssid=Freebox-40A258),
 Cell(ssid=FreeWifi),
 Cell(ssid=FreeWifi_secure),
 Cell(ssid=FREEBOX_ALENA_R3),
 Cell(ssid=FreeWifi),
 Cell(ssid=FreeWifi_secure),
 Cell(ssid=)]

In [6]: w['Freebox-40A258']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d70b2e5be8e6> in <module>()
----> 1 w['Freebox-40A258']

TypeError: list indices must be integers, not str

In [7]: w['Freebox-40A258']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-d70b2e5be8e6> in <module>()
----> 1 w['Freebox-40A258']

TypeError: list indices must be integers, not str

In [8]: w[0]
Out[8]: Cell(ssid=Freebox-40A258)

In [9]: w[0].ssid
Out[9]: u'Freebox-40A258'

In [10]: w[0].signal
Out[10]: -44

In [11]: w[0].quality
Out[11]: u'66/70'

In [12]: w[0].frequency
Out[12]: u'2.472 GHz'

In [13]: w[0].bitrate
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-18bafcb51aab> in <module>()
----> 1 w[0].bitrate

AttributeError: 'Cell' object has no attribute 'bitrate'

In [14]: w[0].bitrates
Out[14]: 
[u'1 Mb/s',
 u'2 Mb/s',
 u'5.5 Mb/s',
 u'11 Mb/s',
 u'22 Mb/s',
 u'6 Mb/s',
 u'9 Mb/s',
 u'12 Mb/s',
 u'18 Mb/s',
 u'24 Mb/s',
 u'36 Mb/s',
 u'48 Mb/s',
 u'54 Mb/s']

In [15]: w[0].mode
Out[15]: u'Master'
```

**Comment by nicolargo** [comment]
Preview:

![selection_263](https://cloud.githubusercontent.com/assets/776747/19602742/b592e274-97ae-11e6-8cf0-81ad865effc2.png)

**Comment by nicolargo** [comment]
Implementation available in the DEVELOP branch.

Please test it.

@nclsHart / @notFloran : Can you implement it on the WebUI ?

**Comment by notFloran** [comment]
@nicolargo I don't have a computer with linux and wifi, can you send me a json of the api results ?

**Comment by nicolargo** [comment]
@notFloran : Here it is:

**curl http://0.0.0.0:61208/api/2/wifi**

    [{"ssid": "Freebox-40A258", "encrypted": true, "signal": -45, "key": "ssid", "encryption_type": "wpa2", "quality": "65/70"}]


**curl http://0.0.0.0:61208/api/2/wifi/views**

    {"Freebox-40A258": {"ssid": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "encrypted": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "signal": {"decoration": "OK", "optional": false, "additional": false, "splittable": false}, "key": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "encryption_type": {"decoration": "DEFAULT", "optional": false, "additional": false, "splittable": false}, "quality": {"decoration": "OK", "optional": false, "additional": false, "splittable": false}}}

In my example there is only one hotspot. You can have multiple hotspot (one dict per hotspot).
If encrypted = true then encryption_type is eqaul to the encryption algorithm. If encrypted = false then encryption_type is equal to 'null' (do not display in the WebUI).

**Comment by nicolargo** [comment]
@notFloran Any news concerning the implementation inside the WebUI ?
