### ISSUE TITLE
AMP Plugin/Stats not visible in webserver mode?

### ISSUE THREAD

**Issue by mannibis** [nicolargo/glances#938]
#### Description

Would it be possible to get the AMP plugin to display when in webserver mode (-w)? I've just upgraded to 2.7 and I'm loving the new AMP plugin that replaces the process monitor, but I noticed that there is no AMP information available when using webserver mode, which I use almost exclusively to remotely monitor my OSX server from work and other locations. The old process monitor was visible in webserver mode, so I can't imagine that the new AMP feature won't work the same way? I apologize if I'm doing something wrong. Thanks

#### Versions

* Glances (glances -V): Glances v2.7.1 
* PSutil (glances -V): psutil v4.3.1
* Operating System (lsb_release -a): Darwin 10.9.5 64bit

**Comment by nicolargo** [comment]
Not reproduced on my site (with Glances 2.7.1)...

Console interface:

![selection_261](https://cloud.githubusercontent.com/assets/776747/19383489/e0a2d230-9204-11e6-90d5-653986154bdd.png)

Web interface:

![selection_262](https://cloud.githubusercontent.com/assets/776747/19383491/e53d5ee6-9204-11e6-83bb-1f32dbf85219.png)

Both show the AMP plugin...

Any log file ? Debug mode (-d).

**Comment by mannibis** [comment]
So, after a few days and several restarts, it is finally showing AMP stats in webserver mode. I wish I could explain it...

Thanks for the great software that is only getting better and better
