### ISSUE TITLE
Add a ZeroMQ export module

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#939]
#### Description

With this request, Glances will be able to export the stats to a ZeroMQ publisher.

### Info....

ZeroMQ web site: http://zeromq.org/
Python API (Pypi):  https://pypi.python.org/pypi/pyzmq
Python API (Doc): https://pyzmq.readthedocs.io/en/latest/
API examples: 
* https://www.digitalocean.com/community/tutorials/how-to-work-with-the-zeromq-messaging-library
* For send_json and recv_json http://www.giantflyingsaucer.com/blog/?p=4967

Test bed: yes there is a Docker for that https://hub.docker.com/r/zeromq/zeromq/

**Comment by nicolargo** [comment]
Done => See the documentation here: https://github.com/nicolargo/glances/blob/develop/docs/gw/zeromq.rst

Please test !

**Comment by GoMapur** [comment]
Hi the simple Python client to subscribe to the Glances stats does not print out anything. I'm trying to find out why now.

**Comment by GoMapur** [comment]
Hi I solved the issue and created a pull request.
