### ISSUE TITLE
Deprecate Windows Curse UI: automaticaly  open Web Browser for the standalone mode

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#946]
#### Description

The Windows Curses interface is a mess. On Windows, Glances standalone mode should start the Web server mode and open automatically the Web browser on the Glances Web UI.

On others systems, an option (--open-web-browser) should be available to have the same behavor.

#### How ?

Use the webbrowser standard lib (https://docs.python.org/2/library/webbrowser.html).

```
import webbrowser

webbrowser.open('http://www.google.fr', new=2, autoraise=1)
```

**Comment by nicolargo** [comment]
Done in the latest commit in the DEVELOP branch.

**Comment by asergi** [comment]
Actually, it's no longer possible to use console mode on Windows, so it's much more than deprecated. What about removing the `glances/outputs/glances_colorconsole.py` at all?

**Comment by nicolargo** [comment]
+1 @asergi

**Comment by asergi** [comment]
cefa8b06cefbe3ab3a62bdaa58b2d4ca94a85ddb
