### ISSUE TITLE
/proc/interrupts not found when running Glances in an OpenVZ container

### ISSUE THREAD

**Issue by yuri-ccp** [nicolargo/glances#947]
First, the Versions!:
Glances v2.7.1 with psutil v2.2.1
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
This is an OpenVZ container!

This version of Glances don't run inside a container because it don't have access to /proc/interrupts from inside:

`Traceback (most recent call last):
  File "/usr/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "/usr/lib/python2.7/site-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 734, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python2.7/site-packages/glances/plugins/glances_irq.py", line 66, in update
    with open('/proc/interrupts') as irq_proc:
IOError: [Errno 2] Arquivo ou diretório não encontrado: '/proc/interrupts'`

The is that glance don't found it and have a fatal error that don't allow it to run, even if I put --disable-irq parameter in command line.

The ideal solution would be to test if the "file" exists and if not, ignore the display of IRQs without major hassles with or without disable-irq parameter.

To workaround the problem I added to "glances/plugins/glances_irq.py" a "import os.path", and changed the line "if not LINUX:" to "if not LINUX or not os.path.isfile('/proc/interrupts'):" but I don't know if this is the ugly solution is the best one (so I won't open a PR).

Sorry for any bad english (is not my native language)

**Comment by nicolargo** [comment]
Hello @yuri-ccp 

First of all, thanks for your issue and the workaround witch can be used by another users.

A know bug will be corrected in the current DEVELOP branch (next 2.8 release) and the --disable-irq (and all other disables tags) will work.

Nevertheless, i let your issue open because a check should also be done on the /proc/interrupts file before reading it.

**Comment by nicolargo** [comment]
Done in the DEVELOP branch (will be release in Glances 2.8).
