### ISSUE TITLE
JS error in web frontend

### ISSUE THREAD

**Issue by mbleichner** [nicolargo/glances#949]
The web frontend sometimes fails to load, giving a JS error about not being able to find _.padLeft(). In fact, this function has been renamed to _.padStart() in lodash 4.0.0.

Replacing the function call in my local main.js solved the issue for me.

For reference: https://github.com/lodash/lodash/wiki/Changelog
(search for "Method renames")

**Comment by nicolargo** [comment]
I think that this issue is the same than https://github.com/nicolargo/glances/issues/934#issuecomment-254072988

Should be corrected in the DEVEL branch.

Can you test it ?
