### ISSUE TITLE
(Terminal) BELLs for critical errors

### ISSUE THREAD

**Issue by yuri-ccp** [nicolargo/glances#950]
**Description**

One of the more interesting functions of the Glances is the ability to detect and show a critical status (when some value is too high or not working correctly), this helps a lot! But sometimes we are not seeing the terminal where the Glances is opened and cannot able to see a critical problem in time.

So I was thinking is could be interesting add some audio support to it. But theres many people that uses Glances remotely (me for example) and pass a sound alert could be some difficult, but I found a way, a terminal bell!

I know a terminal beep is somewhat boring but can be very helpful in cases that the terminal is out of the view. So is possible to us to add some optional "Terminal Beep" support to Glances.

The idea is that beep alert be disable by default and can be enable by user via command line parameter (--enable-bell) and via glances.conf and via key shortcut.

The terminal bell support is relative easy to implement, is just need to send a '\a' to the terminal, this can be done using a print('\a') or sys.stdout.write('\a').

I think would be cool to implement in Glances to send a bell per refresh when a critical alert is happening this way.

What do you think that idea?

Sorry for any bad english.

**Comment by nicolargo** [comment]
Hi @yuri-ccp 

Thinks for your proposal.

Did you know that you can implement action on alert ([click here for the Glances action documentation](glances.readthedocs.io/en/latest/aoa/actions.html)) ?

For example, if you want to add a call to a specific program or command line when the load is critical you just have to edit your Glances configuration file:

```
[load]
critical=5.0
critical_action=/home/myhome/bin/bipper.sh
```

You can add _action to all the careful, warning or critical alert in the Glances configuration file.

Does it respond to your need ?

**Comment by nicolargo** [comment]
@yuri-ccp the main issue is that on modern systems this may not make a noise, it may instead make a visual indication such as flashing the screen, or do nothing at all. I prefer to change this enhancement request for the implementation of a action_repeat feature.

**Comment by nicolargo** [comment]
REJECTED: will be implemented through the action repeat feature (see https://github.com/nicolargo/glances/issues/952).

**Comment by nicolargo** [comment]
Repeat feature implemented in commit https://github.com/nicolargo/glances/commit/6d0fe0f708bc54ae836e64bd346dc649f84acee6 => See https://github.com/nicolargo/glances/issues/952
