### ISSUE TITLE
Add new repeat function to the action

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#952]
#### Description

The goal of this new feature is to be able to run:

* action repeatedly on threshold. For the moment an action is called only when the threshold is reached. 

For example (related to enhancement request https://github.com/nicolargo/glances/issues/950), with the following configuration:

```
[load]
critical=5.0
critical_action=/home/myhome/bin/bipper.sh
```

The bipper.sh script will be called once when the load will be detected as critical.

The current issue proposes to implement a new configuration key (action_repeat):

```
[load]
critical=5.0
critical_action_repeat=/home/myhome/bin/bipper.sh
```

The bipper.sh will be ran at each refresh (by default every 3 seconds) as long as the critical load alert is active.

**Note: be aware that the script is ran every 3 seconds !!!**

**Comment by nicolargo** [comment]
Implemented through the last commit in the DEVELOP branch.
To be tested !

**Comment by nicolargo** [comment]
@yuri-ccp can you test the DEVELOP branch ?

**Comment by yuri-ccp** [comment]
OK, I will
