### ISSUE TITLE
hp-health integration

### ISSUE THREAD

**Issue by SpiGAndromeda** [nicolargo/glances#953]
Hi,

this is a feature request. I am using an HPE Server. HPE provides an linux tool for monitoring different health data of the server. It's called hp-health. For exmaple it provides the fan speed and in some servers also the power consumption. I wanted to know if there could be an hp-health integration for monitoring the fan speed in glances. I guess this could be interesting for all users of an HPE system.

best regards
spigandromeda

**Comment by nicolargo** [comment]
Hi @SpiGAndromeda 

if i understand your need, you want to monitor your HP server. What kind of stats are not already available in Glances. When i read the [HP Health command line documentation](https://oitibs.com/hp-health-command-line-ref/), i see:

* FANS => already available through the [sensor plugin](http://glances.readthedocs.io/en/stable/aoa/sensors.html)
*  TEMP => already available through the [sensor plugin](http://glances.readthedocs.io/en/stable/aoa/sensors.html)

I have no HP server, so can you send us a copy/paste of all the command ? Just to have a look...

**Comment by SpiGAndromeda** [comment]
The Fans cannot be recognized by py3sensors, There are only some temp sensors reckognized by glances.
hp-health is used with the hpasmcli command. You could use that by calling the hpasm command line interface and then typing the commands or using the commands directly from the shell:

The following lines shows and example output:
```
user@Server:~$ sudo hpasmcli -s 'show fans'

Fan  Location        Present Speed  of max  Redundant  Partner  Hot-pluggable
---  --------        ------- -----  ------  ---------  -------  -------------
#1   SYSTEM          Yes     NORMAL  22%     N/A        N/A      No
#2   SYSTEM          Yes     NORMAL  22%     N/A        N/A      No
#3   SYSTEM          Yes     NORMAL  22%     N/A        N/A      No
```

```
user@Server:~$ sudo hpasmcli -s 'show temp'

Sensor   Location              Temp       Threshold
------   --------              ----       ---------
#1        AMBIENT              28C/82F    42C/107F
#2        PROCESSOR_ZONE       40C/104F   70C/158F
#3        PROCESSOR_ZONE        -          -
#4        MEMORY_BD             -          -
#5        MEMORY_BD            36C/96F    87C/188F
#6        MEMORY_BD             -          -
#7        MEMORY_BD             -          -
#8        SYSTEM_BD             -          -
#9        SYSTEM_BD            41C/105F   105C/221F
#10       SYSTEM_BD            33C/91F    85C/185F
#11       POWER_SUPPLY_BAY      -          -
#12       POWER_SUPPLY_BAY      -          -
#13       SYSTEM_BD            42C/107F   115C/239F
#14       SYSTEM_BD             -          -
#15       SYSTEM_BD            33C/91F    115C/239F
#16       SYSTEM_BD            33C/91F    115C/239F
#17       SYSTEM_BD             -          -
#18       SYSTEM_BD             -          -
#19       SYSTEM_BD            33C/91F    115C/239F
#20       SYSTEM_BD            34C/93F    115C/239F
#21       SYSTEM_BD             -          -
#22       SYSTEM_BD            42C/107F   100C/212F
#23       SYSTEM_BD            38C/100F   85C/185F
#24       I/O_ZONE              -          -
#25       I/O_ZONE              -          -
#26       I/O_ZONE              -          -
#27       I/O_ZONE              -          -
#28       I/O_ZONE              -          -
#29       I/O_ZONE              -          -
#30       I/O_ZONE             32C/89F    70C/158F
#31       I/O_ZONE             33C/91F    70C/158F
#32       I/O_ZONE             34C/93F    70C/158F
#33       I/O_ZONE             35C/95F    70C/158F
#34       I/O_ZONE             35C/95F    70C/158F
#35       I/O_ZONE             34C/93F    70C/158F
```

**Comment by nicolargo** [comment]
Could and should be implemented through an dedicated AMP: http://glances.readthedocs.io/en/stable/aoa/amps.html

**Comment by JMY1000** [comment]
@nicolargo Has a dedicated AMP been implemented yet? On my DL580 G5, I'm not showing any sensors (including the CPU temps or fans), despite `sensors` showing the temps of the ISA adapters.
