### ISSUE TITLE
Ambiguous args & options after --disable-* refactor

### ISSUE THREAD

**Issue by hastinbe** [nicolargo/glances#956]
#### Description

Renaming of arguments and option variables introduced by 634f8fb29b7de7325e657f182b18b7b06c6e8d94 is incomplete for the following:

disable_swap -> disable_memswap
disable_log -> disable_alert

#### Versions

* Glances: 2.8_DEVELOP

**Comment by nicolargo** [comment]
Thanks for the patch @hastinbe !
