### ISSUE TITLE
PID column too small if kernel.pid_max is > 99999

### ISSUE THREAD

**Issue by shartge** [nicolargo/glances#959]
I run several systems with kernel.pid_max set to 4194303.

With this setting a PID column of only 6 characters (5 for the numbers and 1 for the spacing) is too small and causes the display to look ugly.

A quick fix would be to increase the size from 6 to 8, but this would waste space on systems with the normal pid_max setting. 

The optimal way would be to read kernel.pid_max and adjust automatically.

**Comment by nicolargo** [comment]
Hi @shartge thnaks for the enhancement proposal.

**Note for the implementation**

The maximum PID number is available through the /proc/sys/kernel/pid_max system file (on a Linux OS).

For example on my system:

    $ cat /proc/sys/kernel/pid_max 
    32768

The following code on top of the(process list plugin should do the trick:

    len(open('/proc/sys/kernel/pid_max').readline()) - 1

The Curses interfaces will be adjust automatically.

**Comment by nicolargo** [comment]
Implementation done in the HEAD version of the DEVELOP branch.

Additionally, the max_pid value is available through the API:

```
=> http://0.0.0.0:61208/api/2/processcount
{"thread": 677, "pid_max": 32768, "zombie": 2, "running": 2, "sleeping": 244, "total": 247} 
```

Note for later: Only available on Linux OS (waiting for PSUtil team -  https://github.com/giampaolo/psutil/issues/720).

**Comment by shartge** [comment]
I think you missed the alignment of the PID header, line 487 in https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_processlist.py#L487
