### ISSUE TITLE
Processes showing up as "Con" and others.

### ISSUE THREAD

**Issue by towo** [nicolargo/glances#965]
#### Description

Not sure what exactly is happening, but it seems like there's some issues with name canonicalization for glances. Process names are shortened in very weird fashions.

This is not the short process mode, FWIW - I can still toggle that and have firefox loose the path, etc.

Process 18694 from the below output has a 2341 character long process name, maybe the issue might be located there. [Chrome it is.]

#### Versions

Glances v2.6.2 with psutil v4.2.0
Ubuntu 16.10

#### Logs

    CPU%  MEM%  VIRT   RES   PID USER        NI S     TIME+   R/s   W/s Command 
    10.8   7.7 2.38G 1.19G 18985 towo         0 S   3h52:23     0     0 /usr/lib/firefox/firefox 
     0.9   7.0 4.22G 1.08G 16684 towo         0 S  11:45.45     0     0 evolution 
     9.6   6.5 2.04G 1.01G 18694 towo         0 S   3h21:25     0     0  
     2.4   6.0 2.91G  948M 16992 towo         0 S   3h34:30   10K    8K google-chrome-beta 
     4.2   4.4 1.67G  701M 17226 towo         0 S   1h06:52     0     0 * 
     4.5   4.4 1.79G  699M 15557 towo         0 S  24:48.52     0     0 Con 
     0.3   2.7 1.81G  419M 30187 towo         0 S   3:52.37     0     0 Con 
    39.8   2.1 1.32G  338M 23535 towo         0 S   7:41.94     0     0 Con 
     0.6   2.1  917M  327M 17042 towo         0 S   2h24:18     0     0 Cont uter/Enabled/ExtensionDeveloperModeWarning/Default/*GFE/Default/InstanceID/Enabled/MaterialDesignDownloads/Enabled/MaterialDesignUserMana
     0.0   1.7 1.07G  272M 18393 towo         0 S   7:09.10     0     0  
     0.9   1.5 1.01G  236M 31663 towo         0 S   0:15.46     0     0 Con 
     0.0   1.5 1007M  230M 19545 towo         0 S   0:44.72     0     0 Con 
    10.2   1.5 1.05G  230M 17797 towo         0 S   2h36:41     0     0  
     0.0   1.4 1.16G  224M 11814 towo         0 S   4:07.21     0     0 Con 
     9.9   1.2 1.80G  184M  9557 towo         0 S   3h30:58    1K   28K /usr/bin/gnome-shell 
     0.0   1.2 1006M  183M  5919 towo         0 S   3:04.35     0     0 Con 
     0.3   1.0 1003M  163M 12370 towo         0 S  16:58.44     0     0 Con 
     0.0   1.0 2.86G  155M 16549 towo         0 S   1:52.84     0     0 /home/towo/.dropbox-dist/dropbox-lnx.x86_64-14.4.19/dropbox 
     0.0   0.9  970M  149M 17741 towo         0 S   1:24.00     0     0  
     0.0   0.9  965M  134M  1397 towo         0 S   0:33.47     0     0 Con 
     0.0   0.8 1.25G  133M 18294 towo         0 S   3:50.48     0     0  
     0.0   0.8  992M  133M 18075 towo         0 S   2:20.76     0     0  
     0.0   0.8  975M  133M 18131 towo         0 S   2:21.70     0     0  
     0.0   0.8 1002M  132M 18189 towo         0 S   3:54.25     0     0  
     0.0   0.8  998M  119M 18216 towo         0 S   2:17.90     0     0  
     0.0   0.7  936M  111M  1635 towo         0 S   0:28.81     0     0 Con 
     0.0   0.7 1.01G  109M 18626 towo         0 S   3:57.50     0     0  
    10.8   0.7  901M  108M 18370 towo         0 S   2h32:31     0     0  
     0.0   0.7  897M  104M 17713 towo         0 S   3:01.75     0     0  
     0.3   0.7  913M  103M 18535 towo         0 S   4:58.54     0     0  
     0.0   0.6  884M  101M 13213 towo         0 S   0:12.77     0     0 Con 
     0.0   0.6  966M  100M 17131 towo         0 S   5:55.46     0     0 St 
     0.0   0.6  989M 99.9M 18618 towo         0 S   3:18.32     0     0  
     0.3   0.6  914M 99.7M 18099 towo         0 S   8:11.91     0     0  
     4.2   0.6  594M 96.0M  9414 towo         0 S   1h38:38     0     0 /usr/lib/xorg/Xorg vt3 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
     0.0   0.6 2.59G 93.3M 16711 towo         0 S   1:08.46     0     0 /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess 38
     0.0   0.6 1.40G 87.2M 11109 towo         0 S   3:05.55     0     0 main.js 
     0.0   0.5  865M 82.6M 17220 towo         0 S   1:54.57     0     0 * 
     0.0   0.5  854M 82.0M 17158 towo         0 S   1:34.79     0     0 * 
     0.0   0.5  836M 81.7M 17720 towo         0 S   1:30.86     0     0  
     0.0   0.5  810M 80.0M  2403 towo         0 S   0:46.80     0     0 Con 
     0.0   0.5  838M 79.9M 18331 towo         0 S   1:19.78     0     0  
     0.0   0.5  852M 76.6M 17086 towo         0 S   0:39.75     0     0 Str 
     0.0   0.5  825M 75.0M 17146 towo         0 S   0:21.60     0     0 * 
     0.0   0.4  815M 70.5M 25776 towo         0 S   0:02.63     0     0 Con

**Comment by asergi** [comment]
Can you test with the latest Glances, please? I think this issue has already been resolved in 2.7.

**Comment by towo** [comment]
Correct, I'll pester Ubuntu on launchpad, then. Thanks.

**Comment by asergi** [comment]
Also duplicate of #826.
