### ISSUE TITLE
Exporting CSV : Mismatching Data in columns 

### ISSUE THREAD

**Issue by arwhiz123** [nicolargo/glances#971]
#### Description

when we generate csv using **glances -t 1  --export-csv /home/eddi/glances/GlancesLog100User.csv**

![image](https://cloud.githubusercontent.com/assets/23705299/20572586/db48e7c8-b1cd-11e6-9f81-ac6a432902ab.png)

**Comment by nicolargo** [comment]
I think that this issue is duplicated and solved in Glances 2.7 or higher => https://github.com/nicolargo/glances/issues/847

What is your Glances version ?

**Comment by arwhiz123** [comment]
I'm Using Glances v2.7.1 with psutil v5.0.0 

![image](https://cloud.githubusercontent.com/assets/23705299/20594213/1e1cf916-b257-11e6-8643-7bb0bb58126a.png)

**Comment by nicolargo** [comment]
Do not know...

Can you try to run Glances in debug mode (option -d) and send us back the /tmp/glances.log file (in a [paste/bin](http://pastebin.com/) link) ?

**Comment by arwhiz123** [comment]
http://pastebin.com/emiAe1gE

**Comment by nicolargo** [comment]
and also passte/bin an extract of your CSV output file (more easy to debug...).
