### ISSUE TITLE
Web Server Mode doesn't render tasks correctly

### ISSUE THREAD

**Issue by dkanejs** [nicolargo/glances#972]
#### Description

On a fresh installation I run `glances -w` and navigate to [http://localhost:61208](http://localhost:61208)

The task list time column looks like the following:

![screenshot_2016-11-24_16-55-20](https://cloud.githubusercontent.com/assets/1489861/20606109/ce5473fe-b266-11e6-8085-a52a89fdd110.png)

#### Versions

* Glances (glances -V): v2.6.2
* PSutil (glances -V):  v4.2.0
* Operating System (lsb_release -a): Ubuntu 16.10 (Xubuntu)

**Comment by nicolargo** [comment]
Can you try with the latest stable release Glances 2.7.1 ?

Thanks !

**Comment by dkanejs** [comment]
I used `apt-get` to install glances.

After removing and using `pip` to install 2.7.1 it's all working now :+1:
