### ISSUE TITLE
Coloring is difficult to read on a white background

### ISSUE THREAD

**Issue by chris-martin** [nicolargo/glances#976]
I just tried glances-2.6.2 in Gnome Terminal with the default black-on-white color scheme, and the primary gray text color is fairly unreadable.

![screenshot from 2016-11-29 14-18-32](https://cloud.githubusercontent.com/assets/399718/20725299/4f33a1bc-b63f-11e6-8417-1f402460ac90.png)

If glances is intended only for a dark background, then perhaps it should set a background color explicitly?

**Comment by chris-martin** [comment]
Oh, I just found the `--theme-white` option, which is nice, but - It would be great to have a single command that's usable regardless of which terminal emulator I'm using at the moment.

**Comment by nicolargo** [comment]
Goog idea but the get background color of the Curses API do not work as excepted:

![image](https://cloud.githubusercontent.com/assets/776747/20727686/ccd9cd72-b67a-11e6-8ffb-d454cdb8df5e.png)

**Comment by JohannesBuchner** [comment]
Could you please put this in the FAQ?

Q: How do I use glances on a white terminal background?
A: glances --theme-white

**Comment by EHJ-52n** [comment]
It would be nice to have a switch for the themes when glances is already running, or use terminal default colors.

**Comment by nicolargo** [comment]
@EHJ-52n done in the develop branch through the '9' hotkey.

Will be released in Glances 3.2.4

**Comment by ankostis** [comment]
in `Glances v3.2.5 with PsUtil v5.9.0` it works indeed fine, but the keystroke is not listed in the [H]elp menu.

**Comment by EHJ-52n** [comment]
The hotkey <kbd>9</kbd> is working as expected under `Ubuntu 22.04.1 LTS` with version `3.2.4.2+dfsg-1` (`Glances v3.2.4.2 with PsUtil v5.9.0`).

But it is not shown in the help menu, too:

```
Glances 3.2.4.2 with psutil 5.9.0

Configuration file: /etc/glances/glances.conf

 a  Sort processes automatically          b  Bytes or bits for network I/O      
 c  Sort processes by CPU%                l  Show/hide alert logs
 m  Sort processes by MEM%                w  Delete warning alerts
 u  Sort processes by USER                x  Delete warning and critical alerts 
 p  Sort processes by name                1  Global CPU or per-CPU stats        
 i  Sort processes by I/O rate            I  Show/hide IP module                
 t  Sort processes by TIME                D  Enable/disable Docker stats        
 d  Show/hide disk I/O stats              T  View network I/O as combination    
 f  Show/hide filesystem stats            U  View cumulative network I/O        
 n  Show/hide network stats               F  Show filesystem free space         
 s  Show/hide sensors stats               g  Generate graphs for current history
 2  Show/hide left sidebar                r  Reset history                      
 z  Enable/disable processes stats        h  Show/hide this help screen         
 3  Enable/disable quick look plugin      B  Count/rate for Disk I/O            
 e  Enable/disable top extended stats     5  Show/hide top menu (QL, CPU, MEM, SWAP and LOAD)
 /  Enable/disable short processes name   Q  Show/hide IRQ stats                
 G  Enable/disable gpu plugin             6  Enable/disable mean gpu            
 0  Enable/disable Irix process CPU       q  Quit (Esc and Ctrl-C also work)    

ENTER: Edit the process filter pattern
```
