### ISSUE TITLE
Enhance Glances browser color

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#977]
#### Description

Enhancement related to issue https://github.com/nicolargo/glances/issues/951

Currently the "glances --browser" colorizes the entire line of the server based on status. But the ideal is that each item have their own color/highlight independently based on careful/warning/critical configs for each server (and if my #950 suggestion be accept with bells too).

**Comment by nicolargo** [comment]
The Windows [getbkgd](https://docs.python.org/2/library/curses.html#curses.window.getbkgd) of the Curses Lib allows return 0 on my system...

**Comment by alexylem** [comment]
Added +1 on this ticket. I monitor several machines and even if one machine goes critical on CPU or Memory, the whole line remains green.
Another (easier?) option would be to show a Counter(s) of ongoing Careful / Warnings / Critical alerts, as an eye-catcher to drill-down. There could be alerts on metrics not displayed in the browser interface (ex: Network, Ports, ...)

**Comment by nicolargo** [comment]
@alexylem Sorry but we have to refactor the API to make it work... The patch break the compatibility with previous version. 

The change will be implemented in Glances 3.0.

**Comment by nicolargo** [comment]
Merged into develop.

![image](https://github.com/nicolargo/glances/assets/776747/902d0b44-d586-4a00-9588-9f4610f41941)

Please test !
