### ISSUE TITLE
Different data displayed when accessing via WAN?

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#978]
Running Glances on Windows 10U as a service (NSSM)
Python:  3.5 64 Bit

I've noticed that some data don't show up if I access the box from outside my LAN. Is this by design?  Not a big deal, but it's got me scratching my head. 

Box.ip:61028:  http://imgur.com/mxpHMDJ
mysite.com:61208:    http://imgur.com/A2FZJcW

Sick platform. THANKS!

**Comment by nicolargo** [comment]
Nope, it's strange... 

What is the Glances version used on your Windows 10 machine ?

**Comment by seanvree** [comment]
@nicolargo  - 

Glances v2.7.1 with psutil v5.0.0

**Comment by nicolargo** [comment]
Can you flush your browser cache and test again ?

___________________________________________________
*Avant donc que d'écrire, apprenez à penser. -+- Nicolas Boileau, Art
poétique -+-*

2016-12-17 11:17 GMT+01:00 seanvree <notifications@github.com>:

**Comment by seanvree** [comment]
@nicolargo  -  That seemed to have worked.  

I'll close this for now, if I see it happen again, I'll reopen.  

THX
