### ISSUE TITLE
[WebUI] Not working when served from iframe

### ISSUE THREAD

**Issue by alebianco** [nicolargo/glances#980]
#### Description

I'm running glances in web server mode inside a docker container.
There's nginx in front of it with the reverse proxy rules as suggested in the wiki.

Glances' web page is then served in an iframe by [muximux](https://github.com/mescon/Muximux) (just my way of managingall the webservices from one place).

The pages loads blank and throws several errors in the console (logs attached).

##### Cause

Muximux uses a few files with the same name, notably "/js/main.js", so when it's time to load glances' one, the browser tries to be smart and uses the one from the cache, never hitting the rewrite rule and breaking the page.

This will impact any use within in iframe where the main page uses similar names. The chance of having names similar to "/js/main.js" is quite high.

#### Versions

* Glances (glances -V): 2.7.1
* PSutil (glances -V): 5.0.0
* Operating System (lsb_release -a): alpine 3.4 (inside a docker container)

#### Logs

The console errors http://pastebin.com/kBHxb6MF

**Comment by nicolargo** [comment]
Hi @alebianco ,

thanks for the report. Is [the proposed patch](https://github.com/alebianco/glances/commit/52fe3eb85421e0d7953539006a287e0973f0289e) solve your issue ?

**Comment by alebianco** [comment]
Hi,
I'm trying it, i'll submit a pull request if it does.

Do you know if it will cause other issues?
From what i know that is needed by angular to handle the browser location history, but that feature is not used here.
