### ISSUE TITLE
 Glances get's stuck on "landing page" after a browser refresh

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#984]
Running Glances on Windows 10U as a service (NSSM)
Python: 3.5 64 Bit
Glances v2.7.1 with psutil v5.0.0 (running as a windows source via NSSM)

Problem: Glances get's stuck on "landing page" after a browser refresh. 

Have tried firefox and chrome, both do it.

I previously had glances running on python 2.7, but switched to 3.5 64 bit when the issues started. 

Nothing is in the logs.  

Just wondering if there is something simple?  

Thanks!

**Comment by nicolargo** [comment]
Can you try to fully reset your browser cache by hitting CTRL-F5.

**Comment by seanvree** [comment]
@nicolargo   Nope.

**Comment by nicolargo** [comment]
Strange... Can you start Glances in debug mode (-d) and pastebin.com us the
log file?

**Comment by seanvree** [comment]
@nicolargo 

Heres's the debug log file:

http://pastebin.com/8qRf4kpc

I also included a screenshot below.  You'll see the console is reporting data (on the left), but for some reason, it's just not displaying on the browser. 

http://imgur.com/oMLxxxF

**Comment by nicolargo** [comment]
@notFloran : Can you have a look on this issue ? No idea...

**Comment by seanvree** [comment]
@nicolargo  @notFloran  -  Do you guys KNOW that this works on Windows 10 using py3.5 64 bit?  Like I said, I had it working great using py27 32 bit, this only started working when I changed to 35 64 bit.

**Comment by notFloran** [comment]
@seanvree Can you give me the console log of your browser ?

**Comment by seanvree** [comment]
@notFloran - not familiar.  Can you give me where to go to find that?

**Comment by notFloran** [comment]
Go to `http://localhost:61208/`, open the web console (for [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) , for [Chrome](https://developer.chrome.com/devtools/docs/console)) and paste me back the result.

**Comment by seanvree** [comment]
@notFloran , well this is weird, it won't even launch in W mode now, however will launch from a the CLI in non-W mode. 

http://imgur.com/CN3D6dk

**Comment by mrangryoven** [comment]
Having the same issue, i have to keep restarting glances either using the command or the way i currently have it set up using NSSM. As soon as I restart glances it starts working but for about 5-10 mins before it freezes again and then when you refresh it goes to the loading screen.

**Comment by seanvree** [comment]
Yup. Glad to know it's not only me.

**Comment by seanvree** [comment]
@notFloran  - 

Update. so I completely ripped out my python installation and all dependencies and reinstalled. Issue is still there. 

I'm running both Py27 32b and Py37 32b, and it SEEMS to be happening on both? 

i don't think the actual python script is crashing. I think it's the web server aspect. Just an assumption tho.

**Comment by nicolargo** [comment]
@seanvree Can you show us the Web console ? It is the only way to investigate...

On Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
On Chrome: https://developers.google.com/web/tools/chrome-devtools/shortcuts

**Comment by notFloran** [comment]
@nicolargo @seanvree give us a screen of firefox with the console https://i.imgur.com/CN3D6dk.jpg

But I don't understand the problem, it seems that the Glances web server doesn't respond to requests.

@seanvree be careful your glances webui is not protected, anyone can access it

**Comment by mrangryoven** [comment]
@nicolargo https://puu.sh/t93zQ/9847187b41.png Heres what i see, its very much a random time frame, not a set 5 mins and then it will die. It seems to be random but thats what the console says when i try to load glances.

**Comment by seanvree** [comment]
@nicolargo  - Roger, I'm switching to a reverse proxy, just doing some testing right now. 

Here's my screen shot:

http://imgur.com/m4PRuEj

It seems to happen if you close out of the browser then try to go back in.  

Does Glances support multiple instances?  Can I have two browsers connecting to the -w server at one time?

thanks,

**Comment by marzliak** [comment]
Same here with ubuntu 16.

in my case it always start after reboot but after 10 seconds it hangs.

**Comment by seanvree** [comment]
I think I figured it out. 

Are you guys hosting this behind an Apache / IIS server, or otherwise?  @marzliak @mrangryoven ?

**Comment by marzliak** [comment]
Hey @seanvree thanks for the quick reply. I am using nginx

**Comment by mrangryoven** [comment]
@seanvree There is Apache running on the server but its running for PlexPy so its not technically "installed" but is active on the server.

**Comment by seanvree** [comment]
@marzliak @mrangryoven yeah, I'm not familiar with either, but there is no doubt that changing this on my server worked.

**Comment by marzliak** [comment]
@seanvree can you give us more details please?

**Comment by seanvree** [comment]
Honestly, unless you're running IIS, I can't.  I'm good at IIS (which is the MS version of Apache, etc), this was even a bit over my head.  What I gather is that essentially the server doesn't have enough resources to keep sending the data.  

So, in my case, I have A LOT of applications that are being served by my web server (IIS), and I"m assuming those starved Glances WebUI and therefore it crashed.  So, by upping the resources for the IIS applications, that was able to free up resources for the Glances UI.

Again,  This is a big assumption, however, I know it's in the right ball-park. 

I would stand by for the Devs to chime in and see what they think.

**Comment by seanvree** [comment]
Any further development on this?  My problems are back. Such a great tool, but so frustrating to have to restart the server every hour or so.

**Comment by seanvree** [comment]
This has been fixed with the latest Glances version.

Thx for the hard work!
