### ISSUE TITLE
Port in the -c URI

### ISSUE THREAD

**Issue by Amxx** [nicolargo/glances#996]
Hello,

I'm accessing glances on a distance server using `glances -c system.mydomain.com -p 80`.
I'm wondering why it is not possible (and if it could be implemented) to include the port in the domain

The resulting command would be:
`glances -c system.mydomain.com:80`

Thank you

------
Glances v2.7.1 with psutil v5.0.1
Linux Maia 4.9.0-1-ARCH #1 SMP Mon Dec 12 20:18:28 MST 2016 armv7l GNU/Linux

**Comment by nicolargo** [comment]
Chalenge accepted !
![image](https://cloud.githubusercontent.com/assets/776747/21820980/0e1d1eb6-d772-11e6-8c35-9e0f67d43f47.png)

We need to analyse the value of the -c option. If it contains ':', the string should be splitted:

    host, port = value.split(':')

**Comment by Amxx** [comment]
in one line, no need to check for the existence of ":"

`host, port = (x if x else y for (x,y) in zip(value.partition(':')[::2], (host, port)))`

**Comment by nicolargo** [comment]
Done in commit b492220
