### ISSUE TITLE
"String indicies must be integers, not str" error

### ISSUE THREAD

**Issue by tidusjar** [nicolargo/glances#997]
#### Description
After running Glances for some time I am getting the following error (this could be after 3 minutes or 20):

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\glances\__init__.py", line 130, in main
    standalone.serve_forever()
  File "c:\python27\lib\site-packages\glances\standalone.py", line 111, in serve_forever
    return self.__serve_forever()
  File "c:\python27\lib\site-packages\glances\standalone.py", line 96, in __serve_forever
    self.screen.update(self.stats)
  File "c:\python27\lib\site-packages\glances\outputs\glances_curses.py", line 1018, in update
    self.flush(stats, cs_status=cs_status)
  File "c:\python27\lib\site-packages\glances\outputs\glances_curses.py", line 996, in flush
    self.display(stats, cs_status=cs_status)
  File "c:\python27\lib\site-packages\glances\outputs\glances_curses.py", line 541, in display
    args=self.args, max_width=plugin_max_width)
  File "c:\python27\lib\site-packages\glances\plugins\glances_plugin.py", line 631, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "c:\python27\lib\site-packages\glances\plugins\glances_network.py", line 281, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers, not str
```
Running it via: `Glances glances --export-influxdb --config glances.conf --disable-load --disable-ip`

#### Versions

* Glances (glances -V): Glances v2.7.1
* PSutil (glances -V): psutil v5.0.1
* Operating System (lsb_release -a): Windows 10 64bit

#### Logs

http://pastebin.com/vLthvZmp

Can't find anything of interest in the logs.

**Comment by tidusjar** [comment]
Further information, added `--disable-network` and I got the same error back but in `glances_disk.py`

**Comment by SvenBrunk** [comment]
yes... have similar things with --export-rabbitmq... (maybe have a look at #931 )
Using the develop branch gives me another error. Now in glances_export.py

**Comment by nicolargo** [comment]
Hi @tidusjar 

Can you please start Glances in debug mode --d) and send us back the glances.log file when it bugs ?

Thanks

**Comment by tidusjar** [comment]
I'll post it tonight! 😄 
Thanks for the assistance

**Comment by tidusjar** [comment]
It's not crashed yet... Strange, before it was crashing pretty consistent, since then the only thing that has changed is that I have restarted my server!

**Comment by nicolargo** [comment]
Let the bug open. Stay in tune.
Please came back if needed...

**Comment by tidusjar** [comment]
It has started crashing again. I'll see if I can update the logs tonight

**Comment by tidusjar** [comment]
Where does the log file get generated?

**Comment by tidusjar** [comment]
Did this help you @nicolargo  ?

Can I provide any more information?

**Comment by nicolargo** [comment]
@tidusjar You need to wait for Glances 2.8.3 or use the DEVELOP branch...

Hope to release Glances 2.8.3 this week-end.

**Comment by tidusjar** [comment]
Is there a guide anywhere how to run Glances devlop branch?

**Comment by nicolargo** [comment]
Yes, have a look on the Wiki

**Comment by nicolargo** [comment]
@tidusjar You can try with the latest Glances version (2.8.5).

**Comment by tidusjar** [comment]
I've been trying, apologies but i'm a complete idiot when it comes to anything other than windows.

I'm just getting the following
![image](https://cloud.githubusercontent.com/assets/6642220/23818106/304a61ea-05f0-11e7-9253-3437b308cc2f.png)

**Comment by nicolargo** [comment]
@tidusjar  Please also upgrade your PSUtil version to 5.2.0 or higher:

    pip install --upgrade psutil
