### ISSUE TITLE
'Process' object has no attribute 'io_counters' on Solaris

### ISSUE THREAD

**Issue by redno2** [nicolargo/glances#998]
#### Description
Installed glances with pip install glances on solaris 10.
Python 2.7 and pip installed by pkgutil from source of https://www.opencsw.org

When I run : /opt/csw/bin/glances I've got this error :
Traceback (most recent call last):
  File "/opt/csw/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.7.1', 'console_scripts', 'glances')()
  File "/opt/csw/lib/python2.7/site-packages/glances/__init__.py", line 127, in main
    args=core.get_args())
  File "/opt/csw/lib/python2.7/site-packages/glances/standalone.py", line 68, in __init__
    self.stats.update()
  File "/opt/csw/lib/python2.7/site-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/opt/csw/lib/python2.7/site-packages/glances/plugins/glances_processcount.py", line 57, in update
    glances_processes.update()
  File "/opt/csw/lib/python2.7/site-packages/glances/processes.py", line 402, in update
    standard_stats=self.max_processes is None)
  File "/opt/csw/lib/python2.7/site-packages/glances/processes.py", line 367, in __get_process_stats
    procstat = self.__get_mandatory_stats(proc, procstat)
  File "/opt/csw/lib/python2.7/site-packages/glances/processes.py", line 205, in __get_mandatory_stats
    proc_io = proc.io_counters()
AttributeError: 'Process' object has no attribute 'io_counters'

#### Versions
Glances v2.7.1 with psutil v3.2.2
Python 2.7.11

/opt/csw/bin/pip list        
Glances (2.7.1)
pip (8.1.2)
psutil (3.2.2)
setuptools (28.8.0.post20161114)

Oracle Solaris 10 1/13 s10x_u11wos_24a X86

Thank you.

**Comment by nicolargo** [comment]
Bug confirmed...

Reason ? As said in the PsUtil documentation:

```
io_counters()

    Return process I/O statistics as a namedtuple including the number of read and write operations performed by the process and the amount of bytes read and written. For Linux refer to /proc filesysem documentation. On BSD there’s apparently no way to retrieve bytes counters, hence -1 is returned for read_bytes and write_bytes fields. OSX is not supported.

    >>> import psutil
    >>> p = psutil.Process()
    >>> p.io_counters()
    pio(read_count=454556, write_count=3456, read_bytes=110592, write_bytes=0)

    Availability: all platforms except OSX and **Solaris**
```

@redno2 can you send us the result of the following commands:

```
# python
> import sys
> sys.platform
```

Thanks in advance !

```

**Comment by giampaolo** [comment]
@nicolargo `psutil.SUNOS` will be `True` if you're on Solaris

**Comment by redno2** [comment]
>>> sys.platform
'sunos5'

Thanks !

**Comment by nicolargo** [comment]
@redno2 Should be corrected by the @asergi patch: https://github.com/nicolargo/glances/commit/7740f588dea865534754e8f0177ab4af9a2f49a0

**Comment by nicolargo** [comment]
Test done: https://github.com/nicolargo/glances/commit/7740f588dea865534754e8f0177ab4af9a2f49a0#commitcomment-20563296
