### ISSUE TITLE
Crash when press e at shell for interactive command on MacOS

### ISSUE THREAD

**Issue by dayuoba** [nicolargo/glances#999]
Before filling this issue, please read the manual (https://glances.readthedocs.io/en/latest/) and search if the bug do not already exists in the database (https://github.com/nicolargo/glances/issues).

#### Description

start glances by type glances at shell
then press `e` for interactive command
then it crashes
![image](https://cloud.githubusercontent.com/assets/9914235/22059231/e7b6d4f2-dda6-11e6-9824-ddfbe864bb97.png)

#### Versions

* Glances (glances -V):
 v2.7.1 

* PSutil (glances -V):
v5.0.1
* Operating System (lsb_release -a):
MacOS 10.12.2
#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by cuiweiqiang** [comment]
I have same issue.

**Comment by asergi** [comment]
This is probably fixed in develop now. Please test it again.

**Comment by cuiweiqiang** [comment]
@asergi it worked ! God job !
